### ISSUE TITLE
Validators should throw an exception when async rules are executed synchronously

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1063]
At the moment if a validator contains async rules and is executed with `Validate`, all the rules will be silently be executed synchronously instead. This is not good behaviour. 

2 Options:

1) Change the default behaviour for 9.0 so that this generates an exception, forcing `ValidateAsync` to be called instead. This should be an opt-out behaviour so the current behaviour can be maintained (controllable by a switch which should generate a warning). This is the easiest change, but generates a runtime error which is non-obvious. 

2) Remove all async methods from `AbstractValidator`, and instead have an explicit `AsyncAbstractValidator`. This is a very large piece of work, and is a bigger breaking change for users too. But this will be a compile time error, so much easier to spot.

**Comment by treg** [comment]
Option 2

**Comment by JeremySkinner** [comment]
Ideally option 2 would be better. But that is essentially a complete rewrite and I’m not sure I’d have the time (or inclination) to do that.

**Comment by jzabroski** [comment]
How would this surface to the user?  Ideally, an input would be yellow for promises (TaskCompletionSource<T>).

I think that people don't actually want to return `Tasks` as Rule outcomes, but `TaskCompletionSource<T>`.  In effect this is like a WPF RelayCommand pattern where you first return an intermediate state while you wait for a final result.  In practical terms, this would be like drawing a yellow/inconclusive UI affordance around a text box while you await the outcome of a rule.

**Comment by JeremySkinner** [comment]
In exactly the same way as now. In the async validator, methods such as MustAsync/CustomAsync etc would be available. In the non-async validator they wouldn’t.

**Comment by nsarris** [comment]
There are two conserns with calling async on a sync flow. 

1. Deadlocks
2. Obscuring thread blocking in an async flow

The first one can be avoided easily. If you followed Stephen Cleary's work and his AsyncEx library he has tackled that issue extensively. I don't want to go into details but you can read more about it here: https://msdn.microsoft.com/en-us/magazine/mt238404.aspx

The jist of it is that you can safely block that awaiter on the thread pool like this (simplified):

Task.Run(() => AwaitableMethodAsync()).GetAwaiter().GetResult();

This works without issues if your awaitable method doesn't depend on a synchronization context, so basicly if the async method doesn't access any WinForms/WPF controls or the ASP.NET HttpContext you shouldn't have any issues. Personally I don't see any reason why a programmer would need anything related to any kind of synchonization context within a validator rule. I've been using this in production code for years without any issues.

The second issue I believe is outside the scope of the library itself. If someone mixes sync and async rules in their code and then goes on to invoke them synchronously they should now what they are doing.

So I would propose to use this way of calling an async method within a sync flow. I would just add a disclaimer in the documentation to advise against actually using it, but I believe it's safe enough.

**Comment by JeremySkinner** [comment]
@nsarris FluentValidation already does exactly this. The aim of this work is to *remove the ambiguity* caused in situations where asynchronous rules are executed synchronously when the developer did not intend this.

**Comment by JeremySkinner** [comment]
Moving this out of the 9.0 release.

**Comment by JeremySkinner** [comment]
Superceded by #1481
