### ISSUE TITLE
Default display name splitting should handle properties containing periods

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1147]
`RuleFor(x => x.Address.Line1)` generates a display name of "Address. Line1" instead of "Address Line1".

**Comment by SeanKilleen** [comment]
I thought I'd pick this up as a way of knocking something out. 

Is this still the case? I tried to write some failing tests in `PropertyChainTests` and a generic validation test against `Address.Line1` that checked the PropertyName, but I can't seem to recreate this behavior.

**Comment by JeremySkinner** [comment]
It’s the display name that’s affected (ie the split version that appears inside the {PropertyName} error message template), not the actual value of PropertyName itself. I don’t have the availability to put together a failing test case atm but essentially I believe it’s reproducible with something like `RuleFor(x => x.Address.Line1).NotNull().WithMessage("{PropertyName}")`


...and then check the full error message

**Comment by JeremySkinner** [comment]
Also this is extremely low priority as typically you’d specify an overridden display name by calling WithName in this scenario anyway. 

If you want to dive in then the documentation updates would be higher priority as I need to get those done before I can release 9.0

**Comment by Frueber** [comment]
@JeremySkinner , I put together [something quick](https://github.com/FluentValidation/FluentValidation/pull/1638) for this that I hope gets us closer to a fix for this issue.
Let me know your thoughts, and if I messed something up with creating a PR to this project as well ;).

**Comment by JeremySkinner** [comment]
Merged for 10.0
