### ISSUE TITLE
Make ValidateAndThrowAsync as virtual method in AbstractValidator

### ISSUE THREAD

**Issue by hichemaichour** [FluentValidation/FluentValidation#1162]
### System Details

- FluentValidation version: 8.4

### Issue Description

It would be great if `ValidateAndThrowAsync` is actually a virtual method in `AbstractValidator` so that we can overload it and throw the errors that we want.

**Comment by hichemaichour** [comment]
Note: We want to throw errors based on `Severity` and/or `ErrorCode`

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. This would be a breaking change so it this isn't something that'd be included for the current 8.x releases but I'll have a think about doign this for 9.0. For now I'd suggest adding your own extension method to do this.

**Comment by JeremySkinner** [comment]
Apologies for taking so long to get to this. 

This is being visited as part of #1467, where we're consolidating all the different overloads of Validate/ValidateAsync. 

`ValidateAndThrow` will still be an extension method, but it will internally translate to the following:

```csharp
validator.Validate(instance, options => {
  options.ThrowOnFailures();
});
```

The logic for handling the `ThrowOnFailures` option will live in a new virtual `RaiseValidationException` method inside `AbstractValidator`. You'll be able to override to customize the behaviour.

**Comment by JeremySkinner** [comment]
FluentValidation 9.1 is now available on nuget with this change.
