### ISSUE TITLE
[Docs] Lifetime scope of validators

### ISSUE THREAD

**Issue by lonix1** [FluentValidation/FluentValidation#1187]
I wanted to know whether validators are registered as transient/singleton/etc. for ASP.NET Core, when using `RegisterValidatorsFromAssemblyContaining`.

Took me a while to [locate the info](https://github.com/JeremySkinner/FluentValidation/issues/814#issuecomment-409804386), they are in fact transient.

Would be nice to have that mentioned in the IoC section [here](https://fluentvalidation.net/aspnet#asp-net-core).

**Comment by JeremySkinner** [comment]
Docs updated
