### ISSUE TITLE
[Docs] [Improvement] Customer Model under Collection

### ISSUE THREAD

**Issue by coolhome** [FluentValidation/FluentValidation#1211]
![image](https://user-images.githubusercontent.com/700740/63104940-de088c80-bf4d-11e9-9cc0-286bbcb8c9f0.png)
I think the `Collection` section could be improved. Under the `Collection` section I would expect all code references to revolve around `Person`. This section currently references both `Person` and `Customer`. `Customer` is actually introduced with a code snippet under `Collections of Complex Objects` which is after the `Collection` section.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. Please feel free to submit a pull request to clean it up, otherwise I’ll try and get to it sometime when I have some availability.

**Comment by Jacksondr5** [comment]
@JeremySkinner any desire to see a PR on this?  I think the examples shown should be moved under the Complex Types section, since I'm struggling to find an example that shows their usefulness and uses simple types.

**Comment by JeremySkinner** [comment]
Hi, yes this issue is awaiting someone to submit a PR
