### ISSUE TITLE
Feature Suggestion: Add Source Link to all nuget packages

### ISSUE THREAD

**Issue by PureKrome** [FluentValidation/FluentValidation#1219]
Hi @JeremySkinner 👋 

Could we get Source Link included into the nuget packages so we can debug into them, if required.

REF: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

Sample scenario: I'm trying to debug why my validator isn't returning a validation error in a test (which is should be doing) but the `OnFailure` is getting called ... so then I can see what's going on.

**Comment by JeremySkinner** [comment]
Thanks, yes that would be nice to get in. Do you know if there's any specific setup that needs to be done to handle multiple packages being in the same repo (like FV is?) I couldn't see any mention of that

**Comment by PureKrome** [comment]
🤔 Hmm... I've actually never used SourceLink with multi-targeted libraries ... just `NS20` -or- multiple packages in the same repo. My gut feeling is that having multiple packages in the same repo shouldn't be a problem because it all refers back to a single repo AND specific paths inside that repo.

But I don't see why multiple packages should be an issue. The changes are on the `.csproj` level, which could be a file located anywhere in the repo.

**Comment by ChaseFlorell** [comment]
I'm personally not familiar with "Source Link", but here's an example of how I add a PDB package with each of my nugets

https://github.com/ChaseFlorell/FutureFlag/blob/development/src/Directory.Build.props#L18

**Comment by JeremySkinner** [comment]
These are very different things. We already provide [embedded debugging symbols](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/FluentValidation.csproj#L93). 

This feature request was specifically for sourcelink integration.

**Comment by JeremySkinner** [comment]
Added for 9.0
