### ISSUE TITLE
Request: Add ObjectInstance to ValidationFailure

### ISSUE THREAD

**Issue by mrpmorris** [FluentValidation/FluentValidation#1236]
The Microsoft Blazor front-end uses an ObjectInstance/PropertyName combination to identify errors, whereas FluentValidation uses a RootObject/PathToProperty.

Could we have some way of retrieving the actual object + property name (rather than path)?

For example. A ValidationFailure for Person.HomeAddress.City would give us
`object Person.HomeAddress, string "City"`

Take a look here for more information in a blog by Steve Sanderson - https://chrissainty.com/using-fluentvalidation-for-forms-validation-in-razor-components/

I'd be happy to submit a PR if you are open to the idea of this improvement and would like to discuss an approach you are happy with?

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, yes I’m certainly open to this if it makes Blazor integration easier. I’m not very familiar with blazor myself, but if you wanted to put together a PR that provides an initial implementation then I’d be happy to review it and go from there. Thanks!

**Comment by mrpmorris** [comment]
Hi @JeremySkinner 

In a rule such as `RuleFor(person => person.Address.Id)` we need to be able to get the instance of Address and the string "Id".

Same for `RuleFor(person => person.Address).SetValidator(new AddressValidator());`

All we need is a way to get a property name (without a path) and the object reference to the property's direct owning object instance.

There's really nothing more to it than that for it to be Blazor compliant. I'll have a crack at it if you'd like me to, but I suspect you'd be able to implement it before me :)

**Comment by JeremySkinner** [comment]
> In a rule such as RuleFor(person => person.Address.Id) we need to be able to get the instance of Address and the string "Id".

Extracting the "Id" string is easy enough, but we never directly have a reference to the Address in a rule like this - we only ever receive the result of invoking the lambda expression (so you'd get back a reference to the Id property).

The only way you'd ever get a reference to the Address is if the rule is defined on the Address property itself and use a child validator (as with your second example). When you do this, you'd be able to override the `Validate` method on the AddressValidator and post-process the validation failures to get the information you need.

**Comment by mrpmorris** [comment]
Hi Jeremy

If you have an Expression<Func<T>> you can get a reference to the object as well as the property name using this approach in Blazor - https://github.com/aspnet/AspNetCore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/Components/Forms/src/FieldIdentifier.cs#L82

Usage example
```
			var person = new Person();
			Expression<Func<string>> propertyExpression = () => person.Address.Country.Code;
			ParseAccessor(propertyExpression, out object model, out string fieldName);
```

**Comment by JeremySkinner** [comment]
Yes, although this creates and compiles a new expression which adds significant overhead. FluentValidation's rule expressions are compiled and executed only once and then the result is cached to lower this significantly. Adding additional expression tree compilation absolutely needs to be avoided unless caching can be introduced.

**Comment by mrpmorris** [comment]
The Blazor code is slightly different, because it is an `Expression<Func<TResult>>` it has to compile every time, whereas FluentValidation uses `Expression<Func<TSource, TResult>>` so you can compile the func once and keep it.

```
using System;
using System.Linq.Expressions;
namespace ConsoleApp12
{
    class Program
    {
        public static object Assert { get; private set; }
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Expression<Func<Person, string>> propertyExpression = p => p.Address.Country.Code;
            ParseAccessor(propertyExpression, out Func<Person, object> getModelFunc, out string fieldName);

            Console.WriteLine("Member name is " + fieldName);
            var person1 = new Person();
            var result1 = getModelFunc(person1);
            if (result1 != person1.Address.Country)
                throw new InvalidOperationException();

            var person2 = new Person();
            var result2 = getModelFunc(person2);
            if (result2 != person2.Address.Country)
                throw new InvalidOperationException();
        }
        private static void ParseAccessor<TSource, TProperty>(Expression<Func<TSource, TProperty>> accessor, out Func<TSource, object> getModelFunc, out string fieldName)
        {
            var accessorBody = accessor.Body;

            // Unwrap casts to object
            if (accessorBody is UnaryExpression unaryExpression
                && unaryExpression.NodeType == ExpressionType.Convert
                && unaryExpression.Type == typeof(object))
            {
                accessorBody = unaryExpression.Operand;
            }

            if (!(accessorBody is MemberExpression memberExpression))
            {
                throw new ArgumentException($"The provided expression contains a {accessorBody.GetType().Name} which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.");
            }

            // Identify the field name. We don't mind whether it's a property or field, or even something else.
            fieldName = memberExpression.Member.Name;

            // Get a reference to the model object
            // i.e., given an value like "(something).MemberName", determine the runtime value of "(something)",
            switch (memberExpression.Expression)
            {
                case ConstantExpression constantExpression:
                    getModelFunc = x => constantExpression.Value;
                    break;
                default:
                    // It would be great to cache this somehow, but it's unclear there's a reasonable way to do
                    // so, given that it embeds captured values such as "this". We could consider special-casing
                    // for "() => something.Member" and building a cache keyed by "something.GetType()" with values
                    // of type Func<object, object> so we can cheaply map from "something" to "something.Member".
                    var modelLambda = Expression.Lambda(memberExpression.Expression, accessor.Parameters);
                    var modelLambdaCompiled = (Func<TSource, object>)modelLambda.Compile();
                    getModelFunc = modelLambdaCompiled;
                    break;
            }
        }
        public class Country
        {
            public string Code { get; set; }
        }
        public class Address
        {
            public Country Country { get; set; } = new Country { Code = "GB" };
        }
        public class Person
        {
            public Address Address { get; set; } = new Address();
        }
    }
}
```

Note that the code is a modified version of the Blazor code, so you might need to consider copyright / ask permission etc.

**Comment by andoband** [comment]
Maybe I'm missing something, but couldn't this be solved in large part by adding a `ValidatedInstance` prop to `ValidationFailure` and set it when creating the failure, [for example in a PropertyValidator](https://github.com/JeremySkinner/FluentValidation/blob/24aaddb4b00e3563e8d03fd6edd06f487e207e8a/src/FluentValidation/Validators/PropertyValidator.cs#L98)?

**Comment by mrpmorris** [comment]
@andoband The difficulty is when your validation expression is `person => person.Address.Country.Code` it is easy to get `person` and it is easy to get the value of `Code`, but what we need is a reference to the owner of the `Code` - i.e. the `Country`.

**Comment by andoband** [comment]
@mrpmorris I didn't realize FluentValidation would even let you specify a nested property!  I've always used child validators.....and now I see you made the distinction in a comment above.  Sorry about that.

Another option...we would need FluentValidation to include, in `ValidationFailure`, both the validation expression (`PropertyValidator.Expression`) and the instance to validate ('PropertyValidatorContext.InstanceToValidate'). Then a FluentValidator component in Blazor could be responsible for pulling out the parent part of the expression, compiling and caching it, and then invoking it on the object instance that was passed with the failure in order to get the parent instance.

**Comment by mrpmorris** [comment]
@andoband Yes, I think that would do the trick.

**Comment by JeremySkinner** [comment]
Yes I think I prefer that approach, as it means handling the expression becomes the responsibility of the integration component rather than core FV. The only thing to consider is ValidationFailure is supposed to be easily serializable...without trying it I’m not sure how easily serializable expression trees are.

**Comment by andoband** [comment]
For the Blazor scenario I don't see a deserialized expression or the instance even working, so I think they could be marked as not serializable.  Plus there's always the path just in case.

**Comment by mrpmorris** [comment]
You could make them private fields and expose them via functions.

**Comment by mrpmorris** [comment]
@JeremySkinner How do you feel about making the expression available via a method from the RuleViolation? Perhaps the RuleViolation could have access to the Rule Definition itself via a method and we could get the Expression from that?

**Comment by JeremySkinner** [comment]
Yes I think exposing the rule via a method should be fine.

**Comment by mrpmorris** [comment]
Excellent, I think that's all we'll need. Thanks!

**Comment by JeremySkinner** [comment]
- [ ] Update `PropertyValidator` to pass the parent rule instance to the `ValidationFailure`
- [ ] Need to decide how to handle `Custom` validators where the user can create the `ValidationFailure` instance directly.
- [ ] Ensure there are tests in place to ensure serialization isn't affected

**Comment by JeremySkinner** [comment]
I'm going to go ahead and close this issue as there hasn't been any activity movement on it for nearly a year. If this is still something you'd like to have included in the project then please feel free to re-open the issue and submit a PR.
