### ISSUE TITLE
RuleForEach doesn't allow to set specific validator for child array item

### ISSUE THREAD

**Issue by IlyaUhlianitsa** [FluentValidation/FluentValidation#1309]
Hi @JeremySkinner,
I use FluentValidation in all projects and really like this tool - thanks!
And now I have trouble. Imagine my API gets information about houses to create.

    public class House
    {
        public IEnumerable<Room> Rooms { get; set; }

        // some properties
    }

    public class Room
    {
        public RoomType RoomType { get; set; }

        // some properties
    }

    public enum RoomType
    {
        Bedroom,
        Kitchen,
        Bathroom
    }

I have `HouseValidator` which validates some properties of `House`. Also, I want to set the various validators for `Rooms` array depend on `RoomType`. Each validator will validate properties in a different way.

    RuleForEach(x => x.Rooms)
        .SetValidator(room => roomFactory.Create(room.RoomType));

But unfortunately, I can't because `room` is the parent instance `House`, not child `Room`. It seems a little strange to me. Correct me if I do something wrong, please.

My environment is:
FluentValidation.AspNetCore 8.6.1 
.Net Core 3.1

**Comment by JeremySkinner** [comment]
Hi, `SetValidator` always receives a reference to the parent object that's being validated. I appreciate it's a bit strange in the case of `RuleForEach`. I think that this can be solved with an extra overload of `SetValidator` that takes an additional parameter in the callback. Then you could do:

```csharp
RuleForEach(x => x.Rooms)
  .SetValidator((house, room) => roomFactory.Create(room.RoomType));
```

I can look at getting this added for a future version. For now you can include an extension method in your own project:

```csharp
public static IRuleBuilderOptions<T, TProperty> SetValidator<T, TProperty, TValidator>(this IRuleBuilder<T, TProperty> rule, Func<T, TProperty, TValidator> validatorProvider, params string[] ruleSets) 
	where TValidator : IValidator<TProperty> {
	
	return rule.SetValidator(new ChildValidatorAdaptor(context => validatorProvider((T) context.InstanceToValidate, (TProperty) context.PropertyValue), typeof (TValidator)) {
		RuleSets = ruleSets
	});
}
```

This is a naive implementation as it doesn't handle null checks of `TProperty` which will need a bit of work, but should work OK for simple cases.

**Comment by IlyaUhlianitsa** [comment]
Brilliant, it works!
Thank a lot Jeremy!

**Comment by JeremySkinner** [comment]
Great, glad it works. I'm going to re-open this for now to track development for inclusion in core

**Comment by JeremySkinner** [comment]
Added in 3060c48f3f1d2ca5adbe2d082ab27a205f5ccc0b. This will be in the 9.0 release.
