### ISSUE TITLE
Unexpected behavior of validator from SetValidator. 

### ISSUE THREAD

**Issue by SowaSS** [FluentValidation/FluentValidation#1330]
### System Details

- FluentValidation version: 8.6.1 
- Web Framework version: .NET Core 3.1

### Issue Description
Hello, 
I could not find any information about the issue I have faced last time.

I wanted to check with validator if the object is not null, so I made use of overriding method ``Validate`` and simply check if the ``InstanceToValidate`` from the context is not null, if it is null then I return ``ValidationFailure``, otherwise I run validation further. It is working perfectly when the validator is used straightforward. But when I use this validator as an argument to ``SetValidator`` then it is not working as expected, it returns that validation passed successfully event when a validated object is null.

Let me show it on an example:

I have ModelValidator which firstly validate if the model is not null by overriding ``Validate`` method:
```c#
public class ModelValidator : AbstractValidator<Model>
{
    public ModelValidator()
    {
        RuleFor(model => model.Text)
            .MinimumLength(3);
    }
    
    public override ValidationResult Validate(ValidationContext<Model> context)
    {
        if (context.InstanceToValidate == null)
        {
            return new ValidationResult(new []
            {
                new ValidationFailure(nameof(Model), "Model cannot be null.")
            });
        }
        return base.Validate(context);
    }
}
```

And ExtendedModelValidator which simply SetValidator for property Model in ExtendedModel.

```c#
public class ExtendedModelValidator : AbstractValidator<ExtendedModel>
{
    public ExtendedModelValidator(ModelValidator modelValidator)
    {
        RuleFor(extendedModel => extendedModel.Model)
            .SetValidator(modelValidator);
    }
}
```

Both model classes look pretty simple:
```c#
public class Model
{
    public string Text { get; set; }
}
public class ExtendedModel
{
    public Model Model { get; set; }
}
```

And tests to clarify where the problem is:
```c#
[Test]
public void ShouldReturnNotValidWhenModelIsNull()
{
    //GIVEN
    Model model = null;

    var validator = new ModelValidator();

    //WHEN
    var result = validator.Validate(model);

    //THEN
    Assert.That(result.IsValid, Is.False);
}

[Test]
public void ShouldReturnNotValidWhenModelInExtendedModelIsNull()
{
    //GIVEN
    var extendedModel = new ExtendedModel()
    {
        Model = null
    };

    var extendedValidator = new ExtendedModelValidator(new ModelValidator());

    //WHEN
    var result = extendedValidator.Validate(extendedModel);

    //THEN
    Assert.That(result.IsValid, Is.False); //It fails here, IsValid is True
}
```
The first test runs successfully, while the second test fails. Validator is classifying that ``extendedModel`` as a fully valid object.

Is it expected behaviour?

**Comment by JeremySkinner** [comment]
Hi, yes that's the expected behaviour.

Child validators set with `SetValidator` will not be invoked if the property is null - [see the documentation](https://docs.fluentvalidation.net/en/latest/start.html#complex-properties)

Overriding `Validate` the way that you're doing is only useful for generating error for the *root level model*. 

For child properties, you need to explicitly define a NotNull rule inside the parent validator, like this:

```csharp
   RuleFor(extendedModel => extendedModel.Model)
            .SetValidator(modelValidator)
            .NotNull().WithMessage("Model cannot be null");
```

**Comment by SowaSS** [comment]
Hi Jeremy,

Thank you for clarifying and pointing documentation with it. 
It makes sense.

Best regards
