### ISSUE TITLE
Rule overriding or alternative for hierarchical viewmodels scenario

### ISSUE THREAD

**Issue by G3Kappa** [FluentValidation/FluentValidation#1331]
### System Details

- FluentValidation version: 9.0.0-preview1
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 3.1

### Issue Description

I have a somewhat uncommon scenario, where the entire ASP.NET application is built on top of a custom multitenancy framework. This makes it possible for controllers, services and even models to be used hierarchically. For instance, **if** tenant "X" does **not** have a _custom_ `CustomisedExpenseService` for their `DerivedExpenseModel`, then they will default to using a regular `ExpenseService` that expects a regular `ExpenseModel`.

We tried two approaches as far as FluentValidation is concerned: composition and inheritance. The former proves problematic due to the way Dependency Injection is handled either by ASP.NET or by DryIoC. It's totally possible, but it's also a bit cumbersome. The latter is the latest take on the problem; here's how it works:

You have a base `BaseValidator<TModel>` with an empty ruleset, which is the default validator for models that don't explicitly declare a custom validator. It's fundamentally just a wrapper of `AbstractValidator<TModel>` with a couple helpers thrown in. Then you have several `DefaultValidator<TModel> : BaseValidator<TModel> where TModel : MyModel` which (expectedly) validate `TModel` instances according to the business logic requirements. This means that if you don't care to validate a particular model, the DI framework will default to using an empty `BaseValidator`, and if you write a default validator, then the DI framework will seamlessly switch to the default validator.

Now for the actual problem: when a tenant, such as tenant "X" from earlier, wants to provide a custom service (as in a customisation of a default service, such as their own implementation of an `ExpenseService`), they will write it such that it expects a `TDerivedModel : TModel`. This is because the underlying domain objects are still the same, but tenants are allowed to add new properties to the schema, and thus to their own derived models, and use them as they see fit.

So far so good. We write a derived validator that inherits the default validator, and add custom validation logic there. But what if a tenant wants to _modify_ the previously established validation rules?

One possible approach would be to make each rule its own method, which is similar to using PropertyValidators. But this is also rather cumbersome because you have to make each individual rule into a virtual method, and that doesn't sound fun nor easy to automate. I understand that the validation graph is built once during initialization, but it would be really great if there was a way to simply drop a rule for a given property and rewrite it from scratch. I understand this might not be the intended usage of FluentValidator, but it is definitely the least-effort-required implementation I could come up with as far as "eventual" customisation is concerned. One of our main goals is that customisation should be as painless as possible, because we're expecting our tenants to diverge significantly based on the previous incarnation of this same project.

If you have any useful pointers as to how to handle this scenario, I would be extremely grateful. Likewise, if a concrete code example is needed I'll provide one.

Thank you for working on such an awesome tool!

**Comment by JeremySkinner** [comment]
Hi,

> But what if a tenant wants to modify the previously established validation rules?

The normal way of switching rules on/off dependent on context is [rulesets](https://docs.fluentvalidation.net/en/latest/rulesets.html), combined with composition (not inheritance) but from what you've said I'm guessing this is not granular enough for you?

Modifying/removing rules is definitely not something that we support as this would completely break the thread safety of validators (which are designed to be immutable once constructed). What you *could* do is generate a condition (equivalent of calling `When`) on every rule that checks if the property name is not in a list of properties to bypass. Something like this hopefully illustrates the point:

```csharp
public class BasePersonValidator : AbstractValidator<Person> {
	private List<string> _switchOff = new List<string>();

	protected void SwitchOff(string tag) {
		_switchOff.Add(tag);
	}

	public BasePersonValidator() {
		RuleFor(x => x.Surname).NotNull();
		RuleFor(x => x.Forename).NotNull();

		// Loop over every rule and apply a condition to all of its validators.
		// The condition checks that the property name associated with the rule is not in the "Switch off" list.
		// This is the equivalent of calling the following for every rule:
		// RuleFor(x => x.Forename).NotNull().When(x => !_switchOff.Contains("Forename"));
		foreach (var rule in this) {
			rule.ApplyCondition(context => !_switchOff.Contains(context.PropertyName));
		}
	}

}

public class DerivedPersonValidator : BasePersonValidator {
	public DerivedPersonValidator() {
		SwitchOff("Surname");
                
                // Base class's "Surname" rule will be switched off, so now we can can add one here. 
		RuleFor(x => x.Surname).NotEqual("foo");
	}
}
```

**Comment by G3Kappa** [comment]
Hey, thank you for replying so fast! Just the time for a bathroom break lol.

That sounds like a really nice and concise idea. I would rather work with expressions than strings, but I think I can manage that on my end. I'd just like to make sure that my code ends up producing the correct strings as a result without asking the user (i.e. future me or future team members) to hardcode them or to abuse `nameof` which can be irksome when it comes to nested properties. I assume you're just extrapolating them from the expression graph?

Either way, I'm not trying to map anything at runtime: my overrides would ONLY take place at construction time, because the DI container is responsible for producing validators (which have a Scoped lifetime, as opposed I think to the default lifetime being Singleton; we do a couple unorthodox things here and there to tie the multitenancy together) so it would still happen before the ruleset is actually built. So what I'm asking is for rules to be removed form the ruleset _builder_, not from the ruleset itself. But then again, if this is not possible then I'm perfectly happy to follow your advice.

**Comment by JeremySkinner** [comment]
>  I assume you're just extrapolating them from the expression graph?

Yes, it just parses the expression tree. 

> So what I'm asking is for rules to be removed form the ruleset builder, not from the ruleset itself

There isn’t actually a distinction. The rule is added to the list of rules to execute at the point RuleFor is called. 

I think this approach is probably going to be the best way to do what you’re after

**Comment by G3Kappa** [comment]
Alright, I see. Thank you very much!

I think I can achieve a good level of flexibility with your solution, since the validators are also configurable via the IOptions<> pattern. I expect most rules to be manageable that way, but I wanted to get a good idea of the available options first, in order not to code myself into a corner down the road.

Cheers!
