### ISSUE TITLE
Retrieving Validation Error for Collection Item 

### ISSUE THREAD

**Issue by BhuvanViswanTrinity** [FluentValidation/FluentValidation#1335]
### System Details

- FluentValidation version 8.6.1: 
- Web Framework version ( WebApi.Core 3.1.):

### Issue Description

I have Address object
public class Address
{
public int AddressId { get; set; }
public int StreetNumber { get; set; }
public string StreetName1{ get; set; }
public string City{ get; set; }
public string State { get; set; }
public int ZipCode{ get; set; }
}

How do I get the Validation Error for specific item of Address.
I have AddressPostRequest Validator which validates automatically before it hits the controller method. So that I do not have to do a explicit Validator.Validate
I also have AddressItemValidator something like this
RuleFor(p => p).SetValidator(new AddressValidator());

lets say I have 10 address for coming in the post and I need to print for this validation errors for every single address separately lets say

Address ID 1 has following errors

a. Invalid Zip Code, Invalid State

Address Id 2 has following errors
b. Invalid Street Number, Invalid City

Address Id 3 has following errors
b. Invalid Zip Code

how do I get the Validatoin REsult with respect to specific Address collection Item?

**Comment by JeremySkinner** [comment]
Hi, in the validation results collection each validation failure is keyed by a full property path which will be a string such as "Address[0].ZipCode" etc. You'd need to extract the index from this to tie it back to your collection.

**Comment by BhuvanViswanTrinity** [comment]
sweet, How did I miss that? That was clean. Thank you so much 👍
