### ISSUE TITLE
ValidationException ctor which utilize both given message and BuildErrorMessage method

### ISSUE THREAD

**Issue by bombek92** [FluentValidation/FluentValidation#1337]
for reference:
https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation/ValidationException.cs

Currently I can either 
get the **BuildErrorMessage(errors)** as the exception message by using public ValidationException(IEnumerable<ValidationFailure> errors) constructor 
or pass my **own message** with public ValidationException(string message, IEnumerable<ValidationFailure> errors) constructor.

What I'm missing is combination e.g. to set Exception.Message as
$"{message} {BuildErrorMessage(errors)}".

I can propose a PR for this improvment.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, yes that sounds like a reasonable imporvement. Please feel free to submit a PR and I'll give it a review.

**Comment by bombek92** [comment]
I created a PR here:
https://github.com/FluentValidation/FluentValidation/pull/1338

Don't know the process tough, should I update some release changes or similar file?

**Comment by JeremySkinner** [comment]
Thanks, no need to update the changelog, I'll handle that. I've left a couple of comments on the PR though that would be good to address before I merge it.

**Comment by JeremySkinner** [comment]
I've published 9.0-preview4 to nuget with these changes
