### ISSUE TITLE
Best Practice Question: User Actions and Parent State

### ISSUE THREAD

**Issue by b-hazelwood** [FluentValidation/FluentValidation#1343]
### System Details

- FluentValidation version: 8.6.0

### Issue Description
Best approach to validating user Actions and object states. For these type of validation the class property rules do not apply. For example;

If a parent state/status is 'closed' a user cannot edit or update a child. I would need to check what the user is doing before trying to decide what they are allowed to do. 
---
If a parent state/status is 'pending approval' a user cannot add new children but may be able update existing children and cannot delete. A user's manager may still  be able do all actions (Create, update, delete).
---

Where is the best place to put rules based on parent & child state/status and user's action?

I hope I explained my issue well enough. Thank-you for any and all assistance.

**Comment by JeremySkinner** [comment]
Hi there, FluentValidation is a tool for validating the properties on objects. It sounds to me like FluentValidation isn't the right tool to be doing this - you should probably perform this type of validation externally.

**Comment by b-hazelwood** [comment]
OK, thank-you for the feedback.
