### ISSUE TITLE
Language Problem - german and english 

### ISSUE THREAD

**Issue by madrianr** [FluentValidation/FluentValidation#1345]
### System Details

- FluentValidation version: 8.6.2
- Web Framework version: ASP.NET Core 2.2

### Issue Description
we have the problem that some messages are in german as expected but some in english...

`public class BetriebsmittelViewModelValidator : AbstractValidator<BetriebsmittelViewModel>
    {
        public BetriebsmittelViewModelValidator()
        {
            RuleFor(c => c.Betriebsmittel_ID).NotNull();
            RuleFor(c => c.Betriebsmittel).NotNull().MaximumLength(65);
        }
    }`

the result is that the "NotNull" displays english error message for required and german for not  null:

_The Betriebsmittel field is required.
 'Betriebsmittel' darf kein Nullwert sein._

the MaximumLength is in german

_Die Länge von 'Betriebsmittel' muss kleiner oder gleich 65 sein. Sie haben 394 Zeichen eingegeben._

I have set the culture in startup:

`ValidatorOptions.LanguageManager.Culture = new CultureInfo("de");`

regards robert

**Comment by JeremySkinner** [comment]
Hi there, the English message you’re seeing (“ The Betriebsmittel field is required.”) isn’t coming from FluentValidation. It’s coming from asp.net directly. This either means:

- You have a [Required] attribute on the property. If this is the case, remove the attribute 
- The property is a non-nullable value type (eg an int or a date time) and you’re sending a null value. If this is the case, then make the property nullable 

Either way this isn’t actually related to FluentValidation, these are features of  asp.net itself.

Hope that clears things up.

**Comment by madrianr** [comment]
Thanks - so I understand...

robert
