### ISSUE TITLE
Version 9 isnt compatible with netstandard2.1?

### ISSUE THREAD

**Issue by Gillardo** [FluentValidation/FluentValidation#1346]
Why is the latest version of fluent validation v9 preview 3 not compatible with netstandard2.1??

Its not like this is old or anything?  Had to revert back to v8

**Comment by JeremySkinner** [comment]
Hi, it is compatible. The core FluentValidation package targets netstandard2.0 which runs on netstandard2.1 just fine too.

**Comment by Gillardo** [comment]
I am sorry, it seems i have been referencing aspnetcore package in my service layer #facepalm! 

thanks for the quick response!
