### ISSUE TITLE
Manual validation when using AddFluentValidation in ASP.NET Core

### ISSUE THREAD

**Issue by GurGaller** [FluentValidation/FluentValidation#1350]
### System Details

- FluentValidation version: FluentValidation.AspNetCore 8.6.2
- Web Framework version: ASP.NET Core 3.1

### Issue Description
When registering validators using the `AddFluentValidation` extension method, there is no way to disable automatic validation. In my case, the business logic code already calls Fluent Validation and I only need to register the validators to the DI container. So, it would be nice to have an option for manual validation when using:
```
services.AddFluentValidation(fv =>
{
    fv.RegisterValidatorsFromAssemblyContaining(typeof(Application.Startup));
});
```
Currently, the best solution I found is to register the validators manually to the DI container (or automatically with reflection), without calling `AddFluentValidation`. 
I suggest adding that option to the `FluentValidationMvcConfiguration` class. The syntax of using it will be something like:
```
services.AddFluentValidation(fv =>
{
    fv.RunValidationOnModelBinding = false;
    fv.RegisterValidatorsFromAssemblyContaining(typeof(Application.Startup));
});
```

**Comment by JeremySkinner** [comment]
Hi, the entire purpose of the AddFluentValidation method is to configure automatic validation. If you’re not using automatic validation then you shouldn’t be calling this (in fact, you don’t really need the FluentValidation.AspNetCore package at all)

Either register the validators directly with the container (as you are doing) or use the extension methods in the FluentValidation.DependencyInjectionExtensions package, which register validators without the auto validation stuff. 

Hope that clears things up

**Comment by GurGaller** [comment]
Thank you, I wasn't aware of the `FluentValidation.DependencyInjectionExtensions` package:)
