### ISSUE TITLE
Support for ASP.NET Core 2.2

### ISSUE THREAD

**Issue by ayedo** [FluentValidation/FluentValidation#1351]
### System Details

- FluentValidation version: 8.6.2
- ASP.NET Core 2.2

### Issue Description
Hello,

first of all: thanks for your great work on this library. It looks very promising. 

I'm trying to integrate it in a ASP.NET Core 2.2 project, and I'm getting errors at runtime expecting ASP.NET Core 2.1. 

I'm new to the .NET ecosystem, so I'm not sure whether there is a way to tell a package to accept higher minor versions? I just wanted to make sure, that version 2.2 is actually supported by the library?

Thanks,
Alon

**Comment by JeremySkinner** [comment]
Hi,

2.2 is not actually supported anymore. Microsoft support for .NET Core 2.2 ended on November 19th 2019. See the .NET Core support dates: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

You should switch to a LTS release of .NET Core - either upgrade to 3.1 or downgrade to 2.1

That being said, FluentValidation does still run on 2.2 without issues (our integration tests run against 2.1, 2.2, 3.0 and 3.1). You need to have the following:
- Your application must be using the `netcoreapp2.2` target framework
- You must be referencing version 2.2 of the `Microsoft.AspNetCore.Mvc` package

If you have these in place, then FluentValidation should run against 2.2 without any problems. 

However as 2.2 is now an unsupported platform I'm afraid you're on your own with this, and it's not something I can provide support for, so I'd strongly suggest going to 3.1 if you can.
