### ISSUE TITLE
RuleForEach with SetValidator doesn't work when CustomizeValidator(RuleSet) is used

### ISSUE THREAD

**Issue by IlyaUhlianitsa** [FluentValidation/FluentValidation#1352]
Hi Jeremy!
I have a model `House`.
```
public class House
{
    public Guid? Id { get; set; }
    public string Name { get; set; }
    public IEnumerable<Room> Rooms { get; set; }
}

public class Room
{
    public int DoorsCount { get; set; }
}

```
I use one model for two endpoints(Create and Update), so I need different RuleSets.
Before I added `CustomizeValidator` to a model, everything worked well, but after that - validation for `Rooms` property doesn't work.
I prepared a simple application that demonstrates it.
Run the application and send this JSON to POST method in swagger.
```
{
  "name": "Kitchen",
  "rooms": [
    {
      "doorsCount": 0
    }
  ]
}
```
It should return 400, because `RoomValidator` expects `doorsCount` greater than 0. But it returns 200.
If you comment `CustomizeValidator`, it will return 400 as expected.

Could you explain is it a bug or I do something wrong?
Thanks!

[WebApplication1.zip](https://github.com/FluentValidation/FluentValidation/files/4379727/WebApplication1.zip)

**Comment by JeremySkinner** [comment]
Hi there,

RuleSets cascade to child validators, so if you're executing the "Create" ruleset on the `HouseValidator`, the Create ruleset will also be executed on the `RoomValidator`, but the `RoomValidator` doesn't have a Create ruleset, so nothing will happen. 

A ruleset always applies to the whole validation hierarchy. 

Hope that helps

**Comment by IlyaUhlianitsa** [comment]
I checked up your code and it works, thanks!
But I have  some more questions:
1) In `HouseValidator` I have `RuleFor(x => x.Name).NotEmpty();` which wrote outside of any RuleSet, but works for all rule sets. In my opinion, it is logical because you can write common parts then. Why 
```
RuleForEach(x => x.Rooms)
    .SetValidator(x => new RoomValidator());
```
doesn't have the same behavior?

2) I see that `SetValidator` has param `params string[] ruleSets`. But why it doesn't work if I write ?
```
RuleForEach(x => x.Rooms)
    .SetValidator(x => new RoomValidator(), "Create", "Update");
```

**Comment by JeremySkinner** [comment]
> In HouseValidator I have RuleFor(x => x.Name).NotEmpty(); which wrote outside of any RuleSet, but works for all rule sets

That shouldn't be the case - I'd suggest you double check this. Rules outside a ruleset will *only execute if no ruleset is specified for execution*

> I see that SetValidator has param params string[] ruleSets. But why it doesn't work if I write ?

This is for a different use case. This is used when you're *not executing a specific ruleset on the parent validator*, but you want a specific ruleset to run in the child validator anyway. So it's essentially for the *opposite* scenario for what you're doing.

**Comment by IlyaUhlianitsa** [comment]
Oh now I understand
Thank a lot, Jeremy!
