### ISSUE TITLE
Feature Request: optionally specify a unit symbol on Transform

### ISSUE THREAD

**Issue by nzain** [FluentValidation/FluentValidation#1353]
### System Details
FluentValidation version: 8.6.1 (on a WPF desktop app)

### Current State
FluentValidation does a great job of showing well formed localized messages for complex constraints defined in simple code. We have a lot of greater-than & less-than constraints on properties that can be edited by the user. Internally we store all distance values as [m] and angles as [rad], but our users can select different unit systems (e.g. international feet/inch). The `Transform(x => x * unitFactor)` method provides a very flexible solution to our custom unit management and often the validation code looks like this:

```cs
    double unitFactor = ... // our custom solution
    this.RuleFor(vm => vm.SomeSpecialValue)
        .Transform(x => x * unitFactor)
        .GreaterThan(0)
        .LessThanOrEqualTo(0.01 * unitFactor);
```

If the display unit is [mm] this would be a factor of 1000 and FluentValidation would display something like: `Some Special Value must be less than or equal to 10.` which matches perfectly with the value entered in the text box. However, our custom text box additionally shows the unit `mm` for clarity, but the validation does not.

### Feature Request
It would be awesome (how much _more_ awesome could this project be?) if we could append a string to the transformed value. The most convenient solution for us would be an additional overload on `Transform` that takes an extra string to append, something like 

```cs
        .Transform(x => x * 1000, "mm")
````
to provide a localized message like: ``Some Special Value must be less than or equal to 10mm.`

Eventually others would like to set a unit string independently of transforms (because they don't use it) but for us this would be the right spot, because scale transform and unit belong together.

If you think this a good idea and not too difficult I might contribute a PR - but I haven't look at the source at all up to now.

**Comment by JeremySkinner** [comment]
Hi there, thanks for the suggestion.

Transform isn't the right place to be doing this. Transformations convert the property value from one form into another - if you apply the suffix at this level then your rule would instead end up validating the string "10mm" rather than the decimal 10. Instead, this is something that should be done at the point where the error message is constructed.

FluentValidation's error messages support custom placeholders, as well as allowing you to modify the built in ones using a custom message builder. I'd suggest doing one of the following:
- Add a `{Unit}` placeholder to your localized messages (eg `{PropertyValue}{Unit} must be greater than {ComparisonValue}`
- Alternatively just modify the `{PropertyValue}` placeholder to contain the suffix you want

Both approaches are very similar using a message builder, which can be wrapped in a custom extension method:

```csharp
public static class UnitExtension {
	public static IRuleBuilderInitial<T, TProperty> Unit<T, TProperty>(this IRuleBuilderInitial<T, TProperty> ruleBuilder, string unitSuffix) {
		return ruleBuilder.Configure(rule => {
			// Rules can only have a single message builder,
			// so keep a reference to the original one (if there is one)
			// to allow them to be chained together.
			var originalMessageBuilder = rule.MessageBuilder;

			rule.MessageBuilder = context => {
				
				// Either add a new custom placeholder...
				context.MessageFormatter.AppendArgument("Unit", unitSuffix);
				// ...or just append the suffix it to the PropertyValue placeholder
				context.MessageFormatter.AppendArgument("PropertyValue", context.PropertyValue.ToString() + unitSuffix);
				
				return originalMessageBuilder?.Invoke(context) ?? context.GetDefaultMessage();
			};
		});
	}

}
```

...then usable like this:

```csharp
this.RuleFor(vm => vm.SomeSpecialValue)
        .Transform(x => x * unitFactor)
        .Unit("mm")
        .GreaterThan(0)
        .LessThanOrEqualTo(0.01 * unitFactor);
```

Hope that helps.

**Comment by nzain** [comment]
Thanks for your quick response. Your first suggestion (custom placeholder) requires custom localization messages, but we use the built-in messages.

Your second suggestion looks like the right way for us, but I couldn't make it work. Stepping through the code, I can see that `context.PropertyValue` is the _untransformed_ value, so I added the `rule.Transformer` and now `context.MessageFormatter.PlaceholderValues["PropertyValue"]` contains the expected string `1000mm`. However, the `originalMessageBuilder` is null and the call to `GetDefaultMessage()` seems to ignore the placeholder values. In other words, the extension method is executing but has no effect.

**Comment by JeremySkinner** [comment]
> but we use the built-in messages

Ok, that makes things slightly different. I assumed you were using custom localized messages that were using {PropertyValue}. The built in messages don't actually include the {PropertyValue} placeholder. For example the default message for LessThanOrEqual is:

```
'{PropertyName}' must be less than or equal to '{ComparisonValue}'.
``` 

The {ComparisonValue} is the value obtained from the call to `LessThan` (not the current property value), so retrieving it is slightly different, but the approach using a message builder is the same (see below)

> I can see that context.PropertyValue is the untransformed value

This isn't actually the case - if you put a breakpoint intside the inner MessageBuilder delegate, you'll see that context.PropertyValue is always the transformed value. If the rule has a transformer configured, this is always invoked prior to the property value being set on the context. See https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation/Validators/PropertyValidatorContext.cs#L47-L50

Anyway, here's a full working example for you:

```csharp
[Fact]
public void Demo() {
	var model = new Demo {SomeValue = 1};
	var validator =new DemoValidator();
	var result = validator.Validate(model);
	Assert.Equal("'Some Value' must be less than '100mm'", result.Errors[0].ErrorMessage);
}
```

```csharp
public class Demo {
	public double SomeValue { get; set; }
}

public class DemoValidator : AbstractValidator<Demo> {
	public DemoValidator() {
		double unitFactor = 1000;

		RuleFor(x => x.SomeValue)
			.Transform(x => x * unitFactor)
			.Unit("mm")
			.LessThan(100);
	}
}
```

```csharp
public static class UnitExtension {
	public static IRuleBuilderInitial<T, TProperty> Unit<T, TProperty>(this IRuleBuilderInitial<T, TProperty> ruleBuilder, string unitSuffix) {
		return ruleBuilder.Configure(rule => {
			// Rules can only have a single message builder,
			// so keep a reference to the original one (if there is one)
			// to allow them to be chained together.
			var originalMessageBuilder = rule.MessageBuilder;

			rule.MessageBuilder = context => {
				if (context.PropertyValidator is AbstractComparisonValidator cv) {
					var comparisonValue = cv.GetComparisonValue(context);
					context.MessageFormatter.AppendArgument("ComparisonValue", comparisonValue + unitSuffix);
				}

				return originalMessageBuilder?.Invoke(context) ?? context.GetDefaultMessage();
			};
		});
	}

}
```

**Comment by nzain** [comment]
You were faster. Indeed, my code looks similar to yours, but I added the `IBetweenValidator`, which uses the `Value` placeholder (not `PropertyValue`) as well. Thanks for helping me out! Feel free to close, unless you want to integrate this at some point.

Just for the sake of completeness, here is my final version:
```cs
public static class UnitExtension
    {
        public static IRuleBuilderInitial<T, TProperty> Unit<T, TProperty>(
            this IRuleBuilderInitial<T, TProperty> ruleBuilder, string unitSuffix)
        {
            if (ruleBuilder == null)
            {
                throw new ArgumentNullException(nameof(ruleBuilder));
            }
            return ruleBuilder.Configure(rule =>
            {
                // Rules can only have a single message builder,
                // so keep a reference to the original one (if there is one)
                // to allow them to be chained together.
                Func<MessageBuilderContext, string> originalMessageBuilder = rule.MessageBuilder;

                rule.MessageBuilder = context =>
                {
                    // We don't have custom messages, an extra placeholder won't work.
                    // Instead append the unit suffix to all relevant display values.

                    // a) the actual property value, not used in default messages
                    context.MessageFormatter.AppendArgument("PropertyValue", context.PropertyValue + unitSuffix);

                    // b) IComparisonValidator (GreaterThan, LessThen, etc.)
                    if (context.PropertyValidator is AbstractComparisonValidator acv)
                    {
                        // the context might provide a comparison value from an expression
                        IComparable comparisonValue = acv.GetComparisonValue(context);
                        context.MessageFormatter.AppendArgument("ComparisonValue", comparisonValue + unitSuffix);
                    }
                    else if (context.PropertyValidator is IComparisonValidator icv)
                    {
                        // fallback, just to cover all cases
                        context.MessageFormatter.AppendArgument("ComparisonValue", icv.ValueToCompare + unitSuffix);
                    }

                    // c) IBetweenValidator (InclusiveBetween, ExclusiveBetween)
                    if (context.PropertyValidator is IBetweenValidator ibv)
                    {
                        context.MessageFormatter.AppendArgument("From", ibv.From + unitSuffix);
                        context.MessageFormatter.AppendArgument("To", ibv.To + unitSuffix);
                        context.MessageFormatter.AppendArgument("Value", context.PropertyValue + unitSuffix);
                    }

                    return originalMessageBuilder?.Invoke(context) ?? context.GetDefaultMessage();
                };
            });
        }
    }
```

**Comment by JeremySkinner** [comment]
Great, glad you have a working solution!
