### ISSUE TITLE
Any "bad word" validation helper out there?

### ISSUE THREAD

**Issue by aktxyz** [FluentValidation/FluentValidation#1354]
would love to be able to do something like ...

RuleFor(x => x.Tagline).MatchesBadword()

maybe someone has created a good one?

**Comment by JeremySkinner** [comment]
There’s nothing built in for this, but FluentValidation is intentionally designed to be extensible, so you can write your own custom validation logic: https://docs.fluentvalidation.net/en/latest/custom-validators.html
