### ISSUE TITLE
Chaining Validators with an OR

### ISSUE THREAD

**Issue by kieronlanning** [FluentValidation/FluentValidation#1355]
I've looked and looked, and if I've missed the how, my apologies!

Is it possible to chain validators together to create an `or` operation?

For example, I'd like to be able to do something like this:

```
RuleFor(m => m.EmailContact)
	.Empty()
	.Or()
	.EmailAddress(FluentValidation.Validators.EmailValidationMode.Net4xRegex);
```

What I'm effectively saying here is that the property `EmailContact` should be `empty` or `null` (I don't care which), but if it's not then it should be a `valid email address` - i.e., execute the next validator in the chain, in this case the `EmailAddress` validator.

**Comment by JeremySkinner** [comment]
Hi, you'd do this using conditions ([see the docs](https://docs.fluentvalidation.net/en/latest/conditions.html))

```csharp
RuleFor(x=> x.EmailContact).EmailAddress().When(value => !string.IsNullOrEmpty(value));
```

**Comment by kieronlanning** [comment]
Ah, I had it the wrong why around. Of course..!

Thankyou!
