### ISSUE TITLE
HowTo: Get the number of the element in collection

### ISSUE THREAD

**Issue by sekulicb** [FluentValidation/FluentValidation#1358]
Hi. When validating collections, there is a special placeholder {CollectionIndex} which works great, but from the end user standpoint, it gets them confused because not everybody is familiar with the fact that index in programming arrays starts from 0. So in their heads when you validate and print message "row 0 has this and that...." will raise eyebrows and will get you back negative feedback. Is there a way to somehow add +1 on top of {CollectionIndex} or maybe there is another placeholder for case like this?

Thanks

**Comment by JeremySkinner** [comment]
Hi, yes you're right - typically `{CollectionIndex}` wouldn't be exposed directly to end users. It's intended use was for APIs. 

If you want to use this for end users then you can use a custom message builder to manipulate the placeholder prior to the message being generated.

```csharp
public static class IncrementCollectionIndexExtension {
	public static IRuleBuilderOptions<T, TProperty> IncrementCollectionIndexBy1<T, TProperty>(this IRuleBuilderOptions<T, TProperty> ruleBuilder) {
		return ruleBuilder.Configure(rule => {
			// A rule can only have a single message builder.
			// If it already has one, cache it and call it from within our new one below
			// (essentially chaining them together).
			var originalMessageBuilder = rule.MessageBuilder;

			rule.MessageBuilder = context => {
				if (context.MessageFormatter.PlaceholderValues.TryGetValue("CollectionIndex", out object index)) {
					if (index is int i) {
						i++;
						context.MessageFormatter.AppendArgument("CollectionIndex", i);
					}
				}
				return originalMessageBuilder?.Invoke(context) ?? context.GetDefaultMessage();
			};
		});
	}
}
```

With this extension method in place, you can then call `IncrementCollectionIndexBy1()` as part of your rule definition.

**Comment by sekulicb** [comment]
Cool, it works perfectly. Thank you for prompt response and solution. 

All the best,
Bane
