### ISSUE TITLE
Add Icelandic language to FluentValidation

### ISSUE THREAD

**Issue by Andri73** [FluentValidation/FluentValidation#1361]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description

The file IcelandicLanguage.txt contains a language class for Icelandic

[IcelandicLanguage.txt](https://github.com/FluentValidation/FluentValidation/files/4445500/IcelandicLanguage.txt)

**Comment by JeremySkinner** [comment]
Hi there, thank you for the submission. Please could you add this as a Pull Request so this goes through our CI process, and also ensures you sign our contributor license agreement. 

You'll need to add the language file to the /Languages directory as well as adding it into the LanguageManager (https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation/Resources/LanguageManager.cs#L47) 

Let me know if you need any help doing this.

Thanks.

**Comment by Andri73** [comment]
Hi

I created

https://github.com/FluentValidation/FluentValidation/pull/1362

Let me know if I need to change anything.

Regands Andri

þri., 7. apr. 2020 kl. 15:30 skrifaði Jeremy Skinner <
notifications@github.com>:

**Comment by JeremySkinner** [comment]
Thanks, looks good. I'll get this merged later in the week.

**Comment by JeremySkinner** [comment]
This has been merged
