### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'AddFluentValidation' and the best extension method overload 

### ISSUE THREAD

**Issue by rodrigofbm** [FluentValidation/FluentValidation#1363]
### System Details

- FluentValidation version: 8.4.0 (and 8.6.2)
- Web Framework version:ASP.NET Core 2.2

### Issue Description
```
IServiceCollection services
'IServiceCollection' does not contain a definition for 'AddFluentValidation' and the best extension method overload 'FluentValidationMvcExtensions.AddFluentValidation(IMvcCoreBuilder, Action<FluentValidationMvcConfiguration>)' requires a receiver of type 'IMvcCoreBuilder' [API]csharp(CS1929)
```

I already installed the FluentValidation.AspNetCore package via NuGet and applied "restore". I also restarted the VS Code but without success.

PS: I can use the FluentValidation namespace in other files but I can't use FluentValidation.AspNetCore in the StartUp.cs file.

**Comment by JeremySkinner** [comment]
Hi there, that error message is correct. `AddFluentValidation` is not a method on IServiceCollection, it's a it's an extension method on IMvcBuilder. 

So you must call `services.AddMvc().AddFluentValidation()`, (the call to AddMvc must directly precede it)
