### ISSUE TITLE
Collection Validator with parent message

### ISSUE THREAD

**Issue by guipiva-dev** [FluentValidation/FluentValidation#1366]
### System Details

- FluentValidation version: 8.6.2

### Issue Description

Is it possible? 
I tried this code but parent message $"The product: ({product.Code}) {product.Description} is invalid" is not showing.

**Example Code:**

`public class OrderValidator: AbstractValidator<Order>

	{
	  public OrderValidator()
	  {
		RuleFor(x => x.Products)
			.NotNull()
			.DependentRules(() =>
				{
					RuleForEach(x => x.Products)
						.SetValidator(new ProductValidator())
						.WithMessage((_,product) => 
						$"The product: ({product.Code}) {product.Description} is invalid");
				});
	  }
	}
	
	public class ProductValidator : AbstractValidator<Product>
    {
        public ProductValidator()
        {
            RuleFor(x => x.Quantity).GreaterThan(0).WithMessage($"Quantity is required!");
        }
    }`

**Expected Validation Result:**
"The product: (001) Product 1 is invalid"
"Quantity is required!"
"The product: (002) Product 2 is invalid"
"Quantity is required!"
"The product: (003) Product 3 is invalid"
"Quantity is required!"

**Comment by JeremySkinner** [comment]
Hi there, no that won't work. When you use a child validator with `SetValidator`, the error message *always comes from the child validator* not the parent validator. Calling `WithMessage` after `SetValidator` will have no affect.

**Comment by JeremySkinner** [comment]
Also, each rule can only have a single message associated with it. You would need to generate a single message inside the product validator that contains this information. Eg:

```csharp
ublic class ProductValidator : AbstractValidator<Product>
{
    public ProductValidator()
    {
        RuleFor(x => x.Quantity).GreaterThan(0).WithMessage(product => $"Product ({product.Code}) {product.Description} - Quantity is required!");
    }
}
```

Also just a tip: github uses 3 backticks to format code blocks.
