### ISSUE TITLE
Handling validation for interfaces

### ISSUE THREAD

**Issue by jasekiw** [FluentValidation/FluentValidation#1367]
### System Details

- FluentValidation version: 8.6.2
- Web Framework version: ASP.NET Core 3.1 (WebApi)

### Issue Description

I have come across a situation when trying to use interfaces for my models in a DRY approach. I could not find support for this using the standard ASP.Net Core validation library and have come here to see if this is suppported.

Please let me know if there are better ways to do this in terms of design.

Please take a look at the following scenario:

```
interface IRevision {
    public string RevisionTitle {get;set;}
    public string RevisionDescription {get;set;}
}


class TaskRevision : IRevision {
    public string RevisionTitle {get;set;}
    public string RevisionDescription {get;set;}
    ... class specific properties
}


class NoteRevision : IRevision {
    public string RevisionTitle {get;set;}
    public string RevisionDescription {get;set;}
   ... class specific properties
}

```
I want all of these models to inherit the same validations rules for RevisionTitle and RevisionDescription so that I don't have to specify them over and over again for each model.

So I created a Validator like so:

```
public class RevisionValidator : AbstractValidator<IRevision>
{
	public RevisionValidator()
	{
		RuleFor(x => x.RevisionTitle).NotNull().Length(1, 255);
		RuleFor(x => x.RevisionDescription).NotNull().Length(0, 1000);
	}
	
}
```

I was able to make this work by getting all classes that implement the interface and looping through them to add the validator to each.

```

public static void ConfigureValidators(this IServiceCollection services)
{
	var entities = GetAllEntitiesThatImplementInterface(typeof(IRevision));
	foreach (var entity in entities)
	{
		services.AddTransient(typeof(IValidator<>).MakeGenericType(entity), typeof(RevisionValidator));
	}
}

private static  List<Type> GetAllEntitiesThatImplementInterface(Type interfaceType)
{
	return AppDomain.CurrentDomain.GetAssemblies().SelectMany(x => x.GetTypes())
		.Where(x => interfaceType.IsAssignableFrom(x) && !x.IsInterface && !x.IsAbstract)
		.ToList();
}
```

`ImplicitlyValidateChildProperties`  had to be enabled to allow this interface to be used as a property of a view model.
```
services.AddControllers()
	.AddFluentValidation(fv => {
		fv.ImplicitlyValidateChildProperties = true;
	});
```

Problems with this approach:

In theory this is an all or nothing approach. Either we validate the model according to the interface or not at all. This is currently all I need by using Asp.Net core's built in validation and only using FluentValidation to handle the interfaces.

Questions:

1. Why does default ASP.Net Core library not mention this scenario or this library for that matter? Is this an anti pattern that I am getting myself into? I am aware I could create a RevisionInfo class that is separate and would solve this issue but I didn't want to have to create another entity for 2 fields.

2. Is there a way to support FluentValidation both for the class that implenents the interface (eg. extra properties) and the fields on the interface itself?

I am specifically trying to apply validator rules by implementing the interface in a class. I would like there to be no extra action required so that the possibility of missing a step is completely removed.

**Comment by JeremySkinner** [comment]
Hi,

So firstly, if we remove ASP.NET from the equation, validation of interfaces is definitely something that's possible and supported. Usually I recommend using composition by making use of [rule inclusion (docs)](https://docs.fluentvalidation.net/en/latest/including-rules.html). With this approach, you'd have a validator for your interface type, but you'd still have a validator for each concrete class, which imports the interface rules, like this:

```csharp
public class RevisionValidator : AbstractValidator<IRevision> {
  public RevisionValidator() {
    RuleFor(x => x.RevisionTitle).NotNull().Length(1, 255);
    //etc 
  }
}

public class TaskRevisionValidator : AbstractValidator<TaskRevision> {
  public TaskRevisionValidator() {
     // Import the rules for the interface.
     Include(new RevisionValidator());
     // Define any further rules that are specific for the subtype.
     RuleFor(x => x....); 
  }
}
```

The advantages of this approach is that it's extremely clear what's happening. There's no magical mapping - we still have 1 validator per class. It also means that using automatic validation with ASP.NET core still works correctly, assuming that your controller action parameters are the concrete type (which they should be), not the interface.

> Why does default ASP.Net Core library not mention this scenario or this library for that matter

Generally when it comes to model binding, you want the input-model to be as simple as possible. IE it should be a direct representation of what the user has entered into the screen (or posted via an api), eg:

```csharp
public ActionResult MyAction(SomeModel model);
```

..where SomeModel would contain properties representing the inputted data. If you had an interface as the parameter, ASP.NET's model binding mechanism won't really know what to do. At some point, it's going to have to instantiate a concrete type, but which one? You can start writing custom binding providers or other mechanisms to work this out, but it starts to become very 'magic' at this point, and it's unintutive what's happening. And that's just the binding, validation then adds a whole other layer - which validator should be chosen for the type? Should it use one for the interface, or for the underlying concrete type.

So when it comes to model binding I'd always recommend using an explicit concrete type, and never an interface (this also goes for built-in interfaces - use `List<T>` for collections, not `IEnumerable<T>`, so it's very clear what ASP.NET will internally be instantating). 
 
> Is there a way to support FluentValidation both for the class that implenents the interface (

Yes, see my composition example above :) 

Hope that helps

**Comment by jasekiw** [comment]
Hi Jeremy,

Thank you for the very well thought out response!

I like the approach of using the Include syntax for including the rules. I apologize for not seeing that feature earlier! One concern I have is that developers in the project might forget to call `Include(new RevisionValidator());` because they don't remember that the model implements IRevision (in a scenario where there are a lot of revision based items).

Calling `Include(new RevisionValidator());` for every concrete class that implements IRevision is in a way not DRY itself (correct me if I am wrong here). A way to include the default Validators for the interfaces a model implements without calling Include explicitly would be helpful to avoid errors when developers forget to call `Include`. I don't know if this violates any design principles however.

if a feature like this were to exist, there would have to be way to override default Validators if a specific concrete class needs to apply special rules to the fields exposed by the interface.

What are your thoughts on this?

**Comment by JeremySkinner** [comment]
> Calling Include(new RevisionValidator()); for every concrete class that implements IRevision is in a way not DRY itself

This really isn't a concern for me at all. FluentValidation prefers being explicit over automatic/magic, so no, I wouldn't be keen on having the interface validator being included automatically. Each validator is an individual, isolated unit and should be configured/set-up independently. 

If this really is a concern for you, then add a base class that uses the `Include` call, and have all your concrete validators inherit from this class. 

Hope that makes sense.

**Comment by jasekiw** [comment]
I like that solution a lot. Thank you for your insight!
