### ISSUE TITLE
Vietnamese Language

### ISSUE THREAD

**Issue by lthoa** [FluentValidation/FluentValidation#1372]
Hi,

This is Vietnamese language file:
https://raw.githubusercontent.com/lthoa/FluentValidation/master/src/FluentValidation/Resources/Languages/VietnameseLanguage.cs

**Comment by JeremySkinner** [comment]
Hi there, please could you submit this as a pull request, and also add it to the LanguageManager. Here's an example: https://github.com/FluentValidation/FluentValidation/pull/1362/files

Thanks.

**Comment by JeremySkinner** [comment]
Closing due to no response. If you'd still like this to be included, please submit it as a pull request.
