### ISSUE TITLE
Hardcoded string "Validation failed: ". No localization possible

### ISSUE THREAD

**Issue by sergeyovchinnikov** [FluentValidation/FluentValidation#1376]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

**Comment by JeremySkinner** [comment]
Please provide more details. Where are you seeing this stirng? What specifically are you trying to do?

Have you [read the documentation on localization](https://docs.fluentvalidation.net/en/latest/localization.html)? All of FluentValidation's default error messages are localized, and you can localize your own custom error messages too.

**Comment by sergeyovchinnikov** [comment]
Hello,

thank you for your quick answer.
I opened the issue because i've got always the message beginning with the english text "Validation failed".
i think i have just overlooked the  other Ctor, that gets the complete message, so I close the issue.
