### ISSUE TITLE
Feature Request: get all rules that have NOT failed

### ISSUE THREAD

**Issue by rayden84** [FluentValidation/FluentValidation#1378]
So far, I have not found a way to get all rules of a validator that have not failed, i.e. that have passed. 

In my use case I would like to show a report after validation is complete, that lists ALL rules, even the passed ones, with their respective actual and expected values, since sometimes it is desired to examine the value of a passed rule, especially if multiple values are allowed. This would help making a report about the entire validation process a lot easier...

Maybe its even possible with the actual version and I simply overlooked something. Is this request legitimate and the use case valid?

**Comment by JeremySkinner** [comment]
Hi, this isn't something that's possible with FluentValidation, and to be honest I'm not really sure how this would work. 

FluentValidation produces `ValidationFailure` objects, keyed by property-path whenever a rule fails. If a rule doesn't fail, then there isn't actually anything exists that you could report on. I suppose what you might be able to do is use the `ValidatorDescriptor` (created by calling `CreateDescriptor` on the validator instance) to look at all the rules inside the validator, but matching them up with those that have failed isn't going to be trivial, especially if you're making use of child/nested validators. But it might be worth trying that approach anyway and seeing if it works for you.

**Comment by rayden84** [comment]
What I have done as a small experiment was to change the ValidationFailure class by introducing a new FailedValidator property, that can be used to make a set difference from the set of all rules. I have forked a MWE over here: 
[https://github.com/rayden84/FluentValidation/tree/failedvalidators](url)

Although the introduced changes were unexpectedly not that invasive (just changing the ValidationFailure class), the approach is surely very hack'ish. Unfortunately the passed rules that I obtained do not contain the entire data (expected/actual) that I was looking for, but it has become a little easier for me. For a long-term solution the validation should return a more "complete" validationresult giving back the failures as well as a sort of validation success objects, both referencing to the rule(s) that lead to that result, meaning that my approach must be pushed deeper in the class hierarchy.

Would you mind giving a look at it? Thank you
