### ISSUE TITLE
Feature request: Expand custom validator to Validate against other property values on object

### ISSUE THREAD

**Issue by lisamariet** [FluentValidation/FluentValidation#1380]
This is what I would like to have:
`RuleFor(e => e.AnswerPath).Custom( (e, context) => {[Validation logic that checks that this property contains other properties on e object]});`

the e.AnswerPath is a string composed of several Id's. So want to check the format is correct and it has the correct Id's.

**Comment by JeremySkinner** [comment]
Hi, could you provide a bit more detail about what you're trying to do? 

If you just need to access other properties on the object being validated, then you can access the properties on the `e` instance directly inside the validation function, but I assume you're trying to do more than that?

If you want the actual *validation failures* to be associated with different properties (ie not with AnswerPath) then you can do that by calling the other overload of AddFailure that contains the name of the property. 

```csharp
RuleFor(e => e.AnswerPath).Custom( (e, context) => {
   var answerPath = e.AnswerPath;
   var someOtherProperty = e.SomeOtherProperty;
   bool valid = //(....some validation logic involving these properties)...
   
  if (!valid) {
    // This will generate a validation failure message associated with the AnswerPath property.
    context.AddFailure("custom validation failed");
    // ... but this would generate a validation failure associated with a different property.
    context.AddFailure("SomeOtherProperty", "custom validation failed");
  }
});
```

**Comment by lisamariet** [comment]
I tried doing what you suggested, but it does not work. e is passed in as the property and not the entire class. However this lead me to test this: 
`RuleFor(e => e).Custom((e, context) => {   });`

And this seems to work. Thank you!!

**Comment by JeremySkinner** [comment]
Ah, yes you're correct - `e` in that case would be the value of the property, rather than the root instance. You can always access the root instance from the `context.InstanceToValidate` property
