### ISSUE TITLE
WithMessage does not work in last version

### ISSUE THREAD

**Issue by vd3d** [FluentValidation/FluentValidation#1383]
Hi,

FYI, I directly use the last version of the source code and ...

I try to use custom message for errors, I use WithMessage, as expected, but it display the "Default" message and not the one I define.

Here is my code :

```
RuleFor(Q => Q.Name).NotEmpty().MaximumLength(255).WithMessage("Hi, very bad name");
RuleFor(Q => Q.Email).NotEmpty().EmailAddress().MaximumLength(255).WithMessage("Hi, very bad email");    
```

I have spend some time to debug the code, and in PropertyValidator.CreateValidationError I have the following code:

```
var error = context.Rule.MessageBuilder != null
  ? context.Rule.MessageBuilder(messageBuilderContext) : messageBuilderContext.GetDefaultMessage();
```

But context.Rule.MessageBuilder is null , so it use the default builder and this one generate a default message and not the one defined with WithMessage !

Do you have any idea ?

**Comment by JeremySkinner** [comment]
Hi there. `WithMessage` definitely *does* work in the latest version

> But context.Rule.MessageBuilder is null 

That is correct. The message builder is an advanced feature that isn't related to calling `WithMessage`.

Please provide some sample code that reproduces the issue.

**Comment by JeremySkinner** [comment]
Also, please note that calling `WithMessage` only applies to *the immediately preceding validator in the chain*. 

So in this case, your "Hi, very bad name" message will only apply to the `MaximumLength` validator. It won't apply to the NotEmpty validator. Similarly, your "Hi, very bad email" message will only apply to the `MaximumLength` validator. It won't apply to the EmailAddress or NotEmpty. Is that what you intended? If you want the same message to be used for all validators in the chain, you must call WithMessage multiple times after each one.

**Comment by vd3d** [comment]
OMG, I expected one message for all the validator, sorry !

Thanks

**Comment by JeremySkinner** [comment]
Ah great, I’m glad that’s all it was!
