### ISSUE TITLE
Culture tests fails

### ISSUE THREAD

**Issue by volodin-danila** [FluentValidation/FluentValidation#1386]
Hi! Two tests fail if the system culture is not en-US.

ShouldNotHaveValidationError_should_have_validation_error_details_when_thrown_ruleforeach
Falls_back_to_default_localization_key_when_error_code_key_not_found

Now
```c#
[Fact]
public void ShouldNotHaveValidationError_should_have_validation_error_details_when_thrown_ruleforeach() {
	ValidationTestException validationTestException = Assert.Throws<ValidationTestException>(() =>
		validator.ShouldNotHaveValidationErrorFor(l => l.NickNames, new[] { "magician", "bull" }));
	Assert.Contains("The length of 'Nick Names' must be at least 5 characters. You entered 4 characters.", validationTestException.Message);
}
```

Fix
```c#
[Fact]
public void ShouldNotHaveValidationError_should_have_validation_error_details_when_thrown_ruleforeach() {
	ValidatorOptions.LanguageManager.Culture = new CultureInfo("en-US");
	ValidationTestException validationTestException = Assert.Throws<ValidationTestException>(() =>
		validator.ShouldNotHaveValidationErrorFor(l => l.NickNames, new[] { "magician", "bull" }));
	Assert.Contains("The length of 'Nick Names' must be at least 5 characters. You entered 4 characters.", validationTestException.Message);
}
```

I can do a pull request.

**Comment by JeremySkinner** [comment]
Hi, thanks, yes a pull request would be great. It should just be a case of calling CultureScope.SetDefaultCulture in the test class constructor. Thanks!

**Comment by volodin-danila** [comment]
Hello again, 

tests are fixed. Thank you for your great work!

https://github.com/FluentValidation/FluentValidation/pull/1387

**Comment by JeremySkinner** [comment]
Sorry I probably wasn't clear. The call to `CultureScope.SetDefaultCulture()` should go into the test class itself, not inside the `TestValidator`

**Comment by volodin-danila** [comment]
Уou are right, I misunderstood the placement of SetDefaultCulture. Made a new pull request.

**Comment by JeremySkinner** [comment]
Merged, thanks
