### ISSUE TITLE
Using InlineValidator for business scenarios

### ISSUE THREAD

**Issue by volodin-danila** [FluentValidation/FluentValidation#1389]
Hi! I'm trying to use FluentValidation without using AbstractValidator through inline validation in my services. I found a great way - this is InlineValidator. But there are no examples about it in the documentation, unit test cases only in source code.

My great way:

```c#
public class LogicService : ILogicService
{
    private readonly IDataService _dataTestService;
    public LogicService(IDataService dataTestService)
    {
        _dataTestService = dataTestService;
    }

    public async Task<ValidationResult> Test()
    {
        var inn = await _dataTestService.GetInn();

        var instance = new Client { Inn = inn };

        var validator = new InlineValidator<Client>();

        if (instance.Inn.StartsWith("1"))
            validator.RuleFor(x => x.FullName).NotNull();

        return await validator.ValidateAsync(instance);
    }
}
```

Is it correct for business scenarios, can there be problems?

Thanks!

**Comment by JeremySkinner** [comment]
Yes, this will work correctly, although generally I'd usually only suggest using InlineValidator for prototyping. As I've explained to you before, inheriting from AbstractValidator and defining rules in the constructor is the intended way of using this library.
