### ISSUE TITLE
Add information about regexp placeholder for Regular Expression Validator to documentation

### ISSUE THREAD

**Issue by anreton** [FluentValidation/FluentValidation#1392]
First of all, I want to thank you for such an excellent tool as FluentValidation.

Secondly, I noticed some out of sync in the documentation.

Open the Regular Expression Validator section - https://docs.fluentvalidation.net/en/latest/built-in-validators.html#regular-expression-validator

In the placeholders list, we see only:
- PropertyName
- PropertyValue

Although there is RegularExpression in the implementation (line 61 - https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation/Validators/RegularExpressionValidator.cs.

It is worth correcting the documentation.

Thank you.

**Comment by JeremySkinner** [comment]
Hi, yes looks like that was just an oversight. If you (or someone else) would like to create a PR to resolve this that'd be great, otherwise I'll try to get to it when I have some time. Thanks.
