### ISSUE TITLE
FluentValidations caused an issue with System.Text.Json.Serialization.JsonIgnoreAttribute

### ISSUE THREAD

**Issue by humza-tufail-confiz** [FluentValidation/FluentValidation#1393]
**Which version of FluentValidation are you using?**
I am using FluentValidation.AspNetCore (8.62)

**Which version of ASP.NET are you using?**
I am using FluentValidations with ASP.NET Core 3.1

**Describe the issue that you're having**
we are using Newtonsoft.json.JsonIgnoreAttribute to ignore the serialization of any particular property in the model, but recently Microsoft has introduced **System.Text.Json.Serialization.JsonIgnoreAttribute** and  **Newtonsoft.json.JsonIgnoreAttribute** is no longer working with ASP.NET Core 3.1. The issue with the FluentValidations is when we use the **System.Text.Json.Serialization.JsonIgnoreAttribute** then **validators validates the request before the control is transferred to the controller action method on PUT/POST calls**. But, when I commented out the System.Text.Json.Serialization.JsonIgnoreAttribute then everything is working as expected.

Startup.cs:
```services.AddMvc().AddFluentValidation(o =>
{
 o.RegisterValidatorsFromAssemblyContaining<AddAgendaValidations>();
}).AddNewtonsoftJson();
```

Models.cs:
```public class AddPatientVitalCommand : IRequest<AddVitalDTO>
    {
        public List<Vitals> HealthRecords { get; set; }

        [JsonIgnore] 
        public Guid StaffId { get; set; }

        [JsonIgnore]
        public Guid PatientId { get; set; }

}
```

Validator: 
```public class AddPatientVitalCommandValidations : AbstractValidator<AddPatientVitalCommand>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddPatientVitalCommandValidations"/> class.
        /// </summary>
        public AddPatientVitalCommandValidations()
        {
            RuleFor(x => x.StaffId).NotNull().NotEmpty().NotEqual(Guid.Empty);
            RuleFor(x => x.PatientId).NotNull().NotEmpty().NotEqual(Guid.Empty);
            RuleFor(x => x.HealthRecords).NotNull().NotEmpty().Must(x => x.Any());
            RuleForEach(x => x.HealthRecords).SetValidator(new VitalsValidator());
        }
 }
```

**Comment by JeremySkinner** [comment]
Hi there, this isn't actually anything to do with FluentValidation. This is entirely under the control of the ASP.NET pipeline - it's not something that we have any control over.

**Comment by JeremySkinner** [comment]
Also please note that Guids are non-nullable value types. If you don't specify a value, then the ASP.NET pipeline may well will generate error messages for these properties such as "A value is required". 

Note that these messages *do not come from FluentValidation* - they come from ASP.NET itself. 

To stop receiving these messages you would need to mark the guids as nullable.
