### ISSUE TITLE
Db validation for ForeignKeys. Best practises

### ISSUE THREAD

**Issue by elciopa** [FluentValidation/FluentValidation#1394]
This is a question and not an issue. I was not able to find anything specific on this. 
Suppose you're using EFCore (but this problem arises even with NHibernate or other ORMs). What's the best practises for Foreign Keys DB validation? 
I mean, suppose I have a request like this:

```
public class MeasureRequest
    {
        public long Id { get; set; }

        public long OtherEntityId { get; set; }
    }
```

and I would like to use FluentValidation to check that the  property OtherEntityId passed is a "valid" id. 
I know I could use the DI and inject the DbContext on the validator but, do you usually do that? Is this the best practise or is preferred to do validation of Foreign Keys on the "business logic" (in my case, since I'm using MediatoR, I should do this validation on the Handler part).

Thanks for any help.

**Fluent Validation 8.6.2**
**Net Core 3.1**

**Comment by JeremySkinner** [comment]
Hi,

Honestly it's really up to you and what you feel makes most sense in your application. Personally I'd inject the db context directly (or maybe a `Func<DbContext>` to avoid lifecycle/scoping issues if your validators are registered as singletons).

**Comment by elciopa** [comment]
Hi,
thanks for your reply. 
Can you give me a simple example of this `Func<DbContext>` ? I would be really interested on this approach.

**Comment by JeremySkinner** [comment]
It's a simpler alternative to having a factory class. https://espressocoder.com/2018/10/08/injecting-a-factory-service-in-asp-net-core/

**Comment by elciopa** [comment]
Wow looks awesome. Thanks for your help.
