### ISSUE TITLE
Transform in older version

### ISSUE THREAD

**Issue by Binjaaa** [FluentValidation/FluentValidation#1397]
**Which version of FluentValidation are you using?**
7.4

**Describe the issue that you're having**
I know there is a `Transform` function after v8.0 but unfortunately, I can't update the .Net framework version (4.5) of the project, therefore the package version. Is there a way to achieve this with a custom code somehow?

**Comment by JeremySkinner** [comment]
Hi,

7.5 is the first version that `Transform` was available in. For 7.4 and older you can perform your transformation inside the `RuleFor` call directly, eg `RuleFor(x => SomeTransformation(x.Foo))` etc. 

A few things to note:
- If you do this, you'll have to explicitly call `OverridePropertyName` in your rule chain, as FluentValidation won't automatically be able to work out the name of the property. 
- Doing this bypasses the expression cache, which has a performance impact, although this is unlikely to be noticeable unless you're repeatedly instantiating the validator a huge number of times

Also:
FluentValidation 8.x _is supported_ on.NET Framework 4.5, so it is perfectly possible to upgrade to FluentValidation 8.x without upgrading your version of .NET. That being said, [.NET 4.5 is no longer supported by Microsoft (support ended in 2016)](https://support.microsoft.com/en-us/lifecycle/search/548). .NET 4.5.2 is the oldest version that they still support, so I'd highly suggest you consider upgrading to at least 4.5.2.

**Comment by Binjaaa** [comment]
Hey @JeremySkinner,

Thanks for the quick feedback.

I realized the version of `System.ComponentModel.Annotations`. After resolving this dependency, I managed to use the latest _8.x_ version. 👍 

Also thanks for pointing out the security aspect of using `netframework452`.
