### ISSUE TITLE
Feature Request: ComparisonProperty content

### ISSUE THREAD

**Issue by gamblen** [FluentValidation/FluentValidation#1398]
If an error has a comparison property, that property when represented in the FormattedMessagePlaceholderValues, is not getting custom formatting rules applied.

I have attached a [gist](https://gist.github.com/gamblen/bc6c6c3400f2ddb43381f718501f8c0c) that that will show it as 

'StartDateTimeDisplay' must be less than or equal to '20/05/2020 00:00:00'.
  ComparisonValue: 20/05/2020 00:00:00
  ComparisonProperty: **End Date Time**
  PropertyName: StartDateTimeDisplay
  PropertyValue: 21/05/2020 00:00:00

could it changed to 

'StartDateTimeDisplay' must be less than or equal to '20/05/2020 00:00:00'.
  ComparisonValue: 20/05/2020 00:00:00
  ComparisonProperty: **EndDateTimeDisplay**
  PropertyName: StartDateTimeDisplay
  PropertyValue: 21/05/2020 00:00:00

As it is for v9 I have applied the ValidatorOptions.Global.DisplayNameResolver.

Thanks.

**Comment by JeremySkinner** [comment]
I'll take a look at the feasibility of adding this for 9.0.

**Comment by JeremySkinner** [comment]
Added in 9.0.0-preview5. 

Please give it a try and re-open this issue if you run into problems.
