### ISSUE TITLE
Preview5: Validate(object) is no longer available

### ISSUE THREAD

**Issue by endeffects** [FluentValidation/FluentValidation#1401]
I tried to test the latest Preview today and saw that it does not support to validate objects anymore.
This brakes the implementation of Steve Sanderson for Blazor Forms (line 32).

Currently i don't see any option to fix this, because the used class EditContext is out of my control.

https://gist.github.com/SteveSandersonMS/090145d7511c5190f62a409752c60d00#file-fluentvalidator-cs

**Comment by JeremySkinner** [comment]
The overload of `IValidator.Validate` that takes an object was removed to improve type-safety. 

However you can still achieve exactly the same result by instantiating a `ValidationContext<object>` (which takes the object in its constructor) and passing this to the overload that takes an IValidationContext. 

This is how the asp.net core integration works, and the Blazor component will need to do the same. 

I will be adding a section on this to the 9.0 upgrade guide but haven’t got round to it yet.

**Comment by endeffects** [comment]
Thank you very much :)
