### ISSUE TITLE
MissingMethodException when validating with RootContextData

### ISSUE THREAD

**Issue by brench** [FluentValidation/FluentValidation#1409]
**Which version of FluentValidation are you using?**
8.6.2

**Which version of ASP.NET are you using?**
ASP.NET 4.0.0.0
.NET Framework 4.6.1

**Describe the issue that you're having**
I have a validator (inheriting from AbstractValidator) that has a RuleFor that accesses a value from ValidationContext.RootContextData.

The validator works when called from my controller, but in my unit test (using XUnit), when I call the Validate method on my validator, I get a MissingMethodException:

Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> FluentValidation.ValidationContext.get_RootContextData()'.

If I comment out the use of RootContextData in my RuleFor body, I can step into my RuleFor from the unit test, and I see that the data I set in RootContextData is there.

I'm wondering if there is a way to get the unit test to work or if this is a bug.

Thank you in advance.

**Comment by JeremySkinner** [comment]
Hi, this is unlikely to be a bug in FluentValidation itself. 

Please can you start by confirming the exact versions for the following that you’re referencing in your test project so we can check if it’s a mismatch in package versions:

- the FluentValidation package 
- the FuentValidation.Mvc5 package (if you’re using it) 
- the FluentValidation.WebApi package (if you’re using it)
- the version of the Microsoft.AspNet.Mvc package (if you’re using it)
- the version of Microsoft.AspNet.WebApi.Core (if you’re using it
- .net framework version (definitely 4.6.1?) 

Secondly please include the sample code necessary to reproduce the issue (a minimal, reproducible sample). Either include the code in this issue or create a repo containing a runnable project that I can look at.

**Comment by brench** [comment]
I was able to resolve this by upgrading my FluentValidation package.  I thought I had already done that, but apparently not.

I was using version 7.3.4 when I received the error.  I'm now using version 8.6.2 and everything works fine.

I haven't been able to re-create the error in a separate project; if I do manage to do that, I'll create a repo.

Thank you for your response.  It got me working on trying to repro the error in a separate project, which eventually helped lead me to solving the issue.
