### ISSUE TITLE
Multiple validators for same model in ASP .Net Core

### ISSUE THREAD

**Issue by uhfath** [FluentValidation/FluentValidation#1410]
If i define multiple validators for one model, which one will be used with automatic model validation in ASP .Net Core controller request? And how to define specific one?

**Comment by JeremySkinner** [comment]
>  which one will be used with automatic model validation in ASP .Net Core controller request

The assembly-scanning process will register them all with the container, and ASP.NET core will pick the first, so there's no guaranteed order.

> And how to define specific one?

Register them manually instead of using auto-registration, eg: `services.AddTransient<IValidator<Person>, PersonValidator>();` 

It's the `IValidator<T>` -> Concrete type mapping that determines which one is picked

**Comment by uhfath** [comment]
Perhaps i could register them automatically and then post-register manually the reset, which are doubles. Will this work? If not, i guess the other way around is to use rule sets. Really don't like the idea to register ALL validators manually.

**Comment by uhfath** [comment]
Interesting.
I've used your solution like this:
```c#
AssemblyScanner
	.FindValidatorsInAssemblyContaining<TStartup>()
	.ForEach(scanResult => 
	{
		var isAsync = scanResult.ValidatorType.Name.EndsWith("Async", StringComparison.OrdinalIgnoreCase);
		if (!isAsync)
		{
			services.AddTransient(scanResult.InterfaceType, scanResult.ValidatorType);
		}
	});
```
The interesting part is that i still can request my "Async" validator from DI where needed, even though it wasn't added here.
Why?

**Comment by JeremySkinner** [comment]
Guessing you probably have something else in the application that is still registering it? Without seeing the code I can’t really know...

**Comment by uhfath** [comment]
I feel so stupid right now.
Was searching the entire project for "fluent" word to see if i missed something.
Found "AddValidatorsFromAssemblyContaining" in some abandoned parts.

Sorry for wasting your time and thanks again...
