### ISSUE TITLE
CustomAsync method does not change ModelState

### ISSUE THREAD

**Issue by rajmondburgaj** [FluentValidation/FluentValidation#1412]
I am using Asp.Net Core V3. My code looks like below:

```
RuleFor(x => x.ApplicationName)
    .NotEmpty().WithMessage("Application name is required to continue")
    .CustomAsync(async (appName, context, cancellationToken) =>
    {
        var application = await applicationProvider.GetLatestApplicationWithContextValuesAsync(appName, false);
        if(application != null)
            context.AddFailure($"Application with name: {appName} already exists.");
    });
```

I am able to debug the app and see that context.AddFailure is executed but the ModelState does not reflect the validation error. 

Is this intentional or a bug ?

When some validation fail while using RuleFor the ModelState change is reflected.

**Comment by JeremySkinner** [comment]
Hi there, 

You haven't provided the requested information on which version of FluentValidation you're using. Please can you ensure you provide this.

Are you using the automatic validation with ASP.NET, or are you invoking the validator manually? If you're using the automatic validation then the first thing I'll point out is that *you should not use async validation in ASP.NET Core*. Please see the big warning on this page: https://docs.fluentvalidation.net/en/latest/async.html ASP.NET's validation pipeline is *completely synchronous* so calling `CustomAsync` (or any other async method) will end up running synchronously. You should change this to `Custom`. 

Assuming you are using automatic validation then any failures that are added with `AddFailure` will automatically be added to ModelState. If you're not seeing this happen once you change CustomAsync to Custom then please provide a small sample project that reproduces the issue.

**Comment by rajmondburgaj** [comment]
Hi,

Thanks for giving me some details about how fluent validation works, basically for now I am doing automatic validation. The package version is the latest one from nuget: 8.6.2. I will try and do manual validation and see how it goes. Maybe building a wrapper factory around it would help for unit testing.

```c#
interface IFluentValidationFactory
{
      IValidator <T> CreateValidator<T>();
}
```

And from this factory I can just get the validator and do the validation.

Not sure if there is such a thing in the package included thou..

**Comment by JeremySkinner** [comment]
> Maybe building a wrapper factory around it would help for unit testing

Yes, `IValidatorFactory` already exists and is included in the library. The default implementation resolves validators from the asp.net service provider. Although you don't really need to use this - you can just inject or resolve validator instances directly. 

> This is how my registration looks like:

Yes, that means you're using automatic validation. 

If you can provide a sample project that reproduces the issue I'll be able to look further.

**Comment by rajmondburgaj** [comment]
Great, started using the factory instead of injecting `IValidator<>` instance because if my controller has 20 models to validate in different actions I don't want to pollute the constructor by injecting 20 instances of `IValidator<MyModel_XXX>`.

This works fine, and now I guess my validations are running asynchronously using the below method:

```c#
var validator = factory.GetValidator<T>();
var result = await validator.ValidateAsync(model);
```

But I think I am facing a strange issue:
Since I call `AddFluentValidation()` method on startup because I want to register the factory, it also adds some custom `IObjectModelValidator` [here](https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L105). Did not check in details how it works but my feeling is that if you call `AddFluentValidation()` method there is no way how to stop automatic validation from happening. Therefore, I end up executing the validation code twice, one time automatically from the library and secondly manually in the action itself.

Is there any way how to stop automatic validation and also have the factory injected ?

I can inject it myself but I guess it is not the best approach!

About the repo:

Will try to create one this weekend and reproduce it, as soon as I am done will share it here.

Thanks for the support!

**Comment by JeremySkinner** [comment]
> Did not check in details how it works but my feeling is that if you call AddFluentValidation() method there is no way how to stop automatic validation from happening

Calling `AddFluentValidation` is what enables automatic validation. If you don't want automatic validation, then don't call `AddFluentValidation` in your startup. Instead just register the services you need directly with the service provider:

```csharp
// Don't call AddFluentValidation, as this enables automatic validation.
services.AddControllers().ConfigureApiBehaviorOptions(...);

// Register the services you need.
services.AddTransient<IValidatorFactory, ServiceProviderValidatorFactory>();
services.AddControllresFromAssemblyContaining<MyValidator>();
```

Note that by switching to manual validation like this you also lose clientside validation integration (but this is no big loss as it's very limited anyway).

**Comment by JeremySkinner** [comment]
Alternatively, you can leave automatic validation enabled (if you want it in some other places) and instead use `[CustomizeValidator(Skip=true)]` on the parameter declaration (see https://docs.fluentvalidation.net/en/latest/aspnet.html#validator-customization)

**Comment by rajmondburgaj** [comment]
> > Did not check in details how it works but my feeling is that if you call AddFluentValidation() method there is no way how to stop automatic validation from happening
> 
> Calling `AddFluentValidation` is what enables automatic validation. If you don't want automatic validation, then don't call `AddFluentValidation` in your startup. Instead just register the services you need directly with the service provider:
> 
> ```cs
> // Don't call AddFluentValidation, as this enables automatic validation.
> services.AddControllers().ConfigureApiBehaviorOptions(...);
> 
> // Register the services you need.
> services.AddTransient<IValidatorFactory, ServiceProviderValidatorFactory>();
> services.AddControllresFromAssemblyContaining<MyValidator>();
> ```
> 
> Note that by switching to manual validation like this you also lose clientside validation integration (but this is no big loss as it's very limited anyway). Also be aware that ASP.NET's model binding process will also still generate some error messages prior to FluentValidation being invoked (eg if you omit a value for a non-nullable value type).

That is fine, will use this approach then, thanks for details :)

**Comment by rajmondburgaj** [comment]
Hi,

Created a new project from scratch and I was not able to reproduce(it works as expected), maybe some issues on my code. Therefore I am closing this ticket because most probably it was my mistake.

Thanks for the support :)
