### ISSUE TITLE
Usage of IDisposables in validators

### ISSUE THREAD

**Issue by uhfath** [FluentValidation/FluentValidation#1413]
My validator requires some disposable classes to be used.
I create them in a constructor but don't know when to dispose them.
Something like:
```c#
public class ViewModelValidator : AbstractValidator<ViewModelValidator>
{
    private readonly Stream fileStream; //just as an example. the real case uses other disposable classes

    public ViewModelValidator()
    {
        fileStream = File.OpenRead("path_to_file"); //when do i dispose this?

        RuleFor(m => m.prop_1)
            .Must((model, prop) =>
            {
                fileStream.Read(...) //disposable used here
            })
        ;

        RuleFor(m => m.prop_2)
            .Must((model, prop) =>
            {
                fileStream.Read(...) //and here
            })
        ;
    }
}
```

**Comment by uhfath** [comment]
On a second thought, since validators are instantiated from DI, which uses request scope, i could inherit the validator itself from IDisposable and dispose it's members in it.
Is this correct?

**Comment by JeremySkinner** [comment]
In ASP.NET applications, validators are registered as transient, not request-scoped. Regardless, this doesn't change that the stream should not be opened at the point the rules are defined. It should be opened at the point validation occurs as per my example.

**Comment by JeremySkinner** [comment]
My first post disappeared for some reason.

The stream shouldn't be opened at the point the rules are defined, but rather at the point validation occurs, the simplest way to do that would be to open and dispose the stream inside the `Must` callback

**Comment by uhfath** [comment]
Thanks.
I thought about that but didn't want to create the required resources on every rule usage.
Also there are cases where validator's constructor is used to get some services out of DI which could be disposables.

**Comment by JeremySkinner** [comment]
Ok, if you don't want to recreate the resource then you could override the `Validate` method, and open the stream in there, store it in the ValidationContext's `RootContextData` and then access it inside the callbacks:

```csharp
public TestValidator() {
	RuleFor(x => x.Surname)
		.Must((model, propertyValue, context) => {
			var stream = (Stream) context.ParentContext.RootContextData["stream"];
			// ...
		});
}

public override ValidationResult Validate(ValidationContext<Person> context) {
	using (var stream = File.OpenRead("...")) {
		context.RootContextData["stream"] = stream;
		return base.Validate(context);
	}
}
}

public override ValidationResult Validate(ValidationContext<Person> context) {
	using (var stream = File.OpenRead("...")) {
		context.RootContextData["stream"] = stream;
		return base.Validate(context);
	}
}
```

That's how I would recommend you do it. But if you wanted to experiment with making the validator IDisposable then that may well work too, but the validators are instantiated multiple times during a single request (eg if there are multiple instances that need to be validated , and obtaining clientside metadata) which would mean the file stream ends up being multiple times anyway, so I would recommend opening it only during the `Validate` method.

**Comment by uhfath** [comment]
Thanks for the idea.
But you've mentioned that validators are registered as transient.
Perhaps it would be possible to override setup process to register them as scoped? Or there could be some issues with this?

**Comment by JeremySkinner** [comment]
You can override the lifecycle if you want, but it is intentionally registered as transient to prevent dependency scoping issues. Many developers are unaware of the issues of having singleton-scoped objects depend on a transient/request-scoped object etc and the problems this cause, so we register them as transient to avoid these kind of issues. If you know what you're doing and are aware of the possible consequences of getting it wrong then feel free to change it.

**Comment by uhfath** [comment]
I see. Thanks for the info.
I'll experiment with both ideas.
