### ISSUE TITLE
Stop validating child validators on first failure with CascadeMode.StopOnFirstFailure

### ISSUE THREAD

**Issue by Crapulator** [FluentValidation/FluentValidation#1415]
Hi,

First of all, thank you for this awesome project :)

As described in the title, I would like to stop validations when one of child validators fails.

For example, this is a small project to reproduce my issue.

I have the following models :
```
public class Customer
{
    public string Name { get; set; }

    public Address Address { get; set; }

    public Cart Cart { get; set; }
}

public class Address
{
    public string City { get; set; }
}

public class Cart
{
    public string Id { get; set; }
}
```
And the following validators :
```
public class CustomerValidator : AbstractValidator<Customer>
{
    public CustomerValidator()
    {
        this.RuleFor(c => c.Name).NotEmpty();

        this.RuleFor(c => c.Address).SetValidator(new AddressValidator());

        this.RuleFor(c => c.Cart).SetValidator(new CartValidator());
    }
}

public class AddressValidator : AbstractValidator<Address>
{
    public AddressValidator()
    {
        this.RuleFor(a => a.City).NotEmpty();
    }
}

public class CartValidator : AbstractValidator<Cart>
{
    public CartValidator()
    {
        this.RuleFor(c => c.Id).NotEmpty();
    }
}
```
And my unit test that currently fails because the properties Address.City and Cart.Id are empty so there are two errors in the `ValidationResult` returned by `Validate()` or `ValidateAync()`.
```
[Test]
public void Test1()
{
    var validator = new CustomerValidator();
    var customer = new Customer
    {
        Name = "Name",
        Address = new Address(),
        Cart = new Cart()
    };

    var result = validator.Validate(customer);

    result.Errors.Should().HaveCount(1);
}
```
I tried some solutions to prevent further validations from child validators when one of them fails, but with no success.
When I look into the source code of `AbstractValidator`, I think this is impossible right now because of this line: `var failures = Rules.SelectMany(x => x.Validate(context));` in the method `Validate()` line 92.
All rules are validated and there is no check on the value `StopOnFirstFailure` of the property `CascadeMode`.

Is there any way to achieve what I want? If there's not, what do you think about checking the value of `CascadeMode` before validating the next rule in the synchronous and asynchronous validation?

Thank you.

**Comment by JeremySkinner** [comment]
Hi there,

CascadeMode only affects validators *within the same rule chain*, eg:

```RuleFor(x => x.Foo).NotNull().NotEqual("bar")```

If you set Cascade to StopOnFirstFailure, then the `NotEqual` would  only be run if the `NotNull` passes. It doesn't affect *separate calls to RuleFor*, which is intentional and by design. [Please see the documentation for CascadeMode](https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode).

You would need to use `DependentRules` to achieve what you want. [The documentation for that is here](https://docs.fluentvalidation.net/en/latest/conditions.html#dependent-rules).

**Comment by Crapulator** [comment]
Thank you for your quick response.

Something like this?

```
public class CustomerValidator : AbstractValidator<Customer>
{
    public CustomerValidator()
    {
        this.RuleFor(c => c.Name)
            .NotEmpty()
            .DependentRules(() =>
            {
                this.RuleFor(c => c.Address)
                    .SetValidator(new AddressValidator())
                    .DependentRules(() =>
                    {
                        this.RuleFor(c => c.Cart).SetValidator(new CartValidator());
                    });
            });
    }
}
```

It was one of the solutions I tried but I didn't feel like it was a good way to achieve what I wanted.
The models in my example are simple but when there are 10 properties, the code looks dirty with all these imbrications.

**Comment by JeremySkinner** [comment]
Yes, that's the only way to achieve what you're after. FluentValidation's rules are not really designed to be dependent on one another as their order of execution isn't guaranteed. By nesting them like this you guarantee that the dependent rules will only be executed if the parent rule succeeds. It's not particularly pretty, but it will achieve what you're after.

**Comment by Crapulator** [comment]
Thank you very much for your explanation.
