### ISSUE TITLE
WithSeverity doesn't work

### ISSUE THREAD

**Issue by AndrewGumenyuk** [FluentValidation/FluentValidation#1416]
**FluentValidation Version: 8.6.2
.NET Core 3.1**

I have this kind of validator:

```
public class StatRequestValidator : AbstractValidator<StatRequest>
    {
        public StatRequestValidator()
        {
            RuleFor(req => req.FromDate)
                .NotEmpty()
                .WithSeverity(Severity.Info);

            RuleFor(req => req.ToDate)
                .NotEmpty()
                .WithSeverity(Severity.Info);
        }
    }
```

```
Injecting in StartUp: .AddTransient<IValidator<StatRequest>, StatRequest>()
Calling like this:  var result = _requestValidator.Validate(requestModel);
```

The ValidationResult (result) has two errors, like: "FromDate should not be empty" and "FromDate should not be empty".

If I correctly understand the main purpose of WithSeverity, ValidationResult should not have any errors and should not throw an exception if I call ValidateAndThrow.

Please, Could you check it?
If I'm right let me know if no, correct me.

Thanks!

**Comment by JeremySkinner** [comment]
Hi, it's working as expected.

Using `WithSeverity` doesn't prevent the ValidationResult from being populated - it just sets the `Severity` property on each validation failure.

Example:

```csharp
public class PersonValidator : AbstractValidator<Person> {
  public PersonValidator() {
        RuleFor(person => person.Surname).NotNull().WithSeverity(Severity.Warning);;
        RuleFor(person => person.Forename).NotNull();
  }
}
```


When you call Validate the ValidationResult will still contain 2 ValidationFailures, but one will have a severity of Error and the other will have a severity of Warning. This is all that calling `WithSeverity` does. You can then filter these as you like.

```csharp
var validator = new PersonValidator();
var result = validator.Validate(new Person());
foreach (var failure in result.Errors) {
  Console.WriteLine($"Property: {failure.PropertyName} Severity: {failure.Severity}");
}
```

The output would be:

```
Property: Surname Severity: Warning
Property: Forename Severity: Error
```

**Comment by AndrewGumenyuk** [comment]
Thanks for your answer. 

So, the result has errors and for each error, we have a severity level - from my side it's a little confused.
Perhaps, if you don't mind, it would be better a little more to describe the Severity level in the documentation.

Big thank, Jeremy.

**Comment by JeremySkinner** [comment]
I've literally just merged https://github.com/FluentValidation/FluentValidation/pull/1408 which adds a section on severity levels to the documentation, it should be deployed shortly

**Comment by AndrewGumenyuk** [comment]
Wow, awesome.
5 minutes ago)
![image](https://user-images.githubusercontent.com/12097084/84132866-0fa79280-aa4f-11ea-9552-ac8d5eab8ab5.png)

**Comment by JeremySkinner** [comment]
This issue reminded me that I hadn't merged it yet! 

It's on the docs site now at https://docs.fluentvalidation.net/en/latest/severity.html

**Comment by AndrewGumenyuk** [comment]
So, the issue was helpful - it's good)
