### ISSUE TITLE
Can I use FlentValidation with WorkerService and MediatR

### ISSUE THREAD

**Issue by iozcelik** [FluentValidation/FluentValidation#1417]
**Which version of FluentValidation are you using?**
v8.6.2

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I have a WebApi working with Angular 9 and I use FluentValidation and MediatR. It is working fine. However, I need to implement multiple worker service now. So, is there a way to using fluent validation with Dependecy Injection?

I use` _validator.Validate` inside my methods but I hope there will be an easy way.
```
using (var scope = Services.CreateScope()) {
                    var mediator =
                        scope.ServiceProvider
                            .GetRequiredService<IMediator>();
                    var context =
                        scope.ServiceProvider
                            .GetRequiredService<IMyDbContext>();
                    _validator = new UpsertCategoryCommandValidator(context);

                    var newCategory = new UpsertCategoryCommand { Name = "CategoryName" };
                    var validationResult = _validator.Validate(newCategory);
                    if (validationResult.IsValid) {
                        var result = await mediator.Send(newCategory);
                    }
                }
```

**Comment by JeremySkinner** [comment]
Hi, I don't really understand what you're asking. Validator classes are just like any other object - you can add them to the service provider and perform dependency injection just like anything else.

**Comment by iozcelik** [comment]
When we use controller (api or MVC), I do not need to add each one to Startup.
```
services
.AddControllersWithViews()
.AddNewtonsoftJson(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver())
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<IMyDbContext>());
```
However in worker service, how I add them?

**Comment by JeremySkinner** [comment]
The `AddFluentValidation` call is specifically for adding the ASP.NET integration - if you're not using this then you don't need to call this method. 

Just register your validators directly with the service provider.

**Comment by iozcelik** [comment]
I am looking for `services.AddValidatorsfromAssemblyContaining<PersonValidator>();` Thanks.

**Comment by JeremySkinner** [comment]
As I said in my example, you need to have the FluentValidation.DependencyInjectionExtensions package installed for that method to show up as it's an extension method.
