### ISSUE TITLE
Change extension methods namespace

### ISSUE THREAD

**Issue by bdovaz** [FluentValidation/FluentValidation#1420]
Please, as a good practice you should use the same namespace of the type you are extending:

https://github.com/FluentValidation/FluentValidation/blob/ea12a0b2515d1c49fb1768a2b3f290e965333006/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs#L19

From:

namespace FluentValidation {

To:

namespace Microsoft.Extensions.DependencyInjection {

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this was an intentional and conscious decision. Libraries should not intentionally pollute the namespace of external assemblies that they don’t control. Importing extension methods should be an explicit decision by the *consumer*, not by the library author.
