### ISSUE TITLE
CascadeMode.StopOnFirstFailure doesn't stop at first failure

### ISSUE THREAD

**Issue by ludydoo** [FluentValidation/FluentValidation#1421]
**Which version of FluentValidation are you using?**
9 preview 2 (ServiceStack)

**Which version of ASP.NET are you using?**
Net Core 3.1

**Describe the issue that you're having**
Either I misunderstand the intended behavior of CascadeMode, or there is a bug with it. Setting CascadeMode.StopOnFirstFailure continues after the first failure.

```
public class Dummy
        {
            public bool IsBla { get; set; }
            public List<DummyItem> Items { get; set; } = new List<DummyItem>();
        }

        public class DummyItem
        {
            public string Name { get; set; }
        }

        public class DummyValidator : AbstractValidator<Dummy>
        {
            public DummyValidator()
            {
                CascadeMode = CascadeMode.StopOnFirstFailure;
                RuleFor(dummy => dummy.IsBla).Equal(true);
                RuleForEach(dummy => dummy.Items).SetValidator(dummy =>
                {
                    var subValidator = new InlineValidator<DummyItem>();
                    subValidator.RuleFor(item => item.Name).MinimumLength(1);
                    return subValidator;
                });
            }
        }

        [Test]
        public void ShouldStopAtFirstError()
        {
            
            var dummy = new Dummy()
            {
                IsBla = false,
                Items = new List<DummyItem>()
                {
                    new DummyItem()
                    {
                        Name = ""
                    }
                }
            };

            var validationErrors = new DummyValidator().Validate(dummy);
            Assert.That(validationErrors.Errors.Count, Is.EqualTo(1));
        }
```

**Comment by JeremySkinner** [comment]
Hello, I think you've misunderstood how CascadeMode works. CascadeMode only applies to *validators within the same RuleFor chain* it does not apply to separate calls to RuleFor. 

Please see the documentation for details: https://docs.fluentvalidation.net/en/latest/conditions.html?highlight=cascade#setting-the-cascade-mode

Please also take a look at the DependentRules section, which is probably what you want instead: https://docs.fluentvalidation.net/en/latest/conditions.html?highlight=cascade#dependent-rules
