### ISSUE TITLE
Dynamic DisplayNameResolver

### ISSUE THREAD

**Issue by dschuermans** [FluentValidation/FluentValidation#1422]
**Which version of FluentValidation are you using?**
8.4.0

**Which version of ASP.NET are you using?**
None, class library in .NET standard 2.0

**Describe the issue that you're having**
Due to the static nature of ValidatorOptions.DisplayNameResolver, code is being called in places we didn't expect.

Our sofware consists out of several "modules", where in one of these modules we are specifying a custom func for DisplayNameResolver, because the display name:
1.) Does not match the property name (eg property X is displayed as "Coordinate X" to the user)
2.) Depending on the context, the display name is dynamic. (eg property X is displayed as "Coordinate X [m]" when unit system is set to metric, while it is displayed as "Coordinate X [in]" when unit system is set to imperial)
Another module also uses FluentValidation, but does not have this requirement.

I initially ran into this issue before, and i "solved" it by first storing the default DisplayNameResolver func in a variable, then assigning my custom func to it, run the validators and then restore the original DisplayNameResolver func.
While this seems to have worked in that particular case, we are now running into issues where this code is called via an Azure function and there is a chance that validation is triggered in 2 different requests that are handled by the same instance.
E.g. the instance could be running the validation from Module A and the validation from Module B at the same time, causing FluentValidation from Module B to use the DisplayNameResolver func declared by Module A

I've been going through the documention / issues with keyword DisplayNameResolver, but none of them seem to have run into the issue I'm having.

I was wondering if you could point me in the right direction to look for a possible solution?

The way our validation is setup is as follows:

We register a collection of IValidator<T> on our container. (Each module has its own container and scope fyi)
We have a "ValidatorFactory" service that we can use to retrieve an instance of a validator for a given type
We then run IValidator.Validate(ValidationContext) and process the validation result.

Ideally, it would've been nice if we could pass a ValidatorOptions instance to the ValidationContext when running the Validate method from IValidator :)

**Comment by JeremySkinner** [comment]
Hi,

The DisplayNameResolver is a global option that should only ever be set once at application start up (it's not thread safe to change this once its been set). You should not set it multiple times, nor should you attempt to switch it once its been set.

The correct way to handle this is to have the switching logic *inside* the function. IE you set the DisplayNameResolver once only at application startup, and inside it you call into the appropriate module-specific code as necessary depending on the type being validated.

If that isn't sufficient and you need further control of the display name process then you'll need to stop using the resolver and instead explicitly set the display names by calling `WithName` in the rule definition

> Ideally, it would've been nice if we could pass a ValidatorOptions instance to the ValidationContext

This is something I've looked at before, but it's not really practical for the majority of options. The DisplayNameResolver is not actually invoked during a call to `Validate` - it is invoked when the validator is initially built (ie when the constructor is run). It is also invoked by ASP.NET's client-side validation infrastructure, which again happens outside of a call to `Validate`, so it needs to be something that is globally available. 

Hope that makes sense

**Comment by dschuermans** [comment]
Hi Jeremy,

Thanks for your response.
We now have a few options to explore, thanks.
