### ISSUE TITLE
Inconsistency with splitting ruleset

### ISSUE THREAD

**Issue by tomek-anuszkiewicz** [FluentValidation/FluentValidation#1424]
**Which version of FluentValidation are you using?**
8.6.2

**Describe the issue that you're having**

When you use `Validation` extension method ruleset are split like (note `Trim()` at the end):

```csharp
IEnumerable<string> source = ((IEnumerable<string>)ruleSet.Split(',', ';'))
    .Select((Func<string, string>)((string x) => x.Trim()));
```

, but with`CustomizeValidatorAttribute` there is no `Trim()`:

```csharp
string[] ruleSets = RuleSet.Split(',', ';')
```

So for `Validation` both apply same rules from both rulesets:

```csharp
new ProjectValidator().Validate(project, ruleSet: "default,createRuleSet");
new ProjectValidator().Validate(project, ruleSet: "default, createRuleSet");
```

And for `CustomizeValidatorAttribute` only first will apply both ruleset.

**Comment by JeremySkinner** [comment]
Thanks for reporting this. I’d happily accept a pull request to make the two consistent, otherwise I’ll try and look at it myself at some point when I get time.

**Comment by tomek-anuszkiewicz** [comment]
Do we considering this as breaking change?

I may try to fix this:
- by supporting Trim() in both versions.
- fix tests
- fix docs?

**Comment by JeremySkinner** [comment]
> Do we considering this as breaking change?

I would say no, but the next scheduled release is 9.0 which is full of breaking changes anyway.

**Comment by JeremySkinner** [comment]
9.1 is now available on nuget with this change.
