### ISSUE TITLE
Nested class white space problem

### ISSUE THREAD

**Issue by dev-fatih-erol** [FluentValidation/FluentValidation#1425]
{
    "User.Id": [
        "'User. Id' must be greater than '4'." <<<<<< problem
    ]
}

 "'User. Id' 
why is there a space here?

**Comment by JeremySkinner** [comment]
This is a known issue when the display name contains a period (#1147) - the display name logic is designed to split PascalCased property names (eg UserId -> User Id) - currently this runs for nested property names too, but it shouldn’t. For now please explicitly specify the display name by calinf `WithName`

I’m going to close this issue as a duplicate - feel free to subscribe to #1147 if you want to keep an eye on development progress.
