### ISSUE TITLE
Unit test IFormFile fails

### ISSUE THREAD

**Issue by stephenstroud** [FluentValidation/FluentValidation#1427]
**Which version of FluentValidation are you using?**
FluentValidation.AspNetCore 8.6.2

**Which version of ASP.NET are you using?**
Core 3.1

**Describe the issue that you're having**
When testing IFormFile property Content-Type or Length it's throwing  System.NullReferenceException : Object reference not set to an instance of an object on all of my other fluent validation tests. How can I test this? 

FrontDocument is iFormFile and works without testing it's property type length or Content Type.

Sample code: 
 RuleFor(x => x.FrontDocument.Length).NotNull().GreaterThan(2097152).WithMessage("File size is larger than 2mb");

RuleFor(x => x.FrontDocument.ContentType).NotNull().Must(x => x.Equals("image/jpeg") || x.Equals("image/jpg") || x.Equals("image/png"))
                .WithMessage("File type is not supported");

**Comment by JeremySkinner** [comment]
Hi, this behaviour is correct. A rule for `x.FrontDocument.Length` will indeed throw a NullReferenceException if the FrontDocument property is null. You need to add a null check condition:

```csharp
RuleFor(x => x.FrontDocument.Length)
  .NotNull()
  .LessThanOrEqualTo(2097152)
  .When(x => x.FrontDocument != null)
  .WithMessage("File size is larger than 2mb");
```

Conditions with `When` and `Unless` are covered in this section in the documentation: https://docs.fluentvalidation.net/en/latest/conditions.html

**Comment by JeremySkinner** [comment]
You can also do a block-level `When` call to apply this condition to multiple rules. Eg:

```csharp
When(x => x.FrontDocument != null, () => {
  RuleFor(x => x.FrontDocument.Length).NotNull().GreaterThan(2097152).WithMessage("File size is larger than 2mb");

  RuleFor(x => x.FrontDocument.ContentType).NotNull().Must(x => x.Equals("image/jpeg") || x.Equals("image/jpg") || x.Equals("image/png"))
.WithMessage("File type is not supported");
});

**Comment by stephenstroud** [comment]
@JeremySkinner  Thank you that makes sense, I'm also receiving Expression must be writable error when unit testing this, any ideas?
 
![image](https://user-images.githubusercontent.com/7649287/86159030-99ec8f00-bb01-11ea-983f-3ef833ca1b96.png)

**Comment by JeremySkinner** [comment]
Yes, that will happen as you're trying to set a read-only property.

The `ContentType` property on the IFormFile is a read-only property - it has no setter. ShouldNotHaveValidationError will internally attempt to set the proeprty to the value you've specified, which won't work here, hence the exception.

For nested properties like this, you need to supply a pre-created object instance, explicitly setting the FrontDocument property to a pre-created instance which contains the values you want to test. Please have a read of the advanced testing section of the documentation: https://docs.fluentvalidation.net/en/latest/testing.html#advanced-test-extensions

**Comment by stephenstroud** [comment]
@JeremySkinner that worked, Very helpful! thank you.
