### ISSUE TITLE
ensure AddFluentValidation has been called from a Library

### ISSUE THREAD

**Issue by StevenTCramer** [FluentValidation/FluentValidation#1428]
**Which version of FluentValidation are you using?**
8.6.2

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I have a library that contains controllers that use FluentValidation.
In my extension method to configure the library I want to ensure that `AddFluentValidation` has already been called.

And is safe for me to call

```
      aServiceCollection.AddValidatorsFromAssemblyContaining<BaseRequest>();
      aServiceCollection.AddValidatorsFromAssemblyContaining<AriesOpenApiOptions>();
```

**Comment by JeremySkinner** [comment]
Hi

`AddFluentValidation` should only ever be called once, inside the application's startup routine. I would recommend that you *don't* call this inside your library setup method, and instead tell users to explicitly call it in your installation instructions.

**Comment by StevenTCramer** [comment]
Hey @JeremySkinner I am not calling it in my library but would like be able to ensure it has been called prior to my libraries extension method and if not throw an exception.  But I don't know how to confirm that is has been called.

**Comment by JeremySkinner** [comment]
Ah, I see. Probably the simplest thing to do would be to check if an `IValidatorFactory` has been registered with the service provider.

**Comment by StevenTCramer** [comment]
```csharp
      if (!aServiceCollection.Any(aServiceDescriptor => aServiceDescriptor.ServiceType == typeof(IValidatorFactory)))
      {
        throw new InvalidOperationException
        (
          $"You must call {nameof(FluentValidationMvcExtensions.AddFluentValidation)} " +
          $"prior to {nameof(AddAriesOpenApi)}"
        );
      }
```
Works perfectly Thanks.
