### ISSUE TITLE
Validation not working for nested list of models

### ISSUE THREAD

**Issue by surbhi05** [FluentValidation/FluentValidation#1429]
**Which version of FluentValidation are you using?**
6.1.0.1

**Which version of ASP.NET are you using?**
.NET Framework 4.6.1

**Describe the issue that you're having**
**Issue**
The list of objects inside the model are not getting validated.

**Sample classes** 
```
public class User {
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Role> Roles { get; set; }
}
public class Role {
    public string Name { get; set; }
    public string Type { get; set; }
}
public class RoleTypeInteger : Role {
    public int Value { get; set; }
}
public class RoleTypeString : Role {
    public string Value { get; set; }
}
```
**Validator classes**
```
public class UserValidator : AbstractValidator<User>
{
    public UserValidator()
    {
        RuleFor(x => x.Name).NotNull();
    }
}
public class RoleTypeIntegerValidator: AbstractValidator<RoleTypeInteger>
{
     public RoleTypeIntegerValidator()
     {
         RuleFor(x => x.Value).InclusiveBetween(10, 30);
     }
}
public class RoleTypeStringValidator: AbstractValidator<RoleTypeString>
{
     public RoleTypeStringValidator()
     {
         RuleFor(x => x.Value).Length(128);
     }
}
```

**MVC Controller**
```
public ActionResult MyMethod([ModelBinder(typeof(UserModelBinder))] User viewModel) {...}
```

Now in my model binder, I convert the received roles to their specific models based on the type property.

**Issue**
The model state is valid even when the validation error should be present.

**Ruled out issues**
Earlier I assumed that there might have been an issue with model binder or polymorphic models, but I tried updating the User model with the following code, where I was only trying to test one type of model, but it still doesn't work.
```
public class User {
    public int Id { get; set; }
    public string Name { get; set; }
    public List<RoleTypeInteger> Roles { get; set; }
}
```

Please suggest what am I missing here.

**Comment by JeremySkinner** [comment]
Hello,

You're using a very old and unsupported version of FluentValidation, so I can't really provide much help with this I'm afraid. However, I suspect the issue is likely to be the model binder - if I remember correctly ASP.NET MVC does not perform validation when using a custom model binder - it bypasses the process. You can confirm this by overriding the validator's `Validate` method (the overload that accepts a ValidationContext). If this method is not invoked, then MVC is not invoking the validation layer in which case you will need to instantiate and execute the validator manually.

**Comment by surbhi05** [comment]
Hi Jeremy,

If I instantiate and execute the validator manually, then also the list model properties are not getting validated. I get an error if the "Name" property in User model is empty, but the list is still not validated.

**Comment by JeremySkinner** [comment]
You need to wire up the child validator. This isn't necessary when you're using MVC's automatic validation, but as you're now using manual validation you need to wire up the child validator explicitly. https://docs.fluentvalidation.net/en/latest/start.html#complex-properties

**Comment by surbhi05** [comment]
I looked into this already, since I have the polymorphic models I can't simply add a single model validator for the list. I'll upgrade the version and get back to you if the issue still exists.

Thanks for the support.

**Comment by JeremySkinner** [comment]
Yes if you want separate validators for the different subclasses then you'll need to write some custom logic to select which one you want to use at runtime. This issue illustrates how to do it: https://github.com/FluentValidation/FluentValidation/issues/1080#issuecomment-480267622

**Comment by JeremySkinner** [comment]
This one would probably work with 6.x: https://github.com/FluentValidation/FluentValidation/issues/111#issuecomment-135343260

**Comment by surbhi05** [comment]
When I add the following rules in my UserValidator, then I get the "**Nested validators can only be used with Member Expressions**" exception.

```
RuleFor(model => model.Roles.OfType<RoleTypeInteger>())
    SetCollectionValidator(new RoleTypeIntegerValidator());
RuleFor(model => model.Roles.OfType<RoleTypeString>())
    SetCollectionValidator(new RoleTypeStringValidator());
```

**Comment by JeremySkinner** [comment]
That’s a limitation of 6.x

**Comment by surbhi05** [comment]
Okay, will update the version and will connect again if required.
Thanks for the immediate responses. :)

**Comment by surbhi05** [comment]
Hi Jeremy,

I upgraded the version to 8.6, now the validator is validating the model but only when called explicitly, that is because of custom model binders.

Now, in my application, I have a requirement to clear the fluent cache after a certain operation. For that I've updated by code to the following, but it doesn't work. Any ideas?

```
AccessorCache<object>.Clear();
```

**Comment by JeremySkinner** [comment]
Hi, you shouldn't be clearing the accessor cache. What's your use case? Why are you trying to do this?

**Comment by surbhi05** [comment]
We have a multilingual application, and all the validation messages are also translatable, so once the message is updated, I need to display the updated messages, but due to caching old messages are displayed.
And this applies to any model with and validations, even the basic ones. So I have to clear the cache.

**Comment by JeremySkinner** [comment]
I think you've misunderstood. The accessor cache caches *expression trees*, it doesn't cache messages. FluentValidation does not include any caching of messages.

**Comment by JeremySkinner** [comment]
If you're seeing messages being cached, then this will be something that isn't configured correctly elsewhere in your application. How are you configuring your messages? If you can provide some code examples of how you've got things set up, then I might be able to help further.

**Comment by surbhi05** [comment]
Okay, so the point is that I fetch the messages in the validator itself.

```
public     public class UserViewModelValidator : AbstractValidator<UserViewModel>
{
    public UserViewModelValidator()
    {
            RuleFor(model => model.FirstName)
            .NotEmpty().WithMessage(db.CallToDatabase(nameof(Constants.ValidationFieldRequired)))
    }
}

```

**Comment by JeremySkinner** [comment]
Yes, so by doing that you're tying message to the lifetime of the validator object. You can either:

- Lazily load the message (as per my previous example), which will reload the message each time the validator is executed and fails
- Extract this logic behind a separate class, where you can control how/when messages are cached. Your validator would then just make use of this object.

Personally I'd suggest the second option.

**Comment by JeremySkinner** [comment]
If you go with the third option, then your custom validator factory can be based off  [default implementation](https://github.com/FluentValidation/FluentValidation-LegacyWeb/blob/master/src/FluentValidation.ValidatorAttribute/AttributedValidatorFactory.cs) (you'd need to add methods for removing items from the ConcurrentDictionary). 

You would then wire it up in your application startup routine, at the point you call `FluentValidationModelValidatorProvider.Configure()`, eg:

```csharp
FluentValidationModelValidatorProvider.Configure(fv => {
  fv.ValidatorFactory = new MyCustomValidatorFactory();
});
```
