### ISSUE TITLE
'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' does not have an implementation

### ISSUE THREAD

**Issue by shaaheed** [FluentValidation/FluentValidation#1430]
**Which version of FluentValidation are you using?**

- FluentValidation.AspNetCore v8.6.2

**Which version of ASP.NET are you using?**

- .NET Core 3.1

**Describe the issue that you're having**
In the server I installed .net core 3.1.301. Please see the bellow error which I got from server

`Jul 05 11:11:49 softbd-external dotnet-api[10095]: Unhandled exception. System.TypeLoadException: Method 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' from assembly 'FluentValidation.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' does not have an implementation.
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at FluentValidation.AspNetCore.FluentValidationMvcExtensions.RegisterServices(IServiceCollection services, FluentValidationMvcConfiguration config)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at FluentValidation.AspNetCore.FluentValidationMvcExtensions.AddFluentValidation(IMvcBuilder mvcBuilder, Action1 configurationExpression) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs:line 74
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at OTMS.Startup.ConfigureServices(IServiceCollection services) in /etc/codes/TMS/OTMS/Startup.cs:line 32
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at Microsoft.Extensions.Hosting.HostBuilder.Build()
Jul 05 11:11:49 softbd-external dotnet-api[10095]:    at OTMS.Program.Main(String[] args) in /etc/codes/TMS/OTMS/Program.cs:line 10`

**Comment by JeremySkinner** [comment]
This isn't an issue with FluentValidation itself. This means you have a version mismatch somewhere between your .NET Core version and the version of FluentValidation.AspNetCore. From the stacktrace it looks like something is pulling in an older version of the FluentValidation.AspNetCore package. Double check your dependency graph to find out why an older version is being pulled in.

**Comment by shaaheed** [comment]
I have installed the newest version (8.6.2) of FluentValidation. I downloaded the FluentValidation.dll file from my server and in ILSpy it is showing the version 8.0.0. Please see the bellow attachments.

![Screenshot_83](https://user-images.githubusercontent.com/7229757/86532609-473e1900-beed-11ea-9402-e5289432c999.png)

![Screenshot_84](https://user-images.githubusercontent.com/7229757/86532611-4a390980-beed-11ea-96d5-84bdb7380db6.png)

**Comment by JeremySkinner** [comment]
That is the *assembly version* which you're seeing. This will always show 8.0.0.0 for 8.x releases - this is different from the *package version* (of which 8.6.2 is the latest). You can check the version by right-clicking on the FluentValidation.AspNetCore dll in explorer and going to "Properties", then looking at the "Details" tab:

![image](https://user-images.githubusercontent.com/90130/86532754-32995b00-bec4-11ea-86f4-887be41c93d1.png)

**Comment by JeremySkinner** [comment]
Also, you need to make sure that your `Infrastructure` project which references this package is targetting the correct framework version too (it must target netcoreapp3.1)

**Comment by shaaheed** [comment]
My `Infrastructure` project is a .net standard class library where I referenced the `FluentValidation 8.6.2`. 

![Screenshot_85](https://user-images.githubusercontent.com/7229757/86533060-3f33a880-bef0-11ea-988a-8ce22262700a.png)

![Screenshot_86](https://user-images.githubusercontent.com/7229757/86532960-9a18d000-beef-11ea-9f4f-53f87a0e07b6.png)

`Infrastructure` class library is referenced in my main solution project which is `netcoreapp3.1`

![Screenshot_87](https://user-images.githubusercontent.com/7229757/86533028-0eec0a00-bef0-11ea-8099-a63e7717a0ae.png)

In my local machine it is working fine. My local machine .net core version is:

![Screenshot_88](https://user-images.githubusercontent.com/7229757/86533098-6e4a1a00-bef0-11ea-9119-04892b23c323.png)

Today I installed .net core 3.1 in my server and version is:

![Screenshot_89](https://user-images.githubusercontent.com/7229757/86533131-b1a48880-bef0-11ea-90f5-674a50e2d72d.png)

I really don't get what I am doing wrong! :(

**Comment by JeremySkinner** [comment]
> My Infrastructure project is a .net standard class library

That is the issue (see the edit I made to my previous post)

**Comment by JeremySkinner** [comment]
(Added some background info to my previous comment). Also I would suggest you restructure things in one of 2 options:

**Option 1:** Change your Infrastructure project (and any others) to be a `netcoreapp3.1` project, not a `netstandard2` project

**Option 2:** Only reference `FluentValidation.AspNetCore` from your Web project, and change the Infrastructure project to reference `FluentValidation`, not `FluentValidation.AspNetCore`

**Comment by shaaheed** [comment]
Tried to option 2 and it is works fine now. But I really do not get why it was working in my local machine but not in server. 

Thanks for your clarification and helps. Really appreciating.

**Comment by JeremySkinner** [comment]
> But I really do not get why it was working in my local machine but not in server.

I'm not sure either without being able to debug it myself. I would expect it to not work consistently on both. Possibly the order the dlls are being loaded in is different or something.
