### ISSUE TITLE
.NET 5 Support

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1431]
Add net5.0 targets to FluentValidation and FluentValidation.AspNetCore to target the .NET 5 previews. Development on this will only start once .NET 5 is closer to release (current aim is preview 8), and more stable as historically the huge amount of churn between .NET Core previews make it impractical to keep reacting and fixing preview releases. 

- [x] global.json needs updating to include minimum sdk version
- [x] add new net5.0 targetframework to FluentValidation.AspNetCore, and ensure references are updated as appropriate (frameworkreference as per netcoreapp3.1) 
- [x] Ensure FluentValidation.AspNetCore still compiles with this new target framework. Expect some conditional compilation will be necessary
- [x] Add net5.0 targetframework to the ASP.NET test project, along with appropriate references to integration testing packages
- [x] Ensure tests build and run locally
- [x] Ensure tests build and run in CI

**Comment by frosadev** [comment]
I would appreciate this one. 
I'm already upgrading a project to net5.0 to be ahead of time and I can't build because of this dependency.

**Comment by JeremySkinner** [comment]
@frosadev I'm planning on starting on it either once preview 8 or rc1 are available, although it is likely to take me some time to complete it. If you need this sooner, then you'd be very welcome to start working on a pull request. I've updated the issue description to indicate what needs doing.

**Comment by JeremySkinner** [comment]
This now builds and all tests pass against .NET 5 Preview 7

**Comment by jaicind** [comment]
Is the build with .net5 preview 7 support available to install?

**Comment by JeremySkinner** [comment]
@jaicind no, you'll need to build from source for now. We'll start producing packages probably either once net5 preview8 or rc1 are  available.

**Comment by JeremySkinner** [comment]
I've released 9.3-preview1 and pushed it to nuget which contains support for .NET 5 Preview 8

**Comment by BenjaminAbt** [comment]
First feedback (I use this issue because it's still open):

- FV 9.3.0-preview
- .NET 5.0.0-preview.8.20407.11
- ASP.NET Core 5.0.0-preview.8.20407.11

My Models and Validators are inside my ASP.NET Core project, but the validators only will be called if I register the current assembly
`.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())`

**Comment by JeremySkinner** [comment]
@BenjaminAbt I don't understand what you're asking - can you clarify? Automatic registration of validators like this requires you to specify the assembly in which the validators reside, so typically you'd call `RegisterValidatorsFromAssemblyContaining<OneOfMyValidators>` .

**Comment by BenjaminAbt** [comment]
Thanks for the hint; my mistake in thinking.
Confused with the behaviour of another project, sorry!

**Comment by JeremySkinner** [comment]
FluentValidation and FluentValidation.AspNetCore 9.3.0-preview2 have been pushed to nuget with support for .net 5 rc1

**Comment by JeremySkinner** [comment]
Support for .NET 5 RC2 has been merged into master, and 9.3.0-preview3 has been pushed to nuget. Master will now require the .NET 5 SDK in order to build.

**Comment by JeremySkinner** [comment]
FluentValidation 9.3 is now available, with .net 5 support.
