### ISSUE TITLE
expose IValidator or IValidatorDescriptor on IChildValidatorAdaptor somehow

### ISSUE THREAD

**Issue by bbarry** [FluentValidation/FluentValidation#1434]
Trying to generate OpenAPI schema based on FV rules I have the following method:

```csharp
private void ApplyRulesToSchema(SchemaProcessorContext context, IValidatorDescriptor descriptor)
{
    _logger.LogDebug(
        $"Applying FluentValidation rules to swagger schema for type '{GetFriendlyName(context.Type)}'.");

    var schema = context.Schema;
    if (schema?.Properties == null)
    {
        return;
    }

    var lookup = Enumerate(descriptor).ToLookup(k => k.Key, v => v.Validator, StringComparer.OrdinalIgnoreCase);
    foreach (var kvp in schema.Properties)
    {
        var key = kvp.Key;
        var noopContext = new PropertyValidatorContext(new ValidationContext<object>(null!), null, key);
        var validators = lookup[key] ?? Array.Empty<IPropertyValidator>();

        foreach (var propertyValidator in validators)
        {
            foreach (var rule in _rules)
            {
                if (rule.Matches(propertyValidator))
                {
                    try
                    {
                        rule.Apply(
                            new RuleContext(key, propertyValidator, kvp.Value, schema.RequiredProperties));

                        _logger.LogDebug(
                            $"Rule '{rule.Name}' applied for property '{GetFriendlyName(context.Type)}.{key}'");
                    }
                    catch (Exception e)
                    {
                        _logger.LogWarning(
                            0,
                            e,
                            $"Error on apply rule '{rule.Name}' for property '{GetFriendlyName(context.Type)}.{key}'.");
                    }
                }
            }

            if (propertyValidator is IChildValidatorAdaptor)
            {
                IValidatorDescriptor propertyDescriptor = ((dynamic)propertyValidator).GetValidator(noopContext).CreateDescriptor();
                ApplyRulesToSchema(context, propertyDescriptor);
            }
        }
    }
}

private static IEnumerable<(string Key, IPropertyValidator Validator)> Enumerate(IValidatorDescriptor descriptor)
{
    // can't just use GetMembersWithValidators itself because it gets the case wrong on keys compared to the actual ones
    foreach (var membersWithValidator in descriptor.GetMembersWithValidators())
    {
        foreach (var propertyValidator in membersWithValidator)
        {
            yield return (membersWithValidator.Key, propertyValidator);
        }
    }
}
```

While this "works" it is quite esoteric and likely prone to a mistake a year or two from now when I go to make a change to it and don't really understand why I did it this way. The disturbing bit is the if statement

```csharp
if (propertyValidator is IChildValidatorAdaptor)
{
    IValidatorDescriptor propertyDescriptor = ((dynamic)propertyValidator).GetValidator(noopContext).CreateDescriptor();
    ApplyRulesToSchema(context, propertyDescriptor);
}
```

which recursively applies adapter rules to nested types (we have json apis that take pretty flat objects and by the time they are run over with FV they are nested objects in C# for example `Street1` might become `Address.Street1`).

It would be nice if this `IChildValidatorAdaptor` interface had a method on it to help recursing into the included rules. To that end I think either of the following interface methods could be useful:

```csharp
public interface IChildValidatorAdaptor {
    Type ValidatorType { get; }
    IValidator GetValidator(PropertyValidatorContext context);
}
```

(implemented explicitly on the ChildValidatorAdaptor type by calling the generic version)

or

```csharp
public interface IChildValidatorAdaptor {
    Type ValidatorType { get; }
    IValidatorDescriptor CreateDescriptor();
}
```

which could be implemented publicly

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. Let me have a think about this. FluentValidation's validators are designed to essentially be "black boxes", extracting the internal rule definitions isn't an intended use of the library and I wouldn't really recommend doing this due to how brittle it is.

Of your suggestions, the first one is more feasible - the second isn't really doable as child validators can be lazily instantiated (which requires a context to be specified).

If we do implement this, it would be a breaking change so it isn't something that would be included outside of a major version bump. We just released 9.0, so its likely to be at least a year before a 10.0 release. 

Let me have a think about it and see if there's a better way to handle this going forwards.

**Comment by bbarry** [comment]
For reference my code is based on https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation but I ported it to NSwag a year ago and updated it a few times. A similar port exists on github at https://github.com/zymlabs/nswag-fluentvalidation and there is an open issue on NSwag to officially support something https://github.com/RicoSuter/NSwag/issues/1722 and the MicroElements one is recommended by Swashbuckle in their [repository](https://github.com/domaindrivendev/Swashbuckle.AspNetCore).

So yes I agree it is brittle, but I think some sort of recommended metadata api that can be instrumented in a documented way is going to be requested over and over again as more people utilize FV in web apis and want to provide endpoint documentation.

**Comment by JeremySkinner** [comment]
Hi, I had a think about this last night and I think if I were doing something similar I wouldn’t attempt to extract the child validator instance from the ChildValidatorAdaptor. Instead, I’d use the `ValidatorType` property from the interface to instantiate a *new* copy of the child validator (eg use the type to resolve it from your IoC container). Would that work in your situation, or would that not be feasible?

**Comment by bbarry** [comment]
I can do this. It is a tiny bit annoying that `IValidatorFactory` doesn't expose `CreateInstance` even though `ValidatorFactoryBase` has it so I either need to register another factory type in my container or cast my local `IValidatorFactory` field as `ValidatorFactoryBase`. I've also fixed an issue where model level validators on included rules were not being checked; the new method:

```csharp

private IEnumerable<IPropertyValidator> ApplyRulesToSchema(
    SchemaProcessorContext context,
    IValidatorDescriptor descriptor)
{
    _logger.LogDebug(
        $"Applying FluentValidation rules to swagger schema for type '{GetFriendlyName(context.Type)}'.");

    var schema = context.Schema;
    if (schema?.Properties == null)
    {
        return Array.Empty<IPropertyValidator>();
    }

    void TryApplyRules(IPropertyValidator propertyValidator, string key, KeyValuePair<string, JsonSchemaProperty> kvp)
    {
        foreach (var rule in _rules)
        {
            if (!rule.Matches(propertyValidator))
            {
                continue;
            }

            try
            {
                rule.Apply(
                    new RuleContext(key, propertyValidator, kvp.Value, schema.RequiredProperties));

                _logger.LogDebug(
                    $"Rule '{rule.Name}' applied for property '{GetFriendlyName(context.Type)}.{key}'");
            }
            catch (Exception e)
            {
                _logger.LogWarning(
                    0,
                    e,
                    $"Error on apply rule '{rule.Name}' for property '{GetFriendlyName(context.Type)}.{key}'.");
            }
        }

        // important bits for this issue here:
        if (propertyValidator is IChildValidatorAdaptor adaptor &&
            _validatorFactory is ValidatorFactoryBase instanceCreator)
        {
            var childValidator = instanceCreator.CreateInstance(adaptor.ValidatorType);
            if (childValidator is null)
            {
                _logger.LogWarning(
                    $"Unable to create instance of validator type {adaptor.ValidatorType} for property '{GetFriendlyName(context.Type)}.{key}'.");
                return;
            }

            var childDescriptor = childValidator.CreateDescriptor();
            var modelValidators = ApplyRulesToSchema(context, childDescriptor);

            foreach (var additionalPropertyValidator in modelValidators)
            {
                TryApplyRules(additionalPropertyValidator, key, kvp);
            }
        }
    }

    var lookup = Enumerate(descriptor).ToLookup(k => k.Key, v => v.Validator, StringComparer.OrdinalIgnoreCase);
    foreach (var kvp in schema.Properties)
    {
        var key = kvp.Key;
        var validators = lookup[key] ?? Array.Empty<IPropertyValidator>();

        foreach (var propertyValidator in validators)
        {
            TryApplyRules(propertyValidator, key, kvp);
        }
    }

    return lookup[null] ?? Array.Empty<IPropertyValidator>();
}
```

This works for my purposes.
