### ISSUE TITLE
RuleSet order

### ISSUE THREAD

**Issue by weitzhandler** [FluentValidation/FluentValidation#1436]
**Is your feature request related to a problem? Please describe.**

A bit related to [this](https://github.com/FluentValidation/FluentValidation/issues/1435) issue, I was trying to execute multiple validation rulesets with a string, and found the order of the rules to be non consistent, hard to track and hard to specify.

**Describe the solution you'd like**
- An alternative way of defining, specifying and consuming rule sets - not hard coded strings.
- A clear documented pattern of the order rule sets are executed, when there are multiple/all rules to be executed.
- Validate rules separately one after the other, with a rule-set dedicated cascade mode.

**Describe alternatives you've considered**
What I ended up doing is validate the rule-sets separately, resulting in tedious code.

**Comment by JeremySkinner** [comment]
Hi, as I mentioned in the other issue this isn't the case. Rules are executed in the order that they're defined.

Calling `RuleFor` adds a rule instance to a list. Executing the validator iterates over the list executing each one in turn. They aren't re-ordered. 

If this isn't the behaviour that you're seeing then please provide a test case that reproduces the issue.

Thanks!

**Comment by weitzhandler** [comment]
I'll check that thoroughly. Thank you Jeremy for your quick response!
