### ISSUE TITLE
Breaking change moving form using 8.6.2 to 9.0

### ISSUE THREAD

**Issue by srqdev** [FluentValidation/FluentValidation#1441]
When I updated to 9.0 my code no longer compiles due to one of the Validate methods overloads (specifically the one that takes an object) being removed. I used this in the following code to validate and then extract errors a particular method

`public bool ValidateModel<T>(T model, string propertyName = null)
{
	var validationResults = Validator.Validate(model);
`
where Validator is a property of type IValidator and the generic model is an AbstractValidator (one for each different class I'm validating. 

As there is no Validate(object instance) anymore then this fails to compile. Can this method be reimplemented or what is an alternative solution to this

**Comment by JeremySkinner** [comment]
Hello,

This is covered in the [Upgrade Guide](https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload), which also explains how to migrate your code to the new version.

**Comment by srqdev** [comment]
Thank you, I'd missed the upgrade guide,
