### ISSUE TITLE
AspNetCore 9.0.0 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' does not have an implementation

### ISSUE THREAD

**Issue by LukasWillin** [FluentValidation/FluentValidation#1443]
**Which version of FluentValidation are you using?**
FluentValidation.AspNetCore 9.0.0 in an AspNet Core 3.1 project and FluentValidation 9.0.0 in a Netstandard 2.1 project.

**Which version of ASP.NET are you using?**
API Project with AspNet Core 3.1 referencing a project with Netstandard 2.1.
This is due to the use of Blazor in a seperate project which we want to be able to share code with the server.
The Blazor Project uses Netstandard 2.1.

**Describe the issue that you're having**
The following exception is thrown during startup of the API-Project.
```
System.TypeLoadException: 'Method 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' from assembly 'FluentValidation.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' does not have an implementation.'
```

I am aware that it states the version 8.0.0.0 even though I am sure it should state 9.0.0.0 since it is not an 8.x release.
However this is what it seems to load.

I have tried manually purging the nuget packages as well as deleteing all "bin" and "obj" folders in the Project and restoring the packages after. This to make sure I am not having an older package version around that is conflicting (unless I have overlooked another possible source where it could have been loaded from)

Downgrading all FluentValidation(.*) to 8.6.2 in all projects fixes the issue. However we would like to use the latest and greatest 9.0.0 version :P So to be clear this issue isn't time critical to us but I am putting this information/report out there in case it helps you or other users of this package diagnose future issues.
I tried upgrading all to 9.0.0 again after this but then I am getting the same error again.

Any Ideas / Help / Fixes for this?

Regards Lukas

**Comment by JeremySkinner** [comment]
Hello,

This is likely to be the same issue as https://github.com/FluentValidation/FluentValidation/issues/1430#issuecomment-653886399

You probably have a netstandard2.0 library that is referencing FluentValidation.AspNetCore, which will cause the .NET Core 2 version of FluentValidation.AspNetCore to be used, not the .NET Core 3.1 version

**Comment by JeremySkinner** [comment]
(Edit: Re the assembly version: this was my mistake, I forgot to bump it for the 9.0 release, it'll be fixed in 9.0.1)

**Comment by LukasWillin** [comment]
Thanks for the quick response!

So I checked all the projects in the solution.
- The only classlibrary referencing FluentValidation 9.0.0 (NOT FluentValiadtion.AspNetCore) uses Netstandard 2.1
`<PackageReference Include="FluentValidation" Version="9.0.0" />`
- The blazor-project does not reference FluentValidation 9.0.0 by itself.
- The API-Project (Asp.Net Core 3.1) references FluentValidation.AspNetCore 9.0.0 only
`<PackageReference Include="FluentValidation.AspNetCore" Version="9.0.0" />`

Going from your clarifications this project looks fine.

So for now I have to assume The API-project loads some old Version of FluentValidation.AspNetCore. If I find out something else I'll report back.

Until then you may close the issue :)

**Comment by JeremySkinner** [comment]
Ok, let me know what you find. I also find its helpful to use the dependency graph tools in VS to show which packages are referenced under which frameworks. Make sure there's nothing in there that's attempting to load a netstandard version of FluentValidation.AspNetCore.

**Comment by JeremySkinner** [comment]
I've also just pushed out a 9.0.1 release that correctly sets the assembly version to 9.0.0.0. You may find that useful to help with debugging and differentiating the releases

**Comment by LukasWillin** [comment]
So you were right it was me at fault.

I completely overlooked that the API-Project was "Asp.Net Core 3.0" not "Asp.Net Core 3.1". Upgrading to Asp.Net Core 3.1 resolves the issue. As the update notes state 3.0 support has been removed. Rightfully so.

Thank you for taking time out of your day to help me out. I must apologise for having overlooked that particular but not less important detail.

I close the issue now.

Kind regards
Lukas

**Comment by JeremySkinner** [comment]
No worries, glad you got it sorted
