### ISSUE TITLE
DefaultValidatorExtensions.LessThanOrEqualTo error with Int16

### ISSUE THREAD

**Issue by mmonterroca** [FluentValidation/FluentValidation#1444]
When I Use LessThanOrEqualTo with a Int16 type I got this compiler error:

The type 'short?' must be a non-nullable value type in order to use it as parameter 'TProperty' in the generic type or method 'DefaultValidatorExtensions.LessThanOrEqualTo<T, TProperty>(IRuleBuilder<T, TProperty>, Expression<Func<T, TProperty?>>)

A tempory solution is to cast to Int like:

RuleFor(account => **(int?)**account.CutOffDay).Cascade(CascadeMode.StopOnFirstFailure).NotNull().LessThanOrEqualTo(31).GreaterThan(0);

**Which version of FluentValidation are you using?**
Please specify which version of FluentValidation you're using. 

**Which version of ASP.NET are you using?**
.Net Core 3.1

**Describe the issue that you're having**
public class Account
    {
        [Key]
        public int AccountId { get; set; }
        [StringLength(50)]
        [Required]
        public string Name { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public AccountType AccountTypeId { get; set; }
        public decimal InitialBalance { get; set; }
        public decimal Balance { get; set; }
        public Int16? CutOffDay { get; set; }
        public Int16? PaymentDay { get; set; }
        public decimal? CreditLimit { get; set; }
        public bool CashFlow { get; set; }
        public bool RoundPayments { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(15)]
        public string BankId { get; set; }
        [StringLength(15)]
        public string TdcId { get; set; }

    }

class AccountValidator : AbstractValidator<Account>
    {
        public AccountValidator()
        {
            RuleFor(account => account.Name).NotEmpty().Length(1, 50);
            RuleFor(account => account.Description).Length(1, 200).When(account => !string.IsNullOrWhiteSpace( account.Description));
            RuleFor(account => account.UserId).NotEmpty().Length(1, 450);

            //example
            //RuleFor(account => account!.CreditLimit).GreaterThan(0);

            RuleFor(account => account.AccountTypeId).IsInEnum();

            When(account => account.AccountTypeId == AccountType.CreditCard,() => {
                RuleFor(account => account.CreditLimit).Cascade(CascadeMode.StopOnFirstFailure).NotNull().GreaterThan(0);
                RuleFor(account => account.TdcId).Cascade(CascadeMode.StopOnFirstFailure).NotNull();
                RuleFor(account => account.CutOffDay).Cascade(CascadeMode.StopOnFirstFailure).NotNull().LessThanOrEqualTo(31).GreaterThan(0);
                RuleFor(account => account.PaymentDay).Cascade(CascadeMode.StopOnFirstFailure).NotNull().LessThanOrEqualTo(31).GreaterThan(0);
            });
        }
    }

**Comment by JeremySkinner** [comment]
Hello,

You're seeing this error because the property type doesn't match the type of the comparison value. In this case, your property is an `Int16` but the comparison value is an `Int32`. Rather than casting the value in the `RuleFor` expression, you should be casting the comparison value, like this:

```csharp
RuleFor(x => account.CutOffDay).NotNull().LessThanOrEqualTo((short)31).GreaterThan((short)0);
```
