### ISSUE TITLE
Is there automatic client-side validation in v9 like in the MVC version?

### ISSUE THREAD

**Issue by hovek** [FluentValidation/FluentValidation#1445]
Is there automatic client-side validation in v9 like in the MVC version? I can't find this in the documentation nor braking changes docs. Am I supposed to keep using the MVC version or is there a simple method to activate it in the newest version and how? I need the same behaviour on the client like in MVC version because I don't like it to brake my code, it's not desirable, or cool.

**Comment by JeremySkinner** [comment]
Yes, there is. This has not changed since FluentValidation 8.x.

https://docs.fluentvalidation.net/en/latest/aspnet.html#clientside-validation

**Comment by hovek** [comment]
> Yes, there is. This has not changed since FluentValidation 8.x.
> 
> It is part of the FluentValidation.AspNetCore package and supports .NET Core 2.1 and .NET Core 3.1 - please see the documentation: https://docs.fluentvalidation.net/en/latest/aspnet.html#clientside-validation

Does it support .NET Framework 4.8 MVC, because that is what I am using?

**Comment by JeremySkinner** [comment]
No

**Comment by hovek** [comment]
> No

So, I am stuck using the old FluentValidation.Mvc5?

> No. FluentValidation 9's MVC support supports .NET Core 2.1 and .NET Core 3.1. This covered in the documentation and the upgrade guide.

Where in the docs because here: https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html it's stated that it supports .NET Framework 4.6.1 and newer? Apparently not all features.

So, I am stuck using FluentValidation.Mvc5?

**Comment by JeremySkinner** [comment]
> So, I am stuck using the old FluentValidation.Mvc5?

That's correct. Microsoft are no longer actively developing MVC5, and it's not feasible for us to continue supporting it either. We deprecated support for MVC5 in 8.x (there have been warnings about this for nearly 2 years in the documentation) and it was removed in 9.0

> Where in the docs because here: https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html it's stated that it supports .NET Framework 4.6.1 and newer? Apparently not all features.

It is stated in the "Supported Platforms" section at the top. I will quote the relevant section for you:

> "Integration with MVC5/WebApi 2 is no longer supported - both the FluentValidation.Mvc5 and FluentValidation.WebApi packages were deprecated with the release of FluentValidation 8, but they will now no longer receive further updates. "

**Comment by JeremySkinner** [comment]
> So, I am stuck using FluentValidation.Mvc5?

Yes, if you are using a legacy ASP.NET MVC 5 project, then you will need to use FluentValidation.Mvc5. It's not going anywhere - it's still available on nuget and will continue to be available for you to use, it's just not receiving any further updates (and hasn't done so for over a year actually).

**Comment by hovek** [comment]
> > So, I am stuck using the old FluentValidation.Mvc5?
> 
> That's correct. Microsoft are no longer actively developing MVC5, and it's not feasible for us to continue supporting it either. We deprecated support for MVC5 in 8.x (there have been warnings about this for nearly 2 years in the documentation) and it was removed in 9.0
> 
> > Where in the docs because here: https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html it's stated that it supports .NET Framework 4.6.1 and newer? Apparently not all features.
> 
> It is stated in the "Supported Platforms" section at the top. I will quote the relevant section for you:
> 
> > "Integration with MVC5/WebApi 2 is no longer supported - both the FluentValidation.Mvc5 and FluentValidation.WebApi packages were deprecated with the release of FluentValidation 8, but they will now no longer receive further updates. "

Who reads all the docs for every plugin we use, we would need two lives or more, and it's not fun. ;)

**Comment by JeremySkinner** [comment]
You should always read the documentation, especially when upgrading between major releases. That's precisely why I link to the upgrade guide in the release notes and on the nuget package page, so consumers of the project can clearly be informed of changes.

**Comment by hovek** [comment]
> You should always read the documentation, especially when upgrading between major releases. That's precisely why I link to the upgrade guide in the release notes and on the nuget package page, so consumers of the project can clearly be informed of changes.

I hate reading docs, wasting much time to maybe find something of interest. It's easier for me to just test the upgraded code. Sorry, I don't like it because you need to read much of redundant or unnecessary info in search of something that is maybe relevant to me, docs are very slow and inefficient. I just hate it, sorry.

**Comment by JeremySkinner** [comment]
If you choose not to read the documentation then you shouldn't be surprised when things break unexpectedly, when the authors have gone to a lot of effort to provide the information for you, for free. By refusing to read the documentation and instead coming here you are literally wasting my time.
