### ISSUE TITLE
Show Valid Values in Error Response

### ISSUE THREAD

**Issue by uchagani** [FluentValidation/FluentValidation#1447]
**Which version of FluentValidation are you using?**
FluentValidation.AspNetCore(9.0.1)

**Which version of ASP.NET are you using?**
 NET Core 3.1

**Describe the issue that you're having**
I am using Fluent Validation and MVC filters to validate a request.  As part of the error, I'd like to show a list of valid values.  I'm not sure how to get the `ValidValues` property populated with a list of valid values the way that `FieldName` and `Message` are getting populated by the validation filter.

Currently the error message looks like this:

```
{
    "errors": [
        {
            "fieldName": "Make",
            "message": "Invalid Make"
        }
    ]
}
```

I'd like it to show something like this:

```
{
    "errors": [
        {
            "fieldName": "Make",
            "message": "Invalid Make",
			"validValues": ["Ford", "Honda"]
        }
    ]
}
```

My Error Model:

```
public class Error
{
    public string FieldName { get; set; }
    public string Message { get; set; }
    public string[] ValidValues { get; set; }
}
```

Validator:

```
RuleFor(car => car.Make)
	.Must(BeAValidMake)
	.WithMessage("Invalid Make.");
	//Add Valid values some how so they can be used by the validation filter to populate the error model.
```

Validation Filter:

```
public class ValidationFilter : IAsyncActionFilter
{
	public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
	{
		if (!context.ModelState.IsValid)
		{
			var errorsInModelState = context.ModelState
				.Where(x => x.Value.Errors.Count > 0)
				.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.Errors.Select(e => e.ErrorMessage)).ToArray();

			var errorResponse = new ErrorResponse();

			foreach (var error in errorsInModelState)
			{
				foreach (var subError in error.Value)
				{
					var errorModel = new Error()
					{
						FieldName = error.Key,
						Message = subError
					};

					errorResponse.Errors.Add(errorModel);
				}
			}

			context.Result = new BadRequestObjectResult(errorResponse);
			return;
		}

		await next();
	}
}
```

**Comment by JeremySkinner** [comment]
Hi, this isn't doable if you're using automatic validation (which you are) because the the ModelState data structure doesn't have the ability to store any additional information. When FluentValidation's results are copied into modelstate the only things that come across are the property name and the error message. You would have to turn off automatic validation and instead invoke the validator's `Validate` method manually if you need to obtain additional information from the rule.
