### ISSUE TITLE
RuleSet inside IValidator added via SetValidator makes no sense

### ISSUE THREAD

**Issue by KindElk** [FluentValidation/FluentValidation#1448]
**Version of FluentValidation: 9.0.0** 

**.NET Framework 4.7**

**Description**

In case you are adding another IValidator instance which has RuleSets inside you cannot run rules described in that validator from specific rule sets. For example:

```
interface IModel {
  int Id { get; }
}

class Validator : AbstractValidator<IModel> {
  public Validator() {
    RuleFor(model => model.Id).SetValidator(new InnerValidator());
  }
}

class InnerValidator : AbstractValidator<int> {
  public InnerValidator() {
    RuleSet("NamedRuleSet", () => {
      RuleFor(i => i).NotEqual(0);
    });
  }
}
```
So when you call ```new Validator().Validate(someIModelImplementer, ruleSet: "NamedRuleSet")``` nothing will be validated.
**Note:** even changing ```.SetValidator(new InnerValidator());``` to ```.SetValidator(new InnerValidator(), "NamedRuleSet");``` haven't helped.
I've found the root cause is that user-defined validator is wrapped in another one which lacks list of the right rulesets, so the following code fixes the issue.
```
public abstract class ExtendedAbstractValidator<T> : AbstractValidator<T>
{
  public IRuleBuilderOptions<T, TProperty> ComplexRuleFor<TProperty>
    (Expression<Func<T, TProperty>> expression, AbstractValidator<TProperty> validator)
  {
    HashSet<string> ruleSetCollection = new HashSet<string>();
    foreach (IValidationRule val in validator)
    {
      if(val.RuleSets.Length == 0)
      {
        ruleSetCollection.Add("default");
      }
      else foreach (string ruleSet in val.RuleSets)
      {
        ruleSetCollection.Add(ruleSet);
      }
    }

    string[] ruleSetArray = ruleSetCollection.ToArray();
    string ruleSetJoined = string.Join(",", ruleSetArray);

    IRuleBuilderOptions<T, TProperty> builder = null;
    RuleSet(ruleSetJoined, () => {
      builder = RuleFor(expression).SetValidator(validator, ruleSetArray);
    });
    return builder;
  }
}
```

As for me it would be nice to have something like this as default behavior.

**Comment by JeremySkinner** [comment]
Hi, this is behaving as intended.

Rulesets cascade down to child validators, so whichever ruleset you execute at the root level will also be run on the child validator (unless you specify an explicit ruleset in SetValidator). Here's a few examples that should illustrate how this works:

Example 1, both rules in same ruleset:

```csharp
class Validator : AbstractValidator<IModel> {
  public Validator() {
    RuleSet("NamedRuleSet", () => {
       RuleFor(model => model.Id).SetValidator(new InnerValidator());
    });
  }
}

class InnerValidator : AbstractValidator<int> {
  public InnerValidator() {
    RuleSet("NamedRuleSet", () => {
      RuleFor(i => i).NotEqual(0);
    });
  }
}

// In this example both the rules are defined in the "NamedRuleSet".

// This will execute all rules not in a ruleset, so nothing will run.
new Validator().Validate(model);

// This will execute all rules in SomeRuleSet, the root-level RuleFor will run
// and the rules inside the child validator will run, as they're in the same named ruleset.
new Validator().Validate(model, ruleSet: "NamedRuleSet");
```

Example 2: Top-level rule not in ruleset, nested validator's rules in ruleset. 

```csharp
class Validator : AbstractValidator<IModel> {
  public Validator() {
     RuleFor(model => model.Id).SetValidator(new InnerValidator());
  }
}

class InnerValidator : AbstractValidator<int> {
  public InnerValidator() {
    RuleSet("NamedRuleSet", () => {
      RuleFor(i => i).NotEqual(0);
    });
  }
}

// In this example both the rules are defined in the "NamedRuleSet".

// This will the rule in the root validator, however as the "NamedRuleSet" isn't included for execution
// the rule inside the nested validator will not run. So there will be no results.
new Validator().Validate(model);

// This will not execute the rule in the root level because it's not in a ruleset. 
// So nothing will run.
new Validator().Validate(model, ruleSet: "NamedRuleSet");

// This will execute the rule at the top level, because it isn't in a ruleset.
// It will also execute the rule inside the child validator inside the NamedRuleSet
// It will also execute any rules inside the child validator that *aren't* in a ruleset
new Validator().Validate(model, ruleSet: "default,NamedRuleSet");
```

Example 3: Explicitly including a child validator's ruleset (I think this is what you want)

```csharp
class Validator : AbstractValidator<IModel> {
  public Validator() {
     RuleFor(model => model.Id).SetValidator(new InnerValidator(), "NamedRuleSet");
  }
}

class InnerValidator : AbstractValidator<int> {
  public InnerValidator() {
    RuleSet("NamedRuleSet", () => {
      RuleFor(i => i).NotEqual(0);
    });
  }
}

// In this example both the rules are defined in the "NamedRuleSet".

// This will execute the rule in the root validator, because it's not in a ruleset.
// Because ruleset is implicitly included in the call to SetValidator, the child validator will run too. 
new Validator().Validate(model);
```

**Comment by JeremySkinner** [comment]
So I believe that example 3 is what you want: You should be explicitly specifying the ruleset at the point you call `SetValidator`, but not at the point you call `Validate`. 

Because the first rule is not included in a ruleset, it will never be executed if you are only passing "NamedRuleset" in your call to validate.

**Comment by KindElk** [comment]
Got your idea, 
The first example is exactly what I want to achieve, thanks. 
The second one looks exactly like my first attempt to use rulesets. I was expecting the call with only one specified ruleset (like ```new Validator().Validate(model, ruleSet: "NamedRuleSet");```) will run rules that belong it, so actual behavior confused me until I dived into sources.
In the third one I'd expect (reading only the client-side code) that call like ```new Validator().Validate(model, ruleSet: "NamedRuleSet")``` will run the rule inside, but surprisingly it did not.

All I was trying to say is that I'd expect ```SetValidator``` to create some transparent thingy, that won't block reaching rules inside.
Another convenient option is to have this behavior explicitly stated in docs: as I see from [StackOverflow](https://stackoverflow.com/questions/46715405/servicestack-and-fluentvalidation-not-firing-separate-rule-sets/62923614) I'm not the only one a bit confused with ```RuleSet```s' behavior.

Thank you for reply and for really cool library!

**Comment by JeremySkinner** [comment]
> All I was trying to say is that I'd expect SetValidator to create some transparent thingy, that won't block reaching rules inside.

It's not that straightforward, because the call to SetValidator is part of a complete rule in itself, that can have other things in the chain, so it isn't transparent. Eg

```
RuleFor(x => x.Something).NotNull().Must(x => x != "foo").SetValidator(new SomethingValidator())
``` 

This is a complete rule containing multiple validators. This entire chain can either be inside a ruleset or not. This can be put in a ruleset (or not) and will affect every part of it, including the call to SetValidator. SetValidator is just another part of the rule, like NotNull. 

Anyway, glad you have a working solution
