### ISSUE TITLE
After upgrading from **8.6.2** to **9.0.1** some email tests cases are failing

### ISSUE THREAD

**Issue by hrytskivr** [FluentValidation/FluentValidation#1453]
**Which version of FluentValidation are you using?**
FluentValidation 9.0.1

**Which version of ASP.NET are you using?**
ASP NET Core 3.1 

**Describe the issue that you're having**
After upgrading from **8.6.2** to **9.0.1** last test case is failing

        [TestCase("12345")]
        [TestCase("email")]
        [TestCase("email@12345.")] <--- this one
        public void TestUserRequestValidator_ShouldHaveError_WhenEmailIsOfInvalidFormat(string email)
        {
            _validator.ShouldHaveValidationErrorFor(r => r.Email, email);
        }

**Comment by JeremySkinner** [comment]
Hi, this will be related to the change to email validation. Please see this section of the upgrade guide https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#default-email-validation-mode-changed

**Comment by hrytskivr** [comment]
@JeremySkinner cheers 🤝
