### ISSUE TITLE
Global IValidatorInterceptor breaks validation in Razor Pages

### ISSUE THREAD

**Issue by david-driscoll** [FluentValidation/FluentValidation#1457]
**Which version of FluentValidation are you using?**
Latest

**Which version of ASP.NET are you using?**
3.1

**Describe the issue that you're having**
When an `IValidatorInterceptor` is defined globally, validation errors from a Razor Page throws an `InvalidCastException`.

```
InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Mvc.RazorPages.PageContext' to type 'Microsoft.AspNetCore.Mvc.ControllerContext'.
```

The problem was fairly easy to track down, it's hard hard cast here: https://github.com/FluentValidation/FluentValidation/blob/6f38b0b1bf3d768a79df203b70a40172446db428/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs#L92

I was able to successfully create a failing test: https://github.com/FluentValidation/FluentValidation/pull/1456

However I uncertian of the next steps as the required changed would mean that the `IValidatorInterceptor` would have to change to be `ActionContext` instead of `ControllerContext`.  😢

**Comment by JeremySkinner** [comment]
Hi, some of the more advanced integration features (including interceptors) aren’t supported under razor pages I’m afraid, only with controllers.

This is something that we could look at supporting in the future, but I believe there was a reason this needed to be a controller context (although I can’t remember the reason, it may not be the case anymore). However, as this is a breaking change it’s not something that would be done outside a major version release.

**Comment by JeremySkinner** [comment]
Another option would be to add a second interface (eg IRazorPagesInrerceptor or something like that). Internally FluentValidation could call the appropriate implementation based on the context type. 

This wouldn’t then be a breaking change. In the next major release they can then be consolidated (I think I’d mark the new interface as obsolete immediately to warn that it’ll be removed again). 

Would that work for you?

**Comment by david-driscoll** [comment]
Yeah that'd totally be fine!
I would maybe not make it RazorPages (`PageContext`) specific, but instead build it around the [`ActionContext`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actioncontext?view=aspnetcore-3.1) base class instead.
Perhaps `IActionContextValidatorInterceptor` ?

Then if someone needs to get more details in the before/after calls they pattern match it against `ControllerContext` or `PageContext`.

I can create or update the PR to have that as the proposed solution if you would like.

**Comment by david-driscoll** [comment]
My specific scenario is just to capture the `ValidationResult` into the `HttpContext.Items` so that it can be picked up later in the mvc filter pipeline in an application that has mixed controllers and pages.

https://github.com/RocketSurgeonsGuild/LaunchPad/blob/b1fcd1c337f6d3938e69eabb82f397ec98f8668d/src/AspNetCore/Validation/ValidatorInterceptor.cs#L21

**Comment by JeremySkinner** [comment]
Yes please, if you want to put together a PR that’d be great, thanks.

**Comment by david-driscoll** [comment]
@JeremySkinner I have updated the PR #1456 with my proposed changes, let me know what you think when you have time!  Thanks!

**Comment by JeremySkinner** [comment]
Thanks, I'll try and review this sometime soon.

**Comment by JeremySkinner** [comment]
9.1 is now available on nuget with this change.
