### ISSUE TITLE
DI AddValidatorsFromAssembly for NonPublic (Internal) Validators

### ISSUE THREAD

**Issue by kl1mm** [FluentValidation/FluentValidation#1458]
**Is your feature request related to a problem? Please describe.**
I like to add Validators to the DI which are not public

**Describe the solution you'd like**
Maybe an additional argument in the AddValidatorsFromAssembly method?
`services.AddValidatorsFromAssembly(assembly, opts => opts.IncludeNonPublic = true)`

**Describe alternatives you've considered**
Don´t use the AddValidatorsFromAssembly and implement searching the IValidator-Types by myself and adding them to the DI-Container

**Additional context**
```csharp
public class UseCase
{
	public class Request { /* some fields */ }

	internal class Handler
	{
		public async Task Handle() => throw new NotImplemented("TBD")
	}

	internal class Validator : AbstractValidator<Request>
	{
		private Validator() 
		{
			// some code to validate request
		}
	}
}
```

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. Generally speaking it isn’t good practice for us to automatically register non-public types. A type being public suggests that it can be used outside its defining assembly, while an internal type shouldn’t  this is similar to how you wouldn’t generally use reflection to invoke a non-public method. 

As such, this isn’t something that we will build into the library. 

If you really want to do this you will need to write your own code to scan for these types.

**Comment by kl1mm** [comment]
Hello JeremySkinner, thanks for your quick response even if I'm not entirely happy with it.
Especially since other libraries do it similarly (e.g. MediatR)

Thank you and greetings kl1mm
