### ISSUE TITLE
Validation on [FromHeader] and [FromRoute] values on controller

### ISSUE THREAD

**Issue by ryanelfmank2** [FluentValidation/FluentValidation#1459]
**Which version of FluentValidation are you using?**
9.0.1

**Which version of ASP.NET are you using?**
ASP.NET Core 3.1

**Describe the issue that you're having**
I have a method signature that uses values from the body, headers and the route

```
public async Task<IActionResult> TestASync
(
            [FromRoute] Guid someGuidValue,
            [FromHeader] string someStringValue,
            [FromBody] SomeModel model
)
```
I would like to be able to create a validator for the someStringValue and someGuidValue to return custom messages. I've tried to do the following:

```
[FromHeader] USerIdModel someStringValue

public class UserIdModel { public string UserId { get;set;} }
```

But I don't want to deserialize an object in my headers I just want the straight up string value.

Is there a built in attribute I can put alongside the `someStringValue` to have custom validation on a single string?

**Comment by JeremySkinner** [comment]
Hello, no, this isn't the purpose of FluentValidation. 

FluentValidation is a library for validating the properties of an object, which is done by creating a validator class that defines rules for the individual properties on a specific model type ([see the docs](https://docs.fluentvalidation.net/en/latest/start.html#creating-your-first-validator))

It sounds to me like the standard ASP.NET DataAnnotations attributes would be a better fit for your scenario
