### ISSUE TITLE
Validate Parameters without a class - Domain Validation

### ISSUE THREAD

**Issue by baartho** [FluentValidation/FluentValidation#1462]
**System Details**
FluentValidation version: 9.0.1
**Issue Description**
I'd like to know if doing similar to the following is possible somehow: 

```
public static ValidationResult Validate(string name, int age)
{
    var validator = new InlineValidator(); // PS: I picked InlineValidator because this was the closest class I found. But I'm open to any other classes / implementations.
    validator._RuleFor_(name).NotEmpty();
    validator._RuleFor_(age).NotEmpty();

    return validator.Validate()
}
```

Instead of validating/creating rules for a specific class <T>, I'd like to validate for some fields that in this case are being passed as a parameter. 

The reason is that I want to leverage the awesome FluentValidation syntax for Domain Model validation.

thank you!

**Comment by JeremySkinner** [comment]
Hello,

No, sorry, this is not the purpose or intended use of FluentValidation. 

FluentValidation is a tool for validating the *properties of an object*, if you're trying to validate parameters without a class then FluentValidation is not the right tool for you and you should use something else, or even just write the logic by hand. FluentValidation doesn't provide any benefit in this situation.

**Comment by JeremySkinner** [comment]
As promised, here's an example using the anonymous type:

```csharp
public static ValidationResult Validate(string name, int age) {
	return Validate(new {name, age}, v => {
		v.RuleFor(x => x.name).NotEmpty();
		v.RuleFor(x => x.age).GreaterThan(0);
	});
}

public static ValidationResult Validate<T>(T model, Action<InlineValidator<T>> action) {
	var validator = new InlineValidator<T>();
	action(validator);
	return validator.Validate(model);
}

```

**Comment by baartho** [comment]
Thank you! 

I'll run some tests and see if it'll be beneficial to use the use case you have provided. 

Or if I should simply stick to a simple "if(name == string.empy)".
