### ISSUE TITLE
FluentValidation 9 ChildValidatorAdaptor Upgrade guide

### ISSUE THREAD

**Issue by wast** [FluentValidation/FluentValidation#1464]
FluentValidation 9
NET Core 3.1

I can't get new ChildValidatorAdaptor working. Can you provide more details on how to use those generic parameters?
My old method:

This is code from version 8 which works:

    public class PolymorphicValidator<TInterface> : ChildValidatorAdaptor
    {
        readonly Dictionary<Type, IValidator> _derivedValidators = new Dictionary<Type, IValidator>();

        // Need the base constructor call, even though we're just passing null.
        public PolymorphicValidator() : base((IValidator)null, typeof(IValidator<TInterface>))
        {
        }

        public PolymorphicValidator<TInterface> Add<TDerived>(IValidator<TDerived> derivedValidator) where TDerived : TInterface
        {
            _derivedValidators[typeof(TDerived)] = derivedValidator;
            return this;
        }

        public override IValidator GetValidator(PropertyValidatorContext context)
        {
            // bail out if the current item is null 
            if (context.PropertyValue == null) return null;

            if (_derivedValidators.TryGetValue(context.PropertyValue.GetType(), out var derivedValidator))
            {
                return derivedValidator;
            }

            return null;
        }
    }
`

**Comment by JeremySkinner** [comment]
Hello, please see the code sample here: https://github.com/FluentValidation/FluentValidation/issues/1433

**Comment by wast** [comment]
Thanks. Didn't see those. I still can't find how you use it now?

I used it with .RuleForEach and .SetValidator + .Add.

**Comment by JeremySkinner** [comment]
Yes, that's correct - you still use it in exactly the same way

**Comment by JeremySkinner** [comment]
Eg 

```csharp
public class MyValidator : AbstractValidator<MyModel> {
  public MyValidator() {
     RuleForEach(x => x.Contacts).SetValidator(new PolymorphicValidator<MyModel, IContact>()
	.Add<Contact>(new ContactValidator())
	.Add<Email>(new EmailValidator())
    );
  }
}

```

**Comment by wast** [comment]
Can't get it working. 

System.InvalidCastException: Unable to cast object of type 'ContactValidator' to type 'FluentValidation.IValidator`1[IContact]

Any hints on what it could be?

**Comment by JeremySkinner** [comment]
Please post the full code

**Comment by wast** [comment]
Child validator

    public class ContactValidator : AbstractValidator<Contact>
    {
        public ContactValidator ()
        {
            RuleFor(t => t.Name).NotEmpty();
        }
    }


Parent validator
```

public class CreateContactsRequestValidator : AbstractValidator<CreateContactsRequest>
    {
        public CreateContactsRequestValidator ()
        {
            RuleForEach(c => c.Contacts)
                .SetValidator(new PolymorphicValidator<CreateContactsRequest, IContact>()
                    .Add<Contact>(new ContactValidator())
            );
        }
    }
```

PolymorphicValidator
```
public class PolymorphicValidator<TPropertyType, TInterface> : ChildValidatorAdaptor<TPropertyType, TInterface>
    {
        readonly Dictionary<Type, IValidator<TInterface>> _derivedValidators = new Dictionary<Type, IValidator<TInterface>>();

        // Need the base constructor call, even though we're just passing null.
        public PolymorphicValidator() : base((IValidator<TInterface>)null, typeof(IValidator<TInterface>))
        {
        }

        public PolymorphicValidator<TPropertyType, TInterface> Add<TDerived>(IValidator<TDerived> derivedValidator) where TDerived : TInterface
        {
            _derivedValidators[typeof(TDerived)] = (IValidator<TInterface>)derivedValidator;
            return this;
        }

        public override IValidator<TInterface> GetValidator(PropertyValidatorContext context)
        {
            // bail out if the current item is null 
            if (context.PropertyValue == null) return null;

            if (_derivedValidators.TryGetValue(context.PropertyValue.GetType(), out var derivedValidator))
            {
                return derivedValidator;
            }

            return null;
        }
    }
```

Model

    public sealed class Contact : IContact
    {
        public string Name { get; set; }
    }
    public interface IContact {}

**Comment by JeremySkinner** [comment]
Thanks. It looks like there’s something not quite right with the updated version that the other user provided. I’ll try and put together an updated version for you.

**Comment by JeremySkinner** [comment]
That implementation I linked to definitely doesn't work, here's an updated version that handles the type conversion correctly:

```csharp
public class PolymorphicValidator<TPropertyType, TInterface> : ChildValidatorAdaptor<TPropertyType, TInterface>
{
	readonly Dictionary<Type, IValidator> _derivedValidators = new Dictionary<Type, IValidator>();

	// Need the base constructor call, even though we're just passing null.
	public PolymorphicValidator() : base((IValidator<TInterface>)null, typeof(IValidator<TInterface>))
	{
	}

	public PolymorphicValidator<TPropertyType, TInterface> Add<TDerived>(IValidator<TDerived> derivedValidator) where TDerived : TInterface {
		_derivedValidators[typeof(TDerived)] = derivedValidator;
		return this;
	}

	public override IValidator<TInterface> GetValidator(PropertyValidatorContext context)
	{
		// bail out if the current item is null
		if (context.PropertyValue == null) return null;

		if (_derivedValidators.TryGetValue(context.PropertyValue.GetType(), out var derivedValidator)) {
			return new ValidatorWrapper(derivedValidator);
		}

		return null;
	}

	private class ValidatorWrapper : AbstractValidator<TInterface> {

		private IValidator _innerValidator;
		public ValidatorWrapper(IValidator innerValidator) {
			_innerValidator = innerValidator;
		}

		public override ValidationResult Validate(ValidationContext<TInterface> context) {
			return _innerValidator.Validate(context);
		}

		public override Task<ValidationResult> ValidateAsync(ValidationContext<TInterface> context, CancellationToken cancellation = new CancellationToken()) {
			return _innerValidator.ValidateAsync(context, cancellation);
		}

		public override IValidatorDescriptor CreateDescriptor() {
			return _innerValidator.CreateDescriptor();
		}
	}
}

```

**Comment by wast** [comment]
It works. Thank you!
