### ISSUE TITLE
Press on Enter for InputNumber field dont mark as invalid input

### ISSUE THREAD

**Issue by sushalex** [FluentValidation/FluentValidation#1466]
Which version of FluentValidation are you using?
last 9 version

Which version of ASP.NET are you using?
NET Core 3.1 etc, Blazor Server

Describe the issue that you're having
I have a table with few rows. Input field for percentage and validation is
   RuleFor(x => x.Percentage).InclusiveBetween(1, 100).WithMessage("Percentage have to be 1..100");
It is work correct if I inserted value and changed focus on another place.
But if to insert 1234 and press Enter button, starts work validation all validation  process correct , but at the end on UI something magic rewrite and current input field marks as correct. For short time I can saw error message.
For the input field I use Blazor InputNumber.

![image](https://user-images.githubusercontent.com/10866727/88665069-b53dc080-d0e6-11ea-883c-257f3386622c.png)
Can you help me to resolve this issue?
With best wishes

**Comment by JeremySkinner** [comment]
Hello. As I mentioned in the other issue you opened, this isn't an issue to do with the FluentValidation library itself. We don't provide any blazor implementation directly - you should speak to whoever wrote the integration between FluentValidation and blazor that you're using. 

This issue tracker is for issues with the core FluentValidation library - not for issues related to using it with Blazor. Thanks for understanding.

**Comment by sushalex** [comment]
Hi @JeremySkinner  again!
I used https://blazor-university.com/forms/writing-custom-validation/ as example and I found that one think didn't work for me.
When I press on form Enter button, it means that I call method submit form. All time event went from OnValidSubmit? Why? I asked myself.
After researh I found that string in code `EditContext.OnValidationRequested += ValidationRequested;` in HookUpEditContextEvents method disturbs me. Because after press Enter first time go EditContext.OnFieldChanged and I reserve error and after that starts all model checking with EditContext.OnValidationRequested += ValidationRequested and it cant correctly find error. No error. 
I think that you can help me with this, is not it?
Why ValidationRequested can find errors where EditContext.Model has empty  field with required dataannotation? 



 
Can you tell me why

**Comment by JeremySkinner** [comment]
I can't help you I'm afraid. As I said before, this is not related to the FluentValidation library itself. I'd suggest you reach out to the author of the article if you're having problems with their code examples.
