### ISSUE TITLE
ScalePrecisionValidator should be PrecisionScaleValidator

### ISSUE THREAD

**Issue by jzabroski** [FluentValidation/FluentValidation#1469]
**Is your feature request related to a problem? Please describe.**
The nomenclature for ScalePrecisionValidator is backwards from how it normally is documented in SQL Server, MySQL, Oracle, etc.  Normally its `decimal(p, s)`.  Therefore, I think:

**Describe the solution you'd like**
1. Rename ScalePrecisionValidator to PrecisionScaleValidator
2. Rename extension method ScalePrecision to PrecisionScale and parameter order to the extension method should change.
3. Add test helper ShouldHaveScaleAndPrecision which tests both positive and negative test cases (I wrote something like this internally for my client, but it seems generally useful - not sure I can contribute it but it's not super complicated to write, either).

**Describe alternatives you've considered**
Create a wrapper around ScalePrecision extension method called PrecisionScale.  However, that means that IntelliSense will pick up both options, confusing some engineers and leading to mistakes.

**Additional context**
Thanks for this awesome library, yet again. Looking forward to hearing your thoughts.

**Comment by jzabroski** [comment]
Jeremy, this would have to go in a 10.0 release, obviously, due to API breaking change.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. I don't really feel that there would be a large enough benefit for this to justify such a large breaking change here. With a library as popular as FluentValidation it's best to avoid breaking changes (even in major version releases) unless it's really necessary. 

In this particular case, I feel that the terminology is clear enough as-is, and reversing it is actually likely to cause more confusion as well as being a breaking change. Is the current naming actively causing a problem for you?

**Comment by jzabroski** [comment]
I think it's stylistically different from everywhere else I refer to scale and precision: Entity Framework entity configuration `HasPrecision(p, s)`, FluentMigrator `AsDecimal(p, s)` column syntax, and T-SQL `decimal(p, s)`

To be honest, I debated not even bothering using the ScalePrecision at all in my code base because its backwards from how I am used to thinking about it.  However, I thought that was a silly reason to not have strong application-level pre-save hooks (one of the ways I use FluentValidation is as database save ingress interceptors, and another is as database outgress validation in ETL projects e.g. after extract and before transform steps).

I have found your library to be very useful, and I also hesitated even raising this issue because I don't want to be the dude who just creates work for you to do on such a popular project.  That said, having used other non-MS projects about as popular as yours (CsvHelper), I have seen projects flourish despite the surface area of the API changing a lot.

An alternative proposal (and possible bridge pattern towards deprecating the ScalePrecision syntax) would be to support both, but on the ScalePrecision syntax, add `[EditorBrowsable(EditorBrowsableState.Never)]`.  Would that be a good middle ground idea for you to consider?  In this way, new users see the more natural syntax, but you don't break old users.

**Comment by jzabroski** [comment]
By the way, credit goes to Daniel Cazzulino for the browsable state idea.  My inspiration is taken from: https://github.com/kzu/IFluentInterface

**Comment by JeremySkinner** [comment]
> An alternative proposal (and possible bridge pattern towards deprecating the ScalePrecision syntax) would be to support both, but on the ScalePrecision syntax, add [EditorBrowsable(EditorBrowsableState.Never)]

Sure, that seems a good compromise and could be implemented sooner rather than later without a breaking change. Please submit a pull request for this and I'll review it. I would suggest the following:

- [ ] Add new `PrecisionScale` extension methods that internally continue to use the `ScalePrecisionValidator` class. 
- [ ] Hide the existing `ScalePrecision` methods with `EditorBrowsable`, and also mark them as `Obsolete`
- [ ] Ensure that the documentation examples are also updated to reflect this change
- Do not rename the `ScalePrecisionValidator` class, leave this as-is. 

This way is fully backwards compatible, and only affects the public API without needing to change the internal API. 

> By the way, credit goes to Daniel Cazzulino for the browsable state idea. My inspiration is taken from: https://github.com/kzu/IFluentInterface

Yes I use that approach elsewhere in FluentValidation already :)

**Comment by weitzhandler** [comment]
@JeremySkinner 

Can you please have a look: 
https://github.com/weitzhandler/FluentValidation.EntityFrameworkCore

Would you be able to talk to me about it? Please drop me a message on twitter ([@weitzhandler](https://twitter.com/weitzhandler)) if so.

Thank you!

**Comment by JeremySkinner** [comment]
@weitzhandler If you have some specific questions you want to ask me then please feel free to open a new issue to discuss, thanks.
