### ISSUE TITLE
.editorconfig tabbing incorrect

### ISSUE THREAD

**Issue by jzabroski** [FluentValidation/FluentValidation#1470]
Overrides happen top-down, and so `[*.cs]` indent_style and tab_width get overridden by `[*]`

It should say:

```ini
 # top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 2

[*.cs]
indent_style = tab
tab_width = 2
end_of_line = crlf

[*]
trim_trailing_whitespace=true
insert_final_newline=true 
```

**Comment by JeremySkinner** [comment]
Can you submit this as a PR? Thanks.

**Comment by jzabroski** [comment]
Yes, I am seeing a problem in Visual Studio 2019 16.4.4.  I will try in vscode.  I can see bug reports in Visual Studio 2019 bug tracker as it relates to handling these things, so its possible they broke something.

**Comment by jzabroski** [comment]
https://github.com/editorconfig/editorconfig/issues/278#issuecomment-258312348 It appears this is a bug in the editorconfig for FluentValidation, based on the editorconfig remarks linked
