### ISSUE TITLE
async example miss client parameter

### ISSUE THREAD

**Issue by htzhang2** [FluentValidation/FluentValidation#1472]
How to pass client paratermeter in async example?
---------------------------------------------------------
public class CustomerValidator : AbstractValidator<Customer> {
  SomeExternalWebApiClient _client;

  public CustomerValidator(SomeExternalWebApiClient client) {
    _client = client;

    RuleFor(x => x.Id).MustAsync(async (id, cancellation) => {
      bool exists = await _client.IdExists(id);
      return !exists;
    }).WithMessage("ID Must be unique");
  }
}
Invoking the validator is essentially the same, but you should now invoke it by calling ValidateAsync:

var validator = new CustomerValidator();
var result = await validator.ValidateAsync(customer);

**Comment by JeremySkinner** [comment]
I don't understand what you're asking. Please can you explain clearly what you need help with? Thanks.

**Comment by htzhang2** [comment]
Where is "SomeExternalWebApiClient _client"initliazed in CustomerValidator?

Does caller pass client information for CustomerValidator?

SomeExternalWebApiClient client = new SomeExternalWebApiClient();
var validator = new CustomerValidator(client);

**Comment by JeremySkinner** [comment]
Yes, it's a constructor parameter.

**Comment by htzhang2** [comment]
Can you update the example then? Caller should pass client to CustomerValidator.

**Comment by JeremySkinner** [comment]
Sure, I'll try and get to it when I have some time, or if you'd like to fix it yourself please feel free to submit a PR.

**Comment by JeremySkinner** [comment]
Fixed in 2ae6be3bfe60fb75baa266959772ec6e11941a8f
