### ISSUE TITLE
CollectionIndex is zero based

### ISSUE THREAD

**Issue by NickLocke** [FluentValidation/FluentValidation#1482]
Not an issue, more of an observation or request for a pointer.  This syntax is fantastic for showing the index in the error message:

`RuleForEach(x => x.AddressLines).NotNull().WithMessage("Address {CollectionIndex} is required.");`

However, because it is zero-based, it doesn't sit well with displaying a message to the user - where they would expect the list numbering to start at one.  I may well be missing something (in which case, apologies), but is there a way to get the first collection element to be one rather than zero?

Thanks,  Nick.

**Comment by JeremySkinner** [comment]
Hi, I think the code from my answer to this issue should do what you need: https://github.com/FluentValidation/FluentValidation/issues/1358

**Comment by NickLocke** [comment]
Brilliant, thamk you.
