### ISSUE TITLE
Validation with ruleSets

### ISSUE THREAD

**Issue by Alazrian** [FluentValidation/FluentValidation#1486]
**Which version of FluentValidation are you using?**
9.0.1, 9.1.1

**Describe the issue that you're having**
To validate an object with ruleSets, You have to pass the ruleSets to the Validate function, as written in the documentation. But actually, it only allows as parameter the object or a ValidationContext.
Only the TestValidate accepts ruleSet as Parameters.

**Comment by JeremySkinner** [comment]
Hi there, the validate method that takes rulesets are *extension methods* - you must have the `FluentValidation` namespace imported with a using statement before they'll show up.

**Comment by JeremySkinner** [comment]
For 9.0:
```csharp
using FluentValidation;

namespace MyApp {

  public class Program {
    public static void Main() {
      var validator = new PersonValidator();
      var person = new Person();
      var result = validator.Validate(person, ruleSet: "Names");    
    }
  }
}
```

For 9.1:

```csharp
using FluentValidation;

namespace MyApp {

  public class Program {
    public static void Main() {
      var validator = new PersonValidator();
      var person = new Person();
      var result = validator.Validate(person, options => options.IncludeRuleSets("Names"));
    }
  }
}

```

**Comment by Alazrian** [comment]
Oh thanks Jeremy.
I was really confused as IntelliSense, didn't propose me to add the using.
