### ISSUE TITLE
Make descriptor that returns only rules that are applied to current object

### ISSUE THREAD

**Issue by Dimo99** [FluentValidation/FluentValidation#1487]
For example when I have this code in my validator
```
RuleFor(location => location.ZipCode)
                    .MaximumLength(50)
                    .NotEmpty().WithMessage(x => ResourceFile.EnterZipCode)
                    .When(ShouldValidateLocation);
```
which sets some validation rules to `location.ZipCode` only when some conditions are met. I want to be able to get validator descriptor that will return me rules that will only apply to the specific object I am passing. 
I imagine it to work like this `validator.CreateDescriptor(myLocation)`. I need this feature because I want to return description of the validations I am applying to the object dynamically based on the object itself.

**Comment by JeremySkinner** [comment]
Hi, this isn't really something that'd be possible. Rules don't know anything about specific instances - there's no way to know if they apply to a specific instance or not until they're executed. 

Perhaps you could explain a bit more about what you're trying to achieve and I might be able to suggest an alternative approach?

**Comment by Dimo99** [comment]
Ok, what I want is on GET request from an API to return my object not only with data but with some meta-information with it. Such meta-information is validations. For example, consider this JSON
```
{
  data: {
   "property1": "value1",
  "property2": false
  },
 meta: {
  "property1": {
   "required": true,
   "pattern": "^[a-zA-Z]{3}\d{2}$"
  }
 }
}
```
I can get this information about validations from the validator descriptor. But it will include all the rules, although some rules may not apply to my current object. For example, I want to have validations on `property1` only if `property2` is true. So I thought it would be possible that `CreateDescriptor()` will accept my current object and will return me only the rules that will apply to my current object. As I will have `When` conditions on them.

**Comment by JeremySkinner** [comment]
> So I thought it would be possible that CreateDescriptor() will accept my current object and will return me only the rules that will apply to my current object.

It's not that simple I'm afraid. Understanding whether a rule or condition applies to a specific object requires additional contextual information about the validation request in order to run. This information is only available and constructed at the point that you call `Validate`. The descriptor literally just gives you information about which rules are defined in the class - it doesn't know any more context than this.

However, I think you can still do what you want - you would need to inspect FluentValidation's internal model and essentially set up a 'fake' validation run that can be used to invoke just the conditions, but without the rest of the validator. Here's an example for you:

```csharp
// Our model and validator, for the example.
var model = new Person();
var validator = new PersonValidator();

// Set up a validation context (this is what FluentValidation does when you call Validate).
var context = new ValidationContext<Person>(model);

// A validator internally an IEnumerable containing a collection of rules
// so you can just use regular Linq methods to query them.
// Start by getting a list of all the rules inside the validator.
// Only select rules of type PropertyRule.
List<PropertyRule> rules = validator.OfType<PropertyRule>().ToList();

// Loop over each rule and find the validators inside it.
foreach (var rule in rules) {

	// You can get the property name out from the rule.
	string propertyName = rule.PropertyName;

	foreach (var propertyValidator in rule.Validators) {
		// Does the property validator have a condition? If so, this is what we want to look at
		// Note that validators can have async conditions too (propertyValidator.Options.AsyncCondition)
		// I'm not including that here, but you may wish to do so if you make use of WhenAsync.
		if (propertyValidator.Options.Condition != null) {
			// The condition is a Func<PropertyValidatorContext, bool>
			// so we need to create a PropertyValidatorContext in order to invoke it.
			// We also need to construct the full property path. Normally FV would do this internally.
			string propertyPath = context.PropertyChain.BuildPropertyName(propertyName);
			var propertyValidatorContext = new PropertyValidatorContext(context, rule, propertyPath);
			
			// Now we have the context we can invoke the condition!
			bool appliesToModel = propertyValidator.Options.Condition(propertyValidatorContext);
			// Now you know if the condition applies to your specific model, use this as appropriate.

			// You can use the type name of the property validator for metadata purposes, eg
			bool required = appliesToModel && propertyValidator is NotNullValidator;
		}

	}
}
```

**Comment by Dimo99** [comment]
Yes, that helps a lot. Thank you!

I am closing the issue as the approach above is fine for me and as mentioned by @JeremySkinner my suggestion is not possible to be implemented.
