### ISSUE TITLE
Feature Suggestion: Filter packages based on framework compatibility

### ISSUE THREAD

**Issue by lorenzosoncini** [FluentValidation/FluentValidation#1489]
When I develop a ".Net universe" project the first think is select the version and framework type used.
When I ask visual studio or look at the site I suggest to add a pre-filter of the framework version.
Example:
If I have created a MVC project based on .Net Core 3.1 I would see ONLY .Net Core 3.1 compatible package.

**Describe the solution you'd like**
Add a filter in the package search based on framework type and version.

**Comment by JeremySkinner** [comment]
This is nothing to do with FluentValidation. I think you’ve opened this in the wrong repository.
