### ISSUE TITLE
(InvalidCharacterError with Datetime (Localized?)

### ISSUE THREAD

**Issue by frablaser** [FluentValidation/FluentValidation#1490]
**Which version of FluentValidation are you using?**
Please specify which version of FluentValidation you're using. 
9.1.1

**Which version of ASP.NET are you using?**
If you are using FluentValidation with ASP.NET, please provide the version of ASP.NET that you're using (eg .NET Core 2.1, NET Core 3.1 etc)
ASP.Net Blazor 3.1
On FireFox 79.0

**Describe the issue that you're having**
A clear and concise description of the issue that you're having, steps to reproduce, and sample code to reproduce the issue. 

When I use a date with fluentvalidation, it always fail with an error:

_System.AggregateException: One or more errors occurred. (InvalidCharacterError: String contains an invalid character)
 ---> System.InvalidOperationException: InvalidCharacterError: String contains an invalid character
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)_

My OS is in french, I tried to set CultureInfo.DefaultThreadCurrentCulture and DefaultThreadCurrentUICulture in english even with CultureInfo.InvariantCulture; it don't work. 

The classes used:
```
    public class Person
    {
        public string PersonName { get; set; }
        public DateTime? PersonBirthDate { get; set; }

    }

    public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            RuleFor(r => r.PersonName).NotEmpty().WithMessage("The name counld not be empty!");
            RuleFor(r => r.PersonBirthDate).Must(BirthDateValidator).WithMessage("Error date!");

        }

        private bool BirthDateValidator(DateTime? date)
        {
            return !(date == null || (date < DateTime.Now.AddYears(-99) || date > DateTime.Now.AddYears(-18)));
        }
    }

```

GitHub Source: [https://github.com/frablaser/ErrorDateFireFox](https://github.com/frablaser/ErrorDateFireFox)

**Comment by JeremySkinner** [comment]
Hello, this doesn’t look like it’s related to FluentValidation. The stacktrace you posted does not indicate that FluentValidation is involved. 

I would suggest you begin debugging this by removing FluentValidation and seeing if the same error occurs.

**Comment by frablaser** [comment]
Without FluentValidation, I don't have this error... 
My date is on the format yyyy-MM-dd, I think it looks for a MM/dd/yyyy format or it reverse the year or can not handle the "-" instead of the "/"?

**Comment by frablaser** [comment]
I get this error in any browser.  All the Mozilla browsers has been tested (Chrome, FireFox, New Edge).

**Comment by JeremySkinner** [comment]
Is this a text field that you're entering a date into? If so then I expect this is actually a model-binding issue. 

If you're entering a date in a format that .NET can't convert to a `DateTime`, then it won't be able to bind the value to the `PersonBirthDateProperty`. This isn't a FluentValidation issue - this happens *before* FluentValidation is executed.

**Comment by frablaser** [comment]
This is the inputDate control of Blazor...

**Comment by JeremySkinner** [comment]
Ok, but it's still a model-binding issue. The process is failing at the point where the selected value is converted to a `DateTime`. This is not related to FluentValidation.

**Comment by frablaser** [comment]
It's happens  after the FluentValidation...

**Comment by frablaser** [comment]
Ok... I sent the same error to the Blazor team, I'll wait for their answer. If they say that this is a FV problem, I'll come back with further information! 😉

**Comment by frablaser** [comment]
The GitHub link is at the end of the issue... 😁

**Comment by JeremySkinner** [comment]
> The GitHub link is at the end of the issue...

The repository is empty...

> Ok... I sent the same error to the Blazor team, I'll wait for their answer. If they say that this is a FV problem, I'll come back with further information!

Ok, sounds good. Yes that's sensible - it seems much more likely to be a blazor issue than a FluentValidation issue. I'll close this for now but please re-open if you get more information.

**Comment by frablaser** [comment]
Ho let me see! 👍

**Comment by frablaser** [comment]
Sorry, I forgot to enter the damned comment to get it synchronized! 🙄😉

**Comment by JeremySkinner** [comment]
When I run the application I see this error:

```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@Required' is not a valid attribute name.
```
If I remove the `@Required` on line 22 of Index.razor the application then run, and the validation works correctly (I'm using EN-GB culture on my PC here). If I change the culture to French, it works fine too. 

I think let's wait and see what the Blazor team say 👍

**Comment by frablaser** [comment]
Let me try...
I added the @Required because Firefox add a small X at the end of the control who erase the date and the error went out all the time...  Did you try to enter a digit has for the year by example? When I try to enter the first "2" of 2000 it failed all time...

**Comment by JeremySkinner** [comment]
> Did you try to enter a digit has for the year by example

Yes, I did. It worked fine for me. 

![image](https://user-images.githubusercontent.com/90130/90526603-83110300-e168-11ea-9108-813415de0610.png)

![image](https://user-images.githubusercontent.com/90130/90526632-8a381100-e168-11ea-91ba-fd4927973301.png)

**Comment by JeremySkinner** [comment]
This might also be relevant to you https://stackoverflow.com/questions/60736406/how-to-modify-the-current-culture-date-format-in-blazor-server

**Comment by frablaser** [comment]
My year format still reversed of yours, I use the international date format has : yyyy-MM-dd

![image](https://user-images.githubusercontent.com/29067539/90526962-0289dc80-e13f-11ea-8c61-e032611ad904.png)

**Comment by frablaser** [comment]
> 
> 
> This might also be relevant to you https://stackoverflow.com/questions/60736406/how-to-modify-the-current-culture-date-format-in-blazor-server

I'll try that! 😉👍 

Just for fun, I did my own component to restrict the user years selection, it share a date parameter and I get the same error with FV... 

![image](https://user-images.githubusercontent.com/29067539/90527771-e9356000-e13f-11ea-937a-2cce818b32be.png)

**Comment by JeremySkinner** [comment]
> My year format still reversed of yours, I use the international date format has : yyyy-MM-dd

How/where are you setting this? I'm using `FR-FR` as the default language for the app, and the date format is dd/mm/yyyy. Are you using fr-fr or a different culture?

**Comment by frablaser** [comment]
I use the fr-ca, but my date format is international ha **yyyy-MM-dd**, that where it bumping into I think...

**Comment by JeremySkinner** [comment]
I am explicitly setting the culture to fr-ca in the application startup:

```csharp
public static void Main(string[] args)
{

    CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("fr-ca");
    CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("fr-ca");

    CreateHostBuilder(args).Build().Run();
}
```

I can confirm that this has taken affect by outputting the culture info into the page:

```
  Current Culture name:  @CultureInfo.CurrentUICulture.Name;<br />
  Current date/time:      @DateTime.Now.ToString(); <br/>
  Current culture date format:      @CultureInfo.CurrentUICulture.DateTimeFormat.ShortDatePattern;<br/>
```

... the input field still displays as dd/MM/yyyy (UK default), and there is still no error displayed.

![image](https://user-images.githubusercontent.com/90130/90530992-6f1bd000-e16d-11ea-9f12-55ac3b0a5018.png)

I think at this point unless you're able to update the sample to reproduce the issue, I'll leave it to the blazor team.

**Comment by frablaser** [comment]
This is a Mozilla thing, it store the culture in the cookies... If you flush the recent cookies it should works.

I'm totally stuck... With Blazor Server side, I have to manipulate the cookies to get rid of the culture, it will totally disturb all my web site, that's not a solution. It's funny that in 2020 there still some date unmanagement like that. I have to drop FV or my site Localization... 🙄 I'll wait for the Blazor team to see if the can fix it...

Thanks anyway Jeremy for your support, the day where I'll do money with my site, I'll come back to pay you a good tip.

Best regards Francis

**Comment by JeremySkinner** [comment]
Also I'll point out that the razor integration with FluentValidation (the `<FluentValidator>` component) is not something we provide - so it might be worth reaching out to the authors of this too to see if they're able to shed any light on it.

**Comment by frablaser** [comment]
> 
> 
> Also I'll point out that the razor integration with FluentValidation (the `<FluentValidator>` component) is not something we provide - so it might be worth reaching out to the authors of this too to see if they're able to shed any light on it.

I'll will knock on that door too! Why not! 😉👍

Regards
