### ISSUE TITLE
Wrong validation in AspNetCoreCompatibleEmailValidator 

### ISSUE THREAD

**Issue by ThomasKuijper** [FluentValidation/FluentValidation#1491]
Im using the latest version (9.1.2) of FluentValidation in an ASP.Net Core 5 preview 7 application.
Before upgrading version (8.6.2), the following check gave a correct false validation:

```
RuleFor(v => v.Email)
                .NotEmpty().WithMessage("{PropertyName} is required.")
                .EmailAddress().WithMessage("Enter a valid email address")
                .MaximumLength(200).WithMessage("{PropertyName} must not exceed {MaxLength} characters.")
```

The test value was "thomas@test". So without a top-level domain

After the upgrade the validation now gives valid. 

If i check the _AspNetCoreCompatibleEmailValidator_ i see that it only checks if there is on @ but doesnt check for a top-level domain. Should this be changed?

**Comment by ThomasKuijper** [comment]
Maybe the change could be something like:
```


var value = context.PropertyValue;

if (value == null) {
	return true;
}

if (!(value is string valueAsString)) {
	return false;
}

// only return true if there is only 1 '@' character
// and it is neither the first nor the last character
int atIndex = valueAsString.IndexOf('@');
int dotIndex = valueAsString.LastIndexOf('.');

return
	atIndex > 0 &&
	atIndex != valueAsString.Length - 1 &&
	atIndex == valueAsString.LastIndexOf('@') &&
	atIndex < dotIndex;

```

**Comment by JeremySkinner** [comment]
Hi, this is intentional. 

It is to match the behaviour of ASP.NET Core's `EmailAddressAttribute` (which has the same logic) and their client-side validation. Please see the documentation for more details behind this: https://docs.fluentvalidation.net/en/latest/built-in-validators.html#email-validator
