### ISSUE TITLE
Add ValidationException To ModelState

### ISSUE THREAD

**Issue by baffourt** [FluentValidation/FluentValidation#1492]
**Which version of FluentValidation are you using?**
FluentValidation 8.6.2

**Which version of ASP.NET are you using?**
I am using FluentValidation with ASP.NET, NET Core 3.1

**Describe the issue that you're having**
I am testing out JasonTaylor's CleanArchitecture Template [https://github.com/jasontaylordev/CleanArchitecture](url), with Razor Pages. I want to show Validation errors to the client on the page with 
`<span asp-validation-for="Command.CenterName" class="text-danger"></span>`

However, I am unable to add the errors on ValidationException to the ModelState so that it appears correctly.
I added the FluentValidation.AspNetCore to the Razor pages project and then I could show relevant messages to the client. 
`services.AddRazorPages()
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CreateCenterCommandValidator>());`

However, some validation rules use the DbContext and so it is injected into the Validator class when I  do that, my Tests fail with an error that `A second operation started on this context with EFCore...`. If I remove the package FluentValidation.AspNetCore and only depend on the FluentValidations in my Class Library, I lose the behavior of being able to show validation rules to the client but rather have a ValidationException returned.

I want a way to mimic the behaviour of FluentValidations.AspNetCore by adding all errors in the ValidationException to the ModelState so that it can be displayed properly.

**Comment by JeremySkinner** [comment]
Hello,

> rules use the DbContext and so it is injected into the Validator class when I do that, my Tests fail with an error that A second operation started on this context with EFCore...

You need to ensure that your validators are transient (instantiated every time they're needed, and not cached) so they don't hold on to an old dbcontext instance. 

> I want a way to mimic the behaviour of FluentValidations.AspNetCore by adding all errors in the ValidationException to the ModelState so that it can be displayed properly.

FluentValidation has an `AddToModelState` extension method that copies the errors from the `ValidationResult` to `ModelState`. Please see this page in the documentation: https://docs.fluentvalidation.net/en/latest/aspnet.html#manual-validation

**Comment by baffourt** [comment]
Thank you @JeremySkinner for this amazing job. I am trying to implement your suggestion. 
What I have done so far is remove dependence on FluentValidations library on the Razor page project. I get the ValidationException object with a dictionary of Errors. It appears that to get the Library in my Razor project before I can use `AddToModelState` extension.

`var exception = context.Exception as ValidationException;
            var validationResult = new ValidationResult(exception.Failures);
            validationResult.AddToModelState(context.ModelState, null);
            context.Result = new ViewResult { ViewData = new ViewDataDictionary(ModelMetadataProvider, context.ModelState) };
            context.ExceptionHandled = true;`

validationResult does not contain a definition for AddToModelState
Kindly check this issue when you are able
[https://github.com/jasontaylordev/CleanArchitecture/issues/153](url)

**Comment by JeremySkinner** [comment]
It's an extension method. You need a using statement for the FluentValidation namespace

**Comment by baffourt** [comment]
I have added the appropriate using statement for FluentValidation. Same error, 
`validationResult.AddToModelState(context.ModelState, null)` gives validationResult does not contain a definition for `AddToModelState`.
I have `using FluentValidation`

**Comment by JeremySkinner** [comment]
Sorry my mistake, it’s in the FluentValidation.AspNetCore namespace, not just FluentValidation. https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation.AspNetCore/ValidationResultExtensions.cs

**Comment by baffourt** [comment]
Very appreciative of your time @JeremySkinner. 
With your help, I have solved this by adding FluentValidation.AspNetCore and then injecting it into the Startup class with
`services.AddRazorPages().AddFluentValidation()` without specifying any Validators. Then the ValidationException raised from my service layers is properly propagated and the ModelState.Valid returns false meaning that the Service is not even called.
The ExceptionFilter does not even hit with ValidationException since it appears the FluentValidation.AspNetCore handles that error.
All tests are passing alright, thank you for the direction.
