### ISSUE TITLE
IRuleBuilderInitial should have the extension WithName

### ISSUE THREAD

**Issue by MarquitosPT** [FluentValidation/FluentValidation#1494]
Hi,

In my opinium the interface **IRuleBuilderInitial** should have the extension method "_**WithName**(string propertyName)_", same as the interface **IRuleBuilderOptions**.

First, is because in initial declaration we are declaring an rule for a property. So it would be the first chance to set the property display name.

Second, if we don't have any rule for a specific optional property, for example a **DateTime?** property, in client side validation we still need to show a validation message if the datetime as an invalid format. Here it would be nice to define the property Name in our current Culture.

Thanks :)

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. For the first scenario that's a good idea. I'll look at getting that added for a future version. 

For the second scenario this won't help though I'm afraid. There are two separate things here that aren't the same:
- Invalid format messages
- Clientside messages 

Invalid format messages are generated by ASP.NET's model binding process, not by FluentValidation. Model binding happens before validation (at the point the object is instantiated and its properties are set). If this process fails (eg if you send an invalid value for a DateTime) then ASP.NET's model binding will generate an error. This happens prior to validation occurring - FluentValidation doesn't get a chance to generate these messages, so defining a message in the validator won't have any affect here as FluentValidation's rules require the property to have been set first.

Clientside messages are different, and run through ASP.NET's clientside validator API. FluentValidation provides metadata to ASP.NET that allows it to generate the appropriate the appropriate clientside validation attributes, including the messages. This process is a one to one mapping, for example a call to `RuleFor(x => x.Name).NotNull().WithName("Nom")` is converted to `data-val-required="Nom must not be empty"`. There must always be validator to generate the message for. A call to `RuleFor(x => x.Name).WithName("Nom")` would not generate anything on the clientside, as clientside metadata needs to be associated with a specific type of validation rule. 

Hope that helps explain things. For the first scenario this seems like a reasonable idea though.

**Comment by JeremySkinner** [comment]
On reflection, this won't be something we implement. For scenario 1, this doesn't really make sense as setting the name without having a preceding validator is a no-op, and won't do anything. It only makes sense if there's at least 1 validator in the rule chain, which is why it appears second, and for scenario 2 this wouldn't actually work as per my previous reply.
