### ISSUE TITLE
ScalePrecisionValidator not working properly

### ISSUE THREAD

**Issue by AdrianoAE** [FluentValidation/FluentValidation#1495]
.Net Core 3.1
FluentValidation.AspNetCore 9.1.3

The ScalePrecisionValidator IgnoreTrailingZeros is not working properly, if we have a ScalePrecision(2, 4, true) the value "1234" should be valid.

https://github.com/FluentValidation/FluentValidation/pull/1356#issue-396007324
@nhowell The tests done in this function "Scale_precision_should_be_valid_when_ignoring_trailing_zeroes" missed this case.

**Comment by JeremySkinner** [comment]
Thanks for reporting this, I'm not particularly familiar with the ScalePrecisionValidator myself but I'll happily accept a PR if you (or someone else) would like to fix it. Thanks!

**Comment by AdrianoAE** [comment]
My bad, tested in SQL Server and it's working properly accordingly to the spec.
