### ISSUE TITLE
[Bug] name@domain passes email validation

### ISSUE THREAD

**Issue by alierdogan70** [FluentValidation/FluentValidation#1496]
**Which version of FluentValidation are you using?**
9.0.0.0

**Which version of ASP.NET are you using?**
Windows Forms Application. Runtime v4.0.30319

**Describe the issue that you're having**
RuleFor(x => x.Email).MaximumLength(100).EmailAddress().When(x => !string.IsNullOrWhiteSpace(x.Email));

'name@domain' passes the validation. Validator does not check for the period.

**Comment by JeremySkinner** [comment]
Hi, this behaviour is correct - the email validator is intentionally naive. Please review these sections in the documentation for details:

https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#default-email-validation-mode-changed
https://docs.fluentvalidation.net/en/latest/built-in-validators.html#email-validator

**Comment by JeremySkinner** [comment]
You might also find this of interest: https://www.reddit.com/r/csharp/comments/hlzpwn/why_is_emailaddress_attribute_validating_as_true/

**Comment by alierdogan70** [comment]
Thanks @JeremySkinner . It looked absolutely wrong so I did not check the documents. Sorry for that.
