### ISSUE TITLE
Question: How to tie a Validation failure to a particular property when using RuleForEach with Must

### ISSUE THREAD

**Issue by bancroftway** [FluentValidation/FluentValidation#1498]
**Which version of FluentValidation are you using?**
9.0

**Which version of ASP.NET are you using?**
ASP.Net Core 3.1 with Blazored.FluentValidation

**Describe the issue that you're having**
I have a class 'Container' which has a list of child objects called 'Activities'. I am building this validation rule on the child Activity object: the 'Actual' property can either be entered on the very first activity or if the previous activity also has the 'Actual' property filled out. The validation code below works fine, but the Validation message is not tied to the 'Actual' field. In my Blazor application, I have a grid of activities and I want to highlight in red color the textbox(es) that are bound to Activity.Actual. Is there a way I can tell FluentValidation that this validation failure should be associated to the 'Actual' field?

```
public class ContainerValidator : AbstractValidator<Container>
        {
            public ContainerValidator ()
            {
                RuleForEach(x => x.Activities).Where(x => x.Actual.HasValue).Must((container, activity, ctx) =>
                {
                    //this activity must be either the very first activity or the previous activity must also have an actual
                    //find index of the current activity
                    var activityIndex = container.Activities.IndexOf(activity);
                    var previousActivity = activityIndex > 0 ? rig.ActivitiesToDisplay[activityIndex - 1] : null;
                    return (previousActivity == null || previousActivity.Actual.HasValue);

                }).WithMessage("Actual not allowed");
            }
        }
```

**Comment by JeremySkinner** [comment]
Hi, a couple of options. 

# Option 1: Use a separate validator, which can associate the rule directly against the Actual property

This is the standard approach. When you use an explicit child validator, you can define rules against its individual properties. 

```csharp
public class ContainerValidator : AbstractValidator<Container> {
	public ContainerValidator() {
		RuleForEach(x => x.Activities)
                    .Where(x => x.Actual.HasValue)
                   .SetValidator(container => new ActivityValidator(container));
	}

}


public class ActivityValidator : AbstractValidator<Activity> {
	public ActivityValidator(Container container) {
		RuleFor(x => x.Actual).Must((activity, actual) => {
				var activityIndex = container.Activities.IndexOf(activity);
				var previousActivity = activityIndex > 0 ? rig.ActivitiesToDisplay[activityIndex - 1] : null;
				return (previousActivity == null || previousActivity.Actual.HasValue);
		})
		.WithMessage("Actual not allowed");
	}
}
```

# Option 2: Custom rule

Gives you complete control of the process for generating the validation failure, but is less "fluent"

```csharp
public class ContainerValidator : AbstractValidator<Container> {
	public ContainerValidator() {
		RuleFor(x => x.Activities)
			.Custom((activities, context) => {
				int index = 0;
				foreach (var activity in activities) {
					if (activity.Actual.HasValue) {
						var previousActivity = index > 0 ? rig.ActivitiesToDisplay[index - 1] : null;
						bool valid = (previousActivity == null || previousActivity.Actual.HasValue);
						if (!valid) {
							context.AddFailure($"Activities[{index}].Actual");
						}
					}
					index++;
				}
			});
	}

}

```

**Comment by bancroftway** [comment]
@JeremySkinner  thank you so much for this solution. We love this library, and could not have done without it. Thanks!!
