### ISSUE TITLE
CascadeMode.StopOnFirstFailure why is going to be removed?

### ISSUE THREAD

**Issue by PatryxCShark** [FluentValidation/FluentValidation#1500]
Hi,
My FluentValidation ver. is 9.1.3 for .NET Core
Why are you going to remove CascadeMode.StopOnFirstFailure completely? As I read: 
[https://docs.fluentvalidation.net/en/latest/conditions.html#stop-vs-stoponfirstfailure](link) the behaviour of CascadeMode.Stop is completely different and I want to stop validation for a particular rule chain, nor for all next rules. If you remove StopOnFirstFailure I wouldn't have such possibility...Maybe better is to leave both options in future? Or you can advise me how to achieve my goal using Stop?
`RuleFor(x => x.Surname).Cascade(CascadeMode.StopOnFirstFailure).NotNull().NotEqual("foo");
RuleFor(x => x.Forename).Cascade(CascadeMode.StopOnFirstFailure).NotNull().NotEqual("foo")`
When I change to Stop then if any Surname chain rule fails it will not check Forename at all - I want to stop only in particular chain rule (as it was in the example code). Is it possible?!

**Comment by buvinghausen** [comment]
@JeremySkinner I think the ability to fail fast is good but typically speaking I want to give the user feedback on all the failed properties at once what I don't like is giving them multiple lines of feedback per property.  As such the stop on first failure set at the validator level was exactly what I wanted.  Now I have to add the cascade call to every single rule for which is tedious and verbose when you're dealing with so many properties.

**Comment by JeremySkinner** [comment]
@buvinghausen You can still use the old behaviour. It’s not been removed.

**Comment by buvinghausen** [comment]
@JeremySkinner for 9.1 yes but how do achieve what I want in 10.0 when it drops?

**Comment by JeremySkinner** [comment]
The feature is not being removed. It will continue to work in 10.0, and will generate a warning, just as it does now.

**Comment by buvinghausen** [comment]
Thanks for the clarification....
