### ISSUE TITLE
SetValidator not obeying RuleSet as expected

### ISSUE THREAD

**Issue by ChaseFlorell** [FluentValidation/FluentValidation#1502]
**Which version of FluentValidation are you using?**
9.1.3

**Which version of ASP.NET are you using?**
n/a

**Describe the issue that you're having**

With the following Validator, when I attempt to validate with a null `AuthorizedFacility`.

```csharp
var result = _validator.ValidateAsync(this, opts => opts.IncludeRuleSets(nameof(ServiceNoOrderDetailWorkflowStep));
``` 

Expected: `result.IsValid` should be `false`

Actual: `result.IsValid` is `true`

```csharp
public sealed class ServiceNoOrderDetailsWorkflowViewModelValidator : AbstractValidator<ServiceNoOrderDetailsWorkflowViewModel>
{
    public ServiceNoOrderDetailsWorkflowViewModelValidator()
    {
        RuleFor(x => x.Context)
           .SetValidator(new StepOneValidator(), STEP_ONE);
    }

    private sealed class StepOneValidator : AbstractValidator<ServiceNoOrderWorkflowContext>
    {
        public StepOneValidator()
        {
            RuleFor(x => x.AuthorizedFacility)
               .NotNull()
               .WithName(Resources.PROP_AuthorizedFacility);
        }
    }

    private const string STEP_ONE = nameof(ServiceNoOrderDetailWorkflowStep);
}
```

**Comment by JeremySkinner** [comment]
Hi, I think you might have misunderstood how to define rulesets.

Rulesets are defined by wrapping specific rules in the `RuleSet` method. In this particular example, you haven't actually defined the ruleset anywhere (by calling `RuleSet`), so when you call `ValidateAsync` passing in `ServiceNoOrderDetailWorkflowStep`, nothing will actually be executed.

Inside your `StepOneValidator`, you would need to define the ruleset like this:

```csharp
RuleSet(nameof(ServiceNoOrderDetailWorkflowStep), () => {
   RuleFor(x => x.AuthorizedFacility)
               .NotNull()
               .WithName(Resources.PROP_AuthorizedFacility);
});
```

**Comment by JeremySkinner** [comment]
(Updated my response for clearer examples)
