### ISSUE TITLE
Add method "Validate(object o)" to IValidator interface

### ISSUE THREAD

**Issue by gevorgter** [FluentValidation/FluentValidation#1503]
**Is your feature request related to a problem? Please describe.**
It allows me to built a Dictionary<Type, IValidator>. Then when i need to validate my DTO i can get IValidator from my Dictionary and run IValidator.Validate(dtoObject);
Unfortunately right now you have to know Generic Type to get IValidator<T> to call Validate(T instance). So i can not build my  Dictionary<Type, IValidator>. Idea is to have a method that would validate all my DTOs by getting DTO type and finding validator in my Dictionary.

**Describe the solution you'd like**
1. Add "ValidationResult Validate(object o);" to interface IValidate
2. Add method to AbstractValidator<T>
ValidationResult IValidator.Validate(object instance) 
{
	return Validate((T)instance);
}

**Describe alternatives you've considered**
I could not find any alternative. 

**Additional context**
Add any other context or sample code about the feature request here.

**Comment by JeremySkinner** [comment]
This overload was intentionally removed. You can achieve the same result by instantiating a context to wrap the object and passing this in instead. Please see https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload

```
var context = new ValidationContext<object>(model);
var result = validator.Validate(context);
```
