### ISSUE TITLE
Documentation for overridding ValidateAsync

### ISSUE THREAD

**Issue by robertlarkins** [FluentValidation/FluentValidation#1506]
**Is your feature request related to a problem? Please describe.**
This is a feature request for documentation, particuraly around overriding `ValidateAsync`. I have seen some references to doing this from google searches, but nothing in the official documentation.

**Describe the solution you'd like**
A description of overriding `ValidateAsync`, when to consider this approach, and any issues to be aware of when doing this.

**Describe alternatives you've considered**
The reason for me looking at `ValidateAsync` is whether it is a better alternative than doing the following:
```c#
RuleFor(x => x).Custom(
	(dto, context) =>
	{
		var animalIds = dto.Animals.Select(x => x.Id);
		var animals = dbContext.Animals.Where(x => animalIds.Contains(x.Id)).ToList();

		foreach (var animal in dto.Animals)
		{
			if (animals.All(x => x.Id != animal.Id))
			{
				context.AddFailure(new ValidationFailure("Animal.Id", $"Animal with Id {animal.Id} is unknown."));
			}
		}
	});
```

which goes through the array of animals gets their Ids and then checks each Id to see if it is in the database. The reason for retrieving all the animals in one go is to avoid doing a database calls for each animal (which could be done as a method from a `Must`).

Alternatively are there other ways of doing this that fits into the standard FluentAssertions structure within the documentation? Such as accessing the dto directly in the constructor rather than within a `RuleFor`?

**Comment by JeremySkinner** [comment]
Hello,

I'm not really sure what kind of documentation you're expecting for this. There isn't any particular guidance for when you should override Validate/ValidateAsync, other than that it's an extensibility point that exists for you to use if you want it, but that's totally up to you. Usually people override Validate/ValidateAsync if they need to do post-processing of the validation results prior to being returned. There isn't really anything else to say about it other than that.

> The reason for me looking at ValidateAsync is whether it is a better alternative than doing the following:

Either approach works. Personally I'd stick with `RuleFor()` for consistency - all the rules are in one place (the constructor), but use what you like the best. There is no practical difference. 

> Alternatively are there other ways of doing this that fits into the standard FluentAssertions structure

You can use a custom property validator class. https://docs.fluentvalidation.net/en/latest/custom-validators.html#reusable-property-validators This will then allow you to simplify your rule definition into something like `RuleFor(x => x.Animals).SetValidator(new AnimalsExistValidator(dbContext))` 

The `AnimalsExistValidator` would contain the logic for iterating over the collection and performing the db lookup, using the `PropertyValidator` base class I linked to.

Hope that helps

**Comment by robertlarkins** [comment]
That is very useful, thanks.

(Personally) I think even this sort of information about Validate/ValidateAsync has a place in the documentation, particularly for recommendations for when it might be used, such as the usual case of post-processing validation results. I may have missed it, but maybe even if the docs listed these (and other?) extensibility points, which would tell people that they exist.

**Comment by JeremySkinner** [comment]
I've added this to the to-do list of things to document (#820), although it might take a while for me to get to it I'm afraid as it'll be pretty low down the priority list.
