### ISSUE TITLE
Unexpected result when I try to use condition like `When`

### ISSUE THREAD

**Issue by Shishkovskiy** [FluentValidation/FluentValidation#1507]
Version="9.1.2"
NET Core 3.1 

- PaymentCurrencyIsoCodes it`s the list of string

```
            this.When(
                    accountInvoiceCurrencySettingsUpdateViewModel =>
                        accountInvoiceCurrencySettingsUpdateViewModel.PaymentCurrencyIsoCodes.Count == 0,
                    () => { this.RuleFor(accountInvoiceBillingPeriodSettingsUpdateViewModel => accountInvoiceBillingPeriodSettingsUpdateViewModel.MainCurrencyIsoCode == "GBP"); })
                .Otherwise(() => this.RuleFor(accountInvoiceCurrencySettingsUpdateViewModel => accountInvoiceCurrencySettingsUpdateViewModel.MainCurrencyIsoCode).NotEmpty().NotNull());


```

**Comment by JeremySkinner** [comment]
Please provide more detail. A code snippet by itself is not enough for me to help you with... 

What is the expected result? What's the actual result? What data are you providing?

**Comment by JeremySkinner** [comment]
I've also reformatted the code example for you. The first call to `RuleFor` is wrong. It doesn't contain a valid rule. You have this:

```
  RuleFor(model => model.MainCurrencyIsoCode == "GBP"); 
```

Should be this:
```
  RuleFor(model => model.MainCurrencyIsoCode).Equal("GBP"); 

```

*Dont put the equality check inside the RuleFor!*

**Comment by Shishkovskiy** [comment]
@JeremySkinner It was my mistake, I've resolved everything)
Sorry for disturbed, thank you a lot and have a good day)
