### ISSUE TITLE
Built-in validator NotEmpty shoulds check where a Guid is empty (Guid.Empty) or not.

### ISSUE THREAD

**Issue by ypBaptiste** [FluentValidation/FluentValidation#1514]
**Is your feature request related to a problem? Please describe.**
The built-in validator NotEmpty doesn't check whethere a Guid is empty or not.

**Describe the solution you'd like**
I think this validator shoulds perform this check on Guid, not only on string.

**Describe alternatives you've considered**
The alternative is to use a Must validator.
```
.Must(id => id.Value != Guid.Empty)
                    .WithErrorCode(CodesErreurs.FIELD_MANDATORY).WithMessage(Erreurs.FIELD_MANDATORY);
```
Thanks to considering this :)

**Comment by JeremySkinner** [comment]
Good idea, thanks. I'll get that added for the next version.

**Comment by JeremySkinner** [comment]
Actually I just checked this and it's already implemented - it correctly NotEmpty already treats Guid.Empty as a failure.

**Comment by ypBaptiste** [comment]
Ok, I will checks that again.
Thanks.
