### ISSUE TITLE
Validator inheritance

### ISSUE THREAD

**Issue by GioviQ** [FluentValidation/FluentValidation#1516]
I would like to create something like this:

     RegisterViewModelValidator : LoginInputModelValidator<RegisterViewModel>

where LoginInputModelValidator is (pseudo code)

     LoginInputModelValidator<T> : AbstractValidator<T> where T is LoginInputModel

Is it possible in some way?

Thank you

**Comment by JeremySkinner** [comment]
Yes, you can do exactly that.
