### ISSUE TITLE
Unable to install packages via nuget for .Net Core 3.1 application

### ISSUE THREAD

**Issue by rizinhussain** [FluentValidation/FluentValidation#1518]
**Which version of FluentValidation are you using?**
v9.2.0

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I have been trying to create a .net core api project using Fluent Validation. but when trying to add relevant nuget packages to the .net core(3.1) api project using nuget console and nuget package manager getting error as follows

Error		Package restore failed. Rolling back package changes for 'FluentValidation.WebApi'.				

Error	NU1202	Package FluentValidation 9.2.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package FluentValidation 9.2.0 does not support any target frameworks.
	
Error	NU1202	Package FluentValidation.DependencyInjectionExtensions 9.2.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package FluentValidation.DependencyInjectionExtensions 9.2.0 does not support any target frameworks.

Looking forward for the solution. ASAP

**Comment by JeremySkinner** [comment]
Hi, you’re installing the wrong package. You need to install FluentValidation.AspNetCore. 

FluentValidation.WebApi is a deprecated package for the old WebApi2 (for .net 4)

https://docs.fluentvalidation.net/en/latest/aspnet.html
