### ISSUE TITLE
Interface support as e.g. AbstractValidator<IContact>

### ISSUE THREAD

**Issue by GioviQ** [FluentValidation/FluentValidation#1522]
I found that using something like AbstractValidator<IContact> is not working. I have to use class instead of interface AbstractValidator<Contact>.

Thanks

**Comment by JeremySkinner** [comment]
I don’t understand what you’re asking. AbstractValidator works fine with interfaces. 

Please provide *all details* of what’s not working, including the version you’re using and any sample code necessary to reproduce the problem (which  was requested in the issue template)

**Comment by GioviQ** [comment]
In fact I am using https://github.com/Blazored/FluentValidation 
so if you say that it is working I suppose depend on registration. I let you know...

**Comment by JeremySkinner** [comment]
That’s a separate project maintained by other people. If you need help with Blazored.FluentValidation you should ask on their issue tracker, not on here.
