### ISSUE TITLE
Blazor Project Updating 8.6.2 to 9.20.

### ISSUE THREAD

**Issue by carlblanchard** [FluentValidation/FluentValidation#1524]
When I try updating the Nuget package in my Blazor project I get this error. Blazor targets .Net standard 2.1 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package FluentValidation.AspNetCore 9.2.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package FluentValidation.AspNetCore 9.2.0 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Comment by JeremySkinner** [comment]
Hello,

The FluentValdiation.AspNetCore is for ASP.NET MVC integration. It does not provide Blazor integration. 

You should be using the FluentValidation package, not FluentValidation.AspNetCore.

**Comment by JeremySkinner** [comment]
Additionally you can make use of one of several 3rd party components that provide integration between FluentValidation and Blazor: https://docs.fluentvalidation.net/en/latest/blazor.html

**Comment by carlblanchard** [comment]
Thanks, I've had it working quite nicely in my Blazor project for about 5 months. I was really impressed that it all just worked.
