### ISSUE TITLE
Using ChildValidatorAdaptor in version 9.x

### ISSUE THREAD

**Issue by furqansafdar** [FluentValidation/FluentValidation#1526]
Hi Jeremy,

I had a discussion with you over a scenario where you helped me solving the problem at hand in the below link:
https://github.com/FluentValidation/FluentValidation/issues/979

Now i have updated the library to 9.x and found the breaking changes, this led me to the documentation post of upgrade guide:
https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html

I see now the `ChildValidatorAdaptor<T, TProperty>` is taking two generic arguments. My confusion is why the implementation is TProperty specific which was not the case earlier. Any detailed documentation on new implementation of ChildValidatorAdaptor so that i can make the code compatible with new changes.

**Which version of FluentValidation are you using?**
I have updated the library to 9.2.0 directly from 8.6.2

**Comment by JeremySkinner** [comment]
Hi, it's part of an ongoing effort to introduce generics throughout the library's core, which will eliminate boxing and help with performance. Part of this is that PropertyValidator instances will require an exact type match to the property being validated going forward. 9.x introduced this in only a couple of places, and the rest of it is planned for 10.0, as it was too big a chance to do at once. The downside of doing this is it makes it a bit harder to do some of the more dynamic things that were possible before (like what you're doing).  

Essentially, you need to wrap the resulting validator to handle the type conversion for you. I was going to suggest the `PolymorphicValidator` to handle this ([as it handles the type conversion for subclasses for you](https://docs.fluentvalidation.net/en/latest/inheritance.html)), but wouldn't quite work in your situation as it needs to know the derived type at compile time. 

For now, you can work around this limitation with a bit of reflection, but I'll make an update to add support for dynamic retrieval of subclasses in the next version. Here's a workaround that will work for now:


```csharp
public class SchedulerTaskCollectionValidator<T> : PolymorphicValidator<T, SchedulerTask>
{
	public override IValidator<SchedulerTask> GetValidator(PropertyValidatorContext context)
	{
		var obj = context.PropertyValue;
		var abstractValidatorType = typeof(AbstractValidator<>);
		var objType = obj.GetType();
		var genericType = abstractValidatorType.MakeGenericType(objType);
		var validatorType = FindValidatorType(objType.Assembly, genericType);
		var validatorInstance = (IValidator)Activator.CreateInstance(validatorType);

		var addMethod = GetType()
			.GetMethods()
			.Where(x => x.Name == "Add")
			.Single(x => x.GetParameters()[0].ParameterType.GetGenericTypeDefinition() == typeof(IValidator<>));

		var closedGenericMethod = addMethod.MakeGenericMethod(objType);
		closedGenericMethod.Invoke(this, new[] {validatorInstance, null});

		return base.GetValidator(context);
	}

	private static Type FindValidatorType(Assembly assembly, Type genericType)
	{
		if (assembly == null) throw new ArgumentNullException(nameof(assembly));
		if (genericType == null) throw new ArgumentNullException(nameof(genericType));
		return assembly.GetTypes().FirstOrDefault(t => t.IsSubclassOf(genericType));
	}

}

```

Note the reflection to invoke the `Add<TDerived>` method, which adds the subclass mapping. Not great, but should suit as a temporary solution. I can try and push out a 9.2.1 hotfix that allows you to add the subclass mapping without the reflection, if this solution works for you.

Also note that this is an area that is likely to change slightly in FluentValidation 10, when the move to generics is complete (`PropertyValidatorContext` will most likely become `PropertyValidatorContext<T,TProperty>`), so just a heads up for that.

**Comment by JeremySkinner** [comment]
Thinking about this further, allowing the `GetValidator` method to return an `IValidator` like in the original implementation would not be problematic for our future introduction of generics, so I may actually reintroduce the original method overload, as it was nice to have that flexibility. Let me have a play with it over the weekend and I'll let you know what I decide.

**Comment by JeremySkinner** [comment]
I've pushed out a 9.2.1 package which adds a non-generic `Add` method to the PolymorphicValidator, so the above example can be simplified to: 

```csharp
public class SchedulerTaskCollectionValidator<T> : PolymorphicValidator<T, SchedulerTask>
{
	public override IValidator<SchedulerTask> GetValidator(PropertyValidatorContext context)
	{
		var obj = context.PropertyValue;
		var abstractValidatorType = typeof(AbstractValidator<>);
		var objType = obj.GetType();
		var genericType = abstractValidatorType.MakeGenericType(objType);
		var validatorType = FindValidatorType(objType.Assembly, genericType);
		var validatorInstance = (IValidator)Activator.CreateInstance(validatorType);

		Add(objType, validatorInstance);               

		return base.GetValidator(context);
	}

	private static Type FindValidatorType(Assembly assembly, Type genericType)
	{
		if (assembly == null) throw new ArgumentNullException(nameof(assembly));
		if (genericType == null) throw new ArgumentNullException(nameof(genericType));
		return assembly.GetTypes().FirstOrDefault(t => t.IsSubclassOf(genericType));
	}
}
```

Regarding ChildValidatorAdaptor, I think I will change its `GetValidator` method to return an `IValidator` rather than `IValidator<TProperty>`, but as this will be a breaking change it'll need to hold off until the next major version (unless you really need it sooner, in which case I can work something out, but I think the PolymorphicValidator update will suit your situation).

**Comment by furqansafdar** [comment]
Thanks for your quick updates in the library and suggestions for the workaround. Note that I am not in a hurry for making these changes infact i would rather prefer to wait until the library is fully supportive to these changes. Few suggestions i wanna make here, consider keeping `IValidator` instead of returing `IValidator<TProperty>` to keep things simple, secondly generics are good to avoid boxing for performance reasons but why not just have simple implementation of PolymorphicValidator<T> instead of PolymorphicValidator<T, TInterface> because all we need is `IValidator` which should work regardless of base class information.

**Comment by JeremySkinner** [comment]
I've committed the change to `ChildValidatorAdaptor` so that `GetValidator` now returns an `IValidator` (2e1bc86e). This will be in the 10.0 release.

> but why not just have simple implementation of PolymorphicValidator<T> instead of PolymorphicValidator<T, TInterface>

`PolymorphicValidator` inherits from `ChildValidatorAdaptor<T,TProperty>`, which requires the second generic, so this will stay in place for PolymorphicValidator. It also aids with type safety in the fluent interface so that when you call `Add<TDerived>(IValidator<TDerived> derived)` it knows whether the validator allowed for the type, as `TDerived` is constrained to `where TDerived : TProperty`
