### ISSUE TITLE
Discussion: FluentValidation breaking changes going forward

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1527]
For FluentValidation 10, I'm considering making several breaking changes that I feel will help the library continue to evolve, but I'm not sure whether these changes are necessarily worth it. Over the last 10 years I've tried to avoid major breaking changes as FluentValidation has a large user-base, and also breaking changes tend to generate a large number of support requests. As the only developer on this project (which I do in my free time), support requests can be a huge time-sink. 

I'd really appreciate others' opinions of whether this is a worthwhile effort, particularly those who have been involved in similar efforts in other OSS projects. At the moment there are 3 main areas I'm considering which will introduce breaking changes: Generics in the internal model, changes asynchronous validation, and dropping support for older .NET versions.

# Generics in the Internal Model.

FluentValidation's public API (the fluent interface) is strongly-typed with generics. This public API builds an internal model, which does *not* use generics, and uses `object` instances to represent both the root model being validated, as well as the individual property values. This decision was originally made to allow the internal API to be a lot more malleable, and be able to customize/extend behaviour which isn't necessarily type-safe at compiletime (but would be at runtime). 

An example of this is [transformations](https://docs.fluentvalidation.net/en/latest/transform.html) which allow the type of the property for while the rule is defined to be changed to another type.

I would like to change this to use generics all the way through FluentValidation, which will eliminate boxing and provide much more type-safety throughout. The main areas that need changing are `PropertyRule` and `PropertyValidator` (and all their subclasses).

PropertyRule represents a rule, and is instantiated whenever you call `RuleFor`. This would be changed to `PropertyRule<T>`, and would receive a `ValidationContext<T>` during its Validate methods. I don't think there are many people this would affect (although I could be wrong). Instantiating a Rule class directly isn't something that would be done outside of the library (with hindsight, this should not have ever been a public class but back when I started the project I thought it was better that as much as possible was public/virtual. Unfortunately this makes it hard to change the internal model without affecting end users)

As well as the internal model, there are a couple of parts of the public API that would be affected. For years, the way to make a reusable property validator was to create a class that inherits from `PropertyValidator` ([docs](https://docs.fluentvalidation.net/en/latest/custom-validators.html#reusable-property-validators)). This would require anyone using this approach to inherit from a new `PropertyValidator<T, TProperty>` instead. Anyone accessing the `InstanceToValidate` or `PropertyValue` properties on `PropertyValidatorContext` would also need to change to using `PropertyValidatorContext<T, TProperty>` instead. 

The fluent interface would also receive an additional type-parameter, representing the current property validator that is active in the chain. This would affect custom extension methods that add to the fluent interface (which is a popular way of extending the library). For example, the `WithMessage` method in the library currently looks like this:

```csharp
public static IRuleBuilderOptions<T, TProperty> WithMessage<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorMessage) {
	return rule.Configure(config => {
			config.CurrentValidator.Options.SetErrorMessage(errorMessage);
	});
}
```
...but would instead become something like the following (note the extra generic)

```csharp
public static IRuleBuilderOptions<T, TProperty, TValidator> WithMessage<T, TProperty, TValidator>(this IRuleBuilderOptions<T, TProperty, TValidator> rule, string errorMessage) {
	return rule.Configure((rule, currentValidator) => {
		currentValidator.SetErrorMessage(errorMessage);
	});
}
```

This would affect anyone who has built extension methods on top of `IRuleBuilder<T,TProperty>` 

# Asynchronous changes

Covered by https://github.com/FluentValidation/FluentValidation/issues/1481. At the moment it's too easy to accidentally force async rules to be run synchronously. This change would introduce a separate base class for validators (`AsyncAbstractValidator`). Async property validators (such as `MustAsync`) and async conditions (`WhenAsync`/`UnlessAsync`) would only be available in validators that inherit from this class. 

Classes that inherit from the new `AsyncAbstractValidator` would not be automatically invoked during the ASP.NET MVC/WebApi validation process (as they don't support async rules). 

This is again a big breaking change. 

# Supporting older .net versions

The main FluentValidation library currently supports netstandard2, meaning it runs on net461 and newer. I'd particularly like to drop support for .NET 4.x, as it's becoming a pain to support, but I'm not sure what percentage of the FluentValidation userbase is still running on .net 4.x. 

I'd also like to make some of the newer c# features (particularly default interface methods, which would make building the fluent interface easier) but these are locked to .net core 3.1 and newer.  .net core 2.1 doesn't reach EOL until late next 2021. 

The first 2 of these are a huge amount of work to implement, so I'm hesitating whether or not they're worth it, and would appreciate others' feedback.

**Comment by oskardudycz** [comment]
@JeremySkinner I feel your pain. In Marten we also try to avoid breaking changes as much as we do. However, they're unavoidable. We made in the past a mistake and let too many classes and class members be public. Most of them should be just internal. As we're quite pedantic about the semantic versioning then we also tried to avoid changing them "just in case". We're currently working in the next major version (v4) and we plan to clean some of that mess in a similar way as you described in the `Generics in the Internal Model` - or even more drastic.
Of course, there needs to be a compromise between putting too many bigger changes in one version to not discourage people for upgrading, but I think that your set of changes should be fine, as long the SemVer rules are kept and there is a (short) guidance of how to migrate.

Regarding `Asynchronous changes` - is it possible to make the previous version obsolete? I think that it'd be good for the users to know earlier than just when it's not invoked. If it's not possible then maybe you could add a method that would validate if there are validators that'll be ignored? If users have a lot of such validators then just ignoring might be hard to spot on.

I think that as OSS Maintainers doing our work on spare time, we should not be more stint than a Pope. If MS does not have LTS on the concrete version of .NET then we shouldn't be maintaining them. If our users have such systems still up and running and don't have plans for migration then we could offer the paid support. 

p.s. I used FluentValidation in many of my projects - I'm really surprised that you're able to maintain it on your own. Keep up the good work 👍

**Comment by JeremySkinner** [comment]
@oskardudycz Thanks I really appreciate the input. 

> Regarding Asynchronous changes - is it possible to make the previous version obsolete?

Yes, I was thinking that the next version would still allow async property validators validators to be used inside  the non-async `AbstractValidator`, but would be marked as obsolete. In the subsequent version that would then be removed entirely, giving a grace period where people can migrate. 

> if MS does not have LTS on the concrete version of .NET then we shouldn't be maintaining them

I agree, which is why I dropped support for non-LTS .net core versions with FV 9. Unfortunately .net 4.x is still supported as long as windows is 😭

> p.s. I used FluentValidation in many of my projects - I'm really surprised that you're able to maintain it on your own. Keep up the good work 👍

Thank you! 🙏

**Comment by oskardudycz** [comment]
@JeremySkinner 
 
> Yes, I was thinking that the next version would still allow async property validators validators to be used inside the non-async `AbstractValidator`, but would be marked as obsolete. In the subsequent version that would then be removed entirely, giving a grace period where people can migrate.

That looks like the right way 👍 

> I agree, which is why I dropped support for non-LTS .net core versions with FV 9. Unfortunately .net 4.x is still supported as long as windows is 😭

Maybe you could gather from NuGet statistic of how many users are using .NET versions that you don't want to support? I think that if you restrict support to .NET Standard 2.1 it should be fine. 
If it appears that there are a lot of them then you could release the last version supporting those versions and inform that from the next version there won't be official support for them but only per-case paid support (so similar as MS does with .NET and Oracle with Java).
Thoughts?

**Comment by JeremySkinner** [comment]
I don't think that nuget provides those stats unfortunately, there doesn't seem to be a breakdown by .net version (as far as I can see). If I knew that it'd definitely make the decision easier! But yes I think that's the way to do it, at least for net4x. For .net core 2.1 I think it seems sensible to just drop it as soon as it becomes EOL next august

**Comment by oskardudycz** [comment]
Yup, for your case that it sounds reasonable to wait with droping the support for .NET Core 2.1. However you may also try to publish the desired roadmap - with few months of notice about dropping support (eg. till the end of the year). During that time you may try to get the feedback from users. In the worst case you'll just prolong it till August.

**Comment by anaximander23** [comment]
On the subject of breaking changes, I notice that a number of interfaces are marked as obsolete with the message "FluentValidation metadata interfaces are deprecated and will be removed in FluentValidation 10." Is there a suggested replacement for these? We have some code that checks for these interfaces to determine which builder class to use to write descriptions of the validation rules into metadata; would it be safe to simply drop the `I` and look for the concrete class?

**Comment by JeremySkinner** [comment]
@anaximander23 I'm actually going to undo that change - the Obsolete attribute has been removed from them for 9.3, so you should be safe to keep them. If we're moving to generics for all property validators then the non-generic metadata interfaces continue to serve a purpose for when type information isn't available.

**Comment by JeremySkinner** [comment]
FluentValidation 10.0-preview1 is now available. This release has mainly focused on implementing generics in the internal model, which has turned out to be a massive undertaking. The other issues referenced here related to asynchronous updates will be pushed out to a future release.  I'm also keeping netstandard2.0 support for the core library for 10.0, but explicit support for .net 4.6 has been dropped, as has .NET Core 2.1 support from the ASP.NET Integration package.
