### ISSUE TITLE
Release note: duplication of "Changes in 9.2.1"

### ISSUE THREAD

**Issue by SiCoe** [FluentValidation/FluentValidation#1530]
Hello,

Sorry this feels pedantic, but it did confuse me when first looking at it:

In the [9.2.2 Release note](https://github.com/FluentValidation/FluentValidation/releases/tag/9.2.2) the latest "Changes" header is marked as 9.2.1 and I suspect it's supposed to be 9.2.2 as the one under it is also 9.2.1.

**Comment by JeremySkinner** [comment]
Fixed, thanks!
