### ISSUE TITLE
Error message localization

### ISSUE THREAD

**Issue by dbalciunas** [FluentValidation/FluentValidation#1531]
When an validation exception is thrown the message error is prefixed with the string: "Validation failed: ". I read the documentation and I didn't find any way to localize this. I searched the source code and I found the place where the messages are build:
	
	private static string BuildErrorMessage(IEnumerable<ValidationFailure> errors) {
			var arr = errors.Select(x => $"{Environment.NewLine} -- {x.PropertyName}: {x.ErrorMessage}");
			return "Validation failed: " + string.Join(string.Empty, arr);
		}

As we can see this string is hardcoded, so the question is how could this be localized.

**Comment by JeremySkinner** [comment]
Hello, this exception message is not intended to be localizable like the validation messages, as exception messages aren’t intended to be presented to end users. If you want the exception to have a different message you’ll need to throw the exception using the constructor that takes a custom message.

**Comment by dbalciunas** [comment]
Hello, I use the validator this way:

        Dim validator = New Validator()
        validator.ValidateAndThrow(Me)

Then I catch the exception and build a message box right from the exception message (desktop application):

       MessageBox.Show($"{ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error)

What should be the correct use? I shouldn't use ValidateAndThrow? Thanks.

**Comment by JeremySkinner** [comment]
You can customize how the exception object is created by overriding the `RaiseValidationException` method in your validator (provided you're running version 9.1 or newer): https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation/AbstractValidator.cs#L374-L376

You can supply a different message in there
