### ISSUE TITLE
Cannot use validate method using a specific ruleset

### ISSUE THREAD

**Issue by belizar** [FluentValidation/FluentValidation#1534]
**Which version of FluentValidation are you using?**
<PackageReference Include="FluentValidation.AspNetCore" Version="9.2.0" />

**Which version of ASP.NET are you using?**
 <TargetFramework>netcoreapp3.1</TargetFramework>

**Describe the issue that you're having**
What I want to do? Validate using a ruleset

What is happen?
When I try to validate an object using a specific ruleset, I realized that validate method does not support to set a specific ruleset. There only exists a one argument method that receive an T instance, and another one that just recieve a ValidationContext<T> object.

![image](https://user-images.githubusercontent.com/37871475/94374792-f6e9e800-00e4-11eb-8417-5555d32bf533.png)

**Comment by JeremySkinner** [comment]
Hi. It’s an extension method, so you need to import it with a `using FluentValidation` namespace import.

**Comment by belizar** [comment]
Very Thank You!
