### ISSUE TITLE
Custom LanguageManager not working

### ISSUE THREAD

**Issue by dbalciunas** [FluentValidation/FluentValidation#1535]
Hi, I implemented a custom LanguageManager to replace some default messages but I can't manage to make it work.

Here is my implementation:

    public class CustomLanguageManager : FluentValidation.Resources.LanguageManager
    {
        public CustomLanguageManager()
        {
            AddTranslation("en", "NotNullValidator", "The field must not be empty.");
            AddTranslation("es", "NotNullValidator", "El campo no debería estar vacío.");
        }
    }

Then I set it in the OnLoad of my main window (I tried in the main function too). 
 
        ValidatorOptions.Global.LanguageManager = New CustomLanguageManager()

I checked that current culture is "en" or "es" when running, but always appear the default message. Maybe it depends on what place the set is made? 

Thanks.

**Comment by JeremySkinner** [comment]
Hi, that should work fine. Which version of FluentValidation are you using?

**Comment by dbalciunas** [comment]
Version 9.2.0

**Comment by JeremySkinner** [comment]
This should work fine in 9.2. Can you put together a small sample project that reproduces the issue? Thanks

**Comment by dbalciunas** [comment]
Ok, I created a simple project and it worked, then I realized that I was translating the NotNull message, but in my validator I was using "NotEmpty" method... Well, your suggestion was useful to solve my problem anyway, thanks a lot and sorry...
