### ISSUE TITLE
FluentValidation, Version=9.0.0.0, Culture=neutral [Failed to resolve assembly]

### ISSUE THREAD

**Issue by rspl-nilesh** [FluentValidation/FluentValidation#1536]
**Which version of FluentValidation are you using?**
I am using latest version 9.0.2

**Which version of ASP.NET are you using?**
If you are using FluentValidation with ASP.NET, please provide the version of ASP.NET that you're using (eg .NET Core 2.1, NET Core 3.1 etc)
-> Using .Net standard 2.1, .NetCore.Platforms 3.1.3

**Describe the issue that you're having**
-> I am using this with my Xamarin.Classic project. I have added a package in PCL but not in any of the platform's projects. I try to run a project but It says Failed to resolve assembly. 
-> I have set linker flag to "Don't Link" as I am running the project in the simulator.

**Comment by JeremySkinner** [comment]
Hello, 

Please try upgrading to the latest version 9.2.2. 

If you still have issues after upgrading then this is likely not to be an issue with FluentValidation itself, and you’ll need to contact someone on the Xamarin team for support.
