### ISSUE TITLE
DefaultValidationFactory instead of AddValidatorsFromAssemblyContaining?

### ISSUE THREAD

**Issue by weitzhandler** [FluentValidation/FluentValidation#1537]
**Is your feature request related to a problem? Please describe.**
I was wondering if instead or as a complement to `AddValidatorsFromAssemblyContaining` you'd consider adding an extension method `AddFluentValidation` to `IServiceCollection`, that in turn creates and registers an `IValidatorFactory` that returns the matching `IValidator<T>` in current/provided assembly.

This would be beneficial for projects that do not use the ASP.NET Core validation or for other target types.

Additionally, for projects that involve dynamic handling with validators, it would be easier creating the validators via a factory than extracting it manually from `IServiceProvider`.

**Describe the solution you'd like**

- Have a `DefaultAuthenticationFactory` that is simply acts as a wrapper around `IServiceProvider`, which is supplied to its concrete implementation constructor.
- An extension method on `IServiceCollection` `AddFluentValidation` that 
  - Calls `AddValidatorsFromAssemblyContaining`
  - registers an `IValidationFactory` to `DefaultValidatorFactory`

I can PR.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion 🤗 

We actually already have extension methods on IServiceCollection to do this. There are `AddValidatorsFrom...` methods available if you install the `FluentValidation.DependencyInjectionExtensions` package. (Internally, the `AddFluentValidation` methods in the ASP.NET Core package make use of the methods in FluentValidation.DependencyInjectionExtensions).   

https://www.nuget.org/packages/FluentValidation.DependencyInjectionExtensions/

https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs

**Comment by weitzhandler** [comment]
Lol, you caught me while editing my post.

**Comment by JeremySkinner** [comment]
> Alternatively, a DefaultAuthenticationFactory that is simply acts as a wrapper around IServiceProvider, which is supplied to its concrete implementation constructor.

This is in the `ServiceProviderValidatorFactory`. Currently this is in the FluentValidation.AspNetCore package, but will be moved to  the DependencyInjectionExtensions package in the next major release.

**Comment by weitzhandler** [comment]
Oh that's great then. Yup, it belongs in the DI package.

**Comment by JeremySkinner** [comment]
It's actually a holdover/legacy from before ASP.NET made use of IServiceProvider. Typically you won't use the IValidatorFactory, and instead make use of IServiceProvider directly. The wrapper around IServiceProvider is for backwards compat, and we'll probably deprecate the IValidatorFactory at some point in the future.

**Comment by weitzhandler** [comment]
I actually do see benefit in `IValidatorFactory`, even as a mere wrapper around the registered sevices (instead of the other way around), because normally it's better to expose a service that satisfies their exact needs (`IValidatorFactory`), rather then giving the consumer the entire service tree.

**Comment by weitzhandler** [comment]
> I think we can benefit from maybe having extension methods on IServiceProvider

That still remains an issue.

The consumer constructor will still depend on `IServiceProvider`, which is meaningless. Consider testing such a consumer, it's pretty ugly having a dependency on `IServiceProvider` when you need a specific service and you know what it is - a dynamic `IValidator<T>`...

**Comment by weitzhandler** [comment]
Anyway it's not a deal breaker, so I'm gonna close this issue now given the above information. Thank you Jeremy for everything!
