### ISSUE TITLE
Translate Property name in error message

### ISSUE THREAD

**Issue by Mastard69** [FluentValidation/FluentValidation#1539]
Hi,

I use FluentValidation (8.6.0) in my project (Asp.net core 3.1) in order to validate almost every requests coming into my WebApi. It works fine, but I've been asked to translate property names in the error messages. My projet must handle at least french and english, so for example, what I want to achieve is :

'First Name' is required (english case)
'Prénom' est requis (french case)

I already have a IPropertyLabelService for other purposes, that is injected in the Startup.cs, that I want to use. It finds translations of property names in a .json, which already works fine.

My problem is that I don't know how to use it globally. I know that FluentValidation's doc says to set the ValidatorOptions.DisplayNameResolver in the Startup file, like this :

FluentValidation.ValidatorOptions.DisplayNameResolver = (type, memberInfo, expression) => {
    // Do something
};

I don't know how I can use my IPropertyLabelService inside this, as the Startup.ConfigureServices method is not over yet, so I can't resolve my service...

Any other solution to achieve this behaviour is also more than welcome. I considered using .WithMessage() or .WithName() but I have a really big amount of validators, that would be really long to add this to all individually.

Thanks

**Comment by Mastard69** [comment]
This is absolutely sensational. Works like a charm !

Thanks you for your fast, detailed and explained answer, just awesome !

**Comment by JeremySkinner** [comment]
I did a quick bit of research and I should be able to make `ValidatorOptions.Global` compatible with `IConfigureOptions` natively for .net 5. It won't be possible to get this working on earlier versions as in .net core 3.1 and older the options class is always instantiated directly using the class's default constructor, but in 5.0 it's possible to cutomize how the options class is created (which in FV's case will pull from `ValidatorOptions.Global`). Will track development for this in #1540 if you're interested.
