### ISSUE TITLE
.Net Framework 4.0 support

### ISSUE THREAD

**Issue by pieroviano** [FluentValidation/FluentValidation#1547]
I was able to re-introduce .Net 4.0 support in FluentValidation
Modifications are really few..
You can see them from here:
https://www.dropbox.com/s/exaw3qcabfnrs2j/FluentValidation.zip?dl=0

**Comment by JeremySkinner** [comment]
Hello, thanks for the suggestion but we won’t be reintroducing support for net4.0. It isn’t practical for us to support multiple obsolete framework versions. We will actually be dropping support for all net4x versions most likely with the next major release, of the one after.
