### ISSUE TITLE
Validate elements in collection against each other, but set errors for individual elements, rather than collection as a whole?

### ISSUE THREAD

**Issue by alexaka1** [FluentValidation/FluentValidation#1549]
Is there a way to validate a collection's elements, but not individually, instead as a whole, but still reflect on which element is invalid, instead of just the entire collection being invalid (that's not useful info, the user needs to know which specific element is invalid).

So say I have a form row (in ASP.NET Core) like this:
```RAZOR
@Model Foo

<div class="row">
        <div class="col d-flex flex-column">
            <label asp-for="SomeName"></label>
            <input asp-for="SomeName"/>
            <span asp-validation-for="SomeName" class="text-danger"></span>
        </div>
        <div class="col d-flex flex-column">
            <label asp-for="SomeOtherField"></label>
            <input asp-for="SomeOtherField" class="form-control" />
            <span asp-validation-for="SomeOtherField" class="text-danger"></span>
       </div>
</div>

<!-- somewhere  outside of scope -->
<span asp-validation-for="MyCollection" class="text-danger"></span>
```
And the user can click on a button to add more rows of this, and it all gets collected into a collection in my viewModel, for example:
```C#
class Foo
{
     List<Bar> MyCollection;
}

class Bar
{
   string SomeName;
   string SomeOtherField;
}
```
I know I can validate the collection as a whole and this appears as an error for the MyCollection error span:
```C#
RuleFor(p => p.MyCollection).Must(x => x.Any()).WithMessage("Must have at least 1 element!");
```
I know I can validate each element individually in the collection, and these errors will appear for the corresponding row (through some black magic, I dunno how it works, it just does):
```C#
RuleFor(x => x.MyCollection).ForEach(x => x.SetValidator(new BarValidator()));
```

However what I don't know how to achieve is to validate the collection's elements against each other, and put the errors to the invalid element.
If I do this, then this can only create a single error message, and it's for MyCollection, not the actual element that's invalid:
```
RuleFor(x => x.MyCollection).Must(x => 
{  
/* pseudo code*/  foreach element if SomeName is longer than 
previous element's SomeName, then current element is invalid, 
and SomeName should have an error msg reflecting this  
});
```

Currently my workaround is, I generate a unique Guid for each row in the form, and I check manually outside of FluentValidation whether the elements are valid, and if not I throw an error message that has the unique Guid in it, so it appears under the correct row's correct field. But this means my validation logic is in two separate places, and I'd like to use FluentValidation instead (it's a really good library, I'm loving it :)).

Is this possible?

**Comment by JeremySkinner** [comment]
Hi, so there's nothing built in to do this. The standard collection validation mechanisms are either you validate the whole collection as a single entity (generating a single error message for the whole collection), or you validate the individual elements and generate a message for those that are invalid (with the correct index).

To do what you want you'll need to write some custom logic by using the `Custom` method: see https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator 

Essentially you'll need to loop over the collection, keeping track of the current index, which you can then use when generating the key in the error message.

**Comment by alexaka1** [comment]
Yes I believe back in the day, I looked into doing custom validations. I don't remember `context.AddFailure()` though, so that's probably what I'm looking for, I can see in the doc, I can add keys to error messages. My custom logic is already set up to creater errors based on the guid keys.

However I now realised my other problem. So if I do this:
```C#
RuleFor(x => x.MyCollection).Custom((list, context) => {
     foreach(var current in list){
           if(someCheck) {
           context.AddFailure($"{nameof(Bar.SomeName)}_[{current.Guid}]","Some error msg.");
           }
     }
   });
```
I only have the reference to MyCollection, I have no reference to Foo, that contains MyCollection. And if I want to validate against that, I cannot. (Say if I have a DateTime in Foo, and all the DateTimes in Bar have to be on the same day.
I'm not sure if `context.ParentContext.InstanceToValidate` gives back the Foo object that contains MyCollection.

**Comment by JeremySkinner** [comment]
> I'm not sure if context.ParentContext.InstanceToValidate gives back the Foo object that contains MyCollection.

Yes, it does, however you're probably better off defining your rule against the root object in that case with `RuleFor(x => x).Custom((model, context) => { ... });` that way you receive a direct reference to the parent model, and from that you can access the collection property too.

**Comment by alexaka1** [comment]
That's great. 

> however you're probably better off defining your rule against the root object

I didn't even think about that. This problem really has been a sword of Damocles over my head lately, so I could only think of more and more convoluted ways to solve this. And this means I won't have to do some possibly unsafe magic casting either. Nice 👍. Thank you!
