### ISSUE TITLE
error CS0103: The name `SN' does not exist in the current context

### ISSUE THREAD

**Issue by Deathsam8** [FluentValidation/FluentValidation#1554]
so i have the issue where is it saying:
error CS0103: The name `SN' does not exist in the current context
error CS0103: The name `ST' does not exist in the current context
error CS0103: The name `Y25Y' does not exist in the current context
error CS0103: The name `Y25N' does not exist in the current context
does anyone know how i can fix this?
![image](https://user-images.githubusercontent.com/73191335/96623055-adb33f80-1302-11eb-9e22-7c0de6d54578.png)
![image](https://user-images.githubusercontent.com/73191335/96623113-c58ac380-1302-11eb-8dfb-5d52bf4379ba.png)
![image](https://user-images.githubusercontent.com/73191335/96623131-cf142b80-1302-11eb-8d4c-c33c4f9b1c88.png)

**Comment by Deathsam8** [comment]
Note that the ^C is not part of the code, it must have of been typed in by accident when taking the screen shot.

**Comment by JeremySkinner** [comment]
This is nothing to do with FluentValidation.
