### ISSUE TITLE
Include When condition in Message

### ISSUE THREAD

**Issue by AndreaCuneo** [FluentValidation/FluentValidation#1555]
I'm always frustrated that when I use Conditions on Rules I've to overwrite the Message to have meaningful errors, even if is just a common NotNull() for which this library already support localized messages.

I'd like that, in case on When() usage, the error message would include the condition the current ValidationFailure message. 

`RuleFor(x => x.P1).NotEmpty().When(x => x.P2 == null);`

Current behaviour: "'P1' must not be empty."
Expected behaviour: "When 'P2' is null, 'P1' must not be empty"

I understand the challenges of composing the string for the Condition. 
The easiest way would be ask it to the library user:
`RuleFor(x => x.P1).NotEmpty().When(x => x.P2 == null, "P2 is null");`

A nice way, would be to somehow reuse the Validator pattern, with a Condition builder.
`RuleFor(x => x.P1).NotEmpty().When(x => ConditionFor(y => y.P2).IsNull());

Currently I've no way to 'compose' the existing Failures from the library to explain the Conditional validation, that are quite common to model constraints.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. This isn't something that would be currently in the roadmap for the library - the `When\Unless` methods intentionally only provide a condition and don't modify any other aspect of the validator (including the message) - it is up to the developer to provide a message if the default is not adequate.

That being said, it's a nice idea. Would you be willing to take ownership of designing and developing this? If so then please feel free to start by putting together a design proposal for how this could be implemented which I'd be happy to review. Once we've approved a design then you can provide a pull request that implements the accepted solution. 

Thanks for wanting to get involved!
