### ISSUE TITLE
Stop vs StopOnFirstFailure

### ISSUE THREAD

**Issue by kyzo** [FluentValidation/FluentValidation#1558]
Version: 9.2.0
.NET Core 2.1.1

Hi,
we recently updated from 8.x to 9.2.0 and we are using extensively CascadeMode.StopOnFirstFailure.
We have forms with 30+ fields and each field has sometimes 3-4 rules which depend on the previous rule to be success.
We show user errors for all fields so they immediately know which fields are not valid.

When switched to 9.2.0 and CascadeMode.Stop the behaviour is not the same.
How to achieve the same behaviour without writing for each RuleFor CascadeMode.Stop?

What we want is some way to achieve CascadeMode.StopOnFirstFailure in 9.2.0 without need to alter each and every RuleFor.
Thanks

**Comment by JeremySkinner** [comment]
You can continue to use StopOnFirstFailure, it isn’t being removed, but it will generate warnings as it’s behaviour is unclear, which you can choose to suppress if you want to.

**Comment by JeremySkinner** [comment]
Also just to be clear, the difference between Stop and StopOnFirstFailure is only when set at the *validator class level*. When set at the *rule* level they are identical.

**Comment by kyzo** [comment]
But this option will be removed in version 10 as stated in docs no? Would like to use things properly :)

**Comment by JeremySkinner** [comment]
> But this option will be removed in version 10

No that's not right. Could you tell me where it says that, and I'll correct it.

**Comment by kyzo** [comment]
Hmm I must have read to it more meaning that there is actually written.
No word about removing, in code it is marked as deprecated so i naturally thought it will be removed in next major version.

![image](https://user-images.githubusercontent.com/12268979/97416232-78ac7b80-1906-11eb-937b-68815c7ee075.png)

**Comment by JeremySkinner** [comment]
Yep, the docs are correct. 

Anything due for removal will say "This will be removed in FluentValidation 10" in the compiler warning. 

In this particular instance it won't be removed as there may be users who rely on its behaviour. However it is confusing and misleading (because it doesn't actually stop on the first failure, despite its name), which is why its been marked as obsolete and will generate warnings going forward.

**Comment by kyzo** [comment]
Ok thanks for the information and help.
If you would want to replicate this behaviour with safer features would you include CascadeMode.Stop on each RuleFor?
What would be your approach.

**Comment by JeremySkinner** [comment]
If you're currently setting the cascade at the rule level, with `RuleFor(x => x.Foo).Cascade(CascadeMode.StopOnFirstFailure).NotNull().Whatever()` then you can just swap this to `CascadeMode.Stop`. Everything will behave in exactly the same way. 

If you're setting the cascade at class level (with `this.CascadeMode = CascadeMode.StopOnFirstFailure` in the constructor), then you'll need to think about what what your intention is. 
- If you only want the validator to only ever generate 1 error message from the first rule that fails, then you can switch to `CascadeMode.Stop`
- If you want the validator generate a maximum of 1 error message *per rule*, then either stick with `CascadeMode.StopOnFirstFailure` at the class level OR: remove it from the class level, and set `CascadeMode.Stop` at the rule-level instead.

I know it's a bit confusing, so let me know if you want me to clarify any of it

**Comment by kyzo** [comment]
No no I understand it perfectly, just wanted to use not deprecated feature correctly and my idea was to put CascadeMode.Stop on each RuleFor, because that is what we need, but it is more verbose than use only once per validator CascadeMode.StopOnFirstFailure.

Thank you very much for your quick support much appreciated

**Comment by JeremySkinner** [comment]
Personally I'd explicitly set it at the rule-level, as I think it's clearer and more obvious what's happening, but yes that is more verbose which is why I left the other option available still.
