### ISSUE TITLE
Document changes coming in 10.0

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1565]
Changes that need to be documented in both the docs, changelog and upgrade guide:

- [x] CollectionPropertyRule now iterates the collection only once
- [x] Remove deprecated IStringSource, LazyStringSource, LanguageStringSource, StaticStringSource. Replaced with delegates.
- [x] ChildValidatorAdaptor.GetValidator is non-generic again
- [x] PropertyValidatorContext removed.
- [x] Remove deprecated FormattedMessageArguments from ValidatioNFailure.
- [x] Remove deprecated MessageFormatter.AppendAdditionalArguments
- [x] PropertyRule.InvokePropertyValidator/Async is now private. 
- [x] Remove deprecated MemberNameValidatorSelector.FromExpressions method
- [x] Remove deprecated `Language` base class
- [x] Remove deprecated properties from ValidatorOptions
- [x] Remove ICommonContext. 
- [x] Removed or made internal various utility methods
- [x] IValidatorInterceptor method signature changes
- [x] DI extensions and MVC integration now register validators as Scoped rather than Transient. 
- [x] CascadeMode is now a protected property (should only be set inside validator's ctor) 
- [x] Transform syntax changes
- [x] Supported framework versions
- [x] PropertyValidator changes (old class deprecated, new interface is generic. Need examples of migrating). 
- [x] ValidatorOptions.ErrorCodeResolver changes
- [x] Various places that previously returned a IPropertyValidator now return a tuple of (ICustomValidator, IPropertyValidatorOptions) including the Descriptor
- [ ] OnFailure changes (either it gets removed or the FI gets updated not to expose it in some situations)
- [x] RuleSets property can be null. 
- [x] RemoveValidator/ReplaceValidator have been removed from rule. 
- [x] Signature changes for client validator adaptors

**Comment by mrNo0b** [comment]
I am now learning how to use FluentValidation and I have a question but there is nowhere to ask so I will ask here (maybe the discussions option should be turned on for this repository)
Is it possible to use `[ValidationAttributes]` instead of `RuleFor`?
for example Email property in Customer class will have:
```
[Required]
[EmailAddress]
public string Email { get; set; }
```
and adding `[UseFluentValidation]` (or something like that) to the object that will create validator instance.
something like Model validation in ASP.NET...
Thank you!
