### ISSUE TITLE
ServiceProviderValidatorFactory belongs in FluentValidation.DependencyInjectionExtensions

### ISSUE THREAD

**Issue by buvinghausen** [FluentValidation/FluentValidation#1566]
Notes:
ServiceProviderValidatorFactory has no ties to AspNetCore plumbing at all
FluentValidation.AspNetCore depends on FluentValidation.DependencyInjectionExtensions so there is no loss of function.

Rationale:
For those of us who don't use the AspNetCore package due to Microsoft's continued insistence on not supporting async validation in the standard pipeline it would be nice to have the IValidationFactory wired up automatically as well so that 3rd party libraries like [MicroElements.Swashbuckle.FluentValidation](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/issues/63) still work out of the box provided you've registered FV with the DI framework.

@JeremySkinner I'm happy to submit a PR if you agree with this sentiment.

**Comment by JeremySkinner** [comment]
Hi, yes this is a good idea and I’d be happy with this change if you want to submit a PR. 

As this is a breaking change this will need to go into the next major release (10.0), so please can you make your PR to target the 10.x branch? 

Thanks!

**Comment by JeremySkinner** [comment]
Moved the factory across. The other changes from the PR won't be included.
