### ISSUE TITLE
Nullable data-val-required not using WithMessage()

### ISSUE THREAD

**Issue by pauldbentley** [FluentValidation/FluentValidation#1569]
**Which version of FluentValidation are you using?**
9.2.0

**Which version of ASP.NET are you using?**
netcoreapp3.1

**Describe the issue that you're having**
With a `NotNull` rule:

```
string Value { get; set; }

RuleFor(m => m.Value)
    .NotNull().WithMessage("Please enter this value");
```

With `Nullable` enabled on the project my message is not used in the client side output:

`data-val-required="The Value field is required."`

So I think because Value is not nullable, MVC is creating this message?  Is there a way to make it use the message from FV?  I don't want to make the Value nullable, because it can't be.

**Comment by JeremySkinner** [comment]
Hi, yes, you’re right this is coming from MVC itself rather than FluentValidation. 

I am not aware of any way of bypassing or customising this, although you might be able to turn it off by removing the default ClientValidatorProvider from the services collection.

**Comment by pauldbentley** [comment]
Ah yes, its coming from [this line](https://github.com/dotnet/aspnetcore/blob/cc96e988f491375fa8e29fc42d558303d5b131f3/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsClientModelValidatorProvider.cs#L99) which adds a default '[Required]' validator if there isn't one but the property isn't nullable.  There is no way to disable this, but removing it from the services collection works.

Thanks

**Comment by pauldbentley** [comment]
Just thinking about this - is removing this service something you would consider for the package?

**Comment by JeremySkinner** [comment]
Yes, definitely something we can look at. We work around several other things like this already, although we need to make sure it still works as a fallback if there isn’t a validator class defined.

**Comment by JeremySkinner** [comment]
Is this something you'd be interested in contributing? If so, then we'll need integration tests to cover the following scenarios:
- There is a validator defined for the type, and a NotNull rule defined for the property. Should use clientside message from FV
- There is a validator defined for the type, but no rule for the property. Should use default mvc message
- There is no validator defined for the type. Should use default mvc message

**Comment by pauldbentley** [comment]
I will take a look.  I can easily replicate in a brand new web project, but not in the test project - so maybe there are some differences between the services/settings used by the test web host.
