### ISSUE TITLE
RunDefaultMvcValidationAfterFluentValidationExecutes=false ignored 

### ISSUE THREAD

**Issue by JosephG3001** [FluentValidation/FluentValidation#1573]
I've also posted this on [stackoverflow](https://stackoverflow.com/questions/64707062/why-is-my-controller-hit-when-the-fluentvalidation-for-the-model-is-not-valid-in).

I believe I'm doing everything according to the documentation. I've setup fluent validation in the Startup.cs class:

     `public void ConfigureServices(IServiceCollection services)
      {
            services.AddSwaggerGen(swagger =>
            {
                swagger.SwaggerDoc("v1", new OpenApiInfo { Title = _swaggerApiName });
                swagger.DescribeAllParametersInCamelCase();
            });

            services.AddMvcCore()
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.IgnoreNullValues = false;
                })
                .AddFluentValidation(options =>
                {                    
                    options.RunDefaultMvcValidationAfterFluentValidationExecutes = false;
                    options.RegisterValidatorsFromAssemblyContaining(typeof(ContentCoreMarker));
                    options.ImplicitlyValidateChildProperties = true;
                })
               .AddApiExplorer()
               .AddRazorViewEngine();
       }
       ` 

My simple validator. Note that a breakpoint is hit on RuleFor.

       `    
       public class AddSectionRequestValidator : AbstractValidator<AddSectionRequest>
       {
            public AddSectionRequestValidator()
            {
                RuleFor(m => m.SectionName)
                    .NotEmpty()
                    .MinimumLength(1)
                    .WithMessage("invalid");

                RuleFor(m => m.ParentSectionId)
                     .NotEmpty();
        }
    }
    `

Shouldn't fluentvalidation automatically return the validation errors without hitting the controller action?

According to the documentation:

>     If you want to disable this behaviour so that FluentValidation is the only validation library that executes, you can set the RunDefaultMvcValidationAfterFluentValidationExecutes to false in your application startup routine

Breakpoint in Controller is still hit. I've also created a local copy of the validator to test and the result is the model is invalid.

     `       
        [HttpPost]
        public async Task<IActionResult> Post([FromBody]AddSectionRequest request)
        {
            var validator = new AddSectionRequestValidator();
            var isValid = validator.Validate(request); // Not valid

            var result = await _addSectionRequestHandler.Handle(request);
            return Ok(result.NewSectionId);
        }
        `

I'm on ASP.Net Core 3.1

**Comment by JeremySkinner** [comment]
Hi

> Shouldn't fluentvalidation automatically return the validation errors without hitting the controller action

It depends. FluentValidation runs during model binding. For standard MVC controllers the validation results are then added to the ModelState dictionary and you can check `ModelState.IsValid` inside your controller. For WebApi controllers, the validation results will be returned immediately (unless you’ve turned this off, this is a feature of ApiControllers)

The `RunDefaultMvcValidationAfterFluentValidationExecutes` setting is nothing to with this. This enables or disables asp.net’s default validation (the data annotations attributes). By default we allow DataAnnotations to run after FluentValidation finishes, but you can turn it off by setting this to false (as you’ve done).But I don’t think this is actually what you want as it doesn’t appear related to what you’re asking? You should typically not change this setting. To reiterate, This setting controls *whether or not asp.net’s default validation should be run after FluentValidatikn* it is nothing to do with *when FluentValidation is run*. I would suggest you remove this line altogether. 

Back to the issue at hand, if your validator is not running automatically then this probably means that you’ve not set something up quite right. First thing to check is this:

```
RegisterValidatorsFromAssemblyContaining(typeof(ContentCoreMarker));
```

Is your validator class definitely in the same assembly as ContentCoreMarker?

**Comment by JosephG3001** [comment]
Apologies for the delayed response - I've had a lot of work on and had to down tools for awhile.  Finally got round to picking this back up and your suggestion set me on the right path.  I knew it had to be something simple - I was missing the [ApiController] attribute which changed the behaviour of the library.  Now I see the following response in Postman and my controller is not hit:

`{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|f5f5b1a2-4dd202e6998784c3.",
    "errors": {
        "Name": [
            "'Name' is required."
        ],
        "Content": [
            "'Content' is required."
        ]
    }
}`

Issue is resolved.
