### ISSUE TITLE
Null Reference Exception on child properties

### ISSUE THREAD

**Issue by AuthorProxy** [FluentValidation/FluentValidation#1578]
```
            RuleFor(dto => dto.Documents)
                .NotEmpty()
                .WithMessage("...")
                .Custom((dto, ctx) => dto.First()..........) // null reference exception

```

Shouldn't it fail on the first error? CascadeMode = OnFirstFailure
Should I always duplicate my previous checks on When block?
Can you improve docs for this cases?

**Comment by JeremySkinner** [comment]
Hi, I don't completely understand what you're asking, could you elaborate?

> Shouldn't it fail on the first error?

If CascadeMode is set to `Stop` and the `NotEmpty` fails, then the `Cutom` won't be run. 

> Should I always duplication my previous checks on When block?

I don't understand what you mean I'm afraid. By default a `When` condition applies to app preceding validators in the chain. However you can't apply `When` to `Custom` (you should perform the check inside the custom block in that case)  


Essentially, you want to do either one of these:

```
// Either
RuleFor(dto => dto.Documents)
  .Cascade(CascadeMode.Stop)
  .NotEmpty()
  .WithMessage("...")
  .Custom((dto, ctx) => dto.First()..........);

// Or:

RuleFor(dto => dto.Documents)
  .Cascade(CascadeMode.Stop)
  .NotEmpty()
  .WithMessage("...")
  .Custom((dto, ctx) => /* Null check in here */)

**Comment by AuthorProxy** [comment]
I have test
```
    public class EmployeeValidationTests
    {
        private readonly EmployeeUpdateDtoValidator _sutValidator;

        public EmployeeValidationTests() => _sutValidator = new EmployeeUpdateDtoValidator
        {
            CascadeMode = CascadeMode.Stop
        };

        [Fact]
        public void TestEmployee_WithoutDocuments_ShouldFailValidation()
        {
            // Fixture setup
            var dto = new EmployeeUpdateDto();

            // Exercise system
            // Verify outcome
            _sutValidator.ShouldHaveValidationErrorFor(entity => entity.Documents, dto);
        }
}
```

and rule:
```
            RuleFor(dto => dto.Documents)
                .NotEmpty()
                .WithMessage("Необходимо добавить документ")
                .AddDocumentsValidator();
```
and it fails inside `AddDocumentsValidator` with nullrefex
but it doesn't when I modify rule like this:
```
            RuleFor(dto => dto.Documents)
                .Cascade(CascadeMode.Stop)
                .NotEmpty()
                .WithMessage("Необходимо добавить документ")
                .AddDocumentsValidator();
```

**Comment by JeremySkinner** [comment]
You need to set the cascade mode *inside* the validator's constructor. You're using an object initializer, which sets it *after* the constructor has run (the rules will already have been created by this point)

**Comment by AuthorProxy** [comment]
Oh thank you, I will set global setting in test or move all to actors.

Also with old test:
Also, it is a different behavior for the same test with:
```
        private readonly EmployeeCreateDtoValidator _sutValidator;

        public EmployeeValidationTests() => _sutValidator = new EmployeeCreateDtoValidator
        {
            CascadeMode = CascadeMode.Stop
        };
```
and with
```
        private readonly EmployeeUpdateDtoValidator _sutValidator;

        public EmployeeValidationTests() => _sutValidator = new EmployeeUpdateDtoValidator
        {
            CascadeMode = CascadeMode.Stop
        };
```

I have validator definitions like this:
```
    public class EmployeeCreateDtoValidator : AbstractValidator<EmployeeCreateDto>
    {
        public EmployeeCreateDtoValidator()
        {
                RuleFor(dto => dto.GenderId).NotEmpty().WithMessage("Необходимо указать пол");
                RuleFor(dto => dto.Documents)
                    .NotEmpty()
                    .WithMessage("Необходимо добавить документ")
                    .AddDocumentsValidator();
        }
}

    public class EmployeeUpdateDtoValidator : AbstractValidator<EmployeeUpdateDto>
    {
        public EmployeeUpdateDtoValidator()
        {
            Include(new EmployeeCreateDtoValidator());
            RuleFor(dto => dto.EmployeeId).NotEmpty();
        }
    }
```

When I use `EmployeeUpdateDtoValidator` it fails with null ref, when I use `EmployeeCreateDtoValidator` if fails with gender, can you explain this behavior, because you just say that prop assignment does not work

**Comment by JeremySkinner** [comment]
I expect It's because of the `Include`  call inside the EmployeeUpdateDtoValidator. 

When you set `CascadeMode` on the `EmployeeUpdateDtoValidator` in your test, that won't set it on the EmployeeCreateDtoValidator (it's not passed through), so the tests will behave differently as in one of them   the `EmployeeCreateDtoValidator` has the cascade mode set (when you instantiate it directly), and in the other it doesn't (when you use `Include`). 

That's why it's always better to set the cascade mode inside the constructor - to ensure it's always set consistently nomatter how the validator is being used.

**Comment by AuthorProxy** [comment]
Ok I just set it via global settings in a startup in the main project, but now with tests in mind, I think it's better to move to the constructor

**Comment by JeremySkinner** [comment]
Yes I agree - you don't want the tests to end up behaving differently from the application

**Comment by AuthorProxy** [comment]
Ok, now while refactoring I noticed `ImplicitlyValidateChildProperties` which said in docs that you shouldn't use `SetValidator` methods, but cannot I cannot figure the way to set it neither in `ctor` nor in `tests`

**Comment by JeremySkinner** [comment]
Have you checked the documentation? It shows how to set it here: https://docs.fluentvalidation.net/en/latest/aspnet.html#implicit-vs-explicit-child-property-validation

It's something that's set during application startup. It's not something you can set during unit tests as it's part of the integration with ASP.NET's automatic validation (during model binding).

**Comment by AuthorProxy** [comment]
Yes, I've read docs, my question is how should I write tests which don't know anything about ASP.NET context, if I should delete `SetValidator` from validators

**Comment by JeremySkinner** [comment]
You can’t test implicit child validation in unit tests - only full integration tests that exercise the full web stack. (Because this is a feature of asp.net, not of FluentValidation) 

You would have to just test each validator class in isolation. 

Personally I recommend not going down this route. Using SetValidator is much better IMO.

**Comment by AuthorProxy** [comment]
Ok, that was I thinking about, but it can confuse somebody, because of little inconsistency, somebody wants to write a test for complex models, I love to set it global because when you reuse models, it is easy to forget or miss to write `SetValidator` for inner props at the model hierarchy, and global setting make it easy, also check this plz #1442

**Comment by AuthorProxy** [comment]
How do you think is it worth to implement some context/provider object to implement this logic for unit testing?
```
options.ImplicitlyValidateChildProperties = true;
options.RegisterValidatorsFromAssemblyContaining<Startup>();
```

**Comment by JeremySkinner** [comment]
I don't understand what you're asking for with a "context/provider".  As I said before, `ImplicitlyValidateChildProperties` isn't something that can be replicated in unit tests - it's a feature of ASP.NET's model binding process. ASP.NET recursively iterates over each object as it's bound in a request and locates a validator for it. This is done by *ASP.NET's model binding* - it isn't something FluentValidation can replicate in a unit test.
