### ISSUE TITLE
'ValidateAndThrow' extension has misleading behavior: unable to mock failures

### ISSUE THREAD

**Issue by julealgon** [FluentValidation/FluentValidation#1580]
**Which version of FluentValidation are you using?**
9.2.2

**Describe the issue that you're having**
Due to a recent change (https://github.com/FluentValidation/FluentValidation/commit/feac1217ee3a2d87fbf99764dbc170b7433c1ce0#diff-d0f407d3b9e61849cd7ed644d772381ec8b5649bbe4c2cb49a6d6138a6bf4d6a) the implementation of the `ValidateAndThrow` extension method now doesn't actually throw anymore: instead, it sets a flag for the _implementation to handle_. This means that, if an implementation doesn't handle the new flag, then the method is basically a lie: it tells that an exception will be thrown, but none is.

I've spent an hour+ trying to mock the call to an `IValidator<T>` while testing my class that uses `ValidateAndThrowAsync` but realized that a recent change made it 100% impossible to mock.

The old behavior was described here:
- https://github.com/FluentValidation/FluentValidation/issues/536

That doesn't apply anymore.

Is there any chance to get back to the old behavior of having the extension method itself throw, instead of delegating this responsibility to the implementation?

For now, I've resorted to handling the exception myself instead of relying on `ValidateAndThrow`. Something like:

```csharp
var validationResult = await this.validator.ValidateAsync(instance);
if (!validationResult.IsValid)
    throw new ValidationException(validationResult.Errors);
```

This is the first time I've had to resort to changing my code logic due to being unable to test the behavior with an interface, so it felt worth sharing here. Especially because this used to work fine in the past.

Additionally, it seems like this significant breaking change was added as part of a minor version bump, which I consider to be a mistake: people upgrading the library in between will see their tests breaking.

**Comment by JeremySkinner** [comment]
Hi, I discussed in my answer to the question here: https://stackoverflow.com/questions/63540185/did-9-1-3-fluentvalidation-update-ruin-validators-mocks/63559548

**Comment by julealgon** [comment]
> Hi, I discussed this in my answer to the question here: https://stackoverflow.com/questions/63540185/did-9-1-3-fluentvalidation-update-ruin-validators-mocks/63559548

Thanks for sharing that. 

The decision to move the throwing logic away from the method that tells it will throw seems like a bad design decision to me. I also strongly disagree with your suggestion of not mocking the validator: being forced to provide a real implementation (even if baked "true/false") in my tests indicate to me that the current validation interface is poor.

However, this is quite subjective and I see it was a conscious decision on your part, and I see you already addressed the "breaking change" part as it being just a mistake on your end, which is fine.

Considering that, I'll keep using a manual exception approach for now.
