### ISSUE TITLE
Validator not being triggered when parameter is not included in the request

### ISSUE THREAD

**Issue by luizffgarcia** [FluentValidation/FluentValidation#1582]
**System Details**
FluentValidation version: 9.3.0
Web Framework version: ASP.NET Core 2.2

**Issue Description**
The validator rules work fine as long as the parameter to be validated is passed, but if it is not passed at all then the validators will not even trigger.

`Startup.cs
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2).AddFluentValidation(options =>
            {
                options.RegisterValidatorsFromAssemblyContaining<Startup>();
            });`

**Example validators:**
`public class GuidValidator : AbstractValidator<Guid>
    {
        public GuidValidator()
        {
            RuleFor(x => x).NotEmpty();
        }
    }`

`public class IntValidator : AbstractValidator<int>
    {
        public IntValidator()
        {
            RuleFor(x => x).NotEmpty();
        }
    }`

**Example controller methods:**
`[HttpGet("guid")]
        public ActionResult<string> GetGuid(Guid guid)
        {
            return guid.ToString();
        }`

`[HttpGet("id")]
        public ActionResult<string> Get(int id)
        {
            return id.ToString();
        }`

For both examples if the request contains either an invalid guid, or a "0" value for the int scenario, then i get an validation error such as :

`"guid": [
            "The value 'test' is not valid." // when passing "test" as a guid
        ]`

or

`"id": [
            "'' must not be empty." // when passing 0 as the int value
        ]`

But if i just call those controller methods without passing any parameters then the methods execute without any errors. Is there a different way to use FluentValidation to prevent that from happening? Ideally it will not only check if the value passed is valid for the respective parameter, but also if the parameter was present.

**Comment by JeremySkinner** [comment]
Hi,

This isn't actually related to FluentValidation. 

Type conversion checks are performed by ASP.NET's model-binding process prior to validation being invoked, which is what you're running into here. Both `Guid` and `int` are non-nullable value types, so an empty/missing value will prevent validation from even occurring and will be handled by ASP.NET's type-conversion checks. 

You would need to make these nullable (by defining them as `Guid?` and `int?`) to bypass this check, which will then allow ASP.NET's validation layer (including FluentValidation) to excute.

Unrelated, but I will also point out that FluentValidation is intended for validating the properties of complex types - it is not intended for validating primitives directly.
