### ISSUE TITLE
Validation of Objects Enumerables

### ISSUE THREAD

**Issue by GianlucaGattiTeixeira** [FluentValidation/FluentValidation#1583]
**Which version of FluentValidation are you using?**
9.2.0

**Which version of ASP.NET are you using?**
.Net Core 3.1

**Describe the issue that you're having**
I want to know if it's possible to create a validator for a list of a Class, something like this, defining the validator for the Enumerable of  an specific class.
`public class HourListValidator : AbstractValidator<IEnumerable<Foo>>
    {
        public HourListValidator()
        {
            RuleForEach(x => x).SetValidator(new FooValidator());
        }
    }
}`

Thanks and regards.

**Comment by JeremySkinner** [comment]
Yes, that will work fine, although if you want it to work with asp.net’s automatic validation it’ll need to be for a concrete type like List rather than IEnumerable.
