### ISSUE TITLE
Localization with When()

### ISSUE THREAD

**Issue by cytex124** [FluentValidation/FluentValidation#1587]
**Which version of FluentValidation are you using?**
9.3.0

**Which version of ASP.NET are you using?**
Asp.Net Core 3.1

**Describe the issue that you're having**
today I tried to implement the translation. Therefore I tried this example:
`
            When(x => x.Contains(Guid.Parse("xxx")), () =>
            {
                RuleFor(x => x.ABC).Must(x => x.Count > 0).WithMessage(x => localizer.GetString("xxx"));
            });
`
I´m always getting the default translation of "xxx".
BUT if I´m **not** using the "when"-condition it is working perfectly fine. So basicly my translation is working perfect. Only If I´m using the When(...) part, it somehow stops working.

Any ideas how to fix this?

**Comment by JeremySkinner** [comment]
Hi, is this for server-side validation or client-side validation? Rules with conditions are not supported with client-side validation.

**Comment by cytex124** [comment]
No It is serverside. It is a Web API. Therefore I´m seting the Accept-Language in the header.
Thread.CurrentCulture and Thread.CurrentUiCulture is settet to the right CultureInfo.

In the startup.cs - ConfigureServices:
```
services.AddLocalization(options => options.ResourcesPath = "Resources");
```

In the startup.cs - Configure:
```            
var supportedCultures = new[]
{
    new CultureInfo("de"),
    new CultureInfo("en")
};
 var requestLocalizationOptions = new RequestLocalizationOptions
{
     SupportedCultures = supportedCultures,
     SupportedUICultures =  supportedCultures,
     RequestCultureProviders = new List<IRequestCultureProvider>
     {
           new AcceptLanguageHeaderRequestCultureProvider(),
           new CookieRequestCultureProvider(),
           new QueryStringRequestCultureProvider()
      }
 };
app.UseRequestLocalization(requestLocalizationOptions);
```

**Comment by cytex124** [comment]
I also have the same behaivour when I´m using ".Custom(...)".

**Comment by JeremySkinner** [comment]
Having a When condition on a rule only affects at what point the rule is run - it won't change how the localizer is executed, so I expect there's something else going on. 

A couple of things to check first:
- If you test invoking the localizer directly, does it come back with the correct result? (ie temporarily remove FluentValidation from the process)
- Make sure your validators are registered with the service provider either as Transient or Scoped (not singleton)

Once you've checked this, if you're still having problems please put together a small, minimal project that reproduces the issue that I can run, and I'll take a further look for you.

**Comment by cytex124** [comment]
Somehow it works now. I don´t know why.
Still thx for the fast repsonse Jeremy 👍 

Case Closed.
