### ISSUE TITLE
How RegisterValidatorsFromAssemblyContaining works

### ISSUE THREAD

**Issue by bwn-z** [FluentValidation/FluentValidation#1589]
**Which version of FluentValidation are you using?**
9.3.0

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I have many validators in my project, catalog - Validators:

```
Project.API
|
| --Validators
            |
            | --Validator1
            | --Validator2
            | --Validator3
```

For example, 
1. Validator1 and Validator2 are registered as singleton (manually registration and using - new Validator1....)
2. I want to use an automatic registration for Validator3
3. I've seen a documentation and I've read a description of a parameter `filter - Optional filter that allows certain types to be skipped from registration.`
4. I've tried to use RegisterValidatorsFromAssemblyContaining with optionally filter.
My example was: ` .AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<Startup>(x => x.ValidationType != typeof(Validator3)` - as a text it is "I want to skip for registration Validators which isn't Validator3. But it doesn't works to me.

1. How can I do this?
2. I think that a more detailed example should be added to the documentation. How do you think?

**Comment by JeremySkinner** [comment]
Hello,

The filter is *inclusive* not *exclusive*, so your example code will do the opposite of what you want (it'll register validator1 and validator2, but skip validator3). You need to change `!= typeof(Validator3)` to `== typeof(Validator3)`

**Comment by bwn-z** [comment]
Hello, @JeremySkinner 

I 've tried to change this syntax from `!=` to `==`. It doesn't work, Validator1 and Validator2 was registered as Validator3. And for every request Validator1 and Validator2 was called in mvc pipeline - Model Binder. Manually registering was ignored.

**Comment by bwn-z** [comment]
Question above was the first.

The second is "How can I register some validators with `RegisterValidatorsFromAssemblyContaining ` syntax with singleton and transient lifecycle at the same time.

For example, I guess it will be as:
```
.AddFluentValidation(options => {
// options.AddValidator<Validator1>(lifecycle: singleton);
// options.AddValidator<Validator2(lifecycle: singleton);
//options.AddValidator<Validator3>(); <-- transient as default
}
```

So, I want to use this validator in mvc pipeline - Model Binder. They are in one assembly

**Comment by JeremySkinner** [comment]
> Validator1 and Validator2 was registered as Validator3. And for every request Validator1 and Validator2 was called in mvc pipeline - Model Binder. Manually registering was ignored.

I don't really understand what you're saying. Can you provide more details of what specifically isn't working? The filter you supply is applied to each validator that's discovered in the assembly. If your filter function returns `true`, it'll be registered with the service provider. If your filter function returns `false` then it won't be, so you need to write the filter to return `true` for those what you want to be registered. 

> The second is "How can I register some validators with RegisterValidatorsFromAssemblyContaining syntax with singleton and transient lifecycle at the same time.

You will need to register them with the service provider directly, by mapping the validator interface to the concrete type (see the first section on this page: https://docs.fluentvalidation.net/en/latest/aspnet.html):

```csharp
services.AddSingleton<IValidator<Type1>, Validator1>();
services.AddTransient<IValidator<Type3>, Validator3>();
// etc. 
```

**Comment by bwn-z** [comment]
So, I've used that:
```
AddFluentValidation(options
                => options.RegisterValidatorsFromAssemblyContaining<Validator3>(x => x.ValidatorType == typeof(Validator3)));
....
.AddSingleton<IValidator<>, Validator1>()
.AddSingleton<IValidator<>, Validator2>();
```
I've got the problem: validator1 and validator2 are working in mvc pipeline - Model binder, but they shouldn't work like that because I'm using they manually with `var validaator1 = new Validator1();...`

Why do validator1 and validator2 work in model binder pipeline??? It's wrong

**Comment by JeremySkinner** [comment]
> Why do validator1 and validator2 work in model binder pipeline??? It's wrong

Because you're still registering them afterwards with `AddSingleton`.

**Comment by bwn-z** [comment]
> If you are instantiating your validators manually with new Validator1() then you don't need to register it with the service provider at all.
-My apologies. It's wrong sentence from me. I've used Valiator1 and Validator2 from DI but manually without mvc pipeline.
Example:

```
public class SomeService: ISomeService
    {
        private readonly IValidator<...> _validator1;

        public SomeService(
            IValidator<...> validator)
        {
            _validator = validator;
        }

        public async Task<...> AddSomeEntityAsync(SomeParam param)
        {
            var validateResult = _validator.Validate(param);
            if (!validateResult.IsValid)
            {
                throw new ValidationException(validateResult.Errors);
            } 
            ...
        }
   }
```



I've used the optional filter which skipping to register Validator1 and Validator2. Why are they used in mvc pipeline? They should not

The last question from me it is: How should I work with FluentValidation in Startus.cs If I don't want that Validator1 and Validator2 are in mvc pipeline (I've used them from DI and worked with them manually), but I want that only validator3 are in mvc pipeline?

**Comment by JeremySkinner** [comment]
> I've used the optional filter which skipping to register Validator1 and Validator2. Why are they used in mvc pipeline? They should not

I have already explained this to you in my previous reply. 

The MVC pipeline will use *any validator registered with the service provider*. If you are registering Validator1 and Validator2 with the service provider (with AddTransient/AddSingleton) then the MVC pipeline will still use them. 

The optional filter only applies to *auto registration*. It doesn't apply to anything you register with the service collection manually.

> If I don't want that Validator1 and Validator2 are in mvc pipeline (I've used them from DI and worked with them manually). 

That's not really possible if you're registering them as  `IValidator`. 

You would either have to use the [Skip functionality](https://docs.fluentvalidation.net/en/latest/aspnet.html) to ignore them at the action-level, or you would have to change your registration. Instead of registering them a `IValidator<Type>` you could register them as the implementation type directly:

```
// Instead of this:
services.AddTransient<IValidator<Type1>, Validator1>();
// Could do this instead:
services.AddTransient<Validator1>();
``` 

This will mean you can't inject `IValidator<Type1>` anymore, so the MVC pipeline will no longer pick it up, but you can still inject `Validator1` directly in your service.

**Comment by bwn-z** [comment]
@JeremySkinner okay, thanks for discuss!)
