### ISSUE TITLE
Automatically register IPropertyValidators

### ISSUE THREAD

**Issue by Pankraty** [FluentValidation/FluentValidation#1592]
**Is your feature request related to a problem? Please describe.**

In our ASP.NET project we're actively using FluentValidator and register all implementations of `IValidator<T>` found in a given assembly by using `services.AddFluentValidation(...)`. But we are also using quite a few property validators (`IPropertyValidator`) some of which have quite complex logic and dependencies injected via constructor. The mentioned `AddFluentValidation` method does not register them in ServiceCollection and we have to do it manually for each validator

This is of course just a small inconvenience, and we can easily implement auto-registration on our side but I thought maybe you'll find it reasonable to register them in the library code altogether. If you agree I can prepare a pull request for this.

**Describe the solution you'd like**

The simplest solution would be just to register `IPropertyValidator`s inside the [AssemblyScanner's method](https://github.com/FluentValidation/FluentValidation/blob/48623e837ad63682b899c5a362b0e6a132fdb94b/src/FluentValidation/AssemblyScanner.cs#L72). This will work seamlessly for most of the users but may potentially break DI configuration for those who are using Ninject _and_ binds property validators manually - they'll have to remove manual bindings or replace `Bind` with `Rebind` because, as far as I know, Ninject does not like duplicate bindings (I can be mistaken here).

The alternative solution would be to let users explicitly specify that they want to register property validators together with `IValidator`s - this can be done by adding an optional parameter to [FluentValidationMvcConfiguration's methods](https://github.com/FluentValidation/FluentValidation/blob/bb87d1a915099132900c0ecbf92a2eff539ec403/src/FluentValidation.AspNetCore/FluentValidationMvcConfiguration.cs#L118) and to public methods of [AssemblyScanner](https://github.com/FluentValidation/FluentValidation/blob/48623e837ad63682b899c5a362b0e6a132fdb94b/src/FluentValidation/AssemblyScanner.cs#L45). The argument type can be a flagged enum, like,
```
[Flags]
public enum ValidatorTypes
{
    IValidator = 1,
    IPropertyValidator = 2,
    All = IValidatator | IPropertyValidator
}
```
with `ValidatorTypes.IValidator` set by default.

**Describe alternatives you've considered**

The obvious alternative would be implementing this on our side solely, but I am not fond of code duplication. Besides, other users can find this useful too.

**Additional context**

I tend to prefer this approach
```
public class ParentValidator : AbstractValidator<SomeEntity>
{
    public ParentValidator(ChildValidator childValidator)
    {
        RuleFor(x => x.SomeProperty)
            .SetValidator(childValidator);
    }
} 
```
as opposed to 
```
        RuleFor(x => x.SomeProperty)
            .SetValidator(new ChildValidator());

```
because 
* `ChildValidator` may have its own dependencies that have to be passed to its constructor,, and it's not `ParentValidator`s business to take care of them
* It simplifies testing of the parent validator because I can pass one or another stub of a child validator and see the parent validator succeeds or fails, respectively. With this, the parent class's tests don't need to know too much of child validators' details.

**Comment by JeremySkinner** [comment]
Hello, 

Thanks for the suggestion but this isn’t something that we’ll implement. Please see my post here which explains why this is extremely dangerous: https://github.com/FluentValidation/FluentValidation/issues/1572#issuecomment-722927849

**Comment by Pankraty** [comment]
Thank you and sorry for creating the duplicate. Honestly, I did search for existing issues but missed that one somehow 🤦

**Comment by JeremySkinner** [comment]
That’s ok! It can be hard to find duplicates unless you know the exact keywords. Hope it makes sense.

**Comment by Pankraty** [comment]
Yeah, totally!
