### ISSUE TITLE
Success does not set ModelState to "Validated"

### ISSUE THREAD

**Issue by lukos** [FluentValidation/FluentValidation#1593]
**Which version of FluentValidation are you using?**
9.3

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I am using a custom model binding provider to support polymorphic binding depending on the `Kind` property of the model. For example, in the code below, the `PageModel` has a property `List<QuestionType`> but these could be different question types. The model binding works OK, I just need to try and get validation working using manual validation since the validation needs to be applied dynamically i.e. some questions might be required, others not required so I thought of using FV (thanks, it is really cool).

Anyway, the only way I could find to work out the correct type of validator is using the code below and then once validating, adding the results to the modelstate to work with MVC. The state of each property in `ModelState` starts as "Unvalidated" but the strange thing is that if the validator fails, the property is correctly marked as "Invalid". However, if the validator is successful, the state remains at "Unvalidated", which means `ModelState` is not valid. I understand this from the perspective that if there are no errors, there is nothing to add to ModelState but then I am not sure how to avoid this problem and getting them to play nice.

I did try polymorphic validator selection using the automatic aspnet core functionality but that didn't seem to work, which is no worries.

```c#
public IActionResult Submit([FromServices] IValidatorFactory factory, 
                            [FromForm] PageModel model)
{
    // Do this manually, cannot get it to work implicitly
    // Use a for loop to generate the correct format for adding to model state
    for ( var i = 0; i < model.Questions.Count(); ++i )
    {
        var question = model.Questions[i];
        Type questionType = question.GetType();
        var validator = factory.GetValidator(questionType);
        var results = validator.Validate(new ValidationContext<object>(question));
        results.AddToModelState(ModelState, $"Questions[{i}]");
    }

    if(!ModelState.IsValid)
    {
        return View(model);
    }
    return RedirectToAction("Finished");
}
```
Registration
```c#
services.AddControllersWithViews(options =>
{
    options.ModelBinderProviders.Insert(0, new QuestionTypeModelBinderProvider());
}).AddFluentValidation(fv =>
{
    fv.AutomaticValidationEnabled = false;
});
```

**Comment by JeremySkinner** [comment]
Hi, you're correct that the `AddToModelState` method only adds errors (which will set modelstate entries to "Invalid") - it doesn't change the state for other modelstate entries, which is intentional. You'll need to modify the ModelState entries yourself if you want the "Unvalidated" entries to be "Valid" instead.

**Comment by lukos** [comment]
OK, thanks for the quick reply.
