### ISSUE TITLE
An easier way to extract metadata from child validators?

### ISSUE THREAD

**Issue by schotime** [FluentValidation/FluentValidation#1596]
FluentValidation 9.3 with net5.0.

I'm iterating through validators for their metadata and want to expand into child validators but had to resort to a nasty dynamic hack. 

https://github.com/schotime/SchoStack.AspNetCore/blob/master/src/SchoStack.AspNetCore.FluentValidation/FluentValidatorFinder.cs#L80

I'm not sure if there is a better way, or a better way can be created?
Cheers

**Comment by JeremySkinner** [comment]
Hey, so the short answer is no - there isn't a better way to do this. Loading the child validator instance isn't really intended to be done in metadata scenarios, as construction of the child validator can be dependent on the context, meaning that its behavior when you do this may end up being different from the behaviour when `Validate` is called. I'm uncomfortable exposing the method publicly on the metadata interface as I really don't want to imply that this is a supported scenario. 

If you really need to do this then I think this is still your best approach, but it's very much a case of "use at your own risk"

**Comment by JeremySkinner** [comment]
I don't know if this would work in your scenario, but another approach would be to use the `ValidatorType` property that's exposed on `IChildValidatorAdaptor` to resolve the correct validator type from the container directly (if it's set)

**Comment by schotime** [comment]
I've been doing https://github.com/schotime/SchoStack.AspNetCore/commit/df7d5e3203c4742b91004487c930a7fff9ff202c#diff-de3cf4cc9136eed81c1e3fa373bbfa96cf8763180eb6258fe6930c197008068fL92 for years (5+) so if what I'm doing isn't much different then it will be good enough for now?

**Comment by JeremySkinner** [comment]
Yes I think it's good enough 👍
