### ISSUE TITLE
When/RuleFor clause depending on two properties

### ISSUE THREAD

**Issue by ChristinaFaur** [FluentValidation/FluentValidation#1598]
Hi,

I have to write a validator which has to check if  ValueDelimiter contains FileDelimiter. This approach works for me, but I don't like the .Must(_=> false) clause. Is it possible to write a message without a condition? Does another better approach exists for this scenario?

When(x => !string.IsNullOrEmpty(x.ValueDelimiter) && x.ValueDelimiter?.IndexOf(x.FileDelimiter) != -1, () =>
{
	RuleFor(x => x.ValueDelimiter)
		.Must(_ => false)
		.WithMessage("The value separator can not contain the complete file delimiter!");
});

**Comment by JeremySkinner** [comment]
Hi, you should put the check inside the call to Must, not inside the call to When. 

Calls to Must can still access other properties on the model (there’s a second overload)
