### ISSUE TITLE
Question re. Warnings generated in validators of nullable reference types

### ISSUE THREAD

**Issue by markm77** [FluentValidation/FluentValidation#1600]
This is a follow-on question relating to https://github.com/FluentValidation/FluentValidation/issues/1168 by @danadesrosiers since that is locked for comments.

When validating an optional property of type Y for which we have a validator, is the following best practice?

```csharp
            RuleFor(x => x.TypeYOptional!)
                .SetValidator(new TypeYValidator())
                .Unless(x=>x.TypeYOptional is null)
```

It would be much nicer to have a syntax that doesn't require ```!``` whose use should be a last resort.

**Comment by JeremySkinner** [comment]
> is the following best practice?

You don't need the call to `Unless`. Child validators aren't invoked for null properties. 

> It would be much nicer to have a syntax that doesn't require ! whose use should be a last resort.

Please feel free to propose a syntax and implementation that you would prefer.

**Comment by markm77** [comment]
Thanks for the quick reply.

Given what you say about child validators not being invoked for null properties, couldn't you then simply allow
```csharp
 RuleFor(x => x.TypeYOptional)
                .SetValidator(new TypeYValidator())
```
although perhaps some kind of transform is needed on the validator to convert from non-nullable generic type ```TInner where TInner: class``` to nullable ```TInner?``` (equal to ```TProperty```). (I don't really know your code just poked around a bit and thought of this.)

**Comment by JeremySkinner** [comment]
I’m probably misunderstanding but how is that any different to the existing method signature? What would the signature of RuleFor look like in your example?

**Comment by markm77** [comment]
I guess I'm not thinking of any change to the existing method signature, rather a transform like

```csharp
public static IValidator<TInner?> NullableVersion(this IValidator<Inner>) where TInner: class
```

which then allows

```csharp
RuleFor(x => x.TypeYOptional)
                .SetValidator( (new TypeYValidator()).NullableVersion())
```
to be used without a compiler warning.

**Comment by JeremySkinner** [comment]
I'm not really sure how that would work. If you could put together an initial implementation in a PR that targets the 10.x branch that illustrates what you're trying to achieve, then I'd be happy to take a look at it. If it looks OK then we can look at fleshing it out further afterwards.

**Comment by markm77** [comment]
Okay, if nullable is not enabled in the core project I don't think this makes sense. I can just have a go at creating this extension method in my project and perhaps in the future add it to the core project when nullable is enabled. If I get something to work, I can post the code here (it won't be complex) to allow others to use as well in their projects which support nullable.

**Comment by JeremySkinner** [comment]
Ok that sounds like a good approach. 

Yes there's no plans on enabling nullable in the core FluentValidation project as it's not something I'm at all keen on, and the complexity it adds isn't worth it. However I'd be open to having it enabled on a separate integration project.

**Comment by markm77** [comment]
Thanks for your help @JeremySkinner . Here's what I decided to go with for now.

```csharp
            RuleFor(x => x.TypeYOptional)
                .SetValidator(
                    new NullableValidator<TypeY>(
                        new TypeYValidator()))
```

where ```NullableValidator``` is essentially a wrapper around the original validator with adjusted ```Validate``` and ```ValidateAsync``` methods:

```csharp
    public class NullableValidator<TValidatorType> : IValidator<TValidatorType?> where TValidatorType : class
    {
        private readonly IValidator<TValidatorType> _baseValidator;

        public NullableValidator(IValidator<TValidatorType> baseValidator)
        {
            _baseValidator = baseValidator;
        } 

        public ValidationResult Validate(IValidationContext context) => _baseValidator.Validate(context);

        public async Task<ValidationResult> ValidateAsync(
            IValidationContext context,
            CancellationToken cancellation = new CancellationToken()) =>
            await _baseValidator.ValidateAsync(context: context, cancellation: cancellation);

        public IValidatorDescriptor CreateDescriptor() => _baseValidator.CreateDescriptor();

        public bool CanValidateInstancesOfType(Type type) => _baseValidator.CanValidateInstancesOfType(type);

        public ValidationResult Validate(TValidatorType? instance) => instance is null
            ? throw new InvalidOperationException("FluentValidation should not try to validate null")
            : _baseValidator.Validate(instance);

        public async Task<ValidationResult> ValidateAsync(
            TValidatorType? instance,
            CancellationToken cancellation = new CancellationToken()) =>
            instance is null
                ? throw new InvalidOperationException("FluentValidation should not try to validate null")
                : await _baseValidator.ValidateAsync(instance: instance, cancellation: cancellation);

        public CascadeMode CascadeMode
        {
            get => _baseValidator.CascadeMode;
            set => _baseValidator.CascadeMode = value;
        }
    }
```

If I find any issues and I'm able to edit this thread I'll try to come back and update.
