### ISSUE TITLE
Validator class nested inside model class

### ISSUE THREAD

**Issue by urielzen** [FluentValidation/FluentValidation#1601]
**Which version of FluentValidation are you using?**
9.3.0 

**Which version of ASP.NET are you using?**
NET 5.0.1

**Describe the issue that you're having**
Do you see any issues if I were to nest the validator class inside the model class?

```
public class RequestModel
{
    public string PropA { get; set; }
    public List<string> PropB { get; set; }

    public class RequestModelValidator : AbstractValidator<RequestModel>
    {
        public RequestModelValidator ()
        {
            RuleFor(m => m.PropA ).NotEmpty();
        }
    }
}

```

I have tested it and it seems to work fine, but I was wondering if you see any problem down the road doing it this way?

Thanks, I appreciate it!

**Comment by JeremySkinner** [comment]
Hi, no problems - that will work fine.
