### ISSUE TITLE
Question: ServiceProviderValidatorFactory / IValidatorFactory service injection in custom classes

### ISSUE THREAD

**Issue by kreditkenny** [FluentValidation/FluentValidation#1602]
I have both FluentValidation and FluentValidation.AspNetCore packages installed and they are working correctly as intended.

My question:
How can I make IValidatorFactory available in my lower level services?

public class SomeCustomClass 
{
    private readonly IValidator _validator;
    public SomeCustomClass(IValidator validator)
    {
         _validator = validator;
    }
    public void SomeImplementation<T>(Model model) 
    {
         var validator = _validator.GetValidator<SomeValidator>();
         validator.Validate(model);
    }
}

// tried1:
                .AddFluentValidation(f => {
                    f.ValidatorFactory = new ServiceProviderValidatorFactory(services.BuildServiceProvider());
                    f.RegisterValidatorsFromAssemblyContaining<LoginCommandValidator>();
                })

// tried2:
            services.AddSingleton<IValidatorFactory, ServiceProviderValidatorFactory>()

**Comment by JeremySkinner** [comment]
Hi, if you’re using the AddFluentValidation method in your application startup then the validator factory will already be registered with the service provider - you don’t need to do anything special. Just inject it via the constructor as you would any other service.

**Comment by kreditkenny** [comment]
i am registering my validators using the .RegisterValidatorsFromAssemblyContaining extension.

`                .AddFluentValidation(f => {
                    f.RegisterValidatorsFromAssemblyContaining<SomeValidator>();
                })`

but the injected factory in custom class can't find it
`var v = _validatorFactory.GetValidator<SomeValidator>();`

any hints?

**Comment by JeremySkinner** [comment]
That's all you need to do - the validator factory will be automatically registered at the point you call `AddFluentValidation`: 

You'll see it's registered in this method. If you don't specify a validator factory type explicitly then it uses the ServiceProviderValidatorFactory.

https://github.com/FluentValidation/FluentValidation/blob/343ac21fd1370ae7ffe37494288c9375dfcc832a/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L108

If it's not working for you then I would think it's most likely that you've not set something up correctly (are all the validator classes public?). I'd suggest putting together a small sample project that reproduces the issue

**Comment by JeremySkinner** [comment]
Also, make sure you're calling the validator factory correctly. The generic type parameter is the *model type* not the *validator type*: 

https://github.com/FluentValidation/FluentValidation/blob/343ac21fd1370ae7ffe37494288c9375dfcc832a/src/FluentValidation/IValidatorFactory.cs#L25-L29

**Comment by kreditkenny** [comment]
hi @JeremySkinner 

thanks for looking.

scaffolded a standard .net weather app and committed to :
https://github.com/kennydust/FluentValidationFactoryUsecase

stack starts on line 33: 
https://github.com/kennydust/FluentValidationFactoryUsecase/blob/master/FluentValidationFactoryUsecase/Controllers/WeatherForecastController.cs

let me know what i'm missing.

**Comment by kreditkenny** [comment]
doh! i just saw your follow up comment. i think what you are describing should work.

**Comment by kreditkenny** [comment]
@JeremySkinner 

so everything ended up working. 

it definitely would have been clearer if the methods were called GetValidatorFor<>();

otherwise, I think this validation framework is great and I plan to use this for my other projects going forward. thanks again!
