### ISSUE TITLE
HasCondition returns false when rule is in a When block

### ISSUE THREAD

**Issue by thomaslevesque** [FluentValidation/FluentValidation#1604]
**Which version of FluentValidation are you using?**
9.3.0

**Which version of ASP.NET are you using?**
ASP.NET Core 5.0

**Describe the issue that you're having**
I have a validator with rules like this:
```csharp
When(x => SomeCondition(x), () =>
{
    RuleFor(x => x.SomeProperty).NotEmpty();
});
```

When I look at the property validator for `SomeProperty`:

```csharp
foreach (var g in validator.CreateDescriptor().GetMembersWithValidators())
{
    Console.WriteLine($"Property name: {g.Key}");
    foreach (var propertyValidator in g)
    {
        if (propertyValidator.Options.HasCondition)
        {
            ...
        }
    }
}
```

`HasCondition` is always false. Is there a way to detect that a given property validator is conditional when using `When` like this? Or do I have to do `RuleFor(...).When(...)`?

**Comment by JeremySkinner** [comment]
Hi, this is the correct behaviour. 

There are 2 levels of `When` conditions (chained, or block-level). `propertyValidator.Options.HasCondition` indicates of a condition has been set within a call to `RuleFor().When()`. If you want to check for a block-level `When`, then you'll need to check the Condition property on the `PropertyRule` instance instead.

**Comment by JeremySkinner** [comment]
Quick example:

```csharp
foreach (var rule in validator) {
	if (rule is PropertyRule propertyRule) {
		bool hasBlockLevelCondition = propertyRule.Condition != null || propertyRule.AsyncCondition != null;

		foreach (var propertyValidator in propertyRule.Validators) {
			bool hasConditionInsideChain = propertyValidator.Options.HasCondition || propertyValidator.Options.HasAsyncCondition;
		}
	}
}

```

(Note that both of these are likely to receive significant changes in FluentValidation 10.0, as much of the internal API is going to be made internal, so just a heads up that you'll likely need to revisit this once 10.0 ships).

**Comment by thomaslevesque** [comment]
Hi @JeremySkinner,

Thanks for the quick answer! That solves my problem, thanks!
