### ISSUE TITLE
How to update model before validation runs?

### ISSUE THREAD

**Issue by epitka** [FluentValidation/FluentValidation#1607]
**Which version of FluentValidation are you using?**
8.6.3 

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
If I want to update model before performing validation via FluentValidation how does one do that. I have a customer filter that pulls the value from the header and updates model with it. Problem is that validation runs first, which makes my model invalid.

This is registration code

```
  services.AddMvc(
                        options =>
                        {
                            options.EnableEndpointRouting = true;
                            options.Filters.Add<CustomerRequestFilter>();
                            options.Filters.Add<ExceptionFilter>();
                        })
                    .AddFluentValidation(
                        config =>
                        {
                            config.RegisterValidatorsFromAssemblyContaining<Startup>();
                        })
```

CustomerRequestFilter looks at either header or claims, extract the value and updates model with it

**Comment by JeremySkinner** [comment]
Hi, FluentValidation runs during ASP.NET's model binding process. You'd need to write a custom model binder if you want to customize this process. https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0
