### ISSUE TITLE
Installation Package

### ISSUE THREAD

**Issue by pascalfossouo** [FluentValidation/FluentValidation#1608]
On VS when trying install the package have this error : 

Erreur		Échec de la restauration du package. Restauration des modifications du package pour 'FluentValidation'.				

Erreur	NU1108	Cycle détecté. 
  FluentValidation -> FluentValidation (>= 9.3.0).	FluentValidation

**Comment by JeremySkinner** [comment]
I don't speak french, but that doesn't look like an issue with FluentValidation - it sounds like either you have a problem with your dependency graph (different projects depending on different versions) or something with the VS package manager is corrupt. Try installing it from the CLI and see if it does the same thing.
