### ISSUE TITLE
RemoveRule

### ISSUE THREAD

**Issue by carlhoogstoel** [FluentValidation/FluentValidation#1609]
Just a quick question.

Can you explain why you made the RemoveRule obsolete? I understand you want things to be immutable, but I just implemented these methods again from [https://github.com/FluentValidation/FluentValidation/blob/7.x/src/FluentValidation/BackwardsCompatibility.cs](url) as I need them for my business logic and was just wondering what I might expect to be broken by using them as they work as expected. 

Or is it just because you want to force the rules to be immutable, i.e. depend on the fact somewhere else in code that they must exist once defined?

Just asking so I know what I am getting myself into:)

**Comment by JeremySkinner** [comment]
Yes, it's because validators are designed to be immutable once constructed - rules shouldn't be removed at runtime.

The file you linked to is out of date (it's from the 7.x release - the current release is 9.3) - those methods were removed a long time ago.
