### ISSUE TITLE
[Advice Needed] Maintaining a persistent state of validation and validating per property

### ISSUE THREAD

**Issue by EP01** [FluentValidation/FluentValidation#1610]
**Which version of FluentValidation are you using?**
9.2.2

**Describe the issue that you're having**
I'm trying to integrate FV into my base view model of my MVVM Xamarin app. The idea is that all VMs inherit this base and define a Validator implementing `IValidator` and all validation is handled automatically when properties change (i.e. immediate feedback to the user after they finish typing in a text field for example). I want to store a persistent state of validation in the base class, so that I can have a simple bool to say whether the model is valid or not, and anything that needs to can just check this bool at any time to know the state. I'll include a simplified non-functional version of what I'm trying to achieve below.

A lot of the validation in my application is complex and for performance reasons it is not desirable to evaluate every rule of a model every time a single property changes, hence my desire to store the state of the whole model when the validator is set and then update single properties as needed. All seemed to be going well until I needed to store a list of the properties that have rules defined in the validator. I could not find a way to access these properties from either the `IValidator` interface, the `ValidationContext`, or the `ValidationResult`. I would prefer not to have to define them separately in each VM.

Does this make sense? Is there a way to get the list of properties that have rules from the Validator in this manner? Does anyone have any advice on this approach, or a different approach altogether?

Thanks in advance.

```
public class BaseViewModel : INotifyPropertyChanged
{
    private IValidator _validator;

    public bool IsValid => StoredValidationResult?.IsValid;

    protected IValidator Validator
    {
        get => _validator;
        set
        {
            _validator = value;
            var _ = Task.Run(async ()=> await Validate());
        }
    }

    // Triggered once when Validator is set
    public async Task Validate()
    {
        if (Validator == null) return;
        var c = new ValidationContext<BaseViewModel>(this);  

        // If the ValidationResult contained all the passed properties and not just the failed ones, I could use that here
        // Otherwise, process this result into a separate class containing the list of properties and their results
        StoredValidationResult = await Validator?.ValidateAsync(c)
    }

    // Triggered on PropertyChanged
    public async Task Validate(string propertyName)
    {
        var c = new ValidationContext<BaseViewModel>(this, new PropertyChain(),
            new MemberNameValidatorSelector(new[] {prop}));
        
        // Process the result of the single property validation to update the overall stored state here
        Result = await Validator?.ValidateAsync(c);
    }
```

**Comment by JeremySkinner** [comment]
I'm not entirely sure I understand what you're asking, but if you need a list of properties defined in the validator then this can be extracted from the validator's metadata using the descriptor. 

```csharp
var descriptor = validator.CreateDescriptor();
var mapping = validator.GetMembersWithValidators();
var propertyNames = mapping.Select(x => x.Key).ToList();
```

**Comment by EP01** [comment]
Hi @JeremySkinner, thanks for the quick response, and sorry my description wasn't very clear! Your interpretation was correct and this is exactly what I needed. I'll close this now, thanks again!
