### ISSUE TITLE
FluentValudation 9.3.0 on net5.0

### ISSUE THREAD

**Issue by robertok77** [FluentValidation/FluentValidation#1611]
FluentValudation 9.3.0
Asp. net core 5.0

### Build Error ###
On fresh new project _Blazor WebAssembly_ on _net 5.0_ when added package _FluentValidation 9.3.0_ to _Shared_ project 
you can get build error:

`Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	BlazorApp1.Client	C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	387	`

See sample in the attachment:
[BlazorApp1.zip](https://github.com/FluentValidation/FluentValidation/files/5809151/BlazorApp1.zip)

**Comment by JeremySkinner** [comment]
Hi, the problem is that you are referencing the `FluentValidation.AspNetCore` package. This is integration components for MVC/WebApi projects - it is not for blazor. You should be referencing the `FluentValidation` package instead. When you make this change, the project will build.
