### ISSUE TITLE
Using WithState with MVC's automatic validation to pass validation information back to client caller

### ISSUE THREAD

**Issue by terryaney** [FluentValidation/FluentValidation#1616]
FluentValidation 9.3.0
.NET 5, Razor Pages Project

I would like the ability to pass back more than 'just' the error message to ajax client calling POST.  Reading this [comment](https://github.com/FluentValidation/FluentValidation/issues/1442#issuecomment-658849867) from #1442, I was trying to understand how to use this as a possible solution.

Currently, I set up FV simply by:

```
services
	.AddFluentValidation(cfg =>
	{
		cfg.RegisterValidatorsFromAssemblyContaining<Startup>();
	});
```

I have a Razor Page `IPageFilter` that runs and in the `OnPageHandlerExecuting` method, if `!ModelState.IsValid` I serialize ModelState to JSON and send back to the client.  However, I was hoping for a way to have the client able to look at some information in the error instead of just basing logic on the error message (which could be different based on localization).

I was thinking this `WithState` might be a possibility until I read your comment.  The best I have figured out so far is to use `IActionContextValidatorInterceptor` as mentioned in #885 and change the message to be the `ErrorCode` to be able to pass down the 'type' to the client.  But then if I want to display the error message, the client side would have to have knowledge of correct error message to display based on type.  So that isn't great option.

What is the best way to be able to send back ModelState (and maybe that is problem, and I need to send back something else) to a client api call so they get error message **and** error type (or other state information).  Is there a way to grab the FV 'validation context/state' from inside `IPageFilter.OnPageHandlerExecuting` so I could serialize that (or part of it) instead?

**Comment by JeremySkinner** [comment]
This isn't really possible using automatic validation. The format of ASP.NET's ModelState dictionary is fixed - you can't add additional properties to it for serialization back to the client. You would need to use your own data structure instead.

You would need to turn off automatic validation, and instead invoke the validator manually, inspect it's result and then use that to create whatever format you want for serialization.

**Comment by JeremySkinner** [comment]
One other option that wouldn't require turning off automatic validation, is you could use the `IActionContextValidatorInterceptor` to store the `ValidationResult` in `HttpContext.Items` which you could then access from inside the action (or a filter) and serialize that instead of ModelState.
