### ISSUE TITLE
Add Information in the RuleSets documentation page

### ISSUE THREAD

**Issue by lucasgit2000** [FluentValidation/FluentValidation#1617]
**Is your feature request related to a problem? Please describe.**
I have to look somewhere else outside the doc page a line of code that was needed to implement RuleSets

**Describe the solution you'd like**
It would be great if in the RuleSets documentation we could also find a piece of information that describes the only way to use options method overload is if we put ```using FluentValidation``` in our code, otherwise it won't work.

**Describe alternatives you've considered**
Maybe the extension or the method with options overload also be located in the same namespace as ```using FluentValidation.Results```?

**Additional context**
```
using FluentValidation

var result = await validator.ValidateAsync(req, options: options => {
options.IncludeAllRuleSets();
});
```

Forgive me if I'm missing something, just found this library and saw the great potential on it, I just wanna help.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. Many of the methods in FluentValidation are extension methods and require the FluentValidation namespace to imported via a using statement. 

This particular method will likely become an instance method in the 10.0 release.

**Comment by lucasgit2000** [comment]
#1618 opened, I hope you'll attend, in case I have to do something else, I'm all ears.
