### ISSUE TITLE
How do I avoid having to set the severity and name for each rule?

### ISSUE THREAD

**Issue by Matthew-Bonner** [FluentValidation/FluentValidation#1619]
When I have the following, is there any way I can avoid having to set the severity and name for each rule?

```
            RuleFor(envelope => envelope.Body.MOARequest.Header.RequestID.Text)
                .NotNull()
                .WithSeverity(Severity.Warning)
                .WithName(NameOf(envelope => envelope.Body.MOARequest.Header.RequestID))
                .NotEmpty()
                .WithSeverity(Severity.Warning)
                .WithName(NameOf(envelope => envelope.Body.MOARequest.Header.RequestID))
                .MaximumLength(20)
                .WithSeverity(Severity.Warning)
                .WithName(NameOf(envelope => envelope.Body.MOARequest.Header.RequestID))
                .When(envelope => envelope?.Body?.MOARequest?.Header?.RequestID != null);
```

**Comment by JeremySkinner** [comment]
You don’t have to call WithName multiple times - you can just call it once as the display name is already scoped to the entire rule. 

However the severity is intentionally scoped to each property validator within the rule chain. You could write an extension method that loops over each validator in the chain and sets the severity to the same thing if you want.

**Comment by Matthew-Bonner** [comment]
Thanks for letting me know, I'll give it a try.

Although in all fairness, I don't even want to have to make that call, I'm only doing it to get the body of the expression to use that as the name such as **envelope.Body.MOARequest.Header.RequestID**. I can see the existing naming is designed for outputting to users which is why I'm overriding it. RuleFor wasn't virtual so I can't override how it works, which is a shame as I'd have been able to override it and set the name then I guess.

**Comment by JeremySkinner** [comment]
You should be able to set the global `ValidatorOptions.Global.DisplayNameResolver` in your application startup if you want to change the display name behaviour for all rules. 

Also the full property path is available on the resulting ValidationFailure regardless of how the display name is set.

**Comment by Matthew-Bonner** [comment]
Unless mistaken, that won't work with expressions though will it as I can't get the expression body.

**Comment by Matthew-Bonner** [comment]
Also, I've applied the update so that I only call WithName once per rule and it works a treat thanks. Could that be added to the docs as I was in a bit of a rush last night and it wasn't really clear so I just went with what I felt was safe.

**Comment by JeremySkinner** [comment]
The third parameter of the global display name resolver is the expression

**Comment by JeremySkinner** [comment]
> Could that be added to the docs

Sure, feel free to send a pull request to add this in, otherwise I’ll try and get to it when I have a bit of time
