### ISSUE TITLE
Package FluentValidation.AspNetCore 9.4.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1)

### ISSUE THREAD

**Issue by robdevil** [FluentValidation/FluentValidation#1620]
Upgraded my web app (which is a react frontend and NetCore backend) from NetCore 3.1 to 5.0 and FluentValidation is the only thing that doesn't want to play nicely. Previous version 8.6.3 works fine with NetCore 5.0.

Error | NU1202 | Package FluentValidation.AspNetCore 9.1.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1).  Package FluentValidation.AspNetCore 9.1.0 supports:  
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)  
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)

My project file details are below:

<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="8.6.3" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

</Project>

**Comment by JeremySkinner** [comment]
The FluentValidation.AspNetCore should only be referenced from your *web* project (net5.0), not a netstandard class library. This package contains the web integration components. 

Your netstandard library should just reference FluentValidation (not FluentValidation.AspNetCore)

**Comment by JeremySkinner** [comment]
You’ll also need to make sure you upgrade both packages to 9.3 or newer for net5 compatibility.
