### ISSUE TITLE
DataGrid Validation (validate collections)

### ISSUE THREAD

**Issue by ac-rosu** [FluentValidation/FluentValidation#1622]
FluentValidation 9.4.0

Hi guys,

Is not an issue. More like a question.

Is it possible to validate a datagrid  for duplicated entries in a column?
Example: Let say I have a DataGridTextColumn "**Id**".. I would like to check all the entries for that column for duplicated ids. 

Thanks for you response!

**Comment by JeremySkinner** [comment]
Hi, I don’t really understand what you’re asking. 

FluentValidation is a tool for validating the properties of strongly typed model objects.

**Comment by ac-rosu** [comment]
Hi, thanks for your reply. What I meant is if I can run the validation on a ObservableCollection, List, ... etc. Thanks!

**Comment by JeremySkinner** [comment]
I still don’t understand what you’re asking, you really haven’t provided enough information about what you’re trying to do. If you could explain in more detail then I’ll try and help you further. Thanks.

**Comment by ac-rosu** [comment]
Ok, Bellow you can see a datagrid, a model, and the collection of that model.

What I would like to achieve is to not allow in TextColumn1 duplicated entries.

I noticed that I can validate my model without problems, but I cannot validate the collection from my viewmodel.

![DataGrid](https://user-images.githubusercontent.com/71214665/105770147-1a238780-5f5f-11eb-8662-dddf0ea728ec.PNG)
![Model](https://user-images.githubusercontent.com/71214665/105770150-1abc1e00-5f5f-11eb-9535-7bce8107b219.PNG)
![ViewModel](https://user-images.githubusercontent.com/71214665/105770152-1abc1e00-5f5f-11eb-9366-06e4a43e9c14.PNG)

**Comment by JeremySkinner** [comment]
How is your validator defined, and how are you invoking it?

**Comment by ac-rosu** [comment]
I created a class as described in the documentation.
And in my model I call the validator class.

![Validator in my model](https://user-images.githubusercontent.com/71214665/105771344-b4d09600-5f60-11eb-9d11-d2350132887d.PNG)
![validator](https://user-images.githubusercontent.com/71214665/105771346-b5692c80-5f60-11eb-98b9-b35434c43f2b.PNG)

**Comment by ac-rosu** [comment]
> How is your validator defined, and how are you invoking it? This is the code I need to see in order to help you.
> 
> I'm guessing your validator is defined against the `DataGridModel` class, rather than against the whole collection?
**Correct**
 If so then essentially you'll need to pass the collection into the validator at the point you instantiate it, then your validator can access it when performing the duplicate check.
**Ok, I will try that**
Thanks!

**Comment by ac-rosu** [comment]
Worked, Thanks!
