### ISSUE TITLE
Allow multiple FluentValidationModelValidatorProvider.

### ISSUE THREAD

**Issue by malylemire1** [FluentValidation/FluentValidation#1627]
FluentValidation 9.4.0

Asp.Net Core 5

The constructor of FluentValidationObjectModelValidator prevent adding another derived class of type FluentValidationModelValidatorProvider. I want to add another FluentValidationModelValidatorProvider that does not replace the behavior of the default one.

`public FluentValidationObjectModelValidator(
			IModelMetadataProvider modelMetadataProvider,
			IList<IModelValidatorProvider> validatorProviders, bool runMvcValidation)
		: base(modelMetadataProvider, validatorProviders) {
			_runMvcValidation = runMvcValidation;
			_fvProvider = validatorProviders.SingleOrDefault(x => x is FluentValidationModelValidatorProvider) as FluentValidationModelValidatorProvider;
		}`

**Comment by JeremySkinner** [comment]
Hi, can you explain your use case?

This class is intentionally internal - this is not a class that should be extended or modified as it's an implementation detail of the library. Why would you want to have multiple instances of this?

**Comment by malylemire1** [comment]
I need to validate a model linked to a view model. And I still need the view model validation to be executed.
I use something like this in a custom FluentValidationModelValidator. For now I have copied the entire code so that the namespace does not match.

`/// <summary>
        /// Validate.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public override IEnumerable<ModelValidationResult> Validate(ModelValidationContext context)
        {
            if (context.Model is IValidationLinkManagerContainer managerModel)
            {
                ModelMetadata linkedModelMetadata = context.MetadataProvider.GetMetadataForType(managerModel.ModelType);

                IModelStateModel linkedModel = managerModel.ToValidationModel();

                if (linkedModel != null)
                {
                    context.ActionContext.HttpContext.Items.TryGetValue(RootMetadata, out object rootMetadata);
                    context.ActionContext.HttpContext.Items.TryGetValue(Customizations, out object customizations);

                    try
                    {
                        ModelValidationContext modelContext = new ModelValidationContext(context.ActionContext, linkedModelMetadata, context.MetadataProvider, null, linkedModel);

                        IEnumerable<string> validations = GetValidationsForLink(managerModel, linkedModel);

                        modelContext.ActionContext.HttpContext.Items[RootMetadata] = linkedModelMetadata;
                        modelContext.ActionContext.HttpContext.Items[Customizations] = new ValueTuple<object, FluentValidation.AspNetCore.CustomizeValidatorAttribute>(
                                linkedModel,
                                new FluentValidation.AspNetCore.CustomizeValidatorAttribute()
                                {
                                    Properties = String.Join(";", validations)
                                });

                        return UpdateValidationResultForLink(managerModel, linkedModel, base.Validate(modelContext));
                    }
                    finally
                    {
                        context.ActionContext.HttpContext.Items[RootMetadata] = rootMetadata;
                        context.ActionContext.HttpContext.Items[Customizations] = customizations;
                    }
                }
            }

            return Enumerable.Empty<ModelValidationResult>();
        }`

**Comment by malylemire1** [comment]
The is no problem adding another FluentValidationClientModelValidatorProvider .

**Comment by JeremySkinner** [comment]
If you're inheriting from `FluentValidationModelValidatorProvider` then you need to *replace* the existing implementation in the ModelValidatorProviders collection, not just add to it.

**Comment by malylemire1** [comment]
Thanks I think I can replace it and only add another FluentValidationModelValidator with this

`
        public override void CreateValidators(ModelValidatorProviderContext context)
        {
            base.CreateValidators(context);
            context.Results.Add(new ValidatorItem
            {
                IsReusable = false,
                Validator = new CoreModelValidator(_implicitValidationEnabled)
            });
        }
    }`

**Comment by JeremySkinner** [comment]
Yes, that's the right way to do it
