### ISSUE TITLE
ScalePrecision is not throwing validation exceptions

### ISSUE THREAD

**Issue by Greven145** [FluentValidation/FluentValidation#1628]
**Which version of FluentValidation are you using?**
9.4.0

**Which version of ASP.NET are you using?**
N/M

**Describe the issue that you're having**
The ScalePrecision validation rule doesn't appear to be working as per the documentation. I have run through a .NET Fiddle to demonstrate that no exception is thrown for a value that is clearly outside the defined bounds of the validator.

https://dotnetfiddle.net/nlB5Tp

Sample code also included here:

```csharp
using FluentValidation;
using FluentValidation.TestHelper;

public class Order {
	public double Price {get; set;}
}

public class TestValidator : AbstractValidator<Order> {
   public TestValidator() {
      RuleFor(order => order.Price)
		  .ScalePrecision(2, 4);
		  //.ExclusiveBetween(20000,50000);
   }
}

public class Program
{
	public static void Main()
	{
		double testValue = 14516.0673370194;
		var order = new Order{Price = testValue};
		var validator = new TestValidator();
		var result = validator.TestValidate(order);
		result.ShouldHaveValidationErrorFor(order => order.Price);
	}
}
```
Uncommenting the ExclusiveBetween rule does fire an exception, so believe that I have the code sample correct. Please let me know if I've missed something.

**Comment by JeremySkinner** [comment]
Hi, the `ScalePrecision` validator only works on properties of type `decimal`. Your property is of type `double`. If you change this to decimal it will work as epxected.

**Comment by Greven145** [comment]
Apologies, my brain just substituted one data type starting with 'd' for another. Thanks!
