### ISSUE TITLE
Provide Property and PropertyValidatorContext in Transform()

### ISSUE THREAD

**Issue by jumpingjackson** [FluentValidation/FluentValidation#1630]
**Is your feature request related to a problem? Please describe.**
I want to write transformation code that doesnt depend solely on the value being passed in.

**Describe the solution you'd like**
Add an overload on Transform that provides a To func that has the object being validated as well as PropertyValidationContext
see RuleFor(x => x.Whatever).Must(MyCustomValidationCode)

**Describe alternatives you've considered**
No much room here for any kind of interesting transformation code if all you have to go on is the incoming value.

**Additional context**
Add any other context or sample code about the feature request here.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion - this is actually already implemented in the 10.0 branch and we’ll be back-porting it to the next 9.x release too.

**Comment by JeremySkinner** [comment]
9.5.1 is released with the ability to access the root object inside the transformer.
