### ISSUE TITLE
Create validation error on failed Transform

### ISSUE THREAD

**Issue by jumpingjackson** [FluentValidation/FluentValidation#1631]
**Is your feature request related to a problem? Please describe.**
I want to return an error to the user when transformation fails without having to duplicate transformation code.

**Describe the solution you'd like**
Something Like:
Transform(x => x.SomeStringProperty, StringToNullableInt).WithMessage("") with similar overloads to the WithMessage on regular property validators

**Comment by JeremySkinner** [comment]
Hi, could you elaborate further on how you'd expect this to work? 

Transformations happen prior to the property value being validated, so generating an error using `WithMessage` errors isn't possible, as nothing exists for the message to be applied to.

When you call something like `RuleFor(x => x.Prop).NotNull().WithMessage("...")` the `WithMessage` is applied to the `NotNullValidator`, which was created by the call to `NotNull` (and replaces its default message). In the case of a Transform, no property validator exists yet, so this proposed syntax wouldn't work. 

Additionally, as a transformation isn't a standard process there's no way to automatically know whether a transformation succeeded or failed, as this is context-dependent and relies on the developer's original intent. It's not something that can be inferred.

What we could potentially do instead is have a way to generate an error inside the transformation function. One idea would be to receive the `ValidationContext<T>` as a parameter: 

```csharp
Transform(x => x.SomeString, to: (instance, value, context) => {
   if (!int.TryParse(value, out int transformed)) {
      context.AddFailure("whatever");
      return null;
   }
   return (int?)transformed;
});
```

...or perhaps alternatively the transformation function could return a tuple indicating whether there's an error:

```csharp
Transform(x => x.SomeString, to: (instance, value) => {
   bool success = int.TryParse(value, out int transformed));
   var value = success ? (int?) transformed : null;
   return (Success: success, Value: value, Error: success ? null : "Value could not be converted..."); 
});
```

Although I'm not entirely sure I like these. Transformations and validations are intentionally separate, and this is blurring the lines a lot.

Perhaps the second example could be modified to just return the value and the success. A custom property validator could then check whether the success property was set to false, and generate an error if so (then passing through the standard property validator mechanism:

 ```csharp
Transform(x => x.SomeString, to: (instance, value) => {
   bool success = int.TryParse(value, out int transformed));
   var value = success ? (int?) transformed : null;
   return (Success: success, Value: value); 
}).TransformMustSucceed().WithMessage("Value could not be converted");
```

Let me know what you think of these options.

**Comment by JeremySkinner** [comment]
It would also be good to details of your specific use case, because in the above examples of converting a string to a nullable int, you can just chain a `NotNull` after the transform to achieve the same result.

**Comment by jumpingjackson** [comment]
I like the last option.  I do a lot of ETL with user provided spreadsheets, so you tend to get pretty dirty data.


in the meantime I ended up doing something like this with 2 properties.


            RuleFor(p => p.AmountStr)
                .Must(ParseToDecimal).WithMessage("Can't parse into decimal")
                .DependentRules(() =>
                {
                    RuleFor(p => p.Amount).ScalePrecision(2, 12);
                    RuleFor(p => p.Amount).LessThanOrEqualTo(999999999.99M);
                });


        public static bool ParseToDecimal(StringyContribution contribution, string arg, PropertyValidatorContext validatorContext)
        {
            if (!string.IsNullOrWhiteSpace(arg))
            {
                return true;
            }

            if (decimal.TryParse(arg, out decimal result))
            {
                contribution.Amount = result;
                return true;
            }
            else
            {
                return false;
            }
        }


________________________________

**Comment by JeremySkinner** [comment]
I've spent some time looking at this recently, and there isn't really a good way to implement this without having to introduce a lot of breaking changes, as well as having a negative impact on performance, which doesn't really seem worth it for a feature that isn't likely to have much usage. 

Instead I've been toying with introducing an exception that could be thrown to cancel execution of the rule if the transform fails:

```csharp
Transform(x => x.AmountStr, value => {
  if (decimal.TryParse(value, out decimal result) return result;
  else throw new TransformFailedException("Can't parse into decimal)
}).ScalePrecision(2,12).LessThanOrEqualTo(999999999.99M);
```

This exception would internally be caught, a validation failure would be generated and the rest of the rule would stop executing. The advantage of this approach is it'd require only minimal changes to the library, and none of them would be breaking. The downside is that using exceptions this way is expensive, so your current approach with DependentRules may actually end up being better. 

Please let me know what you think.

**Comment by JeremySkinner** [comment]
Closing as there were no further responses. Please re-open if you're still interested in discussing this feature.
