### ISSUE TITLE
Support chained conditions after a call to `Include`

### ISSUE THREAD

**Issue by rklec** [FluentValidation/FluentValidation#1640]
**Is your feature request related to a problem? Please describe.**
I use inheritage [as defined here](https://docs.fluentvalidation.net/en/latest/inheritance.html) and want to validate different classes of ViewModel. Common properties are defined in an Interface.
This is very similar as your docs state. The different is just I don't have a child validator for one property I want to use (`SetInheritanceValidator`), as the property are nested, but just the **"plain" properties** on the same type (interface) of an object in my case.

I.e.:
* `CommonPropertiesValidator` with validation for `ICommonProperties`.
* `ImportViewModelValidator` with validations for `ImportViewModel` which implements `ICommonProperties`.
* `EditingViewModelValidator` with validations for `EditingViewModel` which implements `ICommonProperties`.

I cannot solve this with usual `When` clauses because whether/**how the properties should be validated depend on a property in `ImportViewModel`** (let's say this is `ShouldApply`). As that is not a property in `ICommonProperties` I cannot use it in the `CommonPropertiesValidator`.
Of course I could write two validators, but I still like to use `CommonPropertiesValidator` for keeping the properties and validations that are the same in both cases in one place.

**Describe the solution you'd like**
I think my use case would totally be satisfied in a readable way if `Include` would have a way to define constraints, i.e. a `When` clause:
```c#
Include(new CommonPropertiesValidator()).When(x => x.ShouldApply);
```

**Describe alternatives you've considered**
I tried using `DependentRules` as a workaround:
```c#
RuleFor(x => x.ShouldApply).Equal(true).When(x => x.ShouldApply == true).DependentRules(() =>
{
    Include(new CommonPropertiesValidator());
});
```
However, this seems to always `Include` the rules anyway, nesting `Include` does not seem to work.

---

~~An alternative solution could be to use RuleSets in the interface validator for common properties. I.e.:~~
```c#
RuleSet("ShouldApply", () =>
{
    RuleFor(x => x.CommonPropertyExample).NotEmpty();
});
```

~~The problem was I have no way of setting whcih RuleSets it should use when doing `Include`. And unfortunately I do not have access to the `Validate` call in all cases, so I cannot add rulesets there.
So the solution here could be if I had a way to configure the validator inside of the validator, i.e. something like this in `ImportViewModelValidator` e.g.:~~
```c#
RuleFor(x => x.ShouldApply).NotEmpty();
Include(new CommonPropertiesValidator().SetOptions(options => options.IncludeRuleSets("ShouldApply")));
```

**Edit:** Oh forget that, I would need to set the rule set conditionally too, i.e. only include `ShouldApply` if `x.ShouldApply` is `true`, actually, which is not possible AFAIK.

**Additional context**
.NET Core

**Comment by JeremySkinner** [comment]
Hi, I think this should work in your case:

```csharp
When(x => x.ShouldApply, () => {
  Include(new CommonAusweisViewModelValidator());
});
```

**Comment by rklec** [comment]
Awesome, thanks. Indeed that works. Such a simple solution and it did not came to my mind, so thanks a lot!
Anyway, I'll keep this issue open, because I think a `When` clause directly after `Include` in an one-liner is a way to simplify the syntax for this feature a lot (and apparently also may make it easier to discover).

**Comment by JeremySkinner** [comment]
Exposing `When` on the Include method directly isn't currently possible without exposing all the other methods that are part of the fluent interface.

However for the 10.0 release I'm exploring making some breaking changes to the fluent interface which would allow only some methods to be exposed contextually, which would allow this to be implemented.
