### ISSUE TITLE
How do I validate multiple properties with the same rule, without showing multiple errors?

### ISSUE THREAD

**Issue by MrYossu** [FluentValidation/FluentValidation#1644]
I have a `RenewalViewModel`, which is bound to controls that allow a user to set up a renewal for an investment. Investors have a level (basic, business, corporate, etc), and within each level, a monthly amount (£100, £200, etc). These two are bound to a `SelectedLevelId` and `SelectedLevelAmountId` properties on the view model. These two are bound to two dropdowns, with the amount dropdown taking its values according to the selected level. In other words, if they choose the basic level, the amounts dropdown gets populated with the amounts for that level. If you change it to business, the amounts dropdown gets repopulated accordingly.

The model also has a `List<Shares>`, which contains an entry for each share the investor currently has, ie one `Share` object for each company they have invested in, and the `Share` object has a `Quantity` property to say how many shares they have invested in that company.

Each investor has a maximum number of shares they can be allocated, based on the level amount they are on. So, one of the things I need to validate is that the total number of shares they are being allocated does not exceed the maximum they are allowed.

I have set up a validator for this as follows (irrelevant properties removed for clarity)...

```c#
    public RenewalViewModelValidator() {
      RuleFor(rvm => rvm.SelectedLevelId).Custom((_, ctx) => ValidateShares(ctx));
      RuleFor(rvm => rvm.SelectedLevelAmountId).Custom((_, ctx) => ValidateShares(ctx));
      RuleFor(rvm => rvm.Shares).Custom((_, ctx) => ValidateShares(ctx));
    }

    private static void ValidateShares(CustomContext ctx) {
      RenewalViewModel rvm = (RenewalViewModel)ctx.InstanceToValidate;
      int investorMaxShares = rvm.LevelAmounts.Single(la => la.Id == rvm.SelectedLevelAmountId).NumberOfShares;
      if (rvm.Shares.Sum(s => s.Quantity) > investorMaxShares) {
        ctx.AddFailure($"The max shares for this investor is {investorMaxShares}");
      }
      foreach (Share share in rvm.Shares) {
        int totalSharesInCompany = share.Quantity + rvm.OtherShares.Where(os => os.CompanyId == share.CompanyId).Sum(os => os.Quantity);
        if (totalSharesInCompany > rvm.MaxSharesPerCompany) {
          ctx.AddFailure($"A total of {totalSharesInCompany} shares is now allocated to {share.Company.FullName}, which is more than the maximum of {rvm.MaxSharesPerCompany}");
        }
      }
    }
  }
```

As you can see, I pulled out the code that checks the number of shares into a method, so when the level, level amount or any of the share quantities is changed, the validation is fired.

This basically works, but has two problems...

1) As the validation is triggered from three different properties, I get the validation error three times. I only want each error once.

2) If you change the level, then the amounts dropdown is repopulated, and the first value selected. The validation is fired for the level, but not for the amount, which can lead to incorrect validation messages. If you then change the amount, the validation fires for that, but not for the level, so you can end up with inconsistent validation messages.

It could be I'm just doing this the wrong way, in which case any advice would be appreciated. If not, is there a way to get all of the validation rules fired when any of these three properties change? That way at least the messages would be correct and consistent, although I'd still end up with duplicates.

Hope that all makes sense. Thanks for any help you can give.

**Comment by JeremySkinner** [comment]
Hi, 

These features may be of use:

- Setting the cascade mode (specifically the section on setting it at the class level) so only a single failure is returned from the validator: https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode

- Validating individual properties rather than the whole model: 
```csharp
validator.Validate(model, options => {
   options.IncludeProperties("OnlyThePropertyYouWantToValidate");
});
```

- Dependent rules. This allows you to only run certain rules if a previous one succeeds: https://docs.fluentvalidation.net/en/latest/conditions.html#dependent-rules

>  If not, is there a way to get all of the validation rules fired when any of these three properties change?

I don't really know what you mean by this. All of the rules are fired when you call `Validate`, unless you explicitly specify to limit it to certain properties (see my example above)
