### ISSUE TITLE
Could not load file or assembly 'System.Web.Http, Version=5.2.4.0

### ISSUE THREAD

**Issue by mrinalkumarjha** [FluentValidation/FluentValidation#1645]
**Which version of FluentValidation are you using?**
i have installed FluentValidation.WebApi 8.6.1

**Which version of ASP.NET are you using?**
DotNet 4.7.2

**Describe the issue that you're having**
when i added  FluentValidation.WebApi.FluentValidationModelValidatorProvider.Configure(config) inside webapi.config Register method. It throws error while running application. if i comment this line it works fine.

here are exception details:

System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Web.Http, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=apitest
  StackTrace:
   at apitest.WebApiConfig.Register(HttpConfiguration config) in C:\Users\mrinalkumar\source\repos\apitest\apitest\App_Start\WebApiConfig.cs:line 28
   at System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback)
   at apitest.WebApiApplication.Application_Start() in C:\Users\mrinalkumar\source\repos\apitest\apitest\Global.asax.cs:line 17

**Comment by JeremySkinner** [comment]
Hello, this doesn't look like a problem with FluentValidation. It looks like you may have a problem with your references - please confirm which version of the ASP.NET WebApi assemblies you're referencing in your application (specifically which version of System.Web.Http)

**Comment by mrinalkumarjha** [comment]
Thanks for your quick response Jeremy.
yes visual studio was giving warning and when i clicked on that this error is fixed now. However ModelState.IsValid property is always valid even after validation is failing inside validator.  

**Validator code:**
`    public class TestValidator: AbstractValidator<TestModel>
    {
        public TestValidator()
        {
            RuleFor(a => a.id)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty()
                .WithMessage("can not empty");
            //.Length(2, 50)
            //.WithMessage(ExceptionConstants.CANDIDATE_FIRST_NAME + ExceptionConstants.IS_LONGER_THAN_MAXIMUM_LENGTH + "50")
            //.Must(ContainOnlyValidNameCharacters)
            //.WithMessage(ExceptionConstants.CANDIDATE_FIRST_NAME + ExceptionConstants.CONTAINS_INVALID_CHARACTER);


            RuleFor(a => a.Name)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty()
                .WithMessage("can not empty");


        }
    }`
    
    **Model COde**
`[Validator(typeof(TestValidator))]
    public class TestModel
    {
        public int id { get; set; }
        public string Name { get; set; }


    }`

**Controller endpoint**

`[HttpPost]
        [Route("")]
        public async Task<IHttpActionResult> postTest(TestModel model)
        {
            if (!ModelState.IsValid)
            {
                
            }
            return null;
        }`

**Comment by JeremySkinner** [comment]
You'll need to do some debugging yourself here. Override the validator's `Validate` method, put a break point in there to see if the Validate method is being called when you invoke the controller action.

**Comment by mrinalkumarjha** [comment]
Thanks worked now. validate was not being called as i was not passing model. when i passed model it worked. Thanks.
