### ISSUE TITLE
Preprocessors & Validators

### ISSUE THREAD

**Issue by SergejSachs** [FluentValidation/FluentValidation#1646]
Hi,

my API uses the cqrs pattern with fluent validation and mediatr.

I have following usecase for my service:

- client calls save controller with some input data (ids)
- controller emits command
- a validator checks if ids are bigger then 0.
- command gets executed and saves the provided ids

Now I need to get some data from a query for additional id validation.

I would like to create a preprocessor that gets the data and inject it into the command (additional parameters).
In the next step I could create a new validator or extend the old one that check this data.

The problem is that the validator runs first and only after that the preprocessor.
Is there a way to make the preprocessors run before the validation? This would be my prefered way.

I probably want to reuse the query and dont write the same logic in the command again even its not a lot.
I could aggregate the data in the controller action but and prevent calling the command or inject data into the command and let a validator do this job but both feels weird.

**Comment by JeremySkinner** [comment]
Hi, I don't really understand what you're asking. What is a preprocessor in this context? Is that something specific to mediatr ? If so then I can't help with that I'm afraid - I can only answer questions specific to FluentValidation itself.
