### ISSUE TITLE
Nullable validation with IRuleBuilderOptions

### ISSUE THREAD

**Issue by DanieleSky** [FluentValidation/FluentValidation#1657]
**Which version of FluentValidation are you using?**
Version 9.5.1

**Which version of ASP.NET are you using?**
 NET Core 3.1

**Describe the issue that you're having**
Hi,
I'm new in FluentValidation but I've a question that I haven't find solution.
To example, I have two classes:
`
public class ProfiloEntityNullable
   {
   public DateTime? LastChangePassword{ get; set; }
   }
`
and 
`
public class ProfiloEntity
   {
   public DateTime LastChangePassword{ get; set; }
   }
`

I would to check that the date inserted (if not null) is major than DateTime.Now.

To do this, I created
`
public static IRuleBuilderOptions<T, DateTime> ValidazioneDataMinima<T>(this IRuleBuilder<T, DateTime> ruleBuilder)
        {
            return ruleBuilder.GreaterThanOrEqualTo(DateTime).WithErrorCode("DateMinValue");
        }
`
called in
`public ProfiloValidator()
{
            RuleFor(p => p.DataUltimoCambioPassword).ValidazioneDataMinima();
        }`
but this solution don't work with `ProfiloEntityNullable` because the type is DateTime? and not DateTime.

If I add the When condition in RuleFor nothing changes.
The only solution that I have found is to create 
`public static IRuleBuilderOptions<T, DateTime?> ValidazioneDataMinima<T>(this IRuleBuilder<T, DateTime?> ruleBuilder)
`
with When condition inside.
But I ask: if I have a nullable objet, can I validate it only if it have value with the same rule of not nullable type?
Thanks

**Comment by JeremySkinner** [comment]
Hello, 

That’s expected. 

The generic type parameter must match the property type. If you want your custom validation method to work with both `DateTime` and `DateTime?` then you need to create two overloads of the method - one targeting the nullable version and one targeting the non-nullable version. 

This isn’t actually something that’s specific to FluentValidation but is just how generics work in c# in general.

**Comment by DanieleSky** [comment]
I understand.
I've found a way, with Transform method. But it will deprecated in version 10:
`RuleFor(p => p.LastChangePassword).Transform(p => (DateTime?)p).ValidazioneDataMinima();`

**Comment by JeremySkinner** [comment]
Yes that method is removed in 10.0. There's an updated syntax available: https://docs.fluentvalidation.net/en/latest/transform.html

However it's much cleaner to just have 2 overloads of the extension method.
