### ISSUE TITLE
SwaggerGen does not show information from rules defined on base classes 

### ISSUE THREAD

**Issue by fp-jcorriveau** [FluentValidation/FluentValidation#1660]
FluentValidation 9.5.1
.NET Core 3.1
MicroElements Swashbuckle FluentValidation 4.2.0

I'm having an issue using FluentValidation and Swashbuckle SwaggerGen to generate API documentation.
The information shown in SwaggerUI does not mark the information according to the definition of the fluent validators as it is when using DataAnnotations.

I already mentioned the issue to the MicroElements Swashbuckle FluentValidation teams, but they seem to think the error comes from FluentValidation.

Here is an example using DataAnnotations. 
With this code, SwaggerUI will mark the `Name` field of `InstitutionForCreationModel` and `InstitutionForUpdateModel` as required.
```c#
public abstract class  AbstractInstitutionModel
{
    [Required]
    public string Name { get; set; }
}

public class  InstitutionForCreationModel : AbstractInstitutionModel {}
public class  InstitutionForUpdateModel : AbstractInstitutionModel {}
```

If instead of using DataAnnations I create a fluent validator like this the field seems to be optional.
```c#
public class AbstractInstitutionModelValidator : AbstractValidator<AbstractInstitutionModel>
{
    public InstitutionModelValidator()
    {
        RuleFor(p => p.Name)
            .NotEmpty();
    }
}
```
As a workaround, I have to duplicate the rule in 2 different validators, one for each concrete class.

Here is the configuration setup I use in the startup class 
```c#
.AddFluentValidation(options =>
{
    options.RunDefaultMvcValidationAfterFluentValidationExecutes = false;
    options.RegisterValidatorsFromAssembly(callingAssembly);
})
```

**Comment by JeremySkinner** [comment]
Hello,

This issue tracker is for the core FluentValidation library. The MicroElements.Swashbuckle.FluentValidation library is not maintained here - you will need to ask the author of that library for help: https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation

**Comment by JeremySkinner** [comment]
One final thought - you will probably also need to do is ensure your container registrations are set up correctly - FluentValidation's `RegisterValidatorsFromAssembly` method will locate your `AbstractInstitutionModelValidator` and register it with the container as `IValidator<AbstractInstitutionModel>`.

You will also probably need to set up explicit container registrations for `IValidator<InstitutionForCreationModel>` and `IValidator<InstitutionForUpdateModel>` as that won't be done automatically.

**Comment by JeremySkinner** [comment]
Further to the above, if you set up validators explicitly for those subclasses then the registrations will be handled for you automatically. You don't have to duplicate the rules though - you can either use inheritance or composition. 

Inheritance example:

```csharp
public abstract class AbstractInstitutionModelValidator<T> : AbstractValidator<T> where T : AbstractInstitutionModel
{
    public InstitutionModelValidator()
    {
        RuleFor(p => p.Name)
            .NotEmpty();
    }
}

public class InstitutionForCreationModelValidator : AbstractInstitutionModelValidator<InstitutionForCreationModel> 
{
   public  InstitutionForCreationModelValidator() 
   {
       // Define any subclass-specific rules here.
   }
}
```

Composition example:

```csharp
public class AbstractInstitutionModelValidator : AbstractValidator<AbstractInstitutionModel>
{
    public InstitutionModelValidator()
    {
        RuleFor(p => p.Name).NotEmpty();
    }
}

public class InstitutionForCreationModelValidator : AbstractInstitutionModelValidator<InstitutionForCreationModel> 
{
   public  InstitutionForCreationModelValidator() 
   {
       Include(new AbstractInstitutionModelValidator());
       // Define any subclass-specific rules here.
   }
}
```

Either way, I expect you need some way of mapping the subclass types to a specific validator.

**Comment by fp-jcorriveau** [comment]
That's something I don't have to take care of with DataAnnotation, that might be why the confusion.
Thanks for your answer, it is clear.

**Comment by JeremySkinner** [comment]
Yes, that's because DataAnnotations defines the rules in the models themselves, so there's no separate class hierarchy you have to set up. With FluentValidation as the rules are in separate classes, you need to set things up so the container knows how to resolve a validator for each specific type.
