### ISSUE TITLE
Pass custom state from predicate validator body

### ISSUE THREAD

**Issue by h15ter** [FluentValidation/FluentValidation#1661]
I often need to add some contextual information from predicate validator body. I can achieve that by writing a custom validator, which accepts `CustomContext` so I can construct a new `ValidationFailure` object and pass it to `AddFailure()` method, but it nullifies all the beauty of fluent approach. 
Ideally I'd like to be able to set custom state on the PropertyValidatorContext object passed to the predicate.

```
    public class DeleteEntityValidator : AbstractValidator<DeleteEntityCommand>
    {
        private readonly IEntityUsageQuery _usageQuery;

        public DeleteEntityValidator(IEntityUsageQuery usageQuery)
        {
            _usageQuery = usageQuery;

            RuleFor(command => command.EntityId).MustAsync(ShouldNotBeInUse);
        }

        private async Task<bool> ShouldNotBeInUse(DeleteEntityCommand command, long id, PropertyValidatorContext context, CancellationToken token)
        {
            var usedBy = await _usageQuery.GetUsedBy(id, token);

            // todo: pass usedBy as custom state to the property validator context, like this:
            // context.SetCustomState(new {usedBy}); 

            return !usedBy.Any();
        }
    }
```

**Comment by JeremySkinner** [comment]
That’s a good idea. I’ll look at getting it added for the next release, although it might need to wait until 10.1 as I’m currently finishing up the 10.0 release. 

Just a heads up that in 10.0 some of these method signatures will need to be updated as non-generic contexts (such as PropertyValidatorContext) have been replaced with generic versions. 

I’ll post an update here once this has been implemented.
