### ISSUE TITLE
Web Api Action Filters Do Not Run

### ISSUE THREAD

**Issue by terryaney** [FluentValidation/FluentValidation#1667]
FluentValidation: 9.5.0
ASP.NET: 5.0

When I have my own action filters in a Web Api controller, if I am using FluentValidation, the filters do not execute.

Given the following filter:

```
public class MyActionFilter : IActionFilter
{
	public MyActionFilter()
	{
		System.Diagnostics.Trace.WriteLine( "ctor" );
	}

	public void OnActionExecuting( ActionExecutingContext context )
	{
		System.Diagnostics.Trace.WriteLine( "OnActionExecuting" );
	}

	public void OnActionExecuted( ActionExecutedContext context ) 
	{
		System.Diagnostics.Trace.WriteLine( "OnActionExecuted" );
	}
}
```

If I configure my builder as the following:

```
builder
	.AddControllers()
	.AddMvcOptions( opt =>
	{
		opt.Filters.Add( typeof( MyActionFilter ) );
	} )
	.AddFluentValidation( cfg =>
	{
		cfg.RegisterValidatorsFromAssemblyContaining<TValidatorsAssembly>();
	} );
```

The following occurs:
1. The MyActionFilter.ctor is successfully called.
2. Neither of the `OnAction*` methods are called.
3. The web api result is a `ValidationProblemDetails` with correct FluentValidation error messages returned.

If I remove the call to `AddFluentValidation`, then I **do** successfully hit the `OnAction*` methods.

If I try this same pattern for my Razor Pages using an `IPageFilter` (still using `AddFluentValidation`), then the `OnPageHandlerExecuting` **is** successfully called.

Is this a bug in FluentValidation or am I misunderstanding how the flow should work for web api actions?

**Comment by JeremySkinner** [comment]
This doesn't sound like it's related to FluentValidation. 

When you call `AddFluentValidation`, an additional `ModelValidatorProvider` and an additional `ObjectModelValidator` are inserted into the pipeline - that's all. We don't do anything that affects action filters. 

You can see here exactly what calling AddFluentValidation does: https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L77

I'd suggest you start debugging this by creating a small, minimal sample project that attempts to reproduce the issue.

**Comment by JeremySkinner** [comment]
Also double check whether you're using the [`[ApiController]` attribute](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#automatic-http-400-responses) in your controllers. This attribute will prevent both the action method and action filters from running if validation fails (note that this is a feature of ASP.NET, it's not related to FluentValidation)

**Comment by terryaney** [comment]
I am using `ApiController`.  Thought that was a requirement in creating Web Apis?  Is there a work around so that filters continue to execute?

**Comment by JeremySkinner** [comment]
> Thought that was a requirement in creating Web Apis

No, it isn't required. It's a shortcut that enables a certain set of conventions. 

> Is there a work around so that filters continue to execute?

You'd have to disable the automatic 400 responses and switch to returning them manually (or use a different filter type). The ASP.NET documentation explains how to do this. https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#disable-automatic-400-response I'd also suggest reading the rest of that page, as it explains exactly what the ApiController attribute does.

I'm going to close the issue now as it isn't related to FluentValidation.

**Comment by JeremySkinner** [comment]
I'd also suggest reading up on how filters work in ASP.NET: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0 This page explains how one filter can be used to cancel the execution of all others (which is what ApiController is doing - see the section on "Cancellation and short-circuiting")
