### ISSUE TITLE
FluentValidation not working for HTTP GET method argument

### ISSUE THREAD

**Issue by f90fe** [FluentValidation/FluentValidation#1669]
**Which version of FluentValidation are you using?**
FluentValidation 9.5.1

**Which version of ASP.NET are you using?**
NET Core 3.1

**Describe the issue that you're having**
I am working on a web API with ASP.NET Core. I have a GET method getting resource by Id as below. However the validator on DTO object doesn't work. Irrespective of whether I register validators during startup or explicitly calling ValidateAndThrow like I have shown in the code snippet below. If I put an empty id, I am getting a NOT found error instead of a Bad Request(configured in error controller for fluent validation exception).

```
        [HttpGet]
        [Route("abc/{id}")]
        [ActionName(nameof(GetByID))]
        [ProducesResponseType(typeof(ResponseObj), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ErrorObj), StatusCodes.Status404NotFound)]
        public async Task<IActionResult> GetByID([FromRoute] DtoClass dto)
        {
            DtoClassValidator idDto = new DtoClassValidator();
            idDto.ValidateAndThrow(dto);
            ResponseObj responseObj = await this.service.GetByID(dto.id).ConfigureAwait(false);
            return this.Ok(responseObj );
        }

       public class DtoClass 
       {
          
          [FromRoute(Name = "id")]
          public string Id{ get; set; }
       }

      public class DtoClassValidator : AbstractValidator<DtoClass>
      {
          public DtoClassValidator ()
          {
              this.CascadeMode = CascadeMode.Stop;
  
              this.RuleFor(dto => dto.Id)
              .NotEmpty()
              .NotNull()
              .WithMessage("id must be non-empty.");
          }
      }
```

Other than this I have tried registering validator in startup as follow, but that didn't help either.

```        
            services.AddMvcCore(options =>
            {
               ......
            }).AddFluentValidation(fv =>
            {
                // Registers all validators from WebApi project.
                fv.RegisterValidatorsFromAssembly(Assembly.GetExecutingAssembly());
           });
```

Validator for Create method is working fine. So I am confused, is the validation on GET method not supported or I am missing some configuration or is it a bug?

Let me know if you need more information.

Thanks in Advance.

Cheers,
Manish
PS I understand it might be a overkill to create a DTO class just for string. But I was just exploring fluent validation.

**Comment by JeremySkinner** [comment]
This is nothing to do with FluentValidation.

Your route is defined as "abc/{id}". This makes the {id} parameter required, so the controller action can never be invoked without an id parameter. Your validator checks that an ID is specified, which will always be the case. If your route was defined as "abc/{id?}" then it would perform as you expect. [The ASP.NET documentation explains how optional route parameters work.](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)

Unrelated, you don't need both NotNull and NotEmpty in your validator. [NotEmpty also performs a null check.](https://docs.fluentvalidation.net/en/latest/built-in-validators.html#notempty-validator)
