### ISSUE TITLE
Accessing parent class

### ISSUE THREAD

**Issue by ianvink** [FluentValidation/FluentValidation#1670]
Newbie. This is a truly wonderful project, thank you for your efforts.

I have a validation that ensures the Order's Total Sale is above $0. In the error message I need to include the Order ID in the message.

Something like this

        RuleForEach(x => x.Orders).ChildRules(order =>
        {
            order.RuleFor(x => x.TotalSale)
                      .GreaterThan(0)
                      .WithMessage($"{order.orderId}: Total Sales must be greater than $0");

How do I access the "order.OrderId" inside the validation?

**Comment by JeremySkinner** [comment]
```csharp
 order.RuleFor(x => x.TotalSale)
                  .GreaterThan(0)
                  .WithMessage(o => $"{o.orderId}: Total Sales must be greater than $0");
```

This is covered in the documentation: https://docs.fluentvalidation.net/en/latest/configuring.html#placeholders
