### ISSUE TITLE
Documentation about ValidationResult is missing

### ISSUE THREAD

**Issue by jan-johansson-mr** [FluentValidation/FluentValidation#1671]
`ValidationResult` is kind of central when validating, e.g. the result, the message, the property name and so on, but the type is only mentioned briefly in some sections. It would be great to learn more about `ValidationResult` and how it relates to the validation outcome, e.g. how the property name is built and semantical context to that and so on.

Thanks

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. If you'd like to submit a pull request that adds this, that would be great.

**Comment by jan-johansson-mr** [comment]
Oh, that's great! I'll see if I have time this weekend to start something, I'll look at the source some and see if I understand how it works. Thanks!
