### ISSUE TITLE
Conditional transforms

### ISSUE THREAD

**Issue by mvestergaard** [FluentValidation/FluentValidation#1672]
**Is your feature request related to a problem? Please describe.**
The upcoming changes to Transform in v10 poses some problems for us. In particular that it's no longer possible to easily combine a condition with a transform.
We currently have these extension methods to easily work with nullable values. Basically, if the value is null, don't validate the property:
```cs
public static IRuleBuilderInitial<T, TValue> WithNonNullCondition<T, TValue>(this IRuleBuilderInitial<T, TValue> rule)
    => rule.Configure(r => r.ApplySharedCondition(c => r.PropertyFunc(c.InstanceToValidate) is not null));

public static IRuleBuilder<T, TValue> WhenNotNull<T, TValue>(this IRuleBuilderInitial<T, TValue?> rule)
    where TValue : class
    => rule.WithNonNullCondition().Transform(value => value!);

public static IRuleBuilder<T, TValue> WhenNotNull<T, TValue>(this IRuleBuilderInitial<T, TValue?> rule)
    where TValue : struct
    => rule.WithNonNullCondition().Transform(value => value!.Value);
```
That's no longer doable with the new approach.

The other aspect of this problem is that it's no longer possible to do this type of stuff as an extension method, because they are now protected methods on AbstractValidator. This makes it a bit hard to make custom extensions that don't require usage of a different base class (which is doable, but requires some education of developers)

**Describe the solution you'd like**
Some way to only apply the rule if some condition is met.

**Describe alternatives you've considered**
Tried implementing as extension method on new API, but does not seem possible.

**Comment by JeremySkinner** [comment]
Hi, would you be able to provide some more details of your use case and how you're making use of these methods? That'll help me to better understand the intent and whether there's something I can build into the library to make this easier. 

> The other aspect of this problem is that it's no longer possible to do this type of stuff as an extension method, because they are now protected methods on AbstractValidator

Hmm yes that's a good point. Validators should be immutable and I was trying to enforce this by removing the public methods but you're right, this does cause issues with not being able to use extension methods on the validator directly. I may decide to revert this, let me have a think about it.

Generally if you did need to do this, then you'd define it like this:

```csharp
When(x => x.SomeProperty != null, () => {
   Transform(x => x.SomeProperty, x.SomeProperty.Value).Whatever();
});
```

If I made the methods on AbstractValidator public again, then you'd be able to define an extension method on AbstractValidator like this, that does the same thing:

```csharp
public static IRuleBuilder<T, TValue> WhenNotNull<T, TValue>(this InlineValidator<T> validator, Expression<Func<T, TValue?>> expr)
	where TValue : class {

	var func = expr.Compile();

	return validator
		.Transform(expr, value => value!)
		.Configure(r => {
			r.ApplySharedCondition(context => func(context.InstanceToValidate) != null);
		});
}
```

Would that work for you?

**Comment by mvestergaard** [comment]
Here's an example of the usage of the current extension method:
```cs
this.RuleFor(x => x.DateOfBirth).WhenNotNull().GreaterThan(Value.EmptyDate).LessThan(DateTime.Today);
```

So basically, giving the date of birth is optional. If it's null, we don't care, but if it isn't, the rules should apply.

The extension method you suggest would probably work for this nullable scenario, but we use it for something else as well, which I left out to not complicate things too much.
We basically in our API have the ability to do patches, which means we need to ability to know if a property was assigned or not. Think of it like having undefined in javascript. To do this we have `Maybe<T>` which reflects whether the value was assigned or not. When assigned, it could even be assigned to null.

For that scenario we have this extension method:
```cs
public static IRuleBuilder<T, TValue> WhenAssigned<T, TValue>(this IRuleBuilderInitial<T, Maybe<TValue>> rule)
{
    return rule
        .Configure(r => r.ApplySharedCondition(c => ((IMaybe)r.PropertyFunc(c.InstanceToValidate)).HasValue))
        .Transform(value => value.Value!);
}
```

Perhaps your suggestion above for the nullable scenario could work for that too. Depends what the value of `context.InstanceToValidate` is. Is it the actual value of the property, or is it the value after the transform?

**Comment by mvestergaard** [comment]
In regards to the usage of `When`. We use these extension methods in like 150-200 places, so having to define this `When` condition all of the place would be very cumbersome.

**Comment by mvestergaard** [comment]
Gave it a shot on the latest v9, and it seems to work, when `Transform` is not protected:
```cs
public static IRuleBuilderInitial<T, TProperty> WhenAssigned<T, TProperty>(this AbstractValidator<T> validator, Expression<Func<T, Maybe<TProperty>>> expression)
{
    var func = expression.Compile();
    return validator.Transform(expression, value => value.Value!)
        .Configure(r => r.ApplySharedCondition(context => func((T)context.InstanceToValidate).HasValue));
}
```

Compiling the expression is a bit concerning performance wise. Is there some kind of cache in FV that can help with that?

**Comment by JeremySkinner** [comment]
Thanks for the example, that makes sense. Moving to having generics throughout the core model means it is no longer possible to change the type the rule acts upon once the rule has been created (which is why Transform is now a top-level method), so this definitely will require you to take a slightly different approach. 

> Perhaps your suggestion above for the nullable scenario could work for that too. 

Yes, the approach would be the same

> Nevermind that last bit. context.InstanceToValidate would be the T value I suppose.

Yes, `InstanceToValidate` is the root model passed into the validator. 

> Compiling the expression is a bit concerning performance wise. Is there some kind of cache in FV that can help with that?

Yes, we have the [AccessorCache](https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Internal/AccessorCache.cs), which is currently internal but I think this is a good enough reason to make it public. That being said, expression tree compilation is significantly cheaper in modern versions of .net core than it used to be.

**Comment by mvestergaard** [comment]
Yea found the AccessorCache
```cs
public static IRuleBuilderInitial<T, TProperty> WhenAssigned<T, TProperty>(this AbstractValidator<T> validator, Expression<Func<T, Maybe<TProperty>>> expression)
{
    var member = expression.GetMember();
    var func = AccessorCache<T>.GetCachedAccessor(member, expression);
    return validator
        .Transform(expression, value => value.Value!)
        .Configure(r => r.ApplySharedCondition(context => func((T)context.InstanceToValidate).HasValue));
}
```
I believe that should work. In which case I'm okay with not doing more than making these things public (they already are on v9).

**Comment by JeremySkinner** [comment]
I've pushed out a 10.0-preview3 which should make the necessary classes and methods public again. It should show up in the nuget feed shortly. Please feel free to give it a try and let me know if you run into any problems.

**Comment by mvestergaard** [comment]
Awesome, thanks Jeremy, will check it out.

**Comment by mvestergaard** [comment]
Got everything up and running, and tests are now passing with FV 10.0.0-preview3. Closing this one :)
