### ISSUE TITLE
Enable configuration via delegation

### ISSUE THREAD

**Issue by jan-johansson-mr** [FluentValidation/FluentValidation#1675]
Configuration (rules etc.) are available when inheriting from `AbstractValidator<T>`, and therefore it's natural that configuration is done in the constructor of the inheritor. This however locks down the behavior of the validator to one type per inheritance. If I want to lock down a certain behavior but spread the behavior throughout different types, I can not do so by declaring `MyValidator<T> : AbstractValidator<T>`, since each T may have different set of properties and the configuration is confined to constructor of `MyValidator<T>`.

One approach to enable locking down behavior but not type is to unlock configuration via making a configurator object available when constructing the validator, e.g.

```
var myValidator = new MyValidator<MyType>(configuration => configuration.RuleFor(instance => instance.property).NotEmpty());
```

**Comment by JeremySkinner** [comment]
This isn’t something that we’d include in the library as the intention is that rules should be defined in the constructor. That being said, there’s nothing stopping you from doing it this way in your own projects if you want to.  

As an aside, when opening issues please fill in the issue template in the format requested.

**Comment by jan-johansson-mr** [comment]
Thanks, that worked great!
