### ISSUE TITLE
What's the correct way to validate nested property in WPF?

### ISSUE THREAD

**Issue by GF-Huang** [FluentValidation/FluentValidation#1676]
**Which version of FluentValidation are you using?**
9.5.3

**Which version of ASP.NET are you using?**
WPF .NET 5

**Describe the issue that you're having**
I had read the docs: https://docs.fluentvalidation.net/en/latest/start.html#complex-properties, but if the `Address` class which in that docs does not implements `IDataErrorInfo/INotifyDataErrorInfo` interface, the UI element which it bounds will not get the red border around it when validation failed.

The demo code describe the issue:
[ValidationDemo.zip](https://github.com/FluentValidation/FluentValidation/files/6197987/ValidationDemo.zip)

You will not get the red border of first textbox even if it's validate failed.

![image](https://user-images.githubusercontent.com/4510984/112327523-75b88a00-8cf0-11eb-9842-9add9823cf97.png)

**Comment by JeremySkinner** [comment]
Hi, this isn’t something I can really help with. 

FluentValidation is just a library for validating the properties of object graphs. It has nothing to do with WPF directly. How you choose to use it within a WPF project is up to you. 

If using nested validators is not appropriate for your situation and you wish to use `INotifyDataErrorInfo` to wire things up then there’s nothing stopping you from doing this.

**Comment by GF-Huang** [comment]
Sorry, I want to open a discussion but FluentValidation repo does not open this feature.

**Comment by JeremySkinner** [comment]
I don’t provide discussions on this repo; it is only for issues.
