### ISSUE TITLE
Allow Camel-Case property names when writing ValidationResults to ASP.NET Core Model State Dictionary

### ISSUE THREAD

**Issue by feO2x** [FluentValidation/FluentValidation#1679]
When using FluentValidation with ASP.NET Core, the resulting response always contains the names of erroneous properties as they were defined in the corresponding DTO class (PascalCase or UpperCamelCase). I think it would be in the best interest to allow the property names to be formatted differently, as many client technologies that call ASP.NET Core web services use lowerCamelCase by default. This is also the default setting for the JSON serializers (for both System.Text.Json as well as Newtonsoft.Json) - I would argue that clients expect all identifiers to be formatted in lowerCamelCase.

Currently all responses look like this by default:

![error property names use same casing as property name](https://user-images.githubusercontent.com/7884158/112855414-0e635700-90af-11eb-810e-bd3f64ba2b2a.png)

I think the easiest way to achieve this is to add an overload to `AddModelState` that takes an additional enum value describing the desired property formatting:

```csharp
var validationResult = validator.Validate(dto); // the property names of DTO are defined in PascalCase (the default casing in C#)
validationResult.AddToModelState(controller.ModelState, null, PropertyNameFormatting.LowerCamelCase);
```

There currently is a workaround by iterating over all errors and manually adjusting the property name, like so:

```csharp
var validationResult = validator.Validate(dto);
for (var i = 0; i < validationResult.Errors.Count; i++)
{
    var error = validationResult.Errors[i];
    error.PropertyName = error.PropertyName.LowerFirstCharacterIfNecessary();
}
validationResult.AddToModelState(controller.ModelState, null);
```

I still think this would be a nice feature for callers. What do you think about it?

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. I don't feel this is a common enough requirement that we'd build it in to `AddToModelState`, especially as ASP.NET's own built-in validation doesn't support this either. But you can easily add this as an extension method within your own project if you need it.  

Alternatively you can adjust the property names inside the validator itself (by calling `OverridePropertyName` as part of your rule definition) or globally by setting `ValidatorOptions.Global.PropertyNameResolver`
