### ISSUE TITLE
Dynamic creation of validator instance and see the validation rules

### ISSUE THREAD

**Issue by kurkoc** [FluentValidation/FluentValidation#1680]
hey everyone;

i want to taking the type name as a parameter as a string; then dynamically create the validator object, finally I want to see the validation rules of this object.

`object validator = Activator.CreateInstance(validatorType);`
`var validatorInstance = (IValidator)validator;`

Is there any way you can do this? Maybe a property like validatorInstance.Validators, can help but unfortunately it doesn't exist.

**Comment by JeremySkinner** [comment]
Hi, you'll need to use an IoC container or the [.NET Service Provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0) to do this.

**Comment by kurkoc** [comment]
First of all, I apologize for deleting the issue template. Yes, i can get the validator instance from service provider but it stills dynamic type. I have to cast it to a type that comes as a string parameter.

`serviceProvider.GetService(validatorType);` //still dynamic
`serviceProvider.GetService<T>();` // where T is indefinite

Maybe I'm missing something and should approach from a different place

**Comment by JeremySkinner** [comment]
Yes, it'll be dynamic and you'll need to cast it. There's no way around that.

**Comment by kurkoc** [comment]
IValidator doesn't have Validations or something like that. I'm sorry about that :(  Thanks for help

**Comment by JeremySkinner** [comment]
It has the `CreateDescriptor()` method - you need to call this, which will give you a descriptor back. From this you can get the rules for specific members.

**Comment by kurkoc** [comment]
ovv poor me, i haven't seen this. Jeremy, thanks for your patience and quick help.
