### ISSUE TITLE
[Question] context.Rule.MessageBuilder from V9 to V10 upgrade

### ISSUE THREAD

**Issue by MattJeanes** [FluentValidation/FluentValidation#1684]
### FluentValidation version

10.0.0

### ASP.NET version

.NET 5

### Summary

Given the example code below, I am not sure how to appropriately upgrade the syntax to V10. I have read through the upgrade guide but I can't see:
  1. How to not call the validator again (which in my case is a database call)
  2. How to have an essentially async error message

Previously we just set the `context.Rule.MessageBuilder` and do it all in one hit but now `context.Rule` does not exist I am not sure how to do this.

```csharp
namespace MyCompany.Validation
{
    public class ExampleValidator : AbstractValidator<ExampleViewModel>
    {
        public ExampleValidator(IExampleService exampleService)
        { 
            RuleFor(x => x.ExampleProperty)
                .MustAsync(async (x, someOtherId, context, cancellationToken) => {
                    var result = await exampleService.IsValidAsync(x.Id, someOtherId, cancellationToken);
                    context.Rule.MessageBuilder = m => result.ErrorMessage;
                    return result.Valid;
                });
        }
    }
}
```

**Comment by JeremySkinner** [comment]
Hi, 

You should use `CustomAsync` for this (see [the docs](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator))

```csharp
RuleFor(x => x.ExampleProperty).CustomAsync(async (propertyValue, context, cancellationToken) => {
   var result = await exampleService.IsValidAsync(context.InstanceToValidate.Id, propertyValue, cancellationToken);
   if (!result.Valid) {
     context.AddFailure(result.ErrorMessage);
  }
});
```

A `MessageBuilder` should only ever be set as a call to Configure (eg `RuleFor(x => x.Foo).Whatever().Configure(rule => rule.MessageBuilder = ...)`. It should never be set inside a call to `Must` - this is not thread safe. If you have any code using FluentValidation 9.x that still does this I would highly suggest you update it to remove this usage when you can.

**Comment by MattJeanes** [comment]
That's great, thank you very much!
