### ISSUE TITLE
Please add ErrorCode (or GetErrorCode) to IRuleComponent

### ISSUE THREAD

**Issue by jornhd** [FluentValidation/FluentValidation#1690]
### Is your feature request related to a problem? Please describe.

We are using Swagger as our API documentation, and have created an operation filter to describe all possible validation messages for each method.
From the `validator.CreateDescriptor()` we go through members in `GetMembersWithValidators()`, and then for each member, `GetRulesForMember(member.Key)`, and finally for each rule `rule.Components` (incluing DependentRules.Components).
From the component we get the error message with `component.GetUnformattedErrorMessage()`, but we also need to get the ErrorCode for the documentation. As this is not exposed by the interface, we have no other choice than to use reflection: `component.GetType().GetProperty(nameof(RuleComponent<object, object>.ErrorCode))?.GetValue(component)`.

### Describe the solution you'd like

It would be great if you consider to add GetErrorCode() method, or ErrorCode property getter, to IRuleComponent.

**Comment by JeremySkinner** [comment]
Hi, I've pushed out a 10.0.2 release to nuget which now exposes `ErrorCode` on `IRuleComponent`. This was actually supposed to be in 10.0 but it got missed.
