### ISSUE TITLE
v10 breaking changes, need to rewrite my shared validator

### ISSUE THREAD

**Issue by zoinkydoink** [FluentValidation/FluentValidation#1691]
### FluentValidation version

10

### Summary

I have the following code
```
   RuleFor(x => x.Quarter)
          .NotEmpty()
          .InclusiveBetween(1, 4)
          .WithMessage("Quarter must be between 1 and 4")
          .Must((d, _, context) => ValidationHelper.ValidateQuarter(d.Quarter, d.Year, context))
          .When(x => x.DateType ==  DateTypes.Quarter);
```

Accompanied by 
```
public static bool ValidateQuarter(int? quarter, int? year, PropertyValidatorContext context)
{
    var currentQuarter = EventModelHelper.GetDateQuarter(DateTimeOffset.Now);
    if (quarter >= currentQuarter && year >= DateTimeOffset.Now.Year || year > DateTimeOffset.Now.Year) return true;
    if (!year.HasValue)
        context.Rule.MessageBuilder = _ => "Select a year first";
    else
        context.Rule.MessageBuilder = _ => "Quarter cannot be in the past";
    return false;
}
```

Which no longer works in v10, wondering how to rewrite it so I can continue doing what i need, in this case I need to use 2 properties of the object in order to validate one.

Thank you

**Comment by JeremySkinner** [comment]
Hi,

A `MessageBuilder` is not intended to be set as part of a call to `Must` (as part of `Configure`). This is *not* thread-safe, and was actually a bug in v9 that allowed this. 

You should use `Custom`, which allows you to add your own messages as part of the callback. [Please see the docs](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator) 

```csharp
  RuleFor(x => x.Quarter)
          .NotEmpty()
          .InclusiveBetween(1, 4)
          .WithMessage("Quarter must be between 1 and 4")
          .Custom((quarter, context) => {
              var year = context.InstanceToValidate.Year;
              var currentQuarter = EventModelHelper.GetDateQuarter(DateTimeOffset.Now);
              if (quarter >= currentQuarter && year >= DateTimeOffset.Now.Year || year > DateTimeOffset.Now.Year) return;
              if (!year.HasValue)
                context.AddFailure("Select a year first");
               else
               context.AddFailure("Quarter cannot be in the past");
           });
          .Must((d, _, context) => ValidationHelper.ValidateQuarter(d.Quarter, d.Year, context))
          .When(x => x.DateType ==  DateTypes.Quarter);
```

Or you can extract this to an extension method to clean it up (see the docs link I posted)

**Comment by zoinkydoink** [comment]
Thank you, what happens if i want to make that code for validation reusable across multiple validators, instead of copy and paste?

**Comment by JeremySkinner** [comment]
Hi, you should extract it to an extension method (please see the link in the docs I posted)

**Comment by zoinkydoink** [comment]
thank you, that solved my one problem, how do i solve the following? as per recommendation of using `PropertyValidator<T, TProperty>`, I created the following

```
 public class UriValidator<T, TProperty> : PropertyValidator<T, TProperty>
    {
        public override string Name => "UriValidator";

        public override bool IsValid(ValidationContext<T> context, TProperty url)
        {
            return Uri.TryCreate(url.ToString(), UriKind.Absolute, out var uriResult) &&
                           (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);

        }
        protected override string GetDefaultMessageTemplate(string errorCode)
            => "'{PropertyName}' must be a valid url";
    }

```
And I am calling it with the following
```
 RuleFor(c => c.Url)
                .NotEmpty()
                .SetValidator(new UriValidator<CreateLinkCommand, string>());
```
I would imagine that it should never get to the Uri validation part when Url is null/empty so it should short-circuit? base don the NotEmpty() condition

Maybe I got this whole thing wrong, also adding more built in validation is bad but I think a separate library can be added that just adds more built in validators, Url being one of them.

**Comment by JeremySkinner** [comment]
No, that's not how it works - this won't short circuit. All parts of a rule chain are always executed, unless you [set the cascade mode](https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode)

**Comment by zoinkydoink** [comment]
perfect, added CascadeMode.Stop and we golden, thanks for your hlep

**Comment by JeremySkinner** [comment]
Also, your custom validator should probably shouldn't leave the `TProperty` generic open - if this is only ever going to be usedon strings, then its better to constrain it by inheriting from `PropertyValidator<T, string>` instead.
