### ISSUE TITLE
Why Fulent api validaiton slow for 20k records ?

### ISSUE THREAD

**Issue by AryanVerma** [FluentValidation/FluentValidation#1693]
### FluentValidation version

FluentValidation.8.5.0

### ASP.NET version

4.7

### Summary

 public void SetupStartRules()
        {
            RuleForEach(a => a).Custom(ValidateItem);
           
        }
        private static void ValidateItem(ExtSalesOrder rowItem, CustomContext context)
        {
            ValidateSalesOrderName(rowItem, context);
            ValidateDesc(rowItem, context);
            ValidateSourceSystemId(rowItem, context);
            ValidateSourceSystemName(rowItem, context);
        }
I have 20k records in list. Why its fast first time and second time call its slow taking almost 12 min. I tried even with parallel loop be defining single item.

2nd Approach. This one also slow.
private static ValidationResult ValidateSalesOrderRowItemExtCollectionV4(List<ExtSalesOrder> rowItem, Dictionary<string, object> contextInfo)
        {
            AppInsightsRuntime.TelemetryClient.TrackTrace($"Start ValidateSalesOrderRowItemExtCollectionV4 Start", Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical);

            Stopwatch sw = Stopwatch.StartNew();
            ValidationResult validationResult = new ValidationResult();
            Parallel.ForEach(rowItem, new ParallelOptions() { MaxDegreeOfParallelism = 65 }, (item) =>
            {
                ValidateSalesOrderItem(item, contextInfo, ref validationResult);
            });
            sw.Stop();
            AppInsightsRuntime.TelemetryClient.TrackTrace($"Start ValidateSalesOrderRowItemExtCollectionV4 Complete : {sw.ElapsedMilliseconds} ", Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical);

            return validationResult;
        }

**Comment by JeremySkinner** [comment]
You haven't provided any steps to be able to reproduce the problem, so I have no way of helping you. Please provide a sample project that reproduces the issue, ideally in the form of a unit test. 

As I also mentioned in the other issue you opened, FluentValidation 8.5.0 is an *old and unsupported version*. Many performance improvements have been made in 10.0, which is the latest release. Please try with 10.0 and see if that makes a difference.

**Comment by AryanVerma** [comment]
private static ValidationResult ValidateSalesOrderRowItemExtCollectionV4(List<ExtSalesOrder> rowItem )
        {
          

            Stopwatch sw = Stopwatch.StartNew();
            ValidationResult validationResult = new ValidationResult();
            Parallel.ForEach(rowItem, new ParallelOptions() { MaxDegreeOfParallelism = 65 }, (item) =>
            {
                ValidateSalesOrderItem(item,   ref validationResult);
            });
            sw.Stop();
            


            r



private static void ValidateSalesOrderItem(ExtSalesOrder rowItem,  ref ValidationResult validationResult)
        {
            IEnumerable<SalesOrder> salesOrderList = (IEnumerable<SalesOrder>)context["SalesOrderList"];
            if (string.IsNullOrEmpty(rowItem.SalesOrder) || rowItem.SalesOrder == null)
            {
                rowItem.SalesOrder = string.Empty;
                validationResult.Errors.Add(new ValidationFailure("Name", nameof(ControlServices.SOExtImpValidationNameRequired), rowItem));
            }
            if ((!string.IsNullOrEmpty(rowItem.SalesOrder) || rowItem.SalesOrder != null) && rowItem.SalesOrder.Length > 50)
            {
                validationResult.Errors.Add(new ValidationFailure("Name", string.Format("{0}_{1}", nameof(ControlServices.SOExtImpValidationNameLength), Guid.NewGuid().ToString()), rowItem));

            }
           
            
            if ((!string.IsNullOrEmpty(rowItem.Description) || rowItem.Description != null) && rowItem.Description.Length > 250)
            {
                validationResult.Errors.Add(new ValidationFailure("Description", string.Format("{0}_{1}", nameof(ControlServices.SOExtImpValidationDescLength), Guid.NewGuid().ToString()), rowItem));

            }

            if (!string.IsNullOrEmpty(rowItem.SourceSystemId) && rowItem.SourceSystemId != null && rowItem.SourceSystemId.Length > 50)
            {
                validationResult.Errors.Add(new ValidationFailure("SourceSystemId", string.Format("{0}_{1}", nameof(ControlServices.SOExtImpValidationSourceSystemIdLength), Guid.NewGuid().ToString()), rowItem));
            }

            if ((!string.IsNullOrEmpty(rowItem.SourceSystemName) || rowItem.SourceSystemName != null) && rowItem.SourceSystemName.Length > 100)
            {
                validationResult.Errors.Add(new ValidationFailure("SourceSystemName", string.Format("{0}_{1}", nameof(ControlServices.SOExtImpValidationSourceSystemNameLength), Guid.NewGuid().ToString()), rowItem));

            }
        }

Why this its slow in this way. It took 12 min on second call. But in first call take hardly less than a 1 min

**Comment by AryanVerma** [comment]
We can not use updated version still. I want to achieve it in this version only.

**Comment by JeremySkinner** [comment]
This code isn't runnable. If you're not able to produce a *runnable sample project* that reproduces the problem I'm going to close this issue.

**Comment by AryanVerma** [comment]
ValidateSalesOrderRowItemExtCollectionV4 method can work for you. Just pass 20k list of items with following type of class and properties.
 public class ExtSalesOrder
    {
        public ExtSalesOrder() { }

        /// <summary>
        ///  SalesOrder Name
        /// </summary>    
        [System.ComponentModel.DefaultValue("")]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public string SalesOrder { get; set; } = "";
        /// <summary>
        ///  SourceSystemId
        /// </summary>
        [System.ComponentModel.DefaultValue("")]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public string SourceSystemId { get; set; } = "";
        /// <summary>
        ///  SourceSystemName
        /// </summary>
        [System.ComponentModel.DefaultValue("")]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public string SourceSystemName { get; set; } = "";
        /// <summary>
        /// Description
        /// </summary>
        [System.ComponentModel.DefaultValue("")]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public string Description { get; set; } = "";

        #region  NonMap field

        [System.ComponentModel.DefaultValue(0)]
        public int RowId { get; set; }

        [System.ComponentModel.DefaultValue("No")]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public string MatchKey { get; set; }

        [System.ComponentModel.DefaultValue(0)]
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
        public long SalesOrderId { get; set; }

        [JsonProperty("ProjectInfo", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<long, string> ProjectInfo { get; set; } = new Dictionary<long, string>();
           #endregion


    }

**Comment by JeremySkinner** [comment]
I've asked you several time now to provide a *runnable sample project* and you still haven't done so.
