### ISSUE TITLE
Remove single quotes in Property Name 

### ISSUE THREAD

**Issue by SleepyF0X** [FluentValidation/FluentValidation#1695]
### Describe the solution you'd like

I wanna remove all single quotes from Property Name

`'PropertyName' should not be empty. -> PropertyName should not be empty`

Can you please say how can I do it?

**Comment by JeremySkinner** [comment]
You can either override the individual message for a rule by calling `WithMessage` (docs: https://docs.fluentvalidation.net/en/latest/configuring.html?highlight=WithMessage#overriding-the-message)

...or you can override all the default messages and provide your own: https://docs.fluentvalidation.net/en/latest/localization.html#default-messages
