### ISSUE TITLE
Supporting client validation for Record type

### ISSUE THREAD

**Issue by AdiletADD** [FluentValidation/FluentValidation#1696]
### Is your feature request related to a problem? Please describe.

When I submit form with Record type, something like this
 ```
   public record TestDto(string Name);

    public class TestDtoValidator : AbstractValidator<TestDto>
    {
        public TestDtoValidator()
        {
            RuleFor(v => v.Name)
                .NotEmpty().WithMessage("Test required")
                .MaximumLength(2).WithMessage($"Must<2");
        }
    }
```
Client side not validating and immediately send to the server side

### Describe the solution you'd like

It would be helpful if model (Record type) is first checked on the client validation and then sent to the server for validation processing

### Describe alternatives you've considered

None

**Comment by JeremySkinner** [comment]
FluentValidation doesn't provide clientside validation directly, but rather provides metadata that ASP.NET's clientside validation (based on jQuery validate) performs instead. This works with both regular classes and records, provided you follow the instructions in the documentation at https://docs.fluentvalidation.net/en/latest/aspnet.html
