### ISSUE TITLE
CustomContext Removed from Version 9.x to Version 10.0.3

### ISSUE THREAD

**Issue by Skovdk** [FluentValidation/FluentValidation#1699]
### FluentValidation version

10.0.3

### Summary

Hi, I have a function with signature
`public static void MustBeContinuousAndComplete<T>(List<T>? timeDataItems, CustomContext context) where T: ITimeData`

which I call like.
`RuleFor(x => x.ToList()).Custom(CustomValidators.MustBeContinuousAndComplete);`

Which is no longer possible after the recent upgrade from 9.3 to 10.0.3

I tried changing the function signature to: 
`public static void MustBeContinuousAndComplete<T>(List<T>? timeDataItems, ValidationContext<T> context) where T: ITimeData`

but then I ran into more issues like:
 

>  ExchangeRatePriorityValidator.cs(16, 45): [CS0411] The type arguments for method 'CustomValidators.MustBeContinuousAndComplete<T>(List<T>?, ValidationContext<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
>   PriorityValidator.cs(14, 132): [CS1503] Argument 1: cannot convert from 'System.Collections.Generic.List<Hemonto.Client.Models.Client.Priority>' to 'System.Collections.Generic.List<System.Collections.Generic.IEnumerable<Hemonto.Client.Models.Client.Priority>>?'
>   LegalEntityValidator.cs(29, 47): [CS0411] The type arguments for method 'CustomValidators.MustBeContinuousAndComplete<T>(List<T>?, ValidationContext<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
>   LegalEntityValidator.cs(31, 59): [CS0411] The type arguments for method 'CustomValidators.MustBeContinuousAndComplete<T>(List<T>?, ValidationContext<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

And now I am without a clear clue of what to do. 
Can you please guide me how to get a long with the changes you have made?
Thanks in advance and best regards,
Søren

### Steps to Reproduce

See summary.

**Comment by Skovdk** [comment]
@CasperWSchmidt

**Comment by JeremySkinner** [comment]
Hello, you need to update the method signature to have 2 generic parameters - one for the root object, one for the property type. 

```csharp
public static void MustBeContinuousAndComplete<TModel, T>(List<T> timeDataItems, ValidationContext<TModel> context) where T: ITimeData
```

**Comment by Skovdk** [comment]
Hi Jeremy,
Works great and hanks a lot for the prompt answer, much appreciated!
Best regars.
