### ISSUE TITLE
Allow lambda parameters in the InclusiveBetween validator

### ISSUE THREAD

**Issue by diegodalben** [FluentValidation/FluentValidation#1700]
### Describe the solution you'd like

Currently, the **InclusiveBetween** validator does not allow lambda in its parameters. I encountered this old [issue](https://github.com/FluentValidation/FluentValidation/issues/250) that appears with the intention of allowing lambda parameters in this validator in the future.

Let me know if this is something we can expect as a new feature or is it a recommendation to always customize the validation itself for this case?

Below is an use example:

RuleFor(entity => entity.Fee)
        .InclusiveBetween(entity => entity.Parameters.FeeMin, entity => entity.Parameters.FeeMax);

**Comment by JeremySkinner** [comment]
Hi, there's no plans to add this - you should use `Must` to achieve this:

```
RuleFor(entity => entity.Fee).Must((entity, fee) => fee >= entity.Parameters.FeeMin && fee <= entity.Parameters.FeeMax);
```
