### ISSUE TITLE
Examples on how to use FluentValidation with Cake

### ISSUE THREAD

**Issue by augustoproiete** [FluentValidation/FluentValidation#1702]
### Is your feature request related to a problem? Please describe.

FluentValidation can be very useful to perform validation in Cake build scripts, from validation of input arguments, to general data validation of build context data.

### Describe the solution you'd like

I'd like to offer to add code samples and/or documentation on how to leverage FluentValidation when using Cake scripts to help FluentValidation users and to showcase another valid use-case where FluentValidation can be useful.

I'm open to any format(s) that makes sense. As a suggestion, I could send a PR to include a separate section, similar to the ASP .NET integration, that demonstrates the integration of FluentValidation with Cake, with a few examples and code snippets.

![image](https://user-images.githubusercontent.com/177608/115083608-05abb700-9ede-11eb-85c2-2fde1bcf493d.png)

### Additional Context

This relates to a discussion in the NuGet Gallery repo about using FluentValidation in Cake scripts: https://github.com/NuGet/NuGetGallery/issues/8532

**Comment by JeremySkinner** [comment]
Hi @augustoproiete thanks for the suggestion, but I think this is probably out of scope for what we want to include in the docs here. 

FluentValidation can be used in lots of different contexts, and providing documentation for all of these isn't really practical/scalable from a maintenance/support perspective. The exception to this is ASP.NET as we provide [a dedicated integration package](https://docs.fluentvalidation.net/en/latest/aspnet.html) for plugging FV into the ASP.NET validation pipeline, which is maintained as part of this project. 

For example we don't provide any guidance for how to use FV with WPF, or with Blazor (although we [do link to the various FV/Blazor integration packages](https://docs.fluentvalidation.net/en/latest/blazor.html), but the developers of those tools are the ones who provide the documentation for it in their own repos, so it isn't something I end up having to maintain or support).

Thanks for wanting to be involved, hope that makes sense.
