### ISSUE TITLE
Updated minimum supported platform to be .net6+

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1704]
We originally planned to drop netstandard2 in FluentValidation 10, but decided to hold off as .net platform convergence was delayed from .net 5 to .net 6. 

We should target .net 6 as our minimum supported platform. Support for netstandard2 and netstandard2.1 should be removed. 

Users who still require netstandard2 or netstandard2.1 support will continue to be able to use FluentValidation 11.x.

**Comment by richardgavel** [comment]
What new APIs in netstandard 2.1 were you planning on consuming?

**Comment by JeremySkinner** [comment]
Default interface methods is the main thing, which will help tidy up our fluent interface implementation. Additionally it sets a new baseline and ensures the new version can't be used on platforms that we don't support anymore (.net core 2.1 & net4x)

**Comment by JeremySkinner** [comment]
Pushing back for another year

**Comment by AgentFire** [comment]
[richardgavel](https://github.com/richardgavel), well, at least `Task` will be able to be switched for `ValueTask`.
