### ISSUE TITLE
Add a way to get property value from ValidationContext

### ISSUE THREAD

**Issue by ap0llo** [FluentValidation/FluentValidation#1707]
### Is your feature request related to a problem? Please describe.

I'm trying to implement a optional rule and would like to write a custom "Unless" function.

For example, assuming I have the following data class

```cs
public class MyClass
{
    public string? DirectoryPath { get; set; }
}
```

and I want to express "*The directory must exist unless no directory is specified*", I could write

```cs
 RuleFor(x => x.DirectoryPath )
    .Must(Directory.Exists)
    .Unless(x => String.IsNullOrEmpty(x.RepositoryPath))
```

but since I'm using the "Unless null or empty" condition in multiple places, I tried to define a `UnlessNullOrEmpty()` extension method so I can write

```cs
 RuleFor(x => x.DirectoryPath )
    .Must(Directory.Exists)
    .UnlessNullOrEmpty()
```

In the implementation of `UnlessNullOrEmpty()` , I have access to both the instance being validated and the `ValidationContext` which gives me access to the name of the property being validated but no straightforward way to get the property value for the current instance:

```cs
public static IRuleBuilderOptions<T, string?> UnlessNullOrWhiteSpace<T>(this IRuleBuilderOptions<T, string?> builder)
{
    return builder.When((instance, context) =>
    {
        var value = ...
        return !String.IsNullOrWhiteSpace(value);
    });
}
```

### Describe the solution you'd like

It would be nice to be able to access the property value through the `ValidationContext`, e.g. `GetPropertyValue(intance)`, so I write something like 

```cs
public static IRuleBuilderOptions<T, string?> UnlessNullOrWhiteSpace<T>(this IRuleBuilderOptions<T, string?> builder)
{
    return builder.When((instance, context) =>
    {
        var value = context.GetPropertyValue(instance);
        return !String.IsNullOrWhiteSpace(value);
    });
}
```

### Describe alternatives you've considered

An alternative would be to use `ValidationContext.PropertyName` and get the property from the instance but since the property name could be a full property path, this is not straightforward to implement.

**Comment by JeremySkinner** [comment]
Hi, this is already implemented. You'll need to drop down into the internal API and call `ApplyCondition` on the rule instance. Please see https://github.com/FluentValidation/FluentValidation/issues/1688#issuecomment-815990401 for an example
