### ISSUE TITLE
Object reference not set to an instance of an object exception is thrown

### ISSUE THREAD

**Issue by arashcomsense** [FluentValidation/FluentValidation#1709]
### FluentValidation version

10.0.4

### Summary

The latest version of 9.x.x used to be able to validate our models successfully. Upgrading to the mentioned version started exhibiting the exception outlined in the subject line. Further details:

>    at FluentValidation.Internal.PropertyRule`2.<>c__DisplayClass1_0.<Create>b__0(T x) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 44
>    at FluentValidation.Internal.PropertyRule`2.<>c__DisplayClass4_0.<Validate>b__0() in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 108
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.get_Value()
>    at FluentValidation.Internal.PropertyRule`2.InvokePropertyValidator(ValidationContext`1 context, Lazy`1 accessor, String propertyName, RuleComponent`2 component) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 249
>    at FluentValidation.Internal.PropertyRule`2.Validate(ValidationContext`1 context) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 134
>    at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 92
>    at FluentValidation.AbstractValidator`1.Validate(T instance) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 62

### Steps to Reproduce

See the code snippet below:

```csharp
public abstract class BaseValidator<T> : AbstractValidator<T>
{
	protected BaseValidator() { }
}

public abstract class WorkerUnitValidator<T> : BaseValidator<T> where T : IWorker
	{
		protected WorkerUnitValidator()
		{
			RuleFor(w=> uow.CustomerId).NotEmpty();
			RuleFor(w=> w.Guid).NotEmpty();
			When(w=> ShouldValidateUserId(), () => RuleFor(w => w.UserId).NotEmpty());
		}

		protected virtual bool ShouldValidateUserId()
			=> true;
	}

internal class SomeModelPreValidator : WorkerUnitValidator<SomeModel>
	{
		public SomeModelPreValidator ()
		{
			RuleFor(m=> m.Request).NotNull();
			RuleFor(m=> m.Request.UserId).NotEmpty();
		}
	}

public class SomeModel : IWorker
{
   public object Request { get; set; }
   public string UserId { get; set; }
   public string Guid { get; set; }
   public string CustomerId { get; set; }
}
```

I just removed `RuleFor(m=> m.Request.UserId).NotEmpty();` from `SomeModelPreValidator` class and the exception disappeared. The exception should be more descriptive to tell the developers what to do to mitigate the issue.

**Comment by JeremySkinner** [comment]
Hi, this behaviour hasn’t changed from versions 9 to 10. FluentValidation doesn’t handle null references for you - you need to handle null checks yourself:  

```charp

RuleFor(m=> m.Request.UserId).NotEmpty().When(m=> m.Request != null);

```

**Comment by arashcomsense** [comment]
@JeremySkinner Please read the source code that I shared earlier again and compare it with what you suggested. You are comparing with m.Request which is out of the scope of what I outlined.
