### ISSUE TITLE
overriding default bad request response

### ISSUE THREAD

**Issue by kurkoc** [FluentValidation/FluentValidation#1710]
### Is your feature request related to a problem? Please describe.

hey everyone. i used AddFluentValidation extension method to validate all models. But i want to override default response, default response is as follows. i want to use custom api response.

`{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-e263b6c479d0424cb05677e662cc54b5-52fd25dc93004f4a-00",
  "errors": {
    "Name": [
      "Ad Alanı Boş Olamaz"
    ]
  }
}`

i tried IAsyncResourceFilter/OnResourceExecutionAsync method. before await next() the model looks fine. also 
i tried IAsyncActionFilter/OnActionExecutionAsync method but the response sending before working yet this method.

### Describe the solution you'd like

i want to catch all errors and send my custom BadRequest reponse.

**Comment by JeremySkinner** [comment]
Hi, this automatic response is not a feature of FluentValidation - this is a feature of asp.net’s `ApiController` attribute. Please review the asp.net documentation for api controllers, which explains how to disable this: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#automatic-http-400-responses
