### ISSUE TITLE
IValidator.Validate waits IValidationContext

### ISSUE THREAD

**Issue by kurkoc** [FluentValidation/FluentValidation#1712]
### FluentValidation version

10.0.4

### ASP.NET version

.NET 5

### Summary

hey everyone. There was such a use in version 8.6.2 in my app. 

`object validator = Activator.CreateInstance(validatorType);
ValidationResult validationResult = ((IValidator)validator).Validate(dto);`

"validator" is an object to dynamic creation of validator class. dto is object to validate.

Today i upgrade to 10.0.4 and these Validate method excepts to IValidationContext. How to handle this?

**Comment by JeremySkinner** [comment]
Like this:

```csharp
object validator = Activator.CreateInstance(validatorType); 
ValidationResult validationResult = ((IValidator)validator).Validate(new ValidationContext<object>(dto));
```

This is covered in the 9.x upgrade guide: https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload

**Comment by kurkoc** [comment]
thanks. king jeremy ruled his world

**Comment by JeremySkinner** [comment]
haha thanks 😅
