### ISSUE TITLE
Add opportunity to override default severity level

### ISSUE THREAD

**Issue by AlexTruba** [FluentValidation/FluentValidation#1714]
### Is your feature request related to a problem? Please describe.

I'm using severity level for the different cases, for e.g. writing logs with selected level or returning validation error to the client with corresponding level. For 90% of the cases my application uses only one level and I need to explicitly set severity level, if I need another then a `Error` level.
It would be nice to have a setting for default severity, then instead of duplication `WithSeverity` method call, I only need to change default value.

### Describe the solution you'd like

First of all, add a new property with `Severity` name and value `Severity.Error` for backward compatibility inside `ValidatorConfiguration` 
Then update `CreateValidationError` method from `RuleBase` class
**Before:**
```
if (component.SeverityProvider != null) {
    failure.Severity = component.SeverityProvider(context, value);
}
```
**After**
```
if (component.SeverityProvider != null) {
    failure.Severity = component.SeverityProvider(context, value);
}
else
{
    failure.Severity = ValidatorOptions.Global.Severity;
}
```

**Comment by JeremySkinner** [comment]
This seems reasonable, please feel free to submit a PR that adds this along with appropriate tests, and I'll be happy to review it.

**Comment by JeremySkinner** [comment]
I’ve pushed 10.1 to nuget with this change
