### ISSUE TITLE
Using Interfaces to detect and Register fluent validators on startup using RegisterValidatorsFromAssemblyContaining?

### ISSUE THREAD

**Issue by aloksharma1** [FluentValidation/FluentValidation#1717]
### FluentValidation version

10.0.2

### ASP.NET version

Net 5

### Summary

Hello, 
I am using fluent validation in a modular app based on runtime loading of plugins using assemly load contexts, since this is a ever changing scenario i cannot hard code my fluent validation registration on app startup.cs class like the classic example :
```
services.AddMvc(options=>{
                //options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            }).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<AuthenticationRequestValidator>());
```
instead what i want to be able to do is this:
```
services.AddMvc(options=>{
                //options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            }).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<IModuleValidator>());   
```         

so my generic interface that is connected with all abstractclasses can pick up the validator rules from my various plugin assemblies, hope i am clear enough with my explanation.
awaiting your reply.

### Steps to Reproduce

use any sample project given in docs, create a generic interface IPlugValidator or by Any name then use it in validator class like :

```
public class AuthenticationRequestValidator : AbstractValidator<AuthenticationRequest>, IPlugValidator 
    {
        public AuthenticationRequestValidator()
        {
            RuleFor(x => x.UserName).NotEmpty().When(m => string.IsNullOrEmpty(m.Email));
            RuleFor(x => x.Email).NotEmpty().When(m => string.IsNullOrEmpty(m.UserName));
            RuleFor(x => x.Password).NotNull().MinimumLength(6);
        }
    }
```

then try to register it 

```
services.AddMvc(options=>{
                //options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            }).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<IPlugValidator >());   
```   

its not working.. any workaround is appreciated.

**Comment by JeremySkinner** [comment]
This code would only register validators defined in the *same assembly as the IPlugValidator interface itself*. If you have multiple dynamically loaded assemblies, it wouldn't scan these. You need to explicitly indicate which assemblies should be scanned. You'd need to loop over the public types in the dynamically loaded assemblies yourself. Closing as this isn't an issue with FluentValidation.
