### ISSUE TITLE
CascadeMode = CascadeMode.Stop confusion

### ISSUE THREAD

**Issue by zoinkydoink** [FluentValidation/FluentValidation#1718]
### FluentValidation version

10.0.2

### ASP.NET version

.NET Core 6 P3

### Summary

Maybe I am not understanding this correctly, but I thought `CascadeMode = CascadeMode.Stop;` would be forced as per rule and not per validator.

I have the following:
```
            CascadeMode = CascadeMode.Stop;            
            RuleFor(c => c.TimeZoneId)
                .NotEmpty()
                .SetValidator(new TimezoneValidator<EventCommandBase>())
                .When(x => x.DateType == DateTypes.Date_Range || x.DateType == DateTypes.Single_Date);

            RuleFor(x => x.EndDateTime)
               .NotNull().WithMessage("End date and time is required")
               .LessThan(DateTimeOffset.Now).WithMessage("something something")
               .GreaterThan(x => x.StartDateTime).WithMessage("End date time must greater than start date time")
               .When(x => x.DateType == DateTypes.Date_Range);
```

This will show that timezoneid is required and stop (nothing is shown for the fact that timezoneid is not valid (custom validator), this is expected behaviour so far, what is not doing is that its not showing the fact that no messages are shown for EndDateTime, I was under the impression that the way I have it defined would try the first rule for timezone, if it failed and not try second rule for timezone but would continue to the next rule and do the same thing, try first, if failed, not try second rule

I know I can do the below code which would work, but then all chained validators have to be set manually, I guess what I am looking for is a way to say "hey, go through all rules (per field) and for each ruleset, if the first condition fails dont bother going to the second condition, but definitely keep validating other rulesets"
Is this possible or I must define each chain manually?

```
            RuleFor(c => c.TimeZoneId).Cascade(CascadeMode.Stop)
                .NotEmpty()
                .SetValidator(new TimezoneValidator<EventCommandBase>())
                .When(x => x.DateType == DateTypes.Date_Range || x.DateType == DateTypes.Single_Date);

            RuleFor(x => x.EndDateTime).Cascade(CascadeMode.Stop)
               .NotNull().WithMessage("End date and time is required")
               .LessThan(DateTimeOffset.Now).WithMessage("something something")
               .GreaterThan(x => x.StartDateTime).WithMessage("End date time must greater than start date time")
               .When(x => x.DateType == DateTypes.Date_Range);
```

**Comment by zoinkydoink** [comment]
TimezoneValidator in case its needed
```
    public class TimezoneValidator<T> : PropertyValidator<T, string>
    {
        public override string Name => "TimezoneValidator";

        public override bool IsValid(ValidationContext<T> context, string timezoneId)
        {
            try
            {
               
                TZConvert.GetTimeZoneInfo(timezoneId);
            }
            catch (TimeZoneNotFoundException)
            {
                context.AddFailure("Timezone provided could not be found");
                return false;
            }

            return true;

        }

    }
```

**Comment by JeremySkinner** [comment]
This is working correctly. When set at the validator level, CascadeMode.Stop will stop execution once at least one rule fails. It is a “fail fast” behaviour for the whole validator. This is explained in the docs: https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode 

Particularly take a look at the section on Stop vs StopOnFirstFailure, which I believe is what you want instead.

**Comment by zoinkydoink** [comment]
`CascadeMode.StopOnFirstFailure` has been deprecated and suggests we use .Stop so we are going back in circles.

Am I understanding this correctly that the going forward recommendation is I put CascadeMode.Stop on each rule instead of validator level since the validator level approach is deprecated.
What is the future plan?

**Comment by JeremySkinner** [comment]
It is deprecated but you can continue to use it if you wish. It won’t be removed.

**Comment by zoinkydoink** [comment]
for what its worthy, I think you should rename it to something better, dont deprecated it because there should be a way to do it at validator level, just with a better name.  I will just do it at rulelevel as suggested instead of using deprecated code. thank you for your support
