### ISSUE TITLE
Rulesets version 9 vs 10

### ISSUE THREAD

**Issue by LeahPike** [FluentValidation/FluentValidation#1719]
### FluentValidation version

10.0.4

### ASP.NET version

.NET Core 5.0.0

### Summary

Since upgrading to version 10 I have noticed I'm getting duplicate validation messages for a rules without a rule set.

This is the message returned on our site running version 9:

> Validation Failed
> -- Columns: Datasheet requires at least 1 column
> -- Name: 'Name' must not be empty.

This is the message returned on our site running version 10:

> Validation Failed
> -- Columns: Datasheet requires at least 1 column
> -- Columns: Datasheet requires at least 1 column
> -- Name: 'Name' must not be empty.

Name is within a rule set called "Save", columns isn't within rule set.

### Steps to Reproduce

``` c#
var results = await _validator.ValidateAsync(entity, options => options.IncludeRuleSets("default", "save"));
```

``` c#
using FluentValidation;
using m2i.Activ.Data.Reporting;

namespace m2i.Activ.Service.Reporting
{
    public class DatasheetValidator : CompositeValidator<Datasheet>
    {
        public DatasheetValidator(IValidator<Report> baseValidator)
        {
            RegisterBaseValidator(baseValidator);
            RuleFor(e => e.Columns).NotEmpty().WithMessage("Datasheet requires at least 1 column");
        }
    }
}
```

``` c#
using FluentValidation;
using m2i.Activ.Data.Reporting;

namespace m2i.Activ.Service.Reporting
{
    public class ReportValidator : AbstractValidator<Report>
    {
        public ReportValidator()
        {
            RuleSet("save", () =>
            {
                RuleFor(e => e.Name).NotEmpty().Length(1, 255);
            });
        }
    }
}
```

**Comment by JeremySkinner** [comment]
Hi, I can't reproduce this I'm afraid, but I don't know what your `CompositeValidator` or `RegisterBaseValidator` do, so it could be related to that. 

Please could you provide fully runnable steps to reproduce, ideally in the form of a unit test (or alternatively as a small standalone sample project) including all code necessary to reproduce. Thanks

**Comment by LeahPike** [comment]
Thank you, I had overlooked the CompositeValidator and have since found the issue within it.

We were previously concatenating the two lists, however in version 10 this was causing the duplicates, just calling await seems to add it to the existing validation list.

Version 9
``` c#
        public override ValidationResult Validate(ValidationContext<T> context)
        {
            var mainErrors = base.Validate(context).Errors;
            var errorsFromOtherValidators = otherValidators.SelectMany(x => x.Validate(context).Errors);
            var combinedErrors = mainErrors.Concat(errorsFromOtherValidators);

            return new ValidationResult(combinedErrors);
        }
```

Version 10
``` C#
        public async override Task<ValidationResult> ValidateAsync(ValidationContext<T> context, CancellationToken cancellation = default(CancellationToken))
        {
            var validation = await base.ValidateAsync(context, cancellation);

            foreach (var item in otherValidators)
                await item.ValidateAsync(context, cancellation);

            return new ValidationResult(validation.Errors);
        }
```

**Comment by JeremySkinner** [comment]
Ah, yes that makes sense. No need to concatenate the 2 lists in 10.x, as we add them all to a single collection as we go which is stored on the context (rather than producing multiple lists, which the old version did). This helped with performance in 10.x
