### ISSUE TITLE
Validate multiple dependent fields

### ISSUE THREAD

**Issue by knight1219** [FluentValidation/FluentValidation#1720]
### FluentValidation version

9.2.2

### ASP.NET version

.net Core 3.1

### Summary

I have the following class that I need to have validated. 

`

    public class MobilePhone 

    { 
        public string CountryCode { get; set; }

        public string AreaCode { get; set; }

        public string PhoneNumber { get; set; }

        public int Id { get; set; }

    }

`

These are the rules that must be implemented :

- If countryCode OR areaCode OR phoneNumber are not null then

1. countryCode must not be null and must be between 1-3 characters
2. areaCode must not be null and must be between 1-5 characters
3. phoneNumber must not be null and must be between 1-7 characters
4. Must check to see if this combo as a whole is unique in our database, if this fails I want to invalidate all 3 fields.

- Else (countryCode OR areaCode OR phoneNumber ARE null)
1. countryCode must be null 
2. areaCode must be null
3. phoneNumber must be null

`

    public class MobilePhoneValidator : AbstractValidator<MobilePhone>
    {
        private readonly IModelValidator modelValidator;

        public MobilePhoneValidator(IModelValidator modelValidator)
        {
            this.modelValidator = modelValidator;
            this.CascadeMode = CascadeMode.Stop;
            var errorMessage = "Mobile phone number is already attached to another entity, please try again.";

            RuleFor(x => x).Must(e => !string.IsNullOrEmpty(e.CountryCode) ||
                        !string.IsNullOrEmpty(e.AreaCode) ||
                        !string.IsNullOrEmpty(e.PhoneNumber)).DependentRules(() => {
                            RuleFor(x => x.CountryCode).NotEmpty().Length(1, 3)
                                        .MustAsync(async (o, phone, token) =>
                                        {
                                            return await this.modelValidator.IsPhoneUnique(o.CountryCode,
                                                o.AreaCode,
                                                o.PhoneNumber,
                                                o.Id, token);
                                        })
                                        .WithMessage(errorMessage);

                            RuleFor(x => x.AreaCode).NotEmpty().Length(1, 5)
                                        .MustAsync(async (o, phone, token) =>
                                        {
                                            return await this.modelValidator.IsPhoneUnique(o.CountryCode,
                                                o.AreaCode,
                                                o.PhoneNumber,
                                                o.Id, token);
                                        })
                                        .WithMessage(errorMessage);
                            RuleFor(x => x.PhoneNumber).NotEmpty().Length(1, 7)
                                        .MustAsync(async (o, phone, token) =>
                                        {
                                            return await this.modelValidator.IsPhoneUnique(o.CountryCode,
                                                o.AreaCode,
                                                o.PhoneNumber,
                                                o.Id, token);
                                        })
                                        .WithMessage(errorMessage);
                        });

            RuleFor(x => x).Must(e => string.IsNullOrEmpty(e.CountryCode) ||
                        string.IsNullOrEmpty(e.AreaCode) ||
                        string.IsNullOrEmpty(e.PhoneNumber)).DependentRules(() =>
                        {
                            RuleFor(x => x.CountryCode).Empty();
                            RuleFor(x => x.AreaCode).Empty();
                            RuleFor(x => x.PhoneNumber).Empty();
                        });

        }

        
    }
`
There are a few issues I'm having: 

1. The Length rules seems to never get enforced as I can add all types of data to my form and they show valid (im guessing passing the NotEmpty rule.
2. So because Length doesnt run, neither does my MustAsync which is critical for me to ensure my data is good up front.
3. It feels wrong for each RuleFor to have the MustAsync call, but I want that to run during each validation check. But If that MustAsync fails, i want to to invalidate all 3 of the fields (so the UI responds accordingly). I feel like having rules ran on a combination of properties like this is a fairly common thing but i havent been able to find any good. There has to be a better way to do this.

Any help with this would be awesome!

**Comment by JeremySkinner** [comment]
Hi, don't use `Must` with `DependentRules` to do this, this is making it overly complex and hard to debug. 

You should use `When\Otherwise` to set up the top-level condition, then place the rules inside this. You only need one call to `MustAsync` to do the uniqueness check as the use of `CascadeMode.Stop` ensures that it won't run if the previous rules fail.  Here's the updated code:

```csharp
public MobilePhoneValidator (IModelValidator modelValidator) 
{
	CascadeMode = CascadeMode.Stop;

	var errorMessage = "Mobile phone number is already attached to another entity, please try again.";

	bool HasAtLeastOneFieldSpecified(MobilePhone phone)
		=> !string.IsNullOrEmpty(phone.CountryCode) || !string.IsNullOrEmpty(phone.AreaCode) || !string.IsNullOrEmpty(phone.PhoneNumber);

	When(HasAtLeastOneFieldSpecified, () =>
	{
		RuleFor(x => x.CountryCode).NotEmpty().Length(1, 3);
		RuleFor(x => x.AreaCode).NotEmpty().Length(1, 5);
		RuleFor(x => x.PhoneNumber).NotEmpty().Length(1, 7);

		RuleFor(x => x)
			.MustAsync(async (phone, token) => await modelValidator.IsPhoneUnique(phone.CountryCode, phone.AreaCode, phone.PhoneNumber, phone.Id, token))
			.WithMessage(errorMessage);
		
	}).Otherwise(() =>
	{
		RuleFor(x => x.CountryCode).Empty();
		RuleFor(x => x.AreaCode).Empty();
		RuleFor(x => x.PhoneNumber).Empty();
	}); 
}

```

Please note for future reference this is an issue tracker for bugs in the core FluentValidation library and isn't a general discussion/support forum.
