### ISSUE TITLE
Document breaking changes coming in 11.0

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1725]
This issue tracks breaking changes coming in 11.0 that will need to be documented:

# Supported platform changes
- [x] Removal of netcore2.1 (MS official support ends 21 August 2021)

# cascade mode changes
- [x] #1822 

# Public API
- [x] Asynchronous validators will now throw an exception when invoked synchronously, rather than silently running synchronously.
- [x] OnFailure/OnAnyFailure removed
- [x] Remove backwards compatibility property validator layer

# Test Helper
- [x] Remove deprecated test helper methods

# Internal API

- [x] `IValidationRule<T,TProperty>.CurrentValidator` has been removed (use the `Current` property instead)
- [x] `IValidationRule<T,TProperty>.Current` now returns an `IRuleComponent<T,TProperty>` interface instead of `RuleComponent<T,TProperty>` (necessary to support variance) 
- [x] `IValidationRule<T,TProperty>.MessageBuilder`'s argument is now an `IMessageBuilderContext<T,TProperty>` interface instead of `MessageBuilderContext<T,TProperty>` class (necessary to support variance)
- [x] `IValidationRule<T,TProperty>.MessageBuilder` is now set-only, and has no getter exposed (needed to support variance), meaning you can only have one message builder per rule chain. 
- [x] `IRuleComponent<T,TProperty>.CustomStateProvider` is now set-only to support variance
- [x] `IRuleComponent<T,TProperty>.SeverityProvider` is now set-only to support variance
- [x] `GetErrorMessage` is no longer exposed on `IRuleComponent<T,TProperty>`
- [x] Remove deprecated `Options` property from RuleComponent
- [x] MemberAccessor removed

# Aspnet integration
- [x] Remove deprecated RunDefaultMvcValidationAfterFluentValidationExecutes
-

**Comment by karlstefan** [comment]
Hi,
Why are you removing  OnFailure. It is our lifeline to be able to use your fantastic package in our error handling flow. We need to throw custom exceptions. And OnFailure is the only way. We have integrated FluentValidation in an allready existing flow and use it like this. The Rules here are for a user.

RuleFor(r => r.FirstName).NotEmpty().OnFailure(_ => throw new SomeCustomExcepiton("MissingFirstName")))
                                         .MaximumLength(15).OnFailure(_ => throw new SomeCustomExcepiton("ToLongFirstName"));
						 
RuleFor(r => r.Email).NotEmpty().OnFailure(_ => throw new SomeCustomExcepiton("MissingEmail")))
                                 .Must(email => email.IsValidEmail()).OnFailure(_ => throw new SomeCustomExcepiton("NotValidEmail"));

Is there any other way for us to throw our own exception? We can not change everything to handle ValidationException.

Thank you

**Comment by JeremySkinner** [comment]
Hi @karlstefan OnFailure has always always been a problematic feature in terms of maintaining the codebase, and doesn't fit with the standard FluentValidation workflow. If you want to throw your own exception you can override the `RaiseValidationException` in the validator, and throw your own exception in here instead of the standard ValidationException:

https://github.com/FluentValidation/FluentValidation/blob/8b0d4dfac01769ce7c81ace4d6894d68221865cd/src/FluentValidation/AbstractValidator.cs#L428-L430

**Comment by karlstefan** [comment]
Hi, 
Thank you for the fast response. I think that overriding RaiseValidationException might work. If not I will do as you requested.

**Comment by JeremySkinner** [comment]
@ronaldkroon The main reason is because its behaviour is somewhat unintutive as it silently instantiates an instance of the model class and attempts to set the property values, which fails at runtime if the properties aren't writable. This feels too "magic" and has led to a lot of support questions over the years, which I want to minimize. 

If you're happy with the syntax and want to keep using it then you can copy the method implementation into your own application's code (along with the MemberAccessor class) - it's a wrapper around `TestValidate`

**Comment by mnsrulz** [comment]
> @mnsrulz [Please see my response above](https://github.com/FluentValidation/FluentValidation/issues/1725#issuecomment-905644363)

Yeah I saw that - I think what I am trying to say is the code looks much cleaner with the `Should...` methods instead of instantiating the object first and then apply test validate. I do understand that we can take the internals of that method and stick it in our codebase to revive it in v11, but that's something more suited as a test extensions helper within the library I believe.

I have 100's of validation test cases which are one liner with that extension method and these test cases looks really nice and clean.

```
        [Fact]
        public void ShouldNotHaveErrorWhenNameIsValid() => _validationUnderTest.ShouldNotHaveValidationErrorFor(x => x.Name, "Simple Segment");

        [Fact]
        public void ShouldHaveErrorWhenNameIsEmpty() => _validationUnderTest.ShouldHaveValidationErrorFor(x => x.Name, string.Empty);

        [Fact]
        public void ShouldHaveErrorWhenNameIsGreaterThan150Characters() => _validationUnderTest.ShouldHaveValidationErrorFor(x => x.Name, new string('a', 151));

        [Fact]
        public void ShouldNotHaveErrorWhenSegmentValueIsValid() => _validationUnderTest.ShouldNotHaveValidationErrorFor(x => x.Value, "Value");
```

Thanks for maintaining such a wonderful library!
