### ISSUE TITLE
Add an overload to ValidateAsync receiving context and options

### ISSUE THREAD

**Issue by jcaiznaga81** [FluentValidation/FluentValidation#1729]
### Is your feature request related to a problem? Please describe.

I have a custom async validator that receives custom parameters; It works with different Rules sets. There is no way (or I can't find it) to pass a context and also options to the ValidateAsync method (it can be done calling Validate but as I said it is an async validator)

### Describe the solution you'd like

Have an overload to the ValidateAsync:
Task<ValidationResult> ValidateAsync(IValidationContext context, Action<ValidationStrategy<T> options, CancellationToken cancellation = default);

### Describe alternatives you've considered

make a synchronous validator but it will really affect performance.

**Comment by JeremySkinner** [comment]
This doesn't really make sense. Options are just a shortcut way of creating a context - receiving both as parameters would be pointless.

**Comment by JeremySkinner** [comment]
When you call an overload that takes options, it is just calling `ValidationContext<T>.CreateWithOptions` under the covers. See: https://github.com/FluentValidation/FluentValidation/blob/def3ad9aa3038a71626128da2d0db37b0f5eedcc/src/FluentValidation/DefaultValidatorExtensions_Validate.cs#L51-L53

**Comment by jcaiznaga81** [comment]
Hi,

You are totally right. I forgotthe CreateWithOptions method. Thanks a lot.

Josue
