### ISSUE TITLE
Rule introspection

### ISSUE THREAD

**Issue by sandord** [FluentValidation/FluentValidation#1731]
### Is your feature request related to a problem? Please describe.

In my current project, I'm introspecting rules to project a shadow rule model that I'm using for client-side validation in our Angular front-end. This somewhat follows the advice given in https://github.com/FluentValidation/FluentValidation/issues/76#issuecomment-109257686

But since the advent of version 10 and its generic validators, I can't cast an `IPropertyValidator` to `LengthValidator` anymore since it now requires two generic arguments, which I don't have.

This used to work:
    
    if (validator is LengthValidator lengthValidator)
    {
        minLength = lengthValidator.Min;
    }

This code is running inside a loop that iterates over a set of arbitrary validators so I don't have a `TModel` or `TProperty` here. I have to deal with ordinary types.

I'm afraid this forces me to use reflection to access the validator-specific properties, such as the `Min` property in the example. 

I'm aware this usage is a kind of an edge case but it's such a pity that rule inspection has become much harder now.

Perhaps there is a better way than reflection (which is inherently slow, ugly and unstable since an update of FV could easily break it) I've missed so far?

### Describe the solution you'd like

If only `LengthValidator<T>` would inherit from an `ILengthValidator` containing the validator properties ;-)

**Comment by JeremySkinner** [comment]
There's no need to use reflection. We already have a non-generic `ILengthValidator` that you can use precisely for this purpose. https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Validators/LengthValidator.cs#L23

**Comment by sandord** [comment]
Oh wow, how did I manage to miss this 🤦🏽‍♂️I guess I'll consider my wish granted before I even made it.

Anyway, thanks for responding so quickly.
