### ISSUE TITLE
How can I bypass type-safe in validator classes?

### ISSUE THREAD

**Issue by kurkoc** [FluentValidation/FluentValidation#1732]
### FluentValidation version

10.0.4

### ASP.NET version

.NET 5

### Summary

hey everyone.

i have a method where i list all the rules in a validator by dynamically. For ex : List<Rules> GetValidatorRules(string validatorTypeName)  fluentvalidation version : 9.5.3

`            object validator = Activator.CreateInstance(validatorType);
            var validatorInstance = (IValidator)validator;
            var validatorDescriptor = validatorInstance.CreateDescriptor();
            var validatorMembers = validatorDescriptor.GetMembersWithValidators();`

after that i browse through all the rules and do some operations according to the type.

`                    if (ruleItem is MaximumLengthValidator maximumLengthValidator )
                    {
                        var errorMessage = maximumLengthValidator .GetErrorMessageTemplate(null);
                        var parameter = maximumLengthValidator.Max;
                    }`

after i upgrade 10.0.4 some generic constraints have been added to validator types. I can overcome the type checking by using the interface.

`if(ruleItem is IMaximumLengthValidator)`

but how can i overcome this? the type constraint here prevents dynamical usage, because i dont have any T, i only have an object with dynamically created by string.
 
`var parameter = (currentValidator as MaximumLengthValidator<T>).Max;`

I hope I could explain my problem

**Comment by JeremySkinner** [comment]
Hi, you're on the right track. Property validators expose non-generic interfaces precisely for this use case - you should use them as you're doing in your example and access the properties you need via those interfaces.


```csharp
Type validatorType = typeof(ComplexValidationTester.PersonValidator);
IValidator validator = (IValidator)Activator.CreateInstance(validatorType);
var descriptor = validator.CreateDescriptor();
var validatorMembers = descriptor.GetMembersWithValidators();

foreach (var memberWithValidators in validatorMembers) {
	foreach (var item in memberWithValidators) {
		if (item.Validator is IMaximumLengthValidator maximumLengthValidator) {
			var parameter = maximumLengthValidator.Max;
			/// ... use as you need to ...
		}
	}
}

```

**Comment by kostebudinoski** [comment]
Hi @JeremySkinner
not all validators are implementing an interface (except the general one `IPropertyValidator`). Would it be possible that you add marker interfaces for all the existing validations, so we distinguish the underlying type. This is an issue that popped up for us with introducing the generic constraints on the validators. We have a custom logic based on the validator type, to generate client metadata, but with the migration to the generics, I am facing issues to know the validator type. For example, `EnumValidator`, is a validator inheriting `PropertyValidator `only. How would you know if `EnumValidator` is presented on the rules we define? There is nothing similar like the `IMaximumLengthValidator` or `ILengthValidator` and so on.

**Comment by kostebudinoski** [comment]
Thanks for your quick reply @JeremySkinner . Checking their `Name` should be a possible solution.
