### ISSUE TITLE
IAsyncActionFilter no work

### ISSUE THREAD

**Issue by hjkl950217** [FluentValidation/FluentValidation#1735]
### FluentValidation version

FluentValidation.AspNetCore 10.1.0

### ASP.NET version

3.1

### Summary

When the parameters are verified, `IAsyncActionFilter` will not work, and the breakpoint will not enter `OnActionExecutionAsync`.

Validator:
```
    public class TestRequestCheck : AbstractValidator<CreateTestRequest>
    {
        public TestRequestCheck()
        {
    
            this.RuleFor(t => t.CreateTestList)
                .NotNull()
                .WithMessage("不能为空")
                .NotEmpty()
                .WithMessage("必须有值");

           
        }
    }
```
IAsyncActionFilter:
```
    public class TestValidationFilter : IAsyncActionFilter
    {
        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        { //  Break here
            await next();
        }
    }
```
API：
```
        [HttpPost]
        public DataResult<string> Get(CreateTestRequest a)
        {
            return "OK";
        }

        [HttpPost("2")]
        public DataResult<string> Get2()
        {
            return "OK";
        }
```

I need to do some business operations of my own in the Filter, but when I access the first API, I did not enter the Filter, and the second API is fine.
I'm currently testing and haven't started coding business yet

**Comment by JeremySkinner** [comment]
This is not caused by FluentValidation. When you use asp.net’s `ApiController` attribute, asp.net will prevent filters from running if validation fails. 

please review the asp.net documentation which explains how this works and how to disable it:  https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#disable-automatic-400-response

**Comment by hjkl950217** [comment]
I found this question you gave to another person, and I am trying this solution. . But boss, you shouldn't close it directly! I will reply when I solve it and close the problem myself!

**Comment by hjkl950217** [comment]
#1710

**Comment by JeremySkinner** [comment]
This issue tracker is only for bugs in FluentValidation, which is why I closed it. That’s how this works.
