### ISSUE TITLE
PreValidate Error not thrown on ValidateAndThrow if return value is "false"

### ISSUE THREAD

**Issue by matthiaslischka** [FluentValidation/FluentValidation#1736]
### FluentValidation version

10.1.0

### ASP.NET version

.Net Core 3.1

### Summary

When adding an error in `PreValidate` the `ValidateAndThrow()` method does only throw when `PreValidate` returns `true`. Not when it returns `false`.

This is very unexpected and probably an oversight. The validation failed and the method should throw.
https://docs.fluentvalidation.net/en/latest/advanced.html#prevalidate

BR Matthias

**Comment by JeremySkinner** [comment]
Thanks, I’ll look at getting that changed for a future version
