### ISSUE TITLE
Include rule does ignore ValidationFailure result

### ISSUE THREAD

**Issue by adimkov** [FluentValidation/FluentValidation#1738]
### FluentValidation version

10.1.0

### ASP.NET version

.NET Core 3.1

### Summary

Hello, 
I'm not sure is it a defect or my miss-configuration of validation rules.
After updating the library from 9 to 10, we faced this issue, and our included validation rules stopped taking into account.

Note: here is more like a pseudo code. However, I hope it will be understandable.

here is my validator
```csharp
public CreateClientRequestValidator(IValidator<ClientAbstractRequest> clientAbstractRequestValidator)
{
	Include(clientAbstractRequestValidator);
}
````
then in a test, I mocked IValidator to return an error like:
```csharp
clientAbstractRequestValidatorMock.Setup(x =>
                    x.ValidateAsync(It.IsAny<IValidationContext>(), It.IsAny<CancellationToken>()))
.ReturnsAsync(new ValidationResult(new[] { new ValidationFailure("ApplicationId", errorMessage) }));
					
var validator = new CreateClientRequestValidator(_clientAbstractRequestValidatorMock.Object);
validator.ValidateAsync(invalidRequest).IsValid.Should().BeFalse();
```

the issue is `validator.ValidateAsync(invalidRequest).IsValid` returns true, but should false.

I took a look into '[ChildValidatorAdaptor](https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Validators/ChildValidatorAdaptor.cs#L87)' code and find this:

```csharp
await validator.ValidateAsync(newContext, cancellation);
ResetCollectionIndex(context, originalIndex, currentIndex);
return true;
```

returned result of `validator.ValidateAsync(newContext, cancellation);` is ignored. Here I'm not sure what behavior of ValidateAsync should be, should it throw an exception?

Thank you!

PS. We are using this library, not in one project, and I think it awesome!

### Steps to Reproduce

- create validator with included rule
- mock included validator to return ValidationFailure result
- perform validation on any instance

**Comment by JeremySkinner** [comment]
Hi, FluentValidation 10 has a single collection of failures stored on the ValidationContext that is added to directly by the intervals of the library. Instead of mocking the return value you should instead set your mock to add the result to the context parameter’s failure collection (`context.AddFailure` On `ValidationContext<T>`), this will then work as you expect. 

All that being said I really don’t recommend mocking validator like this as this tends to lead to brittle tests. It’s much better to treat them as black boxes and feed them known valid/invalid data.

**Comment by adimkov** [comment]
Oh, got it,  will try that. Thank you!

**Comment by JeremySkinner** [comment]
In case you’re interested, this was done for performance reasons. In older versions we allocated a new collection for every property validator and nested child validator, which had a performance hit for large workloads. By switching to a single collection of failures (along with some other changes) we were able to almost double the performance and half the memory use in 10.x

**Comment by adimkov** [comment]
I used the method `AddFailure,` and it works as expected. 
Thank you for the explanation, that is impressive optimization. Thank you again!
