### ISSUE TITLE
Different behavior of [Test]Validate on Unit Tests

### ISSUE THREAD

**Issue by flavio-cadete-cko** [FluentValidation/FluentValidation#1739]
### FluentValidation version

10.1.0

### ASP.NET version

3.1

### Summary

![image](https://user-images.githubusercontent.com/51323090/118117899-128bcf80-b3e4-11eb-8cd8-543902f36c67.png)

So on 9.5.4 I was getting IsValid == false, which is the expected result. I'm setting up nested validator to have errors.
Now on 10.1.0 those errors don't came back to parent validator / `Validate`.

**Comment by JeremySkinner** [comment]
Please see https://github.com/FluentValidation/FluentValidation/issues/1738

**Comment by flavio-cadete-cko** [comment]
![image](https://user-images.githubusercontent.com/51323090/118119887-f6d5f880-b3e6-11eb-8c91-582919be0774.png)
How do I achieve this?

**Comment by JeremySkinner** [comment]
[Please check the documentation for your mocking library](https://github.com/Moq/moq4/wiki/Quickstart#callbacks) - you'll need to use the Callback method.

**Comment by JeremySkinner** [comment]
It'll be something like:

```csharp
validator.Setup(m => m.Validate(It.IsAny<ValidationContext<Person>>()))
	.Callback((ValidationContext<Person> context) => 
	{
		context.AddFailure(new ValidationFailure("Property", "ErrorMessage"));
	});
```

**Comment by flavio-cadete-cko** [comment]
Awesome thanks.
