### ISSUE TITLE
Exception Migrating to v10

### ISSUE THREAD

**Issue by flavio-cadete-cko** [FluentValidation/FluentValidation#1740]
### FluentValidation version

10.1.0

### ASP.NET version

3.1

### Summary

We are using an implementation using IValidatorFactory, and it's throwing exceptions after we upgraded from v9 to v10.
![image](https://user-images.githubusercontent.com/51323090/118282233-fbbda980-b4c5-11eb-8f80-3d4b50ca5677.png)

### Steps to Reproduce
Our validator is an implementation of AbstractValidator<[Command]> and it seems it throwing exception on return `_serviceProvider.GetService(validatorType) as IValidator;`

```
public class CustomValidatorFactory : IValidatorFactory
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly ConcurrentDictionary<string, Type> _validatorTypeCache;

        public CustomValidatorFactory(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
            _validatorTypeCache = new ConcurrentDictionary<string, Type>();
        }

        /// <summary>
        /// Get validator for the type provided.
        /// </summary>
        public IValidator<T> GetValidator<T>()
        {
            var validatorType = GetValidatorType(typeof(T));
            if (validatorType == null)
            {
                return null;
            }

            return (IValidator<T>)CreateInstance(validatorType);
        }

        /// <summary>
        /// Get validator for the type provided.
        /// </summary>
        public IValidator GetValidator(Type type)
        {
            var validatorType = GetValidatorType(type);
            if (validatorType == null)
            {
                return null;
            }

            return CreateInstance(validatorType);
        }

        private Type GetValidatorType(Type typeToValidate)
        {
            if (_validatorTypeCache.TryGetValue(typeToValidate.FullName ?? throw new InvalidOperationException(),
                out var validatorType))
            {
                return validatorType;
            }

            validatorType = typeof(IValidator<>).MakeGenericType(typeToValidate);

            _validatorTypeCache.TryAdd(typeToValidate.FullName, validatorType);

            return validatorType;
        }

        private IValidator CreateInstance(Type validatorType)
        {
            if (validatorType == null)
            {
                return null;
            }

            return _serviceProvider.GetService(validatorType) as IValidator;
        }
    }
```

_No response_

**Comment by JeremySkinner** [comment]
This means there a problem with your DI setup. You have a singleton-scoped service that’s trying to resolve a validator that’s request-scoped (which is the default in 10.x). Make sure your factory (and anything that depends on it) is registered with the service provider as `Scoped` and not as singleton.

**Comment by flavio-cadete-cko** [comment]
> Cannot consume scoped service 'FluentValidation.IValidatorFactory' from singleton 'Microsoft.Extensions.Hosting.IHostedService'
 By definition IHostedService will be singleton. Who I can workaround this?

**Comment by JeremySkinner** [comment]
You’ll either need to design your dependency hierarchy where you don’t have singleton-scoped services depend on request-scoped services, or change the registrations for your validators to make them transient instead of scoped.

**Comment by flavio-cadete-cko** [comment]
If I put as transient I will get the original error.  
` Cannot resolve scoped service 'FluentValidation.IValidator`1[DdKycOnfido.Services.DispatcherCommands.External.StartKycCheckCommand]' from root provider.`

**Comment by JeremySkinner** [comment]
No, that means the validator is registered as *scoped*. You’ll need to change it to *transient*

**Comment by flavio-cadete-cko** [comment]
Ah you mean something like this:
serviceCollection.AddValidatorsFromAssemblyContaining<Validator>(ServiceLifetime.Transient);

It's working now, thanks

**Comment by JeremySkinner** [comment]
yep
