### ISSUE TITLE
Please Help! When and Must Condation Not Working

### ISSUE THREAD

**Issue by fatihgulerrr** [FluentValidation/FluentValidation#1749]
### FluentValidation version

10.2

### ASP.NET version

.NET CORE 5

### Summary

Please Help! Only when and must conditions don't working

### Steps to Reproduce

My Example;
https://github.com/fatihgulerrr/FluentValdationTest

**Comment by JeremySkinner** [comment]
This is not related to FluentValidation. Your example project doesn't have an action method to accept the HTTP Post, so validation will never run. You need to add an action method that accepts the HTTP Post.

**Comment by JeremySkinner** [comment]
Additionally, the `asp-validation-for` tag helper can't use a self-closing tag, or the message won't display. So you'll need to change this:

```
<span class="validator-message" asp-validation-for="taxno" />
```

to:

```
<span class="validator-message" asp-validation-for="taxno"></span>
```
