### ISSUE TITLE
Current Major Vulnerability - System.Text.Encodings.Web

### ISSUE THREAD

**Issue by CamiloBenavides** [FluentValidation/FluentValidation#1753]
### FluentValidation version

10.2.1

### ASP.NET version

.Net Core 3.1

### Summary

Upgrade of the system.text.encodings.web package reference for the package

Current major vulnerability https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267

![image](https://user-images.githubusercontent.com/11163886/120313469-e7edb200-c2d1-11eb-8103-35b4c27a5049.png)
package

### Steps to Reproduce

Not applicable

**Comment by JeremySkinner** [comment]
This is nothing to do with FluentValidation. We don't reference that package.
