### ISSUE TITLE
Version 10 ValidationContext does not clear Errors as expected when using version 9

### ISSUE THREAD

**Issue by stokara** [FluentValidation/FluentValidation#1755]
### FluentValidation version

10.2.3

### Summary

Calling validator.Validate(IValidationContext) does not work as expected.
When calling validate after fixing the data, the result still returns the previous errors.

I ran the test code below using both Framework 4.7.2 and .net 5 with the same result

### Steps to Reproduce

`public class TestClass {
            public string SomeString { get; set; } = "";
            public int SomeNum { get; set; }
        }

        public class TestClassValidator : AbstractValidator<TestClass> {
            public TestClassValidator() {
                RuleFor(x => x.SomeNum).GreaterThan(0).WithMessage("Num must be greater than 0");
                RuleFor(x => x.SomeString).NotEmpty();
            }
        }

        public void ValidationTest() {
            var testObj = new TestClass();
            var validator = new TestClassValidator();
            var validationContext = new ValidationContext<TestClass>(testObj);
            var result = validator.Validate(testObj);
            Console.WriteLine($"validator.Validate(testObj):{result}");
            var result2 = validator.Validate(validationContext);
            Console.WriteLine($"validator.Validate(validationContext):{result2}");
            Console.WriteLine("Fix Data so Validation should produce no Errors.");
            testObj.SomeNum = 1;
            testObj.SomeString = "not empty";
            var result3 = validator.Validate(testObj);
            Console.WriteLine($"validator.Validate(testObj):{result3}");
            var result4 = validator.Validate(validationContext);
            Console.WriteLine($"validator.Validate(validationContext):{result4}");
        }`

using version 9 the output is:
validator.Validate(testObj):Num must be greater than 0
'Some String' must not be empty.
validator.Validate(validationContext):Num must be greater than 0
'Some String' must not be empty.
Fix Data so Validation should produce no Errors.
validator.Validate(testObj):
validator.Validate(validationContext):

using version 10.2.3 , calling validator.Validate(IValidateContext) retails the validation errors even though they have been cleared:

this is the output:
validator.Validate(testObj):Num must be greater than 0
'Some String' must not be empty.
validator.Validate(validationContext):Num must be greater than 0
'Some String' must not be empty.
Fix Data so Validation should produce no Errors.
validator.Validate(testObj):
validator.Validate(validationContext):Num must be greater than 0
'Some String' must not be empty.

**Comment by JeremySkinner** [comment]
Hi there, that's expected.

That happens because you're re-using context instances between validators. You shouldn't do this- you should instantiate a new context each time.

For some background information, this happens because a single list of errors is stored in the context in v10. The validators add to this list when you call `Validate`. This was done for performance reasons, it means child validators don't have to allocate a new collection each time (and a validator could potentially have many child validators, each time you call RuleFor) 

But essentially: don't reuse context instances and you won't have this problem.
