### ISSUE TITLE
Passing context to child collection validators when using `SetValidator()`?

### ISSUE THREAD

**Issue by sakopov** [FluentValidation/FluentValidation#1756]
### FluentValidation version

10.2.3

### ASP.NET version

.NET Core 3.1

### Summary

Is it possible to pass context to child collection validators when using `SetValidator()`?

### Steps to Reproduce

Suppose I have the following models:

```csharp
public class A 
{
    public IEnumerable<B> Bs { get; set; }
}

public class B 
{
    public string Name { get; set; }
}
```

And the following corresponding validators:

```csharp
public class AValidator : AbstractValidator<A>
{
    public AValidator()
    {
        RuleForEach(model => model.Bs).SetValidator(new BValidator());
    }
}

public class BValidator : AbstractValidator<B>
{
    public BValidator()
    {
        RuleFor(model => model.Name).NotNull();
    }
}
```

I would like to be able to pass a list of strings to `BValidator` to validate `Name` property. I looked at `RootContextData` and it seems like I can pass the list to `AValidator` like so:

```csharp
var validationContext = new ValidationContext<A>(new A());
validationContext.RootContextData["MyData"] = new List<string> { "blah1", "blah2" };
var validationResult = await validator.ValidateAsync(validationContext);
```

How can I pass the context down to `BValidator`?

**Comment by JeremySkinner** [comment]
Hi, `RootContextData` is shared across all validators in the hierarchy so it’ll already available for you to access inside BValidator (in a call to `Custom`)

Please note for future reference that this is an issue tracker for bugs in the library, isn’t a discussion/support forum, sorry.
