### ISSUE TITLE
Register generic Validators

### ISSUE THREAD

**Issue by unchase** [FluentValidation/FluentValidation#1760]
### Is your feature request related to a problem? Please describe.

Suppose I have a generic data model (`GenericCommand<TId, TEntityId, TEntity>`) that I want to validate. I'm creating a validator with generic parameters like this:

```csharp
public class GenericCommandValidator<TId, TEntityId, TEntity> : AbstractValidator<GenericCommand<TId, TEntityId, TEntity>> 
	where TEntity : IEntity<TEntityId>
	where TId : IEquatable<TId>
	where TEntityId : IEquatable<TEntityId>
{
	public GenericCommandValidator()
	{
		RuleFor(request => request.EntityId)
			.Equal(default(TEntityId)).WithMessage(x => localizer["Entity is required!"]);
		RuleFor(request => request.Key)
			.Must(x => !string.IsNullOrWhiteSpace(x)).WithMessage(x => localizer["Key is required!"]);

		//...
	}
}
```

Is it possible to register it with DI in such a way that it works?

### Describe the solution you'd like

The generic validator automatically registered with using:

```csharp
public void ConfigureServices(IServiceCollection services)
{
  //...
  services.AddControllers().AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining(typeof(GenericCommandValidator<,,,>)));
  //...
}
```

**Comment by JeremySkinner** [comment]
Hi, there's nothing built-in to do this automatically, as we'd have no way of knowing the intent and how each of the open generic parameters should be handled. You'll need to handle this explicitly yourself as it's not something the library can do for you.
