### ISSUE TITLE
New DI with scope broke integration tests.

### ISSUE THREAD

**Issue by kjiwatrakan** [FluentValidation/FluentValidation#1763]
### FluentValidation version

10.x

### Summary

Upgrading to .NET 5 and using latest Fluent validation 10 broke the integration test.  It doesn't inject properly for some reason.  I can't resolve IvalidatorFactory or something.

### Steps to Reproduce

Create integration test with .NET 5 and latest fluent validation.

**Comment by JeremySkinner** [comment]
This will be an issue with your own code, not with FluentValidation. You need to ensure that you don’t have anything singleton-scoped depend on something that’s request-scoped. Alternatively, register the factory as transient instead. 

See https://github.com/FluentValidation/FluentValidation/issues/1740
