### ISSUE TITLE
Thai language

### ISSUE THREAD

**Issue by kjiwatrakan** [FluentValidation/FluentValidation#1764]
### Describe the solution you'd like

I have a Thai language C# file and updated LanguageManager.cs. Please let me know if I can send that to you some how.

**Comment by JeremySkinner** [comment]
Please open a pull request, thanks

**Comment by kjiwatrakan** [comment]
I can't push to a different branch.  How do I open a pull request from my
local?

- Krit

**Comment by JeremySkinner** [comment]
you need to fork the repository, commit your change to your fork, and then open a PR from there 

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
