### ISSUE TITLE
ValidateAsync and ThrowOnFailures does not appear to be working after upgrade

### ISSUE THREAD

**Issue by ovation22** [FluentValidation/FluentValidation#1771]
### FluentValidation version

10.2.3

### ASP.NET version

.NET 5

### Summary

Recently upgraded a project from 8.6.3 to 10.2.3 and it doesn't appear that ValidateAsync and ThrowOnFailures are working together as I would expect them to. We are receiving a ValidationResult that contains errors, but it is not throwing an exception that previous code relied on.

Is this expected behavior? Do we need to check the results manually and handle appropriately?

### Steps to Reproduce

var result = await myValidator.ValidateAsync(adjustment, options => {
                    options.ThrowOnFailures();
                    options.IncludeAllRuleSets();
                });

ValidateAndThrowAsync doesn't appear to be working as I would expect either. I'm sure it's entirely possible I'm incorrect in my understanding, so please feel to correct me.

**Comment by JeremySkinner** [comment]
It works fine as far as I can see. Please provide all necessary code to reproduce the issue, preferably in the form of a runnable unit test or small sample project.

**Comment by ovation22** [comment]
Hmm, putting together a small sample app with what I think is our scenario it does in fact appear to be working as expected. 

I'll continue to dig into why we are receiving a ValidationResult (Errors: Count = 1, IsValid false) but it is not throwing in the main app. If I can reproduce in the sample app I'll supply it here.

Thank you!

**Comment by JeremySkinner** [comment]
If you override `PreValidate` in your validator, make sure you're definitely running 10.2.0 or newer because of #1736

**Comment by ovation22** [comment]
Looks like this issue was with an abstract base class and not configuring the validator to use a generic. All seems to be working properly on our end now. 

Thanks again!
