### ISSUE TITLE
Document how to do DI outside of ASP.NET

### ISSUE THREAD

**Issue by Sti2nd** [FluentValidation/FluentValidation#1772]
### Is your feature request related to a problem? Please describe.

I spent an hour setting up DI (Microsoft.Extensions.DependencyInjection) for a simple validator and began thinking it was unsupported based on the current documentation and Github issues.

### Describe the solution you'd like

Include the following example somewhere in the documentation

Startup.cs
```c#
// With Microsoft.Extensions.DependencyInjection
builder.Services.AddSingleton<IValidator<User>, UserValidator>();
```

Your class
```c#
public class UserService
{
    private readonly IValidator<User> _validator;

    public UserService(IValidator<User> validator)
    {
        _validator = validator;
    }

    public async Task SomeMethod(User user)
    {
        var validationResult = await _validator.ValidateAsync(user);
    }
}
```

Worst case, simply mention that DI is supported outside ASP.NET.

**Comment by JeremySkinner** [comment]
Would you be willing to submit a pull request to add this?

**Comment by Sti2nd** [comment]
Sure thing! I can begin working on the docs tonight (in about six hours).

I am thinking I should place this info in the "Creating your first validator" section.

**Comment by JeremySkinner** [comment]
Thanks! I’d suggest putting it in a different section as it isn’t related to creating your first validator - maybe put it in a new page under the Advanced section for now and I’ll have a think about where it can go and move it later

**Comment by Sti2nd** [comment]
> It could also mention how to use the FluentValiation.DependencyInjectionExtensions package too.

I saw that package existed, but have no clue how it works, so unfortunately unable to write about it. Have created PR now 👍

**Comment by JeremySkinner** [comment]
The package doesn’t so very much, just a few convenience extension methods for finding the validators in a library and registering them with the service provider:  https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation.DependencyInjectionExtensions/DependencyInjectionExtensions.cs

Saves having to register each one explicitly. 

Thanks for the PR, I’ll try and review it later this week.

**Comment by Sti2nd** [comment]
Thank you for your good work on this package 👏
