### ISSUE TITLE
Reference enclosing object property inside `ChildRules`

### ISSUE THREAD

**Issue by gabrielmaldi** [FluentValidation/FluentValidation#1775]
### Is your feature request related to a problem? Please describe.

I have a parent-child class hierarchy like this:
```cs
public class Purchase
{
    public int Amount { get; set; }
    public Item Item { get; set; }
}
public class Item
{
    public int Tax { get; set; }
}
```
And their validations:
```cs
public class PurchaseValidator : AbstractValidator<Purchase>
{
    public PurchaseValidator()
    {
        RuleFor(x => x.Item).ChildRules(x =>
        {
            x.RuleFor(x => x.Tax).LessThanOrEqualTo(/*purchase.Amount how?*/);
            // Many more rules for properties of Item.
        });
    }
}
```
How can I access the properties of the enclosing type inside `ChildRules`?

### Describe the solution you'd like

I'm not really sure what a potential solution could look like (without introducing breaking changes throughout the project). Maybe introduce a `ChildRules` overload which takes two arguments, one of them being the enclosing object (like `Must()` has)?

```cs
RuleFor(x => x.Item).ChildRules((item, purchase) =>
{
    item.RuleFor(x => x.Tax).LessThanOrEqualTo(_ => purchase.Amount);
});
```

Thanks for looking into this!

### Describe alternatives you've considered

```cs
RuleFor(x => x.Item).ChildRules(x =>
{
    RuleFor(x => x.Amount).GreaterThanOrEqualTo(x => x.Item.Tax);
});
```
But this sets a rule for `Amount`, when the rule should be for `Item.Tax` (and this is of course reflected in the errors returned).

-----

```cs
RuleFor(x => x.Item.Tax).LessThanOrEqualTo(x => x.Amount);
```
But this doesn't group the rule with the other rules defined in `ChildRules`.

**Comment by JeremySkinner** [comment]
ChildRules is only intended for simple use cases. You should switch to using a full child validator to achieve what you're after:

```csharp
public class PurchaseValidator : AbstractValidator<Purchase>
{
    public PurchaseValidator()
    {
        RuleFor(x => x.Item).SetValidator(x => new NestedItemValidator(x));
    }
}

public class NestedItemValidator : AbstractValidator<Item>
{
    public NestedItemValidator(Purchase purchase) 
    {
        RuleFor(x => x.Tax).LessThanOrEqualTo(purchase.Amount);
    }
}
```

**Comment by gabrielmaldi** [comment]
Great, I will go with the full child validator. Thanks!
