### ISSUE TITLE
FluentValidation several Matches() function with Jquery-validate

### ISSUE THREAD

**Issue by chatay** [FluentValidation/FluentValidation#1776]
### FluentValidation version

10.2.3

### ASP.NET version

.net 5

### Summary

**Current behavior**

when password field is filled with data, it just hits the first .Matches() function, it is more like stuck at the first .Matches and does not move to other .Matches functions. As seen in the picture, even I filled out with numbers, it still says please enter numbers between 0-9!

I doubt it may be related to client-side validation with Jquery-validate?
**Expected behavior**

It should hit the other .Matches function as it is matched.

  ```
public static class RuleBuilderExtensions
{
    public static IRuleBuilder<T, string> Password<T>(this IRuleBuilder<T, string> ruleBuilder)
    {
        var options = ruleBuilder
                        .NotNull()
                        .NotEmpty().WithMessage("Boş geçilemez!")
                        .MinimumLength(8).WithMessage("en az 8 karakter")
                        .MaximumLength(16).WithMessage("en fazla 16 karakter")
                        .Matches("[0-9]").WithMessage("0-9 arasında sayı giriniz!")
                        .Matches("[A-Z]").WithMessage("Büyük harf giriniz!")
                        .Matches("[a-z]").WithMessage("Küçük harf giriniz!")

                        .Matches("[^a-zA-Z0-9]").WithMessage("Özel bir karakter giriniz!");

        return options;
    }
}
```
Is it a bug or what?

![image](https://user-images.githubusercontent.com/27813881/124360697-d0d51380-dc33-11eb-8956-a99e26419f4e.png)

### Steps to Reproduce

the issue is reproduced by someone else in dotnetfiddle and it works smoothly however jquery.validate.js and jquery.validate.unobtrusive.js are not included.

https://dotnetfiddle.net/sEHwVo#

**Comment by JeremySkinner** [comment]
No, this isn't a bug in the library. I've just tried it and it works fine - all 3 calls to `Matches` are invoked against the input, as expected. 

If you're seeing different behaviour on the clientside then this will be related to jquery and its handling of regex, not FluentValidation itself.
