### ISSUE TITLE
Transform results

### ISSUE THREAD

**Issue by virzak** [FluentValidation/FluentValidation#1777]
### Is your feature request related to a problem? Please describe.

When parsing an excel row an `object` value can be int, double or string.

A transform validator can determine whether the object is of an allowed type, and if so if it is truly an integer.

Once that processing is done `ValidationResult` is returned and if the object is valid, the transform needs to be performed again, since the `ValidationResult` does not contain the result.

### Describe the solution you'd like

TTransformed? TransformedResult { get; } could be added to `ValidationResult` or a type that derives from it such as TransformedValidationResult<T>

### Describe alternatives you've considered

The alternative to avoiding the transformation is to generate a list of `ValidationFailure`s outside the FluentValidation library.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, but this isn't the right approach to take. 

Validation failures can already store custom information against them (in their `CustomState`) property - you should use this to store the value. You can set it inside your custom validator at the point when you instantiate the validation failure. [See the docs for using custom validators.](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator)

Alternatively, use the `Transform` method, which can be used to apply a transformation before anything else runs. In this case, the ValidationFailure will already contain the transformed value. [Docs on transform](https://docs.fluentvalidation.net/en/latest/transform.html).

**Comment by virzak** [comment]
Hi @JeremySkinner ,

I might not have explained the issue properly. The transformed value is required on success, not failure. So ValidationFailure.CustomState is of no use. Attaching the example code.

```cs
public IntValidator()
{
    RuleFor(x => x).Custom((sampleObj, context) =>
    {

        int parsedInt;
        ValidationFailure? failure = null;
        if (sampleObj is int @int)
        {
            parsedInt = @int;
        }
        else if (sampleObj is double @double && @double % 1 < 0.00001)
        {
            parsedInt = (int)@double;
        }
        else
        {
            var sampleStr = sampleObj?.ToString();
            if (sampleStr is null)
            {
                failure = new ValidationFailure(string.Empty, "Empty") { Severity = Severity.Warning };

                // Compiles, but I don't care
                failure.CustomState = null;

                context.AddFailure(failure);
            }
            else
            {
                if (int.TryParse(sampleStr, out @int))
                {
                    parsedInt = @int;
                }
                else
                {
                    failure = new ValidationFailure(string.Empty, "Could not parse");
                }
            }
        }

        if (failure is null)
        {
            // Does not compile.
            // Need this to be a part of ValidationResult somehow.
            context.CustomState = parsedInt;
        }
    });
}
```

**Comment by JeremySkinner** [comment]
> The transformed value is required on success

This doesn't really make sense...FluentValidation only produces output on failure, not success. A `ValidationResult` is just a wrapper around a collection of failures objects. So if there are no failures there's nothing to pass along to the ValidationResult - you can't set something on the result. One thing you could do I suppose is store it in `context.RootContextData`, but to be honest it sounds like FluentValidation isn't the right tool for you to be using here.

**Comment by virzak** [comment]
Seems to me that this should be a common issue using transformations. In the documentation example, the string is converted to int. It would seem to me that after a successful validation, the user is likely to need the int again.

```cs
public record MyObject (string SomeStringProperty);

public class TransformValidator : AbstractValidator<MyObject>
{
    public TransformValidator()
    {
        Transform(x => x.SomeStringProperty, StringToNullableInt).GreaterThan(10);
    }
    public static int? StringToNullableInt(string value)
      => int.TryParse(value, out int val) ? val : null;
}

class Caller
{
    void Validate()
    {
        var myObject = new MyObject("abc");

        var result = new TransformValidator().Validate(myObject);

        if (result.IsValid)
        {
            var myInt = TransformValidator.StringToNullableInt(myObject.SomeStringProperty)!.Value;
        }
    }
}
```

So `int.TryParse` is being called twice to do the exact same work. The more expensive transformations and the more instances to validate (such as a huge csv / excel spreadsheet) the slower it will be.

I don't think setting context.RootContextData helps, since it is not available in the `ValidationResult` instance.

It is totally possible to have a solution where the string is only parsed once, without using the FluentValidation library, but I was just thinking it could be a common problem.

**Comment by JeremySkinner** [comment]
> I don't think setting context.RootContextData helps, since it is not available in the ValidationResult instance.

It doesn't need to be on the result - if you instantiate the context directly before calling Validate, you can access the context again after validation has been completed. 

> It would seem to me that after a successful validation, the user is likely to need the int again.

If the user needs the int outside of the validator, then it should be parsed/transformed outside of the validator, eg through a surrogate property.
