### ISSUE TITLE
Have the possibility to remove the severity of the message

### ISSUE THREAD

**Issue by Teides** [FluentValidation/FluentValidation#1778]
### Is your feature request related to a problem? Please describe.

Before upgrading to version 10 of fluent validation, I had the following working correctly:

`current.Should().Throw<ValidationException>().WithMessage("*The device name can contain letters, numbers and spaces. The following special characters are also allowed (-, _, .)");`

After upgrading the version all my unit tests stopped working and I had to change them to be like this:

`current.Should().Throw<ValidationException>().WithMessage("*The device name can contain letters, numbers and spaces. The following special characters are also allowed (-, _, .) Severity: Error");`

### Describe the solution you'd like

Have the possibility of removing the severity level, being able to do this:

`ValidatorOptions.Global.Severity = Severity.None;`

### Describe alternatives you've considered

You should consider that if you put WithSeverity it is shown in the error message, in case you do not put the severity level it does not appear in the message.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. 

Typically you shouldn’t assert against the *exception* message but rather the actual *validation failure message* instead (as per the last example on this page: https://docs.fluentvalidation.net/en/latest/testing.html. This message doesn’t include the severity (the severity is a separate property)

Pinging @jchannon who added the severity to the exception message. Would appreciate your thoughts

**Comment by jchannon** [comment]
Agree completely with Jeremy

**Comment by Teides** [comment]
I understand what you are saying, maybe I should leave the complete test so that you can understand my point of view.

```
[Test]
public void ShouldThrowValidationExceptionWithCharactersNotAllowed()
{
    // Arrange
    string name = "/";
    
    // Act
    var actual = new Func<DeviceName>(() => DeviceName.With(name));
    
    // Assert
    actual.Should().Throw<ValidationException>().WithMessage("*Device name can contain letters, numbers and spaces. The following special characters are also allowed (-, _, .) Severity: Error");
}
```

```
...
private DeviceName(string value) : base(value)
{
    DeviceNameValidator.New().ValidateAndThrow(this);
}
...
```
By using the **ValidateAndThrow** method you are adding the severity in the message and before it was not like that.

**Comment by JeremySkinner** [comment]
I understand, but as I mentioned before you really shouldn’t assert against the exception message. Exception messages are informational and aren’t intended for user consumption, nor are they guaranteed not to change between versions. 

The message on the validation failures is the correct thing to be checking: these are the messages generated by the library that are intended to be displayed to users. You can retrieve failure instances from the exception’s `Errors` property, and then perform your assertion against them

**Comment by Teides** [comment]
Thanks @JeremySkinner I just understood what you suggest. I will give a new approach to my solution. Thank you very much to both of you.
