### ISSUE TITLE
Errors property inside ValidationResult of IValidatorInterceptor returns just 1 error message even though there are more than 1 validation errors

### ISSUE THREAD

**Issue by ZawWinHtike** [FluentValidation/FluentValidation#1780]
### FluentValidation version

10.3.0

### ASP.NET version

.net 5

### Summary

Errors property inside ValidationResult of IValidatorInterceptor returns just 1 error message even though there are more than 1 validation errors. This is for .net core web api on .net5. It was working fine with .netcore 2.2 with fluentvalidation version 8.* before.

### Steps to Reproduce

1) Register Interceptor
`public class RequestModelValidatorInterceptor : IValidatorInterceptor
    {
        public IValidationContext BeforeAspNetValidation(ActionContext actionContext, IValidationContext commonContext)
        {
            return commonContext;
        }

        public ValidationResult AfterAspNetValidation(ActionContext actionContext, IValidationContext validationContext,
            ValidationResult result)
        {
            if (result.Errors.IsNullOrEmpty())
            {
                return result;
            }
            
           **//  result.Errors only contains 1 Invalid street error. even though all properties(street, city, country, etc) validation failed.**
            var errorEntries = result.Errors.Select(failure => failure).ToList();

            throw new Exception(errorEntries);
        }
    }`

2) Register Custom Address Validator
`public class AddressRequestValidator : AbstractValidator<AddressRequest>
    {
        static AddressRequestValidator()
        {
            ValidatorOptions.Global.CascadeMode = CascadeMode.Stop;
        }

        public AddressRequestValidator()
        {
            RuleFor(p => p.Street)
                .ValueRule()
                .MaximumLength(52)
                .WithMessage("Invalid Street");

            RuleFor(p => p.City)
                .ValueRule()
                .MaximumLength(32)
                .WithMessage("Invalid City");

            RuleFor(p => p.State)
                .ValueRule()
                .MaximumLength(100)
                .Matches(@"^$|^[0-9a-zA-Z]{2,3}$")
                .WithMessage("Invalid State");

            RuleFor(p => p.Country)
                .ValueRule()
                .MaximumLength(100)
                .Matches(@"^$|^[a-zA-Z]{2}$")
                .WithMessage("Invalid Country");

            RuleFor(p => p.PostCode)
                .ValueRule()
                .MaximumLength(10)
                .WithMessage("Invalid PostCode");
        }
    }`
3) Register fluentvalidation in startup.cs
services.AddMvc(options =>
                {
                    options.EnableEndpointRouting = false;
                })
                .AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.Formatting = Formatting.Indented;
                    options.SerializerSettings.ContractResolver = new JedisPropertyNamesContractResolver(_hostingEnvironment);
                })
                .AddFluentValidation(
                    fv =>
                    {
                        fv.DisableDataAnnotationsValidation = true;
                        fv.RegisterValidatorsFromAssemblyContaining<BookingRequestValidator>();
                        fv.RegisterValidatorsFromAssemblyContaining<UpdateUserProfileRequestModelValidator>();
                    })
4) Invoke api endpoint that accept AddressRequest object with CustomizeValidator(Interceptor = typeof(RequestModelValidatorInterceptor))]

**Comment by JeremySkinner** [comment]
I can’t reproduce this - it seems likely to be an issue with your code rather than with FluentValidation. 

If you’ve debugged this throughly yourself and you believe this not to be the case then please provide a small, runnable sample project in a GitHub repo that reproduces the issue

**Comment by JeremySkinner** [comment]
Oh, you’ve set CascadeMode to `Stop`. This means your validator will only ever return 1 error (it stops after the first failure occurrs). This is the issue - remove this and it’ll return multiple failures. 

Please ensure you have thoroughly read the documentation on setting the cascade mode: https://docs.fluentvalidation.net/en/latest/conditions.html?highlight=Cascade#setting-the-cascade-mode
