### ISSUE TITLE
To verify a value of an instance without a real instance.

### ISSUE THREAD

**Issue by alexinea** [FluentValidation/FluentValidation#1786]
### Is your feature request related to a problem? Please describe.

We usually get a value that will be part of an instance that is about to be created (or will be created a long time later). We need to verify this value, but we do not have a complete example in our hands (which will contain the verified value).

In the previous version of 9.5.x, I could implement this function based on FluentValidation in some clever ways, but I found that these ways are no longer valid in 10.x.

So I want to ask, how to implement this function in 10.x (without considering the context of the instance). Or is this a new feature?

Thx.

### Describe the solution you'd like

```c#
// Current: Verify the complete example
var validator = new CustomerValidator();
validator.Validate(customer);
```

```c#
// Request:
var validator = new CustomerValidator();
validator.ValidateOne("My Address", "Address");
// or
validator.ValidateOne("My Address", c => c.Address);
```

**Comment by JeremySkinner** [comment]
Hi, FluentValidation is a tool for validating the properties of an object - this isn't a supported or intended use case, sorry.

**Comment by alexinea** [comment]
`IncludeProperties` is a good idea. I'll try.

**Comment by alexinea** [comment]
`IncludeProperties` is indeed what I need, thx a lot.

I used NCC Natasha to encapsulate single-value verification for FluentValidation.

The code is in [FluentValidationCore.cs](https://github.com/cosmos-loops/cosmos-validation/blob/master/src/Cosmos.Validation.Sinks.FluentValidation/Cosmos/Validation/Internals/FluentValidationCore.cs) and line 124.
