### ISSUE TITLE
Rule Stop By convention

### ISSUE THREAD

**Issue by sianmace** [FluentValidation/FluentValidation#1787]
### Is your feature request related to a problem? Please describe.

I have read the reasons behind the depreciation of StopOnFirstFailure and understand your reasoning.
(https://github.com/FluentValidation/FluentValidation/issues/1558)

My question is, would it be possible to set the Rule by convention rather than have to specify for each rule?

### Describe the solution you'd like

Im unsure how you would implement, but some rule conventions may make code cleaner

**Comment by JeremySkinner** [comment]
Hi, you can do this by setting the cascade globally in your application startup: `ValidatorOptions.Global.CascadeMode = CascadeMode.Stop;`

https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode

**Comment by sianmace** [comment]
Ah great, sorry to bother you, i didnt see this mentioned on the other thread about the depreciation of the setting.
I should have read through the docs again! 
Thanks again.

**Comment by JeremySkinner** [comment]
yeah the behaviour change only affects users who were previously using StopOnFirstFailure at the class-level. It doesn’t make a difference to the rule-level or the global-level

**Comment by sianmace** [comment]
I just hadn’t realised that was there at all, and was simply using the class level. Until I have now upgraded and seen the depreciation.

Many thanks, and great library

**Comment by sianmace** [comment]
Actually, im not sure i can do what i was thinking i could.

I want to set the rule for the whole validator to continue - so i get an error for each property (that has an error), but stop on the first failiure for each property.

So in essence, only getting one error for each property.

I have tried setting
ValidatorOptions.Global.CascadeMode = CascadeMode.Stop;
CascadeMode = CascadeMode.Continue;

Thinking that would set it globally for the properties but individually for the validatior classes.
This doesnt give the solution i expected.

So its there a way, to set basically to one error per property - without having to set it on each property? 
and other than using the depriciated setting

**Comment by JeremySkinner** [comment]
Hi, you either need to explicitly specify `Stop` at each individual rule level (this is the recommended approach, as it's clear what's happening) or you can set the legacy `StopOnFirstFailure` (not Stop) globally.

**Comment by sianmace** [comment]
ok thats fine, just wanted to be clear.

I am used to using conventions for things - so i dont personally see it confusing to set rules by convention but i understand your reasoning
