### ISSUE TITLE
Issue in Caching messages for multilingual application. #1788

### ISSUE THREAD

**Issue by AditiG12** [FluentValidation/FluentValidation#1789]
### FluentValidation version

8.2.0

### ASP.NET version

4.8

### Summary

I have reported a issue https://github.com/FluentValidation/FluentValidation/issues/1788. I have some queries so opening the same as bug.

### Steps to Reproduce
Currently we are working in multilingual application supporting 16 languages but here we are facing issues with validation messages.
Scenario1: If a user fires validation in English culture and then change the application culture to German and again fires validation than messages are shown in correct culture. Now suppose user, log out from the application and re-login, then again fire validations. This time user does not see the messages in the expected language, Instead the messages are shown last logged in language, which was German in our case.

Describe the solution you'd like
Question 1: Are there any provision in the fluent Validations to support the multi-lingual messages?

Question 2: What will be the performance impact, if we do not fetch cached messages or simply if we remove caching in our application?

Hi
Thanks for the quick reply. We are setting the current culture in the the thread. Also, for the messages we have written as below:
RuleFor(model => model.FirstName)
.NotEmpty().WithMessage("Field cannot be empty"))

**Comment by JeremySkinner** [comment]
@AditiG12 Please edit the issue and provide all of the requested information. I can't help you if you don't provide any steps to reproduce the problem...

**Comment by AditiG12** [comment]
I want to open the issue "https://github.com/FluentValidation/FluentValidation/issues/1788".

**Comment by JeremySkinner** [comment]
Please provide the information that's been requested. I can't help you if you don't do that.

**Comment by AditiG12** [comment]
We are working in the multilingual application supporting 16 languages. But there is an issue when concurrent users are working. 
1. Suppose If user U1 using english language, fire the validation then he change the culture to say German and then again fire validation - User will be shown the messages in the German culture. 
2. Now suppose user log out from the application and another user U2 (which belongs to Spanish culture) login and fire validation, user will now see the messages German culture which is a issue.

Also, we are using harcoded messages which are stored in DB using .WithMessage attribute() . So do fluent provides us any way to solve the issues of messages in a multilingual application ?

**Comment by JeremySkinner** [comment]
You can't hard-code the message using `WithMessage`. This won't be localized. You need to follow the instructions I've already linked you to in the localization page in the documentation. 

If you can't provide steps to reproduce the problem (which I've asked you for several times) then I'm going to close this again.

**Comment by AditiG12** [comment]
Hi 
Thanks for providing the links associated with it. Also, I have gone through the link and discover solution this can be implemented in the current application. But can you please help me with fluent version in which "FluentValidation.Resources.LanguageManager" class was introduced.

**Comment by JeremySkinner** [comment]
7.0
