### ISSUE TITLE
Invalid error message for ScalePrecision validation

### ISSUE THREAD

**Issue by SatsunkevichAlex** [FluentValidation/FluentValidation#1791]
### FluentValidation version

10.3.0

### Summary

For number 0.01 and validation setting ScalePrecision(1, 3) error message will be
Exp: 'Discount' must not be more than 3 digits in total, with allowance for 1 decimal. 0 digits and 2 decimals were found.
Act: 'Discount' must not be more than 3 digits in total, with allowance for 1 decimals. -1 digits and 2 decimals were found.
 
I created pull request with possible way to fix it.
https://github.com/FluentValidation/FluentValidation/pull/1790

### Steps to Reproduce

add this case to _Scale_precision_should_not_be_valid_ test

```
result = validator.Validate(new Person { Discount = 0.01M });
result.IsValid.ShouldBeFalse();
result.Errors[0].ErrorMessage.ShouldEqual("'Discount' must not be more than 3 digits in total, with allowance for 1 decimal. 0 digits and 2 decimals were found.");
```

**Comment by JeremySkinner** [comment]
10.3.1 has been released with this fix
