### ISSUE TITLE
Impossible to use RuleSets in Automatic validation for Web API .NET 5

### ISSUE THREAD

**Issue by sfilippov** [FluentValidation/FluentValidation#1792]
### FluentValidation version

9.5.4

### ASP.NET version

5.0

### Summary

**RuleSetForClientSideMessages** and **CustomizeValidator** attributes don't work for controllers endpoints to use rule sets in automatic validator

### Steps to Reproduce

There are two rule sets: V1, V2 with two endpoints for it
I have two controller endpoints for each rule set and try to use it
```csharp        
        [HttpPost("order/v1")]
        [RuleSetForClientSideMessages("V1")]
        public async Task<IActionResult> NewOrder(OrderDto order)
        {
            var result = await _service.ProcessNewOrder(order);
            return this.Result(result);
        }
```

Another way to use inline attribute CustomizeValidator for dto model has same result with non-working rule sets.
```csharp        
        [HttpPost("order/v2")]
        public async Task<IActionResult> NewOrderV2([CustomizeValidator(RuleSet = "V2")] OrderDto order)
        {
            var result = await _service.ProcessNewOrderV2(order);
            return this.Result(result);
        }
``` 

Both endpoints use both rule sets, nothing changed after adding rulesets in validator.

There is a solution with using manual validator but do someone know the solution without using manual validation?

**Comment by JeremySkinner** [comment]
Hi,

First just to clarify, `RuleSetForClientSideMessages` and `CustomizeValidator` perform different tasks.

- `RuleSetForClientSideMessages` is for integration with asp.net's client-side validation. It doesn't change how the validator is run.
- `CustomizeValidator` can be used to change which ruleset is run when automatic validation is invoked.

Applying `CustomizeValidator(RuleSet = "V2")]` to the parameter tells FluentValidation to run the "V2" ruleset in your validator. If this isn't the behaviour that you're seeing then you've probably set something up incorrectly - I'd suggest you override the `Validate` method in your validator, put a breakpoint in there and check the `Selector` property - make sure the right ruleset is coming through in here.

**Comment by sfilippov** [comment]
Yes, it's works only by CustomizeValidator with coma as a separator for rules
Thank you, @JeremySkinner !
