### ISSUE TITLE
Validators of IEnumerable not executed

### ISSUE THREAD

**Issue by David-V-Spencer** [FluentValidation/FluentValidation#1794]
### FluentValidation version

10.3.0

### ASP.NET version

.Net 5

### Summary

I have a basic implementation of WeatherForecast sample from a new API project that I am using as example project for various things such as FluentValidation and other standards in team projects.

I create a controller that takes an IEnumerable of  WeatherForecast model as a request body.

The exact same code and validator setup works when the Validator is set as implementing `AbstractValidator<List<WeatherForecast>>` but fails when implementing as `AbstractValidator<IEnumerable<WeatherForecast>>`.

Initially before I figured out that it was the `IEnumerable` vs `List` type I thought it might have been a registration or configuration issue because it was not getting hit in the debugger.

I tried to register the validator as follows without any difference.
`options.RegisterValidatorsFromAssemblyContaining<WeatherForcastValidator>();`

I also tried to set various configuration combinations on the validators but none seemed to change this behavior.
`ImplicitlyValidateChildProperties`
`AutomaticValidationEnabled;`
`ImplicitlyValidateRootCollectionElements`

It seems unexpected that `IEnumerable`, `List`, or another collection types would break the validator like this.

### Steps to Reproduce

I have a basic model of `WeatherForecast` defined as

    public class WeatherForecast
    {
        public DateTime Date { get; set; }
        public string Summary { get; set; }
        public int? TemperatureC { get; set; }
        public int? TemperatureF { get; set; }
    }

And a Controller accepting this model as a POST Body like

    [HttpPost]
    public async Task<ActionResult<IEnumerable<WeatherForecast>>> Post([FromBody] IEnumerable<WeatherForecast> weatherForecasts)
    {
        return CreatedAtAction(nameof(Get), await WeatherForecastService.PostForecast(weatherForecasts));
    }

And the validator defined as

    public class WeatherForcastValidator : AbstractValidator<IEnumerable<WeatherForecast>>
    {
        public WeatherForcastValidator()
        {
            RuleForEach(weatherForecast => weatherForecast).ValidTemperatures();
            RuleForEach(weatherForecast => weatherForecast).ValidForecastDateRange(4);
        }
    }

While registering the Validators in Startup.cs as

      services.AddControllers()
          .AddFluentValidation(options =>
          {
                 options.RegisterValidatorsFromAssembly(typeof(WeatherForcastValidator).Assembly);
          });

If the AbstractValidator base class is defined with type as `AbstractValidator<IEnumerable<WeatherForecast>>` the WeatherForecastValidator constructor will never be hit in the debugger and no validation will occur. 

If simply changing the `IEnumerable` to `List` in the defined type such as `AbstractValidator<List<WeatherForecast>>` the WeatherForecastValidator constructor is hit in the debugger and validation will occur as expected.

**Comment by JeremySkinner** [comment]
Hi,

This is the expected behaviour. This isn't really an issue with FluentValidation, but is a side effect of how ASP.NET's model binding process works.

If your action parameter is an `IEnumerable<T>`, then internally MVC will instantiate a `List<T>` - MVC's model binding process doesn't actually know your intent when you specify an interface as an action method parameter, so it guesses and creates a List, which is the type that's then passed by MVC into FluentValidation.

Personally I'd always recommend using explicit concrete types as action method parameters because of this (ie explicitly specify either `List<T>` or `T[]` as your action parameter). If your validator type directly matches the type of the action parameter (ie both are using List), then this will all just work without any issues.

**Comment by JeremySkinner** [comment]
However if you want to continue to use IEnumerable in your validator then you'll need to be explicit about this in your container registration. 

The `T` in `AbstractValidator<T>` is contravariant, so you should be able to register a mapping with the container for `IValidator<List<WeatherForecast>>` to WeatherForcastValidator (where StudentValidator inherits `AbstractValidator<IEnumerable<T>>`). If you set this up with an explicit call to `services.AddScoped` in your application startup routine then I believe this will allow you to workaround this limitation. Something like:

```csharp
services.AddScoped<IValidator<List<WeatherForecast>>, WeatherForecastValidator>();
```

**Comment by David-V-Spencer** [comment]
Thanks. I will open a PR when I get a free moment.

**Comment by David-V-Spencer** [comment]
@JeremySkinner I have created a local branch with a note comment added to the Collections and ASPNET documentation files like so:
![image](https://user-images.githubusercontent.com/29984571/128240791-6621b9eb-a04a-42ca-a756-19ea1925f371.png)

Unfortunately, I am unable to push my branch and get `ERROR: Permission to FluentValidation/FluentValidation.git denied to David-V-Spencer.` when I try.

I did check the [contributing guidelines](https://github.com/FluentValidation/FluentValidation/blob/41a4996e2b2711779d04b424a951df5034cbe130/.github/CONTRIBUTING.md) and clicked through the [Contributor License Agreement](https://cla.dotnetfoundation.org/) but don't see how to sign the agreement although I did link my GitHub account.

Am I missing something to push my branch to origin and open a PR for the documentation changes?

**Comment by JeremySkinner** [comment]
You’d need to fork the repository (using the GitHub fork button), and then push to your fork. You’ll then be able to open a PR from there 

generally when contributing to an oss project you don’t push to the origin directly, but contributors use their own forks instead (unless part of the project’s core team. hope that makes sense!

**Comment by David-V-Spencer** [comment]
Created a PR https://github.com/FluentValidation/FluentValidation/pull/1796
