### ISSUE TITLE
Testing infinite length strings

### ISSUE THREAD

**Issue by jzabroski** [FluentValidation/FluentValidation#1795]
### Is your feature request related to a problem? Please describe.

I currently extend the existing FluentValidation infrastructure with my own extension method for testing string min and max length.  The signature is:

```c#
public static void ShouldHaveMinAndMaxLength<T>(this IValidator<T> validator, Expression<Func<T, string>> expression, int minLength, 
            int maxLength, bool allowNullOrWhitespace = false)
            where T : class, new()
```

This works great, and I've been using it this way for about two years.  Recently as today, my tests started failing due to `System.OutOfMemoryException` because I guess I am allocating too many chunks of strings in my tests.  (I have around 4,000 tests in my code base now, of which maybe 1,000 are FluentValidation tests vs. half has much two years ago).

I am curious if there is a more elegant way to test infinite length strings like a C# property backed by a SQL Server `NVARCHAR(MAX)`.  Obviously, C# has real physical constraints on the amount of contiguous memory available in order to map a string from SQL Server to memory.

Apologies if I missed something in the docs that covers this.  I'm actually surprised I don't know the answer to this myself, but was wondering if there is some trick I can use.

### Describe the solution you'd like

No need to extend API, just looking to see if you've encountered this as well and what your solution is or would be.

### Describe alternatives you've considered

Skip testing it entirely by mapping infinite length to maxLength = -1 and testing a string of length `string.Empty.PadRight(-1, ' ')` which is an identity function that returns string.Empty, thereby just validating that the string is at least of a minimum length.

Alternatively, generating a string of length `short.MaxValue` instead of `int.MaxValue` and pray that there is contiguous blocks of memory to allocate across all infinite length strings in my validators.

### Additional Context

This is not really a deal breaker, it's just I feel my code is a bit ugly in this corner case that I hadn't really considered before.

**Comment by JeremySkinner** [comment]
This isn't something I can help with, sorry
