### ISSUE TITLE
Count validation for collections

### ISSUE THREAD

**Issue by AdemCatamak** [FluentValidation/FluentValidation#1797]
### Describe the solution you'd like

I need to filter the collection according to certain specs and I need to check that the number of elements in the filtered collection aligns with certain rules. For example: being in a certain range, being greater than a certain value, being less than a certain value etc.

Let's say I have an order basket. Order basket contains a list of products. I need to be able to check that the number of products that are more expensive than $100 is not more than 5.

```CSharp
public class BasketValidator : AbstractValidator<Basket>
{
  public BasketValidator()
  {
    RuleFor(b=> b.BasketLines)
      .MaximumCount(5, line => line.Price > 100);
  }
}
```

If this feature request is accepted, I would like to make the necessary development and contribute to the project.

Kind Regards

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this can already be done by using `Must`, so this probably isn't something we'd accept into the core library:

```csharp
RuleFor(b=> b.BasketLines)
  .Must(lines => lines.Count(line => line.Price > 100) <= 5);  
``` 

Thanks for wanting to be involved though!
