### ISSUE TITLE
Can I make complex properties errors be an object instead a prefix.propertyName in main error object ?

### ISSUE THREAD

**Issue by joaquimpedro** [FluentValidation/FluentValidation#1798]
### Is your feature request related to a problem? Please describe.

Can't transform chained validators errors into object js easily.

### Describe the solution you'd like

Hi, I'm using fluentvalidation 9.5.0 with .net core 3.1

I have this validators: 
```
public class CustomerValidator : AbstractValidator<Customer> {
  public CustomerValidator() {
    RuleFor(customer => customer.Name).NotNull();
    RuleFor(customer => customer.Address).SetValidator(new AddressValidator());
  }
}

public class AddressValidator : AbstractValidator<Address> {
  public AddressValidator() {
    RuleFor(address => address.Postcode).NotNull();
    RuleFor(address => address.Street).NotNull();
  }
}
```

with the following response:
```
  "errors": {
    "Name": [
      " 'Name' must not be empty."
    ],
    "Address.Postcode": [
      " 'Postcode' must not be empty."
    ]
    "Address.Street": [
      " 'Street' must not be empty."
    ]
  }
```

My question is: Is possible to make Address an object with it erros. Like this:

 ```
  "errors": {
    "Name": [
      " 'Name' must not be empty."
    ],
    "Address": {
       "Postcode": [
           "'Postcode' must not be empty."
       ],
       "Street": [
           "'Street' must not be empty."
       ],
       // other address properties errors
    }
  }
```
Thanks for the attention.

**Comment by JeremySkinner** [comment]
Hi, not out of the box; you’d need to process the `ValidationResult` yourself to manually construct the data structure that you want.

**Comment by joaquimpedro** [comment]
@JeremySkinner thanks a lot for you reply!
I didn't understand well what i need to do.
Can you link or show some reference how to do this?

**Comment by JeremySkinner** [comment]
I don't have any full examples I'm afraid as this is nonstandard. FluentValidation doesn't generate any JSON itself; the response for your first example is actually generated by ASP.NET, not by FluentValidation. So you'll need to manually invoke the validator, loop over its errors collection and construct the data structure you want. 

Please note for future reference that this is an issue tracker for tracking bugs in FluentValidation, it isn't for general support, sorry.
