### ISSUE TITLE
How does the validation make available work on binding properties in razor pages project?

### ISSUE THREAD

**Issue by neozhu** [FluentValidation/FluentValidation#1799]
### FluentValidation version

10.x

### ASP.NET version

asp.net core 5 razor pages

### Summary

![image](https://user-images.githubusercontent.com/1549611/128791710-5ec3ccc1-7b44-422d-9702-dc7698dcc162.png)
This is   I defined validation rule.
![image](https://user-images.githubusercontent.com/1549611/128791845-0c9d0cbc-a271-44be-818d-d518ff0661e2.png)
This is razor page form  binding code .

### Steps to Reproduce

following configuration
![image](https://user-images.githubusercontent.com/1549611/128792007-550bd385-95c6-4df7-95bb-b44232564f15.png)
![image](https://user-images.githubusercontent.com/1549611/128792096-c79caf92-e54d-4f04-aaca-79fc4a8a18d4.png)
![image](https://user-images.githubusercontent.com/1549611/128792165-9aab7f01-03a7-4348-8e53-112892fe03a9.png)

Is there something wrong? please tell me, thanks

**Comment by JeremySkinner** [comment]
Please follow the guidelines in the issue template. 

![BB405DE4-FE40-4915-9E0C-FB0B21B22956](https://user-images.githubusercontent.com/90130/128816044-e1b97fda-b9a1-43f7-ad5c-7b31817205ae.jpeg)
