### ISSUE TITLE
Unable to mock a failed validation with IValidator<T>

### ISSUE THREAD

**Issue by Eric-Bonneau** [FluentValidation/FluentValidation#1800]
### FluentValidation version

10.3.0

### ASP.NET version

.NET Core 3.1

### Summary

Hi,

I'm trying to use Moq v4.16.1 to mock a failed validation.

I have an `AbstractValidator<T>` implementation which depends on another `IValidator<U>`. I want to test two things:
1. The `AbstractValidator<T>` implementation uses `IValidator<U>` as a child validator
2. If the `IValidator<U>` fails validation, the `AbstractValidator<T>` will also fail validation

I'm trying to mock the `Validate(IValidationContext)` method of the `IValidator<U>` to return a `ValidationResult` containing `ValidationFailures`. Normally if the `ValidationResult` has errors in it, the result will be a failed validation. I can't seem to get this to work, and it used to work in v8.6.1 of FluentValidation.

I'm using `VerifyAll` and strict mocks to make sure that my mock is getting called. It seems that using both `TestValidate` and `Validate` call my mocks, but I'm never able to get a validation result back that has failures.

I've been trying to figure this out the past two days, but I haven't been able to. So I figured I would reach out to open an issue. 

Please let me know if you need any other information!

Thanks in advance 😄.

### Steps to Reproduce

Here is a runnable unit test for the issue I am experiencing:

```csharp
using FluentValidation;
using FluentValidation.Results;
using FluentValidation.TestHelper;
using Moq;
using Xunit;

namespace MockValidationFailure
{
    public class MockValidationFailureUnitTests
    {
        private readonly Mock<IValidator<ITest>> _childValidatorMock = new Mock<IValidator<ITest>>(MockBehavior.Strict);

        private readonly TestValidator _validator;

        [Fact]
        public void Validate_Test_UsesChildValidator()
        {
            // Arrange
            var validationFailure = new ValidationFailure(nameof(Test.TestProperty), "something went wrong");

            _childValidatorMock.Setup(m => m.Validate(It.IsAny<IValidationContext>()))
                .Returns(new ValidationResult(new[] {validationFailure}));
            
            // Act
            TestValidationResult<Test> result = _validator.TestValidate(new Test());

            // Assert
            _validator.ShouldHaveChildValidator(t => t, typeof(IValidator<ITest>)); // this works
            result.ShouldHaveValidationErrorFor(t => t); // this doesn't :/
            
            _childValidatorMock.VerifyAll();
        }
        
        public MockValidationFailureUnitTests()
        {
            _validator = new TestValidator(_childValidatorMock.Object);
        }
    }

    public class TestValidator : AbstractValidator<Test>
    {
        public TestValidator(IValidator<ITest> validator)
        {
            RuleFor(v => v)
                .SetValidator(validator);
        }
    }

    public class TestChildValidator : AbstractValidator<ITest>
    {

    }

    public class Test : ITest
    {
        public string TestProperty { get; set; }
    }

    public interface ITest
    {
        string TestProperty { get; }
    }
}

```

I'm not sure if it's related to the validation context changes that were introduced in v10.* of FluentValidation. In v8.6.1 I used to be able to use `It.IsAny<ValidationContext>()` (concrete implementation) which worked. I have also tried to use `Is.IsAny<ValidationContext<Test>>()`, but haven't had any luck with that either.

**Comment by JeremySkinner** [comment]
Hi, you need to change how your mock is set up. Child validators no longer return a validation result directly, but rather call the `AddFailure` method on the context. 

```csharp
_childValidatorMock.Setup(m => m.Validate(It.IsAny<ValidationContext<Test>>()))
	.Callback((IValidationContext context) => ((ValidationContext<Test>) context).AddFailure(validationFailure));
```

Secondly, your mock shouldn't be strict:

```csharp
private readonly Mock<IValidator<ITest>> _childValidatorMock = new Mock<IValidator<ITest>>();
```

Thirdly, your call to `ShouldHaveValidationErrorFor` isn't quite right; it needs to property the property:

```csharp
result.ShouldHaveValidationErrorFor(t => t.TestProperty)
```

All that being said, I *highly* recommend *not* mocking validators. Testing the interaction between validators is brittle - it's much better to treat validators as a black box and pass them known specific good/bad input and assert on the results. 

If you *really* feel you need to setup mock validation results, at a minimum I'd suggest you use `InlineValidator` rather a  mocking library, as that way you don't need to mock the internal interactions of FluentValidation:

```csharp
[Fact]
public void Validate_Test_UsesChildValidator()
{
	var childValidator = new InlineValidator<ITest>();
	childValidator.RuleFor(x => x.TestProperty)
		.Custom((x, context) => context.AddFailure("something went wrong"));

	var validator = new TestValidator(childValidator);

	TestValidationResult<Test> result = validator.TestValidate(new Test());
	result.ShouldHaveValidationErrorFor(t => t.TestProperty);
}

```

**Comment by JeremySkinner** [comment]
https://github.com/FluentValidation/FluentValidation/issues/1739

**Comment by Eric-Bonneau** [comment]
I was able to get it to work finally using the `Callback`. I had to also chain my original `Returns` with that statement and it's working as expected.

TIL about the `InlineValidator`! I think that will be the best middleground for what we wish to achieve with our unit tests. 👍

Thanks so much @JeremySkinner for the rapid response and feedback! You're a life saver 😄.
