### ISSUE TITLE
New line character breaks validation of email

### ISSUE THREAD

**Issue by Trolejbus** [FluentValidation/FluentValidation#1809]
### FluentValidation version

10.3.0

### ASP.NET version

.NET 5

### Summary

When using build-in EmailAddress() validation string which contains new line characters breaks validation (ex. "ugly things\ntest@test.com"). If at least one line of validated string will be valid email, validation for property will pass. By this bug I have set invalid property in my db in ASP.NET application. To each EmailAddress I have to add my custom rule to validate against new line characters.

### Steps to Reproduce

Reproduced in dotnetfiddle:
https://dotnetfiddle.net/kwJAyB

**Comment by JeremySkinner** [comment]
Hi, this is expected/intentional. The email validator just does a simple anything@anything check. Please see the docs for more details:

See: https://github.com/FluentValidation/FluentValidation/issues/1643
