### ISSUE TITLE
Enum values validation should be by default

### ISSUE THREAD

**Issue by rodion-m** [FluentValidation/FluentValidation#1813]
### Is your feature request related to a problem? Please describe.

Thank you guys for a great tool! Here is a little suggestion. \
I just started to use this lib and discovered that enum values validation is not working by default (I even not found how to enable it). The only one way is to set enum validation explicitly using `RuleFor(x => x.value).IsInEnum()`. 

### Describe the solution you'd like

I suggest to make enum values validation by default or add this option to a configuration like `EnableEnumValuesValidation`.

**Comment by JeremySkinner** [comment]
I don’t really understand what you’re asking. All of FluentValidation’s rules have to be explicitly configured using RuleFor; enum validation is no different.

**Comment by rodion-m** [comment]
@JeremySkinner Thank you for a fast response! Is there any way to make enum values validation automatically?

**Comment by JeremySkinner** [comment]
@rodion-m I've already answered this above; FluentValidation doesn't support the concept of "automatic" validation - everything is configured by using `RuleFor`. [Please read the documentation](http://docs.fluentvalidation.net)
