### ISSUE TITLE
Unable to use AbstractValidator in controllers request

### ISSUE THREAD

**Issue by Edgaras91** [FluentValidation/FluentValidation#1814]
### FluentValidation version

10.0.

### ASP.NET version

NET Core 3.1

### Summary

When trying to use [FromQuery] attribute in controller on a model that inherits AbstractValidator, it doesn't read model properties.

### Steps to Reproduce

A controller that looks like this:

```
   public async Task<ActionResult<PaginatedList<AccountDto>>> GetPaged([FromQuery] GetAccountPagedQuery query)
        {
            return await Mediator.Send(query);
        }
```
above GetAccountPagedQuery only has 1 property:
`public string EmailAddress { get; set; }`

But it inherits "PagedQuery", which inherits its own validator that inherits from AbstractValidator.

```
   public class GetAccountPagedQuery : PagedQuery<GetAccountHeadersPagedQuery>
    {
        public string EmailAddress { get; set; }
    }
```

Expected for the Swagger (or another alternative) to document this route parameters as "EmailAddress" (string, query), but instead, it documents as "request" (object, query)

I would really like to not detach the validator from this request model, as it saves.
Is there maybe an AspNetCore attribute that would fix this issue?

**Comment by JeremySkinner** [comment]
Hi there, we don't provide any integration with swagger; you'll need to open an issue with whoever maintains the library that integrates FluentValidation with swagger. This issue tracker is only for bugs in the core FluentValidation library.

**Comment by Edgaras91** [comment]
Let's take swagger out of it. Testing above using postman fails just the same - controller is not able to receive the EmailAddress query parameter when AbstractValidator is involved in the model. Tested using below route:
https://localhost:44376/accounts?EmailAddress=123

It works it doesn't inherit abstract validator, but as soon as it does, it gives bad request error:
{
    "errors": {},
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-ba5421fe4860b94a827669ac170fbfa0-3339c3c775d45e46-00"
}

**Comment by JeremySkinner** [comment]
That looks like the expected behaviour. If you have a validator wired up for the model, then it'll be invoked and MVC will then generate a bad request if you're using the [ApiController] attribute. I expect you'll need to do one of the following:

- Either don't register a validator for that class
- Or disable automatic bad request responses which are a feature of asp.net: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#disable-automatic-400-response
- Or just use the CustomizeValidator attribute to skip the validator in this case (see https://docs.fluentvalidation.net/en/latest/aspnet.html#validator-customization)

**Comment by Edgaras91** [comment]
Thanks, I will try your suggestions and update this for future visitors

**Comment by Edgaras91** [comment]
Your option 2 made the controller to work:
```
services.ConfigureApiBehaviorOptions(options => { options.SuppressModelStateInvalidFilter = true; })
```
I was able to test with post man and the query parameter did fill the request model as intended.

That leaves me with 2 issues.

- I have disabled automatic 400 response
- Swagger documentation not recognising the model.

![image](https://user-images.githubusercontent.com/32236075/130238633-9fc95b24-4129-4842-a660-4a81cee138df.png)

I appreciate that you may not help with swagger issue as it could be **their** lack of support for such object models, but hoping if
you can think of another solution for the first problem, in such that I could keep my custom validations, as I need them on such models.

**Comment by Edgaras91** [comment]
Reading more closely into your referenced documentation, disabling automatic 400 response, disables this check:
```
if (!ModelState.IsValid)
{
    return BadRequest(ModelState);
}
```
So is it safe to assume that inheriting AbstractValidator makes the ModelState invalid?
Can I disable this part of the model for the controller not to validate?

**Comment by JeremySkinner** [comment]
> So is it safe to assume that inheriting AbstractValidator makes the ModelState invalid?

If you've enabled auto-validation, yes.

> Can I disable this part of the model for the controller not to validate?

Yes, either by turning off auto-validation globally, or on an individual model by using the `Skip` option that I linked you to above

**Comment by Edgaras91** [comment]
Yes, I am calling AddFluentValidation.

skip like this did nothing:
 `     public async Task<ActionResult> GetPaged([CustomizeValidator(Skip = true)] [FromQuery] GetAccountPagedQuery query)`
Not sure why inheriting an abstract validator makes the model invalid, even when there are no rules for the property...
I still will want the model to auto to validate correctly, hence keeping this AbstractValidator inheritance.

**Comment by JeremySkinner** [comment]
> Not sure why inheriting an abstract validator makes the model invalid, even when there are no rules for the property..

That doesn't sound right to me. If there are no rules in the validator, then nothing will run and it won't be marked as invalid, so chances are that this isn't coming from FluentValidation at all, if there are no rules. 

Please can you put together a small, standalone sample project that reproduces the issue?

**Comment by Edgaras91** [comment]
Sorry for the delay, here it is:

[SampleApi.zip](https://github.com/FluentValidation/FluentValidation/files/7022949/SampleApi.zip)

**Comment by JeremySkinner** [comment]
I've had a quick play with this, and the error isn't coming from FluentValidation, it's coming from somewhere inside ASP.NET itself. I'll try and find a bit of time to dig into it further to see if I can understand it better, but as it's coming from ASP.NET there's probably not going to be much I can do. I'll let you know if I find anything

**Comment by JeremySkinner** [comment]
Right, I think I understand the issue a bit more. The problem isn't coming from FluentValidation directly - the problem is that your model *inherits* from AbstractValidator, so ASP.NET's model binding *will attempt to bind the properties defined on the validator class itself*, which it can't do.  

This isn't really the right way to be handling model binding - you need to separate the model and the validator into separate classes. 

The class that you bind to from the query string should be a simple DTO; it shouldn't inherit from AbstractValidator. The validator should be defined a *separate standalone class*. If you check the exampls in FluentValidation docs you'll see that the model and the validator are always separate classes. 

If you make this change, it'll work correctly.

**Comment by JeremySkinner** [comment]
So something like this:

```csharp
// No longer inherits from the validator. 
public abstract class PagedQuery<T> where T : PagedQuery<T>
{
    public int PageNumber { get; set; } = 1;
    public int PageSize { get; set; } = 10;
}

public abstract class PagedAbstractValidator<T> : AbstractValidator<T> where T : PagedQuery<T>
{
    protected PagedAbstractValidator()
    {
        RuleFor(x => x.PageNumber)
            .GreaterThanOrEqualTo(1);

        RuleFor(x => x.PageSize)
            .GreaterThanOrEqualTo(1);
    }
}

public class AccountPagedQuery : PagedQuery<AccountPagedQuery>
{
    public string EmailAddress { get; set; }
}

public class AccuntPagedQueryValidator : PagedAbstractValidator<AccountPagedQuery>
{
    public AccuntPagedQueryValidator()
    {
        // Inherits all the rules from the base class.
        RuleFor(x => x.EmailAddress).EmailAddress();
    }
}
```

**Comment by Edgaras91** [comment]
Thank you very much for finding time to look into this, I really appreciate it!

I think it's only "CascadeMode" property that ASP.NET is picking up from abstract validator inheritance and is struggling to make sense of. I believe Property is obsolete too. If you are interested, I would suggest seeing if removing it fixes the issue, and then even maybe get rid of it if possible, to fix this kind of bug, but I appreciate it either way.

For now, I ended up separating it out differently like this, **key part is the GetPaged method**:
```

        public async Task<PaginatedList<AccountDto>> GetPaged(**GetAccountsPagedRequest** request)
        {
            var query = new GetAccountPagedQuery
            {
                EmailAddress= request.EmailAddress
            };

            return await Mediator.Send(query);
        }

//Query
 public class GetAccountsPagedQuery : PagedQuery<GetAccountsPagedQuery>
...
 public abstract class PagedQuery<T> : PagedAbstractValidator<T> where T : PagedQuery<T>
...
 public abstract class PagedAbstractValidator<T> : AbstractValidator<T> where T : PagedQuery<T>
...
//Seperate Validator
 public class GetAccountsPagedQueryValidator : AbstractValidator<GetAccountHeadersPagedQuery>
...
```

Above results in 2 validators, 1 for Paged query that I never need to worry about
and optional per query validators (GetAccountsPagedQueryValidator). 

The thing I wanted to avoid is a brand new request model (**GetAccountsPagedRequest**) that would have 100% the same properties as the GetAccountPagedQuery.

**Comment by JeremySkinner** [comment]
> I believe it's obsolete too.

It's not obsolete: https://docs.fluentvalidation.net/en/latest/conditions.html#setting-the-cascade-mode

> to fix this kind of bug

Just to clarify, this isn't a bug. ASP.NET's model binding is doing what's expected of it; it attempts to bind all public properties of the class that you've supplied. A validator isn't intended to be bindable, so you shouldn't include it in the inheritance hierarchy of any input model. 

Also just to point out that inheriting from *any third party class* for input models is a security vulnerability as you have no control of if/when someone else will add properties to a base class, meaning that an attacker could potentially supply query-string parameters that change the application's behaviour. You should always use a *dedicated* "input model" when binding, and ideally you should also white-list which properties are bindable too.

**Comment by Edgaras91** [comment]
Thank you, 

I assumed it's obsolete because the enum has only 2 values, and the 2nd value has obsolete attribute:
```
  /// <summary>Specifies how rules should cascade when one fails.</summary>
  public enum CascadeMode
  {
    /// <summary>
    /// When a rule fails, execution continues to the next rule.
    /// </summary>
    Continue,
    /// <summary>
    /// When a rule fails, validation is stopped and all other rules in the chain will not be executed.
    /// </summary>
    [Obsolete("Use CascadeMode.Stop instead. The behaviour of StopOnFirstFailure was ambiguous when used at validator-level. For more details, see https://docs.fluentvalidation.net/en/latest/conditions.html#stop-vs-stoponfirstfailure")] StopOnFirstFailure,
    /// <summary>When a rule fails, validation is immediately halted.</summary>
    Stop,
  }
```

I didn't consider the security aspect of it, which makes a lot of sense and will do this kind of separation moving forward! Thank you!

**Comment by JeremySkinner** [comment]
It has 3 values actually!
