### ISSUE TITLE
Guid not able to be tested

### ISSUE THREAD

**Issue by mtrtm** [FluentValidation/FluentValidation#1815]
### FluentValidation version

10.3.1

### ASP.NET version

net5.0

### Summary

If I try to make a validator for a value type, for instance an int that only equals 1, or a Guid that isn't empty, I get a compilation error when trying to test when writing xUnit tests

### Steps to Reproduce

```
public class GuidValidator : AbstractValidator<Guid>
	{
		public GuidValidator()
		{
			RuleFor(guid => guid)
				.NotEqual(guid => Guid.Empty);
		}
	}
```

```
[Fact]
public void Validator_WithEmptyGuid_ReturnsValidationError()
		{
			Guid guid = Guid.Empty;
			var result = _validator.TestValidate(guid);
			// can't get this far - error above
		}
```

If I try to do this, I get the error "The type 'Guid' must be a reference type...".  It looks like I can't test my validator - am I doing something wrong or is this a bug?

**Comment by JeremySkinner** [comment]
Hi, currently `TestValidate` only works with reference types for legacy reasons, although there isn't really a need for this constraint anymore. I've pushed out a new release that removes this constraint. If you upgrade then it should work correctly.
