### ISSUE TITLE
[Docs] Please document AutomaticValidationEnabled property

### ISSUE THREAD

**Issue by lonix1** [FluentValidation/FluentValidation#1816]
### Is your feature request related to a problem? Please describe.

I found the `AutomaticValidationEnabled` property, but there's no explanation anywhere as to its use or purpose. (i.e. How does FV behavior change when this property is on / off.)

I searched the docs site, github issues, StackOverflow and Google.

### Describe the solution you'd like

Please consider adding a section to the docs explaining when/why it should be used.

### Additional Context

It might take a while until this is formally documented. In the meantime, if someone wouldn't mind a brief/simple explanation for this option, that would be really appreciated... thanks!

**Comment by JeremySkinner** [comment]
If you change it to false then asp.net won’t attempt to use FluentValidation to validate objects during model binding.

**Comment by lonix1** [comment]
Thanks, that's what I was hoping it was for!

I have a "Mediatr" CQRS pipeline that uses FV, and everything was being validated twice: once in the controller and then once by the cqrs/mediator pipeline.

If I understand correctly, this new property allows me to disable "automatic" validation and only use it "on-demand"... so it's a very useful new feature!

**Comment by lonix1** [comment]
A reasonable place for the content would after the ["Manual Validation"](https://docs.fluentvalidation.net/en/latest/aspnet.html#manual-validation) section. (Though the two sections could get a confusing as they're named similarly.)

Something like:
> ### Disabling automatic validation
>
> In some cases it may be desirable to disable automatic validation, and perform all validation manually. In that case disable automatic validation as follows:
````cs
services.AddFluentValidation(config => {
  config.AutomaticValidationEnabled = false;
});
````

> When disabled, ASP.NET won't attempt to use FluentValidation to validate objects during model binding.

**Comment by lonix1** [comment]
Final point, I don't think my text above would be enough. The obvious question the reader would have would be:

*Why not use the `FluentValidation` library instead of `FluentValidation.AspNetCore`? If using the latter and then just disabling it, what's the point?*

Frankly I'm not sure I get it either. Personally I'm going to use the former library instead.

**Comment by JeremySkinner** [comment]
FluentValidation.AspNetCore provides the automatic validation that we’re talking about here and also provides integration with clientside/javascript validation (see the section on clientside validation in the docs)

If you don’t need either of these features then there’s no need to use FluentValidation.AspNetCore

**Comment by lonix1** [comment]
It also does assembly scanning to register all validators (or is that available in the base library too?)

In which case, what motivated you to add this property - what is the use case for  `FluentValidation.AspNetCore` with `AutomaticValidationEnabled` disabled?

**Comment by JeremySkinner** [comment]
Scanning is available in FluentValidation.DependencyInjectionExtensions (the scanning in the AspNetCore package just wraps this)

> In which case, what motivated you to add this property - what is the use case for FluentValidation.AspNetCore with AutomaticValidationEnabled disabled?

so you can combine the clientside validation integration with manual server side validation

**Comment by lonix1** [comment]
Ooooh! Okay I finally understand.

For those of us building Web APIs (no client side stuff) the base library is sufficient.

(That actually should be in the docs somewhere too, it's very valuable when deciding which library to use, based on one's needs.)

**Comment by JeremySkinner** [comment]
Feel free to submit a PR, otherwise I’ll try and get to it when I have time

**Comment by lonix1** [comment]
Sorry Jeremy I never did figure out the github PR thing. That's why I typed my suggestions above as a comment instead of a PR :)

Here's my final suggestion, for whenever you update the docs:

> ### Disabling automatic validation
>
> In some cases it may be desirable to disable automatic validation, and perform all validation manually. In that case disable automatic validation as follows:
````cs
services.AddFluentValidation(config => {
  config.AutomaticValidationEnabled = false;
});
````

> When disabled, ASP.NET won't attempt to use FluentValidation to validate objects during model binding.
>
> Note that if you do not need integration with client-side validation, an alternative is to use the `FluentValidation` library instead of `FluentValidation.AspNetCore`, in which case you do not need to use this property at all.
