### ISSUE TITLE
The ValidateAndThrowAsync method doesn't work for throwing new exception in OnFailure method.

### ISSUE THREAD

**Issue by konraddabrowski** [FluentValidation/FluentValidation#1817]
### FluentValidation version

10.3.3

### ASP.NET version

.NET 5.0.9

### Summary

Hi, as I mentioned in the title, the ValidateAndThrowAsync method doesn't work for throwing new exception in OnFailure method. I don't find any solution in web so I'm looking for help at the source ;)
My code has thrown the exception but I can't catch it ...code executes further.

Maybe I made the mistake somewhere?

### Steps to Reproduce

I have registered Validator service with method:
`public async Task ValidateAsync<T>(T instance)
        {
            using var scope = _serviceFactory.CreateScope();
            var validator = scope.ServiceProvider.GetService<AbstractValidator<T>>();
            if (validator is null)
            {
                throw AssertorServiceException.Create(nameof(AbstractValidator<T>));
            }
            await validator.ValidateAndThrowAsync(instance);
                //.ValidateAsync(instance, options => options.ThrowOnFailures()); // not working too

        }`

that finally invoke 

`public class LoginValidator : AbstractValidator<Login>
    {
        public LoginValidator()
        {
            RuleFor(x => x.Email).EmailAddress()
                .OnFailure(x => throw EmailException.Create(x.Email));
            RuleFor(x => x.Password)
                .Must(password => new Regex(@"[0-9]+").IsMatch(password))
                .Must(password => new Regex(@"[a-z]+").IsMatch(password))
                .Must(password => new Regex(@"[A-Z]+").IsMatch(password))
                .Must(password => new Regex(@"[!@#$%^&*()_+=\[{\]};:<>|./?,-]+").IsMatch(password))
                .MaximumLength(77)
                .MinimumLength(7)
                    .OnFailure(x => throw IncorrectPasswordOrEmailException.Create());
        }
    }`

The exception is throwing for the first RuleFor method only.

**Comment by JeremySkinner** [comment]
You shouldn't throw exceptions inside a call to `OnFailure` - this isn't the purpose of this method. 

`ValidateAndThrow` will throw an exception that contains all failures, provided the rules are setup normally.

**Comment by konraddabrowski** [comment]
So what do you recommend doing in my case?

**Comment by JeremySkinner** [comment]
Remove the calls to `OnFailure`. Invoke the validator and inspect the failures collection and act upon the results as desired.

**Comment by konraddabrowski** [comment]
All right. I found a solution ;) In my custom webapi I created a filter mechanism that use FluentValidation (FV) and invoke ValidateAndThrowAsync method out of scene. In this case exception thrown at OnFailure method is oke (see first comment), because it had throw before FV exception. The problem occurs below:

```
public void InvokeFilters<T>(T instance)
   => ToList().ForEach(filter => {
      var  tasks = new List<Task>(new[] {
         filter.Invoke<T>(instance),
         filter.Invoke<T>(_serviceScopeFactory),
         filter.Invoke<T>(instance, _serviceScopeFactory)
      });

      Task.WhenAll(tasks);
   });

```
The tasks above work in the background ...so I made mistake after all :)
