### ISSUE TITLE
SetValidator subvalidation not triggered correctly?

### ISSUE THREAD

**Issue by CasperWSchmidt** [FluentValidation/FluentValidation#1825]
### FluentValidation version

10.x (10.3.3)

### Summary

We are using subvalidators with `SetValidator` but somehow it looks like some of the validation in the subvalidator is not triggered correctly?

### Steps to Reproduce

We have the following test:
```
[Theory]
[InlineData(null)]
[InlineData("")]
public void ShouldHaveErrorForReleaseGroupWhenEmpty(string id)
{
    validator.ShouldHaveValidationErrorFor(input => input.ReleaseGroupId, id);
}
```
`validator` is an instance of the following validator (using Moq for mocking the dependencies):
```
public class PortfolioValidator : AbstractValidator<Portfolio>
{
    public PortfolioValidator(IManagerRepository managerRepository, ICustodianRepository custodianRepository,
        IReleaseGroupRepository releaseGroupRepository, IAccountRepository accountRepository)
    {
        RuleFor(x => x.Id).NotEmpty().Id();
        RuleFor(x => x.ManagerId).SetValidator(new IdValidator<Manager>(managerRepository)).When(x=>!string.IsNullOrEmpty(x.ManagerId));
        RuleFor(x => x.ReleaseGroupId).SetValidator(new IdValidator<ReleaseGroup>(releaseGroupRepository));
        RuleForEach(x => x.Depositories).SetValidator(new DepositoryValidator(custodianRepository, accountRepository));
        RuleForEach(x => x.Accounts).SetValidator(new AccountValidator(custodianRepository));
    }
}
```

The `IdValidator` is as follows:
```
public class IdValidator<T> : AbstractValidator<string>
{
    public IdValidator(IRepository<T> repository)
    {
        RuleFor(x => x).Cascade(CascadeMode.Stop).NotEmpty().Id().Must(repository.Exists);
    }
}
```
The test works for the empty string case, but not for the null case (according to the output, only `Id` property has validation errors in this case). According to the documentation [here](https://docs.fluentvalidation.net/en/latest/built-in-validators.html#notempty-validator) `NotEmpty` should check both null and empty string though? Also, changing `PortfolioValidator` to `RuleFor(x => x.ReleaseGroupId).NotEmpty().SetValidator(new IdValidator<ReleaseGroup>(releaseGroupRepository));` makes both cases pass, which is weird IMHO

**Comment by JeremySkinner** [comment]
Hi,

> The test works for the empty string case, but not for the null case

Child validators aren't triggererd for null properties, which is the intended/correct behaviour to prevent NullReferenceExceptions deeper in the validation hierarchy. Null checks on the property should be performed on the top level, not inside the child validator

**Comment by CasperWSchmidt** [comment]
>Child validators aren't triggererd for null properties

Of course! That makes a lot of sense :) How can I have missed that obvious feature...
