### ISSUE TITLE
Special characters isn't properly formatted in {PropertyValue} 

### ISSUE THREAD

**Issue by fialo4ka** [FluentValidation/FluentValidation#1826]
### FluentValidation version

10.2.3

### ASP.NET version

net5.0

### Summary

If checked property contain special characters like " it is not formatted correctly

### Steps to Reproduce

for example:
if property value is `ÄÄÄ"""`
and I try to create json
```
var letterOrDigit = "^[a-zA-Z0-9]*$"; 
RuleFor(v => v)
                .Matches(letterOrDigit)
                .WithMessage(JsonSerializer.Serialize(new ErrorModel()
                        {
                            Name = "nameofModel",
                            Value = "{PropertyValue}"
                        }));
```
it give me in 
(new System.Collections.Generic.ICollectionDebugView<FluentValidation.Results.ValidationFailure>(failures.Errors).Items[0]).ErrorMessage

{"Name":"nameofModel","Value":**"ÄÄÄ""""**}
and this is not valid JSON.
Valid JSON need to contain \ before "
{"Name":"nameofModel","Value":**"ÄÄÄ\\"\\"\\""**}

So, if I try to Deserialize it, I have exception
`'"' is invalid after a value. Expected either ',', '}', or ']'. `

**Comment by JeremySkinner** [comment]
Hi, you shouldn't be serializing with placeholders like this: placeholders are handled with simple string replacement and won't work correctly if you're trying to replace them inside an already-serialized string. You should switch to using a callback instead like this:

```csharp
RuleFor(v => v)
  .Matches(letterOrDigit)
  .WithMessage(v => JsonSerializer.Serialize(new ErrorModel {  Name = "nameofModel",  Value = v }));
````
