### ISSUE TITLE
Error while installing FluentValidation or FluentValidation.AspNetCore

### ISSUE THREAD

**Issue by srihan93** [FluentValidation/FluentValidation#1831]
### FluentValidation version

8.x to latest stable 10.3.3

### ASP.NET version

netcoreapp3.1

### Summary

When I am trying to install Fluent Validation through NuGet, dotnet an error is throwing
Cycle Detected NuGet Error NU1108
![image](https://user-images.githubusercontent.com/47860024/133733481-8f718f76-f17c-4335-9753-bc435cff57f7.png)

### Steps to Reproduce

Create Core Web API project with runtime 3.1,
run the below command,
dotnet add package FluentValidation.AspNetCore

You will see the error

**Comment by JeremySkinner** [comment]
Hi, this isn't a bug with FluentValidation, it means you probably have an issue with how your references are set up in one of your projects. I can't really help any further than that without seeing the projects. I'd suggest you start debugging it by creating a minimal sample project that reproduces the issue.

**Comment by srihan93** [comment]
Hi Jeremy, thanks for the message. Not sure when i created the project again with 5.0 with https support, then it worked. Need to check the real reason of the failure.
