### ISSUE TITLE
custom message and error codes misunderstanding

### ISSUE THREAD

**Issue by ggiacomoo** [FluentValidation/FluentValidation#1833]
### FluentValidation version

9.x-10.x

### ASP.NET version

core5

### Summary

i'm using fluent validation (both 9 and 10 now..) to request validation in asp.net core 5 web application, i'm having some issues with custom messages and error codes...

### Steps to Reproduce

`    public class FooRequest
    {
        public string foo1 { get; set; }
        public string foo2 { get; set; }
    }`

`    public class FooValidator :  AbstractValidator<FooRequest>
    {
        public FooValidator() : base()
        {
            RuleFor(r => r.foo1)
                .NotEmpty()
                .WithMessage($"my message 1")
                .WithErrorCode("MY_ERROR_CODE_1"); 
        }
    }`

`
   //registered with DI and assembly scan
    [HttpPost("fooValidator")]
    public void fooValidator([FromBody] FooRequest fooRequest)
    {
    }`

but i receive and unexpected response (without custom errorCode, and with customMessage inside the errorCode), where i'm wrong??
`
{
"message": "Bad Request",
"errorCode": "my message 1"
}`

P.S. if i change the validator, to set just customErorr

`            RuleFor(r => r.foo1)
                .NotEmpty()
                .WithErrorCode("MY_ERROR_CODE_1"); `
i receive the default one:
`
{
"message": "Bad Request",
"errorCode": "'foo1' must not be empty."
}`

P.S.2 if i try to set the customMessage:
` RuleFor(r => r.foo1)
                .NotEmpty()
                .WithMessage("my error message 1");`
i receive the default message, with errorCode
`{
"message": "Bad Request",
"errorCode": "my error message 1"
}`

**Comment by JeremySkinner** [comment]
Hi, the JSON structure in your example isn't coming from FluentValidation. You'll need to take a look within your codebase to see how you're serializing the FluentValidation error response, that'll be where the problem is, not inside FluentValidation itself
