### ISSUE TITLE
Unintended breaking change on async validations in FluentValidation v10+: deadlocks

### ISSUE THREAD

**Issue by julealgon** [FluentValidation/FluentValidation#1834]
### FluentValidation version

10.3.3

### ASP.NET version

AspNet WebApi 2 (legacy framework)

### Summary

After upgrading from 9.5.3 to 10.3.3, I started seeing application stalls in a few tests. After investigating further, I notice that the stalls were happening on `.Validate` calls in some manual validators, and that those validators had multiple `.MustAsync` calls inside.

At this point, I realized we shouldn't have been using `.Validate` in the first place, but `.ValidateAsync`. After making that change, I'm now observing actual test failures on our side, due to the actual validation logic.

This means the old approach was hiding the issues somehow (perhaps running the validations in background and never failing), but the same calls in the newer version are apparently now causing actual deadlocks.

While I totally understand that we should be using `ValidateAsync` in the first place (and I have already made that change now), it still seems like a unintentional breaking change was made somewhere in the sync to async execution pipeline in FluentValidation that changed the behavior from "run and ignore" to "run and deadlock".

I was not able to find this behavior change described anywhere. Searched here:
- https://github.com/FluentValidation/FluentValidation/issues/1651
- https://github.com/FluentValidation/FluentValidation/issues/1705
- https://github.com/FluentValidation/FluentValidation/issues/1527
- https://github.com/FluentValidation/FluentValidation/issues/1481

### Steps to Reproduce

1. Install FluentValidation v9.5.3:
2. Create a class inheriting from `AbstractValidator<T>` for a given `T` model
2. Add async validations to it using `.MustAsync` and async lambdas
3. Manually execute this validation inside a AspNet WebApi 2 controller against a `T` instance, using `.Validate`
4. Observe that the validation runs to completion
5. Upgrade FluentValidation to 10.3.3
6. Observe that the same validation call now deadlocks the application

**Comment by JeremySkinner** [comment]
Hi, if a validator has asynchronous rules using `MustAsync` then it should always be invoked using `ValidateAsync`, as mentioned in the documentation. Invoking this with `Validate` has always been an unsupported scenario and runs a risk of deadlocks (even in 9.x). 

No breaking changes were intentionally made here, but it's certainly possible that a change was introduced that modified the behaviour, but as this is an unsupported scenario it isn't something that would've been investigated/tested/documented. 

This will be made even more explicit in v11 which will throw an exception if you attempt to invoke an asynchronous validator synchronously.

**Comment by julealgon** [comment]
Thanks for clarifying @JeremySkinner . I understand you don't consider this a breaking change on the premise that the original call itself was unsupported in the first place. That's fair.

It would've been nice if the lack of support was better communicated however (by the code itself throwing a `NotSupportedException` for instance I mean, not in the documentation which already does mention it). I appreciate you are moving in that direction with the next update however.

**Comment by JeremySkinner** [comment]
> by the code itself throwing a NotSupportedException for instance 

Yes that'll happen in the next version.
