### ISSUE TITLE
Add `Required()` to the current release (10)

### ISSUE THREAD

**Issue by umbarov** [FluentValidation/FluentValidation#1837]
### Describe the solution you'd like

Hi,
The [upcoming release (11) removes](https://github.com/FluentValidation/FluentValidation/issues/1725) `NotEmpty()` validator. `NotEmpty()`  is the most used validator. And to make smooth migration to the next major release (11) would be good if you'll add `Required()` to the current version (10) as a new feature.

**Comment by JeremySkinner** [comment]
We decided not to make these changes in the end for v11; no changes will be made to NotNull/NotEmpty and Required won't be introduced.
