### ISSUE TITLE
Iterate the rules dynamically

### ISSUE THREAD

**Issue by furqansafdar** [FluentValidation/FluentValidation#1838]
### FluentValidation version

10.3.3

### Summary

How to do similar stuff in FluentValidation version 10.3.3 which was applicable before in older versions.

```
public MyValidator() {
    RuleFor(x => x.Foo).Whatever();
    //...other rules...
    foreach (var rule in this) {
        if (rule is PropertyRule ruleChain) {
            foreach (var validator in ruleChain.Validators) {
                validator.Options.CustomStateProvider = ctx => ctx.Instance;
            }
        }
    }
}
```

Note: this logic was suggested by you in my earlier [post](https://github.com/FluentValidation/FluentValidation/issues/979)

I am looking for this approach to add [WithState](https://docs.fluentvalidation.net/en/latest/custom-state.html?highlight=WithState#custom-state) dyanamically to each rule.

### Steps to Reproduce

Not applicable

**Comment by JeremySkinner** [comment]
Hi, as part of the move to 10.0 rule components became strongly-typed for performance reasons and type safety. A result of this is dynamic manipulation of rules is no longer supported. 

Generally with FluentValidation I recommend being explicit with each rule definition, so if you can port your validators to use explicit `WithState` calls then this would be the way to go. If you really need the old behaviour then you'll have to continue to use the old version.
