### ISSUE TITLE
Nugets missing license expression

### ISSUE THREAD

**Issue by frankhaugen** [FluentValidation/FluentValidation#1839]
### FluentValidation version

Latest

### Summary

The nugets are distributed without a license expression applied to the csproj causing tools like fossa.com to report "no license" -error

### Steps to Reproduce

Use a tool like fossa.com and scan a repo that has a dependency on a FluentValidation nuget

**Comment by JeremySkinner** [comment]
Feel free to submit a PR to add this, thanks!

**Comment by JeremySkinner** [comment]
Actually I just checked and this isn't the case. We *do* include a license expression in all packages via the embedded Directory.build.props:

https://github.com/FluentValidation/FluentValidation/blob/fb1e9392dc0b97ed2b60bcaa3cef425a413c1a6a/src/Directory.Build.props#L15

...and you'll also note that it correctly shows up on nuget.org in the license section in the sidebar.

**Comment by frankhaugen** [comment]
@JeremySkinner interesting that FOSSA reports it as un-licensed. I'll file a bug with them:
![image](https://user-images.githubusercontent.com/13543585/134816325-faf3e905-768a-4319-93fa-4ea905954e8b.png)
