### ISSUE TITLE
Blazor: LanguageManger: Not using language manager

### ISSUE THREAD

**Issue by sianmace** [FluentValidation/FluentValidation#1840]
### FluentValidation version

10.3.0

### Summary

Using Blazored.FluentValidation (2.0.1)

I have been previously using FluentValidation for some time. I use the language manager to by default change the text of validation.
`ValidatorOptions.Global.LanguageManager = new LanguageManager();`

This approach has worked previously in .net core asp.net

I have attempted to use this in blazor, but the Language Manager is not used.

Has anyone tried this in blazor?

### Steps to Reproduce

Install Blazored.FluentValidation
Add a simple validator
set ValidatorOptions.Global.LanguageManager = new LanguageManager(); with a simple language manager

**Comment by JeremySkinner** [comment]
The core FluentValidation library *always* uses the language manager, regardless of whether you're running in Blazor or any other runtime. It's how all of FluentValidation's error messages are loaded. 

If you're seeing different behaviour when using the ` Blazored.FluentValidation` package then you need to speak to the authors of that package; it's not something we maintain.

**Comment by sianmace** [comment]
I did, they said its a Fluent issue and to speak to this project :)
So sorry, it is using A language manager - not My language manger
ie setting 
`ValidatorOptions.Global.LanguageManager = new LanguageManager();`
is not working and picking up my language manager

**Comment by JeremySkinner** [comment]
I'm sorry but this is simply not the case. FluentValidation always uses the language manager that you set in `ValidatorOptions.Global.LanguageManager`. If this isn't the behaviour you're seeing this is an issue in your code, not with the FluentValidation library. I'd suggest you try and debug the issue put together a small sample project (with no third party libraries) that reproduces the issue.

**Comment by sianmace** [comment]
Ok Fair enough, will do - thanks
