### ISSUE TITLE
Dependency Injection for CustomLanguageManager

### ISSUE THREAD

**Issue by jun1sfukui** [FluentValidation/FluentValidation#1841]
### Is your feature request related to a problem? Please describe.

I made a CustomLanguageManager to determine error messages corresponding to Messages table in a database.

```C#:CustomLanguageManager.cs
interface IMesasgeResolver
{
    public string GetString(string key);
}

class DBMessageResolver : IMessageResolver
{
    private MyDbContext _db;

    public DBMessageResolver(MyDbContext db)
    {
        _db = db;
    }

    public string GetString(string key)
    {
        return (
            from m 
            in this._db.Messages 
            where m.MessageKey == key 
            select m.Message
        ).FirstOrDefault();
    }
}

class CustomLanguageManager : FluentValidation.Resources.LanguageManager
{
    private IMessageResolver _messageResolver;  
    public CustomLanguageManager(IMessageResolver messageResolver)
    {
        _messageResolver = messageResolver;
    }

    public override string GetString(string key, CultureInfo culture = null) 
    {
        string message = this._messageResolver.GetString(key);
        return message ?? base.GetString(key, calture);
    }
}
```

And set it into `ValidatorOptions.Global.LanguageManager`.

```C#
ValidatorOptions.Global.LanguageManager = new CustomLanguageManager(new DBMessageResolver(new MyDbContext()));
```

But this is not a thread-safe way because the instance of MyDbContext is system-global.

How should I do to injection a instance of MyDbContext with request-based lifetime?

### Describe the solution you'd like

I'd like to do:

```C#
Customer customer = new Customer();
CustomerValidator validator = new CustomerValidator(
    cfg => { 
        cfg.LanguageManager =  new CustomLanguageManager(new DBMessageResolver(_db));
    }
);

ValidationResult results = validator.Validate(customer);
```

### Describe alternatives you've considered

If there's no way to injection CustomLanguageManager, I'd like to determine the error message outside FluentValidation based on the error code.
But for now, I can not get enough information to create custom error messages from ValidationResult, for example, {PropertyValue} and {PropertyName}.

**Comment by JeremySkinner** [comment]
Hi, this isn't really the right approach to take. The LanguageManager is only ever intended to be used in a singleton context, and is intended to be a wrapper around FluentValidation's default messages - you shouldn't be replacing the LanguageManager's implementation with a database, and you shouldn't be injecting anything into it. 

If you want localized error messages loaded from a database then you should use a separate service (such as an `IStringLocalizer` implementation) which can then be request-scoped. This is covered in this page in the documentation: https://docs.fluentvalidation.net/en/latest/localization.html#istringlocalizer

Custom LanguageManager implementations should *only* be used to swap out individual messages as per this example: https://docs.fluentvalidation.net/en/latest/localization.html#default-messages
