### ISSUE TITLE
Method not found: 'FluentValidation.AssemblyScanner FluentValidation.AssemblyScanner.FindValidatorsInAssembly(System.Reflection.A ssembly)'.

### ISSUE THREAD

**Issue by VijayKaravadra** [FluentValidation/FluentValidation#1846]
### FluentValidation version

10.3.3

### ASP.NET version

5

### Summary

Getting below exception on loading validators.

Method not found: 'FluentValidation.AssemblyScanner FluentValidation.AssemblyScanner.FindValidatorsInAssembly(System.Reflection.A
ssembly)'.

### Steps to Reproduce

Use any of the below methods to register validators.

services.AddValidatorsFromAssembly(AppDomain.CurrentDomain.Load("ProjectName"));
services.AddValidatorsFromAssemblyContaining<MyValidator>();
services.AddValidatorsFromAssemblyContaining(typeof(MyValidator));

**Comment by JeremySkinner** [comment]
Hi, this isn't an issue with FluentValidation itself. It means that somewhere in your dependency graph you have a mismatch of FluentValidation versions. Something in your dependency graph has been compiled against an older version of FluentValidation and needs to be recompiled against a newer version. I can't provide any further help than this without seeing your project, so it's something you'll need to debug yourself, but hopefully that gives you a pointer in the right direction.
