### ISSUE TITLE
IStringLocalizer with arguments ignores WithMessage

### ISSUE THREAD

**Issue by anddrzejb** [FluentValidation/FluentValidation#1850]
### FluentValidation version

10.3.4

### ASP.NET version

.NET 6

### Summary

It seems that when I used arguments with `IStringLocalizer` in `WithMessage()`, the default message is being used instead the one from `IStringLocalizer`. If I remove arguments, I get message from `IStringLocalizer`.

### Steps to Reproduce

I have this validator for date ranges. It can be customized, so its behavior can be altered just before the validation. However, I stripped the rules to the bare minimum to pinpoint offending code, and I got to this:
```cs
public class DateRangeValidator : AbstractValidator<(DateTime From, DateTime To)>
{
    public DateRangeValidator SetIsLimitInclusive(bool value)
    {
        limitIsInclusive = value;
        return this;
    }
    public bool IsLimitInclusive() => limitIsInclusive;

    private DateTime? fromLessThan;
    public DateRangeValidator SetFromLessThan(DateTime? value)
    {
        fromLessThan = value;
        return this;
    }
    public DateRangeValidator(IStringLocalizer<DateRangeValidator> localizer,
        ISystemClock systemClock)
    {
        RuleFor(data => data.From)
            .LessThanOrEqualTo(data => data.To).WithMessage(data => localizer["From date cannot be after To date."]);

        When(data => IsLimitInclusive(), () =>
        {
            RuleFor(data => data.From).LessThanOrEqualTo(data => fromLessThan)
                .When(data => fromLessThan is not null, ApplyConditionTo.CurrentValidator)
                //this line prints "'Item1' must be less than or equal to '09/01/20 00:00:00'."
                .WithMessage(data => localizer["From date ({0}) has to be before or equal to {1}.", data.From, fromLessThan]);
                //this prints what is in the localizer: "From date ({0}) has to be before or equal to {1}."
                //.WithMessage(data => localizer["From date ({0}) has to be before or equal to {1}."]);
        });
    }
}
```

When I use this line:
```cs
.WithMessage(data => localizer["From date ({0}) has to be before or equal to {1}.", data.From, fromLessThan]);
```
then instead of expected message, I get a generic one: `'Item1' must be less than or equal to '09/01/20 00:00:00'.`

If I remove arguments form the `IStringLocalizer`:
```cs
.WithMessage(data => localizer["From date ({0}) has to be before or equal to {1}."]);
```
I get a message from the localizer: `From date ({0}) has to be before or equal to {1}.`. I there something I am doing wrong, or this is not supported? 
I also tried with string interpolation, just to debug, and it works as expected. But in case of localization string interpolation is useless, because I really need to use the templates.

**Comment by JeremySkinner** [comment]
I'm not really sure I understand the issue, but it looks like it's most likely related to your IStringLocalizer rather than a problem with FluentValidation itself. Can you put together a small sample project that reproduces the issue?

**Comment by anddrzejb** [comment]
Well, you are right. I was walking in circles, but in the end it was my faulty `IStringLocalizer` mock (or rather I forgot to setup the indexer with arguments). Thank you and sorry to take your time.
