### ISSUE TITLE
10.0.4 to 10.3.4 ValidationTestExtension.ShouldHaveValidationErrorFor<T, TValue> is Obsolete

### ISSUE THREAD

**Issue by LeahPike** [FluentValidation/FluentValidation#1851]
### FluentValidation version

10.3.4

### ASP.NET version

.NET Core 6.0.0

### Summary

I've upgraded from 10.0.4 to 10.3.4 and I'm getting a lot of warnings saying:

> 'ValidationTestExtension.ShouldHaveValidationErrorFor<T, TValue>(IValidator<T>, Expression<Func<T, TValue>>, TValue, string)' is obsolete: 'This method is deprecated and will be removed in version 11. Use the TestValidate method instead. See https://docs.fluentvalidation.net/en/latest/testing.html'

I have used the TestValidate elsewhere when I'm wanting to test complex rules using many properties, but we've hundreds of tests just checking single properties without having to define the object. Is there a way to correctly do these tests just passing in the value for the property, or do I need to make the Report object now as below?

``` C#
var item1 = new ReportColumnWidth { Value = 60 };
var item2 = new ReportColumnWidth { Value = 60 };

var report = new Report { ColumnWidths = new Collection<ReportColumnWidth> { item1, item2 } };

_validator.TestValidate(report).ShouldHaveValidationErrorFor(e => e.ColumnWidths)
    .WithErrorMessage("Column widths must not exceed 100");
```

Thanks

### Steps to Reproduce

Current code that gives the warning:

``` C#
var item1 = new ReportColumnWidth { Value = 60 };
var item2 = new ReportColumnWidth { Value = 60 };

_validator.ShouldHaveValidationErrorFor(e => e.ColumnWidths, new Collection<ReportColumnWidth> { item1, item2 }).WithErrorMessage("Column widths must not exceed 100");
```

**Comment by JeremySkinner** [comment]
Hi, you should migrate to using `TestValidate` with an explicitly instantiated Report object. The `ShouldHave...` methods directly on the validator will be removed in FV 11.  

If you're not ready to migrate these methods then you could always copy the code for the `ShouldHave...` methods into your own project when FV 11 is released (they're just wrappers around TestValidate anyway). See https://github.com/FluentValidation/FluentValidation/issues/1725#issuecomment-905644363

**Comment by LeahPike** [comment]
Thank you for the reply. :)

I'll begin updating to use TestValidate. I just wanted to be 100% sure I was doing it the correct way before spending time on going through it all, as there are so many.
