### ISSUE TITLE
YearMonth property gets splitted in YearMonth in GetDefaultMessageTemplate "{PropertyName} is invalid."

### ISSUE THREAD

**Issue by benzmarkus** [FluentValidation/FluentValidation#1852]
### FluentValidation version

10.2.3

### ASP.NET version

net5

### Summary

Wrote a PropertyValidator<T, int> Validator and in the GetDefaultMessageTemplate => "{PropertyName} is invalid." the error message "Year Month is invalid." is generated but currently only for Property "YearMonth". For other properties it's working.

### Steps to Reproduce
`
public class Test
{
        public int YearMonth { get; set; }
}

public class TestValidator: AbstractValidator<Test>
    {
        public TestValidator()
        {
            RuleFor(x => x.YearMonth).SetValidator(new MonthValidator<Test>());
        }
    }

public class MonthValidator<T> : PropertyValidator<T, int> {
	public static string ErrorIsValidDateInvalidDay(string propName) => $"{propName} is invalid.";
	protected override string GetDefaultMessageTemplate(string errorCode) => ErrorIsValidDateInvalidDay({PropertyName}");
	public override string Name => "MonthValidator";
	public override bool IsValid(ValidationContext<T> context, int value)
	{
		if (value < 190001 || value > 999999)
		{
			return false;
		}
		var year = value / 100;
		var month = value % 100;
		try
		{
			_ = new DateTime(year, month, 1);
		}
		catch (ArgumentOutOfRangeException)
		{
			return false;
		}

		return true;
	}
}`

**Comment by JeremySkinner** [comment]
I have no idea what you're asking, can you provide more details along with *clear steps to reproduce the problem* as was requested in the issue template.

**Comment by benzmarkus** [comment]
For the error message a Property "YearMonth" gets splitted. That shouldn't be right?

**Comment by JeremySkinner** [comment]
The `{PropertyName}` placeholder will always split. `FirstName` will become `First Name` etc.

**Comment by benzmarkus** [comment]
Thx ... that helps
