### ISSUE TITLE
MustNot and MustNotAsync API

### ISSUE THREAD

**Issue by leopripos** [FluentValidation/FluentValidation#1857]
### Is your feature request related to a problem? Please describe.

When I want to apply `MustNotAsync`, I have to do something like this and I think we can make it neater

```csharp
public Validator(ICameraRepository cameraRepository)
{
    RuleFor(e => e.SerialNumber)
        .Cascade(CascadeMode.Stop)
        .NotEmpty()
        .MustAsync(async (serialNumber, cancellationToken) => !(await cameraRepository.ContainsSerialNumberAsync(serialNumber, cancellationToken)))
}
```

### Describe the solution you'd like

I suggest to add `MustNot` and `MustNotAsync` as new apis. It will be used like this
```csharp
public Validator(ICameraRepository cameraRepository)
{
    RuleFor(e => e.SerialNumber)
        .Cascade(CascadeMode.Stop)
        .NotEmpty()
        .MustNotAsync(cameraRepository.ContainsSerialNumberAsync);
}
```

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion!

I'm not currently planning on adding any new validators to the core library, but this is something that I'll consider for a future version sometime after 11.0 has shipped. However if you want to include these as extensions in your own project you could implement them as extension methods that wrap the existing Must/MustAsync

**Comment by helmsb** [comment]
Plus 1 for this feature. I run into this issue on about half my validators and I either have to write backwards logic to get around it or reverse it and comment why.

**Comment by dalefrancis88** [comment]
-1 for this feature. While it may seem simple, this is not something that should be the responsibility of the maintainer. This is the equivalent of asking to add `ifNot` to the base language. The maintainers work hard enough in their spare times to build out the base level features and adding trivial pieces such as this has a net negative on the cost/reward scale, it increases the burden for next to no value.

For those that find this you can implement this quite simply in two ways either wrap your predicate function in a `Not` function you import from a static class or implement your own extension. Both can be seen below.

```c#

public static class Functions
{
    public static Func<T, bool> Not<T>(Func<T, bool> predicate)
        => data => !predicate(data);
    public static Func<T, Task<bool>> Not<T>(Func<T, Task<bool>> predicate)
        => async data => !(await predicate(data));
}

public Validator(ICameraRepository cameraRepository)
{
    RuleFor(e => e.SerialNumber)
        .Cascade(CascadeMode.Stop)
        .NotEmpty()
        .MustAsync(Not(cameraRepository.ContainsSerialNumberAsync));
}
```

if if you want you can create your own extensions as seen belo

```c#
public static class ExtraValidatorExtensions
{
    public static IRuleBuilderOptions<T, TProperty> MustNot<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<TProperty, bool> predicate) =>
        ruleBuilder.Must(val => !predicate(val));
    public static IRuleBuilderOptions<T, TProperty> MustNotAsync<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<TProperty, CancellationToken, Task<bool>> predicate) => 
        ruleBuilder.MustAsync(async (val, cancel) => !(await predicate(val, cancel)));
}
```

**Comment by JeremySkinner** [comment]
I don't think this is something that I'll implement in the end, pretty much for the reasons that @dalefrancis88 outlined above. I want to avoid adding new validators to the core, and in this particular case it's easy to add extension methods in your own projects that add this in. 

Putting this in the core also means having to provide default message translations for [all our supported languages](https://github.com/FluentValidation/FluentValidation/tree/main/src/FluentValidation/Resources/Languages).

**Comment by leopripos** [comment]
```
This is the equivalent of asking to add ifNot to the base language
```
I'm not sure about that point, but FluentValidation has `NotEmpty`, `NotNull`, and `NotEqual`. I think they have same idea.

And yes, I can solve it using your solution above or even not using your solution, only using `!` operator as my sample.
But his experience is not only faced by my specific project. I face this in some of my projects, and maybe I'm not the only one.

Since it is simple, should I copy paste over and over again? should I create class library for that simple extension class?
My point is, it would be great if we have that one by default with the FluentValidation.

But, if it is too much effort to make it by default with the library, it's ok. :)
