### ISSUE TITLE
[Question] Is there a better way to test complex objects with nested validators?

### ISSUE THREAD

**Issue by tglowka** [FluentValidation/FluentValidation#1858]
### Describe the solution you'd like

Hello,
I am wondering if the following approach is correct. Let's assume I have the following scenario:
```
class A {
B b;
string SomeTextA;
}

class AValidator : AbstractValidator<A>
{
RuleFor (x => x.b).SetValidator(new BValidator());
RuleFor (x => x.SomeTextA).NotEmpty();
}

class B {
C c;
string SomeTextB;
} 
class BValidator : AbstractValidator<B>
{
RuleFor (x => x.c).SetValidator(new CValidator()); 
RuleFor (x => x.SomeTextB).NotEmpty();
}

class C 
{ 
string SomeTextC;
} 
class CValidator: AbstractValidator<C>
{
RuleFor (x => x.SomeTextC).NotEmpty();
}
```
Now I want to write unit tests for the validators.
```
AValidator aValidator = new AValidator();
BValidator  bValidator = new BValidator();
CValidator  cValidator = new CValidator();

public void TestA
{
A a = new A();
Assert.True(aValidator.Validate(a).IsValid);
aValidator.ShouldHaveChildValidator(x => x.b, typeof(BValidator));
}

public void TestB
{
B b = new B();
Assert.True(bValidator.Validate(b).IsValid);
aValidator.ShouldHaveChildValidator(x => x.c, typeof(CValidator));
}

public void TestC
{
C c = new C();
Assert.True(cValidator.Validate(c).IsValid);
}
```

Is the approach correct to avoid the assertion e.g. CValidator in TestA method? I just want to validate class-related validator and existence of child validators. We can also assume that I am not gonna use conditional validator setting like: RuleFor.SetValidator.When etc.

Thanks in advance!

**Comment by JeremySkinner** [comment]
Hi, this is an issue tracker for bugs in the FluentValidation library, I'm afraid [it isn't for general support questions](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions), sorry.  

All I can do is point you to the [documentation on the test helper](https://docs.fluentvalidation.net/en/latest/testing.html) and encourage you to use it as you feel best fits your use case.
