### ISSUE TITLE
How to properly Include/SetValidator based on a condition?

### ISSUE THREAD

**Issue by uhfath** [FluentValidation/FluentValidation#1859]
### FluentValidation version

10.3.4

### Summary

I have a model which should be validated differently based on it's `Type` field.
For this I've create multiple validators and registered them in DI manually.
The problem is how to pick one.
This is what I came up with currently:
```c#
When(m => m.Type != null, () =>
    Include(m => (ClientDetailsStateAddressModelValidatorBase)serviceProvider.GetRequiredService(AddressTypeValidators[m.Type])))
```
This seems to work.
But I need to output a message when `Type` is `null` and so tried this:
```c#
RuleFor(m => m.Type)
    .NotEmpty()
    .DependentRules(() =>
        Include(m => (ClientDetailsStateAddressModelValidatorBase)serviceProvider.GetRequiredService(AddressTypeValidators[m.Type])))
```
Or this:
```c#
RuleFor(m => m)
    .Cascade(CascadeMode.Stop)
    .Must(m => m.Type != null)
    .SetValidator(m => (ClientDetailsStateAddressModelValidatorBase)serviceProvider.GetRequiredService(AddressTypeValidators[m.Type]))
```
But none of these two worked. Validators don't run or at least do not output any errors.
What is the proper way to do this?

**Comment by JeremySkinner** [comment]
Hi, your first example is the correct way to do it, then add a separate call to do the null check.

```csharp

RuleFor(m => m.Type).NotNull();

When(m => m.Type != null, () => { 
    Include(m => ...); 
});


```

**Comment by uhfath** [comment]
Thank you for the info.

P.s. I've created this issue as a "bug" since I thought that the last 2 methods should work the same way as the first one and perhaps it's some sort of a bug. But I will keep your comment in mind, thanks.
