### ISSUE TITLE
Possibility of TransformAsync?

### ISSUE THREAD

**Issue by Eric-Bonneau** [FluentValidation/FluentValidation#1862]
### Is your feature request related to a problem? Please describe.

I have a property that I would like to transform into another type. The other type I would like to transform it into requires making an `async` call. The reason I want to transform into another type is that I have a custom validator for that type and I would like to set the custom validator on the result of the transformation.

### Describe the solution you'd like

It would be nice to have `TransformAsync` which would allow me to chain `SetValidator` on `T` rather than `Task<T>`.

### Describe alternatives you've considered

I could inline the validation using something like `MustAsync`, but I would like to reuse the validation and separate it out into its own validator.

I think another possibility could be to implement an `AsyncPropertyValidator<T, TProperty>` and use `SetAsyncValidator` for the property I would like to validate.

### Additional Context

Maybe there's another way to achieve what I would like. I think I've gone through the documentation quite thoroughly, so hopefully there is nothing obvious that I'm missing!

Also, thanks so much for this package and all the hard work that's been put into it. It has really made our validations simpler and easier to comprehend 🙌.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't that we'll introduce. The `Transform` method is only intended for very simple use cases where you have  simple synchronous process (eg parsing a string into an int). If you need something more complex than this then using `Transform` isn't the right approach to take and you should look at using a custom validator instead (either using `CustomAsync`, `MustAsync` or even an `AsyncPropertyValidator`.
