### ISSUE TITLE
ValidateAndThrow Extension Method for Context

### ISSUE THREAD

**Issue by bjsafdie** [FluentValidation/FluentValidation#1866]
### Describe the solution you'd like

Currently the ValidateAndThrow extension method extends IValidator.  This is fine for simple validators.  However, it will be nice if there is aa additional version that accepts a ValidationContext<T> to support validation rules that use the RootContextData collection.

`        public static void ValidateAndThrow<T>(this IValidator<T> validator, T instance, ValidationContext<T> context)
`

Or, you could add it to the existing definition as an optional parameter.

`        public static void ValidateAndThrow<T>(this IValidator<T> validator, T instance, ValidationContext<T> context = null)
`

**Comment by JeremySkinner** [comment]
Hi, you'd just set the Throw behaviour on the context directly in this case, no need for a new method:

```csharp
var context = ValidationContext<Person>.CreateWithOptions(instance, options => {
  options.ThrowOnFailures();
});

validator.Validate(context);
```


Calling `validator.ValidateAndThrow(instance)` is just a shortcut for the above.
