### ISSUE TITLE
SetValidator + WithMessage

### ISSUE THREAD

**Issue by Eric-Bonneau** [FluentValidation/FluentValidation#1867]
### FluentValidation version

10.3.5

### Summary

Hi there,

I'm not sure if this is a bug, or as design. I have a custom validator that has a default message. I want to use `SetValidator` with this custom validator, but override the default message using `WithMessage` to provide a custom message.

In my tests, I never see failures with the custom message, only the default message is returned.

I attached a code snippet with a working example to show what I'm trying to do.

I realize that my custom validator can have a custom message passed to its constructor to override the default message, but we're generally injecting validators (like `IValidator<TType>`) and not `new`ing them up like in the example I provided.

The extension methods allow `SetValidator` to be chained together with `WithMessage`, so that's why I'm not sure if it's a bug or as design.

Thanks! 😄

### Steps to Reproduce

```csharp
using System;
using System.Linq;
using FluentValidation;
using FluentValidation.Results;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var validator = new StringHolderValidator();

            ValidationResult result = validator.Validate(new StringHolder
            {
                StringProperty = string.Empty
            });

            const string expectedMessage = "Custom message";

            bool expectedResult = expectedMessage == result.Errors.Single().ErrorMessage;

            Console.WriteLine(expectedResult); // Expecting this to be true, but it's false
        }
    }

    public class StringValidator : AbstractValidator<string>
    {
        public StringValidator()
        {
            RuleFor(s => s)
                .NotEmpty()
                .WithMessage("Default message");
        }
    }

    public class StringHolder
    {
        public string StringProperty { get; set; }
    }

    public class StringHolderValidator : AbstractValidator<StringHolder>
    {
        public StringHolderValidator()
        {
            RuleFor(h => h.StringProperty)
                .SetValidator(new StringValidator())
                .WithMessage("Custom message");
        }
    }
}

```

**Comment by JeremySkinner** [comment]
Hi, this is by design. Calling `WithMesage` following a call to `SetValidator(IValidator<T>)` is a no-op.

**Comment by Eric-Bonneau** [comment]
Okay great, I had a feeling this was the case. I will likely head down this direction instead.

Thank you for your time and effort on this project!
