### ISSUE TITLE
Cannot be used for parameter 'builder' of type RuleBuilder due to differences in the nullability of reference types

### ISSUE THREAD

**Issue by mdmoura** [FluentValidation/FluentValidation#1871]
### FluentValidation version

10

### ASP.NET version

Net 6

### Summary

When I try to use RuleFor with a Nullable type in Net 6:

    RuleFor(x => x.Include)

I get the warning:

`Argument of type 'IRuleBuilderInitial<Model, IncludeExpression?>' cannot be used for parameter 'builder' of type 'IRuleBuilder<Model, IncludeExpression>' in 'IRuleBuilderOptions<Model, IncludeExpression> ValidatorExtensions.IncludeExpression<Model>(IRuleBuilder<Model, IncludeExpression> builder, params string[] fields)' due to differences in the nullability of reference types. `

Can this be solved?

### Steps to Reproduce

I have the model:

    public class Model {
      public IncludeExpression? Include { get; set; }
    } 

And an `IncludeExpression` validator:

```
public class IncludeExpressionValidator<T, TProperty> : PropertyValidator<T, TProperty> {

  public override String Name => "IncludeExpressionValidator";
  private String[] _fields;
  private IEqualityComparer<String> _comparer;

  public IncludeExpressionValidator(String[] fields, IEqualityComparer<String> comparer) {
    _fields = fields;
    _comparer = comparer;
  }

  public override Boolean IsValid(ValidationContext<T> context, TProperty? property) {

    if (property is null) 
      return true;

   // Validation code

  } 

  protected override String GetDefaultMessageTemplate(String errorCode)=> "{PropertyName} contains invalid fields";

} 

```

And the extension method:

```
public static class ValidatorExtensions {

  public static IRuleBuilderOptions<T, IncludeExpression> IncludeExpression<T>(this IRuleBuilder<T, IncludeExpression?> builder, params String[] fields) {
    return builder.SetValidator(new IncludeExpressionValidator<T, IncludeExpression?>(fields, StringComparer.InvariantCultureIgnoreCase)); 
  }

  public static IRuleBuilderOptions<T, IncludeExpression> IncludeExpression<T>(this IRuleBuilder<T, IncludeExpression?> builder, IEqualityComparer<String> comparer, params String[] fields) {
    return builder.SetValidator(new IncludeExpressionValidator<T, IncludeExpression?>(fields, comparer)); 
  }

}
```

**Comment by JeremySkinner** [comment]
The type definitions don't match up in your extension methods. 

If you define an extension method for `IncludeExpression?` the return type must also be for `IncludeExpression?` - you can't mix nullable and non-nullable like you're doing. Note that this isn't related to FluentValidation but is a requirement of the C# compiler. Your return type should be `IRuleBuilderOptions<T, IncludeExpression?>`. 

```csharp
public static IRuleBuilderOptions<T, IncludeExpression?> IncludeExpression<T>(this IRuleBuilder<T, IncludeExpression?> builder, params String[] fields) {
	return builder.SetValidator(new IncludeExpressionValidator<T, IncludeExpression?>(fields, StringComparer.InvariantCultureIgnoreCase));
}

public static IRuleBuilderOptions<T, IncludeExpression?> IncludeExpression<T>(this IRuleBuilder<T, IncludeExpression?> builder, IEqualityComparer<String> comparer, params String[] fields) {
	return builder.SetValidator(new IncludeExpressionValidator<T, IncludeExpression?>(fields, comparer));
}
```

It will then compile.

**Comment by mdmoura** [comment]
> It will then compile.

It does. Thank you ...
