### ISSUE TITLE
Overiding info displayed for collections

### ISSUE THREAD

**Issue by AndersMalmgren** [FluentValidation/FluentValidation#1875]
### Is your feature request related to a problem? Please describe.

If you have a collection and the validator for that collection is not valid it displays

> CollectionPropertyName[Index].PropertyName: Vallidation message

`CollectionPropertyName[Index]` doesnt help much finding which entity is faulty.

### Describe the solution you'd like

`ValidatorOptions.DisplayNameResolver` and `ValidatorOptions.PropertyNameResolver` doesnt help here we need soemthing on the `AbstractValidator<T>` class like

DisplayNameResolver(i => $"Invoice({i.InvoiceNumber})");

**Comment by AndersMalmgren** [comment]
Btw, I talk about when we have `ImplicitlyValidateChildProperties = true` If we explicit call RuleForEach we can use the OverideIndexer option

**Comment by JeremySkinner** [comment]
Hi, if you have `ImplicitlyValidateChildProperties` set to `true` then the property name resolution is *handled by ASP.NET* not by FluentValidation, as Implicit Child validation is a feature of ASP.NET's model binding process. So there's not really anything that FluentValidation can do in this case. 

If you need the flexibility of overriding the indexer, then you'll need to use explicit child validation, not implicit, and then you can make use of `OverrideIndexer`
