### ISSUE TITLE
custom return information

### ISSUE THREAD

**Issue by wdqzdd** [FluentValidation/FluentValidation#1876]
### Is your feature request related to a problem? Please describe.

asp.net core 3.1 
i want  custom return information.

my application has rpecific format.

what do i do?

![image](https://user-images.githubusercontent.com/27991992/147084231-4bcd7893-4d44-48ff-8543-d8906655dbd3.png)

### Describe the solution you'd like

1

**Comment by JeremySkinner** [comment]
The automatic 400 JSON response is not part of FluentValidation - this is coming from ASP.NET itself. Please see https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0#automatic-http-400-responses
