### ISSUE TITLE
Allow validators to be prefixed

### ISSUE THREAD

**Issue by sommmen** [FluentValidation/FluentValidation#1879]
### Is your feature request related to a problem? Please describe.

Right now i've gotten an OrderValidator setup like so:

``` csharp
public OrderValidator()
{
    ...

    RuleForEach(o => o.Discounts)
        .SetValidator(new OrderDiscountValidator());
}
}

...
internal class OrderDiscountValidator : AbstractValidator<OrderDiscount>
{
    public OrderDiscountValidator()
    {
       ...
        RuleFor(o => o.Description)
            .NotEmpty();
        
    }
}
```

The problem here is that right now i'm getting validation failure messages correctly if the description is empty, but i can't find out which `OrderDiscount` is the issue if there are multiple.

### Describe the solution you'd like

I'd love if i could prefix validators with a custom string. Something like:

``` csharp
internal class OrderValidator : AbstractValidator<Order>
{
    public OrderValidator()
    {
       SetPrefix(o => o.OrderNumber); 
        ...
    }
}

internal class OrderDiscountValidator : AbstractValidator<OrderDiscount>
{
    public OrderDiscountValidator()
    {
       SetPrefix(o => o.ExternalId); 
        ...
    }
}
```

This way i can get messages like:
`Order48823DD Discount.2134 The specified condition was not met for 'Discount Incl Tax'.`

### Describe alternatives you've considered

I haven't found any alternatives to this - but i'd love some suggestions.

**Comment by JeremySkinner** [comment]
Hi, out of the box the `PropertyName` on the validation failure will contain the index of the item within the collection. This is the usual/standard way of identifying which instance within the collection failed. 

However if you want something custom inside the *message* coming from the parent, then you can pass it in via the constructor:

```csharp
class OrderValidator
{
  public OrderValidator()
  {
    RuleForEach(o => o.Discounts)
        .SetValidator(o => new OrderDiscountValidator(o.OrderNumber));
  }
}

class OrderDiscountValidator : AbstractValidator<OrderDiscount>
{
    public OrderDiscountValidator(string parentOrderNumber)
    {

        RuleFor(o => o.Description)
            .NotEmpty().WithMessage($"Order: {parentOrderNumber}. Description is required");
    }
}
```
