### ISSUE TITLE
[Question]: V10 Breaking changes related to "Context.Rule.Member"

### ISSUE THREAD

**Issue by parmarprakash41** [FluentValidation/FluentValidation#1880]
### FluentValidation version

10.3.6

### ASP.NET version

.NET 5

### Summary

I have migrated from version 8.6.2 to 10.3.6 for performance reason. I have below code that is not working as I am not getting context.Rule directly. Could you please guide me for same. Thanks in advance.

### Steps to Reproduce

1) Here In my code, I am getting group attribute by context.Rule.Member and checked specified groupName contains or not.

`public static IRuleBuilderOptions<T, TProperty> IsWithinGroup<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder)
{
    return ruleBuilder.IsWithinList((entity, property, context) =>
    {
        var groupAttribute = context.Rule.Member.GetCustomAttribute<GroupAttribute>();
        return EnumHelper.ToEnumList<TProperty>(groupAttribute.GroupNames);
    });
}

private static IRuleBuilderOptions<T, TProperty> IsWithinList<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<T, TProperty, PropertyValidatorContext, IEnumerable<TProperty>> predicate)
{
    return ruleBuilder.Must((entity, property, context) =>
    {
        var list = predicate(entity, property, context);

        if (list == null)
        {
            // TODO: Add proper error message
            throw new NullReferenceException(nameof(list));
        }
        else
        {
            var contains = property == null || list.Contains(property);

            if (!contains)
            {
                context.MessageFormatter.AppendArgument("List", string.Join(", ", list));
            }

            return contains;
        }
    }).WithValidationErrorCode(nameof(ValidationErrors.VAL0069));
}`

**Comment by JeremySkinner** [comment]
Hello, this issue tracker is for tracking bugs in the FluentValidation library, and [isn't for general support/questions](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions), sorry.
