### ISSUE TITLE
Not working in ASP.Net Core 6.0  Web API 

### ISSUE THREAD

**Issue by kamlesh-nb** [FluentValidation/FluentValidation#1883]
### FluentValidation version

10.3.6

### ASP.NET version

.NET Core 6.0

### Summary

I am trying to use Fluent Validations in my ASP.Net Core Web API project, but it is not at all working. following is the code; I have followed all the steps mentioned in the documentation, but it is not working at all.

**Program.cs**

```
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddControllers();

builder.Services.AddMvcCore().AddFluentValidation(
    fv => {
        fv.RegisterValidatorsFromAssemblyContaining<Program>();
        fv.DisableDataAnnotationsValidation = true;
    }
);

// builder.Services.AddScoped<IValidator<Customer>,CustomerValidator>();

builder.Services.Configure<ApiBehaviorOptions>(options => 
  options.SuppressModelStateInvalidFilter = true);
  
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

public partial class Program {}
```

**Model Class**

```
public class Customer 
{
  public int Id { get; set; }
  public string Surname { get; set; }
  public string Forename { get; set; }
  public decimal Discount { get; set; }
  public string Address { get; set; }
}
```

**Validator Class**

```
using FluentValidation;

public class CustomerValidator : AbstractValidator<Customer>
{
  public CustomerValidator()
  {
    RuleFor(customer => customer.Surname).NotNull().WithMessage("Customer Surname cannot be Null!");
  }
}
```

And finally, the **Controller Class**

```
using Microsoft.AspNetCore.Mvc;

namespace APITest.Controllers;

[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    private readonly ILogger<WeatherForecastController> _logger;

    public WeatherForecastController(ILogger<WeatherForecastController> logger)
    {
        _logger = logger;
    }

    [HttpGet(Name = "GetWeatherForecast")]
    public IEnumerable<WeatherForecast> Get()
    {
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = Summaries[Random.Shared.Next(Summaries.Length)]
        })
        .ToArray();
    }

    [HttpPost]
    public IActionResult Post(Customer customer) {
        return Ok(customer);
    }
}
```

### Steps to Reproduce

Use the code given in summary.

**Comment by JeremySkinner** [comment]
Hi, FluentValidation 10.x is fully supported and works just fine with Web API projects on .net 6. If it’s not working correctly for you then this probably means you haven’t configured something correctly. 

Some things to try:
- make sure you’ve followed the docs at https://docs.fluentvalidation.net/en/latest/aspnet.html
- make sure your validators are defined in the correct assembly (your registration line indicates that they’re in the same assembly as `Program` but you should double check this)

if you’re still unable to get it to work then please provide a minimal, runnable, self-contained sample project that reproduces the issue and I’ll then be able to help further.

**Comment by JeremySkinner** [comment]
Oh one other thing I noticed is you’re not actually doing anything with the validation results inside your `Post` action. You’ll need to add a check for`ModelState.IsValid` and act accordingly.

**Comment by kamlesh-nb** [comment]
Hi @JeremySkinner,

Thanks for your quick response, this was just a .net6.0 test project, where I was testing the validations. 
I figured out what the issue is, somehow, mvc pipeline rejects the request, if non nullable field is null, so, can't test NotNull validations.

Let me know if there's any workaround you know for this, I am trying to figure out if we can do something with JSON Settings.

Thanks
Kamlesh

**Comment by JeremySkinner** [comment]
> somehow, mvc pipeline rejects the request, if non nullable field is null

that’s a part of asp.net’s model binding process and can’t be turned off, and isn’t something FluentValidation has any control over. you’d need to make the property nullable.
