### ISSUE TITLE
Invoking validator in ActionFilter

### ISSUE THREAD

**Issue by epitka** [FluentValidation/FluentValidation#1884]
### Is your feature request related to a problem? Please describe.

I would like to disable all automatic validation that happens when integrated with aspnetcore and then invoke same automatic validation manually in  ActionFilter. Reason for this is that we have another custom filter that changes the model, adds additional data from JWT token into a request model.   Validation of the model happens before this filter has a chance to run, so we are unable to validate model automatically but have to resort to hacks (use Mediatr behavior with FluentValidation).
I've seen quite few questions about this exact problem, but have not found answers. Solution below works now, if you think it is something that would be useful to others and implementation is ok, I can create PR...

### Describe the solution you'd like

~I'd like to know if it is possible to resolve validator in Action filter.  I have tried injecting IValidatorFactory into filer but it does not resolve validator. Getting validator from Services works though.~  Another problem is that even if I was able to resolve validator I would not be able to construct ValidationContext as it is has generic parameter. I could resort to reflection, but that seems like hack upon hack. 

setup

```
services .AddFluentValidation(
                    opt =>
                    {
                        opt.AutomaticValidationEnabled = false;
                        opt.DisableDataAnnotationsValidation = true;
                        opt.ImplicitlyValidateChildProperties = true;
                    });

services.AddValidatorsFromAssembly(typeof(Program).Assembly);
```

```
public class ValidateModelFilter : IActionFilter
{
    private const string ProblemType = "https: //tools.ietf.org/html/rfc7231#section-6.5.1";

    private readonly IValidatorFactory validatorFactory;

    public ValidateModelFilter(IValidatorFactory validatorFactory)
    {
        this.validatorFactory = validatorFactory;
    }

    public void OnActionExecuting(ActionExecutingContext context)
    {
        var traceId = Activity.Current?.Id ?? context.HttpContext?.TraceIdentifier;

        foreach (var actionArgument in context.ActionArguments)
        {
            var modelToValidate = actionArgument.Value;

            // cache type information
            var modelToValidateType = modelToValidate!.GetType();

            var validator = this.validatorFactory.GetValidator(modelToValidateType);

            if (validator != null)
            {
                var openGenericType = typeof(ValidationContext<>);
                var closedMakeGenericType = openGenericType.MakeGenericType(modelToValidateType);

                var validationContext = Activator.CreateInstance(closedMakeGenericType, new object[] { modelToValidate });

                if (validationContext != null)
                {
                    var results = validator.Validate((IValidationContext)validationContext);
                    results.AddToModelState(context.ModelState, null);
                }
            }
        }

        if (!context.ModelState.IsValid)
        {
            var problemDetails = new ValidationProblemDetails(context.ModelState);
            context.Result = new BadRequestObjectResult(problemDetails);
            problemDetails.Type = ProblemType;
            problemDetails.Extensions.Add("traceId", traceId);
        }
    }

    public void OnActionExecuted(ActionExecutedContext context)
    {
    }
```

**Comment by JeremySkinner** [comment]
> invoke same automatic validation manually in ActionFilter

This isn't possible I'm afraid. Automatic validation is part of ASP.NET's model binding process, it isn't a direct feature of FluentValidation, and can only be run during model binding. You'd need to instantiate the validator and invoke it manually (as you are doing in your filter). 

> Another problem is that even if I was able to resolve validator I would not be able to construct ValidationContext as it is has generic parameter

You don't need to use reflection or do anything with generics, just directly instantiate a `ValidationContext<object>`.

```csharp
var validator = this.validatorFactory.GetValidator(modelToValidateType);
IValidationContext context = new ValidationContext<object>(modelToValidate);
var results = validator.Validate(context);
```
