### ISSUE TITLE
Document on how to delegate CustomValidators to buildt-in/other ones

### ISSUE THREAD

**Issue by rklec** [FluentValidation/FluentValidation#1886]
### Is your feature request related to a problem? Please describe.

I want to write a simple [custom validator/extension](https://docs.fluentvalidation.net/en/latest/custom-validators.html) for getting the file name of a file (path) provided in a property and

```csharp
namespace Something
{
    public static class FileValidatorExtensions
    {
        /// <summary>
        /// Defines a 'must have file name' validator on the current rule builder.
        /// The validation will succeed if the file name equals the specified value.
        /// The validation will fail if the file name is different than the specified value or cannot be extracted.
        /// </summary>
        /// <typeparam name="T">Type of object being validated</typeparam>
        /// <param name="ruleBuilder">The rule builder on which the validator should be defined</param>
        /// <param name="fileName">The file name being compared</param>
        /// <returns></returns>
        public static IRuleBuilderOptions<T, string> MustHaveFileName<T>(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
            ruleBuilder.Must(x => Path.GetFileName(x) == fileName);
    }
}
```

Now, the problem is if that validator fails, I do not see any output of what the current and expected value are etc.

As such, I want to **delegate the customvalidator after getting the value I want** to the existing `Equal` validator, because it all already does this, so why bother reimplementing it?
It looks quite simple, as I can just use `.Equal` instead of `.Must`, but it is not that easy apparently... 🤔 

### Describe the solution you'd like

I tried it like this, but I am a little stuck with the C# syntax here:
```csharp
        public static IRuleBuilderOptions<T, string> MustHaveFileName<T>(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
            ruleBuilder.Equal<T, string>((rootObject, propertyValue) => Path.GetFileName(propertyValue));
```

or....
```csharp
        public static IRuleBuilderOptions<T, string> MustHaveFileName<T>(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
            ruleBuilder.Equal<T, string>((rootObject, propertyValue) => new Expression<Func<T, string>>(Path.GetFileName(propertyValue)));
```

It all does not work.

### Describe alternatives you've considered

IMHO this is a popular use case (also file/path validation in general), to be documented. At least one such simple example would IMHO make implementing a custom validator much easier.

Also, I guess it would avoid people having to reqrite such a thing as equality comparison, which is likely a popular thing for custom validators. You do sth. and get a different result than the original property and now compare it.

Of course, you could also do it inline and get the value in a lambda expression there, but after all you want to extract it into a custom validator so you don't have to do it multiple times and have it in there, actually.

### Additional Context

FluentValidation v10.0.4

Another use case would e.g. be combining multiple operators in such a CustomValidator, e.g. most often you may check a property for `null` before you actually do sth.,

**Comment by JeremySkinner** [comment]
Hello,

Your first example using `Must` is the correct way to do this. 

I think you may have misunderstood the `Equal` and `NotEqual` validators. The overload that takes a lambda expression is for performing a cross-property equality comparison, where you compare one property to another of the same type on the same object instance, eg `RuleFor(x => x.Surname).NotEqual(x => x.Forename)`. This isn't relevant in your use case.

The other overload of `Equal` just takes a constant value, so you could just use that overload if you don't care about lazy evaluation:

public static IRuleBuilderOptions<T, string> MustHaveFileName<T>(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
	ruleBuilder.Equal(Path.GetFileName(fileName));


...but if you want it evaluated lazily then you should use `Must`, which is FluentValidation's intended method for performing any kind of custom checks when you need lazy evaluation. 

> Another use case would e.g. be combining multiple operators in such a CustomValidator, e.g. most often you may check a property for null before you actually do sth.,

You can do that by method chaining on the rule within your extension method, in exactly the same way as you would if you called RuleFor directly, eg:

```csharp
public static IRuleBuilderOptions<T, string> MustHaveFileName<T>(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
        ruleBuilder.NotNull().Must(propertyValue => Path.GetFileName(propertyValue) == fileName);

```

If you feel that the docs could use some more examples or if you think the existing ones need clarifying please feel free to open a PR for the docs and I'll happily give it a review. Thanks!

**Comment by rklec** [comment]
> Must is FluentValidation's standard way of doing any kind of custom checks and is the correct method to be using here, so your firs implementation of MustHaveFileName above is correct.

Hmm but the issue then still is I would have to write the failure messages etc. manually by myself. Can't I re-use the existant `Equal` validator?  So that I automatically get an error message `Expected to equal FileName, but was FileNameX` e.g.
Actually, what you initially wrote with a static Equal validator sounds good?

I.e.:
```csharp
public static IRuleBuilderOptions<T, string> MustHaveFileName(this IRuleBuilder<T, string> ruleBuilder, string fileName) =>
ruleBuilder.Equal(Path.GetFileName(fileName));
```

I guess I don't use [that Lazy feature anyway](https://docs.simpleinjector.org/en/latest/howto.html#lazy), so well...

**Comment by JeremySkinner** [comment]
> but the issue then still is I would have to write the failure messages etc. manually by myself

Why is that a problem? You only need to define the message once in your extension method.  

> Actually, what you initially wrote with a static Equal validator sounds good?

That's passing the `fileName` variable to `Path.GetFileName`, not the property value, so I don't think that's correct?

**Comment by rklec** [comment]
Ah thanks, this helps a lot thanks! 🙂
