### ISSUE TITLE
List validation does not validate for child class

### ISSUE THREAD

**Issue by SociallyAwkwardBuddha** [FluentValidation/FluentValidation#1889]
### FluentValidation version

10.3.6

### ASP.NET version

.NET 6

### Summary

NotEmpty and Must validations on List properties do not execute for the child class. Not Null executes fine.

### Steps to Reproduce

1. Create a class with a list
2. Create sub class
3. Create api endpoint for both classes
4. Make api call with empty list for each

base class validation failing for empty location array (expected)
![image](https://user-images.githubusercontent.com/77939994/151647697-f884cb80-2451-426c-a094-13537a08afce.png)

sub class validation passing for empty location array (not expected)
![image](https://user-images.githubusercontent.com/77939994/151647722-cd5dac99-7390-4469-a1f8-35cb8a188e1a.png)

sub class validation failing as expected for null location array (expected)
![image](https://user-images.githubusercontent.com/77939994/151647734-a207298a-f6f6-4c74-8da1-9e78a007e79f.png)

**Comment by JeremySkinner** [comment]
You haven’t provided any sample code to be able to reproduce the problem.
