### ISSUE TITLE
Email spaces validation

### ISSUE THREAD

**Issue by 21r8390** [FluentValidation/FluentValidation#1890]
### FluentValidation version

10.3.6

### ASP.NET version

(Blazor) 6.0.1

### Summary

The `RuleFor(f => f.Email).EmailAddress();` does not check for spaces in an email address. So the email `test       ing@test.dev` will be shown as valid.

The local-part of the email address may use any of these ASCII characters:
---
> uppercase and lowercase Latin letters A to Z and a to z;
> digits 0 to 9;
> special characters !#$%&'*+-/=?^_`{|}~;
> dot ., provided that it is not the first or last character unless quoted, and provided also that it does not appear consecutively  unless quoted (e.g. John..Doe@example.com is not allowed but "John..Doe"@example.com is allowed);
> space and "(),:;<>@[\] characters are allowed with restrictions (they are only allowed inside a quoted string, as described in the paragraph below, and in addition, a backslash or double-quote must be preceded by a backslash);
> comments are allowed with parentheses at either end of the local-part; e.g. john.smith(comment)@example.com and (comment)john.smith@example.com are both equivalent to john.smith@example.com.

**Source:**
_https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address_

### Foo class & FooValidator:
```csharp
	public class Foo
	{
		public string Email { get; set; }
	}

	public class FooValidator : AbstractValidator<Foo>
	{
		public FooValidator()
		{
			// !! Email is a email address
			RuleFor(d => d.Email).EmailAddress();
		}

		public Func<Foo, string, Task<IEnumerable<string>>> ValidateValue => async (Foo model, string propertyName) => {
			// Create the error messages from the model

			var result = await ValidateAsync(ValidationContext<Foo>.CreateWithOptions(model, x => x.IncludeProperties(propertyName)));
			if (result.IsValid)
				return Array.Empty<string>();
			return result.Errors.Select(e => e.ErrorMessage);
		};
	}
```

### How I call the validator:
```csharp
    Foo foo = new();
    FooValidator fooValidator = new();

    private void ValidateFoo()
    {
        // Bad email with spaces
        foo.Email = "test ing@test.dev";

        // Result is empty => email is valid??
        var result = fooValidator.Validate(foo);
    }
```

**Comment by JeremySkinner** [comment]
This is expected. See https://github.com/FluentValidation/FluentValidation/issues/1643#issuecomment-781300192
