### ISSUE TITLE
EmailValidator regexp incorrect

### ISSUE THREAD

**Issue by gelatincrypto** [FluentValidation/FluentValidation#1892]
### FluentValidation version

10.3.6

### ASP.NET version

.net 6

### Summary

I have updated my project to version .net 6. At the same time, I also updated the FluentValidation dependency.AspNetCore from version 8.1.1 to version 10.3.6.

After the update, the following emails started to pass validation (although it is obvious that they are incorrect):
sms@paysystemtech (doesnt have dot after @)
sms@paysystem. tech (with whitespace after dot)

### Steps to Reproduce

Validation code for my model:
 ```
 RuleFor(m => m.ReceiveEmail).ReceiveEmail();


  public static IRuleBuilderOptions<T, string> ReceiveEmail<T>(this IRuleBuilder<T, string> ruleBuilder)
  {
            return ruleBuilder.EmailAddress().WithMessage("Invalid email");
  }
```

**Comment by JeremySkinner** [comment]
This is the expected behaviour and has been covered on this issue tracker several times, and is also covered in the documentation. Please see https://github.com/FluentValidation/FluentValidation/issues/1643#issuecomment-781300192 for details.
