### ISSUE TITLE
Default cascade mode (continue) not working properly.

### ISSUE THREAD

**Issue by matteo-mosca** [FluentValidation/FluentValidation#1896]
### FluentValidation version

10.2.3

### ASP.NET version

.NET 6

### Summary

I am building a main validator with a few sub validators, that are set with "SetValidator".

When running validation with multiple errors on multiple properties, only the first error is reported by the framework as if I had set CascadeMode to "Stop".

By setting manually CascadeMode to "Continue" in the main validator all the rules are run correctly but not the rules inside the sub validators. For those to work I also have to set "Continue" in each one of them.

Setting the global cascade mode to "Continue" also does not work, only setting it in each individual validator works, which is my current workaround albeit not an ideal one.

### Steps to Reproduce

Create a validator with multiple rules for different properties.
Try to submit a validation with multiple errors on different properties.
The validation result contains only the first failure as if CascadeMode was set to "Stop".

**Comment by JeremySkinner** [comment]
[You haven't provided any code to reproduce the issue](https://github.com/FluentValidation/FluentValidation/blob/7a6a426e3a868b720e4d553fefdc87b7643512f0/.github/CONTRIBUTING.md#filing-bug-reports-and-feature-requests)

**Comment by matteo-mosca** [comment]
I did not provide any code because it affects any basic validator written with your library, which you obviously know how it works. Shall I provide code from one of your tutorials?
I am reporting a real problem here, maybe related to the use of .Net 6 I don't really know, but right now it's becoming messy to use your library which I used without issues for years.

**Comment by JeremySkinner** [comment]
@matteo-mosca Yes, please provide all necessary sample code to reproduce the issue, as is requested in the issue template. 

I did try it myself and could not reproduce a problem- it worked correctly, so a sample project will be needed to investigate further. Please re-open the issue once you’ve provided an executable sample project that clearly illustrates the issue. 

One thing that did occur to me, is please double check that the behaviour you’re seeing is actually coming from FluentValidation, and not asp.net itself. Asp.net has its own parameter validation that checks for type conversions errors and for missing values for non-nullable properties. These checks occur *before* asp.net invokes FluentValidation, and if they fail then asp.net will not get as far as executing your validator. This happens in the following situations: 
- you attempt to send a value that can’t be conveyed to the target type (eg trying to send sending something to a DateTime property that isn’t a date string)
- Sending a null value for a type that is marked as non-nullable (either a non-nullable value type such as int/datetime, or a non nullable reference type.)

the above 2 situations generate generic messages such as “a value is required” or “the format is incorrect”. If these are what you’re seeing, then they are generated by asp.net itself and are not something that FluentValidation has any control over.

**Comment by matteo-mosca** [comment]
Thank you for your reply, I'm sure it's not the scenario you described because I am invoking fluent validation manually inside my business layer unit of work.

I cannot provide the project I'm working on but I'll try to create a sample project with the problem when I have the time. For now I had to put "CascadeMode.Continue" in the constructor of all my validators in order to have the expected behavior.

Thanks.

**Comment by JeremySkinner** [comment]
If you had to explicitly set CascadeMode to Continue inside the validator then that suggests that the default has been overridden to `Stop` at the global level. Make sure you have nowhere in your application's startup routine that's explicitly setting `ValidatorOptions.Global.CascadeMode`.
