### ISSUE TITLE
ServiceProviderValidatorFactory : why not use GetRequiredService?

### ISSUE THREAD

**Issue by StefH** [FluentValidation/FluentValidation#1899]
### FluentValidation version

latest

### Summary

The current code from ServiceProviderValidatorFactory is this:

``` c#
public override IValidator CreateInstance(Type validatorType) {
    return _serviceProvider.GetService(validatorType) as IValidator;
}
```

Would it make sense to change it to this?
``` c#
public override IValidator CreateInstance(Type validatorType) {
    return (IValidator) _serviceProvider.GetRequiredService(validatorType);
}
```

1. GetRequiredService makes sure that if the implementation is not found, an exception is thrown
2. There is no need to use the `as IValidator`, just cast it. In case casting fails, an exception is thrown

### Steps to Reproduce

See summary.

**Comment by JeremySkinner** [comment]
We explicitly *don't* want to throw an exception. Validator factories should return `null` if the validator can't be found. This behaviour is necessary for integration with ASP.NET's validation infrastructure.
