### ISSUE TITLE
problem upgrading 8.6.2 to 10.3.6

### ISSUE THREAD

**Issue by alexan1** [FluentValidation/FluentValidation#1900]
### FluentValidation version

10.3.6

### ASP.NET version

.NET 6

### Summary

in ValidateModel method:

var validationResults = validator.Validate(editContext.Model);

Validate now require IValidationContext parameter, but when trying to cast it:

var validationResults = validator.Validate((IValidationContext)editContext.Model);

get runtime error:

Unable to cast object of type 'SearchModel' to type 'FluentValidation.IValidationContext'

In ValidateField metod:

var context = new ValidationContext(fieldIdentifier.Model, new PropertyChain(), new MemberNameValidatorSelector(properties));

ValidationContext is now gereric, so it was replaced by:

var context = new ValidationContext<object>(fieldIdentifier.Model, new PropertyChain(), new MemberNameValidatorSelector(properties));

But get context is null.

Also in SearchValidator

RuleFor(x => x.SearchValue).Transform(x => x.Triim()).MinimumLength(3).WithMessage(x => localizer[nameof(Resources.SharedResource.ErrorSearchMinLengthRequired)]);

Transform doesn't work anymore. How I can trim value?

Thanks for any help.

### Steps to Reproduce

code almost the same as in this repo: https://github.com/chrissainty/FluentValidationWithRazorComponents

**Comment by JeremySkinner** [comment]
These are covered in our documentation. Please review the 8.x to 9.x upgrade guide. 

This section explains how to use `ValidationContext<object>`:
https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload
