### ISSUE TITLE
Are possible to exclude certain validators from automatic validation

### ISSUE THREAD

**Issue by nzabsodislab** [FluentValidation/FluentValidation#1901]
### Is your feature request related to a problem? Please describe.

Is it possible to exclude certain validators from automatic validation? But these validators registered in DI already.

For some purposes I want to use StringValidator, but I dont want to use it each time, when a string arrives on the backend?

### Describe the solution you'd like

I would to except some validators from autovalidation for asp .net mvc core.

**Comment by JeremySkinner** [comment]
If it's the root model, then you can use the `CustomizeValidator` attribute to skip validating certain parameters on a case by case basis. Please review the documentation: https://docs.fluentvalidation.net/en/latest/aspnet.html#validator-customization

If you're using implicit child validation then no, you can't exclude it as this is a feature of ASP.NET that fluentvalidation has no control over.

Please note for future reference, this issue tracker is for reporting bugs in the core FluentValidation library. [This is not a general support forum](https://github.com/FluentValidation/FluentValidation/blob/80961b87dc2a591bbff6f470ab24565e38f9a684/.github/CONTRIBUTING.md#general-support-feedback-and-discussions), sorry.
