### ISSUE TITLE
Add a NotMatch Method

### ISSUE THREAD

**Issue by RyanGaudion** [FluentValidation/FluentValidation#1902]
### Describe the solution you'd like

I wish to check to see if a string property does not match a regex query rather than matches one. Could we add a .NotMatches method or is there a way to inverse the current .Matches method?

### Describe alternatives you've considered

Current alternative is to use .Must and write the regex match myself returning `!match.Success`

**Comment by JeremySkinner** [comment]
Hi there, thanks for the suggestion. 

We aren't planning on adding any more additional validators to the core library, but you can add this yourself with an extension method:

```csharp
public static IRuleBuilderOptions<T, string> NotMatches<T>(this IRuleBuilder<T, string> ruleBuilder, string expression) {
	var regex = new Regex(expression, RegexOptions.None, TimeSpan.FromSeconds(2.0));
	return ruleBuilder.Must(value => !regex.IsMatch(value)).WithErrorCode("RegularExpressionValidator");
}
```
