### ISSUE TITLE
Custom HTTP status codes

### ISSUE THREAD

**Issue by Pankraty** [FluentValidation/FluentValidation#1904]
### Is your feature request related to a problem? Please describe.

FluentValidation greatly helps in organizing all validation logic in one place but if we want to implement comprehensive Web API utilizing different HTTP codes, such as `NotFound` (404), `Forbidden` (403), `Conflict` (409), and so on, we have to keep these pieces of logic apart from other validation rules because built-in validation will only return `BadRequest` response in case of any failure.
Particularly, we wanted our APIs respond with 404 when an entity does not exist but as FluentValidation did not support such use case, some of the teams chose to neglect this recommendation and return `BadRequest` (keeping all validations in one place), while others preferred to put additional logic into controllers and/or handlers for checking entity existence after the validation.

### Describe the solution you'd like

I have prepared a solution with the extension methods allowing to support HTTP responses with alternative status codes: https://github.com/Pankraty/FluentValidation.HttpExtensions

I don't think it must be incorporated into the `FluentValidation.AspNetCore` (though, I would not object if you chose that). But I would be greatful if you allowed to publish the nuget package with this name: `FluentValidation.HttpExtensions`, because `FluentValidation*` seems to be a reserved prefix.

### Describe alternatives you've considered

We could use this library internally, without publishing to nuget.org, but I figured, it may be helpful to other devs for designing flexible APIs.
Alternatively, we may use a different prefix for the package, but I think using `FluentValidation.*` will increase the visibility of the package.

**Comment by JeremySkinner** [comment]
Hi @Pankraty `FluentValidation` is a reserved prefix that indicates an official package that we maintain. You'll need to use a different prefix. Generally 3rd party packages use the convention `<YourCompanyName>.FluentValidation.Whatever`
