### ISSUE TITLE
Regex Source Generator

### ISSUE THREAD

**Issue by adamradocz** [FluentValidation/FluentValidation#1907]
### Describe the solution you'd like

In .NET 7 the [precompiled regex](https://github.com/dotnet/runtime/issues/44676) can improve the performance quite a bit.  Are you planning the use this feature in the next release?

### Additional Context

https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation

**Comment by JeremySkinner** [comment]
For FluentValidation's own internals we don't use any regexes in the library (apart from the old regex-based email validator, which is deprecated) so there wouldn't really be anything actionable here.

For end users, they can make use of precompiled regexes and pass them into `Matches` or `Must` without requiring any changes to the library.

**Comment by JeremySkinner** [comment]
Oh we also use a regex for parsing out message format args, so could potentially make use of it here if benchmarks show it to be worthwhile. Will assign this to the backlog to investigate once .net 7 is released.

**Comment by JeremySkinner** [comment]
Decided against this as I don't want to have to rely on conditional compilation for this. Will stick with `RegexOptions.Compiled` for our parsing of message placeholders.
