### ISSUE TITLE
Contributing to FluentValidation

### ISSUE THREAD

**Issue by Pirand92** [FluentValidation/FluentValidation#1908]
### Is your feature request related to a problem? Please describe.

Hi,
in my company we make a large use of FluentValidation and for that I'd like contribute to this repo by adding new built-in validators.

For example I created a new validator called AtLeastOneFilled that check if the object you pass ha at least one property valorized. Unfortunely I can't push my code because I'm not authoirzed.

So, is it possible contribute in some way?

Thank you very much for your attention.

### Describe the solution you'd like

Contribute with new built-in validators

**Comment by JeremySkinner** [comment]
Hi, thanks for wanting to be involved in the project.

We don't currently plan on accepting any new validators into the core library as these add a large support & maintenance overhead, and we intentionally provide extensibility to points to allow users to add their own validators without them. 

If you'd like to make your validators publicly available then I'd suggest releasing them as a 3rd party package which you maintain and support yourself. 

If your company would like to support the project directly, then the most valuable form of contribution is [ongoing monthly financial sponsorship](https://github.com/FluentValidation/FluentValidation#supporting-the-project).
