### ISSUE TITLE
`RegularExpressionValidator` should include `{RegularExpression}` placeholder in default message template

### ISSUE THREAD

**Issue by gitfool** [FluentValidation/FluentValidation#1909]
### Is your feature request related to a problem? Please describe.

More information is required to fix a failing regex validation, in particular the pattern that was used, so I was surprised to find this isn't already in the default message template.

### Describe the solution you'd like

Change the default message template for all languages to include the `{RegularExpression}` placeholder; e.g. [EnglishLanguage](https://github.com/FluentValidation/FluentValidation/blob/81f0b2bfce219a16e5fc9dd8e97309c7faef5b2d/src/FluentValidation/Resources/Languages/EnglishLanguage.cs#L44) could change from:
```
"'{PropertyName}' is not in the correct format."
```
to something like:
```
"'{PropertyName}' must match regex '{RegularExpression}'."
```

### Describe alternatives you've considered

This could be worked around by using `WithMessage`, but I created this issue because it would be _much nicer_ if this was the default behavior, similar to other validators that already include such relevant information.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this isn't something we'll be changing.

The default error messages are intended to be end-user friendly and non-technical, so we intentionally do not expose the the regex in the message. You should use `WithMessage` in this situation. 

Alternatively you could override the default message [using specifying a custom language manager](https://docs.fluentvalidation.net/en/latest/localization.html#default-messages).
