### ISSUE TITLE
Enabling automatic validation of PageModels in ASP.NET Razor Pages

### ISSUE THREAD

**Issue by danielgreen** [FluentValidation/FluentValidation#1911]
### Is your feature request related to a problem? Please describe.

As described in these issues https://github.com/FluentValidation/FluentValidation/issues/887 and https://github.com/dotnet/aspnetcore/issues/4911, the PageModel of a Razor Page isn't automatically validated.

Having to create another class as a child property of the PageModel in order to get automatic validation defeats one of the benefits of the Razor Pages approach. Alternatively, having to manually validate the PageModel is an annoyance.

### Describe the solution you'd like

With the use of a Razor Page filter, validation can be run against the PageModel once model binding has taken place.

Is it possible to have the FluentValidation.AspNetCore package include this filter with an option for wiring it up?

```using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc.Filters;

namespace WebApplication1;

public class RazorPageFilter : IAsyncPageFilter
{
    public Task OnPageHandlerSelectionAsync(PageHandlerSelectedContext context) => Task.CompletedTask;

    public async Task OnPageHandlerExecutionAsync(PageHandlerExecutingContext context, PageHandlerExecutionDelegate next)
    {
        if (!HttpMethods.IsPost(context.HttpContext.Request.Method))
        {
            await next.Invoke();
            return;
        }

        var pageModel = context.HandlerInstance;
        var modelType = pageModel.GetType();
        var validatorType = typeof(IValidator<>).MakeGenericType(modelType);
        var validator = context.HttpContext.RequestServices.GetService(validatorType);

        if (validator is not null)
        {
            var results = (ValidationResult)validator.InvokeMethod("Validate", new object[] { pageModel });
            results.AddToModelState(context.ModelState, null);
        }

        await next.Invoke();
    }
}

public static class TypeUtils
{
	public static object InvokeMethod(this object target, string methodName, object[] methodArgs)
	{
		return target.GetType().InvokeMember(
			methodName,
			BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.Public | BindingFlags.NonPublic,
			null,
			target,
			methodArgs);
	}
}
```

### Describe alternatives you've considered

If including a Razor Page filter within FluentValidation isn't palatable, perhaps the docs could include sample code to show how a developer could add one to the solution?

**Comment by JeremySkinner** [comment]
Hi, as this isn't something supported in ASP.NET itself it isn't something that FluentValidation will support either. If Microsoft ever add support to ASP.NET for validating the Pagemodel directly then FluentValidation will support this too.

Using a filter to perform validation isn't ideal as it prevents the pipeline from running in the correct order. You're welcome to take this approach within your own project, but as it can potentially cause issues we won't be including this ourselves nor is it an approach we can recommend. You should really take this up with the ASP.NET team directly, not with us.

**Comment by danielgreen-nes** [comment]
Thanks for the reply, would you be able to expand on the point about the pipeline not running in the correct order please?

**Comment by danielgreen** [comment]
Thanks for the reply, would you be able to expand on the point about the pipeline not running in the correct order please?

**Comment by JeremySkinner** [comment]
@danielgreen By default asp.net runs validation rules before filters are invoked, allowing the completed validation results to be accessed inside the filter. (For example, the [ModelStateInvalidFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.modelstateinvalidfilter?view=aspnetcore-6.0) relies on this).

Invoking validation inside a filter could be problematic for anyone who relies on this behaviour.

**Comment by danielgreen** [comment]
Hopefully taking that approach in my own project will be OK, since there is no other validation happening against the page model, and it would be limited to Razor Pages not Web API endpoints. Understandable that you wouldn't recommend it generally however, and I have asked the question of the ASP.NET team.

**Comment by JeremySkinner** [comment]
FYI if you do decide to use this approach in your own project, then you can eliminate some of the reflection overhead by using the non-generic `IValidator` interface:

```
        var validatorType = typeof(IValidator<>).MakeGenericType(modelType);
        var validator = context.HttpContext.RequestServices.GetService(validatorType) as IValidator;

        if (validator is not null)
        {
            var validationContext = new ValidationContext<object>(pageModel);
            var results = validator.Validate(validationContext);
            results.AddToModelState(context.ModelState, null);
        }
```
