### ISSUE TITLE
Allow wildcard in call to SetRulesetForClientsideMessages

### ISSUE THREAD

**Issue by danielgreen** [FluentValidation/FluentValidation#1912]
### Is your feature request related to a problem? Please describe.

When calling SetRulesetForClientsideMessages I need to pass all the ruleset names, when it would be simpler to pass "*" as a wildcard. This already works for IncludeRuleSets I believe.

### Describe the solution you'd like

A call to HttpContext.SetRulesetForClientsideMessages("*") should mean that all rules (whether in a ruleset or not) should be used to generate client-side validation attributes.

(Hopefully this isn't user error on my part - apologies if so!)

**Comment by JeremySkinner** [comment]
10.4 has been pushed to nuget with this change.

**Comment by danielgreen-nes** [comment]
@JeremySkinner Thanks for pushing that out so quickly. Should it be added to the docs on here as well https://docs.fluentvalidation.net/en/latest/aspnet.html

**Comment by danielgreen** [comment]
@JeremySkinner Thanks for pushing that out so quickly. Should it be added to the docs on here as well https://docs.fluentvalidation.net/en/latest/aspnet.html

**Comment by JeremySkinner** [comment]
Could you open a PR to add it? Thanks!
