### ISSUE TITLE
Multiple property names in message

### ISSUE THREAD

**Issue by CME64** [FluentValidation/FluentValidation#1921]
### Is your feature request related to a problem? Please describe.

Say I have a property that must be validated against other properties like so
`RuleFor(i => i.total).Equal(p.itemA + p.itemB).WithMessage(i => $"property {PropertyName} must be equal to {i.itemA.PropertyName} + {i.itemB.PropertyName}")`

But the validator catches only the property name being validated with the placeholder `{PropertyName}`.

### Describe the solution you'd like

It would be awesome to be able to access other property names using the same methodology
however I'm currently using `nameof(i.itemA)` in order to resolve the names.

I suggest the following methodology to add this feature
`RuleFor(i => (i.total, i.itemA, i.itemB) ).Equal(p.itemA + p.itemB).WithMessage(i => $"property {PropertyName} must be equal to {PropertyName1} + {PropertyName2}")`

where the rule has an overload of accepting a tuple. the first element is always the validated property and is backward compatible with the {PropertyName}, the rest are just mapped in terms of names to the passed properties in the order provided e.g. PropertyName1 refers to itemA in the order provided.

### Describe alternatives you've considered

or we just keep using `nameof` and it is added to the documentation or somewhere to let people know they can use that instead

### Additional Context

I understand it is a difficult to map other random properties names or even extend all properties just to get their names and probably this is no the ideal solution.
Also I suggest loading names in relation the validated object (e.g. Person.Address.ZipCode instead of ZipCode or using the attribute text description/summary) since it's not meant to be a description when it's called property name. You could have another property called PropertyDescription for that.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, but this isn't something we'll be adding. Your solution using `nameof` (or just hard-coding the name) is the correct/intended way to handle this. Please feel free to submit a PR for the documentation if you think it'd be worth adding some examples for this. 

> Also I suggest loading names in relation the validated object 

Property names within the message are intended to be human-readable so we intentionally don't include the full path by default. The full path of the property being validated is exposed as a separate property on the `ValidationFailure`. 

If you want to include the full path inside the message then you'd need to access `context.PropertyName` inside either a call to `Must` or `Custom` and explicitly insert this to the message.
