### ISSUE TITLE
FluentValidation DI causes a conflict with EFCore at design time

### ISSUE THREAD

**Issue by rezathecoder** [FluentValidation/FluentValidation#1922]
### FluentValidation version

10.4

### ASP.NET version

6.0.3

### Summary

Registering FluentValidation using RegisterValidatorsFromAssemblies() method creates a conflict with EFCore that you can't run migrations or other EFCore command line tools and raises following error:

Unable to create an object of type 'AppDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

### Steps to Reproduce

I have provided a repo that demonstrate this issue:
https://github.com/rezathecoder/FluentValidationEfCoreConflict

Clone the repo and run one of the EFCore command line tools like 'add-migration InitialCreate' and you'll get the error.
Then just comment this line:
https://github.com/rezathecoder/FluentValidationEfCoreConflict/blob/d78f3be28c046997000b1392e98d8e49e5c1e317/Program.cs#L21
Run the command again and it will work this time

**Comment by JeremySkinner** [comment]
Hi, this isn't an issue with FluentValidation. 

The `RegisterValidatorsFromAssemblies` method loops over all public types within the assemblies that you pass in. You're passing in `AppDomain.CurrentDomain.GetAssemblies()` which means *all assemblies that are loaded into the AppDomain*, which includes EF Core's design-time assemblies. It isn't FluentValidation's fault that EF Core throws an exception when its assemblies are reflected over. Instead, you should only be including assemblies that contain validators. For example, 

```
fv.RegisterValidatorsFromAssemblyContaining<MyValidator>();
```
