### ISSUE TITLE
Length client side validation of HTML Select isn't working properly

### ISSUE THREAD

**Issue by TheWayTC** [FluentValidation/FluentValidation#1925]
### FluentValidation version

10.4.0

### ASP.NET version

.NET 6

### Summary

Length client side validation of HTML Select isn't working properly. After some testing, it looks like the client side validation thinks the length of an HTML select value is always 1 (assuming something is actually selected). All server side validation is working fine, but the client is stopping it.

I realize this an odd use case. My work around for now is to only validate that is it NotEmpty() because I don't want to remove all client side validation.

### Steps to Reproduce

1. Made a project by doing `dotnet new webapp -o FluentValidationTest` and added FluentValidation package with `dotnet add package FluentValidation.AspNetCore --version 10.4.0`
2. Added a Test class and validator.
```
public class Test
{
    public string? Something { get; set; }
}

public class TestValidator : AbstractValidator<Test>
{
    public TestValidator()
    {
        RuleFor(t => t.Something).NotEmpty().Length(3); 
    }
}
```
3. To Index.cshtml.cs I added
```
[BindProperty]
public Test Test { get; set; }

public void OnGet()
{
    Test = new Test();
}
```
4. To Index.cshtml I added
```
<div asp-validation-summary="All" class="text-danger"></div>

<form method="POST">
    <div class="row">
        <div class="col-lg-2">
            <label asp-for="Test.Something" class="form-label"></label>
            <select asp-for="Test.Something" class="form-select">
                <option value=""></option>
                <option value="AAA">A value</option>
            </select>
            <span asp-validation-for="Test.Something" class="text-danger"></span>
        </div>
    </div>

    <br />
    <button type="submit">Submit</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
```
5. Hooked up the app for client side validation with
```
.AddFluentValidation(options =>
    {
        // Validate child properties and root collection elements
        options.ImplicitlyValidateChildProperties = true;
        options.ImplicitlyValidateRootCollectionElements = true;
        // Automatic registration of validators in assembly
        options.RegisterValidatorsFromAssemblyContaining<TestValidator>();
    });
```
added to `builder.Services.AddRazorPages()` in Program.cs

**Comment by JeremySkinner** [comment]
Hello, FluentValidation doesn't provide any client-side validation directly ([see the docs](https://docs.fluentvalidation.net/en/latest/aspnet.html#clientside-validation)). 

Clientside validation is done by ASP.NET's integration with the jQuery-Validate javascript library, so this isn't something we have control over. 

If you believe this is a bug then I'd suggest you report it to the appropriate maintainers. However, my understanding is that the clientside length validator is only intended to validate the length of `<input type="text">` elements and is not intended for use with `<select>` elements.

**Comment by TheWayTC** [comment]
I see. That makes sense given FluentValidation doesn't have its own JavaScript to include like some Data Annotation extensions do. I tested the same scenario using the built-in Data Annotations and it has the same issue so this all makes sense now.

Thanks for the quick response by the way.
