### ISSUE TITLE
Inconsistent Behavior Of Built-in Empty() Validator On String Variables

### ISSUE THREAD

**Issue by HuggerCoursera** [FluentValidation/FluentValidation#1926]
### FluentValidation version

10.3.4

### Summary

I've found that Empty() builit-in validator doesn't return validation error for a string variable that consists of a whitespace (" "). That behaviour is inconsistent with c# built-in String.IsNullOrEmpty(String) method which indicates whether the specified string is null or an empty string ("").

### Steps to Reproduce

Code to reproduce the issue using NUnit:

```C#
public class Developer 
{
        public bool IsBankrupt { get; set; }

        public string BankruptcyCaseNumber { get; set; }
}


public class DeveloperValidator : AbstractValidator<Developer>
{
    public DeveloperValidator()
    {
        RuleFor(x => x.BankruptcyCaseNumber)

            .NotEmpty().When(x => x.IsBankrupt == true, ApplyConditionTo.CurrentValidator)

            .Empty().When(x => x.IsBankrupt == false, ApplyConditionTo.CurrentValidator);
    }
}


[TestFixture]
public class DeveloperValidatorTests
{
        private DeveloperValidator validator;

        [SetUp]
        public void Setup()
        {
            validator = new DeveloperValidator();
        }

        [Test]
        public void ShouldHaveErrorWhenNotSetAsBankruptButBankruptcyCaseConsistsOfWhitespace()
        {
            var model = new Developer { IsBankrupt = false, BankruptcyCaseNumber = " " };
            var result = validator.TestValidate(model);
            result.ShouldHaveValidationErrorFor(developer => developer.BankruptcyCaseNumber);
        }

}
```

**Comment by JeremySkinner** [comment]
This isn't a bug - the behaviour is intentional.

Internally the validator uses `string.IsNullOrWhitespace`, not `string.IsNullOrEmpty`. See https://github.com/FluentValidation/FluentValidation/blob/044382a02a8ee209946ec16a62b8d44a4ad2b5e9/src/FluentValidation/Validators/EmptyValidator.cs#L33 

If you want to explicitly use `string.IsNullOrEmpty` then you can do so within a call to `Must`:

```
RuleFor(x => x.Foo).Must(value => string.IsNullOrEmpty(value))
```

**Comment by HuggerCoursera** [comment]
> This isn't a bug - the behaviour is intentional.
> 
> Internally the validator uses `string.IsNullOrWhiteSpace`, not `string.IsNullOrEmpty

And that's the problem: you are using different interpretation of what it means for a string to be empty than the one that c# is using. Hence the inconsistency that I mentioned.

**Comment by JeremySkinner** [comment]
We're intentionally using `string.IsNullOrWhitespace` because this is what the default .net `[Required]` validation attribute also uses. This isn't something we'll be changing.

**Comment by HuggerCoursera** [comment]
According to your explanation currently you mean Required() with string while the name of the validator says Empty () and there's already an established meaning in C# of what an empty string is (i.e. "").

I understand that there's an easy workaround. That's why I talk about an inconsistency rather than a bug.

Adding a flag or greater emphasis in the documentation would be helpful. Personally I've found the issue only while running tests although previously read description in the docs.

**Comment by JeremySkinner** [comment]
> According to your explanation currently you mean Required() with string while the name of the validator says Empty () and there's already an established meaning in C# of what an empty string is (i.e. "").

Historically `NotEmpty` was originally the equivalent of `[Required]`, and then `Empty` was contributed later as the inverse behaviour. (Ideally `NotEmpty()` should've been named `Required()` too, but it's not something I'm keen to change at this point)

> Adding a flag or greater emphasis in the documentation would be helpful

Yeah I think adding this to the docs would be the way to go. Would you be able to open a PR for this? If not I'll try and get to it when I have a bit of time

**Comment by HuggerCoursera** [comment]
> Yeah I think adding this to the docs would be the way to go. Would you be able to open a PR for this? If not I'll try and get to it when I have a bit of time

Ok, I'll open it. BTW thanks for taking your time to explain the issue.
