### ISSUE TITLE
Upgrading from 8.x to 10.x - Derive from AbstractValidator<T> - AddRule() is gone

### ISSUE THREAD

**Issue by rizi** [FluentValidation/FluentValidation#1927]
### FluentValidation version

10.4.0

### ASP.NET version

.NET 6.0

### Summary

Hi,
I've updated FluentValidation from 8.x to 10.4.0.

Now we have the issue that AddRule(...) is no longer available and I can't find an info about that change in the upgrade guides (https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html, https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html)

As the name AggregateValidator implies we want to execute n-Validator (or the rules of that validators) at once.

Therefore we pass a list of validators in the constructor and we want to execute all rules of the given validators --> we have hundreds of usages of the AggregateValidator<T>, is there a way to make it work with 10.4.0?

If so could you please tell me how to do it?

Br

```
public class AggregateValidator<T> : AbstractValidator<T>
{
    /// <summary>
    /// Initializes a new instance of this class.
    /// </summary>
    /// <param name="validators"></param>
    public AggregateValidator(params AbstractValidator<T>[] validators)
    {
        validators ??= Array.Empty<AbstractValidator<T>>();

        foreach (IValidationRule rule in validators.SelectMany(validationRules => validationRules))
        {
            AddRule(rule);
        }
    }
}
```

### Steps to Reproduce

**AddRule() no longer exists.**

```
public class AggregateValidator<T> : AbstractValidator<T>
{
    /// <summary>
    /// Initializes a new instance of this class.
    /// </summary>
    /// <param name="validators"></param>
    public AggregateValidator(params AbstractValidator<T>[] validators)
    {
        validators ??= Array.Empty<AbstractValidator<T>>();

        foreach (IValidationRule rule in validators.SelectMany(validationRules => validationRules))
        {
            AddRule(rule);
        }
    }
}
```

**EDIT:**
It seems it can be solved with Include(https://docs.fluentvalidation.net/en/latest/including-rules.html?highlight=include) --> is this correct?

br

**Comment by JeremySkinner** [comment]
Hi, yes, you should use `Include` to do this provided that the types being validated are compatible. I expect the removal of `AddRule` was missed from the upgrade guide.

**Comment by rizi** [comment]
> Hi, yes, you should use `Include` to do this provided that the types being validated are compatible. I expect the removal of `AddRule` was missed from the upgrade guide.

Thank you very much 👍
