### ISSUE TITLE
Add .NET 7 Minimal API Support Using Filters

### ISSUE THREAD

**Issue by RehanSaeed** [FluentValidation/FluentValidation#1929]
### Is your feature request related to a problem? Please describe.

.NET 7 adds support for filters in ASP.NET minimal API's. This means that we can write a filter to run fluent validation validators. @Elfocrash explains this well in [this video](https://www.youtube.com/watch?v=Kt9TiXrwIp4) (Note: In the example @Elfocrash wrote in his video, he didn't return a `ProblemDetail` response which I think should be the default).

### Describe the solution you'd like

A built in filter to run fluent validation for minimal API's and return a 400 Bad Request or 422 Unprocessable Entity with `ProblemDetail` response.

See @khalidabuhakmeh's issue https://github.com/dotnet/aspnetcore/issues/6145 for more info on why 422 is actually the more correct status code and should possibly be the default. Although there is the argument that 400 is what people expect when coming from ASP.NET.

### Describe alternatives you've considered

Everyone ships this code themselves.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn’t something we’ll be adding. 

The current recommended approach for minimal APIs is to resolve the validator instance inside your handler method and invoke the validator directly. 

If you or others think a filter-based approach would be beneficial then I’d suggest developing this as a separate community-supported package. I’d be very happy to provide any guidance and input that would be helpful to integrate, but this isn’t something I have capacity to maintain so will require someone else from the community to step up and take responsibility for this if it’s something that people want.
