### ISSUE TITLE
Add support for rooted JSON path for property names

### ISSUE THREAD

**Issue by rmacfadyen** [FluentValidation/FluentValidation#1930]
### Is your feature request related to a problem? Please describe.

ASP.NET MVC Core 6 issues the following sort of 400 BAD REQUEST response to badly formatted JSON:

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-0332360da37517a30a13675a0e3214a9-6e7b7c5ef44859f5-00",
  "errors": {
    "$.Number": [
      "The JSON value could not be converted to System.Int32. Path: $.Number | LineNumber: 2 | BytePositionInLine: 17."
    ]
  }
}
```
(this was in response to a JSON object who's number property was being passed as boolean, eg { number: false }).

The key thing to note is that the errors map appears to use a rooted JSON path to identify the field in question ("$."... the root of the JSON document).

FluentValidation.net on the other hand does not use a root JSON path:

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-4b1645afd1563efd905c6cd5fdbbc37e-c6453ab4e9031439-00",
  "errors": {
    "Number": [
      "'Number of requests' must be less than '100'."
    ]
  }
}
```

It sure would be nice if FluentValidation.net and ASP.NET MVC Core 6 were consistent with each other. 

### Describe the solution you'd like

A boolean flag on ValidatorConfiguration: UseRootedJSONPaths. Default to false so as to preserve backwards compatibility.

### Describe alternatives you've considered

None.

**Comment by JeremySkinner** [comment]
FluentValidation doesn't provide any kind of JSON serlialization. The JSON output you're seeing comes from ASP.NET - we just pass a collection of error messages to ASP.NET, which decides what format the validation output should be displayed in. We don't have any control of how this is actually serialized.  

The only thing I can suggest is if you called `OverridePropertyName` in your rule definition then this will probably pass through to ASP.NET. Eg: `RuleFor(x => x.Number).Whatever().OverridePropertyName("$.Number")`

**Comment by rmacfadyen** [comment]
Dang it. But solid answer. Thanks!
