### ISSUE TITLE
global setting and notempty as default like notnull

### ISSUE THREAD

**Issue by yeganehaym** [FluentValidation/FluentValidation#1931]
### Describe the solution you'd like

when i write a property with string or string? , notnull works properly
but notempty is not a default behaviour and i must write notempty for each string property
it would be good if  FV had a globalvlidation like this:
`FV.SetGlobalSetting<String>.NotEmpty()`

**Comment by JeremySkinner** [comment]
This isn't a feature of FluentValidation. The global handling of nullable/non-nullable types is something provided by ASP.NET and isn't something that we have control over.
