### ISSUE TITLE
IValidationRule.MessageBuilder lack of getter breaks existing code

### ISSUE THREAD

**Issue by virzak** [FluentValidation/FluentValidation#1934]
### FluentValidation version

11

### Summary

This won't work anymore. Any suggestion? https://github.com/FluentValidation/FluentValidation/issues/1353#issuecomment-604951897

### Steps to Reproduce

Just doesn't compile

**Comment by JeremySkinner** [comment]
You can now only have a single MessageBuilder  associated with a rule chain, so you'll need to remove calls to `originalMessageBuilder`:

```csharp
return ruleBuilder.Configure(rule => {
  rule.MessageBuilder = context => {
    
    // Either add a new custom placeholder...
    context.MessageFormatter.AppendArgument("Unit", unitSuffix);
    // ...or just append the suffix it to the PropertyValue placeholder
    context.MessageFormatter.AppendArgument("PropertyValue", context.PropertyValue.ToString() + unitSuffix);
    
    return context.GetDefaultMessage();
  };
});
```

I'll add a note on this this to the upgrade guide too.
