### ISSUE TITLE
ComparisonValue Not displayed

### ISSUE THREAD

**Issue by ltemimi** [FluentValidation/FluentValidation#1950]
### FluentValidation version

11.02

### ASP.NET version

Blazor server dot net 6

### Summary

The comparison value is not diplayed when using MinimumLength for string validation as below

 RuleFor(u => u.Password)
            .NotNull()
            .NotEmpty().WithMessage("{PropertyName} is required.")
            .MinimumLength(6)
            .WithMessage("{PropertyName} must not be less than {ComparisonValue} characters.");

The display is
        Password must not be less than { ComparisonValue} characters.

Thanks for the help

### Steps to Reproduce

1 - blazor server
2 - create validation for a string
3 - Check and observe the comparison valued is not displayed (see description for rules)

**Comment by JeremySkinner** [comment]
The `MinimumLength` validator doesn't have a `ComparisonValue` placeholder. Please review the documentation which shows which placeholders are supported: 

https://docs.fluentvalidation.net/en/latest/built-in-validators.html#minlength-validator

```
{PropertyName} – Name of the property being validated
{MinLength} – Minimum length
{TotalLength} – Number of characters entered
{PropertyValue} – Current value of the property
```
