### ISSUE TITLE
FluentValidation.AsyncValidatorInvokedSynchronouslyException: The validator can't be used with ASP.NET automatic validation as it contains asynchronous rules

### ISSUE THREAD

**Issue by xts-velkumars** [FluentValidation/FluentValidation#1956]
### FluentValidation version

11.0.3

### ASP.NET version

.NET 6

### Summary

@JeremySkinner I'm facing an issue after I updated FluentValidation 11.0.3

FluentValidation.AsyncValidatorInvokedSynchronouslyException: The validator "SaveUserCommandValidator" can't be used with ASP.NET automatic validation as it contains asynchronous rules.
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext) in /Users/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs:line 121

I'm getting an exception when I use MustAsync. Below is my code

 
The one rule with out MustAsync is working fine. 

### Steps to Reproduce

```
public class SaveUserCommandValidator : AbstractValidator<SaveUserCommand>
 {
    private readonly DatabaseContext context;

     public SaveUserCommandValidator(DatabaseContext context)
        {
            this.context = context;

            RuleFor(cmd => cmd.MobileNumber)
                .NotEmpty()
                .WithMessage("Mobile Number is required")
                .Must(IsValidMobileNumber).WithMessage("Mobile Number must be only numeric")
                .Length(10, 10).WithMessage("Mobile Number should have 10 characters");

            RuleFor(x => x).MustAsync(async (x, cancellationToken) => await IsMobileNumberAlreadyRegistered(x, cancellationToken))
                .OverridePropertyName("MobileNumber")
                .WithMessage("Mobile number already registered");
}

private async Task<bool> IsMobileNumberAlreadyRegistered(SaveUserCommand command, CancellationToken cancellationToken)
        {
            if (command.Id > 0)
                return true;

            var result = await context.User
                .AsNoTracking()
                .FirstOrDefaultAsync(i => i.MobileNumber.Equals(command.MobileNumber), cancellationToken);
            return result == null;
        }
 }
```

**Below is the code to Validate my Object**

```
 public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            var context = new ValidationContext<TRequest>(request);

            var results = new List<ValidationResult>();
            foreach (var validator in validators)
            {
                results.Add(await validator.ValidateAsync(context, cancellationToken));
            }

            var failures = results.SelectMany(r => r.Errors)
             .Where(f => f != null)
             .ToList();

            if (!failures.Any())
                return await next();

            var result = new TResponse();
            result.SetFailures(failures.Select(f => f.ErrorMessage).ToList());
            return result;
        }
```

**Comment by JeremySkinner** [comment]
Hi @xts-velkumars that exception is thrown when you use ASP.NET auto-validation as ASP.NET's auto-validation process is not asynchronous and can't run asynchronous rules or conditions. 

In previous versions of FluentValidation, when asp.net auto-validation invoked a validator containing async rules the validator would be silently run synchronously which would lead to deadlocks. In 11.0 we switched this over to throw an exception to make it very explicit that this is an unsupported scenario (see upgrade guide https://docs.fluentvalidation.net/en/latest/upgrading-to-11.html#sync-over-async-now-throws-an-exception) 

The validation code in your handler isn't triggering the exception - only auto-validation triggers the exception (check the stack trace). Auto validation is invoked by asp.net prior to passing the model object into a controller action, so you'll need to search your application to find where this is happening. Presumably you don't actually want auto-validation enabled if you're explicitly validating inside your handler.

**Comment by xts-velkumars** [comment]
@JeremySkinner,  Thank you so much. Below configuration works for me.

```
.AddFluentValidation(fv =>
            {
                fv.AutomaticValidationEnabled = false;             
            });
```

**Comment by xts-velkumars** [comment]
One more clarification. 

Previous version I'm getting error message in nice format as below 

**Version 10.3.6**

![image](https://user-images.githubusercontent.com/13570225/174337299-0679a16b-ba18-45d1-87fc-cffdf65706b6.png)

**Version - 11.0.3**

![image](https://user-images.githubusercontent.com/13570225/174337749-81e32131-1c8f-4fc8-97e1-6f39102784b8.png)


Do I need to add any settings to get error message in JSON format ?

**Comment by JeremySkinner** [comment]
FluentValidation doesn't have any control over how the response is sent/formatted - this is entirely provided by ASP.NET.

When you use Auto Validation, ASP.NET will convert FluentValidation's response to JSON automatically (your first screenshot). This is handled by ASP.NET's `ModelStateInvalidFilter` (presumably you're using `ApiController`? If so, [ASP.NET wires this up automatically](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0#automatic-http-400-responses)). 

When you don't use auto validation (ie you manually invoke the validator inside your handler) then it's your responsibility to handle this. Typically you'd copy the validation results into ModelState and then return a `BadRequest` result.

You were seeing the automatic JSON response before because you were relying on ASP.NET's auto-validation (essentially bypassing your handler). Now you've turned off auto-validation, you need to handle populating the ModelState collection and returning the correct response.

**Comment by xts-velkumars** [comment]
@JeremySkinner, Thank you
