### ISSUE TITLE
Feature Request: Annotate regex "expression" parameter with [StringSyntax(StringSyntaxAttribute.Regex)]

### ISSUE THREAD

**Issue by JohnyL** [FluentValidation/FluentValidation#1957]
### Is your feature request related to a problem? Please describe.

In .NET 7 [you can annotate](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#stringsyntaxattribute-regex) regular expression pattern parameter with `[StringSyntax(StringSyntaxAttribute.Regex)]` so that this pattern will be colorized and validated in Visual Studio (also IntelliSense will work). Could you add this attribute to `expression` parameter in `RegularExpressionValidator`?

### Describe the solution you'd like

Colorization, validation and IntelliSense for regular expression pattern string.

**Comment by JeremySkinner** [comment]
Seems like a good idea. We don't provide a specific build for .NET 7 yet, but once we do then yes we can add this. We'll probably add a .net7-specific build once .net 7 reaches Release Candidate stage.

**Comment by JohnyL** [comment]
@JeremySkinner Thanks! 😎
