### ISSUE TITLE
Request for feedback: The future of our ASP.NET Integration package

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1959]
I am considering the future of our `FluentValidation.AspNetCore` package:

# Background

We ship the `FluentValidation.AspNetCore` alongside our core `FluentValidation` package in order to provide integration with ASP.NET Core in 2 main ways:

- Integration with ASP.NET Core's auto-validation pipeline
  - When ASP.NET attempts to validate an object during model-binding, [FluentValidation can be invoked to handle this process](https://docs.fluentvalidation.net/en/latest/aspnet.html). 
- Integration with ASP.NET Core's client-side validation process
  - We provide adaptors that convert a [limited subset of FluentValidation's rules](https://docs.fluentvalidation.net/en/latest/aspnet.html#clientside-validation) into html attributes that can be used with jQuery Validation. 

# The problem

The `FluentValidation.AspNetCore` package is problematic to maintain for several reasons:

**Async Validation**:
ASP.NET's validation pipeline is synchronous*, meaning none of FluentValidation's support async rules can be utilised and Microsoft do not seem keen on providing asynchronous validation apis in ASP.NET (although [they are reconsidering this for .net 8](https://github.com/dotnet/aspnetcore/issues/31905)). As asynchronous code becomes more and more prevalent, the sync-only approach taken by asp.net core is particularly limiting and feels extremely antiquated. 

* Note that this only applies to MVC/Web APIs. Blazor's validation process is asynchronous, and Minimal APIs don't provide any kind of auto-validation (you invoke the validator manually, and act upon its results, which is actually my preferred approach). 

**Maintenance burden**
The ASP.NET validation pipeline has contained breaking changes for almost every release of ASP.NET Core (.net 7 is the first where nothing has broken during the upgrade). Some of these have required a significant time investment to track down and troubleshoot, especially as the ASP.NET validation pipeline is quite complex internally. This isn't an enjoyable experience for me and I'm not keen on continuing to have to do this with every release.

**Support burden**
The ASP.NET validation pipeline is complex and often hard to understand, largely because of the 'magic' nature of auto-validation and the vast majority of support requests I receive on this issue tracker are related to this. Even though there usually isn't an issue with FluentValidation itself it's hard for developers to understand when an issue lies with ASP.NET (most of the time), vs when it lies with FluentValidation (rarely). 

The support burden for FluentValidation.AspNetCore is extremely frustrating for me to the point where I wish I'd never built and supported this myself, and instead focused only on the core `FluentValidation` library and allowed the community to maintain the ASP.NET integration separately. ([Like we do for Blazor](https://docs.fluentvalidation.net/en/latest/blazor.html)) 

The majority of issues I've had in my personal life related to "OSS-burnout" is largely due to FluentValidation.AspNetCore.

# The future

Essentially: I don't really want to support `FluentValidation.AspNetCore` anymore and I'd like the community's input on what to do with it going forward (and to clarify; I do still want to support the main `FluentValidation` library!)

**Option 1: Deprecate the package and provide guidance for alternative approaches**
- Encourage users to manually invoke validators rather than rely on auto-validation
- We might have to provide some better helpers for copying validation results into `ModelState` 
- `FluentValidation.AspNetCore` would be deprecated and receive no further updates or support from me
  - Users could continue to use it if they wanted, unsupported (until some future ASP.NET update breaks it)

**Option 2: The community takes over maintaining it**
If anyone in the community is willing to put the time investment into maintaining and supporting FluentValidation.AspNetCore then this would be an alternative option:
- The code for FluentValidation.AspNetCore is moved into a new repository, maintained by the community and publishes it as a new package
  - We wouldn't transfer ownership of the existing package due to chain-of-trust issues. Instead the existing package would be deprecated and the new community package would be recommended a a replacement 
- In our own documentation we would encourage users to manually invoke validators rather than rely on auto-validation, but also link to the community package as an alternative

**Option 3: Maybe some kind of commercial approach**
- Maybe move to a paid license, or try and find corporate sponsors willing to pay for ongoing maintenance for the library. 
- This doesn't seem realistic

What do you all think?

**Comment by smartprogrammer93** [comment]
I suggest going with both option 1 and 2. I dont see why the community cant pick up the maintainance, as well as having and explaining in the docs the manual validation approuch and introducing the helper that maps to ModelState. Appreciate your efforts on this lib. It is amazing

**Comment by codymullins** [comment]
I vote for option 2. This allows the community to maintain it, even if that means just maintenance to keep it up to date with changes. 

Focusing on building a better FluentValidation library will make room for others to innovate on integration in to .NET Core. Thanks for all the work you've put in to it so far.

**Comment by collinstevens** [comment]
Going by how you ordered your list, I would assume the "Async Validation" is your biggest issue.

I heavily use the auto-magic validation in all of my ASP.NET Core Web API projects, but I wouldn't mind having to DI the validators into my endpoints if this meant a reduce maintenance burden on the library. To be honest, I wasn't aware those async calls weren't running asynchronously, looks like I have some things to go look at...

With respect to "Maintenance burden" and "Support burden", the breaking changes with ASP.NET releases would seemingly have to be overtaken by the community. I'm not familiar enough with how much compensation commercial sponsors provide or if it is an even a feasible option.

I would go with option 2.

**Comment by JeremySkinner** [comment]
@collinstevens 

>  I wasn't aware those async calls weren't running asynchronously

Yeah that’s something that I’ve frequently encountered when talking with users of the library, that many people aren’t aware of this problem, which is why with 11.x we now throw an exception if you try and use auto-validation to invoke a validator that contains async rules (rather than silently force them to run synchronously) so it’s now very explicit that something is wrong

**Comment by collinstevens** [comment]
> we now throw an exception if you try and use auto-validation to invoke a validator that contains async rules

I was going to suggest this, but I didn't want to add to your maintenance burden. This sounds like a great addition.

**Comment by darren-clark** [comment]
I mean, 2 would be great, but I don't know that anyone really feels passionately about it enough to take over the problems you've outlined. Personally I love the auto-validation, but I figured it was a pretty trivial "nice to have" integration. I'm certainly not willing to make it my life's work(or really any work) to keep it running. There are more important things to spend significant effort on than avoiding manually invoking model validation.

Only other approach I can think of would be rewrite to NOT use the AspNetCore validation pipeline, but rely on more stable parts of the request pipeline. But again, unless it's trivial, it's not something _I_ would spend my time, so can hardly ask someone else to.

**Comment by nhwilly** [comment]
1. I’m just getting into this package and I really like it. Thank you for creating and maintaining it. 

2. I am using the pipeline, but will promptly be taking your preferred approach. The magical bits have thrown me a couple of times already, but I thought that’s what everyone was doing.  I like async. 

3. Tend to your personal health. Nothing matters if that fails. 

Thanks and good luck with whatever you decide.

**Comment by rude-seagull** [comment]
First, I'd like to say thank you for your hard work, Fluent Validation is awesome.
As @nhwilly said, your personal health and pleasure to work on OSS must prevail.
Option 2 would rely on a community capable of tackling update based on your work and Microsoft breaking changes, seems like a long shot to me. The ecosystem around what Fluent Validation has to offer and what it has not would also be less clear. 
That's why I would go with option 1, it's not like you cannot do the things you were doing before, you just have to adopt a different way of doing them. Seems like a very small concession to me.

Take care.

**Comment by langebo** [comment]
Hey Jeremy,

in my opinion you should simply stop supporting the  AspNetCore integration library as you mention in option 1. My understanding of OSS spirit in a situation like this is: "if there's enough need, enthusiasm and/or pain" someone will take over. If there isn't, then it's ok to be deprecated entirely imho. Focus on whats fun and/or rewarding and get rid of things burning you out eventually. I love using FluentValidation and losing it would leave a hole in the dotnet OSS ecosystem. And maybe someone will come up with a totally different approach of plugging async validation into AspNetCore.. Who knows. 

Take care

**Comment by nhwilly** [comment]
@JeremySkinner As promised, I am getting away from the synchronous validation in Asp.Net Core and moving toward the suggestion you made in the original post.  

To make sure I'm clear on this, your preference is to manually invoke the validation in the controller?  

This is instead of a custom `IAsyncActionFilter` implementation (or something) I write myself (haven't even tried, not sure it's possible, etc.)

If this has already been done, please let me know.   There are so many options in the docs, sometimes I'm not sure where to start and I want to be in line with your future direction.

TIA

**Comment by JeremySkinner** [comment]
Thanks everyone for your input so far, I really appreciate it and it's really encouraging.

I took some time to think think about this further over the weekend and based on the feedback received so far have decided on the following for now:

- I will immediately deprecate the features in FluentValidation.AspNetCore that are most problematic (mainly those related to [implicit child validation](https://github.com/FluentValidation/FluentValidation/issues/1960)) 
  - I will aim to put together some instructions for how to bring this functionality into your own codebase for anyone who relies on this functionality. 
- I'll also deprecate several features which are duplicated elsewhere (see #1963, #1961, #1965)
- I have [reworked the ASP.NET documentation](https://docs.fluentvalidation.net/en/latest/aspnet.html) to make it clear that manual validation is the preferred approach, and discourage the use of auto-validation
- The `AddFluentValidation()` method will be replaced with 2 methods: `AddFluentValidationAutoValidation()` and `AddFluentValidationClientsideAdapters()` to make it easier for users to enable the clientside validation integration without enabling auto validation (#1965)
  - I might move the clientside integration to a separate package. Not sure yet. 
- I will keep an eye on [this issue](https://github.com/dotnet/aspnetcore/issues/31905) to see whether Microsoft reconsider enabling asynchronous validation for .net 8. If they do, then I may keep auto-validation around (albeit in a more limited form).

That's my current plan, although I may change things depending on how the first set of deprecations are received by the wider community. I'll aim to post any further updates here too. 

I've relased 11.1.0 with these changes. 

[Please check out the updated docs](https://docs.fluentvalidation.net/en/latest/aspnet.html) and let me know if there's anything that doesn't make sense that could do with clarifying/expanding.

**Comment by GTmAster** [comment]
Tough, but respectable decision. Looking forward toinstructions, how get FluentValidation.AspNetCore in own codebase - our project heavily rely on that.

**Comment by JeremySkinner** [comment]
I've now split out the source code of `FluentValidation.AspNetCore` from the main FluentValidation repository and moved it into its own repository at https://github.com/FluentValidation/FluentValidation.AspNetCore

**Comment by jvandertil** [comment]
As an alternative idea, you could consider slimming down the integration you provide out of the box in the AspNetCore package.

I am not quite sure how much the client side adapters are part of the validation pipeline that make it a pain to maintain the package, but that would be one thing that I would appreciate to have as integration.

The automatic validation is nice to have, but if it is a burden to maintain then by all means deprecate that part. Maybe add some docs that point people in the right direction if they want that? I am gonna look if I can implement an action filter or something to do the validation as I really like not having to think about validation in every method 😄 

I appreciate the change to throw an exception when Async validation happens in a the sync pipeline, never knew that was happening under the covers.

Just my 2 cents!

**Comment by jvandertil** [comment]
As an extra, an `IAsyncActionFilter` I threw together in a couple minutes to see how it would look like:
```cs
public class ValidationActionFilter : IAsyncActionFilter
{
    private readonly IServiceProvider _serviceProvider;

    public ValidationActionFilter(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        var arguments = context.ActionArguments;

        if (arguments.Count > 0)
        {
            foreach (var argument in arguments.Values)
            {
                if (argument is null)
                {
                    continue;
                }

                // We probably are not interested in validating these kind of arguments.
                var argumentType = argument.GetType();
                if (argumentType.IsPrimitive
                    || argumentType == typeof(string))
                {
                    continue;
                }

                var validatorType = typeof(IValidator<>).MakeGenericType(argumentType);
                var validator = (IValidator?)_serviceProvider.GetService(validatorType);

                if (validator != null)
                {
                    // The ValidationContext<object> does not look nice, but it works.
                    var result = await validator.ValidateAsync(new ValidationContext<object>(argument));

                    result.AddToModelState(context.ModelState, prefix: null);
                }
            }
        }

        await next();
    }
}
```

Just register it in DI and you should be good to go:
```cs
services.AddTransient<ValidationActionFilter>();

services .AddMvcCore(opts =>
{
    opts.Filters.AddService<ValidationActionFilter>();
});
```

Probably not the most efficient you could get, but captures the general idea.

**Comment by dlebee** [comment]
@jvandertil I came to a similar conclusion :D

```csharp
public class AsyncAutoValidation : IAsyncActionFilter
    {
        private readonly IServiceProvider serviceProvider;
        private readonly ProblemDetailsFactory problemDetailsFactory;

        public AsyncAutoValidation(IServiceProvider serviceProvider, ProblemDetailsFactory problemDetailsFactory)
        {
            this.serviceProvider = serviceProvider;
            this.problemDetailsFactory = problemDetailsFactory;
        }

        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            foreach(var parameter in context.ActionDescriptor.Parameters)
            {
                if (parameter.BindingInfo.BindingSource == BindingSource.Body || (parameter.BindingInfo.BindingSource == BindingSource.Query && parameter.ParameterType.IsClass))
                {
                    var validator = serviceProvider.GetService(typeof(IValidator<>).MakeGenericType(parameter.ParameterType)) as IValidator;
                    if (validator != null)
                    {
                        var subject = context.ActionArguments[parameter.Name];
                        var result = await validator.ValidateAsync(new ValidationContext<object>(subject), context.HttpContext.RequestAborted);
                        if (!result.IsValid)
                        {
                            result.AddToModelState(context.ModelState, null);
                            var validationProblem = problemDetailsFactory.CreateValidationProblemDetails(context.HttpContext,
                                context.ModelState,
                                statusCode: null,
                                title: null,
                                type: null,
                                detail: null,
                                instance: null);

                            context.Result = new BadRequestObjectResult(validationProblem);
                            return;
                        }
                    }
                }
            }

            await next();
        }
    }
```

I also added support for FromQuery objects to be validated.

iff you call await without a result does it validate the same?

**Comment by sebastienlabine** [comment]
I understand this might be a little of topic, but do you think it would be possible to also provide a way to inject a single IValidator instance that take a generic parameter for validation? Just like AutoMapper is doing?


```c#
private readonly IValidator _validator;

public MyClass(IValidator validator) {
       _validator = validator;
}

public async Task MyController(MyDTO dto) {

        var validationResult = await _validator.ValidateAsync<MyDTO>(dto);
}


```

**Comment by celluj34** [comment]
If the validation pipeline was async by default, would that have an impact on your decision to stop support? Or is it mainly the maintenance costs between major version upgrades?

**Comment by JeremySkinner** [comment]
> If the validation pipeline was async by default, would that have an impact on your decision to stop support? Or is it mainly the maintenance costs between major version upgrades?

It’s mainly the support and maintenance burden.

**Comment by icequark** [comment]
I personally love the automatic validation.  
I use the framework mainly to check if passed in objects are valid.  A valid object to me is something that satisfies all invariants and an object that is valid today is also valid tomorrow and was also valid yesterday.  The validity of the object is therefore not data dependant. I therefore never do any validation against existing data.  These check I perform somewhere else. (I however see the appeal)

Therefore I have never had the need to use async and to me automatic validation is much more valuable than async functionallity. I also like the depricated parameters `ImplicitlyValidateChildProperties` and `ImplicitlyValidateRootCollectionElements` and to me this is moving backwards.  A framework should be more powerful and easier to use with time, not the other way around.

I personally would gladly take part in a community effort to maintain this library.

**Comment by JeremySkinner** [comment]
@icequark 

> I also like the depricated parameters ImplicitlyValidateChildProperties and ImplicitlyValidateRootCollectionElements and to me this is moving backwards. A framework should be more powerful and easier to use with time, not the other way around.

Unfortunately the support and maintenance burden is too heavy for me to keep maintaining these features which is why they're now deprecated, but if you consider them valuable then this will require members of the community (whether that's you or others) to step up and take responsibility for maintaining and supporting this going forward.

If you are interested in taking this on then I'd suggest timing it to coincide with our next major release, but the process would essentially be:

- You fork the FluentValidation.AspNetCore repository
- We deprecate the existing FluentValidation.AspNetCore package
- You publish a new package based on your fork
- We update the documentation and old package to link to the replacement package
- We archive the current FluentValidation.AspNetCore repository 

...but for this to be successful it does require enough buy-in from the community to keep it going, and so far I believe you're the only person who's expressed an interest in maintaining this. I don't want to end up in a situation where we go through this process only for the fork to end up abandoned if there aren't enough people willing to maintain it together, as personally I believe it's too time consuming for just 1 person to do in their spare time.

**Comment by icequark** [comment]
@JeremySkinner 

This might be something I for sure might be interested in and I see on this thread that there are couple of other potential contributors, like @jvandertil and @dlebee. I will start by looking at the code, both for the ASP.NET Core package and also the base package before I commit to do this.

**Comment by JeremySkinner** [comment]
The main thing to be aware of with the code for the auto-validation stuff is that asp.net’s validation pipeline is designed for data annotations (which validate each property value before the property is set), while FluentValidation works by validating the whole object in one go after all properties have been set. 

To achieve this (and particularly to achieve enabling/disabling validating children implicitly) requires quite a lot of hacks and workarounds.

**Comment by Carl-Hugo** [comment]
I've put together a minimal API endpoint filter named `FluentValidation.AspNetCore.Http`, but I assume `FluentValidation` is a reserved prefix on NuGet.

Since you want to focus on only maintaining the main package in the future, do you plan on creating a `FluentValidation.Contrib` project or something similar, or do you recommend simply naming the FluentValidation-related packages differently, like `[something].FluentValidation.AspNetCore.Http`?

Thanks

---

Link to my initial work for those interested: https://github.com/Carl-Hugo/FluentValidation.AspNetCore.Http

**Comment by JeremySkinner** [comment]
hi @Carl-Hugo the usual convention is something like `<CompanyName>.FluentValidation.Whatever`. 

I'd be happy to link to your package from the documentation site once you've published it, [like we do for the Blazor packages](https://docs.fluentvalidation.net/en/latest/blazor.html).

**Comment by danielgreen** [comment]
> I personally love the automatic validation. I use the framework mainly to check if passed in objects are valid. A valid object to me is something that satisfies all invariants and an object that is valid today is also valid tomorrow and was also valid yesterday. The validity of the object is therefore not data dependant. I therefore never do any validation against existing data. These check I perform somewhere else. (I however see the appeal)
> 
> Therefore I have never had the need to use async and to me automatic validation is much more valuable than async functionallity. I also like the depricated parameters `ImplicitlyValidateChildProperties` and `ImplicitlyValidateRootCollectionElements` and to me this is moving backwards. A framework should be more powerful and easier to use with time, not the other way around.
> 
> I personally would gladly take part in a community effort to maintain this library.

I'd echo this - I use the AspNetCore package for the convenience of auto validation of Razor Page models (plus the clientside adapters) and have not been affected by the lack of async support or minimal API support yet.

I could look into replacing auto validation with a custom IPageFilter (or IAsyncPageFilter), similar to the example from @jvandertil, but it slightly feels like reinventing the wheel since nothing is broken (yet) 😃

**Comment by JeremySkinner** [comment]
@danielgreen thanks for the feedback. Beyond the async issue is the question of support/maintenance of the AspNetCore package, so unless someone wants to fork & support it, my current intention is to essentially leave it as-is for anyone who wants to use it, but otherwise it will be completely unsupported and won't receive any fixes or updates beyond the bare minimum to get it working with the upcoming FluentValidation 12.0 release. Following the 12.0 release I'll close down it's issue tracker and won't maintain it any further.

**Comment by mvdgun** [comment]
Based on the two code snippets in this thread, I have just created two NuGet packages that facilitate automatic validation for both MVC controllers and minimal APIs (endpoints) through filters. I would greatly appreciate any feedback you can provide on these packages!

https://github.com/SharpGrip/FluentValidation.AutoValidation
https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Mvc
https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Endpoints

It's currently still a beta release but I am already using it in personal projects with success so far. Will promote it to a stable release in about a week or so.

**Comment by JeremySkinner** [comment]
@mvdgun Give me a shout once you consider them stable and I'll add links to them from our doc page.

**Comment by mvdgun** [comment]
@JeremySkinner was looking for a way to contact you directly but couldn't find any. Hopefully it's okay that I ask you here; 

For the skipping of the data annotations validation in my library I would like to copy over some code from the FluentValidation.AspNetCore repository. Am I allowed to do so under the Apache 2.0 license?

**Comment by JeremySkinner** [comment]
@mvdgun yes, provided you abide by the terms of the license. Please review the license as it explains what you can/can't do: https://github.com/FluentValidation/FluentValidation/blob/main/License.txt

**Comment by mvdgun** [comment]
Hi @JeremySkinner, I just released v1.0.0 of my library (https://github.com/SharpGrip/FluentValidation.AutoValidation). 

**Packages:**
MVC asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Mvc
Minimal APIs (endpoints) asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Endpoints

**Comment by Carl-Hugo** [comment]
> Hi @JeremySkinner, I just released v1.0.0 of my library (https://github.com/SharpGrip/FluentValidation.AutoValidation).
> 
> **Packages:** MVC asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Mvc Minimal APIs (endpoints) asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Endpoints

Hey @mvdgun, I received a notification about this conversation this morning and was curious: have you tried **FluentValidation.AspNetCore.Http** ([NuGet](https://www.nuget.org/packages/ForEvolve.FluentValidation.AspNetCore.Http), [GitHub](https://github.com/Carl-Hugo/FluentValidation.AspNetCore.Http)) before packaging your own Minimal API filter? If so, what was missing or wrong?

**Comment by mvdgun** [comment]
Hi @Carl-Hugo, no, I haven't tried your library. A while ago, I developed a project that we use internally to automatically validate minimal APIs, based on some code I found in the FluentValidation documentation. I wasn't aware of any other library that did this. So, when I started creating a package for MVC, I decided to release our internal minimal API validation logic as a package as well. As for your question about whether something is wrong, I have no idea :). Your library looks more advanced and configurable, though.

**Comment by Carl-Hugo** [comment]
> Hi @Carl-Hugo, no, I haven't tried your library. A while ago, I developed a project that we use internally to automatically validate minimal APIs, based on some code I found in the FluentValidation documentation. I wasn't aware of any other library that did this. So, when I started creating a package for MVC, I also decided to release our internal minimal API validation logic as a package. As for your question about whether something is wrong, I have no idea :). Your library looks more advanced and configurable, though.

Ok, thanks for this quick response; it makes sense. I implemented the library in January 2023 but forgot to talk about it (here) until recently... Anyway, I was just curious to know if there was something wrong or missing to fix it before hitting the limitation or whatnot myself (or someone else).

**Comment by JeremySkinner** [comment]
> Hi @JeremySkinner, I just released v1.0.0 of my library (https://github.com/SharpGrip/FluentValidation.AutoValidation).
> 
> **Packages:** MVC asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Mvc Minimal APIs (endpoints) asynchronous automatic validation: https://www.nuget.org/packages/SharpGrip.FluentValidation.AutoValidation.Endpoints

Thanks! I've added links to the asp.net page in our docs

**Comment by timpage** [comment]
Hi @JeremySkinner, having read through this thread can I just ask where your thoughts are currently on the client-side validation part?  Your earlier messages gave the impression that the client-side support is not the part that has been a significant burden, and that you were considering maintaining it as a separate package going forward, without the auto validation?  I assume that was why AddFluentValidationClientsideAdapters was split out as a separate method? Is it still a possibility that you will split it out and maintain that part, or definitely no longer the case? I've started using FluentValidation on a Razor Pages project recently, but for me the client-side part is a key feature, and the only part of the FluentValidation.AspNetCore package I'm using, so am wanting to know whether it's sensible to continue using it or I need to find something else?

Completely understand your reasons for dropping this, and am glad you've had the courage to make the choice to put your wellbeing first. So I'm not trying to push for anything, just seeking clarity on something which is not completely clear from the conversation here.  Thanks.

**Comment by JeremySkinner** [comment]
hi @timpage I don’t personally have any interest in continuing to support or maintain it, but the package is still available and is still available to use. The method was split out to allow the community to fork the clientside part more easily if someone is keen to take on maintenance of it.

**Comment by timpage** [comment]
> hi @timpage I don’t personally have any interest in continuing to support or maintain it, but the package is still available and is still available to use. The method was split out to allow the community to fork the clientside part more easily if someone is keen to take on maintenance of it.

Okay, thanks for the clarification.
