### ISSUE TITLE
SetValidator error while compiling

### ISSUE THREAD

**Issue by Ramasagar** [FluentValidation/FluentValidation#1962]
### FluentValidation version

11.3.0

### Summary

Compile error while adding Upgrading fluent validation from 7.2.0 to 11.3.0

'type' does not contain a definition for 'name' and no accessible extension method 'name' accepting a first argument of type 'type' could be found (are you missing a using directive or an assembly reference)

### Steps to Reproduce

Step 1:Create a Validation Rule as below and compile will throw a error at Setvalidator

`RuleFor(x => x.DealerRoles)
.NotEmpty()
.Must(dealerRole =>
{
var dealerIds = dealerRole.Select(x => x.DealerId).ToList();
var duplicateItems = dealerIds.GroupBy(x => x).Where(x => x.Count() > 1).Select(x => x.Key);
return !duplicateItems.Any();
})
.WithMessage("Cannot contain duplicate Dealer Ids.")
.SetValidator(new DealerRoleValidator())`

internal class DealerRoleValidator : AbstractValidator<DealerRoleRequest>
{
public DealerRoleValidator()
{
RuleFor(x => x.DealerId)
.NotEmpty(); RuleFor(x => x.RoleId)
.NotEmpty();
}
}

Step 2: Create a Nested Validation Rule and compile will throw a error at ParentContext

`RuleFor(x => x.Signature)
.NotNull()
.SetValidator(new PaperworkSignatureRequestValidator())
.DependentRules(() =>
{
RuleFor(x => x.Signature.SignatureDate)
.Cascade(CascadeMode.StopOnFirstFailure)
.Must(x => x != DateTime.MinValue)
.When(x => x.Signature.SignatureDate.HasValue)
.WithMessage(ValidationMessageResource.SignatureDateValidationMessage)
.LessThanOrEqualTo(DateTime.Now.AddYears(50))
.When(x => x.Signature.SignatureDate.HasValue)
.WithMessage(string.Format(ValidationMessageResource.SignatureDateMaxDateValidationMessage, DateTime.Now.AddYears(50).ToString("MM/dd/yyyy")))
.CustomAsync(async (signatureDate, context, token) =>
{
var request = (PaperworkAchOnlyRequest)context.ParentContext.InstanceToValidate;
var (isValid, errorMessage) = await paperworkDataValidator.IsValidSignatureDate(signatureDate, request.LoanApplicationId, "ACH");
if (!isValid)
{
context.AddFailure(errorMessage ?? ValidationMessageResource.SignatureDateValidationMessage);
}
});`

**Comment by JeremySkinner** [comment]
You have not provided enough information to reproduce a problem so I cannot help you. 

Either provide a runnable unit test or a small, minimal sample project that reproduced the issue.
