### ISSUE TITLE
AddToModelState Error after updating to 11.0.3

### ISSUE THREAD

**Issue by Ramasagar** [FluentValidation/FluentValidation#1967]
### FluentValidation version

11.0.3

### ASP.NET version

Net4.7

### Summary

ValidationResult Doesnt contain defintion for AddToModelState 

### Steps to Reproduce

**Step 1**: With FluentValidation, lets define a class that inherits from AbstractValidator which contains the rules for a particular class.
```
`public class PaperworkSubmissionRequestValidatorV3 : AbstractValidator<PaperworkSubmissionRequest>
{
public PaperworkSubmissionRequestValidatorV3(IPaperworkDataValidator paperworkDataValidator, long userId)
{
// Include rules from base validator.
RuleFor(x => x)
.NotNull()
.SetValidator(new PaperworkSubmissionRequestValidator(paperworkDataValidator))
.DependentRules(() =>
{
// Validate promotion after everything else is done
RuleFor(x => x.LoanParameters)
.MustAsync(async (x, loanparams, token) =>
{
return await paperworkDataValidator.IsPromotionValid(userId, x.LoanApplicationId, new PromotionInfo
{
LoanType = loanparams.CreditType,
AmountFinanced = loanparams.AmountFinanced,
StateCode = loanparams.ContractState,
PaymentFactor = loanparams.PaymentFactor,
AnnualPercentageRate = loanparams.AnnualPercentageRate,
PrimaryPromotionId = loanparams.PrimaryPromotionId,
SecondaryPromotionId = loanparams.SecondaryPromotionId,
ClosedEndPaymentRateId = loanparams.ClosedEndPaymentRateId,
RepaymentTerms = loanparams.RepaymentTerms,
});
})
.WithMessage(ValidationMessageResource.InvalidPromotionValidationMessage);
});



When(x => x.Signature != null && x.Signature.SignatureTypes.Contains(SignatureTypeEnum.Electronic), () =>
{
RuleFor(x => x.Signature.DocusignRedirectUrl)
.MustAsync(async (request, item, token) => await paperworkDataValidator.IsValidDocusignRedirectUrl(item, userId))
.WithMessage("Invalid DocuSign redirect URL");
});



When(x => x.DocumentSelection != null, () =>
{
RuleFor(x => x.DocumentSelection.DocumentTypes)
.Null();
});
}
}
}` 

```
**Step 2** :Now create a Async Task to validate 

```
public async Task<IHttpActionResult> Submit(object request)
{
var submission = (PaperworkSubmissionRequest)request;

// Since the request comes in as an object, it's not being validated by FluentValidation. Manually call validator here.
var validationResult = await new PaperworkSubmissionRequestValidatorV3(_paperworkDataValidator, this.GetAuthorizedUserId()).ValidateAsync(submission);
if (!validationResult.IsValid)
{
validationResult.AddToModelState(ModelState, nameof(request));
return BadRequest(ModelState);
}
```

**Comment by JeremySkinner** [comment]
It's an extension method that was part of the FluentValidation.WebApi project.  You can copy the source code for it into your project from here: https://github.com/FluentValidation/FluentValidation-LegacyWeb/blob/master/src/FluentValidation.WebApi/ValidationResultExtension.cs

**Comment by Ramasagar** [comment]
Iam using fluent validation 11.0.3.so how can we get rid of it without using the source code and package?

**Comment by JeremySkinner** [comment]
@Ramasagar you need to copy the method definition *into your own project*, then you can use it with 11.0.3:

```csharp

namespace YourProject {
    using System.Collections.Generic;
    using System.Globalization;
    using FluentValidation.Results;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.ValueProviders;

    public static class ValidationResultExtension {

		public static void AddToModelState(this ValidationResult result, ModelStateDictionary modelState, string prefix) {
			if (!result.IsValid) {
				foreach (var error in result.Errors) {
					string key = string.IsNullOrEmpty(prefix)
						? error.PropertyName
						: string.IsNullOrEmpty(error.PropertyName)
							? prefix
							: prefix + "." + error.PropertyName;

					if (modelState.ContainsKey(key)) {
						modelState[key].Errors.Add(error.ErrorMessage);
					}
					else {
						modelState.AddModelError(key, error.ErrorMessage);
						//To work around an issue with MVC: SetModelValue must be called if AddModelError is called.
						modelState.SetModelValue(key, new ValueProviderResult(error.AttemptedValue ?? "", (error.AttemptedValue ?? "").ToString(), CultureInfo.CurrentCulture));
					}
				}
			}
		}
	}
}

**Comment by Ramasagar** [comment]
is it added in latest version 11.1.0? this error has been solved after updating to 11.1.0

**Comment by JeremySkinner** [comment]
No. 

We don’t support Web API 2 anymore, and that method requires typed from Web API in order to work. 

You need to copy the method into your web project as I’ve already explained.

**Comment by JeremySkinner** [comment]
Either delete it if you’re not using it, or copy the source code for it into your own project.

**Comment by Ramasagar** [comment]
Thanks for the reply .

now iam getting error at FluentValidationModelValidator.cs class as below

![image](https://user-images.githubusercontent.com/8260281/175961439-6da43df0-c600-420a-b93a-55484c61b4b6.png)


System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'.
  Source=FluentValidation.WebApi
  StackTrace:
   at FluentValidation.WebApi.FluentValidationModelValidator.ConvertValidationResultToModelValidationResults(ValidationResult result) in C:\Users\rsagar.AQUAFINANCE\Documents\Aqua\site-redesign\src\server.side\FluentValidation.WebApi\FluentValidationModelValidator.cs:line 82
   at FluentValidation.WebApi.FluentValidationModelValidator.Validate(ModelMetadata metadata, Object container) in C:\Users\rsagar.AQUAFINANCE\Documents\Aqua\site-redesign\src\server.side\FluentValidation.WebApi\FluentValidationModelValidator.cs:line 71
   at System.Web.Http.Validation.DefaultBodyModelValidator.ShallowValidate(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, BodyModelValidatorContext validationContext)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()
