### ISSUE TITLE
FluentValidationModelValidator.cs class error after using source code

### ISSUE THREAD

**Issue by Ramasagar** [FluentValidation/FluentValidation#1970]
### FluentValidation version

11.0.3

### Summary

```

System.MissingMethodException
HResult=0x80131513
Message=Method not found: 'System.Collections.Generic.IList1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'. Source=FluentValidation.WebApi StackTrace: at FluentValidation.WebApi.FluentValidationModelValidator.ConvertValidationResultToModelValidationResults(ValidationResult result) in C:\Users\rsagar.AQUAFINANCE\Documents\Aqua\site-redesign\src\server.side\FluentValidation.WebApi\FluentValidationModelValidator.cs:line 82 at FluentValidation.WebApi.FluentValidationModelValidator.Validate(ModelMetadata metadata, Object container) in C:\Users\rsagar.AQUAFINANCE\Documents\Aqua\site-redesign\src\server.side\FluentValidation.WebApi\FluentValidationModelValidator.cs:line 71 at System.Web.Http.Validation.DefaultBodyModelValidator.ShallowValidate(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable1 validators)
at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable1 validators) at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, BodyModelValidatorContext validationContext) at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, BodyModelValidatorContext validationContext, Object container, IEnumerable1 validators)
at System.Web.Http.ModelBinding.FormatterParameterBinding.d__18.MoveNext()
```

### Steps to Reproduce

Error after using source code https://github.com/FluentValidation

[FluentValidation-LegacyWeb](https://github.com/FluentValidation/FluentValidation-LegacyWeb) with Fluent validation 11.0,3

**Comment by JeremySkinner** [comment]
It looks like you’ve built the source code against an older version of FluentValidation - I expect you’ll need to update the package reference in FluentValidation.WebApi.csproj. Make sure you update it to 11. This is the like you’ll need to change: https://github.com/FluentValidation/FluentValidation-LegacyWeb/blob/48c7fb80b6999d3346d0233a52699b985b6e4a50/src/FluentValidation.WebApi/FluentValidation.WebApi.csproj#L38

I will point out again to you that this is *completely unsupported*, which means I can’t continue to help you with questions regarding FluentValidation.WebApi. You can continue to use the source code but you are on your own in doing so and it is not something I can continue to help you with.
