### ISSUE TITLE
Make validator retrieve data from parent validator, but not break AddFluentValidationRulesToSwagger by doing so

### ISSUE THREAD

**Issue by kada-v** [FluentValidation/FluentValidation#1980]
### FluentValidation version

11.1.0

### ASP.NET version

.NET 6

### Summary

I am using `services.AddFluentValidationRulesToSwagger();` in my Startup and I do use Custom Validators, which are created on-demand, so I can pass data to a validator via constructor.

I am using this approach from [here](https://stackoverflow.com/questions/61550275/fluentvalidation-using-a-parent-property-value-in-a-child-collection-rule) to pass data from parent validator to a child validator.
```c#
public class MyTypeValidator: AbstractValidator<MyType>
{
    public LoadValidator(PassedParameterType inputData)
    { 
       ... some more rules based on inputData
    }
}

public class ContainerClassValidator: AbstractValidator<ContainerClss>
{
    public ContainerClassValidator()
    {
        RuleForEach(containerData=> containerData.MyTypeObjects).SetValidator(containerData => new MyTypeValidator(containerData.passDataAsParameter));
    }
}
```
`AddFluentValidationRulesToSwagger` uses some kind of assembly scanning (i guess) to gather the necessary data for creating validation rules in swagger.
This leads to a exception when trying to instantiate the validator with constructor custom parameters (since the passed param data cannot be found by DI) and results in a NullpointerException.
``` 
GetValidator for type 'MyType' fails.
System.InvalidOperationException: Unable to resolve service for type 'PassedParameterType' while attempting to activate 'MyTypeValidator'.
```
and finally a Nullpointer when DI tries to resolve the lambad function.

I created a bug over there at [MicroElements.Swashbuckle.FluentValidation #117](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/issues/117)

*But my question is*: Is there any other way I can achieve child validation based on parent validator data, without doing it inline in the parent validator itself? I need to use a ChildValidator class, since the validation is quite complex and a lot of rules in general.

### Steps to Reproduce

Create a Validation Setup as above, where a child validator uses data from constructor parameters.

Add AddFluentValidationRulesToSwagger in your Startup

Startup progam leads to exception as described

**Comment by kada-vkw** [comment]
FluentValidation offers an option to scan the assembly for validators as well. But it offer an option to override the behavior by filtering the found dependencies as described [here](https://docs.fluentvalidation.net/en/latest/di.html?highlight=assembly#filtering-results)
Is there a similar option for AddValidationRulesToSwagger?

**Comment by JeremySkinner** [comment]
The approach you're using to pass data to the child validator is the correct way to to do this. 

However, you should ensure that the child validator is *not* registered with the DI container - you should exclude it when you register your other validators with the container as it can only ever be instantiated manually. This will fix the exception you're seeing as the swagger integration won't then attempt to instantiate it, but it also means your child validator can't be used with Swagger. This is a trade-off you'll have to accept. 

The only other approach you could take is to [store the extra data inside `RootContextData`](https://docs.fluentvalidation.net/en/latest/advanced.html#root-context-data), which you could then pull out from within the child validator. However this isn't really the intended use of RootContextData, and your original approach is the intended way of handling this.

I don't have any involvement with MicroElements.Swashbuckle.FluentValidation, so I'll let you continue the discussion on their issue tracker.
