### ISSUE TITLE
Generic validation without strong typing

### ISSUE THREAD

**Issue by Gabriel-DC** [FluentValidation/FluentValidation#1983]
### Describe the solution you'd like

Hii, Know the package proposal, and get strong typing validation, but I would like to know about the possibility of implementation
from a generic validator to variables of a given scope as a form of generalization.

![image](https://user-images.githubusercontent.com/57327840/182371541-9d85aa46-9b67-400b-b3ca-e5ea32b65719.png)

### Describe alternatives you've considered

I kind of improvised to use a generic validation.

![image](https://user-images.githubusercontent.com/57327840/182371992-7d7b067e-165b-47fb-980c-576efa844fa9.png)

In this example I created the 'GenericValidation' class that implements the 'AbstractValidation<object>'

GenericValidation Class: 

![image](https://user-images.githubusercontent.com/57327840/182371038-567a1dd5-8540-4daf-9e67-a54165c24b92.png)

### Additional Context

![image](https://user-images.githubusercontent.com/57327840/182372075-f255be67-a5d6-41ce-bae8-4339ed129290.png)

The codes used are available at the link: https://github.com/Gabriel-DC/CQRS-API/tree/main/CqrsApi.Domain/Context/Entities/Generic

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this is out of scope for this project.

**Comment by Gabriel-DC** [comment]
I figured that would be the case anyway, thanks 😊
