### ISSUE TITLE
Better ValidationContext creation support

### ISSUE THREAD

**Issue by aTuck** [FluentValidation/FluentValidation#1984]
### Is your feature request related to a problem? Please describe.

**I'm using 9.x**

Running into `System.InvalidOperationException : Collection was modified; enumeration operation may not execute.`

The root cause is from manually modifying the rootContextData as per [this documentation](https://docs.fluentvalidation.net/en/latest/advanced.html#root-context-data). 

This is a downstream effect after calling `validator.ValidateAsync(context)` inside of an extension method for `IValidator<T>`.

My validator is injected into my service. I believe this is getting thrown inside a child validator called from a `RuleForEach` in the parent validator.

If this is just misuse of the library please point me in the right direction. Thanks.

### Describe the solution you'd like

I believe this could be fixed if, similar to options, one could define a rootContext dictionary at context creation

`var context = ValidationContext<T>.CreateWithOptionsAndContext(instance, options => options.ThrowOnFailures(), context);`

Or something less verbose.

#### Extension Method
````csharp
public static async Task ValidateThrowAsync<T>(this IValidator<T> validator, T instance, (string?, string?)? rootContextData, CancellationToken cancellationToken = default)
{
    try
    {
        var context = ValidationContext<T>.CreateWithOptions(instance, options => options.ThrowOnFailures());
        context.RootContextData.Add(rootContextData?.Item1, rootContextData?.Item2);

        await validator.ValidateAsync(context, cancellationToken);
    }
    catch(ValidationException ex)
    {
        // ...
    }
}
````

#### Parent Validator
````csharp
public class ParentValidator : AbstractValidator<Child>
{
    public ParentValidator(IValidator<Child> childValidator)
    {
        // ...

        RuleForEach(x => x.ListProperty).SetInheritanceValidator(v =>
        {
            v.Add<Child>(childValidator);
        });
    }
}
````

**Comment by JeremySkinner** [comment]
This doesn’t sound like an issue with FluentValidation. 

The exception you’re seeing indicates that you have code somewhere attempting to modify a collection whilst you’re iterating over it. However you’ve not provided enough information for me to be able to help you further. 

If you still believe this is an issue with FluentValidation then please re-open this issue and provide all information necessary to reproduce the issue, specifically:
- a minimal, runnable reproduction of the problem (ideally as a unit test, or a minimal sample project) using the latest 11.x release 
- the full stack trace of any exceptions you receive 
- please ensure any samples
