### ISSUE TITLE
Issue with the FormsHelper suggestion in the Clientside section of the doc

### ISSUE THREAD

**Issue by mattkirschner** [FluentValidation/FluentValidation#1991]
### Is your feature request related to a problem? Please describe.

Since the .AspNetCore version of the FluentValidation package has essentially been deprecated (in favor of nothing really), I wanted to point out the the suggestion in the docs to use something like FormsHelper is somewhat paradoxical, since FormsHelper seems to rely on FluentValidation.AspNetCore for it's implementation... or at least the sample does.

### Describe the solution you'd like

It would be nice to have an example of clientside validation support that doesn't use FluentValidation.AspNetCore.

**Comment by JeremySkinner** [comment]
Client-side validation in FluentValidation.AspNetCore is not being deprecated.
