### ISSUE TITLE
Suggestion for Enhancement: Allow options and context together

### ISSUE THREAD

**Issue by SeanKilleen** [FluentValidation/FluentValidation#1995]
### Is your feature request related to a problem? Please describe.

* I have validator with a few `RuleSet`s that I am using for options
* I would also like to make use of `RootContextData` for some context for the validator.
* I don't appear to be able to use both a context and options within the `Validate` method. 
* I also don't appear to be able to set the options as part of the context.

### Describe the solution you'd like

Either of the following would be fine:

* An overload to `Validate` that allows both the context and options
* An addition of `ValidationStrategy` or `Options` to the `ValidationContext`, so that I could set them and use `Validate(context)`. 

### Describe alternatives you've considered

Working on simplifying this validator, for starters. :) Came across this in a client project.

But as of now, we'll likely have to use the constructor of the `AbstractValidator` to set some of the context, which is fine but prevents us from injecting the validator.

**Comment by JeremySkinner** [comment]
Hi @SeanKilleen this is already possible. The options-based overload of Validate is just a convenience wrapper for creating a context. 

```csharp
var person = new Person();

var context = ValidationContext<Person>.CreateWithOptions(person, options => {
	options.IncludeRuleSets("Foo");
	options.ThrowOnFailures();
});

context.RootContextData["Foo"] = "Bar";

var validator = new PersonValidator();
validator.Validate(context);
```

**Comment by SeanKilleen** [comment]
Ah thank you! I missed CreateWithOptions and was thinking about it backwards. Much appreciated!
