### ISSUE TITLE
How do I access object property in AbstractValidator?

### ISSUE THREAD

**Issue by warheat1990** [FluentValidation/FluentValidation#1996]
### Is your feature request related to a problem? Please describe.

Yes

### Describe the solution you'd like

Let's take this example

```
public class CustomerValidator: AbstractValidator<Customer> {
  public CustomerValidator() {
    RuleFor(x => x.Surname).NotEmpty();
    RuleFor(x => x.Address).Length(20, 250);
  }
}
```
How do I access the `Customer` object before the `RuleFor`? The reason for this is I have 

```
public class CustomerValidator: AbstractValidator<Customer> {
  public CustomerValidator(ApplicationContext context) {

    var resp = context.HiddenSecret.GetSomethingFromSomewhere(cust.Id); \\I need this cust object

    RuleFor(x => x.SecretId).MustExistInCollection(resp.Secrets);
    RuleFor(x => x.OtherId).MustExistInCollection(resp.Others);
    RuleFor(x => x.BirthDate).LessThanOrEqualTo(resp.SomeDate);
    RuleFor(x => x.Surname).NotEmpty();
    RuleFor(x => x.Address).Length(20, 250);
  }
}
```

Now of course I can achieve this by using the `Custom` or `Must` method but it's not as readable as the example above because I have lots and lots of property needed to be validated using the same method.

**Comment by JeremySkinner** [comment]
You won't be able to access it in the constructor like this as the instance is not available yet. You'll need to access it inside a custom validator instead. [See the documentation for writing custom validators](https://docs.fluentvalidation.net/en/latest/custom-validators.html#predicate-validator). 

It'll look something like this:

```csharp
public CustomerValidator(ApplicationContext context) 
{
  RuleFor(x => x.SecretId).Must((customer, secretId) => 
  { 
     var resp = context.HiddenSecret.GetSomethingFromSomewhere(customer.Id);
     return resp.Secrets.Contains(secretId); // or whatever check you need to do
  });
}
```

Please note for future reference that this issue tracker is for bugs in the FluentValidation library, [and is not for general support or questions, as mentioned in our contributing guideliens](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions).
