### ISSUE TITLE
ComparisonProperty (name) is empty with no way to set it.

### ISSUE THREAD

**Issue by LorneCash** [FluentValidation/FluentValidation#1997]
### FluentValidation version

11.2.0

### Summary

I'm not sure if this is a strange use case or if this if more of a feature request than a bug but here it goes:
I'm writing a .NET 6.0 Console application with this validator:

`public class DifferenceValidator : AbstractValidator<FilterOptions>`
`{`
`	public DifferenceValidator(FilterOptions existing)`
`	{`
`		RuleFor(x => x.PriceChangePercent)`
`			.GreaterThanOrEqualTo(existing.PriceChangePercent)`
`			.WithMessage("'{PropertyName}' [{PropertyValue}] must be greater than or equal to '{ComparisonProperty}'` `[{ComparisonValue}]");`
`	}`
`}`

The message I get back is this:

> 'Price Change Percent' [5] must be greater than or equal to '' [10]

I think the problem I'm having should be fairly obvious.  The value for `{ComparisonProperty}` is empty and I have no way to set it.  If there was a method like `WithName()` or `OverridePropertyName()` but for the ComparisonProperty that would be perfect.

A possible more ideal solution could be to use `[CallerArgumentExpression]` [https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information) to get that name and populate the value without the need for an override method.  However, even if it did get the ComparisonProperty name automatically, I'd still want the override method too for cases where I want to be more descriptive in a message than in my code.

Thank you for your consideration.

### Steps to Reproduce

`	[TestMethod]`
`	public async Task TestForBugReport()`
`	{`
`		var existing = new FilterOptions { PriceChangePercent = 10 };`
`		var current = new FilterOptions { PriceChangePercent = 5 };`

`		var differenceValidator = new Validators.DifferenceValidator(existing);`
`		var differenceValidatorResult = await differenceValidator.ValidateAsync(current);`

`		differenceValidatorResult.IsValid.Should().BeFalse();`
`		differenceValidatorResult.Errors[0].ErrorMessage.Should().NotBe("'Price Change Percent' [5] must be greater than or equal to '' [10]");`
`	}`

**Comment by JeremySkinner** [comment]
The behaviour is correct. `ComparisonProperty` is only set when performing a cross-property comparison.

A cross-property comparison is something like `RuleFor(x=>x.Foo).GreaterThan(x=>x.Bar)`where you are comparing two properties of the same input model. As you aren’t doing this, the ComparisonProperty placeholder isn’t available. 

I’d suggest just hard-coding the value - that is the simplest option. You could also use a custom MessageBuilder if you really wanted to populate the placeholder yourself but personally I wouldn’t bother.

**Comment by LorneCash** [comment]
I understand the intent now, and I can work around this by hard coding the message but it would make for cleaner code on my end if you would consider adding the `OverrideComparisonPropertyName()` method.  I can't imagine it being very difficult and it seems logical for it to be there since the value is populated.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't something we'll include. The `ComparisonProperty` palceholder is intended to be used when performing a cross-property comparison. It does not make sense to me to allow its use in situations where you're not performing a cross-property comparison.

That being said, if you really want this then you can implement it yourself using an extension method that wraps a MessageBuilder:

```csharp
public static class Extensions {
	public static IRuleBuilderOptions<T, TProperty> SetComparisonPropertyName<T, TProperty>(this IRuleBuilderOptions<T, TProperty> ruleBuilder, string name) {
		return ruleBuilder.Configure(rule => {
			rule.MessageBuilder = context => {
				context.MessageFormatter.AppendArgument("ComparisonProperty", name);
				return context.GetDefaultMessage();
			};
		});
	}
}
```

**Comment by JeremySkinner** [comment]
Or alternatively you could write overloads of `GreaterThan` etc that allow you to specify the comparison property name, rather than inferring it from an expression.

```csharp
public static IRuleBuilderOptions<T, TProperty> GreaterThanOrEqualTo<T, TProperty>(
	this IRuleBuilder<T, TProperty> ruleBuilder, TProperty valueToCompare, string comparisonPropertyName) where TProperty : IComparable<TProperty>, IComparable {
	return ruleBuilder.SetValidator(new GreaterThanOrEqualValidator<T,TProperty>(instance => valueToCompare, null, comparisonPropertyName));
}
```
