### ISSUE TITLE
Validation still continue after first failure on CascadeMode.Stop

### ISSUE THREAD

**Issue by warheat1990** [FluentValidation/FluentValidation#1998]
### FluentValidation version

11.2.0

### ASP.NET version

NET 6

### Summary

Validation still continue after first failure on CascadeMode.Stop

### Steps to Reproduce

I'm sorry if this is just my misunderstanding of how FluentValidation works, but I have this validation

```
            RuleFor(x => x).Custom((obj, ctx) =>
            {
                var cust = _context.Purchase.Find(obj.CustId);

                if (cust == null)
                    ctx.AddFailure($@"custId not found.");

                var custAddress = cust.Addresses.First(f => f.Id == obj.CustAddressId);

                //rest of code
```

However after this line `ctx.AddFailure($@"custId not found.");`, I can see that it's still continue validating the `custAddress `.

My CascadeMode is set to Stop in `Program.cs`

```
ValidatorOptions.Global.DefaultClassLevelCascadeMode = CascadeMode.Stop;
ValidatorOptions.Global.DefaultRuleLevelCascadeMode = CascadeMode.Stop;
ValidatorOptions.Global.DisplayNameResolver = (type, member, expression) => member?.Name;
```

I was under the impression that if it's set to Stop, it will stop validating on the first failure, I tried changing the `CascadeMode` to `StopOnFirstFailure` and it's still continue validating. Technically I can achieve what I want by doing `return` after every `AddFailure` but is it possible without using `return`?

**Comment by JeremySkinner** [comment]
`CascadeMode` only applies to calls to regular rules. 

It does not apply to completely custom logic inside a call to `Custom`. You should use `return`. 

Cascade usage is explained here: https://docs.fluentvalidation.net/en/latest/cascade.html
