### ISSUE TITLE
null String with .NotEmpty() on non-nullable field will return two errors

### ISSUE THREAD

**Issue by aaronzhongg** [FluentValidation/FluentValidation#2000]
### FluentValidation version

11.1.2

### ASP.NET version

.NET 6

### Summary

Non-nullable string with a `.NotEmpty` validation rule will return two errors. One for the `field is required` and another for the message of `.NotEmpty`

### Steps to Reproduce

I have a record like so (simplified):

```
public record Request(string Name);
```

With a validator Rule: 

```
RuleFor(r => r.Name)
  .NotEmpty()
  .WithMessage("Name cannot be empty.");
```

When I provide the values `""`, `"     "`, `null` I want it to return a single error message `"Name cannot be empty." `

However, when `null` is provided it returns two errors: 
```
{"The Name field is required.", "Name cannot be empty."}
```

I do not want to make the Name nullable for the sake of making the validation work as expected.

Thanks for your time

Edit:

### Workaround
To workaround this issue, I added a When clause to the Rule and accepted the difference in messages
```
RuleFor(r => r.Name)
  .NotEmpty()
  .WithMessage("Name cannot be empty.")
  .When(r => r.Name is not null);
```

**Comment by JeremySkinner** [comment]
The `field is required` message is not coming from FluentValidation. 

This message is coming from ASP.NET's model binding process directly, and is not something FluentValidation has control over. ASP.NET's model binding process will not allow a null value to be passed to a non-nullable property.
