### ISSUE TITLE
Revert IValidatorFactory deprecation

### ISSUE THREAD

**Issue by jvmlet** [FluentValidation/FluentValidation#2002]
### Is your feature request related to a problem? Please describe.

With previous  version (where `IValidatorFactory` was **not** deprecated), I was able to implement `CompositeValidatorFactory` which produces  `hierarchy-aware` `CompositeValidator ` validator :
````
 internal class CompositeValidator<T> : AbstractValidator<T> {
        private readonly IComponentContext _context;
        private readonly Lazy<bool> _initialized;

        public CompositeValidator(IComponentContext context) {
            _context = context;
            _initialized = new Lazy<bool>(() => {
                IEnumerable<IValidator> validators = _context
                    .Resolve<IEnumerable<IValidator>>()
                    .Where(v => v.CanValidateInstancesOfType(typeof(T)));  // include both A-type-validator  and BaseA-type-validator
                foreach (IValidator validator in validators) {
                    Include((IValidator<T>) validator);
                }

                return true;
            });
        }

        protected override bool PreValidate(ValidationContext<T> context, ValidationResult result) {
            // make sure we initialize composite once on-demand
            bool initializedValue = _initialized.Value;

            return true;
        }
    }
````
As you can see I'm using DI container (AutoFac  in this case) to discover  all validators and register them together with factory :
````
forEach( discoveredValidator){
 builder.RegisterType(validatorImplementationType)
                    .As<IValidator>()
                    .SingleInstance();
}
builder
                .RegisterType<CompositeValidatorFactory>()
                .As<IValidatorFactory>()
                .SingleInstance();
````

 but  deprecating `IValidatorFactory` will require me to implement this factory logic for each DI container (MS/AutoFac/SimpleInjector/etc) if I want to ship the library that seamlessly plugins into end-user choice of DI container implementation. 
Moreover,  projects that are not using DI container won't be able to benefit from this. 

### Describe the solution you'd like

Please bring `IValidatorFactory` back ;-)

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't something I'm keen on. `IValidatorFactory` is a legacy feature that was originally introduced to provide DI support in ASP.NET MVC before the `IServiceProvider` was introduced. Nowadays we recommend just using the ASP.NET service provider directly, and I'm keen to reduce maintenance overhead/burden.

I'll have a think about it, but my inclination is still to drop this with the next major release.

**Comment by JeremySkinner** [comment]
I’ve had time to think about this. We won’t be reverting the deprecation, but we will leave the code in place for an extra major version (so instead of being removed in 12.0 it will be removed in 13.0 instead). 

This gives you an additional year to migrate your code.
