### ISSUE TITLE
Custom Validator - AttemptedValue is not available to edit

### ISSUE THREAD

**Issue by Pitfin** [FluentValidation/FluentValidation#2005]
### Is your feature request related to a problem? Please describe.

I'd like to be able to validate the Json payload below.
I want to be able to get a list of TransactionIds that do NOT appear in the Customers list. I would like to be able to set the attempted value field as (as in this example): "12, 13"
Then in the Message: Transaction IDs 12, 13 did not have a corresponding Customer record.

**This issue seems to be due to not being able to set the AttemptedValue field**

`{
	"payloadNumber": "1",
	"customers": [
		{
			"customerNumber": "001"
		}
	],
	"cashOutTransactions": [
		{
			"customerNumber": "001",
			"transactionId": "10"
		},
		{
			"customerNumber": "001",
			"transactionId": "11"
		},
		{
			"customerNumber": "002",
			"transactionId": "12"
		},
		{
			"customerNumber": "003",
			"transactionId": "13"
		}
	]
}`

### Describe the solution you'd like

An ability to set the AttemptedValue field in a Custom Validator.

### Describe alternatives you've considered

Tried everything on the documentation page. Cant seem to be able to set AttemptedValue.

**Comment by Pitfin** [comment]
If you try and add your own custom ValidationFailure, you end up with 2 ValidationFailures:

`        public override bool IsValid(ValidationContext<T> context, TProperty value)
        {
            var custSnap = context.InstanceToValidate;
            var x = new ValidationFailure(Name, "MyCustomValidator is invalid", "12, 14");
            x.CustomState = custSnap.CustomerNumber;
            x.ErrorCode = "CUST9999";
            context.AddFailure(x);

            return false;
        }`

**Comment by JeremySkinner** [comment]
I don't really understand what you're trying to achieve. 

`AttemptedValue` on the `ValidationFailure` is just a reference to the value of the property being validated. It isn't intended to be customised. It's not used for anything other than for providing information to the consumer of the validation failure about the value that caused the failure. 

Can you provide a more detailed example about specifically what you want to achieve in the form of a unit test? Thanks.
