### ISSUE TITLE
Rule for GreaterThan() displays the same as GreaterThanOrEqualTo() in Swagger

### ISSUE THREAD

**Issue by PeterTragardh** [FluentValidation/FluentValidation#2007]
### FluentValidation version

11.2.2

### ASP.NET version

.NET 6

### Summary

![image](https://user-images.githubusercontent.com/36367209/189901430-6b6a27af-972d-4abe-bda5-8096b6e4a1df.png)

As you can see, the result says "minimum: 0"
but the rule is:
RuleFor(x => x.JustAnotherValue).GreaterThan(0);

It should be saying something like: "minimum: 1"

### Steps to Reproduce

Run application and go to the endpoint in Swagger.
Click on: Schema

[ApiController]
[Produces("application/json")]
[Route("api/[controller]")]
public class PetTryoutController : Controller
{
    [HttpPost]
    public ActionResult TryoutFluVal(TryoutRequest ourRequest)
    {
        ourRequest.JustAnotherValue += 10;
        return Ok(ourRequest);
    }
}

public class TryoutRequest
{
    public int JustAnotherValue { get; set; }

    internal class Validator : AbstractValidator<TryoutRequest>
    {
        public Validator()
        {
            RuleFor(x => x.JustAnotherValue).GreaterThan(0);
        }
    }
}

**Comment by JeremySkinner** [comment]
Hello, we don't provide any integration with Swagger out of the box. You should raise this issue with the maintainers of whichever library you use to provide swagger integration with FluentValidation.
