### ISSUE TITLE
Conditional errorMessage and severity

### ISSUE THREAD

**Issue by azerios** [FluentValidation/FluentValidation#2008]
### Describe the solution you'd like

Dear,

I have this little code as sample : 
`namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var foo = new MyObject();
            foo.Ids = "1,2,3";
            foo.Countries = "IT,FR,IT";

            var validator = new MyObjectValidator();
            var result = validator.Validate(foo);
            // result.Errors.Count is 0

            foo.Ids = "1,2,4";
            foo.Countries = "IT,FR,LU";
            result = validator.Validate(foo);
            // result.Errors.Count is 1
        }
    }

    public class MyObject
    {
        public string Countries { get; set; }

        public string Ids { get; set; }
    }

    public class MyObjectValidator : AbstractValidator<MyObject>
    {
        public MyObjectValidator()
        {
            RuleFor(i => i)
                .Must(ValidatorExtension.IsValid)
                .When(i => !string.IsNullOrWhiteSpace(i.Ids) 
                    && !string.IsNullOrWhiteSpace(i.Countries)
                    && !i.Countries.Contains("LU"))
                .WithMessage("Wrong combination")
                .WithSeverity(Severity.Warning)
                .WithErrorCode("BC");

            RuleFor(i => i)
                .Must(ValidatorExtension.IsValid)
                .When(i => !string.IsNullOrWhiteSpace(i.Ids)
                    && !string.IsNullOrWhiteSpace(i.Countries)
                    && i.Countries.Contains("LU"))
                .WithMessage("Very bad combination")
                .WithSeverity(Severity.Error)
                .WithErrorCode("VBC");
        }
    }

    public class ValidatorExtension
    {
        internal static List<string> Countries = new List<string>
        {
            "LU",
            "ES",
            "FR",
            "IT"
        };

        internal static List<string> AllowedIds = new List<string>
        {
            "1",
            "2",
            "3"
        };

        internal static bool IsValid(MyObject arg)
        {
            var splitCountries = arg.Countries.Split(',');
            var splitIds = arg.Ids.Split(',');
            var isValid = true;
            for (var i = 0; i < splitCountries.Length; i++)
            {
                var s = splitCountries[i];
                if (isValid)
                    isValid = Countries.Contains(s) && AllowedIds.Contains(splitIds[i]);
            }
            return isValid;
        }
    }
}`

I'm wondering if there is another way than using a condition in When method to correctly return an error or a warning following strings content.

Regards

**Comment by JeremySkinner** [comment]
`WithMessage` and `WithSeverity` both have overloads that can take a lambda expression. You could use this to conditionally return a different message/severity based on the input. Alternatively you could [use a custom validator](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator) to build whatever message/severity you want. 

Option 1, using labmdas in WithMessage/WithSeverity:

```csharp
RuleFor(x => x).Must(ValidatorExtension.IsValid)
  .When(...whatever...)
  .WithMessage(x => SomeConditionalCheck(x) ? "Wrong combination" : "Bad combination")
  .WithSeverity(x => SomeConditionalCheck(x) ? Severity.Warning : Severity.Error)
```

Option 2, Custom validator:
```csharp
RuleFor(x => x).Custom((x, context) => {
  bool valid = ValidatorExtension.IsValid(x);
  if (!valid) {
    string message;
    Severity severity;
    if (SomeCondition(x)) {
      message = "Wrong combination";
      severity = Severity.Warning;
    }
    else {
      message = "Bad combination";
      severity = Severity.Error;
    }
    context.AddFailure(new ValidationFailure(context.PropertyName, message) { Severity = severity })
  }
})
```


Please note this is an issue tracker for reporting bugs in the library - [it is not for general support or usage questions](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions).
