### ISSUE TITLE
Custom Validator - run only when value is valid

### ISSUE THREAD

**Issue by zaverden** [FluentValidation/FluentValidation#2011]
### Is your feature request related to a problem? Please describe.

I'm building a heavy custom async validator that does not make sense to run if any of previouse rules failed. for example:

```
RuleFor(x => x.Email).NotEmpty().EmailAddress().CustomAsync(this.CheckActiveCustomer);
``` 

where `CheckActiveCustomer` goes to the external API sending `Email` value. I don't want to run this expensive operation if user did not send a valid email. 

### Describe the solution you'd like

I see 2 options:

1. `runOnInvalid` flag for `CustomAsync` and similar methods
```
RuleFor(x => x.Email).NotEmpty().EmailAddress().CustomAsync(this.CheckActiveCustomer, runOnInvalid: false);
```

2. `IsValid` property in `ValidationContext<T>`
```
        private async Task CheckActiveCustomer(string email, ValidationContext<MyModel> context, CancellationToken _token)
        {
            if (!context.IsValid) return;
            // ... api calls ...
        }
```

### Describe alternatives you've considered

Expose `Failures` property in `ValidationContext<T>` to public. It's internal as for v11

if we choose this option, it is better to expose it as `IReadOnlyCollection<ValidationFailure>`, I believe.

**Comment by JeremySkinner** [comment]
You can achieve this by setting the `ClassLevelCascadeMode` property to `Stop` on the validator class. This prevents rule chains from executing if the previous one fails. https://docs.fluentvalidation.net/en/latest/cascade.html

**Comment by zaverden** [comment]
thank you for pointing
