### ISSUE TITLE
Flag to fail if property sent to options.IncludeProperties is not found

### ISSUE THREAD

**Issue by dberry-rcs** [FluentValidation/FluentValidation#2014]
### Is your feature request related to a problem? Please describe.

There was a typo in a unitTest where the property was misspelled and the test still passed. The intended validation was not being run and, in fact, ignored. 

### Describe the solution you'd like

A boolean flag parameter on  ValidationStrategy<T>.IncludeProperties to fail if a passed in property does not exist, such as,

ValidationStrategy<T>.IncludeProperties( string[] properties, bool failMissing = false);

### Describe alternatives you've considered

I have considered interrogating the instance myself to see if all the properties do in fact exist.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but I'm not keen on this. 

I would recommend interrogating the instance yourself if you need this behaviour. Alternatively, if you want type safety then you should use the overload of `IncludeProperties` that takes a series of lambda expression instead:

```
validator.Validate(customer, options => 
{
  options.IncludeProperties(x => x.Name, x => x.Age);
});
```

**Comment by dberry-rcs** [comment]
Thanks for reviewing. Unfortunately we are receiving data from GraphQL and do not know ahead of time what properties need to be updated. That is why we use the string[].
