### ISSUE TITLE
MaxLength and MinLength specific messages for collection

### ISSUE THREAD

**Issue by be-swarm** [FluentValidation/FluentValidation#2015]
### Is your feature request related to a problem? Please describe.

[MaxLength] and [MinLength] control string length and number on items in a collection.

fluent validation only have localized messages for string:
"MinimumLengthValidator" => "The length of '{PropertyName}' must be at least {MinLength} characters. You entered {TotalLength} characters.",
"MaximumLengthValidator" => "The length of '{PropertyName}' must be {MaxLength} characters or fewer. You entered {TotalLength} characters.",

### Describe the solution you'd like

Is it possible to have specific localized message for collection  ?

Thanks

**Comment by JeremySkinner** [comment]
FluentValidation's `MinimumLength` and `MaximumLength` methods are only for string lengths and are not for validating collection lengths.

For collection lengths you should use the `Must` method and [provide a custom predicate](https://docs.fluentvalidation.net/en/latest/built-in-validators.html#predicate-validator). You can provide your own localised messages for this.
