### ISSUE TITLE
Generic validator not found

### ISSUE THREAD

**Issue by johnkwaters** [FluentValidation/FluentValidation#2017]
### FluentValidation version

11.2.2

### ASP.NET version

dotnet 6

### Summary

I have a generic validator, used for MediatR requests:

```
public class SearchQueryValidator<TEntity, TEntityDto, TSearchDto> 
    : AbstractValidator<SearchQuery<TEntity, TEntityDto, TSearchDto>>
    where TEntity : class, new()
    where TEntityDto : class, new()
    where TSearchDto : PagedResultsRequestDTO, new()
{
    public SearchQueryValidator()
    {
        RuleFor(x => x.Search.PageSize).GreaterThan(0).
            WithMessage("Page size must be >= 0");
    }
}

```

When I try to resolve Validators in my pipeline behavior constructor, none are found. When I step through the code behind

`
.AddValidatorsFromAssemblyContaining(typeof(SearchQueryValidator<,,>),ServiceLifetime.Transient);
`
I see

```
	private IEnumerable<AssemblyScanResult> Execute() {
		var openGenericType = typeof(IValidator<>);
		var query = from type in _types
			where !type.IsAbstract && !type.IsGenericTypeDefinition
			let interfaces = type.GetInterfaces()
			let genericInterfaces = interfaces.Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == openGenericType)
			let matchingInterface = genericInterfaces.FirstOrDefault()
			where matchingInterface != null
			select new AssemblyScanResult(matchingInterface, type);

		return query;
	}

```

If I remove 

`&& !type.IsGenericTypeDefinition`

From the query, it DOES find my generic validator

### Steps to Reproduce

See code above.

**Comment by JeremySkinner** [comment]
We intentionally do not register open generic types within the automatic assembly scanning functionality. If you are using open generics in this way then you will need to register them directly rather than using the `AddValidator...` methods.

**Comment by johnkwaters** [comment]
If I register it manually, it still isn't found when I ask to inject instances of IValidator. I have to create a concrete subclass with types for it to be found

`public class UserSearchQueryValidator : SearchQueryValidator<ApplicationUser, UserDTO, UserSearchDTO> { }`

Seems annoying to have to create a type just for this to work - I admit this is not my strongest suite.
