### ISSUE TITLE
Provide a way to assert a specific validator was run

### ISSUE THREAD

**Issue by petro2050** [FluentValidation/FluentValidation#2031]
### Is your feature request related to a problem? Please describe.

I'm writing tests for various validators using [Test Extensions](https://docs.fluentvalidation.net/en/latest/testing.html). I have multiple properties that make use of `SetValidator()`. Here's an example:

```
public class CustomerValidator : AbstractValidator<Customer> 
{
    public CustomerValidator() 
    {
        RuleFor(x => x.Address).NotNull().SetValidator(new AddressValidator());
    }
}
```

When working on tests for `CustomerValidator`, instead of writing tests that touch `AddressValidator`, I'd like to simply assert that the validator was run. This way, the tests for the address validator can be placed in a separate class dedicated to `Address`.

### Describe the solution you'd like

There should be a result returned from `TestValidate()` that tells me if a specific validator was run. This will be useful in cases where I don't care if validation had errors or not. Asserting that a property is being validated by a custom validator will prevent future regressions.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. You should use dependency injection and a stub implementation of your child validator to achieve this. A simple implementation might look something like this:

```
public class StubValidator<T> : AbstractValidator<T> {
	public bool ValidateInvoked;
	public bool ValidateAsyncInvoked;

	public override ValidationResult Validate(ValidationContext<T> context) {
		ValidateInvoked = true;
		return base.Validate(context);
	}

	public override Task<ValidationResult> ValidateAsync(ValidationContext<T> context, CancellationToken cancellation = new CancellationToken()) {
		ValidateAsyncInvoked = true;
		return base.ValidateAsync(context, cancellation);
	}
}
```

Your `CustomerValidator` would be defined as follows:

```csharp
public class CustomerValidator : AbstractValidator<Customer> {
	public CustomerValidator(IValidator<Address> addressValidator) {
		RuleFor(x => x.Address).NotNull().SetValidator(addressValidator);
	}
}
```

Your test would then look like this:

```csharp
var addressValidator = new StubValidator<Address>();
var validator = new CustomerValidator(addressValidator);
validator.Validate(new Customer());
Assert.True(addressValidator.ValidateInvoked);
```

and in your application you'd inject a real `AddressValidator` instance into your `CustomerValidator`

**Comment by petro2050** [comment]
Thanks @JeremySkinner. I've started incorporating your changes. How does a stub validator behave if it's used to validate `RuleForEach`? It seems only a single copy of a validator will be used for each item that needs to be validated which means `ValidateInvoked` becomes a shared variable.

**Comment by JeremySkinner** [comment]
That’s correct. This was just a simple implementation - you could change it to a counter that tracks the number of times invoked for example if you need more granularity with RuleForEach.
