### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ltemimi** [FluentValidation/FluentValidation#2032]
### FluentValidation version

latest  11.4.0

### ASP.NET version

dot net 7

### Summary

I have a blazor server app dot net 7. I published the app when I try and run it I get an unhandled exception

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'FluentValidation, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0'. The system cannot find the file specified.

NOTE All works OK when building and running locally in visual studio

### Steps to Reproduce

1 - Create a blazor server app
2 - install fluent validation and use in some code
3 - publish the app and create IIS site
4 - Run the site with errors enabled in web. config file
5 - open the create error file stdout_20221130084314_11720  in the log directory 
6  - observe that an unhandled exception is reported in the error file

**Comment by JeremySkinner** [comment]
This works fine for me. It sounds like your publishing process is not copying the FluentValidation assembly to the output directory for some reason, but this isn't an issue with FluentValidation itself - this will be an issue with your setup somewhere, so I'm afraid I can't really help you with this. 

I would suggest you troubleshoot by creating a minimal sample project that strips out everything unrelated and see if it still happens. Also try removing FluentValidation entirely and see if the same thing happens with other assemblies which will help eliminate FluentValidation itself as being the cause. 

Sorry I can't help further.

**Comment by ltemimi** [comment]
Hi

I have found the issue you are right, the fluent validation was not pushed to the output folder when publishing. I unticked "Trim unused code" and unticked the ahead compilation in the publish profile and all worked.

Thanks for your help
