### ISSUE TITLE
Regression in v11.0.0 and later: test helper WithErrorMessage behaves differently from v10.4.0, when used multiple times in Fluent call chain

### ISSUE THREAD

**Issue by Bergam64** [FluentValidation/FluentValidation#2034]
### FluentValidation version

11.0.0 to 11.4.0

### ASP.NET version

.NET 6

### Summary

Hello!

I'd like to report a regression that I discovered when I upgraded from 10.4.0 to 11.0.0 in one of my projects, and which is still present in the latest version (11.4.0).

The problem lies in how extension method `WithErrorMessage` behaves **when used multiple times in a Fluent call chain**, like this:
```csharp
var result = target.TestValidate(myModel);

result
    .ShouldHaveValidationErrorFor(m => m.MyProperty)
    .WithErrorMessage("ValidationError1")
    .WithErrorMessage("ValidationError2");
```

Notes:
- It appears that `WithErrorMessage` no longer returns the initial `IEnumerable<ValidationFailure>` returned from the first call in the chain (`ShouldHaveValidationErrorFor`).
- The problem stays hidden if only 1 call to `WithErrorMessage` is made in the chain.

---

The only workaround I've found so far is this one:
```csharp
var result = target.TestValidate(myModel);

var validationFailures = result.ShouldHaveValidationErrorFor(m => m.MyProperty);
validationFailures.WithErrorMessage("ValidationError1");
validationFailures.WithErrorMessage("ValidationError2");
```

Notes:
- This workaround is no longer _Fluent_, which is too bad (after all, this is FluentValidation, isn't it?).
- This workaround doesn't work in 11.0.0, but this was fixed in 11.0.1.

---

I've been using this library for quite a while now and, despite this regression, this is a **great** library !
Keep up the good work !

### Steps to Reproduce

I had prepared a minimal sample solution, but I've not found a way to upload it here, so here's the code.

- Create a C# Class Library project targeting .NET 6, named `Repro`.
  - Delete auto-generated class `Class1`.
  - Add a NuGet reference to `FluentValidation 10.4.0` (to prove it was working in that version).
  - Add a class named `Model`:
    ```csharp
    namespace Repro;
  
    public class Model
    {
        public string Name { get; set; } = "";
    }
    ```
  - Add a class named `ModelValidator`:
    ```csharp
    using FluentValidation;

    namespace Repro;

    public class ModelValidator : AbstractValidator<Model>
    {
        public ModelValidator()
        {
            RuleFor(m => m.Name)
                .Custom(MustBeValid);
        }

        private void MustBeValid(
            string name,
            ValidationContext<Model> context)
        {
            if (name.Contains("Condition1"))
            {
                context.AddFailure("ValidationError1");
            }

            if (name.Contains("Condition2"))
            {
                context.AddFailure("ValidationError2");
            }
        }
    }
    ```
- Add a C# NUnit Test Project targeting .NET 6, named `Repro.Tests`.
  - Delete auto-generated class `UnitTest1`.
  - Add a class named `ModelValidatorTests`:
    ```csharp
    namespace Repro.Tests;

    [TestFixture]
    public class ModelValidatorTests
    {
        [Test]
        public void WithoutWorkaround()
        {
            var target = new ModelValidator();
            var model = new Model { Name = "Condition1, Condition2" };

            var result = target.TestValidate(model);

            // The following code used to work in FluentValidation 10.4.0, but is broken from 11.0.0 to at least until 11.4.0.
            result
                .ShouldHaveValidationErrorFor(m => m.Name)
                .WithErrorMessage("ValidationError1")
                .WithErrorMessage("ValidationError2");
        }

        [Test]
        public void WithWorkaround()
        {
            var target = new ModelValidator();
            var model = new Model { Name = "Condition1, Condition2" };

            var result = target.TestValidate(model);

            // The following workaround (valid in FluentValidation 10.4.0), started to work in 11.0.1 and is still
            // valid up to at least until 11.4.0. But this is just a workaround: the chained call syntax (Fluent) is broken
            // since 11.0.0.
            var validationFailures = result.ShouldHaveValidationErrorFor(m => m.Name);
            validationFailures.WithErrorMessage("ValidationError1");
            validationFailures.WithErrorMessage("ValidationError2");
        }
    }
    ```
  - Run all tests. All are green. So far so good.
- Upgrade NuGet reference to `FluentValidation 11.0.0`.
  - Run all tests. All are red.
- Upgrade NuGet reference to `FluentValidation 11.0.1`.
  - Run all tests. `WithWorkaround` is green but `WithoutWorkaround` is red.
- Same situation if you upgrade to `FluentValidation 11.4.0`.

**Comment by JeremySkinner** [comment]
Hi, this behaviour is intentional - each assertion chain is intended to be standalone, and each step within the assertion chain further filters down the set of matched failures. So calling `WithErrorMessage("ValidationError1")` filters the failures down to only those which match the message "ValidationError1", when you can then make further assertions against those. 

You should think as each assertion chain as being a separate 'test', so if you have 2 failures with different messages you should have 2 separate assertion chains. In your case you should be doing the following:

```csharp
var result = target.TestValidate(myModel);

result.ShouldHaveValidationErrorFor(x => x.MyProperty).WithErrorMessage("ValidationError1");
result.ShouldHaveValidationErrorFor(x => x.MyProperty).WithErrorMessage("ValidationError2");
```

Alternatively your workaround works too, but I think being explicit and having 2 separate chains is better.

**Comment by Bergam64** [comment]
Thanks for your feedback! (**Impressive** response time, BTW!)

I suspect I'm not the only one who fell (or might fall) in that trap, so this intended behavior should probably deserve a bit of explanation in the **Test Extensions** page of your documentation.

Thanks again.

**Comment by JeremySkinner** [comment]
Please feel free to open a PR to add some extra clarity to the docs page if you think it’s needed. Thanks!
