### ISSUE TITLE
Validating collection items: accessing the index of the collection item for validation logic

### ISSUE THREAD

**Issue by mmacagno** [FluentValidation/FluentValidation#2037]
### Is your feature request related to a problem? Please describe.

Hello. Love the library.

I have a validation rule where I have elements in a collection that have a Duration property that it must be NotNull for each element of the collection, but the last.

I am converting the manual validation into a Fluent validation:

![image](https://user-images.githubusercontent.com/2315384/209170492-df960394-2fd2-4362-a901-d1a8a38e930d.png)

I am not sure how to implement this in Fluent.
While I could inject the collection count in an override Validate (unless there is a better way), I am not sure how to access the current collection index during the custom rule validation: as I understand, CollectionIndex is only available as a token for the property name or the message.

### Describe the solution you'd like

Any way to access the Collection Index at run time. Maybe there is a way already, but could not figure it out.

Thanks for your great library!

**Comment by JeremySkinner** [comment]
I wouldn't bother trying to rewrite this in a 'fluent' way - the simplest thing to do is just port the logic across as-is [within a custom rule](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator).

**Comment by mmacagno** [comment]
Thanks for your feedback.
So, to be clear, there is no way in the RuleForEach to access the current index for the item.
I was trying to create a special validator only for the "phase" to reuse elsewhere. Not a biggie, just want to confirm the capabilities of the ForEach rules.

Thanks again

**Comment by JeremySkinner** [comment]
Correct. ForEach rules are really for simple use cases - sometime a loop is just a better solution.
