### ISSUE TITLE
Quite slow in my test

### ISSUE THREAD

**Issue by daxu7509** [FluentValidation/FluentValidation#2038]
### FluentValidation version

latest

### ASP.NET version

.net 6

### Summary

hi,
I would to use fluentValidation in our production environment and tested performance in a console app. To my surprise, it is really slow for some reason. I raised the question on stackoverflow as well and all my testing code is there.

https://stackoverflow.com/questions/74914380/slow-fluentvalidation-performance-net-6

I don't really expect fluent validation is as fast as my other validator there, but 100k time slower or 100 time slower is bit too much.

### Steps to Reproduce

https://stackoverflow.com/questions/74914380/slow-fluentvalidation-performance-net-6

All test code is there

**Comment by JeremySkinner** [comment]
Definitely looks like there's something wrong with your setup - 

Firstly, if you want to accurately benchmark please use something like BenchmarkDotNet (which handles warmup as well as averaging across multiple runs), not the StopWatch class, which will not give you reliable results.

Secondly, ensure that you are running *without* the debugger (this is the most common mistake I see when people attempt benchmarking, as the debugger significantly slows down all code). Also make sure you are compiling your application in Release mode. 

The most expensive part of FluentValidation is the compilation of the expression trees within the `RuleFor` lambda calls. Once the validator has been instantiated the first time, the compiled expression trees are cached and reused, and actual validator execution is much faster. 

I'd suggest you look at our own benchmarks, which we use when doing our own profiling of FluentValidation and also use to check whether changes we make affect performance etc. Our own benchmarks can be found here: https://github.com/FluentValidation/FluentValidation/tree/main/src/FluentValidation.Tests.Benchmarks

There are several benchmarks in here, but the one to look at is the `ValidationBenchmark`, which will run against a dataset of 10,000 objects by default (although you can increase that if you want in `DataSet.cs`. 

For 10,000 iterations these are the results I get:

| Method | DataSet | Mean | Error | StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated|
|-- | -- | -- | -- | -- | -- | -- | -- | --|
| FailFast | HalfErrors | 336.58 ms | 3.222 ms | 3.014 ms | 125000 | 0 | 0 | 250.22 MB|
|Validate | HalfErrors | 462.12 ms | 3.303 ms | 2.758 ms | 183000 | 0 | 0 | 364.96 MB|
|FailFast | ManyErrors | 14.65 ms | 0.052 ms | 0.043 ms | 10265.625 | 0 | 0 | 20.5 MB|
|Validate | ManyErrors | 513.44 ms | 2.353 ms | 2.086 ms | 223000 | 0 | 0 | 445.5 MB|
|FailFast | NoErrors | 416.87 ms | 2.178 ms | 2.037 ms | 179000 | 0 | 0 | 357.91 MB|
|Validate | NoErrors | 413.22 ms | 4.085 ms | 3.621 ms | 179000 | 0 | 0 | 357.91 MB|

As expected the ManyErrors dataset (without failing-fast) is the slowest, with mean execution time of 513ms. 

For 100,000 iterations these are the results I get:

|   Method |    DataSet |       Mean |    Error |   StdDev |        Gen 0 | Gen 1 | Gen 2 |  Allocated |
|--------- |----------- |-----------:|---------:|---------:|-------------:|------:|------:|-----------:|
| FailFast | HalfErrors | 2,112.6 ms | 14.10 ms | 13.19 ms | 1251000 |     - |     - | 2494.97 MB |
| Validate | HalfErrors | 3,090.3 ms | 29.23 ms | 27.34 ms | 1815000 |     - |     - | 3619.35 MB |
| FailFast | ManyErrors |   112.8 ms |  2.21 ms |  2.80 ms |  102800 |     - |     - |  205.24 MB |
| Validate | ManyErrors | 3,526.6 ms | 14.60 ms | 12.19 ms | 2223000 |     - |     - | 4433.68 MB |
| FailFast |   NoErrors | 2,987.9 ms | 12.35 ms | 11.55 ms | 1780000 |     - |     - | 3549.74 MB |
| Validate |   NoErrors | 2,977.6 ms | 26.49 ms | 24.78 ms | 1780000 |     - |     - | 3549.74 MB |

Again the slowest will be the Validate/ManyErrors dataset, at 3526ms. This is significantly faster than in your test, and the validator we're using in our benchmarks is much more complex than the one in yours, so I do think there's something not right with your setup.

I can't really help you further than that. If the above benchmarks are still not acceptable to you then I'd suggest you use another library.
