### ISSUE TITLE
Minimal API .net 7.0 - problem in validation from API response during bad request 400.

### ISSUE THREAD

**Issue by YannCardozo** [FluentValidation/FluentValidation#2043]
### Is your feature request related to a problem? Please describe.

Hi, i appreciated so much this packet, it's amazing and I'm loving in using it.

I'm a c#/asp.net core beginner, so I had a problem using him with my API in minimal API 7, maybe i did something very wrong but I didn't notice so far.

my project with general classes is like that:

   public class ProjetosValidador : AbstractValidator<Projetos>
    {
        public ProjetosValidador(IStringLocalizer<Projetos> localizer)
        {

            RuleFor(x => x.Nome).Length(0, 100).WithMessage(x => localizer["E necessario um nome com ate 100 caracteres"]).WithErrorCode("#Nome100");
            RuleFor(x => x.Descricao).NotNull().Length(0, 1000).WithMessage(x => localizer["E necessario um nome com ate 1000 caracteres"]).WithErrorCode("#Nome1000");
            RuleFor(x => x.Prioridade).IsInEnum().WithMessage("Prioridade so pode ser de 0 a 4");
            RuleFor(x => x.QuemSolicitou).NotNull().MaximumLength(200).WithMessage("e necessario informar quem solicitou");
            RuleFor(x => x.DataInicial).LessThanOrEqualTo(x => x.DataFinal).WithMessage("Data inicial e maior que a final");
            RuleFor(x => x.DataFinal).GreaterThanOrEqualTo(x => x.DataInicial).WithMessage("Data final e menor que a data inicial");
            RuleFor(x => x.Cliente).NotNull().NotEmpty().SetValidator(new GuidValidator()).WithMessage("Guid invalido");

           //Some another tries here...

           // var validator = new ProjetosValidador();
           // var result = validator.Validate(new Projetos());
           // foreach (var failure in result.Errors)
           // {
           //     Console.WriteLine($"Property: {failure.PropertyName} Error Code: {failure.ErrorCode}");
           // }
        }
    }
    public class GuidValidator : AbstractValidator<Guid>
    {
        public GuidValidator()
        {
            RuleFor(x => x).NotEmpty();
        }
    }

The verb POST from API PROJECT it's in that way now:

            app.MapPost("/Projetos", async (IValidator<Projetos> ProjetosValidador, Projetos c) =>
            {
                using (ProjetosRepository rep = new())
                {

                    FluentValidation.Results.ValidationResult validationResult = await ProjetosValidador.ValidateAsync(c);

                    if (!validationResult.IsValid)
                    {
                        return Results.ValidationProblem(validationResult.ToDictionary());
                    }

                    object value = rep.InsertAsync(c);

                    return Results.Created($"/{c.id}", ProjetosValidador);
                };
            })

In that Code, i've tried to configure fluent validation for CHANGING this marked in red:

My question is: HOW can i CHANGE from the body response : 

"TITLE", 
"TYPE" , 
"https://tools.ietf.org/html/rfc7231#section-6.5.1" 
"One or more validation errors occurred."

![Captura de tela 2023-01-04 182024](https://user-images.githubusercontent.com/82240581/210652083-d333d993-075e-46ef-b973-3a75c2dfb1c8.png)

### Describe the solution you'd like

My question is: HOW can i CHANGE from the body response : 

"TITLE", 
"TYPE" , 
"https://tools.ietf.org/html/rfc7231#section-6.5.1" 
"One or more validation errors occurred."

![Captura de tela 2023-01-04 182024](https://user-images.githubusercontent.com/82240581/210652083-d333d993-075e-46ef-b973-3a75c2dfb1c8.png)

**Comment by JeremySkinner** [comment]
The format of the response body isn't controlled by FluentValidation - you're using `Results.ValidationProblem` which is part of ASP.NET directly. This is what is producing the body in this format. If you don't want to use this you'd need to manually build your own JSON response in the format that you want. 

Please note that this issue tracker is for reporting bugs in the FluentValidation library - [it isn't for general support/questions](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions), sorry.
