### ISSUE TITLE
Clarify why `MessageFormatter` is in a namespace named `Internal`

### ISSUE THREAD

**Issue by glen-84** [FluentValidation/FluentValidation#2046]
### Is your feature request related to a problem? Please describe.

I'd like to define a custom message formatter, but I'm concerned about the `MessageFormatter` class being in a namespace named `Internal`.

### Describe the solution you'd like

Clarification that it's okay to extend this class, or for the class to be moved to a different namespace.

**Comment by JeremySkinner** [comment]
It is an internal implementation detail of the library hence the `Internal` namespace. You are safe to extend it - we adhere to semantic versioning so any breaking changes would only occur in a major version release, and would be documented in the upgrade guides.
