### ISSUE TITLE
Expose `FormattedMessage` on `ValidationFailure`

### ISSUE THREAD

**Issue by glen-84** [FluentValidation/FluentValidation#2047]
### Is your feature request related to a problem? Please describe.

We'd like to include the "formatted message" (message pattern) in our error responses, to allow them to be localized on the client side.

### Describe the solution you'd like

Would it be possible to include this in the `ValidationFailure` class?

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. 

I'm not keen on further expanding the number of properties exposed on the `ValidationFailure` (it already exposes too much, and I regret agreeing to all the requests over the years to add more to it) but I'll have a think about it.

**Comment by glen-84** [comment]
An alternative may be to use:

```cs
ValidatorOptions.Global.LanguageManager.GetString(validationFailure.ErrorCode);
```

But this would break if a custom error code is set (if I understand correctly).

**Comment by glen-84** [comment]
@JeremySkinner Have you had a chance to think about this some more?

**Comment by JeremySkinner** [comment]
It's not something I'm keen on and isn't something I want to support, so I'm afraid it won't be something that we'll be implementing, sorry. FluentValidation is a server-side library so we expect all localization of messages [to be handled server-side](https://docs.fluentvalidation.net/en/latest/localization.html) 

If you really want to do this then you'd need to use your workaround that you posted above, keeping in mind the limitations regarding overriding the error code. However I'd probably go as far to say that if this is a core requirement for you then you may want to consider whether FluentValidation is actually the best library for you to be using, or if something else would be more suitable.

Sorry if this is disappointing.
