### ISSUE TITLE
.MinimumLength does not check strings for null

### ISSUE THREAD

**Issue by kbilsted** [FluentValidation/FluentValidation#2053]
### FluentValidation version

11.2.2

### ASP.NET version

net6

### Summary

The minimumlength should not allow `null` to be a legal value. 

### Steps to Reproduce

class 

```
  public class CallBackObject
    {
        public string TelephoneNumber { get; set; }
    }
```

given the validation

```
public class CallBackObjectValidation: AbstractValidator<CallBackObject>
{
    public CallBackObjectValidation()
    {
        RuleFor(x => x.TelephoneNumber).MinimumLength(8);
    }
}
````

this test succeeds

```
  [Test]
        public void FluentValidation()
        {
            var res = new CallBackObjectValidation().TestValidate(new CallBackObject());
           //  assert res is empty...
        }
```

whereas it fails when my validation is

``` 
    public CallBackObjectValidation()
    {
        RuleFor(x => x.TelephoneNumber).NotNull().MinimumLength(8);
    }
 ```

which seems needlesly verbose and easy to forget to add `NotNull`

**Comment by JeremySkinner** [comment]
This behaviour is intentional - null is not the same as zero length. This is also consistent with the behaviour of data annotation validation attributes which are built into .NET. 

You should include an explicit NotNull check as per your last example.

**Comment by kbilsted** [comment]
Thanks for the swift reply. Is it worth considering having extension methods that combine notnull + validationXX ?

I think it would make writing validations less tedious. Validation logic can be a struggle to get developers to write in the first place. So i think key board efficiency i important here.

I know I well could write those myself but then no one else get to benefit from it.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but that's not something I'm interested in having in the main library. The principle behind FluentValidation's rules is generally to create composable rule chains of several small parts.
