### ISSUE TITLE
Document how to customize what exception to throw

### ISSUE THREAD

**Issue by kbilsted** [FluentValidation/FluentValidation#2054]
### Is your feature request related to a problem? Please describe.

Reading the documentation https://docs.fluentvalidation.net/en/latest/start.html#throwing-exceptions I can't figure out the best way to adjust the exception being thrown. As I see it there are two candidates

  1. Create your own extension method that calls the validation and throws exception if there are validation errors. 
  2. Create a subclass of `AbstractValidator`

for (1) the implementation could be

```
    public static void ValidateAndThrowArgumentException<T>(this IValidator<T> validator, T instance)
    {
        var res = validator.Validate(instance);

        if (!res.IsValid)
        {
            var ex = new ValidationException(res.Errors);
            throw new ArgumentException(ex.Message, ex);
        }
    }
```

for (2) The implementation could be

```
public class ThrowArgumentExceptionValidator<T> : AbstractValidator<T>
{
    protected override void RaiseValidationException(ValidationContext<T> context, ValidationResult result)
    {
        var ex = new ValidationException(result.Errors);
        throw new ArgumentException(ex.Message, ex);
    }
}
```

(1) seems the most pure, it allows for using the same rules with different exceptions being thrown or not thrown at all.

(2) feels a bit "wrong" as it is invasive in all validation implementations by requiring a new base-class. On The other hand it may be a natural place for other company specific customizations so it is the right way to progress? 

I have too little experience with this to pass judgement.

### Describe the solution you'd like

It would be great with more documentation on this topic. If we can agree on something I may be able to contribute to the documentation.

**Comment by JeremySkinner** [comment]
Either approach is valid - I'd say do whatever you prefer in the context of your application. I don't really have any guidance to give beyond that.

If you feel the documentation needs expanding feel free to open a PR that amends it and I'd be happy to review it.
