### ISSUE TITLE
Fall back on Data Annotations for model validation when no rule for property is defined. 

### ISSUE THREAD

**Issue by bjm3819** [FluentValidation/FluentValidation#2060]
### Is your feature request related to a problem? Please describe.

I am not clear if my feature request is related to a problem. 
I was using Data annotations for my validations. I was told of this library and so I started using it. I quickly learned however that when using fluent validation to validate properties on a class will not defer to using the data annotation validation when no fluent validation rule is defined. 
This forced me to remove the validation annotations I had and move them to a rule on a fluent validation class. 

### Describe the solution you'd like

I would prefer that when using fluent and no Rule for property is defined that any annotation validation would be used as a default. [ref](https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions/mvc-music-store/mvc-music-store-part-6)

### Describe alternatives you've considered

NA

### Additional Context

NA

**Comment by JeremySkinner** [comment]
It depends on how you're invoking the validator.

If you are using the automatic validation that's part of the [FluentValidation.AspNetCore](https://github.com/fluentvalidation/fluentvalidation.aspnetcore) library then validation will fall back to using data annotations attributes if no validator is found. However this is not a feature of FluentValidation, but of ASP.NET itself.

If you are manually invoking the validator by calling the `Validate` method then this is literally only invoking FluentValidation, so data annotations would not be invoked as it is a separate library. Invoking data annotations in this case would not be within scope of this project.
