### ISSUE TITLE
Return IEnumerable<ValidationFailure>

### ISSUE THREAD

**Issue by iamjplant** [FluentValidation/FluentValidation#2061]
### Is your feature request related to a problem? Please describe.

Calling Validate on a large amount of data could result in a ValidationResult with many errors. Due to ValidationResult.Errors being a List, all of these errors have to be in memory at the same time.

### Describe the solution you'd like

It would be nice to be able to call something like ValidateAsIEnumerable that returned an IEnumerable\<ValidationFailure\> using yield return. This would have the added benefit of returning ValidationFailures as they're found instead of waiting for the Validate call to return and getting them all at the same time. The ValidationResult.Errors property wouldn't be needed since it is derivative of the presence of any ValidationFailures in the result.

### Describe alternatives you've considered

The existing functionality works, but this would be a nice option to have.

### Additional Context

We do large file batch processing and on occasion the files have a significant number of errors.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't something we'll be including.
