### ISSUE TITLE
Add documentation for validating abstract class implemenetations

### ISSUE THREAD

**Issue by MarvinKlein1508** [FluentValidation/FluentValidation#2063]
### Is your feature request related to a problem? Please describe.

I have a class which holds a List of an abstract class. 
For example:

```csharp
public class Form
{
    public List<FormElement> Elements { get; set; } = new();
}

public abstract class FormElement
{
    public string Name { get; set; } = string.Empty;

    public abstract string GetDefaultName();
}

public class FormNumberElement : FormElement
{
    public int MinValue { get; set; }

    public override string GetDefaultName() => "Number";
}

public class FormDateElement : FormElement
{
    public DateTime MinDate { get; set; }
    public override string GetDefaultName() => "Date";
}
```

The real object now hold different implementations of this abstract class. For example `FormNumberElement` and `FormDateElement`

Now I want to split my validation into pieces because I do not want to repeat the name validation in every validator again. So i've created an abstract Validator for the abstract class `FormElement`

```csharp
public abstract class FormElementValidator<T> : AbstractValidator<T> where T : FormElement
{
    public FormElementValidator()
    {
        RuleFor(x => x.Name)
            .Must(ValidateName)
            .WithMessage("Please enter a name for the element");
    }

    private bool ValidateName(FormElement element, string name)
    {
        if (name == element.GetDefaultName())
        {
            return false;
        }

        return true;
    }
}
```

Now I add two more validators for the other classes.
```csharp
public class FormNumberElementValidator : FormElementValidator<FormNumberElement>
{
    public FormNumberElementValidator() : base()
    {
        RuleFor(x => x.MinValue)
            .GreaterThan(10);
    }
}

public class FormDateElementValidator : FormElementValidator<FormDateElement>
{
    public FormDateElementValidator() : base()
    {
        RuleFor(x => x.MinDate)
            .GreaterThan(DateTime.Now);
    }
}
```

Now I want to validate my `List<FormElement>` and use the correct validator for the corresponding object within my list. So if my item is of type `FormNumberElement` then I'll want to use the `FormNumberElementValidator` and when it's of type `FormDateElement` I'll want to use the `FormDateElementValidator`.

To achive this I've added an abstract method to my `FormElement` class which returns an `IValidator`
`public abstract IValidator GetValidator();`

Each implementation of `FormElement` returns the corresponding validator. For example within `FormNumberElement` I have:
`public override IValidator GetValidator() => new FormNumberElementValidator();`

Now I can loop through all my elements in my List like this:
```csharp
Form form = new Form();
form.Elements.Add(new FormNumberElement());
form.Elements.Add(new FormDateElement());

foreach (var element in Input.GetElements())
{
    IValidator validator = element.GetValidator();
    IValidationContext context = new ValidationContext<FormElement>(element);
    if (validator.Validate(context).IsValid)
    {
        Console.Writeline($"element is valid");
    }
    else
    {
        Console.Writeline($"element is not valid");
    }
}
```

This works exactly as I expect it. The base validation is done and the validation for the corresponding object is done as well. However, I didn't find any documentation within the docs to truely inherit one validator to another validator in abstract context. 

My suggestion is to add an explanation of this to the official docs since it took me quite some time to figure this out. I don't know though if this works as well with DI.

### Describe the solution you'd like

Please add documentation for validating a List which holds abstract items. The items in the list should be validated by the right validator implementation.

**Comment by JeremySkinner** [comment]
Our recommended way to do this is with our Inheritance Validator, which is covered in the documentation here: https://docs.fluentvalidation.net/en/latest/inheritance.html

**Comment by MarvinKlein1508** [comment]
Hi @JeremySkinner thanks for your reply. I've looked at this docs before. But I think they are not good for my use case. 

If I understand this correctly, then according to the documentation I have to define the inherited validator again in all validators.

For example:
```
public abstract class FormElement
{
    public string Name { get; set; }
}

public class FormNumberElement : FormElement
{
    public int MaxValue { get; set; }
}

public class FormElementValidator : AbstractValidator<FormElement>
{
    public FormElementValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty();
    }
}

public class FormNumberElementValidator : AbstractValidator<FormNumberElement>
{
    public FormNumberElementValidator()
    {
        RuleFor(x => x.MaxValue)
            .LessThan(100);

        RuleFor(x => x).SetInheritanceValidator(v => 
        {
            v.Add<FormElement>(new FormElementValidator());
        });

    }
}
```

With my apporach this is not neccessary anymore. It validates the base validator and then the next inhertited instance. 

The main advantage using my code is that I can validate a List of abstract objects within my code. 

That's why I think the docs should be improved for an abstract class validation use case.

**Comment by JeremySkinner** [comment]
No that's not quite right - you'd call `SetInhertanceValidator` in the validator for the class that contains the collection, not the subclass for each element. Example:

```csharp
class FormValidator : AbstractValidator<Form> {
  ctor() {
     RuleForEach(x => x.Elements).SetInheritanveValidator(v => {
        v.Add<FormNumberElement>(new FormNumberElementValidator());
        v.Add<FormDateElement>(new FormDateElementValidator());
       // etc
     });
  }
}
```

**Comment by MarvinKlein1508** [comment]
Ohh now this makes much more sense. Thanks for pointing this out. 

Is there also a way to only validate the elements in this use case? Lets say my FormValidator has more properties to validate but within my code I only want to check only the collection of elements.

That's why I came up with my approach in the first place, because I only want to validate my collection at this point of time.

**Comment by JeremySkinner** [comment]
Yes, use `IncludeProperties` to only validate specific properties on the root validator:

```csharp
validator.Validate(model, options => {
  options.IncludeProperties("Elements");
});
```

**Comment by MarvinKlein1508** [comment]
^Nice. Okay last but not least. Can I also validate only one object from my collection?

**Comment by JeremySkinner** [comment]
You can use the same syntax as above to limit to a specific index:

```
validator.Validate(model, options => {
  options.IncludeProperties("Elements[0]");
});
```

Internally `IncludeProperties` makes use of an `IValidatorSelector` implementation that includes/excludes properties by name. If you have custom logic you want to use you can write your own `IValidatorSelector` too

Alternatively in the rule definition you can filter out items that don't match a certain criteria:

```csharp
RuleForEach(x => x.Elements).Where(elem => ...).SetInheritanceValidator(...)
```

**Comment by MarvinKlein1508** [comment]
@JeremySkinner 

I've changed my code now accoridng to the docs.

```
RuleForEach(x => x.Elements)
    .SetInheritanceValidator(x =>
    {
        x.Add(new FormElementValidator());
        x.Add(new FormTextElementBaseValidator());
        x.Add(new FormCheckboxElementValidator());
        x.Add(new FormDateElementValidator());
        x.Add(new FormFileElementValidator());
        x.Add(new FormLabelElementValidator());
        x.Add(new FormNumberElementValidator());
        x.Add(new FormRadioElementValidator());
        x.Add(new FormSelectElementValidator());
        x.Add(new FormTableElementValidator());
        x.Add(new FormTextareaElementValidator());
        x.Add(new FormTextElementValidator());
    });
```

It chose  the right validator now. But the validator for the base class (`FormElementValidator`) does not get executed. Which makes sence because the validation is now using the right validator for the corresponding object.

To get the base validation working I'll need to change my code like this for example:
```
    public abstract class FormElementValidator<T> : AbstractValidator<T> where T : FormElement
    {
        public FormElementValidator() : base()
        {
            RuleFor(x => x.Name)
                .Must(IsNameSet)
                .WithMessage("Bitte geben Sie dem Feld einen Namen");

        }

        protected bool IsNameSet(FormElement element, string name)
        {
            return element.GetDefaultName() != name;
        }
    }
```

Notice the abstract and the generic specification in the class definition.

Within my final element I can then inherit from the abstract validator like this:
```
    public class FormDateElementValidator : FormElementValidator<FormDateElement>
    {
        public FormDateElementValidator() : base()
        {
            RuleFor(x => x.MinDate)
                .GreaterThan(DateTime.Today.Date);
        }
    }
```

Now it also validates the name with no need to retype it within every validator again.

**Comment by JeremySkinner** [comment]
Yep, that approach is fine and works well. Alternatively you can use [Include statements](https://docs.fluentvalidation.net/en/latest/including-rules.html) if you prefer composition to inheritance
