### ISSUE TITLE
Inconsistent validation error message while using .NotEmpty().

### ISSUE THREAD

**Issue by sunilshahi** [FluentValidation/FluentValidation#2066]
### FluentValidation version

11.4.0

### ASP.NET version

net7.0

### Summary

I see that the validation message generated with .NotEmpty() is slightly different for null vs emty or white space.

Example

```
RuleFor(u => u.UserName)
  .NotEmpty()
  .WithMessage("{PropertyName} is required.");
```
creates these error message.
null => "The UserName field is required."
empty string or whitespace => "User Name is required."  ['The' is removed and 'User Name' is split with a space. ]

OR
```
RuleFor(u => u.UserName)
  .NotEmpty();
```
creates these error message.
null => "The UserName field is required."
empty string or whitespace => "'User Name' must not be empty."  [Again 'The' is removed and 'User Name' is split with a space. But also 'User Name' is surrounded with single quote  ]

While the message is clear it would be better if these message were consistent specially for integration testing.

### Steps to Reproduce

Please see code above.

**Comment by JeremySkinner** [comment]
This isn't related to FluentValidation.

> null => "The UserName field is required."

This message isn't coming from FluentValidation. The "[field name] is required" message comes from ASP.NET's default built-in validation, which executes prior to FluentValidation being run and isn't something we have control over. Essentially ASP.NET itself will generate a message if you supply null to a non-nullable property. 

Either you're trying to pass a null to a non-nullable value type, or you have nullable reference types enabled in your project and have marked the property as non nullable. Either way, this will cause ASP.NET's built in validation to kick in, generating this error message, which short-circuits validation and prevents FluentValidation from being able to run. 

You will need to ensure that the property is marked as nullable if you want to bypass this message, which will then allow FluentValidation to run.

**Comment by sunilshahi** [comment]
Thanks @JeremySkinner  for that prompt reply. I feel dumb now. That makes sense. I feel like I underestimated how well this project is written. :) 
 Thanks for the great work.
