### ISSUE TITLE
11.5.0 breaks EnsureInstanceNotNull workaround for testing with TestValidate

### ISSUE THREAD

**Issue by edubsi** [FluentValidation/FluentValidation#2067]
### FluentValidation version

11.5.0

### ASP.NET version

7.0.200

### Summary

The new version of the package breaks the "workaround" for null Models to be validated with the method described here https://github.com/FluentValidation/FluentValidation/issues/486.

```
protected override void EnsureInstanceNotNull(object instanceToValidate)
    {
        // allow null not to be passed to the validator (https://github.com/FluentValidation/FluentValidation/issues/486)
    }
```

The workflow with PreValidate and returning early didn't work either.

Following Code worked before which is now throwing an ArgumentNull Exception which is thrown by the Guard
```
[Fact]
    public void ShouldValidateNull()
    {
        // act
        var result = validator.TestValidate(null);

        // assert
        result.ShouldHaveAnyValidationError();
    }
```

I worked around this issue by passing the options to the TestValidate

 ```
   [Fact]
    public void ShouldValidateNul()
    {
        // act
        var result = validator.TestValidate(null, options:_ => {});

        // assert
        result.ShouldHaveAnyValidationError();
    }
```

I am not sure if this is intentional or it is okay to break the TestValidate. Feel free to close this issue if it's expected behaviour.

### Steps to Reproduce

// call TestValidate with null which did not throw before 11.5.0

`validator.TestValidate(null);`

**Comment by JeremySkinner** [comment]
You're seeing this as the compiler is unable to determine which overload of the method should be called - the overload that takes the model type, or the overload that takes a `ValidationContext` (added in 11.5).  You can work around with the solution that you've used or alternatively use a cast to the model type (eg `validator.TestValidate((Person)null)` if your validator is for type `Person`) which will force the compiler to pick the correct overload.

Please also note that allowing null instances to be passed to a validator is not recommended, and we're considering removing this behaviour in the future.
