### ISSUE TITLE
Aspect Oriented way of hooking up validators

### ISSUE THREAD

**Issue by jsiegmund** [FluentValidation/FluentValidation#2080]
### Describe the solution you'd like

We have a design philosophy where we create classes for our domain objects, where the constructor (and its methods) of a class safeguards that each instance of that class is in a valid state. For this I'd like to use FluentValidation, but calling the validator from the constructor would require passing it in as an argument (I don't want to `new` it to have DI flexibility), which means I need to bother all places where these types are instantiated with having to pass in the validator. That could be abstracted in another layer but that only complicates things for the wrong reasons. 

So I was wondering what other options I would have and I considered some sort of aspect oriented style where we could append an attribute to a given class to indicate that I'd want the class to be validated as part of the constructor logic (after it's own constructor code finishes). 

I searched for such a thing but could not find it. Is that something that is being or has been considered before? Or maybe a route that has been tried but turned out to be a dead end? Or perhaps there's other ways to fulfill this type of behavior in a good way, I'm eager to find out. When this approach would be interesting I'm open to put in some work and produce a PR.

**Comment by JeremySkinner** [comment]
This isn't something that's within scope of this library, sorry.

**Comment by jsiegmund** [comment]
Ok no problem, thanks for letting me know. If I can carve out some time to build something, i'll leave a link here for those interested.
