### ISSUE TITLE
Optional Validator 

### ISSUE THREAD

**Issue by xyfy** [FluentValidation/FluentValidation#2082]
### Is your feature request related to a problem? Please describe.

now ,all built in validator can return true when null value ,(exclude GreaterThan)  ,

but when I got an empty string ,it cannot pass check

I  want get a way to say when the string is empty,I will get validator passed

No I can only use When(x=>string.isNullorEmptly) to set condition

### Describe the solution you'd like

Give a way  set    `Optional().Validator()`  this will pass all way when value is empty

Or  Option(x=>x.property,()=>{

})

all in the action validator will pass all way when value is empty

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't something we'll be including.
