### ISSUE TITLE
[Docs] Add documentation on TestValidationResult to the Testing section

### ISSUE THREAD

**Issue by ThomasOrtiz** [FluentValidation/FluentValidation#2089]
### Is your feature request related to a problem? Please describe.

When testing a Validator with a `ValidationContext` there is not an obvious way to test the validator with the context. 

The solution is to wrap your validate response with `TestValidationResult` - detailed in #1745 - but there isn't any documentation on that class.

### Describe the solution you'd like

I'd like this [answer](https://github.com/FluentValidation/FluentValidation/issues/1745#issuecomment-849445411) to be added as a section somewhere in the Testing section of documentation.

JeremySkinner:
```
var instanceToValidate = new Person();
var context = new ValidationContext<Person>(person);
context.RootContextData["MyCustomData"] = "Test";
var validator = new PersonValidator();
var result = new TestValidationResult<Person>(validator.Validate(context));
result.ShouldHaveValidationErrorFor(...) //etc
```

**Comment by JeremySkinner** [comment]
With the current version you can pass a context into `TestValidate/TestValidateAsync` directly - no need to manually instantiate `TestValidationResult`, eg `var testResult = validator.TestValidate(context);`

Feel free to submit a PR to the docs if you think that section needs expanding
