### ISSUE TITLE
MinimumLenght MaximumLength properties do not appear in RuleFor function

### ISSUE THREAD

**Issue by hasancaktar** [FluentValidation/FluentValidation#2092]
### FluentValidation version

11.5.1

### ASP.NET version

.net 7.0

### Summary

As seen in the picture, I cannot use the features I specified.
![image](https://user-images.githubusercontent.com/53625738/226822518-9aeb207a-55ea-4ba1-b7e2-4648a4143f1f.png)

### Steps to Reproduce

 public class ProductValidator: AbstractValidator<Product>
    {
         public ProductValidator()
         {
             RuleFor(x => x.RefNo).M
         }
    }

**Comment by hasancaktar** [comment]
> Are you sure you installed the correct nuget packages? I have added the validation package and version information I used in the current project below. You should also remember that the feature you want to use applies to textual expressions. for example: string.
> 
> Package Name: FluentValidation.AspNetCore Version: 11.2.2

Yes. I installed this package
![image](https://user-images.githubusercontent.com/53625738/226947461-ed2db7b6-5cfe-40a3-adb6-b0fe5bce9daa.png)

**Comment by cihatsolak** [comment]
Does the project have a github address? If the project has a Github address, can you share it? You can also pass a screenshot of the product class. It is obvious that there is an error in the lines of code. I don't think there will be any other reason.

**Comment by cihatsolak** [comment]
If you share your repo address with me, I will try to help you.

**Comment by hasancaktar** [comment]
> If you share your repository address with me, I will try to help you.

After a long struggle it was fixed. I actually didn't do anything. I just opened the project on a different computer and there was no problem. thank you so much for helping

**Comment by cihatsolak** [comment]
I'm glad the issue was resolved. Good luck.
