### ISSUE TITLE
RulesetValidatorSelector does not pass Ruleset to child validator on collection

### ISSUE THREAD

**Issue by wonea** [FluentValidation/FluentValidation#2100]
### FluentValidation version

11.5.2

### ASP.NET version

11.3.0

### Summary

RulesetValidatorSelector does not pass Ruleset to child validator. The following should fail with the books not having a name.

### Steps to Reproduce

LINQPad 7 test, child objects should fail.

	void Main()
	{
		var requestObj = new Library("L3 8EW", "Libraries & Information Services", new List<Book>
		{
			new("9780545791434", null),
			new("9780439358071", null),
			new("9780545790352", null),
			new("9780747560722", null)
		});

		var serviceCollection = new ServiceCollection();
		serviceCollection.AddScoped<IValidator<Library>, LibraryValidator>();
		serviceCollection.AddScoped<IValidator<Book>, BookValidator>();
		var serviceProvider = serviceCollection.BuildServiceProvider();
		
		var serviceType = typeof(IValidator<Library>);

		if (serviceProvider.GetService(serviceType) is not IValidator validator)
		{
			return;
		}

		var selector = new RulesetValidatorSelector(new string[] { "Post" });
		// create validation context
		var validationContextGeneric = typeof(ValidationContext<>).MakeGenericType(typeof(Library));
		var validationContext = Activator.CreateInstance(validationContextGeneric, requestObj, new PropertyChain(),
			selector);

		// validate
		var result = validator.Validate((IValidationContext)validationContext);
		result.Dump();
		if (!result.IsValid)
		{
			throw new ValidationException(result.Errors);
		}
	}

	private class Library
	{
		public string PostCode { get; set; }
		public string Name { get; set; }

		public ICollection<Book> Books { get; set; }

		public Library() { }

		public Library(string postCode, string name, ICollection<Book> books)
		{
			PostCode = postCode;
			Name = name;
			Books = books;
		}

		public override string ToString()
		{
			return $"{nameof(PostCode)}: {PostCode}, {nameof(Name)}: {Name}, {nameof(Books)}: {Books.Count}";
		}
	}

	private class LibraryValidator : AbstractValidator<Library>
	{
		public LibraryValidator(IValidator<Book> bookValidator)
		{
			RuleFor(l => l.PostCode)
				.NotEmpty();

			RuleSet("Post", () =>
			{
				RuleFor(l => l.Name)
					.NotEmpty();
			});

			RuleForEach(l => l.Books)
				.SetValidator(bookValidator, "Post"); // Ruleset does not get applied
				//.SetValidator(bookValidator); // Ruleset does not get applied

			/*RuleFor(x => x).ChildRules(child => {
				child.RuleForEach(b => b.Books).SetValidator(bookValidator, "Post");
			});*/
		}
	}

	private class Book
	{
		public string Isbn { get; set; }
		public string Name { get; set; }

		public Book() { }

		public Book(string isbn, string name)
		{
			Isbn = isbn;
			Name = name;
		}

		public override string ToString()
		{
			return $"{nameof(Isbn)}: {Isbn}, {nameof(Name)}: {Name}";
		}
	}

	private class BookValidator : AbstractValidator<Book>
	{
		public BookValidator()
		{
			RuleFor(v => v.Isbn)
				.NotEmpty();

			RuleSet("Post", () =>
			{
				RuleFor(v => v.Name)
					.NotEmpty();
			});
		}
	}

**Comment by JeremySkinner** [comment]
This looks like it's working correctly to me. 

Your call to `RuleForEach(l => l.Books)` is not inside a ruleset, so when you you execute the "Post" ruleset, this collection won't be included for execution. The way you have it configured means "If NO ruleset is executed at the root level, then execute the child validators for the Books collection, but execute their Post ruleset rather than their default ruleset".

I think maybe you meant to do this:

```
RuleSet("Post", () => {
  RuleForEach(l => l.Books).SetValidator(bookValidator);
}
```

...which means "When the post ruleset is executed, execute the child validators for the books collection and also execute their Post ruleset" (you don't have to explicitly specify the ruleset argument for the validator - this is only for overrides. The ruleset the rule is inside will be passed down to the child validator by default)
