### ISSUE TITLE
Rulesets and SetValidator

### ISSUE THREAD

**Issue by Robelind** [FluentValidation/FluentValidation#2101]
### FluentValidation version

11.5.2

### Summary

It seems that in certain scenarios when having rulesets with SetValidator(), the validations are not performed.

### Steps to Reproduce

Using the code below validation works as expected and you get 3 errors.
```
using FluentValidation;
using FluentValidation.Results;

IValidator<Test> validator = new TestValidator();
ValidationResult result = await validator.ValidateAsync(new Test(),
     strategy => strategy.IncludeRuleSets("Test", "Test2").IncludeRulesNotInRuleSet());

foreach(var error in result.Errors)
{
    Console.WriteLine(error.ErrorMessage);
}

Console.ReadKey();

public class TestValidator : AbstractValidator<Test>
{
    public TestValidator()
    {
        RuleFor(t => t.Value).Equal(56);
        RuleSet("Test", () => RuleFor(t => t).SetValidator(new TestValidator2()));
        RuleSet("Test2", () => RuleFor(t => t).SetValidator(new TestValidator3()));
    }
}

public class TestValidator2 : AbstractValidator<Test>
{
    public TestValidator2()
    {
        RuleFor(t => t.Value).Must(value => value == 12);
    }
}

public class TestValidator3 : AbstractValidator<Test>
{
    public TestValidator3()
    {
        RuleFor(t => t.Value).Must(value => value == 13);
    }
}

public class Test
{
    public int Value { get; set; }
}
```
If  we change the validation request to:
```ValidationResult result = await validator.ValidateAsync(new Test(), strategy => strategy.IncludeRuleSets("Test", "Test2"));```
 the rulsets doesn't seem to be executed and we get no validation errors.

Changing the implementation of `TestValidator2` to:
`RuleSet("Test", () => RuleFor(t => t).Must(t => t.Value == 12));`
yields one validation error.

Have I misunderstood something or is this intended behaviour?

**Comment by JeremySkinner** [comment]
This is the correct behaviour - ruleset selection cascades down to child validators. If you invoke the "Test" ruleset on your top-level validator and the child validator definition is inside the "Test" ruleset, then only rules inside the child validator also within a "Test" ruleset will be executed.

You can change/override the default behaviour by specifying a ruleset override in the call to SetValidator:

For example:

```
RuleSet("Test", () => { 
  RuleFor(t => t).SetValidator(new TestValidator(), "default")
});
```

With the above change, whenever the "Test" ruleset is invoked on the top-level validator, then rules in the default/no-ruleset will be invoked in the TestValidator.

**Comment by JeremySkinner** [comment]
> why is not "default" default?

"Default" *is* the default. If you don't specify any rulesets, then the default is executed (ie rules not in a ruleset). When you specify explicitly named rulesets these are executed *instead* of the default. If you want to execute the default too, then you must specify that.

>  there is no need for "default". Why is that?

`IncludeRulesNotInRuleSet()` is just a shortcut for including "default".
