### ISSUE TITLE
How to work around deprecation of ValidatorFactory

### ISSUE THREAD

**Issue by lukos** [FluentValidation/FluentValidation#2107]
### Is your feature request related to a problem? Please describe.

#1961 announced the deprecation of the validator factory, which I understand. 

In the first example, however, there is an issue where you might want lots of different validators available. With the factory, you can just grab the one you need with a single dependency injected into the service class but in the new way, you would need to inject potentially lots of different validators.

In the second example, *with* the factory, you have a meaningful injection of a single service but in the *new* way, you would need to inject the service provider, which is an anti-pattern.

### Describe the solution you'd like

A clearly explanation on the issue of why the factory was deprecated and potentially the pros and cons of creating our own validator factory so we can get the more correct semantics of getting validators where either we are doing something dynamic, or where we are using a high number of different model validators and do not want to inject them separately.

### Describe alternatives you've considered

The only I have currently is to keep using the deprecated factory but if there really is no way to support this, I will have to look at creating my own factory class instead.

**Comment by sebastianstudniczek** [comment]
Hi. I am trying to create a simple service resolver for situation where I have multiple validators defined for a single type and I want to choose the required one based on some value. But I have a problem where validation is triggered right after resolving the service, why is that?
`csharp
internal delegate IValidator<CreateFxDealCommand> FxDealValidatorFactory(FxDealType dealType);

internal class CreateFxDealCommandHandler : IRequestHandler<CreateFxDealCommand> {
    private readonly FxDealValidatorFactory _validatorFactory;

    public CreateFxDealCommandHandler(FxDealValidatorFactory validatorFactory) {
        _validatorFactory = validatorFactory;
    }

    public async Task Handle(CreateFxDealCommand request, CancellationToken cancellationToken) {
        var fxDealValidator = _validatorFactory(dealType);
        var result = fxDealValidator.Validate(request); // This line is never called
    }
}

private static IServiceCollection AddValidators(this IServiceCollection services) {
        services.AddScoped<FxSpotForwardValidator>();

        services.AddScoped<FxDealValidatorFactory>(sp => dealType => dealType switch {
            FxDealType.FXSpotForward => sp.GetRequiredService<FxSpotForwardValidator>()
            _ => throw new KeyNotFoundException()
        });

        return services;
    }

internal class FxSpotForwardValidator : AbstractValidator<CreateFxDealCommand> {
    public FxSpotForwardValidator() {
        RuleFor(x => x.UserId).NotEmpty().MaximumLength(30);
        RuleFor(x => x.PlAllocation).NotEmpty();
    }
}

`
