### ISSUE TITLE
Add CallerContext to ValidationFailure

### ISSUE THREAD

**Issue by SchneiderMK** [FluentValidation/FluentValidation#2116]
### Is your feature request related to a problem? Please describe.

At the moment it is hard to find out what Rule is failing if you have cascaded validators.

### Describe the solution you'd like

Adding a CallerContext with LineNumber, MemberName, FiltePath would help to find the Rule that created the failure.
This could be done by using the CallerLineNumberAttribute, CallerMemberNameAttribute, CallerFilePathAttribut to the RuleFor method.
The CallerContext could be stored in the Rule and if the Rule fails, added to the ValidationFailure.

Example Code:
<code>
public record ValidationCallerContext(string MemberName, string SourcePath, int LineNumber);
     
public IRuleBuilderInitial<T, TProperty> RuleFor<TProperty>(
    Expression<Func<T, TProperty>> expression,
    [CallerMemberName] string memberName = "",
    [CallerFilePath] string sourceFilePath = "",
    [CallerLineNumber] int lineNumber = 0) {
		expression.Guard("Cannot pass null to RuleFor", nameof(expression));
		var rule = PropertyRule<T, TProperty>.Create(expression, () => RuleLevelCascadeMode);
		Rules.Add(rule);
                callerContext = new ValidationCallerContext(memberName, sourceFilePath, lineNumber);
		return new RuleBuilder<T, TProperty>(rule, this);
	}
</code>

### Describe alternatives you've considered

Create a Rule Method like WithState to add the CallerContext to the rule. User can then decide to use the CallerContext or not.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't something we'll be adding to the core library. Adding new properties to ValidationFailure has a lot of implications as a many users directly serialize validation failures and return them from API endpoints, so automatically adding this kind of information in risks exposing information to consuming clients which shouldn't be exposed. 

If you want to do this in your own project I'd recommend using the WithState approach - this is the usual way for handling this kind of scenario.
