### ISSUE TITLE
Building FluentValidation fails with CS0618 on CascadeMode.StopOnFirstFailure

### ISSUE THREAD

**Issue by kennethcochran** [FluentValidation/FluentValidation#2117]
### FluentValidation version

source

### Summary

When I attempt to build from source using either the build.cmd or using Visual Studio I am getting:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0618	'CascadeMode.StopOnFirstFailure' is obsolete: 'The behaviour of StopOnFirstFailure has been replaced by use of the separate validator-level properties ClassLevelCascadeMode and RuleLevelCascadeMode, and their global default equivalents. StopOnFirstFailure will be removed in a later release. For more details, see https://docs.fluentvalidation.net/en/latest/cascade.html .'	FluentValidation (net5.0), FluentValidation (net6.0), FluentValidation (net7.0), FluentValidation (netstandard2.0), FluentValidation (netstandard2.1)	C:\Users\kenne\source\repos\FluentValidation\src\FluentValidation\Enums.cs	39	Active
`

From examining the csproj file it doesn't look like there is a property group explicitly setting TreatWarningsAsErrors or WarningsAsErrors but it appears to be defaulting to enabled in VS2022 (17.6.4) none the less. Not sure if it has always been this way, its a problem with just my machine or if there was a recent change to msbuild (I'm using 17.6.3+07e294721). In any case, I cannot build from source without either modifying the source or overriding the build properties.

This is my first attempt at building FluentValidation from source so it could just be some step I'm overlooking.

### Steps to Reproduce

1. Update Visual Studio 2022 to 17.6.4
2. Do a fresh clone FluentValidation
3. Attempt to run Build.cmd
4. Attempt to build from Visual Studio

**Comment by kennethcochran** [comment]
I tested in using dotnet build. Same result. Interestingly the line it's hitting on is where the obsolete member is defined: enums.cs. Wrapping the obsolete member with pragmas disabling the warning seemed to do the trick. I'm not sure if that's a solution or not.

Still it makes me wonder why I'm seeing this behavior if others aren't. Are all core contributors developing on Linux? You wouldn't think the OS would affect a compiler's behavior when it comes to handling [Obsolete]. Curious.

**Comment by Sivatronics** [comment]
Added this to the FluentValidation.csproj file 

<PropertyGroup>
    <NoWarn>1591</NoWarn>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

**Comment by JeremySkinner** [comment]
@Sivatronics That isn't the correct solution. TreatWarningsAsErrors must remain enabled and suppressions should be placed in code where needed using #pragma, not disabled globally.

**Comment by JeremySkinner** [comment]
@kennethcochran I had some time this evening so I made the change and pushed it up in aa61b359 so no need for a PR. Please give it a try and let me know if you run into further issues.

**Comment by kennethcochran** [comment]
Thanks, that did the trick. I'm using .NET SDK v7.0.305.
