### ISSUE TITLE
Minimal API validation library

### ISSUE THREAD

**Issue by Carl-Hugo** [FluentValidation/FluentValidation#2121]
> I'd be happy to link to your package from the documentation site once you've published it, [like we do for the Blazor packages](https://docs.fluentvalidation.net/en/latest/blazor.html).
> 
> _Originally posted by @JeremySkinner in https://github.com/FluentValidation/FluentValidation/issues/1959#issuecomment-1455165298_

Hi Jeremy, I finally prefixed my Minimal API library and deployed it to NuGet.org. It is a very simple first version that validates Minimal APIs parameters using FluentValidation. I added very few options and will update as new needs arise (if any do). 

When you have a second, please add a reference to the documentation. Here are the NuGet and GitHub links:

- NuGet: https://www.nuget.org/packages/ForEvolve.FluentValidation.AspNetCore.Http
- GitHub: https://github.com/Carl-Hugo/FluentValidation.AspNetCore.Http

Thanks

> I posted in a different issue to keep the other one focused on its subject.

**Comment by JeremySkinner** [comment]
Done, thanks
