### ISSUE TITLE
Don't evaluate specific "heavy" rules if validator already has other failures

### ISSUE THREAD

**Issue by gdoron** [FluentValidation/FluentValidation#2122]
Basically, I I'm looking for somewhat the "opposite" of Cascade.
Instead of stopping the validation chain, I want to skip specific `MustAsync` rules from running if there are other failures already.

Consider a model with 10 `NotEmpty` rules for email, name, credit card etc.
And 1 rule that goes to the DB and verifies name is unique.

Ideally I would want to client to get the failures for all the issues it has, but only go to the DB if all other validations passed.

Seemed like I could achieve something like that with `ValidationContext<T>` in `MustAsync` but it exposes the Failures list with the `internal` modifier, so close but no cigar.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. You can already do this by using separate rulesets, and then combining the result. 

```
class FooValidator : AbstractValidator<Foo> {
  public FooValidator() {
     RuleFor(x => x.Prop1).NotEmpty();
     RuleFor(x => x.Prop2).NotEmpty();

     RuleSet("expensive", () => {
        RuleFor(x => x.Foo).MustAsync(...);
     });
  }
}

var model = new Foo();
var validator = new FooValidator();
// Validate rules not in a ruleset.
var result = validator.Validate(model, opt => opt.IncludeRulesNotInRuleSet()); 
if (result.IsValid) {
   result = await validatator.ValidateAsync(model, opt => opt.IncludeRuleSets("expensive"));
}

```
