### ISSUE TITLE
How to Replace Default placeholder expect {Propertyname}

### ISSUE THREAD

**Issue by HossienMehdikhah** [FluentValidation/FluentValidation#2123]
### Describe the solution you'd like

Hi, 
I Want To Replace value of  {PropertyName} placeholder when it rendring so I use ValidatorOptions.Global.DisplayNameResolver
But I want Replce other placeholder like {ComparisonValue}.
 how do it ?

**Comment by JeremySkinner** [comment]
That's not supported. The placeholders are for FluentValidation's default/built-in messages. If you don't want to use these placeholders you should use your own custom messages with `WithMessage` instead.
