### ISSUE TITLE
Combine multiple ValidationResults

### ISSUE THREAD

**Issue by leandromoh** [FluentValidation/FluentValidation#2125]
### Is your feature request related to a problem? Please describe.

No, just a useful method that I could not find in the lib. 
Is there any "native" way to combine/join multiples ValidationResult's?

### Describe the solution you'd like

It is very useful to combine/join mutiples ValidationResults into a new ValidationResults, for example..

```c#
  ValidationResult fullValidation = new[]
  {
      ValidationA(obj),
      ValidationB(obj),
      ValidationC(obj),
  }
  .Combine();

ValidationResult ValidationA(Person x) { ... }
ValidationResult ValidationB(Person x) { ... }
ValidationResult ValidationC(Person x) { ... }
```

### Describe alternatives you've considered

In my current system I've added the following extension methods.
If there are interest to make them part of the library (in case of no current native solution) I can submit a  PR.

```c#
public static ValidationResult Combine(this ValidationResult validationResult, params ValidationResult[] failuresResult)
{
    return failuresResult.Append(validationResult).Combine();
}

public static ValidationResult Combine(this IEnumerable<ValidationResult> failuresResult)
{
    var errors = failuresResult.SelectMany(x => x.Errors);

    return new ValidationResult(errors);
}
```

**Comment by JeremySkinner** [comment]
I'm not keen on a `Combine` method, but I could add another constructor to `ValidationResult` that takes an `IEnumerable<ValidationResult>` if that'd be helpful?

**Comment by leandromoh** [comment]
> I'm not keen on a `Combine` method, but I could add another constructor to `ValidationResult` that takes an `IEnumerable<ValidationResult>` if that'd be helpful?

Sure! It would help a lot.

**Comment by JeremySkinner** [comment]
Added the new constructor in 1f9102d8a. This will go in the 11.7 release.

I'm not keen on including the extension methods in the library, I don't feel they're necessary, but you can continue to use them within your own project.

**Comment by leandromoh** [comment]
@JeremySkinner thanks for the improvement (:

**Comment by JeremySkinner** [comment]
11.7.0 us now released with this change

**Comment by cremor** [comment]
> Added the new constructor in [1f9102d](https://github.com/FluentValidation/FluentValidation/commit/1f9102d8ab299eeddf3b4ffda9b96b695dedecfb). This will go in the 11.7 release.

@JeremySkinner What about the `RuleSetsExecuted` property? Do you not have to combine those too?

**Comment by JeremySkinner** [comment]
@cremor Yes you’re right, I missed that. I’ll try and push out a further update to resolve that when I get some time, or if you’d like to submit a PR that’d be very welcome

**Comment by cremor** [comment]
I'm not really sure what the correct implementation would be. Maybe this?

```cs
RuleSetsExecuted = otherResults.Where(x => x.RuleSetsExecuted != null).SelectMany(x => x.RuleSetsExecuted).Distinct().ToArray();
```

**Comment by JeremySkinner** [comment]
Yep I think that should work

**Comment by JeremySkinner** [comment]
I've pushed out 11.7.1 with this fix
