### ISSUE TITLE
typo in breaking changes issue

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [FluentValidation/FluentValidation#2126]
### FluentValidation version

11.3.0

### ASP.NET version

.net7

### Summary

in this issue https://github.com/FluentValidation/FluentValidation/issues/1965
it have this code 
`services.AddValidatorsFromAssemblyComtaining<MyValidator>();`

but it should be

`services.AddValidatorsFromAssemblyContaining<MyValidator>();`

### Steps to Reproduce

open the other issue issue

**Comment by JeremySkinner** [comment]
Corrected, thanks
