### ISSUE TITLE
Correction in Brazilian Portuguese Translation of "ExactLength_Simple" Message

### ISSUE THREAD

**Issue by renanl23** [FluentValidation/FluentValidation#2130]
### FluentValidation version

11.6.0

### ASP.NET version

.NET 6

### Summary

Hello everyone,

We have identified a minor grammatical inaccuracy in the Brazilian Portuguese translation of the "ExactLength_Simple" message in project.

### Steps to Reproduce

Currently, the message is being translated as:
`"ExactLength_Simple" => "'{PropertyName}' deve ter no máximo {MaxLength} caracteres.",`

We suggest correcting the message to the following format:
`"ExactLength_Simple" => "'{PropertyName}' deve ter {MaxLength} caracteres de comprimento.",`

The word "máximo" is not appropriate in this translation, as it implies that the value of {MaxLength} is the maximum allowed, when in fact, it indicates the exact size that the property must have.

This change will ensure a better understanding of the message for Brazilian users and avoid possible confusion regarding property size requirements.

We would greatly appreciate it if someone could review and implement this translation change. 

Thank you all for your attention and constant effort to make FluentValidation more user-friendly and accessible to everyone!

**Comment by renanl23** [comment]
PR opened [https://github.com/FluentValidation/FluentValidation/pull/2131](https://github.com/FluentValidation/FluentValidation/pull/2131)

**Comment by JeremySkinner** [comment]
Merged, thanks!
