### ISSUE TITLE
Add implicit NotNull rule to non-nullable reference types

### ISSUE THREAD

**Issue by rez-gparker** [FluentValidation/FluentValidation#2133]
### Is your feature request related to a problem? Please describe.

Model validation in ASP.NET core has a spiffy feature where it treats non-nullable properties as if they were adorned with the RequiredAttribute even if they are not.  This is especially beneficial for non-nullable references types when coding in a project that has the nullable context enabled in the project `<Nullable>enable</Nullable>`.  The biggest benefit comes with strings.  See:  https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0#non-nullable-reference-types-and-required-attribute.

This is a very nice feature that I would love to see in the FluentValidation library. 

### Describe the solution you'd like

Perhaps a setting like this
```
ValidatorOptions.Global.ImplicitlyAddNotNullRuleForNonNullableReferenceTypes = true;
```
That would make it so that the "NotNull" rule is automatically added for all properties of a class that are non-nullable reference types.  

So, if you have a class that looks like this:
```
public class User
{
    public int Id { get; set; }
    public string FirstName { get; set; } = default!;
    public string LastName { get; set; } = default!;
}
```

You could change your validator from this:

```
internal class UserValidator : AbstractValidator<User>
{
    public UserValidator()
    {
        RuleFor(x => x.Id).GreaterThan(0);

        RuleFor(x => x.FirstName).NotNull();

        RuleFor(x => x.LastName).NotNull();
    }
}
```
To this:

```
internal class UserValidator : AbstractValidator<User>
{
    public UserValidator()
    {
        RuleFor(x => x.Id).GreaterThan(0);
    }
}
```

And the FirstName and LastName would still get validated to ensure that they are not null simply because they are defined as non-nullable reference types.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't something we'll be adding. The purpose of FluentValidation is to define rules explicitly at compile-time. This would go against that principle.
