### ISSUE TITLE
Consider using source generators for regular expressions

### ISSUE THREAD

**Issue by virzak** [FluentValidation/FluentValidation#2138]
### Is your feature request related to a problem? Please describe.

The recommended way of using regular expressions is through [source generators](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/).

### Describe the solution you'd like

This line (and others like it)
https://github.com/FluentValidation/FluentValidation/blob/1f9102d8ab299eeddf3b4ffda9b96b695dedecfb/src/FluentValidation/Internal/MessageFormatter.cs#L29

can be rewritten as:

```cs
private static readonly Regex _keyRegex = _keyRegexMethod();

[GeneratedRegex("{([^{}:]+)(?::([^{}]+))?}")]
private static partial Regex _keyRegexMethod();
```

This feature is only available in .NET 7 and above and language version 11+, so `NET7_0_OR_GREATER` symbol should be used.

### Additional Context

Obviously this is very low priority issue, but came across when working on #2136, since this is where we were discussing source generators.

Visual Studio and Rider actually recommend this change when you drop all frameworks other than .NET 7 and upgrade LangVersion.

![image](https://github.com/FluentValidation/FluentValidation/assets/6209775/70bb0790-cdfc-4b18-8859-2af05c5568a1)

![image](https://github.com/FluentValidation/FluentValidation/assets/6209775/a9539b22-9e6f-44ba-96fc-6c489a080c96)

I can send a PR if you're interested.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, this was discussed already in #1907 and the decision was to leave it for now. We'll re-visit once we drop support for platforms older than net7.
