### ISSUE TITLE
Can WithMessage be extended to have an ApplyMessageTo parameter

### ISSUE THREAD

**Issue by danielgreen** [FluentValidation/FluentValidation#2142]
### Is your feature request related to a problem? Please describe.

If there are multiple components in a rule and you want them all to have the same error message, you need to have multiple WithMessage calls in the chain.

### Describe the solution you'd like

Could an ApplyMessageTo parameter work like the When method's ApplyConditionTo?

**Comment by JeremySkinner** [comment]
No, sorry. Messages are intentionally scoped to their immediately preceding component. If you want the same message on multiple components, you must explicitly define it with multiple calls to WithMessage. This is by design.
