### ISSUE TITLE
data-val attributes for client side validations are not generating from fluent validation

### ISSUE THREAD

**Issue by aloksharma1** [FluentValidation/FluentValidation#2144]
### FluentValidation version

11.6.0

### ASP.NET version

.Net 7

### Summary

I'm encountering an issue with FluentValidation's client-side validation in an ASP.NET Core MVC project. While server-side validation works as expected and uses the custom messages defined in my FluentValidation validators, the client-side validation seems to default to using Data Annotations messages.

In short the data-val attributes that should be coming from fluent library is coming from mvc, i tried setting config.DisableDataAnnotationsValidation = true but it didn't work.

PS: i am migrating from .net 5 where everything was working fine.

### Steps to Reproduce

builder.Services.AddFluentValidationAutoValidation(config => config.DisableDataAnnotationsValidation = true).AddFluentValidationClientsideAdapters();
builder.Services.AddValidatorsFromAssemblyContaining<IUltraValidator>();

//validator
public class CustomViewValidator : AbstractValidator<CustomViewsDTO>, IUltraValidator
    {
        public CustomViewValidator(IJsonStringLocalizer<CustomViewsDTO> StringLocalizer)
        {
            RuleFor(x => x.BlockName).NotEmpty().WithMessage(StringLocalizer["Please Enter Unique View Name."]);
            RuleFor(x => x.BlockHtml).NotEmpty().WithMessage(StringLocalizer["This Block Html Field Is Required."]);           
        }
    }

**Comment by JeremySkinner** [comment]
Hi, nothing's really changed between net5 and net7 other than method names so should all work fine. 

- Make sure you're referencing the latest version of FluentValidation.AspNetCore
- Make sure you follow the instructions listed here: https://github.com/FluentValidation/FluentValidation.AspNetCore#clientside-validation
 - Ensure your validators are registered with the container (either via `services.AddValidatorsFromAssemblyContaining<T>());` where T is one of your validators, or by explicitly adding each validator to the container)
 - Make sure you've called in your application startup `services.AddFluentValidationClientsideAdapters();` 
 - That should be all you need to do. You don't need to set `config.DisableDataAnnotationsValidation = true` - this is not related to clientside attributes.

Beyond that I can't really help any further - the FluentValidation.AspNetCore package is no longer supported, although it remains available to use still, but you'll need to troubleshoot/debug this yourself I'm afraid.

**Comment by aloksharma1** [comment]
no issues, I have opted for the alternate ajax form you guys have suggested in your readme.
