### ISSUE TITLE
Support Double data type validation to be used with PrecisionScale

### ISSUE THREAD

**Issue by Shashanksud** [FluentValidation/FluentValidation#2145]
### Is your feature request related to a problem? Please describe.

Before 11.4.0 version we were directly able to validation double dat type using 
`RuleFor(x => (x.CurrMonthlyGrossIncome).ScalePrecision(2, 10)` where CurrMonthlyGrossIncome would be of double type

But after the update, we need to convert it to Decimal and then validate:
`RuleFor(x => Convert.ToDecimal(x.CurrMonthlyGrossIncome)).PrecisionScale(10, 2, false)`

### Describe the solution you'd like

If we can directly validate the Double data type, it would be more cleaner/readable

`RuleFor(x => CurrMonthlyGrossIncome)).PrecisionScale(10, 2, false)`
where CurrMonthlyGrossIncome is of double data type

### Describe alternatives you've considered

Alternate solution is just to convert into decimal and then validate:
`RuleFor(x => Convert.ToDecimal(x.CurrMonthlyGrossIncome)).PrecisionScale(10, 2, false)`

**Comment by JeremySkinner** [comment]
Precision/scale validation is intentionally only supported for decimals. If you were able to do this in older versions then this was an oversight - internally the validator only works with decimals. You should only use this validator on decimal types.
