### ISSUE TITLE
Microsoft.AspNetCore.Mvc.ModelBinding.Validation library deprecated

### ISSUE THREAD

**Issue by jlchavez** [FluentValidation/FluentValidation#2154]
### FluentValidation version

11.4.0

### ASP.NET version

7.0

### Summary

.NET Package Maintenance (deprecation) compatibility issues, some libraries have been deprecated
https://github.com/dotnet/announcements/issues/217

The Microsoft.AspNetCore.Mvc.ModelBinding.Validation library is a deprecated library, and it references old versions of other libraries like System.Runtime.Handles 4.0.1, System.IO.FileSystem.Primitives 4.0.1, etc.

So no ValidationAttribute can be created for interacting in MVC Api validation process since the IPropertyValidationFilter interface is part of the ...Validation library, and for custom types that must be serialized/deserialized manually like in the NetTopologySuite.Geometries, from Microsoft, it won't succeed at all. This downgrade on dependencies break publishing to production...

> C:\Users\jlcha\source\repos\WebPx10\Modules\Medical\WebPx.Medical.Data.EFCore\WebPx.Medical.Data.EFCore.csproj(0,0): Error NU1605: Warning As Error: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
> WebPx.Medical.Data.EFCore -> WebPx.Medical.Abstractions -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
> WebPx.Medical.Data.EFCore -> WebPx.Medical.Abstractions -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)

Currently I will disable the warning as error, but at some point this will be a breaking change.

### Steps to Reproduce

- Create a .net 7 project
- Add the NetTopologySuite
- Add a Custom Serializer/Deserializer for System.Net.Json

```
    public class NetPointConverter : JsonConverter<Point>
    {
        public override Point Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            var parts = value!.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var x = double.Parse(parts[0], CultureInfo.InvariantCulture);
            var y = double.Parse(parts[1], CultureInfo.InvariantCulture);
            return new Point(x, y);
        }

        public override void Write(Utf8JsonWriter writer, Point value, JsonSerializerOptions options)
        {
            writer.WriteStringValue($"{value.X.ToString(CultureInfo.InvariantCulture)} {value.Y.ToString(CultureInfo.InvariantCulture)}");
        }

    }

```

- Add it as a converter in program.cs

```
            services.AddControllersWithViews()
                .AddJsonOptions(options =>
                {
                    var converters = options.JsonSerializerOptions.Converters;
                    converters.Add(new NetPointConverter());
                });
```

- Add it as a property in a class to use in aa API

```
        [ValidateNever]
        public Point? Point { get; set; }
```

- Publish it

**Comment by JeremySkinner** [comment]
I have no idea what you're talking about - this is nothing to do with FluentValidation.
