### ISSUE TITLE
Validator's Validate method doesn't have a second parameter to specify options

### ISSUE THREAD

**Issue by abbatepabloo** [FluentValidation/FluentValidation#2156]
### FluentValidation version

11.7.1

### Summary

Using a validator, I want to validate only one property of many. So  I followed this example from the documentation: [Validating specific properties](https://docs.fluentvalidation.net/en/latest/specific-properties.html)
When I specify the second parameter for the Validate method I get the error: **No overload method 'Validate' takes 2 arguments**
Am I missing something? Is the documentation outdated? If so, is there a way to validate only one property?

### Steps to Reproduce

- Create a validator class:
```cs
public class CustomerValidator : AbstractValidator<Customer>
{
  public CustomerValidator()
  {
    RuleFor(x => x.Surname).NotNull();
    RuleFor(x => x.Forename).NotNull();
    RuleForEach(x => x.Orders).SetValidator(new OrderValidator());
  }
}
```
- Create an instance of the validator:
```cs
var validator = new CustomerValidator();
validator.Validate(customer, options => 
{
  options.IncludeProperties(x => x.Surname);
});
```
- You get the following error:
![image](https://github.com/FluentValidation/FluentValidation/assets/33328600/a156f1ed-233e-4a37-aabb-2a3826350ab3)

**Comment by JeremySkinner** [comment]
It's an extension method. Please make sure you've added a using statement for the `FluentValidation` namespace.
