### ISSUE TITLE
ShouldHaveChildValidator not recognizing Nested Child Validator in Child List Item

### ISSUE THREAD

**Issue by AhmedToInfinity** [FluentValidation/FluentValidation#2157]
### FluentValidation version

10.4.0

### ASP.NET version

6.0

## Preface
I know `ShouldHaveChildValidator` is not your favorite as seen here:
* `//TODO: Should ShouldHaveChildValidator be deprecated? It isn't recommended and leads to brittle tests.` ([method code](https://github.com/FluentValidation/FluentValidation/blob/6cb6b3f52c1b0f21f4c96c5fd0eed1c11cd3cd90/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs#L47))
* [This issue #252](https://github.com/FluentValidation/FluentValidation/issues/252)
* [This other issue #1115](https://github.com/FluentValidation/FluentValidation/issues/1115#issuecomment-490807439)
  * However the suggestion to use `ShouldHaveChildValidator` along with `a few core rules on the child` seems like a great compromise

## Issue
Based on said compromise (`ShouldHaveChildValidator` with `a few core rules on the child`), we are trying to implement this; however, using `RuleForEach` along with `SetValidator`, is returning the error: `FluentValidation.TestHelper.ValidationTestException : Expected property 'Labels' to have a child validator of type 'LanguageTextValidator.'. Instead found 'none'` (see code below for example)

I do not believe this should be the case since [in the current testing](https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation.Tests/ValidatorTesterTester.cs#L192) there is a test to ensure `RuleForEach` with `SetValidator` works for `ShouldHaveChildValidator`. Please advise, why is the error appearing for `none` when there is a child validator set? Code snippet below.

Thank you!

## Code
```c#
public class SomeCommand
{
    public SomeSetupInfo SetupInfo { get; set; }
}

public class SomeSetupInfo
{
    Labels = new List<LanguageText>();
};

public class LanguageText
{
    public string Value { get; set; }
}

internal class SomeValidator : AbstractValidator<SomeCommand>
{
    public SomeValidator()
    {
        RuleFor(x => x.SetupInfo)
            .NotEmpty();

        RuleForEach(x => x.SetupInfo.Labels)
            .SetValidator(new LanguageTextValidator());
    }
}

public void SomeTest()
{
    // Arrange
    var validator = new SomeValidator();
    var command = new SomeCommand
    {
        SetupInfo = new SomeSetupInfo
        {
            Labels = new List<LanguageText>
            {
                new LanguageText { "en" }
            }
        }
    };

    // Act
    var result = validator.Validate(command);

    // Assert
    validator.ShouldHaveChildValidator(x => x.SetupInfo.Labels, typeof(LanguageTextValidator));
}
```

**Comment by JeremySkinner** [comment]
`ShouldHaveChildValidator` only supports checking top-level properties, it doesn't work with nested property paths. You'd need to write your own logic to check this
