### ISSUE TITLE
PhoneValidator?

### ISSUE THREAD

**Issue by mariusz96** [FluentValidation/FluentValidation#2159]
### Describe the solution you'd like

Hi, what is a good way to do phone number validation (international or country-specific) in `FluentValidation`?

It seems that this is so common that even a built-in `PhoneValidator` could be warranted here.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but we have no plans to add any new built-in validators to the core library. You'd need to use the regex validator or a custom validator, depending on your use case.

**Comment by mariusz96** [comment]
Ok, got it. Thanks for quick answer👍
