### ISSUE TITLE
Validations are not getting triggered

### ISSUE THREAD

**Issue by CRC32EX** [FluentValidation/FluentValidation#2160]
### FluentValidation version

11.7.1

### ASP.NET version

7.0

### Summary

`[FromForm]` validations are not getting triggered.
Default (JSON) validations are working successfully.

### Steps to Reproduce

1. unzip [WebApplication1.zip](https://github.com/FluentValidation/FluentValidation/files/12741496/WebApplication1.zip)

2. Test Validation
- Post001 (Validation not working)

![image](https://github.com/FluentValidation/FluentValidation/assets/25629617/0e6e3119-5ce8-4f7c-81a9-dfe58fc4131d)

- Post002 (Validation working)

![image](https://github.com/FluentValidation/FluentValidation/assets/25629617/d0f4ee4e-356e-4f58-a126-0c3fabf41cbf)

**Comment by JeremySkinner** [comment]
We don't maintain the SharpGrip.FluentValidation.AutoValidation package and can't provide support for it - please contact the authors of that package. https://github.com/SharpGrip/FluentValidation.AutoValidation
