### ISSUE TITLE
IEnumerable<T> validation not works with List<T>

### ISSUE THREAD

**Issue by aslandgn** [FluentValidation/FluentValidation#2161]
### FluentValidation version

11.0.0.0

### ASP.NET version

.net 6

### Summary

When I defined the abstract validators with IEnumerable<T> interface, validator can not capture the objects with defined as List<T>
When change the type of validator as List<T> it works fine.
### Steps to Reproduce

define a request class
define a AbstractValidator<IEnumerable<T>> validator with rules
define a httpPost endpoint that accepts List<T>
try to make a request with unvalidateable data
Fluenvalidation will not works.

define a request class
define a AbstractValidator<List<T>> validator with rules
define a httpPost endpoint that accepts List<T>
try to make a request with unvalidateable data
Fluenvalidation will works fine.

**Comment by JeremySkinner** [comment]
This is expected. If you're using automatic validation with ASP.NET then the endpoint and validator must both be defined for `List<T>` - ASP.NET always requests the validator for the exact concrete type that's defined in the endpoint.

**Comment by aslandgn** [comment]
Thanks for reply.
I was thought that should work because of inheritance between IEnumerable and List.
