### ISSUE TITLE
Custom IValidators thrown errors are ''forgotten'' by validator

### ISSUE THREAD

**Issue by Lucasharskamp** [FluentValidation/FluentValidation#2162]
### FluentValidation version

11.7.1

### ASP.NET version

.NET 7

### Summary

In my specific use case the user input must be adhering to a strict number of specific, unique rules. For example, input strings often aren't allowed to have digits, special characters, must be of specific lengths and so on and so forth. As such a simple ''notnull()'' doesn't suffice. These property validators are often shared between unique business object types. (e.g. ''accounts'' and ''environments'' both have an ''owner'', a GUID reference property they both have based on an interface and both business object types must have that field filled in, otherwise the state of the object is not valid.

However, when these specific unique validators throw errors in their results, they aren't (for some reason) thrown back up the stack, but are forgotten. In the following scenario I have a validator called _AccountValidator_, which derives from _AbstractValidator_ of interface type _IAccount_

```
    public AccountValidator(IStringLocalizer<Texts> loc)
    {
        RuleFor(account => account.FirstName).SetValidator(new LabelValidator(loc, nameof(IAccount.FirstName), false, false, StatusCodes.FirstNameNotFilledIn));
        RuleFor(account => account.LastName).SetValidator(new LabelValidator(loc, nameof(IAccount.LastName), false, false, StatusCodes.LastNameNotFilledIn));
        RuleFor(account => account.EmailAddress).SetValidator(new EmailAddressValidator(loc));
    }
```

LabelValidator.cs:

```
internal class LabelValidator : IValidator<string>
{

    public LabelValidator(IStringLocalizer<Texts> loc, string propertyName, bool allowDigits, bool allowSpecialCharacters, StatusCodes notFilledInStatusCode)
    {
        this.Loc = loc;
        PropertyName = propertyName;
        AllowDigits = allowDigits;
        AllowSpecialCharacters = allowSpecialCharacters;
        NotFilledInStatusCode = notFilledInStatusCode;
    }
    // properties, methods, etc...

        /// <inheritdoc />
    public ValidationResult Validate(string instance)
    {
        if (!ModelValidatorsExtensions.IsStringValid(instance, AllowDigits, AllowSpecialCharacters, NotFilledInStatusCode, out var validationModel))
        {
            return new ValidationResult(new[] { new ValidationFailure(PropertyName, String.Format(this.Loc[validationModel.I18nKey], this.Loc[this.PropertyName])) });
        }
        return new ValidationResult();
    }

```

What _LabelValidator_ does is check whether or not the user string meets all the required criteria. However, in case it doesn't, we throw an error alongside with it. **Debugging with breakpoints indicates the _Validate(string instance)_ method has been invoked and the error has been returned properly if the user input didn't meet criteria**

  
```
private void ValidationRequested(object sender, ValidationRequestedEventArgs args)
  {
      ValidationMessageStore.Clear();
      var validationContext = new ValidationContext<object>(EditContext.Model);
      var result = Validator.Validate(validationContext);
      AddValidationResult(EditContext.Model, result);
  }

```

In this case, variable result is always devoid of failure strings, even though one or multiple have been returned 

### Steps to Reproduce

Make an _AbstractValidator_ that implements multiple _IValidator's_ for specific properties and see for yourself.

**Comment by JeremySkinner** [comment]
This isn't the right way to create a custom validator. You shouldn't be implementing `IValidator<T>` directly at any time. 

The `Validate(string instance)` method you've created won't be called. When you use `SetValidator`, only the overload that takes a `ValidationContext` will be invoked. AbstractValidator handles delegating to this overload correctly, but your implementation doesn't. 

The documentation covers how to write custom validators here: https://docs.fluentvalidation.net/en/latest/custom-validators.html Please review this page as it illustrates several approaches outlined on this page, either by using a reusable extension method or by creating a class that inherits from `PropertyValidator`. Alternatively, you could could inherit from `AbstractValidator<string>` and use a Custom rule (but the other approaches are preferred).

Here's an example using a custom extension method:

```csharp
public static class CustomValidators 
{
	public static IRuleBuilderOptionsConditions<T, string> Label<T>(this IRuleBuilder<T, string> rule, IStringLocalizer<Texts> loc, string propertyName, bool allowDigits, bool allowSpecialCharacters, StatusCodes notFilledInStatusCode) 
	{
		return rule.Custom((propertyValue, context) => 
		{
			if (!ModelValidatorsExtensions.IsStringValid(propertyValue, allowDigits, allowDigits, notFilledInStatusCode, out var validationModel))
			{
				context.AddFailure(string.Format(loc[validationModel.I18nKey], loc[propertyName]));
			}
		});
	}
}

// Usable like this:
RuleFor(account => account.FirstName).Label(loc, nameof(IAccount.FirstName), false, false,statusCodes.FirstNameNotFilledIn);
```

Here's an example using `AbstractValidator`:

```csharp
public class LabelValidator : AbstractValidator<string> {

	public LabelValidator(IStringLocalizer<Texts> loc, string propertyName, bool allowDigits, bool allowSpecialCharacters, StatusCodes notFilledInStatusCode) 
	{
		Custom((propertyValue, context) => 
		{
			if (!ModelValidatorsExtensions.IsStringValid(propertyValue, allowDigits, allowDigits, notFilledInStatusCode, out var validationModel)) 
			{
				context.AddFailure(string.Format(loc[validationModel.I18nKey], loc[propertyName]));
			}
		});
	}
}

// Usable as per your original example:
RuleFor(account => account.FirstName).SetValidator(new LabelValidator(loc, nameof(IAccount.FirstName), false, false, StatusCodes.FirstNameNotFilledIn));
```

I would highly recommend you review the documentation page I linked to on custom validators and will reiterate that *you shouldn't be implementing `IValidator` directly*.

**Comment by JeremySkinner** [comment]
The documentation is already sufficiently detailed
