### ISSUE TITLE
Change PropertyChain to inherit from List<string> to avoid allocations

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#2163]
### Describe the solution you'd like

As raised in #2158, changing PropertyChain to inherit from List<string> will reduce allocations. This is a runtime breaking change so should be done in 12.0.

**Comment by hogwartsdeveloper** [comment]
I can do it?

**Comment by JeremySkinner** [comment]
> I can do it?

Thank you for the offer, but no - please leave this one. I haven’t yet decided if this will go ahead.
