### ISSUE TITLE
Rehabilitate Net4xRegex as not obsolete

### ISSUE THREAD

**Issue by christopheblin** [FluentValidation/FluentValidation#2164]
### Is your feature request related to a problem? Please describe.

I want to validate my email with a regexp approach

I KNOW that to verify that the email is valid you must send an email BUT this is not what I want to do (I just want to validate that the email is RFC valid)

### Describe the solution you'd like

Allow something like .EmailAddress(EmailValidationMode.RegexRfcXxxx) with a clear documentation saying it is supported BUT not 100% enough 

### Describe alternatives you've considered

Doing my own .RegExpEmailAdress() extension which calls the .EmailAddress(EmailValidationMode.Net4xRegex) with pragma to disable warnings

**Comment by JeremySkinner** [comment]
Thanks for suggestion but no, this will remain deprecated. However it won't be removed - it will remain available to use, but will also remain deprecated.
