### ISSUE TITLE
How to join error codes when there are nested child validators?

### ISSUE THREAD

**Issue by RayWangQvQ** [FluentValidation/FluentValidation#2167]
### Is your feature request related to a problem? Please describe.

Is there a way to join error codes when there are nested child validators？

Such as:

```
public class ParentValidator : AbstractValidator<ParentClass>
{
    private string _errorCodePrefix = "ParentCode";

    public ParentValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithErrorCode($"{_errorCodePrefix}_NameEmpty");

        RuleFor(x => x.Child)
            .SetValidator(new ChildValidator());
    }
}

public class ChildValidator : AbstractValidator<ChildClass>
{
    private string _errorCodePrefix = "ChildCode";

    public ChildValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithErrorCode($"{_errorCodePrefix}_NameEmpty");
    }
}
```

Now, when Parent.Child.Name is null, I will get error code `ChildCode_NameEmpty`

What I want is `ParentCode_ChildCode_NameEmpty`

### Describe the solution you'd like

Of course, I can pass the `ParentCode` into the sub-validator as a construction parameter to achieve this function.

However, it's not very elegant.

I would like to know if there is a more convenient and automatic way to achieve this function? 

And, if not, will we consider adding this function to the new feature plan?

Thx.

**Comment by JeremySkinner** [comment]
Passing in via the constructor is the only way to do this. This isn’t something that we’ll be adding to the library, sorry.
