### ISSUE TITLE
Abstraction package for at least IRuleBuilder

### ISSUE THREAD

**Issue by wilkovanderveen** [FluentValidation/FluentValidation#2169]
### Is your feature request related to a problem? Please describe.

We are using fluent validation in 3 different projects (which are all nuget packages), and we need an extension on IRuleBuilder, for now I don't see any solution without wrapping the rulebuilder and everything needed.

Any other suggestions without having an abstraction package on your side?

### Describe the solution you'd like

An abstraction package would be nice

### Describe alternatives you've considered

wrapping the rulebuilder and everything needed.

**Comment by JeremySkinner** [comment]
No we have no plans to add this, sorry. Please reference the FluentValidation package directly.
