### ISSUE TITLE
Document Guidance on External Calls from Validations

### ISSUE THREAD

**Issue by bjsafdie** [FluentValidation/FluentValidation#2172]
### Is your feature request related to a problem? Please describe.

I am going back and forth on an aspect of our FluentValidation implementation. I can mostly validate everything discretely, only accessing an injected configuration object containing reference values/lookup lists. However, I have to call out to a repository for some values to get customer information about "grandfathered" values that may alter the validation. Thinking I should not "pollute" the validations with external calls, I implemented that check in the service layer outside our validation pipeline (a MediatR Pipeline Behavior).  
 
However, in researching the issue, I see Q&A where people deem making such external calls from a validator acceptable as long as they are constrained and do not move too much domain logic into the validator. My call to get the grandfathered value is done via a MediatR query, so I would only need to inject IMediator.  Thus, the validator would not be tightly coupled to a repository.
 
I like the idea of keeping all validations within the FluentValidation framework, and the automatic application of validation rules in the MediatR pipeline is an excellent approach. Still, I cannot decide if moving the MediatR query to access external data into the validations crosses a line we do not want to cross.

The documentation offers guidance and opinions on some topics, such as Dependent Rules. It would be very helpful if the authors also included a section providing advice on choices about making external calls from validators.
 

### Describe the solution you'd like

A section in the documentation that discusses the issues, considerations, and recommendations about making external calls from validators.

**Comment by JeremySkinner** [comment]
Hi, I can't really offer this kind of architectural guidance I'm afraid. These kinds of decisions are very much up to you and what makes most sense within the context of your application.
