### ISSUE TITLE
Receiving IEnumerable<ViewModel> from a [FromBody] in a Controller is not validated

### ISSUE THREAD

**Issue by joseph-salem** [FluentValidation/FluentValidation#2175]
### FluentValidation version

11.8.1

### ASP.NET version

.NET 6, .NET 8

### Summary

I created a Asp.NET Core Web Api project in .NET 6 and .NET 8. 

My goal was to be able to validate a IEnumerable received from a [FromBody] in a controller. I created 2 endpoints, one that receive the model as a single object and the second as a collection. The endpoint that receives the single object is able to validate the view model. The endpoint that receives the collection doesn't validate the list of view models. I tried many different solutions but nothing worked.

Below, you'll find the source code and the classes that I used in the projects.

Code that contain .NET 6 and .NET 8 projects
[FluentValidationExample.zip](https://github.com/FluentValidation/FluentValidation/files/13445187/FluentValidationExample.zip)

View Model:
```C#
public struct PersonViewModel
{
    public string Name { get; set; }
    public string Email { get; set; }
}
```

Validators:
```C#
public class PersonCollectionValidator : AbstractValidator<IEnumerable<PersonViewModel>>
{
    public PersonCollectionValidator()
    {
        RuleForEach(x => x).SetValidator(new PersonValidator());
    }
}

public class PersonValidator : AbstractValidator<PersonViewModel>
{
    public PersonValidator() {
        RuleFor(x => x.Name).NotNull().NotEmpty();
        RuleFor(x => x.Email).EmailAddress();
    }
}
```

Controller:
```C#
[ApiController]
[Route("persons")]
public class PersonController : Controller
{
    [HttpPost("/")]
    public PersonViewModel Post([FromBody] PersonViewModel personViewModel)
    {
        return personViewModel;
    }

    [HttpPost("/bulk")]
    public IEnumerable<PersonViewModel> Post([FromBody] IEnumerable<PersonViewModel> personViewModels)
    {
        return personViewModels;
    }
}
```

Program.cs:
```C#
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidationDotNet6.Validators;
using FluentValidationDotNet6.ViewModels;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddMvc();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddFluentValidationAutoValidation();

builder.Services.AddValidatorsFromAssemblyContaining<PersonViewModel>();
builder.Services.AddValidatorsFromAssemblyContaining<IEnumerable<PersonViewModel>>();

builder.Services.AddScoped<IValidator<PersonViewModel>, PersonValidator>();
builder.Services.AddScoped<IValidator<IEnumerable<PersonViewModel>>, PersonCollectionValidator>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

### Steps to Reproduce

1. Download the project that has been provided in the summary.
2. Build and Run the FluentValidationDotNet6 or FluentValidationDotNet8 project and a swagger web page will open.
3. Run the first endpoint with the default values and a email validation error will appear in the http response.
4. Run the second endpoint with the default values and no validation will be executed on the model.

**Comment by JeremySkinner** [comment]
This is expected. 

If you're using automatic validation with ASP.NET then the endpoint and validator must both be defined for `List<T>` not `IEnumerable<T>`. 

Internally ASP.NET always requests the validator for the *concrete* type of the controller action parameter. You should switch both the endpoint and the validator to `List<T>` and then it'll work. Please note this isn't an issue with FluentValidation - this how ASP.NET itself works and isn't an issue with FluentValidation.
