### ISSUE TITLE
Setting a message for a collection that is validated with a child validator.

### ISSUE THREAD

**Issue by JohanDelvaux** [FluentValidation/FluentValidation#2178]
### Is your feature request related to a problem? Please describe.

I would like to be able to do the following:
        RuleForEach(parent => parent.Children).SetValidator(new ChildValidator()).WithMessage("Child {CollectionIndex} is invalid. Message = {ChildValidatorMessage}.");

### Describe the solution you'd like

Now the WithMessage is ignored and I just see the message from the child.

**Comment by JohanDelvaux** [comment]
Hello Jeremy,

Thank you for your response.
I am indeed doing the validation in the child validator. My question concerns how I can adapt the message of the child validation so that it reflects which of the children has a problem. 
You already provide the possibility to use {CollectionIndex} for the standard validators, but this is not available when using child validators.
I can of course build up the message in the child itself and add some identification of the child (which is what I chose to do now), but I think some extra construct(s) could be useful here.

Best regards,
Johan

**Comment by JeremySkinner** [comment]
> You already provide the possibility to use {CollectionIndex} for the standard validators, but this is not available when using child validators.

This isn't the case. The `{CollectionIndex}` placeholder is accessible inside the child validator.
