### ISSUE TITLE
Move the `IValidationRule<T, TProperty>.SetDisplayName(string)` method to the `IValidationRule` interface.

### ISSUE THREAD

**Issue by GillesTourreau** [FluentValidation/FluentValidation#2179]
### Is your feature request related to a problem? Please describe.

When creating an inherited class from the `AbstractValidator<T>` it is not possible when overriding the `OnRuleAdded()` method, to change the display name of the property.

```csharp
protected override void OnRuleAdded(IValidationRule<T> rule)
{
    // Unable to change the display name using rule.SetDisplayName()
}
```

It is also not possible to cast the rule into the `IValidationRule<T, out TProperty>` because the `OnRuleAdded()` is called for each property to validate.

### Describe the solution you'd like

It will be great to move `IValidationRule<T, TProperty>.SetDisplayName(string)` method to the `IValidationRule` interface.

```csharp
protected override void OnRuleAdded(IValidationRule<T> rule)
{
    rule.SetDisplayName("My display name property");
}
```

### Describe alternatives you've considered

We can use reflection currently for this work around:

```csharp
protected override void OnRuleAdded(IValidationRule<T> rule)
{
    var setDisplayNameMethod = rule.GetType().GetMethod("SetDisplayName", new[] { typeof(string) })!;
    setDisplayNameMethod.Invoke(rule, new object[] { "My display name property" });
}
```

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. Seems like a reasonable idea, although it would need to wait until 12.0 as this is a breaking change.

**Comment by hogwartsdeveloper** [comment]
I would like to do it
