### ISSUE TITLE
Covariant IValidator<T> interface

### ISSUE THREAD

**Issue by dioptryk** [FluentValidation/FluentValidation#2180]
### Is your feature request related to a problem? Please describe.

Hello, I really like this library and am currently researching whether it would be a good match for my project, but when implementing a simple (apparently) prototype I almost immediately encountered a problem, due to polymorphic collections I have in abundance. 

Imagine two example classes: _Document_ and _SecretDocument_ (which extends the _Document_), both of which should be validated, also SecretDocument should inherit all the Documents' validation. If I were to implement validation directly on the type itself, then it would be as trivial as implementing a virtual `Validate()` method on the Document, overriding it on SecretDocument and that's it. Then the owner of `IEnumerable<Document>` collection could simply call Validate() on everything.

This is unfortunately not so easy with FluentValidation. My first idea was to have the objects implement a `virtual CreateValidator` method (returning `IValidator<Document>`), then the root object would do:

`RuleForEach(x => x.Documents).SetValidator((i, doc) => doc.CreateValidator());`

However this cannot be done. Why? Because IValidator is CONTRAVARIANT, instead of COVARIANT, so you can't cast `IValidator<SecretDocument>` to `IValidator<Document>`, but only the other way around, which is useless in this context.

### Describe the solution you'd like

I am not sure if it's possible with the current architecture of the library (smells like a definite breaking change), but making the `IValidator<T>` interface **_covariant_** would make many more nice things possible. For example, ugly stuff like `SetInheritanceValidator` would become completely obsolete.

I also tried `Include()` and additional contructor with an additional validator, but both fail due to missing covariance support.

### Describe alternatives you've considered

I _could_ use `SetInheritanceValidator` but I really do not like the idea. What if someone "forgets" adding a new type they created to the validator? Why not allow using polymorphism instead of implementing code that needs a priori knowledge about all the types?

**Comment by JeremySkinner** [comment]
> but making the IValidator<T> interface covariant would make many more nice things possible

No, this isn't possible. `IValidator<T>` is *intentionally* not covariant, as this would lead to runtime exceptions. If this was allowed, then the compiler let allow you to wire up validators for types that the validator can't act upon, which would then fail at runtime. 

The correct solution is to use SetInheritanceValidator - this requires you to specifically map which class is used by which validator. You should be using this in your scenario.
