### ISSUE TITLE
AddValidatorsFromAssembly not scanning internal classes

### ISSUE THREAD

**Issue by ericvdberge** [FluentValidation/FluentValidation#2181]
### FluentValidation version

11.8.1

### ASP.NET version

.NET 7

### Summary

To give a little context, I am building an API with the clean architecture.

The solution structure is:
- Application layer (Class library)
- Domain layer (Class library)
- Infrastructure layer (Class library)
- REST layer (Web Api)

I have an IServiceCollection extension method in my application layer called AddApplicationServices. A preview can be seen below:
``` cs
public static IServiceCollection AddApplicationServices(this IServiceCollection services)
{
    services.AddMediatR(options =>
        options.RegisterServicesFromAssembly(typeof(ApplicationExtensions).Assembly)
    );

    services.AddValidatorsFromAssembly(typeof(ApplicationExtensions).Assembly);
    services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));

    return services;
}
```
I am calling this extension method in the program.cs of the API project.

```cs 
/// <summary>
/// Add services from application layers
/// to the service collection
/// </summary>
services.AddApplicationServices();
```
The problem is that my Mediatr commands can be public (because they need to be referenced by the API project), but i want my validators to be internal, because no other layer needs access to the validators.

### Steps to Reproduce

Create a .NET 7 Web API and a .NET 7 class library within the same solution.
1. In the application layer (where all the use cases are located) you can create the applicationExtensions class that contains the function as mentioned in the summary.
2. In the API layer at program.cs, you can call the function as mentioned in the summary as well.
3. Setup a simple minimal API with mediatr in the API layer and place all the commands and queries in the application layer.
4. I also have a ValidationBehaviour that i use with mediatr to throw an exception when a validation error accurs.
```cs
public sealed class ValidationBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public ValidationBehaviour(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public async Task<TResponse> Handle(TRequest request, RequestHandlerDelegate<TResponse> next, CancellationToken cancellationToken)
    {
        var context = new ValidationContext<TRequest>(request);

        var failures = _validators
            .Select(v => v.Validate(context))
            .SelectMany(result => result.Errors)
            .Where(error => error != null)
            .ToList();

        if (failures.Any())
        {
            var failureMessages = string.Join("\n", failures.Select(failure => failure.ErrorMessage).ToList());
            throw new ValidationException(failureMessages);
        }

        return await next();
    }
}
```
5. I created a validation middleware in the API project that caches the validationException and creates a ProblemDetails result
6. **When the validator class and constructor are internal, the validator does not react to the request, but when they are public it will be catched by the AddValidatorsFromAssembly middleware**

**Comment by JeremySkinner** [comment]
You need to set the `includeInternalTypes` parameter:

```
services.AddValidatorsFromAssembly(typeof(ApplicationExtensions).Assembly, includeInternalTypes: true);
```

Without this, internal types won't be scanned. This is the default behaviour as internal types aren't part of an assembly's public API and shouldn't be included, unless specifically opted in.
