### ISSUE TITLE
When condition is not triggered or does not prohibit rules to be executed inside custom RuleBuilder extensions method

### ISSUE THREAD

**Issue by kostas-kapasakis** [FluentValidation/FluentValidation#2186]
### FluentValidation version

11.7.1

### ASP.NET version

7

### Summary

When condition is not triggered or does not block rule from executing during a custom validation extension method and even if the rule should not be triggered , it ignores the condition result if its run and executed regardless.

### Steps to Reproduce

1) Create a custom validation extension
2) Use when condition with ApplyConditionTo.CurrentValidator for rules
3) All rules are executed even if some conditions return false

        public static IRuleBuilderOptions<T,TProperty>  ExistsInPayloadWithValue<T, TProperty>
           (this IRuleBuilder<T, TProperty> ruleBuilder)
            {
                return ruleBuilder
                   .ExistsInPayload()
                   .When((_, context) => Condition(context), ApplyConditionTo.CurrentValidator)
                   .PayloadNotNull()
                   .When((_, context) => Condition1(context), ApplyConditionTo.CurrentValidator)
                   .PayloadNotEmpty()
                   .When((_, context) => Condition2(context_, ApplyConditionTo.CurrentValidator);
              }

ExistsInPayload
PayloadNotNull
PayloadNotEmpty
are other custom validation extensions in the same extension class that return IRuleBuilderOptions<T,TProperty>

**Comment by JeremySkinner** [comment]
Please provide full steps to reproduce the issue in the form of a runnable unit test, as was requested in the issue template.
