### ISSUE TITLE
Add ability to both throw on validation error and include root context data

### ISSUE THREAD

**Issue by ww2406** [FluentValidation/FluentValidation#2190]
### Is your feature request related to a problem? Please describe.

Right now, there is no effective way within FluentValidator to combine the ValidateAndThrow behavior with root context data without manually throwing an exception.

### Describe the solution you'd like

I'd like to have some mechanism either through configuring the validation context or using the validation strategy to configure root context data. I'd be happy to contribute to make this happen, but wasn't sure if you have a preference for either approach or another approach.

**Comment by JeremySkinner** [comment]
This is already supported:

```csharp
var instanceToValidate = new Person();
var context = ValidationContext<Person>.CreateWithOptions(instanceToValidate, options => {
	options.ThrowOnFailures();
});
context.RootContextData.Add("Foo", "bar");
validator.Validate(context);
```
