### ISSUE TITLE
List all possible validator names

### ISSUE THREAD

**Issue by huysentruitw** [FluentValidation/FluentValidation#2194]
### Is your feature request related to a problem? Please describe.

In an application, we would require a list of all possible validator names, to make sure we have translations for every possible validation error. We save a snapshot of that in a unit-test, so we could detect new/changed validation names in future FluentValidation updates.

### Describe the solution you'd like

The solution could be a static class that contains all known validator names. F.e:

```
public static class KnownValidatorNames
{
    public const string GreaterThanValidator = "GreaterThanValidator";

    // ...
}
```

### Describe alternatives you've considered

I've tried to create such list and snapshot it in our tests using the following reflection code:

```C#
private static IEnumerable<string> EnumFluentValidationErrors()
{
    var propertyValidatorType = typeof(IPropertyValidator);
    var fluentValidationAssembly = propertyValidatorType.Assembly;
    var types = fluentValidationAssembly.GetTypes()
        .Where(type => type.IsAssignableTo(propertyValidatorType)
                       && !type.IsAbstract
                       && !type.IsAssignableTo(typeof(IChildValidatorAdaptor))
                       && type.GetConstructor(Array.Empty<Type>()) is not null);

    return types.Select(type =>
    {
        if (type.GetGenericArguments().Length == 2)
            type = type.MakeGenericType(typeof(object), typeof(string));
        else
            type = type.MakeGenericType(typeof(object));
        var nameProperty = type.GetProperty("Name", BindingFlags.Public | BindingFlags.Instance);
        return nameProperty?.GetValue(Activator.CreateInstance(type)) as string ?? type.Name;
    });
}
```

But as you can see, that's not really maintainable. Would be easier if we could just enumerate static fields from a single static type.

### Additional Context

If this is something you wouldn't mind adding to the library, I'm willing to create a PR for it of course.

**Comment by JeremySkinner** [comment]
I'd suggest just hard-coding the list - [this is what we do in our own tests](https://github.com/FluentValidation/FluentValidation/blob/a796e460fff7339bc686e146d70cc94811f15be5/src/FluentValidation.Tests/LanguageManagerTests.cs#L153). We have no plans to add any more built-in validators to the core library, so this is safe to do.

**Comment by huysentruitw** [comment]
Ok clear. Thanks!
