### ISSUE TITLE
Register File/Internal Scoped Validators

### ISSUE THREAD

**Issue by arex388** [FluentValidation/FluentValidation#2202]
### Describe the solution you'd like

Apologies if this has been answered before. I tried looking for issues about internal validators, but didn't see anything that stood out.

I am exploring enhancements to how I structure my vertical slices in my project. One of the things I've started leveraging is `file` scoped classes. This works seamlessly with MediatR and AutoMapper, but FluentValidation requires that the the validators be public, so it throws a wrench in my intentions. For now I'm getting around it by declaring the classes the way I have been, but would like to see `file` scoped classes also be allowed for registration. From what I can tell, they're compiled to `internal`, so I guess I'm really asking for `internal` to be allowed for registration?

### Current Structure

```c#
public static class Add {
  public sealed class Command : IRequest;
  public sealed class CommandValidator : AbstractValidator<Command>;
}

file sealed class CommandHandler : IRequestHandler<Command>;
```

### Enhanced Structure

```c#
public static class Add {
  public sealed class Command : IRequest;
}

file sealed class CommandHandler : IRequestHandler<Command>;

file sealed class CommandValidator : AbstractValidator<Add.Command>;
```

I register the validators using `AddValidatorsFromAssemblyContaining<T>()`.

Thank you for your time in considering this request.

**Comment by JeremySkinner** [comment]
[#2181](https://github.com/FluentValidation/FluentValidation/issues/2181#issuecomment-1851689843)

```
services.AddValidatorsFromAssemblyContaining<MyValidator>(includeInternalTypes: true);
```
