### ISSUE TITLE
`ValidationStrategy.IncludeSeverity(Severity)`

### ISSUE THREAD

**Issue by space-alien** [FluentValidation/FluentValidation#2204]
### Describe the solution you'd like

I would like to be able to validate only the rules with `Severity.Error`, thus skipping any rules that produce warnings, etc.

For example:

```csharp
var vr = validator.Validate(request, options => options.IncludeSeverity(Severity.Error));
```

### Describe alternatives you've considered

I imagine I could manually target warning-producing rules by creating RuleSets or perhaps by including properties by name, but either approach creates a maintainability/overhead concern.

I explored the possibility of using `UseCustomSelector(IValidatorSelector)` but a rule's `Severity` is not available that way.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't something we'll be including.

Severity is not defined at the rule-level, but rather at the component level, and is intended to only be resolved at the point when a validation failure is generated, ie this is failure-level metadata not rule-level metadata. 

You'd probably be better off using rulesets to achieve what you want. https://docs.fluentvalidation.net/en/latest/rulesets.html
