### ISSUE TITLE
Generate JSON Schema from fluent validation

### ISSUE THREAD

**Issue by neotrow** [FluentValidation/FluentValidation#2208]
### Is your feature request related to a problem? Please describe.

We generate an openapi spec with nswag. This is great because we can also generate some zod schemas based on that for our frontend. It's a huge plus if we can have server and client side validation linked together. It solves the issue of having to code it twice and also makes it easier to update it. 

But of course openapi has some limitations. For simple validations it works well but for more complex cases like "if this field has this value, than this field is required" it doesn't work.

### Describe the solution you'd like

JSON Schema probably also doens't support all cases that fluent validation does but it could at least generate it for those that it does. 

For eample in JSON Schema we could have:
```
{
  "$id": "https://example.com/conditional-validation-dependentRequired.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Conditional Validation with dependentRequired",
  "type": "object",
  "properties": {
    "foo": {
      "type": "boolean"
    },
    "bar": {
      "type": "string"
    }
  },
  "dependentRequired": {
    "foo": ["bar"]
  }
}
```

Which could be generated from something like this:
```
RuleFor(x => x.Surname).NotNull().DependentRules(() => {
  RuleFor(x => x.Forename).NotNull();
});
```

I was wondering if it would be possible to generate json schemas (https://json-schema.org/) from the fluent validation configs? 
I am not an expert at all on this topic but I think through reflections it should be possible?

**Comment by JeremySkinner** [comment]
Every validator exposes its internal rule model, which you can interrogate to see what rules a validator contains. 

```
var validator = new MyValidator();
foreach (var rule in validator) {
  // Loops through all rules defined in the validator.
  // This gives you a reference to each rule chain.
 foreach (var component in rule.Components) {
   // Loop through each component inside the rule. 
   // For example, RuleFor(x => x.Foo).NotNull().NotEqual("bar") is a rule with 2 components
   if (component.Validator is INotNullValidator) {
     // Can check for specific individual property validators. 
   } 
 }
} 
```

Producing a json model is something that's not in scope for this project, but inspecting this structure would be your starting point if you wanted to do it yourself. 

There's a 3rd party library (https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation) that makes use of this for swagger integration, maybe take a look at that.
