### ISSUE TITLE
Add support for validating arbitrary property values without a model instance

### ISSUE THREAD

**Issue by DaRosenberg** [FluentValidation/FluentValidation#2210]
### Is your feature request related to a problem? Please describe.

We'd like to use FluentValidation for a rather large greenfield API.

For many resources this API will support PATCH endpoints, where client can pass in a partial payload of some request type `TRequest`, which will deserialize into a dictionary. Deserializing into `TRequest` is not feasible as the .NET type system lacks the ability to distinguishe between a property being missing/undefined, and a property having its default value (i.e. there is no equivalent of JavaScript's `undefined` vs. `null`).

Upon receiving the request and validating it, the endpoint then loads a corresponding entity of type `TEntity` from the database and dynamically applies the values from the dictionary.

In POST and PUT endpoints, things are easy. We deserialize into `TRequest` and validate the deserialized instance.

In PATCH endpoints it's trickier. Since we don't have an instance of `TRequest`, we would like to instead validate property by property, but still using the validator of `TRequest`. However we have not been able to find any support for this in the API surface of FluentValidation. (The `System.ComponentModel.DataAnnotations` namespace supports this, but we'd prefer to use FluentValidation if possible, for various other reasons.)

Note that the database type `TEntity` is not the same as the request model `TRequest`. We do not want to create FluentValidation validators for our database entity types - only for our API request models. As a matter of hygiene and separation of concerns, these are separate layers, and we want to validate the incoming request before we go off and fetch an entity from the database.

### Describe the solution you'd like

Given this validator:

```cs
public class WorkspaceValidator : AbstractValidator<Workspace>
{
    public WorkspaceValidator()
    {
        RuleFor(x => x.Name).NotEmpty().MaximumLength(512);
    }
}
```

We'd like to be able to do the following:

```cs
var validator = new WorkspaceValidator();

// Validate an instance (this we can already do)
var item = new Workspace(createdByUserId: null) { Name = "SomeWorkspace" };
validator.Validate(workspace);

// Validate an arbitrary value identified by lambda:
validator.ValidateValue(x => x.Name, value: "SomeWorkspace");

// Validate an arbitrary value identified by name:
validator.ValidateValue("Name", value: "SomeWorkspace");
validator.ValidateValue(nameof(Workspace.Name), value: "SomeWorkspace");

// Validate a set of arbitrary values represented as a dictionary:
var values = new Dictionary<string, object>() {	["Name"] = "SomeWorkspace" };
validator.ValidateValues(values)
```

New members could maybe defined something like this:

```cs
public interface IValidator<T> : IValidator
{
    // ...

    ValidationResult ValidateValue<TProperty>(Expression<Func<T, TProperty>> expression, TProperty? value);
    ValidationResult ValidateValue<TProperty>(string propertyName, TProperty? value);
    ValidationResult ValidateValues(IEnumerable<KeyValuePair<string, object?>> values);
}
```

### Describe alternatives you've considered

We're aware of this feature:
https://docs.fluentvalidation.net/en/latest/specific-properties.html

But that's for a different purpose, as it still requires an instance of the model type to validate, it simply limits the validation of that instance to a subset of properties.

Only alternative solution considered is to use `System.ComponentModel.DataAnnotations` instead.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this is out of scope of the library. The entire purpose of FluentValidation is to validate properties of objects, not individual values. You'd be better off looking elsewhere if this is a hard requirement for you.
