### ISSUE TITLE
I would like to add a way of Unit Testing Children Validators.

### ISSUE THREAD

**Issue by rsibanez89** [FluentValidation/FluentValidation#2212]
### Unit Testing feature request: Test that  Children Validators are called without having to run the whole set of nested validators.

I'm trying to find a way of unit testing my conditional children validators.

In this example, I got a condition that will setup a different child validator based on the condition.

```
public enum BookingCountry
{
    US,
    ROW
}

public class Booking
{
    public string Date { get; set; }
    public BookingCountry Country { get; set; }
}

public class USDateValidator : AbstractValidator<string>
{
    public USDateValidator()
    {
        RuleFor(x => x)
            .Must(x => DateTime.TryParse(x, new CultureInfo("en-US", false), out _))
            .WithMessage("Date is not in US format");
    }
}

public class ROWDateValidator : AbstractValidator<string>
{
    public ROWDateValidator()
    {
        RuleFor(x => x)
            .Must(x => DateTime.TryParse(x, new CultureInfo("en-AU", false), out _))
            .WithMessage("Date is not in ROW format");
    }
}

public class BookingValidator : AbstractValidator<Booking>
{
    public BookingValidator(IValidator<string> usValidator, IValidator<string> rowValidator) {
        RuleFor(x => x.Date)
            .SetValidator(usValidator)
            .When(x => x.Country == BookingCountry.US);
        RuleFor(x => x.Date)
            .SetValidator(rowValidator)
            .When(x => x.Country == BookingCountry.ROW);
    }
}

[Fact]
public async Task Validate_Right_Validator_Is_Setup_For_Each_Country()
{
    var usValidator = new Mock<USDateValidator>();
    var rowValidator = new Mock<ROWDateValidator>();
    var validator = new BookingValidator(usValidator.Object, rowValidator.Object);

    validator.ShouldHaveChildValidator(b => b.Date, typeof(USDateValidator)); // True
    validator.ShouldHaveChildValidator(b => b.Date, typeof(ROWDateValidator)); // True
}
```

### Describe the solution you'd like

I would like to be able to do something like this:
```
[Fact]
public async Task Validate_Right_Validator_Is_Setup_For_Each_Country()
{
    var usValidator = new Mock<USDateValidator>();
    var rowValidator = new Mock<ROWDateValidator>();
    var validator = new BookingValidator(usValidator.Object, rowValidator.Object);

    var booking = new Booking { Country = BookingCountry.US };
    var result = validator.Validate(booking);

    // Something where I can verify one of the Mocks was called.
    usValidator.Verify(v => v.Validate(It.IsAny<string>()), Times.Exactly(1));
    rowValidator.Verify(v => v.Validate(It.IsAny<string>()), Times.Never);

    // Or
    validator.ShouldHaveChildValidator(b => b.Date, typeof(USDateValidator)).When(condition); // True
    validator.ShouldHaveChildValidator(b => b.Date, typeof(ROWDateValidator)).When(condition);; // False
}
```

### Describe alternatives you've considered

I know this is a small example and I could just put everything in one single validator.
My real case is way bigger, with several nesting child validations, and I was hoping to be able to unit test it.

I've seen this issue: https://github.com/FluentValidation/FluentValidation/issues/1115
And also this page where you recommend not using Mock. https://docs.fluentvalidation.net/en/latest/testing.html

However, if I don't use mocks how can I create unit tests?
I don't want to test the whole set of nesting dependencies for each of my objets, I just want to test each level individually.

### Additional Context

Thanks

**Comment by JeremySkinner** [comment]
This isn't the correct approach for testing validators. As mentioned in the documentation page you linked to, you should treat validators as black boxes - create your tests around expected output not around expected interactions. 

I would recommend treating the parent validator as a single unit - your application will be invoking the parent validator, not the child, and acting upon the result, so your tests should replicate this. Treat the booking validator as a black box and supply it with valid/invalid input. Whether the validation failures are created by the parent validator or the child validator really isn't relevant - the correct place for testing the logic is in the tests for the parent as this is what your application will be invoking.

However, if you really want to split it up, don't use a mocking library - use `InlineValidator` instead  as it doesn't require you to make assumptions about how validators work internally. Using InlineValidator creates a stub that can then supply a specific result which you would then assert against:

```
[Fact]
public async Task Validate_Right_Validator_Is_Setup_For_Each_Country()
{
	var usValidator = new InlineValidator<string>();
	usValidator.RuleFor(x => x).Must(x => false).WithMessage("US failed");

	var rowValidator = new InlineValidator<string>();
	rowValidator.RuleFor(x => x).Must(x => false).WithMessage("ROW failed");

	var validator = new BookingValidator(usValidator, rowValidator);

	var booking = new Booking { Country = BookingCountry.US, Date = "foo" };
	var result = await validator.ValidateAsync(booking);

	Assert.Equal(1, result.Errors.Count);
	Assert.Equal("US failed", result.Errors[0].ErrorMessage);
}

```

That being said, my recommendation would be not to do this, and use a black box approach as mentioned above.
