### ISSUE TITLE
Allow service provider access in DisplayNameResolver

### ISSUE THREAD

**Issue by chrischu** [FluentValidation/FluentValidation#2218]
### Is your feature request related to a problem? Please describe.

I would like to automatically translate all the property names in my validation messages. I tried using `ValidatorOptions.Global.DisplayNameResolver` but unfortunately I do not  have access to a service provider instance in there and therefore cannot resolve a `IStringLocalizer<T>` instance.

### Describe the solution you'd like

I would love if I would have access to an `IServiceProvider` instance in the `DisplayNameResolver`.

### Describe alternatives you've considered

I know the official way is to just add `.WithName(localizer[nameof(Property)])` to my rules, but this seems very tedious and can be easily forgotten.

### Additional Context

I'm using FluentValidation in version 11.9.1.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't something we'll be implementing as the global display name resolver has no way to get access to the current service provider, so it isn't something that can be passed to the callback. The correct way of handling this is to inject the `IStringLocalizer` into your validator's constructor, and then use the overload of `WithName` that supports a callback: `WithName(x => localizer["some property"])`
