### ISSUE TITLE
Based FluentValidation, extend some validators.

### ISSUE THREAD

**Issue by kelilive** [FluentValidation/FluentValidation#2221]
### Is your feature request related to a problem? Please describe.

I hope there is a simpler and more general solution for some common validations, avoiding writing a lot of messages to implement validation.

### Describe the solution you'd like

Expand some validators based on C# FluentValidation.

Add expression tree to expand support. But there will be a problem that the expression contains custom methods. At this time, you can solve it by bringing out the method name.

Add comparison validator. Implement value comparison between member objects.

Add regular validator. Expand email validator (must contain @ symbol, email can only use numbers and letters as name) Mobile phone validator (11 digits) User name validator (can only contain numbers and letters).

**Comment by JeremySkinner** [comment]
Our list of default, built-in validators is documented here: https://docs.fluentvalidation.net/en/latest/built-in-validators.html
