### ISSUE TITLE
Multi-language display problem

### ISSUE THREAD

**Issue by kelilive** [FluentValidation/FluentValidation#2222]
### FluentValidation version

11.9.1

### Summary

In the development of AutoCAD plug-ins, I found that it is necessary to use powerful settings to make the display language effective. 

```
// it's ok
ValidatorOptions.Global.LanguageManager.Culture = new CultureInfo(languageName);

// local message text can only be displayed normally in regular projects
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo(languageName);
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo(languageName);
```
   

### Steps to Reproduce

If you are familiar with AutoCAD operations, you can try to write a simple case to test it. It seems that it is not so troublesome to set up a regular project with a dedicated API.

**Comment by JeremySkinner** [comment]
I don't understand what you're asking.

By default, FluentValidation uses the current UI culture for displaying messages (`CultureInfo.CurrentUICulture`). Setting `ValidatorOptions.Global.LanguageManager.Culture` overrides this.

**Comment by kelilive** [comment]
I kind of understand it, but it doesn't work when I set the region, in an AutoCAD plugin development project.
I had to use `ValidatorOptions.Global.LanguageManager.Culture` to do it.

**Comment by JeremySkinner** [comment]
FluentValidation uses `CultureInfo.CurrentUICulture` directly [as you can see here](https://github.com/FluentValidation/FluentValidation/blob/95081c419d76f427a210f617eb7e0cee88c848ce/src/FluentValidation/Resources/LanguageManager.cs#L127), if it's not working then that isn't an issue with FluentValidation. I can't help you with AutoCAD as I don't know anything about that.
