### ISSUE TITLE
Improve Custom Validator Support by exposing some internal helpers

### ISSUE THREAD

**Issue by Euan-McVie** [FluentValidation/FluentValidation#2224]
### Is your feature request related to a problem? Please describe.

We have a custom validator created using:

```cs
public static IRuleBuilderOptions<T, IEnumerable<TElement>> BeDistinctBy<T, TElement, TChildElement>(
    this IRuleBuilder<T, IEnumerable<TElement>> ruleBuilder,
    Expression<Func<TElement, IEnumerable<TChildElement>>> childSelector)
{
    return ruleBuilder
        .Must((_, elements, context) =>
        {
            if (elements is null)
                return true;

            var member = childSelector.GetMember();
            var compiledSelector = AccessorCache<TElement>.GetCachedAccessor(member, childSelector);

            context.MessageFormatter.AppendArgument("ChildPropertyName", member.Name.SplitPascalCase());

            return elements.SelectMany(compiledSelector).Distinct().Count() == elements.SelectMany(compiledSelector).Count();
        })
        .WithMessage("'{PropertyName}' must contain only items that are distinct by '{ChildPropertyName}'.");
}
```

The ability to reuse the `GetMember` and `AccessorCache` that `RuleFor` use were particularly useful. 👍 
The only flaw is that `SplitPascalCase` is not public and so I've had to take a copy.

Great library we've been using for years.
Many Thanks
Euan

### Describe the solution you'd like

Make the `SplitPascalCase` public to enable reuse of the same property name logic as the `PropertyName` already uses.
The other side effect is the reduction of maintenance on our side to keep its behaviour aligned in the unlikely event it were to change in the future.

I'm pretty sure the `BeDistinctBy` use case on a collection is not common enough to warrant addition to the library, but feel free to clone the approach if you decide it is.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this isn't something we'll be implementing. Internal helpers like this are subject to change at any time and aren't something we make available in our public API, which is focused on validation. As this is a string utility it's outside of the scope of the public API for this library.
