### ISSUE TITLE
FormattedMessagePlaceholderValues[PropertyName]

### ISSUE THREAD

**Issue by xbikuna** [FluentValidation/FluentValidation#2226]
### FluentValidation version

11.9.2

### Summary

When migrating from 11.7.1 there has been an issue on the code (or at least in my code),
the point is that with complex structure validations (with multiple leves), on FormattedMessagePlaceholderValues[PropertyName] the name that was stored was the real property name, but current versions are storing the Pretty property Name (with spaces) so the Error Provider is not working property as the error property names do not match.

It will be interesting to have PropertyName as is, and also PrettyName if some feature needs in FormattedMessagePlaceholderValues[] dictionary, as FormattedMessagePlaceholderValues[Path] gives you the full path but you got no chance to get the real PropertyName 

Thanks in advance

### Steps to Reproduce

1. create a validator that uses a validator y a 2 level class structure, validate it having an error on the second level validator

Order
     OrderLine
             Id
             Price

**Comment by JeremySkinner** [comment]
Hi, thanks for getting in touch but this is the correct behaviour.

The `FormattedMessagePlaceholderValues` dictionary holds always contains the same values that were used to format the error message. The `{PropertyName}` placeholder is always the pretty name, as this is the value that's used when constructing the error message, and so it will be the same in the dictionary.

If you want the 'real' property name you should look at the path instead (or the `PropertyName` property on the `ValidationFailure`). Split this using `.` as a delimiter to get the 'real' property name.

**Comment by xbikuna** [comment]
Hi Jeremy:

                Thanks for this quick answer, As you said this is what I made (split (‘.’) path) to solve the issue, but I will say that in previous version I was using (or at least on my tests) I thought PropetyName was the real property name, (or even there was a bug on that version)
but if you say that PrettyName is OK, It’s OK and you can close this issue, I notified just in case it was a bug… But probably it was a bad understanding of myself.

                Thanks in advance


De: Jeremy Skinner ***@***.***>
Enviado el: jueves, 20 de junio de 2024 14:47
Para: FluentValidation/FluentValidation ***@***.***>
CC: Xabi Bikuña Losada ***@***.***>; Author ***@***.***>
Asunto: Re: [FluentValidation/FluentValidation] FormattedMessagePlaceholderValues[PropertyName] (Issue #2226)


Hi, thanks for getting in touch but this is the correct behaviour.

The FormattedMessagePlaceholderValues dictionary holds always contains the same values that were used to format the error message. The {PropertyName} placeholder is always the pretty name, as this is the value that's used when constructing the error message, and so it will be the same in the dictionary.

If you want the 'real' property name you should look at the path instead (or the PropertyName property on the ValidationFailure). Split this using . as a delimiter to get the 'real' property name.
