### ISSUE TITLE
Rules for when validation context is (not) asyncronous

### ISSUE THREAD

**Issue by 82amp** [FluentValidation/FluentValidation#2230]
### Is your feature request related to a problem? Please describe.

When calling Validate() on validators that contain a `MustAsync`, `WhenAsync`, etc., for example, when the ASP.Net pipeline runs.

### Describe the solution you'd like

Ability to define rules that will only be executed when `context.IsAsync` is true (or false). A few different syntaxes have been given in the code example section

Or, ability to access validation context from within rule definitions

Or, ability to configure a validator to opt into the new functionality, e.g. at the constructor level, like `Class/RuleLevelCascadeMode` (which would then also support inheritence, DI, etc), or possibly via interface flagging, inheritence, etc.

Configurations: 
- All = current behaviour - attempts to run all rules whether invoked syncronously or asyncronously
- ExactMatch = if invoked syncronously, only runs syncronous rules, if invoked asyncronously, only runs async rules
- SyncOnAsync = if invoked syncronously, will only run syncronous rules. If invoked asyncronously, will invoke sync and async rules 

Some considerstion would need to be given for how nested rules work, i.e. a validator that includes a sub-validator, but has different syncronisation matching configuration.

### Describe alternatives you've considered

Having separate validators for different purposes, and including the "syncronous validator" from the "asyncronous validator". This splits the logic for the thing being validated into multiple places.

```csharp
public class SimpleValidator : AbstractValidator<Foo>
{
  public SimpleValidator() {
    RuleFor(x => x.Email).EmailAddress();
  }
}

public class ComplexValidator : SimpleValidator
{
  public ComplexValidator() {
    RuleFor(x => x.Email).MustBeUniqueAsync()
  }
}
```

Overriding `Validate(Async)` (in a base class?) to expose the validation context, allowing rules to consume it. This feels very, very hacky, and is not thread safe, meaning singleton/shared validator instances will have race conditions. 

```csharp

public class MyValidator : AbstractValidator<Foo>
{
 ValidationContext<Foo> Context {get;set;}
 override Validate(context) { Context = context; return base.Validate(context); }
 override ValidateAsync(context, ct) { Context = context; return base.ValidateAsync(context, ct); }

  public MyValidator () {
  When(_ => Context.IsAsync, () => {
    RuleFor(x => x.Email).MustBeUniqueAsync()
  });
}

```

Having a mediated object for validation, which contains the context as a property, but as identified in other issues in this repo, that mixes model validation. 

### Additional Context

```csharp

public class FooValidator : AbstractValidator<Foo> {
 MyValidator(IService service)
  {  
    // multiple rules together:
    OnlyWhenAsync(() => {
      RuleFor(x => x.Bar)
      .Must(bar => bar == "executed asyncronously")  
      .MustAsync(async (bar, ct) => { return await service.CheckSomething(bar, ct); }) 

    OnlyWhenSync(() => {
      RuleFor(x => x.Bar)
        .Must(bar => bar == "something")  
   });    

// additional parameter for each of the Async methods (and possibly the sync methods)
// Sync always runs when sync, Async always runs when async, but can exclude Async from sync calls (and vice versa, but probably let sync calls still run when async)
    RuleFor(x => Bar)
      .Must(bar => bar == "invoked syncronously", ContextSyncronisation.SyncOnly)
      .Must(bar => bar == "invoked asyncronously", ContextSyncronisation.AsyncOnly)
      .MustAsync(async (bar, ct) => await service.CheckSomething(bar,ct), ContextSyncronisation.AsyncOnly) // only called when invoked with ValidateAsync
      .MustAsync(async (bar, ct) => await service.CheckSomething(bar,ct), ContextSyncronisation.All) // current behaviour, will throw exception if invoked syncronously

// per property, add additional methods for each of the "Async" methods
// makes API messier
     RuleFor(x => x.Bar)
      .Must(bar => bar == "something")  // always runs
      .MustIfContextIsAsync(async (bar, ct) => { return await service.CheckSomething(bar, ct); }) // only runs when ValidateAsync
  }
}

// alternatively, just configure the validator to behave in a particular way without changing the syntax / call hierarchy. This would make reusing existing code easier.
public class FooValidator : AbstractValidator<Foo> {
 MyValidator(IService service)
  {  
      // as a property exposed on base class perhaps?
     MatchContextSyncronisation =  ContextSyncronisation.SyncOnAsync // or ContextSyncronisation.ExactMatch, or ContextSyncronisation.All (default behaviour)
     RuleFor(x => x.Bar)
      .Must(bar => bar == "something") 
      .MustAsync(async (bar, ct) => { return await service.CheckSomething(bar, ct); })
  }
}


var foo = new Foo("something")
var validator = new FooValidator(...);

validator.Validate(foo) // will pass, as the sync rule passes and async rule not executed
validator.ValidateAsync(foo) // will pass or fail depending on outcome of service.CheckSomething

```

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this isn't something we'll be including - this kind of mixing sync & async rules is intentionally not something we want to support.

If a validator contains async rules then it should always be called with `ValidateAsync` and if you try to invoke it synchronously then it will throw an exception as this makes it very clear to the developer that something has been set up incorrectly. 

If your codebase includes asynchronous rules then you should always invoke your validators asynchronously. Synchronous validator execution is considered legacy and a mix/match approach (which we've experimented with before) leads to confusion. Ensuring asynchronous validators are not invoked synchronously was a conscious design choice and I'm afraid this isn't something we'll be allowing. 

(We no longer support the ASP.NET validation pipeline due to it being sync-only, and recommend injecting validators directly into your controllers and invoking them directly with `ValidateAsync` - see https://docs.fluentvalidation.net/en/latest/aspnet.html)
