### ISSUE TITLE
Problem with chained validation rules

### ISSUE THREAD

**Issue by Skuzzle-UK** [FluentValidation/FluentValidation#2236]
### FluentValidation version

11.9.0

### ASP.NET version

,NET 8.0

### Summary

This may be the intended functionality but it feels wrong and caused problems which required debug. When chaining multiple rules some rules were skipped and not validated.

### Steps to Reproduce

Create validation rule as follows:

```
RuleFor(x => x.EndTime)
    .NotNull()
    .WithMessage($"{nameof(Scheduled.EndTime)} can't be null")

    .NotEmpty()
    .WithMessage($"{nameof(Scheduled.EndTime)} can't be empty");

RuleFor(x => x.EndTime)
    .Must(BeValidDateTime)
    .When(x => !string.IsNullOrWhiteSpace(x.EndTime))
    .WithMessage($"{nameof(Scheduled.EndTime)} must be a valid datetime");
```

Note that I have had to use RuleFor(x => x.EndTime) twice. If I try the following it skips the not null and not empty rules completely but still validates against the BeValidDateTime bool:

```
RuleFor(x => x.EndTime)
    .NotNull()
    .WithMessage($"{nameof(Scheduled.EndTime)} can't be null")

    .NotEmpty()
    .WithMessage($"{nameof(Scheduled.EndTime)} can't be empty")

    .Must(BeValidDateTime)
    .When(x => !string.IsNullOrWhiteSpace(x.EndTime))
    .WithMessage($"{nameof(Scheduled.EndTime)} must be a valid datetime");
```

The code compiles fine in both situations without warnings but the validations don't work as intended.

**Comment by JeremySkinner** [comment]
By default, using a `When` method applies the condition to *all preceding components in the same rule chain*, so if the condition isn't met then they will be skipped. 

You can change this behaviour by passing `ApplyConditionTo.CurrentValidator` as the second parameter of the `When` method. This will ensure the condition only applies to the component that immediately precedres the conditoon.

Please review this section of the documentation which covers this: https://docs.fluentvalidation.net/en/latest/conditions.html
