### ISSUE TITLE
FluentValidation to Python

### ISSUE THREAD

**Issue by p-hzamora** [FluentValidation/FluentValidation#2237]
### Is your feature request related to a problem? Please describe.

Hi Jeremy,

A few month ago, I found myself needing to use FluentValidation in Python for an ORM project I'm developing. The problem was that there wasn't a library like FluentValidation available for that lenguage, so I decided to replicate your code in Python. I aimed to maintain all the lines of code by applying Python's inheritance techniques and ensuring that all variables are typed to make the user experience as similar to C# as posible.

I've been replicating your library to enable basic validation operations along with the options to validate specific properties.

Although there are still many features left to implement, I've replicated the tests that I could so far to ensure thateverything works as you intented.

The library is published at [fluent_validation](https://pypi.org/project/fluent_validation/), and I would love to hear your thoughts on it.

 If you agree, it would be great to give it some visibility so that other developers can join the project.

Thank you very much in advance.

### Describe the solution you'd like

.

**Comment by JeremySkinner** [comment]
I don't have any experience with Python so I can't really comment on it I'm afraid, but so long as you're abiding by the project's license then I don't see any issue with this, and I'm glad my work has been able to serve as an inspiration for you.
