### ISSUE TITLE
Introspection for Conditions

### ISSUE THREAD

**Issue by jonathanantoine** [FluentValidation/FluentValidation#2242]
### Describe the solution you'd like

I am in the process of providing the fluent validation rules to a SPA (Angular) application.
I would like to send out conditions when this is simple one ( Property == true for instance).

I would like to be able to access the condition but for now, this seems buried inside a private class (RuleComponent<,>).

Is there a way to get this information ?

Thanks.

**Comment by JeremySkinner** [comment]
No, sorry, this isn't something we plan to support.
