### ISSUE TITLE
Expose the Enum Type in EnumValidator.

### ISSUE THREAD

**Issue by jonathanantoine** [FluentValidation/FluentValidation#2243]
### Is your feature request related to a problem? Please describe.

I am trying to export fluent validation rules in another format (json schema, custom, etc.)

### Describe the solution you'd like

I would like EnumValidator<> to implement a new IEnumValidator interface exposing the target enum type.

### Describe alternatives you've considered

Using reflection and  the field name.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. This seems like a reasonable enhancement, which I'd be happy to add. If you'd like to submit a PR I'll give it a review.

That being said I will point out that FluentValidation is explicitly *not* intended to be something whose rules are exportable. If you are trying to do this to have 1 set of rules across client and server I highly, highly recommend not doing this. You are better off having rules defined distinctly in each platform.

**Comment by jonathanantoine** [comment]
Thank you for being open to this idea. I have implemented the PR #2244
