### ISSUE TITLE
When using WithMessage() the message defined is ignored

### ISSUE THREAD

**Issue by Bond-Addict** [FluentValidation/FluentValidation#2246]
### FluentValidation version

11.9.1

### ASP.NET version

Dotnet 8

### Summary

When using the .WithMessage() function the message defined is not used.
In the example below, the rendered message is 'First Name' cannot be blank.
The difference is that in my custom message I do not have any ``'`` marks wrapping my "First Name" property.

### Steps to Reproduce

RuleFor(c => c.FirstName).Cascade(CascadeMode.Stop).NotNull().NotEmpty().WithMessage("First Name cannot be blank.");

**Comment by JeremySkinner** [comment]
`WithMessage` only applies to *the immediately preceding component* in the chain, meaning that you're changing the message for the `NotEmpty`, but you're *not* changing the message for the `NotNull`, so if you wanted the message to apply to both components, you must specify it twice.

```
RuleFor(c => c.FirstName)
  .Cascade(CascadeMode.Stop)
  .NotNull().WithMessage("First Name cannot be blank.");
   .NotEmpty().WithMessage("First Name cannot be blank.");
```

However, this is actually not necessary here, as `NotEmpty` will also perform a not-null check, so you can actually just remove the NotNull entirely

```
RuleFor(c => c.FirstName).NotEmpty().WithMessage("First Name cannot be blank.");
```

**Comment by Bond-Addict** [comment]
Ah okay. This is a code base I inherited so I wasn't sure. That makes total sense though. Thanks for the quick help!
