### ISSUE TITLE
Usage with the Mvvm.CommunityToolkit

### ISSUE THREAD

**Issue by mario-dg** [FluentValidation/FluentValidation#2267]
### Is your feature request related to a problem? Please describe.

How can I leverage the nice format of fluent validation with the comfort of source generators of the `Mvvm.CommunityToolkit`, especially the `ObservableValidator` for my WPF application?
The `ObservableValidator` already implements the INotifyDataErrorInfo interface and I just need to link my FluentValidation validation to it, but I just can't seem to find a way.

### Describe the solution you'd like

Anyone with any experience on this issue that can help?

**Comment by JeremySkinner** [comment]
I'm afraid this isn't something I can help as Mvvm.CommunityToolkit isn't something I have any experience with. 

Please note that this issue tracker is for bugs/feature requests for the core fluentvalidation library only, not for usage questions. You may be better off asking somewhere like stackoverflow.
