### ISSUE TITLE
DependentRules syntax 2

### ISSUE THREAD

**Issue by murshex** [FluentValidation/FluentValidation#2270]
You might want to consider closing issues rather than locking them to at least give the issue author a chance to reply... you never know, they might know something you don't, and you just lost your chance to hear what they have to say.

How about allowing syntax like:
```csharp
RuleFor(x => x.Email)
    .Cascasde(CascadeMode.Stop)
    .NotEmpty()
    .EmailAddress()
    .Cascade(CascadeMode.Continue) // Allow cascade mode to be switched mid-rule
    .Must(ExampleMethod1)
    .Must(ExampleMethod2);
```

P.S. I know this won't help persuade you on the syntax, but, I'll delete the issue template if I see fit :)

**Comment by JeremySkinner** [comment]
I locked the previous issue as 1) it didn't require further discussion as it was regarding something that was decided against 5 years ago and 2) you deleted the issue template.

Issue templates are in place to ensure that you don't waste the time of the maintainers and provide all necessary information that they've requested. Filling in the information requested by the maintainers is a common courtesy. 

The fact that you deleted the issue template again after I *specifically asked you not to* shows you have no respect for my time, so I will be locking this issue too, and you will no longer be able to open issues here.
