### ISSUE TITLE
ValidationResult to consider the Severity for the IsValid property

### ISSUE THREAD

**Issue by AndyCC25** [FluentValidation/FluentValidation#2272]
### Is your feature request related to a problem? Please describe.

One thing I notice while using this along with the https://github.com/ryanelian/FluentValidation.Blazor is that even when the validator has a severity as Warning, the result of the validation is still invalid, which makes sense but makes me thing what is the real use of the severity, what if the result of the validation consider the severity in each field and only consider the ones that are errors for the final result

### Describe the solution you'd like

Provide a way to set the warning for the severity so that the ValidationResult is true when all the failures are warning and only be not valid if there is one with error severity, so that in the client the message can be showed but is a warning and is not a stop

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but this isn't a change we'll be including. 

IsValid essentially means whether or not the validator produced failure instances.

The severity is just some extra/optional metadata for you to make use of if you choose to, but doesn't actually impact the behaviour of FluentValidation in any way.
