### ISSUE TITLE
Support composition-based validators

### ISSUE THREAD

**Issue by lirannl** [FluentValidation/FluentValidation#2273]
### Is your feature request related to a problem? Please describe.

When trying to migrate consuming applications/libraries from inheritance towards composition, one of the roadblocks is fluentvalidation, as creating new validators currently requires inheriting from AbstractValidator. 

### Describe the solution you'd like

A generic interface (such as IValidator<T>) could be added as another option for creating validators, which does not require inheritance.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion.

FluentValidation does support composition using the `Include` statement (https://docs.fluentvalidation.net/en/latest/including-rules.html). This allows you to break down validation logic into separate chunks and then compose them together, provided the validators all target the same type (or a compatible interface/base class). However, these composed validators must still inherit from AbstractValidator. 

FluentValidation has a specific way of doing things, and using AbstractValidator as a base class for configuring validators is a requirement that we won't be changing.

That being said, you could wrap your external class in a FluentValidation validator that calls `Custom` to delegate the actual work of validation to your external class.
