### ISSUE TITLE
PrecisionScale - Failing When Scale Value Is Greater Than 4

### ISSUE THREAD

**Issue by gift-musandiwa-absa-africa** [FluentValidation/FluentValidation#2277]
### FluentValidation version

11.10.0

### ASP.NET version

.NET 6

### Summary

'Amount' must not be more than 15 digits in total, with allowance for 7 decimals. 18 digits and 7 decimals were found.'

**RuleFor(x => x.Amount).PrecisionScale(15, 7, false);**
where x.Amount = 19999987299.70

It seems that the you are taking the length of the precision [x.Amount.ToString().Length]:**11** and adding the scale value:**7** then checking if the sum:**18** is greater than precision:**15**

### Steps to Reproduce

RuleFor(x => x.Amount).PrecisionScale(15, 7, false);

where x.Amount = 19999987299.70

**Comment by JeremySkinner** [comment]
hi @gift-musandiwa-absa-africa the validator is behaving correctly as the value 19999987299.70 can't fit in a decimal value defined as decimal(15, 7), however the error message is not very clear. 

Breaking it down:

A value defined as decimal(15, 7) means:
- Total number of digits both left and right of the decimal point must not exceed 15
- Number of digits to the right of the decimal point must not exceed 7
- The maximum number of digits to the left of the decimal point is 8 digits (15 total digits - 7 digits to store the scale, leaves only 8 digits for the integer) 
- The largest value permitted in a decimal(15,7) is `99999999.9999999` 

Our sample value (19999987299.70)
- 11 digits to the left of the decimal point
- 2 digits to the right of the decimal point

So although the total of 13 digits is within the allowed precision of 15, the integer number of digits (11) is larger than the maximum integer digits allowed in a decimal(15, 7), which is 8 (15 total - the 7 digits for scale), ie `19999987299.70` is larger than the maximum value allowed (`99999999.9999999`)

So is correct that the validator fails and generates an error.

However the message is misleading. What it's *trying* to say is you need a precision of 18 to store the value of `19999987299.70` (ie a decimal(18, 7) would be able to store this value). For legacy reasons, FluentValidation is constrained by the multilingual translations that we had in place for an earlier version. I'm not sure if there's a good solution for this, but hopefully it explains why the validator is failing (and why that's correct).

**Comment by JeremySkinner** [comment]
Pinging @nhowell @dropik I'd appreciate your input on this if you have some time, I know you've both worked on the ScalePrecisionValidator around this area as part of #2211, and probably understand it better than me. I'm not sure if there's really a good solution which wouldn't require re-translation of the error message into every language.

I'm wondering if maybe it'd be better to introduce a second message which is only generated in this situation (and could therefore be translated separately), but that's still a huge amount of work. Open to other ideas.
