### ISSUE TITLE
Provide some general guidance with regards to test coverage estimation

### ISSUE THREAD

**Issue by nulltoken** [FluentValidation/FluentValidation#2279]
### Is your feature request related to a problem? Please describe.

Using standard test coverage analysis approach with FluentValidation doesn't bring much value.

Indeed, provided the DI registration went well, all the declaration of the validators are reported as covered (which is good!), even if there are actually no test leveraging any of those validators (which is... maybe less good? :wink:).

When designing an API, we're given an OpenApi spec describing the expected contract to implement.
Then, in order to ensure the contract is properly implemented, we write some http based integration tests against an in-memory http instance.

Which is fine.

The problem with this approach is that the code review may become a bit complicated as there is no way (at least, *I haven't found any*) to ensure that all the test combinations have been written.

Exposing it differently: If, rather than using FluentValidation, I had written some if/then based validation, the potential missing tests would be easily spotted through the lack of branch coverage of those if/then clauses.

### Describe the solution you'd like

Ideally, I'd like some way to turn FluentValidation validators into some "have I been triggered?" mode, run the tests and then once all have run, being able to query FluentValidation and ask for the coverage of the possible validation combinations, considering all the registered validators.

I know this request may sound a tad wacky, but one could think of it as some kind of Valgrind-like **tooling to identify orphaned validation branches in deer need of some testing**.

We all want our APIs contracts to be correct, and we all want to make sure we're testing them thoroughly, don't we? :wink:

### Describe alternatives you've considered

~~Sadly, I've haven't found any :-/~~ 

Actually, I've found an alternative approach. Using Stryker.Net to detect mutant validators. Although that helps identifying those "not properly tested validation branches", that's kind of a heavyweight approach that doesn't scale well with a huge codebase.

Besides, the Stryker.Net feedback loop (for the sake of detecting those) is a bit long to my taste :-/

**Comment by JeremySkinner** [comment]
Hi, I'm afraid I can't really offer you much guidance here - it's really up to you to decide what makes most sense in the context of your own project.

Personally when it comes to FluentValidation, my usual approach is to use a basic red-green testing approach: write tests that exercise the rules I expect to happen, ensure that they fail, then write the rules and ensure that they pass. I treat the validator as black boxes that I test in isolation. Even if you've got integration tests that cover your endpoints I'd personally still have dedicated tests for the validators themselves. 

I'll also point out that I've seen a lot of people decide to use FluentValidation when it isn't really appropriate or necessary and they end up with unnecessarily complex/overkill solutions. If an "if/then based" validation approach makes more sense in your scenario, then I'd strongly suggest using that instead. Don't try and shoehorn FluentValidation into a solution if it's not working for you. 

> I'd like some way to turn FluentValidation validators into some "have I been triggered?" mode

I'm afraid this is outside the scope of the project so isn't something that I'll be including

Sorry I can't really offer any guiance beyond this.

**Comment by nulltoken** [comment]
@JeremySkinner Thanks a lot for the answer.

>I'd personally still have dedicated tests for the validators themselves.

Even in that context, I believe the question still stands. How can one ensure no validator has been overlooked?

>Personally when it comes to FluentValidation, my usual approach is to use a basic red-green testing approach: write tests that exercise the rules I expect to happen, ensure that they fail, then write the rules and ensure that they pass.

That makes a lot of sense. This approach works indeed pretty well with dedicated and self-reliant developers. However, from a reviewer standpoint how would you ensure all validators have been tested to their fullest extent?

>Don't try and shoehorn FluentValidation into a solution if it's not working for you.

The if/then approach works. However, it's a long road. FluentValidation comes with a lot of useful helpers and makes the code a lot more terse. I wasn't trying to "shoehorn" the lib, but rather leverage its heavily tested and validation domain oriented approach in a way that would put most of the burden of the reviewers' shoulders.

>I'm afraid this is outside the scope of the project so isn't something that I'll be including

Thanks again for the time you took to consider this request.
