### ISSUE TITLE
add fluentValidation in client project break webassembly app when reference also skiaSharp

### ISSUE THREAD

**Issue by julienGrd** [FluentValidation/FluentValidation#2281]
### FluentValidation version

11.11

### ASP.NET version

.NET9.0

### Summary

I have a blazor webassembly which reference many libraries, including fluent validation.

I use another library which ask me to add these lines in the csproj of my client project 
````
 <ItemGroup>
   <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\st\*.a" />
 </ItemGroup>
 <PropertyGroup>
   <WasmNativeStrip>true</WasmNativeStrip>
   <WasmBuildNative>true</WasmBuildNative>
 </PropertyGroup>

    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Syncfusion.Blazor.SfPdfViewer" Version="27.2.4" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="27.2.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.8" />
````
documentation of the library :
https://blazor.syncfusion.com/documentation/pdfviewer-2/getting-started/web-assembly-application?_gl=1*1xhyz87*_gcl_au*ODg4MTY2ODUzLjE3MzI2NTY1MDU.*_ga*OTQ1MTgyMzExLjE3MzI2NTQzMTA.*_ga_41J4HFMX1J*MTczMjcyMjI1MC42LjEuMTczMjcyNDkwMS4wLjAuMA..#add-the-following-propertygroup-and-itemgroup

If i run a webassembly app just with that, everything work fine

But if i add fluent validation package, the webassembly app can't load with these errors in chrome console

blazor.web.js:1 Aborted(Assertion failed: native function `mono_wasm_send_dbg_command` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits))

### Steps to Reproduce

just checkout this project https://github.com/julienGrd/BlazorTestPdfViewerNextGen and run the app

**Comment by JeremySkinner** [comment]
That's very strange. This doesn't sound like an issue with FluentValidation. I'd suggest you troubleshoot by stripping out everything except FluentValidation. If FluentValidation is the only library present does the issue still occur?

**Comment by julienGrd** [comment]
Yes im agree its very strange.
anyway if i put the library <PackageReference Include="FluentValidation" Version="11.11.0" />, it stoppend working, if i remove it work again.

so "something" happen

> If FluentValidation is the only library present does the issue still occur?
No, its really something which add relation to this line abive because when i remove it it work again (but my component stop working so its not the idea)
 <ItemGroup>
   <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\st\*.a" />
 </ItemGroup>

I actually have  workaround solution by syncfusion which resolve the error even with FluentValidation referenced. (but i fall on another problem with their workaround)

I let this issue open a bit in case you have other ideas

**Comment by julienGrd** [comment]
yes i was expected that, i honestly expect a full workaround by them and not by your library, it was more for understand.

The workaround is described here : https://help.syncfusion.com/document-processing/faq/how-to-fix-skiasharp-native-reference-issue-in-blazor-net90-app
remove  <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.8" />
add <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.8" />
add these line in the client project
<Target Name="RuntimeIssue109289_Workaround" AfterTargets="_BrowserWasmWriteRspForLinking">
    <ItemGroup>
      <_WasmLinkStepArgs Remove="@(_EmccLinkStepArgs)" />
      <_EmccLinkStepArgs Remove="&quot;%(_WasmNativeFileForLinking.Identity)&quot;" />
      <_WasmLinkDependencies Remove="@(_WasmNativeFileForLinking)" />
      <_SkiaSharpToReorder Include="@(_WasmNativeFileForLinking)" Condition="$([System.String]::Copy('%(FullPath)').Contains('libSkiaSharp.a'))" />
      <_WasmNativeFileForLinking Remove="@(_SkiaSharpToReorder)" />
      <_WasmNativeFileForLinking Include="@(_SkiaSharpToReorder)" />
      <_EmccLinkStepArgs Include="&quot;%(_WasmNativeFileForLinking.Identity)&quot;" />
      <_WasmLinkDependencies Include="@(_WasmNativeFileForLinking)" />
      <_WasmLinkStepArgs Include="@(_EmccLinkStepArgs)" />
    </ItemGroup>
  </Target>

**Comment by JeremySkinner** [comment]
Thanks for documenting the workaround. I'll go ahead and close this as there's no action required from our end.
