### ISSUE TITLE
Validatable commands

### ISSUE THREAD

**Issue by ygarciadiaz** [FluentValidation/FluentValidation#2282]
### Is your feature request related to a problem? Please describe.

Commands are usually bind by the API model binding. Commands usually use the framework attributes to validate the fields. Can there be a self validatable option.

### Describe the solution you'd like

CreateCustomer : AbstractValidator<CreateCustomer>

Currently this can be done. The issue is that AbstractValidator public properties are being serialized. 
Can abstract public properties be marked with ignore?

Should a different AbstractSelfValidatable<T> be created? to write code as createCustomer.Validate().

CreateCustomer constructor has the validation rules.

**Comment by JeremySkinner** [comment]
No, sorry, this is out of scope for the project. Validators are intentionally separate from the classes being validated.

If you want your commands to have a Validate method, then internally this could instantiate and invoke a separate validator class, but your commands shouldn't inherit from AbstractValidator directly.
