### ISSUE TITLE
DependentRules commited even they should not to

### ISSUE THREAD

**Issue by retegate** [FluentValidation/FluentValidation#2284]
### FluentValidation version

11.11.0

### Summary

Hi, I am trying to write my own extensions of the FluentValidation (hopefully I will be able to send them to you, co include within FluentValidation basic package or publish them as an extension). But I found maybe an issue. I thought the DependentRules should run only when precedent rules are met. So I made simple example bellow (I use Rider upon mac).

### Steps to Reproduce

Just make a simple console app and make it look like a following and that is it. The dependent rules are hit even ith the must condition is met.

```
using FluentValidation;

var testValidator = new TestValidator();
testValidator.ValidateAndThrow(" ");

public class TestValidator : AbstractValidator<string>
{
    public TestValidator()
    {
        RuleFor(x => x)
            .Cascade(CascadeMode.Stop)
            .Must(x => !string.IsNullOrWhiteSpace(x))
            .WithMessage("Cannot be empty or whitespace string.")
            .DependentRules(() =>
            {
                RuleFor(x => x)
                    .Must(x => x.All(char.IsLetterOrDigit));
            });
    }
}
```

**Comment by retegate** [comment]
Uf, thank you, but I need to investigate what is wrong on my side then, because 
<img width="919" alt="image" src="https://github.com/user-attachments/assets/b1b54408-c84f-45cd-9bbc-228b7f978bfc" />

**Comment by JeremySkinner** [comment]
@retegate pleas re-read my comment above:

> Note that the dependent rule will always be created regardless of the first rule (ie putting a breakpoint inside the DependentRules callback will always be hit), but the rule will only be executed if the first one fails.
