### ISSUE TITLE
.NotNull() Validator to return IRuleBuilderOptions<T, TElement>

### ISSUE THREAD

**Issue by wadeamaral** [FluentValidation/FluentValidation#2287]
### FluentValidation version

11.3

### ASP.NET version

.NET 9

### Summary

Is it possible for the `.NotNull()` validator to return an `IRuleBuilderOptions<T, TElement>` instead of `IRuleBuilderOptions<T, TElement?>`? The reason is I am getting a possible null reference exception when using the `.SetValidator` method on a property to be validated even though I am first declaring it should be `.NotNull()`.

I have a few cases of this so my thought was to create my own extension method. What I have so far is:

```
public static IRuleBuilderOptions<T, TElement?> SetNotNullValidator<T, TElement>(this IRuleBuilder<T, TElement?> ruleBuilder, IValidator<TElement> validator)
{
    #pragma warning disable CS8620
    return ruleBuilder.NotNull().SetValidator(validator);
    #pragma warning restore CS8620
}
```

However this seems more like a workaround by just disabling the compiler warnings.

### Steps to Reproduce

```
public class SomethingToValidate
{
    public SomethingElseToValidate? SomethingElse { get; set; }
}

public class SomethingElseToValidate
{
    public int? SomeNumber { get; set; }
    public string? SomeString { get; set; }
}

public class SomethingToValidateValidator : AbstractValidator<SomethingToValidate>
{
    public SomethingToValidateValidator()
    {
        RuleFor(x => x.SomethingElse).NotNull().SetValidator(new SomethingElseToValidateValidator()); // Possible null reference here
    }
}

public class SomethingElseToValidateValidator : AbstractValidator<SomethingElseToValidate>
{
    public SomethingElseToValidateValidator()
    {
        RuleFor(x => x.SomeNumber).NotEmpty().GreaterThan(0);
        RuleFor(x => x.SomeString).NotEmpty();
    }
}
```

**Comment by wadeamaral** [comment]
After digging around it looks like this is similar to #1649

**Comment by JeremySkinner** [comment]
No, this isn't possible. I spoke about this here: https://github.com/FluentValidation/FluentValidation/issues/2271#issuecomment-2431597057

The `SetNotNullValidator` wrapper method is the only solution.
