### ISSUE TITLE
Multiple Validation

### ISSUE THREAD

**Issue by pmareke** [FluentValidation/FluentValidation#758]
In the Startup.cs you register only the Customer Validator:

```            
services
  .AddMvc()
  // Adds fluent validators to Asp.net
  .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CustomerValidator>());
```

But in the application the objects Sample, BasicGetRequest and Dependencies have the validation in Swagger too, how is it possible?

Sorry if I'm missing something but I can't see when you tell the app to inject them.

Great work!

**Comment by JeremySkinner** [comment]
Hi, I don't really understand your question.

Calling `RegisterValidatorsFromAssemblyContaining<CustomerValidator>` doesn't just register CustomerValidator it registers _all validators that reside in the same assembly_ as CustomerValidator (the method name is pretty clear). So all validators are automatically registered.

If you need to register other services, just register them with MVC's `services` collection directly. [You can read about that on the official docs. ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.0)

**Comment by pmareke** [comment]
Thanks Jeremy, it's just what I meant...sorry for my English.

At the beggining I was thinking that the assembly was the assembly of the CustomerValidator itself not the "app" assembly.

Thanks so much for your time.
