### ISSUE TITLE
ShouldHaveValidationErrorFor and ShouldNotHaveValidationErrorFor needs identity overload

### ISSUE THREAD

**Issue by jzabroski** [FluentValidation/FluentValidation#910]
This won't compile in C#:

```csharp
// Mock.Of refers to Moq
validator.ShouldNotHaveValidationErrorFor<Model, Model>(
                m => m,
                Mock.Of<Model>,
                "Create,CreateOrUpdate");
```

generates compile error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'ValidationTestExtension.ShouldHaveValidationErrorFor<T, TValue>(IValidator<T>, Expression<Func<T, TValue>>, TValue, string)' and 'ValidationTestExtension.ShouldHaveValidationErrorFor<T, TValue>(IValidator<T>, Expression<Func<T, TValue>>, T, string)'	Tests	C:\source\ModelValidatorTests.cs	86	Active
```
I believe we need an overload to express the Identity function relationship:
```csharp
    public static class ValidationTestExtension
    {
        public static IEnumerable<ValidationFailure> ShouldHaveValidationErrorFor<T>(this IValidator<T> validator, Expression<Func<T, T>> expression, T value, string ruleSet)
            where T : class, new()
        {
            T instance = Activator.CreateInstance<T>();
            return validator.TestValidate<T>(instance, ruleSet).ShouldHaveError<T, T>();
        }
    }
```
This is useful when writing validations that involve multiple properties.

**Comment by JeremySkinner** [comment]
That overload of ShouldHaveValidationErrorFor is designed to set the property value, which you don’t need to do in this case. You should be using the overload which already takes a prepopulated model instance in this case.

**Comment by jzabroski** [comment]
Is there a unit test that proves this will compile?  If not, I'll submit a patch to write one so we can see exactly if I'm right or wrong.

**Comment by JeremySkinner** [comment]
I’m not sure I understand. Yes this doesn’t compile but that doesn’t matter as you can use the other overload of the method that takes the prepopulated model - you don’t need to use the one that takes an expression. I don’t think there needs to be a patch for this.

**Comment by jzabroski** [comment]
When *T* and *TValue* are the same, C# Compiler *cannot* know which generic method to select. This *only* happens if the validation expression is the identify funciton.
Compare these two signatures:
```csharp
    public static IEnumerable<ValidationFailure> ShouldHaveValidationErrorFor<T, TValue>(this IValidator<T> validator, Expression<Func<T, TValue>> expression, TValue value, string ruleSet = null) where T : class, new()
    public static IEnumerable<ValidationFailure> ShouldHaveValidationErrorFor<T, TValue>(this IValidator<T> validator, Expression<Func<T, TValue>> expression, T objectToTest, string ruleSet = null) where T : class
```
How will C# know if Model is T objectToTest or TValue value?

**Comment by jzabroski** [comment]
...That's basically what I am doing, but it's not as convenient as having it as part of the library:

```csharp
    public static class ValidationTestExtension
    {
        public static IEnumerable<ValidationFailure> ShouldHaveValidationErrorFor<T>(this IValidator<T> validator, Expression<Func<T, T>> expression, T value, string ruleSet)
            where T : class, new()
        {
            T instance = Activator.CreateInstance<T>();
            return validator.TestValidate<T>(instance, ruleSet).ShouldHaveError<T, T>();
        }
    }
```
usage:
```csharp
var results = validator.ShouldHaveValidationErrorFor(m => m,
                mockDuplicate,
                "Create,CreateOrUpdate");
            Assert.True(results.Any());
```

**Comment by JeremySkinner** [comment]
Thanks, yes if you want to submit a pull request then I’ll try and get t meted in soon (I’m probably not going to get a chance to work on FluentValidation for a few weeks)

**Comment by jzabroski** [comment]
Thank you.

**Comment by jzabroski** [comment]
I've updated the extensions above to add two more overloads. It occurred to me that the code I was specializing was ignoring the value property, and both an overload for that and an overload that creates a default instance would make sense.

However, #912 made me realize there may need to be a more generic way to set multiple properties.  I'll refrain from submitting a patch for this issue until #912 has a clear solution

**Comment by JeremySkinner** [comment]
Thanks for this. A couple of small changes I'd suggest:

- For the overloads that take a `T value`, you should remove the `new()` constraint from the method so models without parameterless constructors can be passed in.
- For the overloads that don't take a `T value`, the `new()` constraint means you can say `var instance = new T()`; rather than using `Activator.CreateInstance`.

**Comment by JulidaRocks** [comment]
when will these adaptions be available?

**Comment by JeremySkinner** [comment]
Currently awaiting @jzabroski (or someone else) to submit a pull request with appropriate tests. Once that's done and reviewed it can go into the next release.

**Comment by duzenko** [comment]
Do we need expression at all here?
How about this:

```
ShouldHaveValidationErrorFor<T>(this IValidator<T> validator, T objectToTest, string ruleSet = null) where T : class
...
validator.ShouldNotHaveValidationErrorFor<Master>(Mock.Of<Model>, "Create,CreateOrUpdate" );

```

**Comment by JeremySkinner** [comment]
Technically no, an expression isn’t needed but I’d prefer it as it helps with clarity and is consistent with the other overloads.

**Comment by JeremySkinner** [comment]
Re-opening as this was closed by mistake and hasn't yet been implemented

**Comment by jzabroski** [comment]
> Do we need an expression at all here?
> How about this:
> 
> ```
> ShouldHaveValidationErrorFor<T>(this IValidator<T> validator, T objectToTest, string ruleSet = null) where T : class
> ...
> validator.ShouldNotHaveValidationErrorFor<Master>(Mock.Of<Model>, "Create,CreateOrUpdate" );
> ```

Master and Model are not the same type, so you are literally not testing the scenario that causes a compiler error.

I'll try to submit a PR soon; I got sidetracked when I rolled off the project where I was working with FluentValidator.  I still want to contribute this fix as it would be helpful to others.

**Comment by JeremySkinner** [comment]
This didn't make it into the 8.2 release as it's still awaiting a PR. Not planning on any more 8.x releases except for emergency hotfixes. Retargetting for 9.x.

**Comment by jzabroski** [comment]
OK, I'll try to prioritize this for you, as I feel you've been especially helpful towards me, I'd like to contribute and make your life better.

**Comment by jzabroski** [comment]
I got halfway done with this and got dumped with a ton of work.  I'll try to push my progress upstream next week - hopefully with everything done but we're upgrading to VS2019 this week too so we'll see.

**Comment by mehdikhaleghian** [comment]
Hi @jzabroski how far are you with this feature. I might be able to help

**Comment by jzabroski** [comment]
I just need to wrap up the tests. I wrote two tess. I can push what i have
tomorrow morning to my fork.

**Comment by jzabroski** [comment]
@mehdikhaleghian I just pushed what I had to https://github.com/jzabroski/fluentvalidation - sorry I am so scatterbrained and have not finished this up.  

The latest build.ps1 checked in from Jeremy's master branch is throwing an exception, FYI.

```
target : Method invocation failed because [System.String] does not contain a method named 'ContainsKey'.
At D:\source\GitHub\FluentValidation\build.ps1:25 char:1
+ target default -depends compile, test, deploy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [target], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,target
```

**Comment by JeremySkinner** [comment]
@jzabroski delete the .build directory and the error will go away.

**Comment by JeremySkinner** [comment]
If you can create a pull request then I'll give this a proper review, but from a quick glance there are a couple of minor changes:

- [ ] incorporate changes from earlier in the thread https://github.com/JeremySkinner/FluentValidation/issues/910#issuecomment-426206547
- [ ] formatting should be consistent with the rest of the project (brace layout; indentation)

**Comment by jzabroski** [comment]
- It needs test cases.  I probably need one solid hour to complete it, but I've married into a culture where they have three wedding ceremonies (family introductions, family approval, then a white wedding) and the last 7 months has been hectic.
- Sorry about the formatting.

**Comment by mehdikhaleghian** [comment]
@jzabroski cannot work on this atm

**Comment by jzabroski** [comment]
@JeremySkinner I thought about picking this back up, but can you tell me what happened to the ShouldHaveError extension method?

**Comment by JeremySkinner** [comment]
@jzabroski with 9.0 much of the test helper was refactored to remove a lot of the duplication. Everything now runs through the `TestValidate` logic internally.

**Comment by JeremySkinner** [comment]
Closing this as `TestValidate` has support for this, and is the recommended approach for tests going forward.

```csharp
var testResult = validator.TestValidate();
testResult.ShouldHaveValidationErrorFor(x => x);
//or 
```

**Comment by jzabroski** [comment]
Interesting.  Was this something you added after I closed the PR, or something you just realized?  Thanks again.

**Comment by JeremySkinner** [comment]
Apparently I added it in 8.5, which was in September last year! 🤷‍♂️

**Comment by jzabroski** [comment]
Awesome, thank you so much.  Will clean up my own code.
