### ISSUE TITLE
FluentValidation 9.0 - list of breaking changes 

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#981]
This is a working list of the expected breaking changes in 9.0:

- [x] Generic type parameters added to a couple of places (ChildValidatorAdaptor, IncludeRule) 
- [x] Remove support for netstandard1.1 and netstandard1.6  
- [x] Instead of net45 will support net461 as the new minimum
- [x] Drop support for MVC5 and WebApi 2. These will continue to receive critical fixes for 8.x only. 
- [x] Remove `SetCollectionValidator`, which was deprecated with 8.0 (`RuleForEach` is the alternative) 
- [x] Remove `ReplacePlaceholderWithValue` and `GetPlaceholder` from `MessageFormatter`
- [x] Remove `WithLocalizedMessage` and `LocalizedStringSource`. Using the overload of `WithMessage` that takes a func can cover the use case of needing to work with strongly-typed resource wrappers. 
- [x] `ResourceName` and `ResourceType` will be removed from IStringSource. 
- [x] `ResourceName` removed from `ValidationFailure`. 
- [x] Removed `PropertyValidatorContext.Instance` - use `PropertyValidatorContext.InstanceToValidate` instead. 
- [x] DelegatingValidator removed. 
- [x] Email validation mode: defualt changed from regex, to asp.net core compatible. 
- [x] Syntax changes for advanced test helper (#1148)
- [x] Severity changes (#1152) 
- [x] ComparisonProperty formatting (#1204)
- [x] Rename `ShouldValidateAsync` (#1279) 
- [x] Equal/Notequal now do ordinal comparisons for strings (#1301) 
- [x] Do not attempt to automatically infer property names from the presence of `DisplayNameAttribute` or `DisplayAttribute`, as this no longer works properly with the way asp.net core handles localization. If you really want this behaviour back, add the following to startup:
```csharp
ValidatorOptions.DisplayNameResolver = (type, memberInfo, expression) => {
	return memberInfo.GetCustomAttribute<System.ComponentModel.DataAnnotations.DisplayAttribute>()?.GetName();
};
```

**Comment by JeremySkinner** [comment]
The following will probably now not make it into 9.0:

- Consider making "sql server compatible mode" the default for the ScalePrecisionValidator (#1008). This issue appears to have been abandoned. With no community buy in I'm not inclined to do any further work on this validator. 

- Splitting out async/sync workflow (#1063) This still requires a huge amount of work. Revisit the feasibility for 10.0

**Comment by JeremySkinner** [comment]
Published the 9.0 upgrade guide https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html

**Comment by cjlotz** [comment]
Hi Jeremy - thanks for the awesome library and efforts in keeping it current and evolving with the .NET landscape.  Just a quick question around the dropping of `DelegatingValidator`.  I had a look at the migration guide but don't see any recommendations for migrating away from the use of it.  Any pointers/alternatives as we are currently making use of it.  Thx

**Comment by JeremySkinner** [comment]
Hi @cjlotz every validator now has an associated condition property (accessed via propertyValidator.Options.Condition or AsyncCondition). Calls to `When` now set this directly rather than wrap the validator in a DelegatingValidator.

If you’re making use of DelegatingValidator by using When/Unless then there is no migration necessary. If you’re instantiating it manually, then could you provide more details of your use case?

**Comment by cjlotz** [comment]
@JeremySkinner  

We have a custom rule expression language that we use as conditions/predicates on validation rules associated with properties on models.  Here's an example snippet from a validator class illustrating the predicate usage:

```c#
private static CriteriaExpression IsCancelledOrClosed { get; } =
     new CriteriaExpression($"Alarm->Status EQ '{nameof(AlarmStatus.CancelledByUser)}' OR " +
                             $"Alarm->Status EQ '{nameof(AlarmStatus.CancelledBySystem)}' OR " +
                             $"Alarm->Status EQ '{nameof(AlarmStatus.Closed)}'");
 
RuleFor(x => x.Notes).IsReadOnly().WhenExpr(IsCancelledOrClosed)
```

Behind the scenes the `WhenExpr` extension method is defined as:

```c#
        public static IRuleBuilderOptions<T, TProperty> WhenExpr<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, CriteriaExpression predicate, ApplyConditionTo applyConditionTo = ApplyConditionTo.AllValidators)
        {
            return rule.Configure(config =>
            {
                PropertyRule propertyRule = config;
                int num = (int) applyConditionTo;                
                propertyRule.ApplyCondition(predicate, (ApplyConditionTo) num);
            });
        }

        private static void ApplyCondition(this PropertyRule rule, CriteriaExpression predicate, ApplyConditionTo applyConditionTo = ApplyConditionTo.AllValidators)
        {
            if (applyConditionTo == ApplyConditionTo.AllValidators)
            {
                foreach (IPropertyValidator propertyValidator in rule.Validators.ToList())
                {
                    var criteriaValidator = new CriteriaExpressionValidator(predicate, propertyValidator);
                    rule.ReplaceValidator(propertyValidator, criteriaValidator);
                }

                foreach (var validationRule in rule.DependentRules.OfType<PropertyRule>().ToList())
                {
                    validationRule.ApplyCondition(predicate, applyConditionTo);
                }
            }
            else
            {
                var criteriaValidator = new CriteriaExpressionValidator(predicate, rule.CurrentValidator);
                rule.ReplaceValidator(rule.CurrentValidator, criteriaValidator);
            }
        }
```

You'll notice that we create a wrapping `CriteriaExpressionValidator` based on the `DelegatingValidator` to allow us to first evaluate the predicate and, if `true`, delegate to the execution of the actual validator as shown below:

```c#
    public class CriteriaExpressionValidator : DelegatingValidator
    {
        public CriteriaExpressionValidator(CriteriaExpression predicate, IPropertyValidator innerValidator)
            : base(ctx =>
            {
                if (predicate.ShouldExecute(ctx))
                    return predicate.Evaluate(ctx.Instance);

                return false;                
            }, innerValidator)
        {
            Predicate = predicate;
        }

        public CriteriaExpression Predicate { get; }
    }
```
I realise this is a quite specialized usage scenario, but the flexibility allows us to use FluentValidation in combination with our rule expression language.

**Comment by cjlotz** [comment]
Other areas where we use the flexibility afforded by `DelegatingValidator` is also to specify when specific rules should/should not execute based on the current stack of requests (we call them `IOperationSteps`) for the current request/operation being executed in the system.  

```c#
    public class InOperationValidator : DelegatingValidator
    {
        private readonly IOperationStep[] _steps;
        
        public InOperationValidator(IOperationStep[] steps, IPropertyValidator innerValidator)
            : base(ctx =>
            {
                IOperationContext context = ctx.ParentContext.GetOperationContext();
                return context.InOneOfOperations(steps);
            }, innerValidator)
        {
            _steps = steps;
        }
        public IEnumerable<IOperationStep> Steps => _steps;
    }
```
This allows us to specify rules like the following:

```c#
RuleFor(x => x.Id).GreaterThanOrEqualTo(0).WhenNotInOperation(SyncOperations.SaveSyncContainer)
```

**Comment by JeremySkinner** [comment]
@cjlotz  so you'll need to change your implementating to not be based on the `DelegatingValidator`, and instead switch to using FluentValidation's condition API, which is done by passing a `Func<PropertyValidatorContext, bool>` to ApplyConditon that does the work that you'd previously be doing inside the DelegatingValidator. 

```csharp
// Step 1: WhenExpr. This can now simply define a Func<PropertyValidatorContext, bool> that evaluatuates your CriteriaExpression, and then pass the func directly to FluentValidation's propertyRule.ApplyCondition method. Your ApplyCondition method can be removed completely.

public static IRuleBuilderOptions<T, TProperty> WhenExpr<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, CriteriaExpression predicate, ApplyConditionTo applyConditionTo = ApplyConditionTo.AllValidators)
{
	var predicateFunc = new Func<PropertyValidatorContext, bool>(ctx => {
		if (predicate.ShouldExecute(ctx))
			return predicate.Evaluate(ctx.InstanceToValidate);

		return false;
	});

	return rule.Configure(propertyRule => {
		propertyRule.ApplyCondition(predicateFunc, applyConditionTo);
	});
}

// Step 2, your WhenNotInOperation validator can be implemented in a similar way by defining a function that does the work, which you then pass to ApplyCondition:
public static IRuleBuilderOptions<T, TProperty> WhenNotInOperation<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, params IOperationStep[] steps) {
	var predicateFunc = new Func<PropertyValidatorContext, bool>(ctx => {
		IOperationContext context = ctx.ParentContext.GetOperationContext();
		return context.InOneOfOperations(steps);
	});

	return rule.Configure(propertyRule => propertyRule.ApplyCondition(predicateFunc));
}
```

Hopefully that illustrates what you'll need to do to port to 9.0. Note that FluentValidation 8.x switched internally from using DelegatingValidator to the conditon API a while back, so you can switch over to this today without needing to wait for 9.0.  

Of course, the other option is that you could copy the `DelegatingValidator` from the 8.x source code into your own project if you want to keep using it ([source](https://github.com/FluentValidation/FluentValidation/blob/8.x/src/FluentValidation/Validators/DelegatingValidator.cs)), but I would highly recommend moving over to the condition API instead. 

If you have any further questions, could you open a separate issue? Thanks.
